### ISSUE TITLE
Cloaks Can Do Things

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#100]
**Describe the bug**
I stole the janitor's cloaking device and found a couple things that it probably shouldn't be able to let you do.

> You can clickdrag-pickup items from adjacent tiles without disrupting your cloak.

> You can do that special attack thing with bare hands without disrupting your cloak.

**To Reproduce**
1. Get cloak
2. Do the things
3. Remain invisible
4. Bug report

**Expected behavior**
Cloak stop cloaking.

**Screenshots**
[x]

**Additional context**
I was in the chapel again.

**Comment by iod6239** [comment]
I don't know if these are bugs as well, but I should mention a couple more things you can do while cloaked, in case they are:

You can use the P hotkey to pick up nearby items without disrupting the cloak.

You can throw items.

**Comment by ZeWaka** [comment]
these mentioned procs aren't calling the disrupt_cloak() proc or similarly named
