### ISSUE TITLE
Ghost drones can't go through thindow doors

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#10011]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Be a ghost drone
2. Find a thindow door, like the ones at the cog1 operating room
3. Try to go through them
4. Can't

### Expected Behavior

To be able to go through thindow doors as a ghost drone.

**Comment by nefarious6th** [comment]
duplicate of #8306

**Comment by ThatFiveGuys** [comment]
Closing due to duplicate
