### ISSUE TITLE
Clicking an empty taser rack with an empty hand causes a runtime

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#10013]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Walk up to a taser rack.
2. Touch it with your bare hands.
3. Runtime.

### Expected Behavior

To not runtime.

**Comment by BatElite** [comment]
(Specifically it's) https://github.com/goonstation/goonstation/blob/5b0081af1a82f38397bd9c90d2ff90975811dcb7/code/obj/machinery/weapon_racks.dm#L236-L238

That sure is code
