### ISSUE TITLE
Ghost drones can spray they're flashlight toggle icons.

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#10020]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Be a ghost drone
2. Pull out your flashlight
3. Switch to your spray bottle without storing your flashlight
4. Click the flashligh toggle icon
5. Spray a UI element

### Expected Behavior

To not be able to spray my UI

**Comment by UrsulaMejor** [comment]
verified still happens in 2023
