### ISSUE TITLE
The major random event cycle can pick nonexistent events

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#10024]
### Labels

[BUG]

### Description

The list for major random events includes a couple of non-functional parent types

### Steps to reproduce

For a loose definition of "reproduce" anyway, but here's how to see what I'm talking about without waiting on random rolls for a while:

1. open the game panel and then the random event controller under coder tools (not the random event controls under admin tools)
2. scrolls down to the events variable
3. Observe `datum/random_event_major/antag` and `datum/random_event_major/player_spawn` are in there

### Expected Behavior

No blank events being eligible

### Additional Information & Screenshots

This has probably lead to a significant amount (ratio 2/17) of major random event rolls not doing anything,

**Comment by UrsulaMejor** [comment]
unable to replicate; probably fixed?

**Comment by pali6** [comment]
fixed by 767b2c3b4895b714c0b312a6af8eefe62d8dad61
