### ISSUE TITLE
Players antagified through the new antag system don't have an antag icon

### ISSUE THREAD

**Issue by flrsh** [goonstation/goonstation#10033]
### Labels

[BUG]

### Description

Players antagified through the new antag system don't have an antag icon

### Steps to reproduce

1. Be an admin
2. Antagify a player through `Add Antagonist Role (New system, WIP)`
3. Observe the player
4. Notice that they don't have an antag icon 

### Expected Behavior

I expect them to have their appropriate antag icon 

### Additional Information & Screenshots

Related to #9771

Related to #9966 and #9762

**Comment by flrsh** [comment]
@Ilysen

**Comment by Ilysen** [comment]
This is surprising, actually. Antag HUD icons are tied to mind special role, I believe, which is unaffected. Do you know if this applies to roundstart/natural antagonist roles, or just to adminified ones?

**Comment by flrsh** [comment]
Just adminified ones, roundstart ones seem fine. Their `mind.special_role` seems to be set correctly.

**Comment by Ilysen** [comment]
Found the cause; they're not in `ticker.mode.traitors` or `ticker.mode.Agimmicks`; easy fix.
