### ISSUE TITLE
Traitor role in player panel is in black text instead of red

### ISSUE THREAD

**Issue by flrsh** [goonstation/goonstation#10032]
### Labels

[TRIVIAL]

### Description

Traitor role in player panel is in black text instead of red

### Steps to reproduce

1. Be an admin
2. Look at traitor's player panel
3. Notice that their traitor role is in black text instead of red 

![image](https://user-images.githubusercontent.com/59894319/182441659-2df2882b-aa53-4b93-a46e-77c37b70e2f4.png)

### Expected Behavior

I expect the text to be red as usual

### Additional Information & Screenshots

Related to #9966

This also applies to any other antag roles that are added through the new system

**Comment by flrsh** [comment]
@Ilysen

**Comment by Ilysen** [comment]
I remember doing this for a reason, but I'm not sure what. It was mostly a readability thing; would y'all prefer it being red?

**Comment by flrsh** [comment]
I would prefer it being red, not sure about others.
