### ISSUE TITLE
Removing an antag role that was added through the new antag system doesn't remove its corresponding objectives

### ISSUE THREAD

**Issue by flrsh** [goonstation/goonstation#10034]
### Labels

[MINOR]

### Description

Removing an antag role that was added through the new antag system doesn't remove its corresponding objectives

### Steps to reproduce

1. Be an admin
2. Antagify a player through `Add Antagonist Role (New system, WIP)`
3. Remove their antag role through `Remove`
4. Notice that they still keep their antag objectives

### Expected Behavior

I expect their antag objectives to be removed with their antag role

### Additional Information & Screenshots

Related to #9966 and #9762

**Comment by flrsh** [comment]
@Ilysen

**Comment by Ilysen** [comment]
I'll look into this.

**Comment by Ilysen** [comment]
Peeking around at the code for objectives, this might be a bit more involved than it'd seem; current antagonist tools for admins don't feature this functionality either, as I recall. It's 100% something I wanna do, but it might come after the latest fix batch.
