### ISSUE TITLE
I gibbed so hard, the AI watching me died.

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#10052]
### Labels

[BUG]

### Description

As a fire elemental, I got spaced into a wall so fast I gibbed, and apparantly took the AI with me

### Steps to reproduce

1. Be a fire elemental
2. Have an AI watch you
3. Be spaced really fast into a wall
4. Die, and take the AI with you.

### Expected Behavior

To not kill the AI watching me when I die.

### Additional Information & Screenshots

Not sure if changing z levels then immediatly gibbing into a wall has any relation to it.

**Comment by amylizzle** [comment]
Goddammit, I thought I fixed that.

**Comment by amylizzle** [comment]
Can you give some more details on this? I'm not able to replicate at all and I can't see why it would happen either.

Mostly, how did the AI observe you off the station Z? That shouldn't be possible at all. And slamming into a wall just calls `.gib()` which works normally while an AI is observing. I am confused D:

**Comment by Wisemonster** [comment]
I'm not really sure how the AI was able to observe me off station, although I did gib almost immediatly after changing z-levels. I'm not sure what the AI was doing specifically at the time, but I was stunned and holding a keybind for the flamethrower ability when it happened.

**Comment by UrsulaMejor** [comment]
Unable to be reproduced, stepping through doesn't seem to indicate how or why this would happen
