### ISSUE TITLE
Spawning as a latejoin traitor with no uplink

### ISSUE THREAD

**Issue by Rmille19bing** [goonstation/goonstation#10054]
### Labels

[BUG]

### Description

Latejoin traitor getting no uplink code

### Steps to reproduce

1. Join the game as a latejoin traitor (potentially as a nonstandard latejoin role, I think both times this happened to me it was with specific latejoin roles).
2. Not have any uplink code, but do have 2 copies of my objectives in the chat

### Expected Behavior

I expected to have an uplink code, either radio or pda

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/90483401/182686177-3acef450-c78e-4ceb-b5a8-6a8a14130735.png)
![image](https://user-images.githubusercontent.com/90483401/182686192-a25d3588-0d30-449e-b8de-d51552e60fbf.png)

**Comment by ThatFiveGuys** [comment]
Probably related to #9966

**Comment by ThatFiveGuys** [comment]
"Latejoin traitors are now datumized. There's a 1-second delay between selection and uplink equipment to account for lag, but this may not be enough - I'll need to test more." Probably related to this?

**Comment by Ilysen** [comment]
Most definitely, yeah. I can look into diagnosing this; if any staff have runtime logs that might be related from this round, they'd be a big help
