### ISSUE TITLE
Portagene missing eject occupant and scanner lock options

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#10061]
### Labels

[BUG]

### Description

The portagene was missing the eject occupant and scanner lock options after repairing it with glass.

### Steps to reproduce

1. Repair broken portagene with glass
2. Put an npc or monkey inside
3. They are stuck. You cannot get them out.

### Expected Behavior

I expect to be able to remove the monkey from the device in which it is enclosed.

**Comment by UrsulaMejor** [comment]
Unable to replicate
