### ISSUE TITLE
AI supposedly able to figure out IDs from pda pockets

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#10086]
### Labels

[BUG]

### Description

AI should not be able to get ID information from pockets

### Steps to reproduce

1. Drink some fluorosulfuric acid so your voice comes out as unknown
2. Put on a gas mask
3. Put your PDA with inserted ID in your pocket

I then asked AI "What's my name" and he answered it right. I was pretty confused about how he managed to, I didn't do anything notable in the round at all so I'm pretty sure it's not memory nor guessworks. Some other player told me it was a bug and suggested I make a bug report, here it is!

### Expected Behavior

AI can not figure out my name

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/6396368/183119673-a45b11e9-d7f2-460a-bb96-6ce2d74dd570.png)

**Comment by Argonius-Angelus** [comment]
This might not be a bug. The AI could have just examined you and saw that you had an item with your name on it (for example the har), or it detected your PDA (it'll flag this even when it's not in your ID slot). You might show up as unknown in the radio and visually, but the AI might have just examined you and said your name from those clues.

**Comment by Garash2k** [comment]
I didn't have any trinket item with my name on it. It could be the PDA detection thing, how is it supposed to work? What does and doesn't work should /probably/ be documented on the AI wiki page for counter-play purposes, it's pretty dang important.

**Comment by Argonius-Angelus** [comment]
I am personally unsure, however it seems that if they have the PDA on their person (be it in a pocket or on the belt or ID slots), it detects as "They have a PDA \*\*MESSAGE**". Best way to test it again is to do the same thing, but use a station bounced radio and have your PDA in your backpack. See if they can figure out who you are from that.

**Comment by TobleroneSwordfish** [comment]
it should only return PDAs in these slots
![image](https://user-images.githubusercontent.com/20713227/183231723-80844182-bd48-4dae-a181-e79287942ab1.png)
not pockets too

**Comment by Argonius-Angelus** [comment]
Interesting. I wonder what the code looks like for the comms ID that the AI can see.
