### ISSUE TITLE
A couple of lights on the Zeta shuttle are misaligned

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#10093]
### Labels

[minor]

### Description

A couple of lights on the Zeta shuttle are misaligned

### Steps to reproduce

1. On donut 2, call the research shuttle
2. See misaligned lamps

### Expected Behavior

correct lamps

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/31984217/183223568-a7d84010-3441-4ee8-a743-5ac3b0e8ff07.png)

**Comment by Sord213** [comment]
Resolved
