### ISSUE TITLE
Donut 2 missing important machines

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#10096]
### Labels

[BUG]

### Description

doesn't seem to have any manufacturers or device vendors in tool storage

### Steps to reproduce

1. go onto donut 2
2. try to get tools or igniter
3. be poor
4. cry

### Expected Behavior

If it's a functional map it should have the modern items required for  tool storage longevity

### Additional Information & Screenshots

not exactly a bug but worth tracking as an issue

**Comment by Sord213** [comment]
they exist, look better
