### ISSUE TITLE
Taser / gun balance feedback thread

### ISSUE THREAD

**Issue by Tarmunora** [goonstation/goonstation#101]
Please respond to this issue with concerns regarding the *balance* of tasers, wavegun, lawgiver, etc. as a direct consequence to #55 for the purposes of a followup rebalance if necessary.

Also just general stun/gun balance I suppose

**Comment by Tarmunora** [comment]
EMP mode against the nuke is probably too devastating. Perhaps exclude the nuke from the AoE component (leaving the range-based single target EMP), or exclude nuclear bomb entirely.

**Comment by PrimeNumb** [comment]
> Please respond to this issue with concerns regarding the _balance_ of tasers, wavegun, lawgiver, etc. as a direct consequence to #55 for the purposes of a followup rebalance if necessary.

I have an idea: tasers could do more stamina damage, but the maximum stun/KO they can apply is clamped to a very low duration.

**Comment by Flaborized** [comment]
I think that combat situations that last longer tend to me more fun, and I think that reaching a "win condition" (deep crit/handcuffed target) should be harder than it is now, specifically with ranged stun weapons. I like the idea to capping the stun/KO they can apply to a few seconds, requiring that people use a baton as a follow up to actually get people in handcuffs.

I think this is more dynamic to play, and much more satisfying to pull off than point-blanking repeatedly with a taser. It's more difficult and makes it easier for the other player to turn around the fight, but I think that's fine and actually Good and in-line with my ideas about reaching "win conditions" being more difficult.

There was a short time when I was playing sec often where tasers were bugged to only stun for like a second or so at max, and it was surprisingly fun to play as sec and felt a lot more interesting than what we currently have. It was a bit extreme and made tasers on their own pretty bad (only good when paired with something) but I think it shows that changes in this direction can be beneficial to the game.

**Comment by Tarmunora** [comment]
Hm. Sounds like there's a want for making tasers more of a disorient weapon than a stam/stun weapon? Correct me if I'm wrong here

**Comment by PrimeNumb** [comment]
It should still be able to KO/stun

**Comment by Tarmunora** [comment]
Current thought process: split tasers + some taserlike projectiles into a new `D_DISTRUPT` projectile damage type (this gives the option to keep stuff like waveguns, probably AI tasers etc. using current stuns which I *think* work fairly well for them) 
Refactor `stun_bullet_hit()` into bullet_act where appropriate (also perhaps bleed from projectiles)
