### ISSUE TITLE
Reset All APCs fails to reset Main Breakers

### ISSUE THREAD

**Issue by Connie-Dun** [goonstation/goonstation#10104]
### Labels

[BUG]

### Description

AI's reset all APCs not fix Main Breaker

### Steps to reproduce

1. Turn off APCs' Main Breakers.
2. Reset all APCs as AI.
3. Notice power remains off although it says Main Breakers are back on.

### Expected Behavior

Resetting the APCs should restore power where main breakers were turned off

**Comment by TobleroneSwordfish** [comment]
I can't reproduce this, maybe the APCs had AI control disabled?

**Comment by Connie-Dun** [comment]
Not so in this instance; after Reset All APCs failed, I individually went to each APC and turned the main breakers off and then back on, which restored power.

**Comment by Connie-Dun** [comment]
I've testing it myself a little bit more, and it has only seemed to happen when I turn off several breakers - if just one or two, it works as expected.

**Comment by UrsulaMejor** [comment]
Unable to reproduce
