### ISSUE TITLE
Pipeshot consumes entire material stacks

### ISSUE THREAD

**Issue by Smearfo** [goonstation/goonstation#10110]
### Labels

[BUG]

### Description

When using scrap or glass to fill pipeshot, the entire stack of the given material is consumed at once, and in the case of glass shards, only counts as one shard.

### Steps to reproduce

1. Fabricate and cut pipeshot
2. Fill with fuel
3. Attempt to add scrap/glass from a stack
4. Observe your entire stack of material be consumed
5. Cry

### Expected Behavior

For only one unit of material be consumed per pipeshot, or two in the case of glass shards.

### Additional Information & Screenshots

There's also some strange interaction with the shard filling text: "You add the 5 shards to the the filled pipe hulls. You feel like you'll need 1 more 5 shardss to fill all the shells. "

**Comment by pgmzeta** [comment]
Dupes #9866
