### ISSUE TITLE
revenants are chased by animated objects

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#10149]
### Labels

[BUG]

### Description

when in revenant form as a wraith, any objects previously animated by yourself or animated by your poltergeists will chase and attack you

### Steps to reproduce

1. Be wraith
2. Have some poltergeist friends
3. Animate a bunch of objects
4. Take revenant form
5. Be chased by circular saws, captain's sabre, coffee machines, crowbars, etc.
6. Lose a lot of health from being attacked by your own doing

### Expected Behavior

I expected revenants to have immunity/not be targeted by animated objects that they or their poltergeists animated

**Comment by frawhst** [comment]
woops

**Comment by frawhst** [comment]
should be fixes
4b8df8db3b968bbddbf60f706dbbaf9e6e8244cc
