### ISSUE TITLE
Invisible cloning console when sideways!

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#10141]
### Labels

[BUG]

### Description

Invisible Cloning Console

### Steps to reproduce

1. Find a left/right facing console such as the one on nadir
2. Scan someone and have it enter the "ready to clone" red blink state
3. Console becomes invisible (but still interactible with right click)

### Expected Behavior

A visible console

### Additional Information & Screenshots

Noticed on nadir!
![image](https://user-images.githubusercontent.com/6396368/183313013-6d1ec06b-3376-4b46-b46f-4348076ce2e2.png)
![image](https://user-images.githubusercontent.com/6396368/183315458-7e241302-7ec2-46a1-ae24-4173d478316a.png)
![image](https://user-images.githubusercontent.com/6396368/183315462-db350c36-d344-4641-abde-bb4d52fe7ce0.png)

**Comment by Kubius** [comment]
Issue with Nadir branch which is not in yet, likely due to some problems in the automatic icon merge - happened with the armory computer previously.

**Comment by Kubius** [comment]
Resolved with the manual icon cleanup.
