### ISSUE TITLE
unconcious and death overlays dont disappear when a body is taken over in revenant form

### ISSUE THREAD

**Issue by ghost** [goonstation/goonstation#10151]
### Labels

[BUG]

### Description

after taking over a body in revenant form, the unconcious/death visual overlays do not disappear, limiting field of vision in some cases

### Steps to reproduce

1. Be wraith
2. Have points to turn into a revenant
3. Target a dead body
4. Resurrect as a revenant
5. Have the restricted vision of the black unconcious overlay or the annoyance of the white crit overlay stuck on your screen while you're revenant

### Expected Behavior

I expect revenants in reanimated bodies that are fully healed to also have full range of vision granted the person who's body it was didnt have any vision quirks before dying. Maybe a feature though?

**Comment by UrsulaMejor** [comment]
unable to reproduce
