### ISSUE TITLE
ghostcritter bird beak doesn't function for eating

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#10153]
### Labels

[BUG]

### Description

As title.

### Steps to reproduce

1. Become a space robin or whatever
2. try using your beak on food
3. starve

### Expected Behavior

For the beak to basically function as a icon swap of the critter mouth really

### Additional Information & Screenshots

use-in-hand with the other limb does work

**Comment by soleilan** [comment]
works fine, probably fixed
