### ISSUE TITLE
flocktrace has a few physical interactions it probably shouldnt have

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#10173]
### Labels

[BUG]

### Description

flocktrace can remove items from people, eject people from sleepers, move items via clickdrag, etc

### Steps to reproduce

1. be flocktrace
2. right click sec personnel
3. press show inventory
4. remove shoes

### Expected Behavior

probably not being able to do that

**Comment by amylizzle** [comment]
while in flock ghost form or while possessing a drone?

**Comment by TobleroneSwordfish** [comment]
in ghost form sadly, a couple of missing `isintangible` checks (though Sian repeatedly having his shoes stolen by an invisible force was pretty funny)
