### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by OopsieOops** [goonstation/goonstation#10170]
### Labels

[BUG]

### Description

When clicking on things that open a seperate window, ie a fabricator or a vending machine. A blank white screen will pop up. ive tried a handfull of different things to fix. Nothing has worked.

### Steps to reproduce

1. Click on a vending machine, fabricator etc

### Expected Behavior

There should be text but there isnt any

**Comment by Chatauscours** [comment]
Likely a client side, or one time issue.
