### ISSUE TITLE
Flock Control Panel appears out of focus

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#10188]
### Labels

[BUG][MINOR]

### Description

The Flock Control Panel is always out of focus.

### Steps to reproduce

1. Be Flockmind
2. Open Flock control panel

### Expected Behavior

For the Flock control panel to be in focus when opened

**Comment by amylizzle** [comment]
is this still the case with the new tgui update?

**Comment by FlameArrow57** [comment]
Yep

**Comment by amylizzle** [comment]
Boo :(

**Comment by FlameArrow57** [comment]
Seems it appears in focus while in a drone
