### ISSUE TITLE
Flockminds can convert listening post doors to break in

### ISSUE THREAD

**Issue by cheekybrdy** [goonstation/goonstation#10194]
### Labels

[BUG] [Major]

### Description

Flockdrones can break into the listening post and make it a hive, which is unintended according to the flock discord chat

### Steps to reproduce

1. be flock
2. use nanite sprayer on listening post entrance door
3. break in and eat the syndicate hologram module (yum!)

### Expected Behavior

No break into the syndicate VIP cool kids club

**Comment by frawhst** [comment]
syndi-flock with grenade launchers…. Yes….

**Comment by FlameArrow57** [comment]
Was fixed
