### ISSUE TITLE
Too many flockdrones

### ISSUE THREAD

**Issue by Smearfo** [goonstation/goonstation#10201]
### Labels

[BUG] 

### Description

In some circumstance, placing down the flockrift will cause it to infinitely spew flockdrones

### Steps to reproduce

1. Get midround flock event antag
2. Move to engineering and place down rift
3. Rift spawns flockdrones and other beginning materials
4. Rift doesn't go away
5. goto 3
6. Infinite flockdrones cause infinite lag and the server dies

### Expected Behavior

For a rift to just spawn the flock starter kit and disappear

### Additional Information & Screenshots

![flockwins](https://user-images.githubusercontent.com/46880050/184222543-72d2d10d-9add-4733-92bb-5b4dcf3d1728.png)

**Comment by TobleroneSwordfish** [comment]
Fixed by #10202, whoops
