### ISSUE TITLE
Using the visual studio code Sync button causes for messy re-authorized commits

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#10228]
### Labels

[A-TOOLING][C-DOCUMENTATION]

### Description

Using the visual studio code Sync button causes for messy re-authorized commits

### Steps to reproduce

When trying to update my fork's master, if I were to use VSC's sync button, it would lead me re-autoring commits of everything everyone else did, causing for messy logs, messy PRs, and mentions in other pull requests.

The cause of that was while installing git, this Rebase option was picked.
![image](https://user-images.githubusercontent.com/6396368/184448740-5d499f56-71d1-498c-bcb8-ad7fad192979.png)

The solution is to remove that setting by editing your system's gitconfig to delete this section:
```
[pull]
	rebase = true
```
Location of the file:
[C:\Program Files\Git]\etc\gitconfig

### Expected Behavior

Being able to update master without re-authoring everything

**Comment by TobleroneSwordfish** [comment]
Really not sure this should be an issue on this repo, but I suppose it's useful information

**Comment by Garash2k** [comment]
ZeWaka asked me to make one!

**Comment by ZeWaka** [comment]
awesome ty now it's searchable!
