### ISSUE TITLE
Only the first mousetrap in a container triggers

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#10249]
### Labels

[BUG]

### Description

^

### Steps to reproduce

1. Put multiple mousetraps in a box
2. Arm the bottom one
3. Reopen the box
4. Mousetrap does not trigger

### Expected Behavior

I expected the mousetrap to go snap satisfyingly

**Comment by ThatFiveGuys** [comment]
Intentional

**Comment by frawhst** [comment]
To elaborate: behavior prevents suicide bombing/flashbanging with an entire box of grenades in one click.
