### ISSUE TITLE
refueling material-restricted RCD with matter cartridges isn't functional

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#10258]
### Labels

[runtime]

### Description

An RCD with material restrictions (only the cardboard RCD in practice) will runtime because RCD ammo doesn't have a material.

### Steps to reproduce

1. As a human, spawn a cardboard RCD
2. Spawn some RCD ammo or loot EVA
3. Try to stick the ammo into the cardboard RCD
4. get runtime

### Expected Behavior

For this to fail gracefully (or for RCD ammo to work with all restricted RCDs frankly. This seems to refer to something that hasn't been implemented whatsoever)

### Additional Information & Screenshots

In code/obj/item/rcd.dm
![image](https://user-images.githubusercontent.com/31984217/184554711-f87073c9-0f5a-4d09-8dd8-9a877f567214.png)

**Comment by BatElite** [comment]
FWIW this also happens when you're a ghostdrone

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/cb463cb049aff9f83082076719b888f0e03676b2
