### ISSUE TITLE
Respawning as event antag on gang round keeps you in your previous gang

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#10353]
### Labels

[BUG]

### Description

If you die on a gang round and get respawned as an event antag, you are still a gang member.

### Steps to reproduce

1. Die as gang member/leader
2. Respawn as event antag
3. See issue

### Expected Behavior

They do not get put back on the same gang

### Additional Information & Screenshots

having a werewolf and wizard on the same gang is probably not a good thing for balance reasons

**Comment by Mister-Moriarty** [comment]
Fixed by #13346.
