### ISSUE TITLE
Able to see edges of azones by leaving afterlife bar.

### ISSUE THREAD

**Issue by Conchuckter** [goonstation/goonstation#10365]
### Labels

[BUG - MINOR][SPOILER]

### Description

I was able to see the edges of azones by leaving afterlife bar.

### Steps to reproduce

1. Die as snail (Not required?)
2. Enter afterlife bar
3. Leave afterlife bar
4. Do not move

### Expected Behavior

You should immediately go into observe where you entered afterlife bar from.

### Additional Information & Screenshots
Spoiler: https://user-images.githubusercontent.com/93377868/185736641-1a2f0b8b-8782-4f81-b559-17fef3281c03.png

**Comment by frawhst** [comment]
Couldn't reproduce on a local even while tapping keys very slowly. Might be dependent on something about the mob, or maybe the map?

**Comment by Conchuckter** [comment]
Don't really any idea, the only I could think of was being a snail was becuase of admin foolery.

**Comment by Conchuckter** [comment]
Related? #10161

**Comment by Retrino** [comment]
![Screenshot (878)](https://user-images.githubusercontent.com/73998720/194731124-a34f5fb0-b716-4753-8897-b414adc665c3.png)
definitely still a thing, may not work on local for whatever reason? definitely works on live
