### ISSUE TITLE
"You don't have a corpse" while corpse still exists

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#10399]
### Labels

[BUG]

### Description

While inside my corpse, my screen suddenly went black and when I moved to ghost it said I no longer had a corpse. My corpse still existed and was untouched in the same position.

### Steps to reproduce

1. Die
2. Don't leave your corpse
3. Your screen turns black and the UI gets all weird
4. You apparently no longer have a corpse despite your corpse existing

### Expected Behavior

I still have a corpse?

**Comment by TheTyrant25** [comment]
unable to reproduce
