### ISSUE TITLE
Tile so hot these days

### ISSUE THREAD

**Issue by pali6** [goonstation/goonstation#104]
Submitter: veilivel
The first tile in that botany ship for some reason likes to start off close to a million degrees

To Recreate!
Go to the botany ship in the debris field
Walk one tile into the right side from the middle
Notice that you're burning to a crisp

It's happened multiple rounds in a row now, I dunna what could possibly have caused it, but it's scary.  The heat slowly goes away without affecting any other tiles.

4/4/2020

**Comment by flrsh** [comment]
Pushed a fix; I changed all the airless turfs from inside the shuttle to non-airless ones. Doesn't fix the underlying issue of airless and non-airless tiles not playing nice, but I'm not cool enough to look into atmos. Maybe someone else will! ✨
