### ISSUE TITLE
the research shuttle's floor and some walls do not exist

### ISSUE THREAD

**Issue by reaper90202** [goonstation/goonstation#10419]
### Labels

[BUG]

### Description

the research shuttle's floor and some walls do not exist. map is donut 2

### Steps to reproduce

1. look at the research shuttle on donut 2

### Expected Behavior

for it to exist

### Additional Information & Screenshots

![research](https://user-images.githubusercontent.com/92821079/185962628-59e0de5d-8d35-419d-a425-ccd5a59966ac.PNG)

**Comment by TobleroneSwordfish** [comment]
duplicate of #9968
