### ISSUE TITLE
Declare ready button doesn’t work for some people.

### ISSUE THREAD

**Issue by Merlin1230** [goonstation/goonstation#10429]
### Labels

[BUG]

### Description

Some people are stuck in the lobby, as hitting declare ready does.. nothing

### Steps to reproduce

1. Join a server
2. Hit the ready button
3. Nothing happens
4. Panic

### Expected Behavior

People should be able to ready up

### Additional Information & Screenshots

I haven’t had this issue myself, I’ve only seen multiple mhelps about it recently (it may also be a server thing as all the mhelps I’ve noticed were from 1, but I didn’t look that far back for all of them). 

Another thing I’ve noticed is that people affected by this show up as “[DEAD]”, when people in the lobby should be showing up with just their ckey.

**Comment by CalliopeSoups** [comment]
Some light on this bug from how I'm experiencing it, but it seems that I'm getting locked out of pressing ready specifically after opening up the latejoin menu, closing it then trying again. Restarting client fixes it.

**Comment by Merlin1230** [comment]
Huh, last mhelp about it I saw was during pre-round. The weirdest part about this whole thing is that its not really.. consistent at all
