### ISSUE TITLE
co2 tanks on monkeys

### ISSUE THREAD

**Issue by XanaxSpace** [goonstation/goonstation#1044]
[BUG]
monkeys can live on pure co2 canisters
**Describe the bug**
pure co2 tanks with internals cant put monkey oxygen damage over 149, they can live forever breathing only co2, after a while taking internals off doesnt heal their oxygen damage over time either, though making them smell an ampule when they are capped out on that 148-149 oxygen does make it go above it, getting rid of the bug.

**To Reproduce**
1.get an oxygen tank from a canister dispenser
2.empty the oxygen tank out
3. fill the empty oxygen tank completely with co2
4.get a mask
5.put said mask and co2 tank on a monkey
6.make sure to turn internals on
7. watch it live forever on pure co2
**Expected behavior**
from 0 to 90 oxygen damage should rack up very fast, it slows down a bit up until 149 at which point it stops completely, removing internals will not heal the monkey over time at all.
make the monkey inhale a capsule when its at 149 cap to break the bug, making it suffocate completely in a short while 

**Screenshots**

**Additional context**
locking monkeys in a room and opening a valve to a full CO2 canister in it does properly kill them off. co2 tank bug does not work on human players, only monkeys.

**Comment by Tarmunora** [comment]
Not a bug, but maybe something to still take a look at - mobs don't breathe when in crit, so the negative effects of breathing CO2 (passing out and taking large oxy damage) would not apply.

**Comment by Sovexe** [comment]
unless it's done this way for balance reasons it seems a bit absurd

**Comment by ZeWaka** [comment]
Doesn't seem like a bug.
