### ISSUE TITLE
I can't see the chat

### ISSUE THREAD

**Issue by Yeeb0** [goonstation/goonstation#10498]
### Labels

[BUG]

### Description

I cannot connect to the chat

### Steps to reproduce

1. I'm not sure, maybe my byond is outdated or my computer sucks

2. Scream

### Expected Behavior

I am supposed to be able to see the chat

### Additional Information & Screenshots

https://imgur.com/gallery/4Wr13Qo

**Comment by Conchuckter** [comment]
This is likely an issue with IE or something else, I've had this happen a few times but generally a reload works.

**Comment by FlameArrow57** [comment]
#7529
