### ISSUE TITLE
Donut 2's mining nano-fabricator is inside a wall.

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#10511]
### Labels

[BUG]

### Description

There's a nano-fabricator inside a wall.

### Steps to reproduce

1. Start a round on donut 2
2. Walk to mining
3. Notice a machine in a wall

### Expected Behavior

There not be a machine inside the wall.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/84296283/187136013-1e2b81ed-fe21-4b42-8756-e7e62822c6e3.png)

**Comment by frawhst** [comment]
There's also one in the refinery, so I assume that one is a mapping misclick

**Comment by Sord213** [comment]
yep, misclick
