### ISSUE TITLE
Fish drones and shark drones do not drop syndicate boards

### ISSUE THREAD

**Issue by Jaheen84** [goonstation/goonstation#10528]
### Labels

[BUG][MAJOR]

### Description

The wiki states on the NT Reputation page that fish drones and shark drones are supposed to drop syndicate boards that can be given to the NT representative on Oshan. However, they do not seem to drop at all.

### Steps to reproduce

1. Spawn on Oshan Laboratory.
2. Kill a fish drone or shark drone in the trench or around the station.
3. Notice how it explodes without leaving behind any syndicate boards.

### Expected Behavior

The drones should drop syndicate boards upon death, either every time or at least randomly, however it was back when they did.

### Additional Information & Screenshots

If I were to guess, this may be connected to drones in space also ceasing to drop special items. Sawdrones used to drop circular saws, laser drones used to drop phasers, etc. They stopped doing so some time ago, 1-2 months if I were to estimate, and the changelogs do not mention this from what I can find. My suspicion is that these special drops were silently patched out (perhaps because devs thought it made for a too easy source of phasers, that's the only justification I can think of at least), and doing so also caused drones on Oshan to lose their special drops. Or this is an issue that predates that change, I am unsure because I wasn't looking for the boards until recently. Regardless, the NT reputation feature is effectively useless while this is the case.

**Comment by stonepillars** [comment]
Confirmed, caused by #10234 keeping a flag which bypasses pod colosseum checks, leading to drones only dropping loot when they had that flag set.
