### ISSUE TITLE
Bible inventory deleting items

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#10543]
### Labels

[BUG]

### Description

While holding a bible full of tools, the hud suddenly switched from TG style centered inventory, to the bottom-left goon inventory for only the bible. After this happened a few times and I put an item into the bible, all the other items were gone.

### Steps to reproduce

1. Have a bible full of tools
2. Pull out crowbar to fight fish in trench
3. Bible inventory moves to the other hud style location a few times, fixed each time by closing and reopening the bible
4. Continue to walk with the bible inventory open, all tools present and the crowbar still in hand
5. Drop the bible & crowbar (I was in crit and dying)
6. Pick up the bible and put crowbar inside, then place bible into backpack
7. Pull out bible later and it only has a crowbar?

### Expected Behavior

My items should not just disappear just because I dropped the bible.

**Comment by frawhst** [comment]
bleh, iirc bibles share a HUD for everyone using them due to General Bible Shitcode, so the HUD style would get fucked up if two people opened it at once. Sounds like the disappearing crowbar might have just been someone else taking the crowbar out of it?

**Comment by Zamazenta** [comment]
I was alone in the trench, so nobody could have taken anything out of it. The crowbar was the item that stayed, since I was holding it at the time, all the other tools disappeared.

**Comment by BatElite** [comment]
They could have, the gimmick of bible storage is that it's shared between all bibles.

Unfortunately that gimmick isn't very robustly coded

**Comment by Zamazenta** [comment]
Didn't know that the bible inventory was shared. In that case it probably was just someone else taking the items.
