### ISSUE TITLE
Fire elemental corpse produces infinite mystery meat

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#10541]
### Labels

[BUG]

### Description

Spotted someone butchering a fire elemental corpse for infinite mystery meat.

### Steps to reproduce

1. Kill and butcher a fire ele
2. Hopefully it's reproduceable

### Expected Behavior

Not infinite meat

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/20713227/187705790-0e7d558a-4659-416a-8920-927782d734ea.png)

**Comment by ThatFiveGuys** [comment]
#10688
