### ISSUE TITLE
Donut 3 Emergency Lights can have their bulbs removed, but not put back in.

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#10569]
### Labels

[BUG]

### Description

If you click an emergency light (the little red ones) to remove its bulb, then try to put the bulb that you just removed back into it, you will not be able to

### Steps to reproduce

1. Remove bulb from emergency light
2. Try to put the same bulb back in

### Expected Behavior

I can put the bulb back into the light that it was removed from

### Additional Information & Screenshots

Maybe this happens on other maps i dont know
![image](https://user-images.githubusercontent.com/25157685/187924725-79fea704-8a1e-4f8e-b75b-2d1ff1c517f6.png)

**Comment by pgmzeta** [comment]
has been fixed since this was filed
