### ISSUE TITLE
Two-handed weapons container click-drag oddity with not having both hands free.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#1059]
**Describe the bug**
If you try to click-drag a two-handed item from your backpack to another container, while not having both hands available (holding an item in one hand, missing an arm, etc), the item will "disappear" and not go to the other container.
In reality, the two-handed item remains in your backpack, its slot just appears empty. Clicking on the "empty" slot will retrieve the two-handed item.

**To Reproduce**
1. Have an AK47 (or other two-handed item) in your backpack.
2. Have another backpack/box/container near you.
3. Have not both of your arms free (hold something in your hand / be missing an arm, etc).
4. Click-drag the AK47 onto another backpack/box/container near you.
5. The AK47 "disappears" from your inventory, doesn't re-appear in the other container, no messages or sounds.
6. Clicking on the "empty" slot in your backpack retrieves the AK47.

**Expected behavior**
Doesn't let you do the click-drag interaction or drops the two-handed item at your feet.

**Comment by Tarmunora** [comment]
similar to #945
dropping at feet would be consistent behavior

**Comment by pali6** [comment]
Unable to reproduce.
