### ISSUE TITLE
Can't apply patches to self or turn internals on/off when buckled in

### ISSUE THREAD

**Issue by pali6** [goonstation/goonstation#106]
Submitter: trustworthyfella
**Describe the bug**
Title.

**To Reproduce**
1. Buckle into a seat
2.Try to set internals or apply a patch
3. It doesn't work
4. Wonder why as you're dying

**Expected behavior**
Being able to apply patches and set internals.

**Additional context**
Say you're being sabered out

Reported on: Goonstation 2020-04-04 21:14:52

**Comment by pali6** [comment]
Fixed the internals thing. Unable to replicate the patches.

**Comment by flrsh** [comment]
Also unable to replicate patches behavior.

**Comment by ZeWaka** [comment]
Closing due to lack of replication, open another issue if you can find a working test-case.
