### ISSUE TITLE
Can't put emergency suit back in O2 box despite it spawning in there

### ISSUE THREAD

**Issue by krimmity** [goonstation/goonstation#10608]
### Labels

[BUG]

### Description

Being unable to put emergency suit back in O2 box despite it spawning in there

### Steps to reproduce

1. Randomly spawn with an emergency suit in your O2 box
2. Remove the emergency suit from O2 box
3. Try and put it back in
4. "The engineering diving suit won't fit into the box!"

### Expected Behavior

The suit should be able to fit in the O2 box

**Comment by UrsulaMejor** [comment]
Intended.
