### ISSUE TITLE
Tables no longer connect on roundstart

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#10669]
### Labels

[BUG]

### Description

Tables show up as if they're disconnected

### Steps to reproduce

1. join server
2. observe table
3. witness jank

### Expected Behavior

they should show up as connected!

### Additional Information & Screenshots

Probably a variable someone was clumsy and forgot to turn on or off

![image](https://user-images.githubusercontent.com/96703882/188521173-1ec244e4-f715-48ce-9dcc-7741c2ef07e1.png)

**Comment by pgmzeta** [comment]
Fixed in acf68de10b6b2b7d01bc40133c337a20e2d643b8
