### ISSUE TITLE
Canbombs explode pre-emptively/make 30 second jumps in time

### ISSUE THREAD

**Issue by Kaan-NN** [goonstation/goonstation#10711]
### Labels

[MAJOR]

### Description

Canbombs pre-emptively explode/make 30 second jumps in time.

### Steps to reproduce

1. Build a canbomb (gas mix doesnt matter)
2. Set the timer to a random time or leave it at 90 seconds
3. Start the timer
4. Drag it or bolt it then wait for about 10 seconds until it explodes
5. Die before reaching the shuttle with the the funny bomb😢

### Expected Behavior

The canbomb shouldnt detonate before the 90 second timer (or 15 min whatever is the actual minimum time) is over

### Additional Information & Screenshots

https://user-images.githubusercontent.com/68946148/188958979-cfe303b4-0513-4a51-9e79-125fdf88846b.mp4

RIP non antags trying to make a timed explosion

**Comment by MetricDuck** [comment]
Something is extremely strange with the timer
