### ISSUE TITLE
[BUG] loyalty implants instantly kill revolutionaries

### ISSUE THREAD

**Issue by mopcat** [goonstation/goonstation#1074]
**Describe the bug**
when you loyalty implant a revolutionary they die instantly

**To Reproduce**
1. implant rev man
2. rev man die after 3 seconds of being implant
3. wonder what went wrong, comrade

**Expected behavior**
rev man not die and instead become loyal man

**Comment by pali6** [comment]
Also probably fixed by 494bfd56.
