### ISSUE TITLE
Equipped items drop on spawn.

### ISSUE THREAD

**Issue by Stealthy122** [goonstation/goonstation#10749]
### Labels

[BUG] Items drop shortly after spawning

### Description

Almost 100% of the time, if you equip an item after you spawn, it is dropped. There was one time where my uniform dropped too, causing me to drop all the items I have on the floor.

### Steps to reproduce

1.  Join the game.
2.  Equip an item (Or spawn with, say, a toolbox).

### Expected Behavior

Expected to not drop my items. This has caused me to not notice I have dropped my first aid kit when spawning as a Medical Doctor, and losing my automender somewhere in arrivals.

**Comment by Balarak** [comment]
I believe this is related to mutantraces, Spawning in as a job probably rolls before the raceswap, and currently changing mutantrace causes your held items to drop.
