### ISSUE TITLE
Aggressively grabbing people instantly knocks them out and keeps them that way, as if equivalent to a kill choke.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#1078]
**Describe the bug**
As the title says, aggressive grab someone and they'll be instantly knocked out, with stamina going instantenously from full to negative full red.

**To Reproduce**
1. Aggressively grab someone.
2. They fall unconscious and stay that way until you let go.

**Expected behavior**
Just being grabbed and held in the same spot as the grabber, as it used to before.

**Additional context**
Could be related to the recent Life() reorganising?

**Comment by pali6** [comment]
Probably fixed by 494bfd56.
