### ISSUE TITLE
Rancher job considered secret content

### ISSUE THREAD

**Issue by LudumSi** [goonstation/goonstation#10788]
### Labels

[SECRETS]

### Description

Rancher machines and chickens do not load on privately hosted server

### Steps to reproduce

1. Host server with blank secrets file
2. Go to ranching area
3. Observe that chickens placed on maps are just critters, and that egg incubators and feed grinders are just generic machines.

### Expected Behavior

The non-secret portions of the ranching job are not in the secrets folder

### Additional Information & Screenshots

I've been running a private /tg/ server with friends for years. We have attempted this with Goon a few times, and as I have recently been playing on the public servers I figured it was time to give it another spin. Last time we gave up on it due to the missing secrets folder preventing ranching from being a thing. One of the players naively picked the role and ended up very disappointing. Ranching is largely after my time, but from my understanding the chicken breeding was at one time secret content. Now there is a guide to doing it available in-game. I get the need to have secret content and am in no way asking for that to be released, but it would be nice to be able to host a server with a few friends and have all jobs work as intended.

**Comment by Wisemonster** [comment]
Not a bug, considering it is secret content.

**Comment by LudumSi** [comment]
My apologies. You are correct. If a github issue is not the proper avenue to appealing this, I would appreciate being pointed towards the proper channels.

**Comment by Wisemonster** [comment]
The goonstation forums might be a good idea https://forum.ss13.co/
