### ISSUE TITLE
constable hooty can see and judge ghosts

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#10813]
### Labels

[BUG]

### Description

Constable hooty can frown at ghosts

### Steps to reproduce

1. be ghost
2. float by sec
3. hooty sees all

### Expected Behavior

Surely owls should not be able to see ghosts

### Additional Information & Screenshots

Honestly this could very easily be considered a feature
![image](https://user-images.githubusercontent.com/96703882/190232709-6aceb6fe-6a82-48c5-89b8-1f9ab11eaeba.png)

**Comment by DimWhat** [comment]
feature as stated by zewaka in #9349
