### ISSUE TITLE
Slowdown from wraith curse cannot be cured

### ISSUE THREAD

**Issue by Spell-Tech** [goonstation/goonstation#10821]
### Labels

[BUG]

### Description

After being given a weakness curse from a wraith and curing it, the stamina regen debuff was removed, but the slowdown remained and could not be cured.

### Steps to reproduce

1. Get a weakness curse from a wraith
2. Cure it by splashing holy water on yourself
3. Crawl around at snail speed

### Expected Behavior

I expected that the slowdown would be cured by the holy water, same as the drowsiness and stamina penalty.

**Comment by frawhst** [comment]
Last commit fixed this
