### ISSUE TITLE
Skeleton commander attacked by own summons

### ISSUE THREAD

**Issue by ThePastTenseOfYeetIsYote** [goonstation/goonstation#10851]
### Labels

[BUG]

### Description

Skeleton commander summoned a skeleton on shuttle only to get repeatedly get stunned by their own summon

### Steps to reproduce

1. Roll skeleton commander
2. Summon skeleton
3. Sometimes they start attacking and stunning you

### Expected Behavior

Summons shouldn't target their master

**Comment by frawhst** [comment]
Fixed with factions I believe
