### ISSUE TITLE
Bugs when removed skeleton head takes damage.

### ISSUE THREAD

**Issue by Two-Braids** [goonstation/goonstation#10904]
### Labels

[BUG] 

### Description

Removing skeleton head and damaging it causes examine text to update but health icon does not update with it and you can't seem to heal the damge (only tried synthflesh in beaker). Body also becomes a regant container and gets stuck like that.

### Steps to reproduce

1. Be skeleton in afterlife bar.
2. Remove skeleton head.
3. Attack own head on ground with a crowbar.
4. Body examine text updates to having damage, but Health icon does not.
5. Try to pour synthflesh on self (tried targeting head and torso), "You transfer 10 units of the solution to Nurse Dee Ceased." Examine text for body does not change.
6. Pour synthflesh on decapitated head, examine text for body does not change.
7. Re-attach head to self. Try pouring synthflesh on self. "You transfer 10 units of the solution to Nurse Dee Ceased."
8. Remain severely injured via examine text only.
9. Scan self with reagent scanner after pouring synthflesh into "self" container. Synthflesh is there and degrades but doesn't heal you.

### Expected Behavior

Health indicator updates with damage and being able to heal yourself from it. Body not getting stuck as a container??

### Additional Information & Screenshots

![dreamseeker_yoPxktznQA](https://user-images.githubusercontent.com/107102007/191124824-73e44246-28f5-4903-97ee-f05cada2dbc8.png)
![dreamseeker_ZvVX69Nzqh](https://user-images.githubusercontent.com/107102007/191124828-460b3c52-039d-4731-86e0-4ccc34ef7958.png)

**Comment by frawhst** [comment]
Fixed in fa2d7a9
The pouring chems in while headless is intended (humans without heads are considered open containers, so you can pour things in etc), but the status wasn't being cleared when your head was reattached. The whole set-to-open-container is handled better now so this shouldn't happen.
