### ISSUE TITLE
Lead walls and windows do not connect

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#10921]
### Labels

[minor]

### Description

As title, see screenshot

### Steps to reproduce

N/A

### Expected Behavior

something that doesn't look silly

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/31984217/191342512-2a716df7-94c8-4796-89bc-ebbcd984fa67.png)

**Comment by ZeWaka** [comment]
i think i fixed this iirc, reopen if not
