### ISSUE TITLE
Microbombs seem to not delete/dispose after explosions.

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#10949]
### Labels

[BUG] [MAJOR]

### Description

After a hunter exploded, I was able to steal their microbomb and implant it in myself. After using it for a gimmick when I rolled sleeper, I too exploded and the microbomb fell out of me onto the ground.

### Steps to reproduce

1. boom.
2. boom chip on ground.

### Expected Behavior

I mean personally it's kind of fun, but I think they're supposed to be disposed of after explosion.

**Comment by nefarious6th** [comment]
Duplicate of #10946

**Comment by Momoberry** [comment]
> Duplicate of #10946

Just flip the 9 at the end around and pretend it's my PR
