### ISSUE TITLE
Reactor statistics runtimes.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#1095]
**Describe the bug**
Reactor statistics causing continuous runtimes.

[05:57:33] reactor_stats.dm,685: Undefined operation: 0.165416 /= null
[05:57:33] reactor_stats.dm,231: bad index

**To Reproduce**
Occured on cogmap1 during a seemingly standard furnace and cooler setup and (obviously) with the reactor statistics computer turned on. Not sure as to whether it can be reliably and consistently reproduced.

**Expected behavior**
Not causing errors.

**Additional context**
Hard to tell at glance what the cause is, perhaps some revelations might be made from glancing into the code.

**Comment by Adharainspace** [comment]
line 685: `if(ret["pressure_c"])` ret["pressure"] /= ret["pressure_c"]` i dont see why this would runtime, it checks to see if it exists before dividing by it
line 231: `c_metric["o2_dx"] = L["o2"] - master_chamber_datapoints[last]["o2"]`

i dont know anything about this code btw

**Comment by MarkNais** [comment]
I first did a char-burn space-radiator setup on Cog2, no runtimes.
I then did a char-burn freezer setup on Cog1, no runtimes.
I tried messing with the burn chamber, farting adding gas, removing the floor, opening the vents. no runtimes.
I tried deleting pipes near and around the meters, no runtimes.
I tried deleting a meter itself: a runtime at line 411 `master_meter_datapoints["[p_tag]"][++master_meter_datapoints["[p_tag]"].len] = L`

Could not reproduce.

**Comment by ZeWaka** [comment]
Still happening.
