### ISSUE TITLE
Fire elementals can lay "traps" by pointblanking themselves with the flare

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#10970]
### Labels

[BUG][major]

### Description

title- they can make stationary flares that light people on fire when they walk into it. Don't think this is intended

### Steps to reproduce

1. be fire ele
2. click self on disarm intent with flare
3. watch as sec walks into it
4. bit of trolling

### Expected Behavior

them to deal self damage

### Additional Information & Screenshots

Honestly, this is pretty cool and could be made into a feature, but doesn't seem intentional
![image](https://user-images.githubusercontent.com/96703882/192048663-a1606e86-e8bc-4492-a9cc-67bd993c8208.png)
![image](https://user-images.githubusercontent.com/96703882/192048822-a024e0a4-679b-4a5c-b375-c76cc059fdb2.png)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/496308216dce4ccf94854af53b02504c4fe083a9
