### ISSUE TITLE
Shoes and glove sprites are broken on monkeys (again)

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#10979]
### Labels

[BUG][Minor]

### Description

When a monkey puts on shoes or gloves they default to the human sprite instead of the bespoke ones I made months ago.

### Steps to reproduce

1. Turn yourself into a chimp
2. Put on shoes/gloves
3. See oversized and ill fitting sprites.

### Expected Behavior

To use the bespoke sprites like before when they are available.

### Additional Information & Screenshots

Directly tied to #9773
example of a captain monkey wearing insulated gloves and military boots.
![image](https://user-images.githubusercontent.com/40079883/192075572-3e7682b7-dc79-4d37-b3ef-5a24b485d2cc.png)

**Comment by pgmzeta** [comment]
testing a fix for this. silly mistake on my part :(
