### ISSUE TITLE
HoP jacket worn icons are gone

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#10987]
### Labels

[minor]

### Description

As title

### Steps to reproduce

1. Grab the  HoP's jacket
2. Wear it
3. Look as cool as you did before

### Expected Behavior

A visible jacket

### Additional Information & Screenshots

Side effect of #10903 - https://github.com/goonstation/goonstation/pull/10903/checks?check_run_id=8504681110

(To be perfectly honest, I find it fairly sloppy that it wasn't caught before merging. The difs aren't subtle.)

**Comment by ThatFiveGuys** [comment]
Fixed
