### ISSUE TITLE
Wraith client lag

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#10993]
### Labels

[BUG]

### Description

When playing wraith my client framerate seems lower and choppy.

### Steps to reproduce

1. Be wraith
2. Move around and observe the choppy framerate

### Expected Behavior

I expected to not lag just for being a wraith

### Additional Information & Screenshots

Not related to the wraith rework, have been experiencing this for a while.
My CPU usage seems to be consistently about 5% higher when playing wraith, not sure if this means anything or really how to go about diagnosing this. I'm just posting this to see if anyone else has this issue or an idea of what causes it.

**Comment by MetricDuck** [comment]
Playing around I think it's refreshing point generation at an excessive rate - the lag goes away if you set regen rate to 0. Similar to how it can be a bit laggy if you leave the internals tab open.
