### ISSUE TITLE
Pinning a monkey has no scream cooldown

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11006]
### Labels

[BUG]

### Description

As title, I hate it

### Steps to reproduce

1. Blindfold a monkey for convenience, then aggressive grab em
2. spam click a floortile to cause a racket

### Expected Behavior

less screaming

**Comment by gear-space** [comment]
Not sure when or where, but this bug appears to have been fixed as I can no longer reproduce the issue. Spam clicking the floor has the monkey scream once every few seconds. Our eardrums are safe! (for today) Please reopen if you find a way to reproduce.
