### ISSUE TITLE
manually removed borg upgrades are invisible

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11007]
### Labels

[BUG]

### Description

If you remove an upgrade from a borg by hand (something that I haven't seen anyone do in all the time I've been here, to be fair), the upgrade comes out invisible

### Steps to reproduce

1. On an operational borg, unlock its interface and crowbar its panel open
2. Assuming you're on local, you can insert the upgrades in this state
3. Remove an upgrade
4. have an invisible upgrade for some reason

### Expected Behavior

For this code not to fuck around with icon states in general really

### Additional Information & Screenshots

I've encountered this bug with a recovery upgrade, if that matters any

**Comment by amylizzle** [comment]
![image](https://user-images.githubusercontent.com/3855802/224395048-c870c2ef-7320-473a-91c3-8b41ce0ec1b2.png)

Unable to replicate.
