### ISSUE TITLE
Hydra smart pistol targets sawflies

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#11046]
### Labels

[BUG]

### Description

At least I'm pretty sure some poor nukie shot most of their smartgun ammo into the 16 sawflies their ally spawned.

### Steps to reproduce

1. Spawn sawfly
2. Target with smart pistol

### Expected Behavior

I expected the smart pistol to be smarter

**Comment by frawhst** [comment]
Yeah, looks like it just checks if the target is a living mob, isn't the shooter, and isn't wearing an agent card.

**Comment by NightmareChamillian** [comment]
if someone fixes this, it'll probably be worthwhile to also ensure they don't target nukie gunbots
