### ISSUE TITLE
Missing Space Diner APC

### ISSUE THREAD

**Issue by Nidabutt** [goonstation/goonstation#11056]
Labels
[BUG]

Description
There is a missing APC in the northern dining area of the space diner, above the residential area with the bedrooms. This room will eventually run out of power if used by a player for recharging cyborgs, cloning, etc... and then be unable to be recharged due to the missing APC without admin intervention.

Steps to reproduce
Enter the room, look around, no APC connected to this room.

**Comment by Sord213** [comment]
There is an APC, it's just hidden and not in the same room...for some reason. Looks intentional, but I don't know why.
![Screenshot_603](https://user-images.githubusercontent.com/71185626/192877208-dee2fe9a-2876-40c0-8f67-919f99be9148.png)

**Comment by Nidabutt** [comment]
That is... Bizarre, yeh.

**Comment by TobleroneSwordfish** [comment]
this is some minecraft adventure map design
