### ISSUE TITLE
Oshan missile arrival doesn't seem to work

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#11060]
### Labels

[BUG][minor]

### Description

When I spawned in on oshan, I instantly appeared in arrivals

### Steps to reproduce

1. connect to oshan round
2. spawn in
3. don't come from a missile

### Expected Behavior

I should spawn in a missile

### Additional Information & Screenshots

Could be admin intervention, or a 1-off fluke. Auto-adding the reproducing tag in case either are true.
![image](https://user-images.githubusercontent.com/96703882/192848230-9a0926d7-589e-4f5e-a401-c7fe1628079f.png)

**Comment by nefarious6th** [comment]
verified
