### ISSUE TITLE
Containers don't show how full they are on mouse over

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1108]
**Describe the bug**
When you mouse over a container, it no longer tells you how many items are in it.

**To Reproduce**
1. Mouse over a container
2. Do not see X/7 or whatever number it may be

**Expected behavior**
On mouseover, the tool tip used to display how many items were in the container out of the maximum.

[BUG}

**Comment by RSG250** [comment]
Ill add that beakers mouse over showing whats in them isnt refreshing aka, say you had 100 charcoal in a beaker, empty it , mouse over will still show 100 charcoal in it

**Comment by Tarmunora** [comment]
Tooltip caching bug
