### ISSUE TITLE
Borgs can Drink

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#11092]
### Labels

[BUG]

### Description

Borgs, specifically the brobocop module, can drink from pitchers and beer bottles.

### Steps to reproduce

1. Be Borg
2. Be Brobocop
3. Click yourself with your beer
4. Notice you "Drink" some.

### Expected Behavior

To not be able to drink

**Comment by Saicchi** [comment]
Do you really drink it ( remove reagents from the pitcher ) or does it only play the drinking animation?
Making the AI drink booze is fun ( only plays animation, doesn't remove any reagents from the bottle ).

**Comment by Wisemonster** [comment]
Animation only

**Comment by TheTyrant25** [comment]
related to #11772 , where borgs drink unstable mutagen
