### ISSUE TITLE
Brig chutes are releasing people as incarcerated

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#11091]
### Labels

[BUG]

### Description

Title, instead of putting them on released, they come out as incarcerated, despite not being that

### Steps to reproduce

1. Have sec huds
2. Throw stirstir into the brig release chute
3. Notice they have an I next to them when released, instead of an R

### Expected Behavior

For them to be changed to released

**Comment by Gerhazo** [comment]
Partially rectified in #11306
(though not fixed, since this is most probably not a bug and just one of the cases mentioned in the previous comment occuring)

**Comment by Chatauscours** [comment]
Got fixed in #11306 and one of the commits that go gut pushed shortly afterwards that I am unable to find.
