### ISSUE TITLE
Cannot swirlie people because they have no head, except they do have a head

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#11105]
### Labels

[BUG]

### Description

^

### Steps to reproduce

1. Try to swirlie someone
2. Observe their head

### Expected Behavior

I expected to be able to swirlie crimers

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/20713227/193421100-4033431f-b9b4-4515-b1bd-48481e362000.png)

**Comment by nefarious6th** [comment]
Introduced in #10989

**Comment by TobleroneSwordfish** [comment]
Oh yeah, it's checking if they have something _on_ their head not if they have a head.
