### ISSUE TITLE
Gaping hole in chest cannot be surtured

### ISSUE THREAD

**Issue by Glamurio** [goonstation/goonstation#11130]
### Labels

[BUG][MAJOR]

### Description

When trying to surture a gaping hole shut, it won't work.

### Steps to reproduce

1. Find an injector artifact that injects you with a strange stone.
2. The strange stone will randomly mutate you into a different race.
3. Have the stone implant be removed while having a gaping hole and reinject yourself with it afterwards.

### Expected Behavior

The surture should be able to remove the gaping hole

### Additional Information & Screenshots

Here's a screenshot of the ingame text. Silas Moore is me.
![image](https://user-images.githubusercontent.com/51779813/193460590-009ed10e-ef3d-453e-97aa-0d3d57243fcc.png)

Additionally, this caused me to be unable to breathe O2 even though I had lungs. This was fixed upon transforming again.

**Comment by Glamurio** [comment]
Follow-up on this, I had this happen recently unrelated to the artifact in question. It seems that sometimes gaping holes just cannot be fixed, period.

**Comment by Gerhazo** [comment]
It seems grab intent is required to suture the chest cavity, could this not be a bug and a case of user error (and somewhat confusing intent management)? Or was the intent definitely in use during attempts?

**Comment by Glamurio** [comment]
That's a good question, was this changed? I certainly wasn't aware that Grab intent is necessary. At least two different doctors have tried, I did not confirm whether or not they were on Grab intent, I know I wasn't. It's possible it's a user error and this should be made clear somehow. Certainly not by saying "You have no wounds or incisions to close", since that clearly means the suture is being used correctly, maybe just not in the correct context.

**Comment by Gerhazo** [comment]
It's been as such for a long time.

Depending on whether the grab intent is used, the chest might be sewn closed with or without having sewn in the item inside (assuming one was placed) securely. This affects some interactions with the chest cavity item.

There are probaly ways to improve this (like a message when examining or otherwise), but for the topic at hand, this may have been user error and not a bug.
