### ISSUE TITLE
Beepsky has lost their voice

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#11153]
### Labels

[BUG]

### Description

Beepsky no longer plays their voice lines, only have the text above them.

### Steps to reproduce

1. Be criminal
2. Go to beepsky
3. Notice they say their line, but don't use their dectalk
4. Be sad and arrested

### Expected Behavior

For beepsky to use their voice

### Additional Information & Screenshots

Seems to be tied with dectalk in general being broken.

**Comment by Gerhazo** [comment]
Can't seem to reproduce. Also I'm fairly sure beepsky uses preset sound files, don't think dectalk is involved.

**Comment by thegrb93** [comment]
Oddly, I don't see any reference to VOXsound["beepsky"] or playsound with "sound/vox/beepsky.ogg" in the source code. Maybe it was accidentally removed?

**Comment by MetricDuck** [comment]
I just got told by beepsky I couldn't outrun a radio - seems ok to me?

**Comment by thegrb93** [comment]
I think those are generic robot voice lines though.

```
	'sound/voice/bgod.ogg'
			, 'sound/voice/biamthelaw.ogg'
			, 'sound/voice/bsecureday.ogg'
			, 'sound/voice/bradio.ogg'
			, 'sound/voice/binsultbeep.ogg'
			, 'sound/voice/bcreep.ogg'
			)
```

**Comment by thegrb93** [comment]
Oh, maybe those are the correct ones. Perhaps it is working correctly.
