### ISSUE TITLE
Certian Drone not doing damage

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1116]
[BUG]

**Describe the bug**
the Saw drone, along with the fish drone and the shark drone are not doing any damage, other drones may be affected

**To Reproduce**
1. get in pod or sub
2. sit next to above mentioned drones
3. be amazed that there is no damage

**Expected behavior**
pod get hurt

**Comment by zjdtmkhzt** [comment]
I think there was a thing about those using 1 range projectiles, so they may be affected by projectile changes?

**Comment by Sovexe** [comment]
this extends to a number of the drones including the y drone. Basically every drone I've tested other than the X drone is unable to shoot. I'm trying to see if I can't fix it
