### ISSUE TITLE
Mech Comp Button is missing it's pushed icon

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#11167]
### Labels

[BUG]

### Description

The button that mechanics get for mech comp stuff is missing it's icon when pressed, causing the sprite to dissapear

### Steps to reproduce

1. Get mech comp button
2. Wrench it down
3. Push
4. See magic dissapearing button

### Expected Behavior

For it not to dissapear

**Comment by 112358sam** [comment]
I haven't been able to replicate this on local. Has this been fixed?

**Comment by TealSeer** [comment]
Cannot reproduce, most likely fixed
