### ISSUE TITLE
Character sprite turns invisible after limb replacement

### ISSUE THREAD

**Issue by Glamurio** [goonstation/goonstation#11172]
### Labels

[BUG][MAJOR]

### Description

After a limb has been replaced, the character sprite is invisible

### Steps to reproduce

1. Replace a limb on a character
2. The sprite turns partially invisible (face, hair)
3. Changing clothing items to toggle different parts of the sprite invisible.

### Expected Behavior

I expected my character sprite to remain non-transparent

### Additional Information & Screenshots

Full screenshot with equipment
![image](https://user-images.githubusercontent.com/51779813/193891158-3b4c9ac8-8c64-4e15-adff-35a76737d854.png)

Variants produced by re-equipping clothing items.
![image](https://user-images.githubusercontent.com/51779813/193890919-37522012-6fc0-485e-b5cb-148dc98b0f85.png)
![image](https://user-images.githubusercontent.com/51779813/193890947-86d7169d-6bf0-45d8-bac4-6a934c4fc4c5.png)
![image](https://user-images.githubusercontent.com/51779813/193891006-a33fbe34-c9d2-4074-82a5-e0d65bcb0f57.png)
![image](https://user-images.githubusercontent.com/51779813/193891043-a82648c9-07dd-48ba-8b3c-daf087338715.png)

**Comment by nefarious6th** [comment]
Related to #7732

**Comment by TealSeer** [comment]
Most likely fixed in https://github.com/goonstation/goonstation/commit/dfe2096953affe9a96f1ebf9d39c6b3553260ba6
