### ISSUE TITLE
Soul Guard seemingly doesn't work in shuttle transit

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#11179]
### Labels

[BUG]

### Description

I took soul guard and got thrown off the shuttle, but got kicked straight into ghost.

### Steps to reproduce

1. Be wizard take soul guard
2. Get thrown off departed shuttle
3. The Soul Guard takes a nap

### Expected Behavior

Soulguard respawns me at wizard den

**Comment by MetricDuck** [comment]
The cordon is one of the few things that will permakill soulguard & shield of souls as it skips the fluff and sets death directly. Unsure if this is a feature or not

**Comment by Retrino** [comment]
this should no longer be an issue since being shuttle tossed no longer insta kills you with the cordon
