### ISSUE TITLE
Martian warriors are weak

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#11190]
### Labels

[BUG]

### Description

When letting martian warriors do their thing, absolutely nothing happens

### Steps to reproduce

1. Go to the martian ship
2. Stand still
3. Get strangled by martian warriors
4. Your neck is too strong for their tentacles

### Expected Behavior

I expected a stranglehold to actually strangle or at least harm you in any way

**Comment by ZeWaka** [comment]
they're doing brain damage
