### ISSUE TITLE
Monster burgers make mentor mice mighty unmurderable

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#1120]
[BUG]

**Describe the bug**
Earlier, I went to the bar as a mentor mouse and ate a the monster, and from it obtained the intrinsic healthboost. The chef didn't like this, likely because I assumed I wouldn't eat the whole thing in one bite, and started attacking me with his cleaver. My health icon did not change from the full-health green, even after nearly a dozen whacks of his knife, more than enough to seriously mess up an actual crewhuman. Only after I completely bled out did I actually die.

**To Reproduce**
1. Assume the purple mousie position
2. Eat a the monster hugeburger
3. Piss off the chef into trying to murder you
4. Be not-murdered, despite being thoroughly robusted

**Expected behavior**
Dying after roughly 5 hits.

**Additional context**
I did get stunned pretty badly from the fighting and the burger, though.

**Comment by Tarmunora** [comment]
Issue revolves around healthholders having a minimum value i.e.: maximum amount of damage they can take.

**Comment by flappybatpal** [comment]
This is probably fixed by https://github.com/goonstation/goonstation/commit/a8af69b76e9907b8f2148e6b9d9916cb9423bc27 ?
