### ISSUE TITLE
Goon2 centcom canvas crashes game

### ISSUE THREAD

**Issue by mantwerp** [goonstation/goonstation#11226]
### Labels

[BUG]

### Description

The canvas on centcom has been crashing everybodys game for like two weeks now

### Steps to reproduce

1. (somehow) survive a shift
2. can't wait to place the pixel youve worked so hard for
3. attempt to click the canvas
4. game crashes
5. weep

### Expected Behavior

canvas worky not broky

### Additional Information & Screenshots

https://media.discordapp.net/attachments/1013186238192291941/1026557213034156043/unknown.png?width=1156&height=613

**Comment by TheTyrant25** [comment]
uhhh well goon2 no longer exists so this isn't an issue anymore so
