### ISSUE TITLE
Pipebomb assemblies specifically require unsecured assemblies to make

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11256]
### Labels

[bug]

### Description

When making the three flavours of pipebomb assembly, you can't secure the timer/signaller/proximity-igniter assembly for some reason.

### Steps to reproduce

1. Make some pipebombs until you've done the wiring stage
2. Make some igniter assemblies and secure them
3. Hit the bombs with your assemblies, have nothing happen
4. Unsecure the assemblies, try again successfully

### Expected Behavior

For just secured assemblies to work

### Additional Information & Screenshots

For timer/igniters, make sure to do the hit-assembly-with-bomb route. The recipe where you hit the bomb with the timer/igniter doesn't actually care whether the assembly is secured. Not that I count that as a pipebomb assembly but it's worth pointing out.

**Comment by pgmzeta** [comment]
Fixed with #15687
