### ISSUE TITLE
Borg slowed when dragging someone.

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1126]
[BUG]

**Describe the bug**
When dragging someone, borg are being slowed as is the normal case with humans. I didn't see anything in the changelog so I assume this is a bug?

**To Reproduce**
1. Be borg
2. Drag person alive or dead
3. Be super slowed
4. Be sad

**Expected behavior**
Being able to drag someone at normal speed.

**Comment by Tarmunora** [comment]
Borg has overriden movement_delay proc. Whoever looks at this should migrate borgs to movement modifier system.
