### ISSUE TITLE
filling a sleepy pen produces a sound

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#11270]
### Labels

[BUG][MAJOR]

### Description

same as title, has no chat message but still has a sound

### Steps to reproduce

1.  pour stuff from a beaker into a sleepy pen
2.  noise

### Expected Behavior

fully silent

### Additional Information & Screenshots

im assuming that is not on purpose since it hides the chat message

**Comment by BatElite** [comment]
Definitely need confirmation on this, but I thought that refilling the pen was meant to be a fairly high profile thing that could tip off others.

**Comment by UrsulaMejor** [comment]
intended imo; many stealthy items have periods where they are loud
