### ISSUE TITLE
Some StG cards have "bad icon" as their face side

### ISSUE THREAD

**Issue by TheRealMrN** [goonstation/goonstation#11272]
### Labels

[BUG] [MINOR]

### Description

Same as title

### Steps to reproduce

1. Get a deck of StG cards
2. Search for one with a bad icon

### Expected Behavior

For it to show a face side and not take up half the table

### Additional Information & Screenshots

Only happened on the atmospheric technitian and medical doctor cards while playing
https://media.discordapp.net/attachments/720461884909813830/1028144576059408534/unknown.png

**Comment by flappybatpal** [comment]
Fixed by 1dc31e002bcfd73b1aa3be0f536f282cbcda8da8
