### ISSUE TITLE
screwing in an emergency light turns it on regardless of emergency status

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11273]
### Labels

[minor]

### Description

As title.

### Steps to reproduce

1. Take out an emergency light's bulb
2. Reinsert it

### Expected Behavior

For it not to turn on when emergency isn't active

**Comment by frawhst** [comment]
You can take those bulbs out??????

**Comment by BatElite** [comment]
You used to not be able to, but at some point that got changed I guess (#8986 apparently)

**Comment by Chatauscours** [comment]
Duplicate of #9055
