### ISSUE TITLE
Flockmind blocked by shuttle walls

### ISSUE THREAD

**Issue by Ricviu** [goonstation/goonstation#11310]
### Labels

[BUG]

### Description

Flockmind cannot pass through shuttle walls, except diagonals. This includes the structure in the SE space of the Atlas map.

### Steps to reproduce

1. Be on Atlas
2. Spawn as a flockmind
3. Fly through space to the structure in the SE of the map
4. Move into the walls, fail to move through any but the diagonals (windows and doors are not blocked)

### Expected Behavior

Flockmind moves over walls as if it was not physical

**Comment by FlameArrow57** [comment]
#10193
