### ISSUE TITLE
cant go thru wet concrete

### ISSUE THREAD

**Issue by Adharainspace** [goonstation/goonstation#1134]
[BUG]

**Describe the bug**
wet concrete objects cant be walked through

**To Reproduce**
1. get beaker of concrete
2. pour on the floor
3. try to walk through it and not be able to

**Expected behavior**
you should be able to walk thru wet concrete slowly

**Screenshots**

**Additional context**
issue is in code/obj/cement.dm, probably has to do with the canpass proc?? unsure

**Comment by Laboredih123** [comment]
This is no longer a bug due to #2295.
