### ISSUE TITLE
Old Jukebox cannot be claimed as a spy objective.

### ISSUE THREAD

**Issue by ThePastTenseOfYeetIsYote** [goonstation/goonstation#11343]
### Labels

[BUG]

### Description

Old Jukebox cannot be claimed as a spy objective.

### Steps to reproduce

1. Try to claim old jukebox for an objective, it doesn't work.
2. Try to claim it while its playing, doesn't work.
3. Try to click drag the jukebox onto pda, doesn't work.

### Expected Behavior

Claim the jukebox for sick loot as a spy.

**Comment by swinglow20** [comment]
Would you need to unsecure it to claim the reward?

**Comment by BatElite** [comment]
Basically yeah. IIRC since it's _technically_ an item you have to deliver it in a specific room.

Maybe that's what happened here?

**Comment by ZWRh3** [comment]
likely the same for piano and its subtypes

**Comment by frawhst** [comment]
e93f559
