### ISSUE TITLE
Unable to change the default frequencies of a Shock Kit

### ISSUE THREAD

**Issue by vortex1942** [goonstation/goonstation#11355]
### Labels

[BUG][MINOR]

### Description

Clicking any buttons for the frequency menu on the shock kit causes the menu to close instantly

### Steps to reproduce

1. Interact with a shock kit item
2. Press any of the hyperlink buttons in the menu
3. The menu will close without changing any of the frequencies

### Expected Behavior

The frequencies should be able to be adjusted. This has worked in the past.

**Comment by TealSeer** [comment]
Fixed in #17031
