### ISSUE TITLE
emoji crew names screws up AI tracking

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11363]
### Labels

[BUG][major]

### Description

If you try to track with an emoji for a name, it'll instead try to have your browser navitage to where it's getting the twemoji icon from I think?

### Steps to reproduce

1. Have someone with an emoji for a name (I think this is possible with jobs that let you rename)
2. Try to track them as AI (clicking their name in chat)
3. have your browser take over and open up nothing instead??

### Expected Behavior

For crew tracking not to get screwed by this

### Additional Information & Screenshots

This is what the borked link looked like:
![image](https://user-images.githubusercontent.com/31984217/195914414-ba2b8ca3-10a6-4147-af72-f0f85dc4c16e.png)

This is the "URL" that my browser tried to navigate (I don't think there's anything in there that would be bad to share here, right?):
`file:///E:/Games/byond/bin%00/?src=[0x203e3f3];track3=%3Cimg%20class=%22emoji%22%20draggable=%22false%22%20alt=%22%f0%9f%91%bb%22%20src=%22https://twemoji.maxcdn.com/v/14.0.2/svg/1f47b.svg%22/%3E;track2=[0x30000fd];track=[0x300013f]`

**Comment by frawhst** [comment]
a vision into a cyberpunk future. changing your name to an emoji to crash the tracking software

**Comment by Glamurio** [comment]
Emojis were a mistake, remove them all

**Comment by TealSeer** [comment]
fixed in https://github.com/goonstation/goonstation/commit/e2e92814ce9f9bd552a0112a713bfc1bb344c17f
