### ISSUE TITLE
Pizza boxes allow for borg item sharing

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#11365]
### Labels

[BUG]

### Description

You can use pizza boxes to drop items as a borg

### Steps to reproduce

1. be a borg with a carbon friend
2. Obtain open pizza box
3. Have borgs place items in box
4. Pick them up as carbon
5. Am able to use items

### Expected Behavior

Should not be able to do any of this

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/195926648-ea608ba4-22e4-446e-afe8-ddf89f797ec3.png)

**Comment by NightmareChamillian** [comment]
courtesy pinging @CaioFrancisco

**Comment by CaioFrancisco** [comment]
#11364 duplicate. I will be closing this one to keep it clean.
