### ISSUE TITLE
Mentor mice sprint weirdly

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#1138]
[BUG]

**Describe the bug**
Sprinting as a mentor mouse doesn't seem to work properly. Holding down shift and running only allows the mouse to sprint for a brief moment, consuming around 15 stamina before going back to normal speed. Spamming shift allows the mouse to briefly sprint with each press of shift, however this doesn't seem to consume much (if any) additional stamina, allowing the mouse to sprint forever in tiny, tiny increments. 

**To Reproduce**
1. Get that horrible purple
2. Be mouse
3. Sprint
4. Fail to sprint more than a split second
5. Spam sprint and never get tired

**Expected behavior**
Mouse run fast, then later get tired and not run fact.

**Additional context**
My client is laggy as heck and I'm not 100% sure sprint-spamming actually makes the mouse all that much faster. Or if sprinting makes any actual speed increase. 85-90% sure it does, but that could just be coincidental lag.

**Comment by pali6** [comment]
Not a bug according to @mybluecorners .
