### ISSUE TITLE
Arc electroplater does not require power to function

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11392]
### Labels

[BUG]

### Description

As title. 

### Steps to reproduce

1. Turn off everything in the APC for the room where the plater is in
2. Load a material and item into the electroplater
3. Get a plated item without needing power

### Expected Behavior

For the plater not to function unpowered.

**Comment by RSG250** [comment]
question is what should it do if its already doing its job and power goes out.

**Comment by BatElite** [comment]
I feel it'd be fine if it finishes the job in that case, pretend there's a big capacitor in there or something

That or eject the item while eating the material, for some plausibly deniable sabotage potential
