### ISSUE TITLE
Antag Critter Spiders eject their brains on growing up

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#1139]
[BUG]

Description: After draining a suitable target, the antag space spider will harmlessly eject its own brain when it grows up.

Reproduction:
Drain a corpse.
Spider grows up and brain belonging to space spider pops out.

Expected behavior: 
Spider doesn't eject brain.

[/BUG]

**Comment by Xkeeper0** [comment]
I asked and apparently this is still happening with space spiders? Needs to be tested
