### ISSUE TITLE
Missing/incorrect cloner console sprite

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#11455]
### Labels

[BUG] [MAJOR]

### Description

Cloning console is missing its frame and the screen is very faint. also needs to be interacted with with right click context menu.

### Steps to reproduce

1. look at cloning console in south facing direction when someone can be cloned(?)

### Expected Behavior

It shows up normally

### Additional Information & Screenshots

![Screenshot 2022-10-19 220529](https://user-images.githubusercontent.com/113442598/196804127-55d43670-db51-4727-8a9a-4732ae104fff.png)

**Comment by CheffieGithub** [comment]
This was also an issue in the nadir playtests so I can only assume it has something to do with that.

**Comment by Kubius** [comment]
Yep, goofed this. Fix coming soon.
