### ISSUE TITLE
Joining on Nadir with Mail Order will not spawn your character

### ISSUE THREAD

**Issue by vortex1942** [goonstation/goonstation#11463]
### Labels

[BUG][MAJOR]

### Description

When latejoining on Nadir with the Mail Order purchase I was not spawned anywhere, The mail order retried 3 times and did not put me anywhere.

### Steps to reproduce

1. Purchase the Mail Order spacebux option
2. Late join on the server
3. Spawn in the void?

### Expected Behavior

I expected to be mailed through in the crate :(

### Additional Information & Screenshots

![Goonstation 3 Roleplay Morty The Curse of Nadir Extraction Site 2022-10-20 133721](https://user-images.githubusercontent.com/22815407/196843957-0cb941a4-ea46-4053-a470-a2572ca08a09.png)

Additionally, accessing my space GPS did not give me any coordinates when I was in this null space

**Comment by Kubius** [comment]
Drat. I was hoping this would work once secret submodule was involved; will be devising an alternate solution soon.
