### ISSUE TITLE
Maximum recursion level reached

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#11479]
### Labels

[INTERNAL][RUNTIME]

### Description

Runtime occurs shortly after starting a build in game

### Steps to reproduce

1. Start round instantly when game says ready
2. Wait a small amount of time, less than a minute

### Expected Behavior

For no runtime

### Additional Information & Screenshots

In code\obj.dm
![image](https://user-images.githubusercontent.com/53062374/197076839-8109672d-9f27-4e7f-a02c-ee3648a506ca.png)

![image](https://user-images.githubusercontent.com/53062374/197078101-785c0b6e-db32-4017-89d2-90d25d6ba195.png)

![image](https://user-images.githubusercontent.com/53062374/197078083-8e1f82c0-b959-4d54-8d76-28169f6209f5.png)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/bd32c00fdccc3b95631e85713319f430bcbabc8d
