### ISSUE TITLE
Sea elevator shaft can be walked on

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#11472]
### Labels

[BUG] [MINOR]

### Description

If you send the sea elevator down to the trench the shaft thats left can be walked on normally

### Steps to reproduce

1. send the elevator down while not on it
2. walk on the shaft with the power of magic

### Expected Behavior

you fall down and break your legs

### Additional Information & Screenshots

![Screenshot 2022-10-20 163603](https://user-images.githubusercontent.com/113442598/197032886-6d6d5c81-0c13-485c-b935-8f3f518809cf.png)

**Comment by Kubius** [comment]
Area seems to be configured the same on both Oshan and Nadir; doing some local repro attempts soon.

**Comment by Kubius** [comment]
![image](https://user-images.githubusercontent.com/12454065/197294849-132e62c4-1b6d-4014-a509-418a0f6f5882.png)
Seems to happen on Oshan too.

**Comment by CheffieGithub** [comment]
yeah it seems to be a general issue with the elevator shaft

**Comment by BatElite** [comment]
the fucking seafall landmarks broke??

**Comment by Kubius** [comment]
Think I may have figured this out; checking now. If this issue doesn't get mentioned from a PR within an hour, I didn't figure it out.

**Comment by CheffieGithub** [comment]
Im pretty sure this was fixed a while ago, closing now.
