### ISSUE TITLE
Item arm delimbing itself breaks the item arm

### ISSUE THREAD

**Issue by PrimeNumb** [goonstation/goonstation#1148]
[BUG]
**Describe the bug**
Title. Instead of the item dropping, it drops a duplicate arm.

**To Reproduce**
Replace one of your arms with an item. Then target that arm and delimb (katana and csaber are both able to do this). Now the item will be stuck in the hand slot forever.

It's possible that you need to be disarmed by someone else for this, not sure.

**Expected behavior**
The item you used as an arm should drop, instead of an actual arm.

**Comment by Tarmunora** [comment]
Could not reproduce
