### ISSUE TITLE
Characters do not fall down the trench elevator on Nadir

### ISSUE THREAD

**Issue by vortex1942** [goonstation/goonstation#11505]
### Labels

[BUG][MINOR}

### Description

If you stand ontop of the elevator shaft you will not fall down it

### Steps to reproduce

1. Lower Elevator
2. Stand on the exposed elevator shaft

### Expected Behavior

I expect to fall down the elevator shaft in a blaze of glory

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/22815407/197294091-0a682c1b-86e6-486f-823f-9b94053ba8dc.png)

**Comment by Kubius** [comment]
Duplicate with #11472.
