### ISSUE TITLE
Oshan hotspots can be under arrivals

### ISSUE THREAD

**Issue by ATDoop** [goonstation/goonstation#11511]
### Labels

[BUG]

### Description

hotspot seemed to have moved/spawned under arrivals and started creating fires, this probably shouldn't happen

### Steps to reproduce

1. have a hotspot move under arrivals
2. watch as it lights arrivals on fire

### Expected Behavior

arrivals should be safe from hotspots

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/1959416/197313587-1995f701-0ad3-4e9d-875b-9d8276c5f3f3.png)

**Comment by TheTyrant25** [comment]
this doesn't seem like a bug to me. A naturally moving hotspot has no reason to bounce off arrivals instead of going under it like normal.

Going to go ahead and say this is intended behaviour.
