### ISSUE TITLE
Cloning completes at too high of a health threshold

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1152]
[BUG]

**Describe the bug**
Lately, cloning has been taking an absurdly long time to complete, slowing down ridiculously at high completion percentages and sometimes with the completion percentage going down.  Turns out the pod is considering cloning complete at 90% health, when before it considered it complete at ~70% health.

**To Reproduce**
1. Clone someone
2. Periodically check the pod both with a hand and with a health analyzer to see how complete it is and what damage the cloned person has.

**Expected behavior**
The expected behavior is for cloning to take about the same amount of time for every person being cloned and, if allowed to complete naturally, to eject the clone unconscious and in yellow health with some brain damage.  Right now, the time it takes is highly variable.  Epinephrine only heals TOX when health is from -65 to -10.  When your BRUTE damage hits 0, the cloned person will pretty consistently have about 30 TOX.  Now, your TOX does go down very slowly after that, so something in the pod is healing TOX (I assume epinephrine has an RNG based chance to heal TOX outside of crit, like ephedrine does, that isn't documented on the wiki, although I suppose perfluorodecalin could be the one with an undocumented and random TOX healing since I don't use it enough to definitively know that it does not heal TOX).
But if cloning is currently relying on undocumented behavior to _even finish at all_ without additional TOX healers being added, something is clearly wrong.

[BUG]

**Comment by Tarmunora** [comment]
Two notes:
1. heal_level appears to have been 90 for well, at least the last 3 months (extent of public git history)
2. Clonepod itself has passive non-chem healing (relevant is the 0.5 tox heal per cycle)

**Comment by Gerhazo** [comment]
I remember cloned people coming out at 90 health for a very long time, because I'd often inject tiny amounts of charcoal to make up for specifically that amount.

**Comment by Cthucky** [comment]
Odd, I distinctly remember it spitting people out at 70 health for most of the time I've been playing, which admittedly is only since Jan 2019 or thereabouts.  Perhaps spitting them out at 70 health with brain damage was itself the bug.  That said, ff that's not the reason why cloning seems to stall out around 90% complete, then perhaps something went wrong with the clone pod heal (which I did not know about) when the life cycle got reworked recently.  I recall there being other problems from that.

Something is definitely broken, though.

**Comment by TDHooligan** [comment]
may be notable that the last time this occurred to me i had continual messages similar to heart failure - Your arm hurts!
- Your chest hurts!

**Comment by phyvo1** [comment]
In my experience this past year as a medical doc it seemed that the cloner was spitting people out mostly with 20-30 tox damage that I had to clean up afterwards. I went on a bit of a haitus though so I don't have a good grasp of recent cloning.

**Comment by Tiggersaurus** [comment]
> In my experience this past year as a medical doc it seemed that the cloner was spitting people out mostly with 20-30 tox damage that I had to clean up afterwards. I went on a bit of a haitus though so I don't have a good grasp of recent cloning.

Can confirm. As mediborg I'd have to inject people with 15u charcoal when they popped out due to 30 tox so something changed.

**Comment by ThePotato97** [comment]
I assume this has been fixed.
