### ISSUE TITLE
Adding a "Needs Reproducing" label to an issue then commenting why removes the label

### ISSUE THREAD

**Issue by MetricDuck** [goonstation/goonstation#11567]
### Labels

[BUG]

### Description

Adding a "needs reproducing" label to an issue and then commenting why you've added the label removes the label. Fully appreciate it's an automated action to "stale" issues and it's a good idea, but would is it be possible to add a short grace period?

### Steps to reproduce

1. Add a "needs reproducing" label to an issue
2. Comment a couple of sentences saying as such
3. Automated workflow removes the needs reproducing label

### Expected Behavior

Ideally it would have a small grace period where you could comment before it removed the label. 

### Additional Information & Screenshots

I appreciate you can just add the label after commenting / readd the label but github actions aren't instantaneous, and it's really easy mistake to make if you aren't paying attention. Source: I made this mistake a bunch.

**Comment by MetricDuck** [comment]
L + ratio + unable reproduce + read the contributor guidelines

**Comment by MetricDuck** [comment]
38 minutes later?

**Comment by MetricDuck** [comment]
2 hours

**Comment by MetricDuck** [comment]
3 hour grace period?

**Comment by flappybatpal** [comment]
Test comment as requested. I have no idea what is going on with messages here.

**Comment by MetricDuck** [comment]
Just gonna assume higher minds are doing things in the automated workflow

**Comment by frawhst** [comment]
The was originally an issue when I added issue staling, but I fixed it about a week after. If you see any erroneously removed labels feel free to re-add them.

**Comment by MetricDuck** [comment]
Ya that makes sense, I noticed it happening somewhere on the 5th page
