### ISSUE TITLE
Revhead/Command staff trackers don't work

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#11572]
### Labels

[BUG]

### Description

The revhead and command staff pda programs don't work

### Steps to reproduce

1. Rev round
2. Open pda apps
3. Try searching for nearest head

### Expected Behavior

For the apps to work

### Additional Information & Screenshots

Pressing the button to search doesn't work. Pressing refresh shows values for the stats displayed as empty

**Comment by ThatFiveGuys** [comment]
Should be fixed
