### ISSUE TITLE
capybara death sprite is not displayed

### ISSUE THREAD

**Issue by wolfolotl** [goonstation/goonstation#11601]
### Labels

[BUG] [MINOR]

### Description

when the capybara is killed, it does not switch to its dead sprite. rather, it becomes completely transparent

### Steps to reproduce

1. find capybara
2. choke down your humanity and kill it
3. get surprised when it disappears

### Expected Behavior

for the capybara to display its death sprite

### Additional Information & Screenshots

the issue isn't caused by a lack of a death sprite, since I drew one and put it in the dmi and everything

**Comment by Retrino** [comment]
tried on local and live, both show death sprite

not sure what circumstances caused your capybaras death, in fact strangling seemed to do no damage to the capybara at all

**Comment by wolfolotl** [comment]
it might actually be specifically when it's sitting down, since in the instance I noticed this it was being knifed to death by a chef while it was sitting
