### ISSUE TITLE
Revhead/Command staff tracker unlocks in half the time

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#11619]
### Labels

[BUG]

### Description

The revhead/command staff tracker pda programs unlock around 15 minutes

### Steps to reproduce

1. Rev round
2. Reach around 15 minute mark
3. Program unlocks

### Expected Behavior

For the pda programs to unlock around 30 minutes

**Comment by TobleroneSwordfish** [comment]
I guess half hour SPAWNs aren't very reliable, possibly something kills the proc for being idle for that long?

**Comment by ThatFiveGuys** [comment]
Got a report of the tracker also not being sent out for a 30 minute round, was early on (meaning smaller pops), it may scale with lag in the opposite way or something like that? But either way SPAWN probably shouldnt be used here
