### ISSUE TITLE
MechComp vendor stock transforms into wifi splitters after one purchase

### ISSUE THREAD

**Issue by HBS-System** [goonstation/goonstation#11623]
### Labels

[BUG]

### Description

When gathering components from the MechComp vendor, the first purchase is fine but immediately after it goes through EVERYTHING becomes a wifi splitter until you refresh the window

### Steps to reproduce

1. Get a MechComp vendor
2. Purchase anything
3. Withess the army of wifi splitters!

### Expected Behavior

I expect the stock to not magically become the same item, and to stay consistent.

**Comment by TobleroneSwordfish** [comment]
must've been #11616 somehow I guess?

**Comment by pali6** [comment]
Hmm, hasn’t happened to me when testing but I haven’t tested this particular vending machine.

**Comment by TobleroneSwordfish** [comment]
someone said it was happening with seaweed in the kitchen vendor too

**Comment by pali6** [comment]
Fixed by #11627
