### ISSUE TITLE
ValuChimp monkey icons have human heads

### ISSUE THREAD

**Issue by ATDoop** [goonstation/goonstation#11631]
### Labels

[BUG]

### Description

the valuchimp icons are scary and have human heads!!!

### Steps to reproduce

1. click valuchimp
2. get scared

### Expected Behavior

Monkeys look normal

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/1959416/198301647-80b7a4f9-a5ec-414e-9123-ac2f86b0b3e0.png)
also, I was in the afterlife bar when I saw this if that changes anything.

**Comment by TealSeer** [comment]
Cannot reproduce, thankfully
