### ISSUE TITLE
Head Light of the Space Helmat

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1164]
[BUG]

**Describe the bug**
Engineering space suit Head Lamp doesnt seem to be working

**To Reproduce**
1. equip helmat
2. turn on head lamp

**Expected behavior**
it should work

**Comment by pali6** [comment]
Can't reproduce.

**Comment by pali6** [comment]
![image](https://user-images.githubusercontent.com/358431/85225731-6740e900-b3d3-11ea-94a9-5cbea6102cda.png)

**Comment by Gannets** [comment]
Working fine for me too, gonna go ahead and close this.
