### ISSUE TITLE
flockcage will still tear you and your items apart after you escape

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1165]
[BUG]

**Describe the bug**
If you escape from a flockcage (I flipped a bunch), the cage, despite no longer existing, will still pull clothing off of you and eventually your limbs and organs.

**To Reproduce**
1. Get caught by a flock cage
2. Escape
3. Oh god the horror

**Expected behavior**
Escaping from the cage should prevent you from being torn to bits.

[BUG]

**Comment by moonlol** [comment]
cant reproduce on local. Most likely a runtime
