### ISSUE TITLE
space diner backroom can be a bounty delivery location on nadir

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#11678]
### Labels

[BUG]

### Description

you can get the space diner backroom as a bounty delivery location when a spy on nadir

### Steps to reproduce

1. be a spy
2. see that sweet mindhack implant bounty with a delivery location to the space diner backroom
3. waste time trying to break down an rwall into a 1x3 room for a delivery
4. question whether there were better opportunities

### Expected Behavior

it just seems a little odd that it can be a delivery location since it's kind of obtuse to get to and no other small areas like that on donut3 or cog1 count as bounty areas. maybe it can be excluded from the potential areas?

**Comment by Kubius** [comment]
There are two ways into it without disassembly; however, I think the backroom could reasonably be extended to encapsulate not just the little 1x3 area. Noted for future change.

**Comment by nefarious6th** [comment]
i only just discovered how today, no worries ;)
