### ISSUE TITLE
Chameleon bombs can't scan items in your inventory

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#11708]
### Labels

[BUG]

### Description

Chameleon bombs can't scan items that are in hand or in your inventory

### Steps to reproduce

1. Have chameleon bomb
2. Click item in hand or in inventory

### Expected Behavior

For the chameleon bomb to scan the item

### Additional Information & Screenshots

No feedback is given when trying to scan the item

**Comment by MetricDuck** [comment]
It's because they're forbidden from scanning things on the HUD plane
