### ISSUE TITLE
GPS in mining sub not working

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#1173]
[BUG]

**Describe the bug**
While in a mining sub, the space gps item does not work. Not sure if this is true for all subs

**To Reproduce**
1. Get Space GPS
2. Go to trench
3. Get in sub
4. Try to input GPS coordinates

**Expected behavior**
GPS coordinated entered for tracking

**Comment by Adharainspace** [comment]
tested and this isnt limited to trench or subs, it doesnt seem to work on any z level when youre inside of a container (pod, locker, sub)
