### ISSUE TITLE
Pump Control UI has no titlebar/controls on Underwater Cogmap1

### ISSUE THREAD

**Issue by cassinidev** [goonstation/goonstation#1174]
[BUG]

On the underwater Cogmap1, bringing up the engine pump control UI causes it to create a window without a title bar and controls, meaning you can't close it. It stays onscreen permanently.

**To Reproduce**
1. Be on Cogmap1. Underwater.
2. Activate the pump control console in engineering.
3. Pump window appears without title bar and close/minimize/maximize controls.
4. Have annoying window that covers up half the center of your screen until reboot.

**Expected behavior**
UI appears with regular window controls to close it again.

**Screenshots**
![pumpfail](https://user-images.githubusercontent.com/8256657/85248807-f673ee00-b41f-11ea-955b-c3e9e81d618c.png)

**Comment by cassinidev** [comment]
Confirmed this happens on Cogmap2 as well. Restart of BYOND necessary to remove UI

**Comment by ZeWaka** [comment]
probably fixed now, if not let me know and i'll make a tgui version
