### ISSUE TITLE
Recent text dropping

### ISSUE THREAD

**Issue by Connie-Dun** [goonstation/goonstation#11811]
### Labels

[BUG]

### Description

Stuff in TGUI radio prompt randomly drops off letters

### Steps to reproduce

1. Use the radio a couple times
2. Notice that sometimes the last letter or two drops off
3. Shake your fist at TGUI (I haven't seen it happen with the still-old-style regular saybox)

### Expected Behavior

Don't drop off letters

**Comment by Retrino** [comment]
doesnt seem to be an issue anymore
