### ISSUE TITLE
Excessive delay when using a vending machine with the new TGUI interface

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#11850]
### Labels

[BUG]

### Description

On a live server, there is a noticeable delay now between pressing the button to vend an item, and actually receiving the item. This did not happen with the previous interface, as it was instantaneous. Perhaps this also ties in to the audio issues mentioned in #11573 ?

### Steps to reproduce

1. Press button
2. Expect item in hand right away
3. Wait full second for vending machine to contemplate the meaning of its existence
4. Receive item, but frustratingly delayed

### Expected Behavior

Cigarettes to be rapidly placed in the palm of my hand to feed my nicotine addiction

**Comment by pali6** [comment]
> it was instantaneous

`vend_delay` has been a thing back then too. Maybe something about tgui makes this feel longer or makes the delay longer but the delay has been a feature for as long as I remember.

https://github.com/goonstation/goonstation/blob/master/code/modules/vending/vending.dm#L69

**Comment by virvatuli-gh** [comment]
bug report is inaccurate after further testing, not sure if it was latency that was throwing me for a loop or something else. will re-report it more accurately if i notice it happening again
