### ISSUE TITLE
Skeleton critters cannot be healed in any way

### ISSUE THREAD

**Issue by MrMagolor** [goonstation/goonstation#1186]
[BUG]

**Describe the bug**
I was respawned as a skeleton critter via the antagonist critter event, and got burned. I tried all manner of things, but nothing increased my HP.

**To Reproduce**
1. Get respawned as a critter skeleton.
2. Get injured in some way.
3. Try to heal yourself.
4. Your HP has not changed.

**Expected behavior**
To be able to have my HP restored.

**Additional context**
The methods I tried were: Applying styptic and sulfadizine chemicals, drinking milk, and using a healing artifact.

The HP was originally lost via being on fire from plasmafire exposure.

**Comment by ZeWaka** [comment]
that's weird, you should be able to drink milk...

**Comment by MrMagolor** [comment]
> that's weird, you should be able to drink milk...

Let me clarify: I was able to drink milk, but it didn't do anything.

**Comment by zjdtmkhzt** [comment]
Skeleton critters seem to have "metabolizes" set to 0, hence they don't actually process the milk and it stays in their system forever, from what I could see. 
Perhaps we should change this to 1, even if it doesn't make much sense for Skeletons to metabolize their chems? Alternatively we could change it to an ingest effect.
