### ISSUE TITLE
Wraith triggers Nadir's acid-detecting IR beams

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#11874]
### Labels

[BUG]

### Description

Pretty much as the title says, be a wraith and fly through the IR beams, triggering them and alerting everyone even though there's no acid to be seen..

### Steps to reproduce

1. Be a wraith, a spooky incorporeal entity that not even humans with ectovision can see
2. Get detected anyways on the IR wavelength
3. Cry ghostly tears because this is pretty shit

### Expected Behavior

True stealth until I choose to reveal myself

**Comment by Kubius** [comment]
Reproduced locally with Cog1's AI core IR beams; confirming that this seems to be an issue with the beams in general, not just Nadir's installation of them.

**Comment by Bartimeus973** [comment]
#11873 fixed it.
