### ISSUE TITLE
Trying to grab someone's pet item spawned using the admin command while it's next to them clicks them instead

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#11886]
### Labels

[BUG]

### Description

Trying to grab someone's pet item using the right-click menu while near them will instead click them with whatever intent you were on.

### Steps to reproduce

1. Give everyone a pet flash
2. Go find Jones
3. Attempt to grab Jones pet flash while near them
4. Notice you pet Jones instead

### Expected Behavior

To grab the item, not pet it's owner

**Comment by Bartimeus973** [comment]
Same as #1780
