### ISSUE TITLE
Atropine disappears when applied to hypo spray

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#1189]
[BUG]

**Describe the bug**
Transfering atropine from the bottles dispensed from the medical venders makes the atropine say its injected int other hypospray when none is and it is consume

**To Reproduce**
1. Get a hypospray
2. Get a bottle of atropine from a medical vender
3. Try to fill hypospray by click and dragging the bottle
4. None added but message given

**Expected behavior**
The hypospray fills with atropine

**Comment by awfulworldkid** [comment]
Not a bug - iirc, atropine isn't in the hypospray whitelist because it has the potential to do significant toxin damage, so when it's added to a non-emagged hypospray it disappears like any other disallowed chem.

**Comment by Gannets** [comment]
Confirmed, atropine is not a whitelisted hypospray chem and is removed when used, printing this message: "The hypospray identifies and removes a harmful substance."

The full whitelist is:
`var/global/list/chem_whitelist = list("antihol", "charcoal", "epinephrine", "insulin", "mutadone", "teporone",\
"silver_sulfadiazine", "salbutamol", "perfluorodecalin", "omnizine", "stimulants", "synaptizine", "anti_rad",\
"oculine", "mannitol", "penteticacid", "styptic_powder", "methamphetamine", "spaceacillin", "saline",\
"salicylic_acid", "cryoxadone", "blood", "bloodc", "synthflesh",\
"menthol", "cold_medicine", "antihistamine", "ipecac",\
"booster_enzyme", "anti_fart", "goodnanites")`
