### ISSUE TITLE
Blob Fire-Resistant Membranes damaged by Spray fire ability on Flamethrower

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#11897]
### Labels

BUG

### Description

Blob Fire Resistant Membrane deleted by Spray on flamethrower, this is not supposed to happen.

### Steps to reproduce

1. Plant room of blob cells, plant Fire Resistant Membrane in doorway of room blocking it.
2. Fire Flamethrower through on Normal mode, and Spray mode.
3. Watch as the Fire Immune Tile is deleted for some reason (See below.)

### Expected Behavior

I see Fire abilities, I use fire immune cell to survive, I do not get curb stomped because literally everyone and their momma can get a flamethrower and spray me, themselves, and everyone, because fire does no damage to them really, but I roast.

### Additional Information & Screenshots

Apparently, for some reason, the Flamethrower is doing Brute Damage.

**Comment by Bartimeus973** [comment]
#11899 and Tarmunora's comment seems to indicate it's been fixed.
