### ISSUE TITLE
Merge conflict label removal failing

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#11912]
### Labels

[BUG]

### Description

^

### Steps to reproduce

1. Make a PR
2. Get a merge conflict
3. Fix it
4. Bot breaks and fails to remove the label

### Expected Behavior

I expected the bot to remove the label

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/20713227/201017640-d1cd8819-5202-4d5b-9023-7fa21c0a5c76.png)

**Comment by frawhst** [comment]
![image](https://user-images.githubusercontent.com/67879783/201190595-07d645ec-ec60-44f7-bf7f-a92f9a61bf4c.png)
seems to be working
