### ISSUE TITLE
Emote hotkey broken?

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#11927]
### Labels

[BUG]

### Description

Press M brings up the Emote chat menu, but then immediately switches to the command bar?

### Steps to reproduce

1. be ingame
2. Press M to Emote
3. I start typing Sigh to sigh but I'm suddenly in the command bar so it does nothing

### Expected Behavior

I press M to Emote in the Emote chat and I don't switch to the Command bar.

**Comment by DisturbHerb** [comment]
it's not that the button is broken, it's that the shortcut doesn't focus you on the text box. weird though, never liked how the button did that

**Comment by frawhst** [comment]
Yeah this is a thing

**Comment by nefarious6th** [comment]
Duplicate of #11159

**Comment by frawhst** [comment]
other one has a more descriptive title so closing this one
