### ISSUE TITLE
AI eye is pulled by gravity pulling artifacts

### ISSUE THREAD

**Issue by cheekybrdy** [goonstation/goonstation#11933]
### Labels

[BUG]

### Description

Its in the title

### Steps to reproduce

1. Be AI
2. Have Artsci trigger a artifact
3. Get yanked

### Expected Behavior

I expect that the conceptual existence of the AIeye to not be yanked by a gravity field

**Comment by frawhst** [comment]
Either we fixed this or it still exists and frankly I'm fine either way
