### ISSUE TITLE
Stroopwaffel = Loaf

### ISSUE THREAD

**Issue by Conchuckter** [goonstation/goonstation#11937]
### Labels

[BUG][MINOR]

### Description

The recipe for stroopwafels results in a loaf of bread.

### Steps to reproduce

1. Place maple syrup and 2x dough into an oven.
2. Run it for 2 seconds on high.
3. Observe.

### Expected Behavior

For the recipe to result in a stroopwafel.

**Comment by CaioFrancisco** [comment]
Couldn't replicate on my end. To cook the stroopwafel, I did the following:

- Picked up flour.
- Picked up sugar.
- Turned the flour into dough.
- Clicked on the dough with the sugar.
- Cut the sweet dough with a knife.
- Picked up 2 of the resulting cookie doughs and put it in an oven.
- Picked up a maple syrup from the FoodTech vendor and put it in the oven.
- Put it for 4 seconds on low.

I'm sure you forgot to make the dough sweet, which is a common mistake when looking at the images in the wiki.

**Comment by Conchuckter** [comment]
Ah, my bad.
