### ISSUE TITLE
Wraith can click drag move items while incorporeal

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#11931]
### Labels

[BUG]

### Description

Wraith can move items around by click dragging them

### Steps to reproduce

1. Be wraith
2. Be incorporeal
3. Click drag items from one tile to another

### Expected Behavior

I expected mob/living/intangible to not allow this, apparently it does

**Comment by Bartimeus973** [comment]
That was a thing before the transition to intangible. Im reasonably sure this is intended behavior?

**Comment by MetricDuck** [comment]
This is just their click-drag tk, unless I'm reading it properly

#4768

**Comment by Bartimeus973** [comment]
I'll close this considering it's very likely intended, as there is specific code supporting this. Do re-open it if it isnt!
