### ISSUE TITLE
funny stomper boots glitch

### ISSUE THREAD

**Issue by krimmity** [goonstation/goonstation#11945]
### Labels

[BUG][MAJOR]

### Description

Stomper boots allow you to become partially non-solid

### Steps to reproduce

1. Equip and activate the stomper boots
2. Quickly equip some other type of shoes and drop the stomper boots
3. You can now phase through other people and walk on tables

### Expected Behavior

Stomper boots shouldn't do that :(

**Comment by frawhst** [comment]
fixed. now breaks your ankles
