### ISSUE TITLE
Vampire thralls suffer for eating/sipping blood

### ISSUE THREAD

**Issue by TDHooligan** [goonstation/goonstation#1195]
[BUG]
While thralled, IVing, drinking or swallowing blood provides practically zero blood points.
Additionally, thralls can get hypertensive from swallowing blood.

**To Reproduce**
Be a zombie thrall
Attempt to drink/eat/IV blood (not tested with the ability)
Blood immediately disappears

**Expected behavior**
Blood points increase and remain
Thralls should not become hypertensive

**Comment by MarkNais** [comment]
Upgrading this because it sounds like it could strongly hinder thralls.

**Comment by Tarmunora** [comment]
closed by https://github.com/goonstation/goonstation/commit/0efb2e70c3a825b9eb90aee2ae8b06097ad2e94f I believe
