### ISSUE TITLE
Self-paid cargo might not work on Nadir

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#11951]
### Labels

[BUG][major]

### Description

Nadir's cargo system might not be set up to handle self-paid crates?

### Steps to reproduce

1. Enter your pin on the supply request console
2. Buy something
3. Apparently it doesn't show up

### Expected Behavior

For my shit to come in automatically

### Additional Information & Screenshots

I wasn't working cargo, so no idea if it's actually an error on the QMs' part. I don't know how it works on that map.

**Comment by Kubius** [comment]
Validated that self-paid cargo does work; as with other crates, it's placed in the queue to be received at transception pads.

**Comment by Kubius** [comment]
Arguably, such crates could be forcibly received by direct queue, but I'd want to have a dedicated pad in the lobby for that and at that point it'd be a feature addition and not a bugfix (may look into that at some point).
