### ISSUE TITLE
chameleon kit gear doesn't seem to show up on examine

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#11985]
### Labels

[BUG][major]

### Description

Was ghosting an infil, and half their equipment doesn't display when I click on them

### Steps to reproduce

1. observe nukie round
2. follow infil
3. click on infil when following them
4. see that, like, maybe 3 things show up on examine

### Expected Behavior

seems to be a pretty major bug if you can easily tell someone's wearing a chameleon kit

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/202229136-22389993-506d-4300-95a0-352bdc63cf01.png)

**Comment by NightmareChamillian** [comment]
courtesy pinging @Flaborized

**Comment by Flaborized** [comment]
Not a bug as far as I can tell? The suit and helmet block you from examining stuff under them. You can see that the backpack shows up just fine on description, tested this briefly on a local server and was able to produce the same results: examining without a redsuit they show up, with one on they don't.

**Comment by NightmareChamillian** [comment]
Ah. It'd appear I forgot about a basic feature of the video game.
