### ISSUE TITLE
being able to ghost in ghost restricted zone

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#11984]
### Labels

[BUG][reproduce]

### Description

I was ghosting around, as one does, and  ended up 

### Steps to reproduce

1. Be roundstart ghost
2. Observe nukie
3. stop observing nukie
4. don't get teleported to arrivals shuttle
5. do get teleported to arrivals shuttle if you try to move

### Expected Behavior

seems to be problematic. Unsure what I did to cause this.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/202227843-a97aab19-cd16-4fd6-a422-a17907f039db.png)

**Comment by frawhst** [comment]
Been reported a few times but I can't repro locally. Will experiment more ig
