### ISSUE TITLE
Mentor mice cannot biblefart

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#1199]
[BUG]

**Describe the bug**
Mentor mice are too helpful for the bible to be offended by their outgassing.

**To Reproduce**
1. Be mentor mouse
2. Flatulate on bible
3. You're okay!

**Expected behavior**
The bible sees past their helpful veneer and smites these filthy animals.

**Comment by UrsulaMejor** [comment]
Allowing ghost critters to biblefart seems like a recipe for an infinite flood of gibs and blood. We _could_ just yell at mentor mice that abuse this, but instead, I'd rather add something else instead.
