### ISSUE TITLE
Unkillable immortal undying plague rat

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#12002]
### Labels

[BUG]

### Description

A stage 1 small plague rat appeared to become immortal, got to -2000% health, didn't die and healed to full by eating dirt. 

### Steps to reproduce

I don't really know, it was on Nadir, the rat got batonged and beaten. Eventually its attackers gave up.

### Expected Behavior

I expected the rat to perish

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/20713227/202556498-b8affd1e-b942-4cfa-9323-8f85d42976a3.png)

**Comment by Bartimeus973** [comment]
Dammit.

**Comment by Bartimeus973** [comment]
I'm having some trouble finding out how this happened. No runtime log makes it a bit harder.

**Comment by frawhst** [comment]
Will look for related runtimes

**Comment by Bartimeus973** [comment]
fixed in #12004
