### ISSUE TITLE
nadir transception runtime

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#12016]
### Labels

[BUG] [RUNTIME] [MINOR]

### Description

runtime

### Steps to reproduce

1. idk

### Expected Behavior

no runtime

### Additional Information & Screenshots

This runtime has occurred 1 times.

File nadir_antenna.dm 
Line 724 
Error bad index 
Usr Kyle Whitaker (deadman164) 

 Description
proc name: Topic (/obj/machinery/computer/transception/Topic)
  source file: nadir_antenna.dm,724
  usr: Kyle Whitaker (/mob/living/carbon/human)
  src: the Transception Interlink (/obj/machinery/computer/transception)
  usr.loc: the steel floor (162,119,1) (/turf/simulated/floor/orangeblack/side)
  src.loc: the steel floor (163,119,1) (/turf/simulated/floor/orangeblack)
  call stack:
the Transception Interlink (/obj/machinery/computer/transception): Topic("src=\[0x2042ac6]&action=send&s...", /list (/list))
DeadMan164 (/client): Topic("src=\[0x2042ac6]&action=send&s...", /list (/list), the Transception Interlink (/obj/machinery/computer/transception))
DeadMan164 (/client): Topic("src=\[0x2042ac6]&action=send&s...", /list (/list), the Transception Interlink (/obj/machinery/computer/transception))
DeadMan164 (/client): Topic("src=\[0x2042ac6]&action=send&s...", /list (/list), the Transception Interlink (/obj/machinery/computer/transception))
DeadMan164 (/client): Topic("src=\[0x2042ac6]&action=send&s...", /list (/list), the Transception Interlink (/obj/machinery/computer/transception))
DeadMan164 (/client): Topic("src=\[0x2042ac6]&action=send&s...", /list (/list), the Transception Interlink (/obj/machinery/computer/transception))

**Comment by frawhst** [comment]
@Kubius 
(ignore if the transception PR already fixes this)

**Comment by Kubius** [comment]
Not sure what the cause is at a glance, but I think I'll be able to figure it out. Will look into this sometime SoonTM.
