### ISSUE TITLE
Trinkets don't GC

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#12038]
`Didn't GC: [0x20415b1] /obj/item/reagent_containers/food/drinks/bottle/hobo_wine/safe -- name Isaac Elberto's stupid Watered Down Grump Grappa, iconstate bottle-vermouthC1, icon icons/obj/foodNdrink/bottle.dmi`

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/6dd029a680a366500f77483d56f52b94261ce15a
