### ISSUE TITLE
Map lights don't GC

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#12034]
`Didn't GC: [0x2024cc8] /obj/map/light/brightwhite -- name glow - BRIGHT WHITE, iconstate light, icon icons/effects/mapeditor.dmi`

`Didn't GC: [0x202ebc1] /obj/map/light/lava -- name glow - LAVA, iconstate light, icon icons/effects/mapeditor.dmi`

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/77e82557bf6cd9ce7a1a806a8ae289699b927558
