### ISSUE TITLE
raw_materials don't GC

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#12041]
`Didn't GC: [0x204b09a] /obj/item/raw_material/bohrum -- name amazing bohrum ore, iconstate bohrum, icon icons/obj/materials.dmi`
etc
happens often at a variety of times, so unlikely to be related to a single source (rockbox explosion etc)

**Comment by Tarmunora** [comment]
able to reproduce when stacking raw materials

**Comment by Tarmunora** [comment]
Ok it's actually maybe a rockbox thing

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/b216e08cbdc436d5b4b47db9c074e91ac39444a3
