### ISSUE TITLE
Shuttle computers termOS error

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#12053]
### Labels

[BUG]

### Description

The asylum shuttle computer in donut 3 medbay is showing a termOS error

### Steps to reproduce

1. Go there
2. See computer
3. Cry at the clown being trapped forever

### Expected Behavior

I expected clown retrieval

**Comment by RSG250** [comment]
bug is also happening on the space Diner computers that call the mining shuttle and Johns bus, as well as the computer on the mining shuttle itself
