### ISSUE TITLE
Some Fontawesome icons are non-functional

### ISSUE THREAD

**Issue by pali6** [goonstation/goonstation#12071]
### Labels

[BUG]

### Description

For example search icon is now an A

### Steps to reproduce

1. As an admin open the `spawn` verb menu
2. Look at the search icon

### Expected Behavior

For the icons to work as they used to

### Additional Information & Screenshots

![Uploading image.png…]()

**Comment by ZeWaka** [comment]
Uhh I think I fixed this lol
