### ISSUE TITLE
Taking control of a flockdrone while having it selected doesn't clear the outline

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#12113]
### Labels

[BUG]

### Description

It should

### Steps to reproduce

1. Be flockmind
2. Click on drone
3. Drag yourself onto drone

### Expected Behavior

I should have added a check

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/20713227/203420422-a6b7a872-2bc5-4412-a332-55ea7cfa98f9.png)
glowy ass drone

**Comment by amylizzle** [comment]
I knew I should've moved that code from the double click to the take-control thing
