### ISSUE TITLE
Fluid level

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1212]
[BUG]

**Describe the bug**
Fluid levels are not being properly represented by walls

at one point i remember walls having like a filling up effect with regards to liquids now its just like flat against the walls no matter what and its weird

**To Reproduce**
1. fill a hollow 3 by 3 cube, with fluid a lot of it
2. see how its still looks flat

**Expected behavior**
at one point i remember walls having like a filling up effect with regards to liquids now its just like flat against the walls no matter what and its weird

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/85630608-f05d5780-b641-11ea-91cb-3170d295b4b9.png)

**Additional context**
its also really weird how that effect shows up for objects and people but it doesnt effect walls like it used too.

**Comment by ZeWaka** [comment]
BYOND bug - ish
