### ISSUE TITLE
VR murderbox has strange rain overlay

### ISSUE THREAD

**Issue by trollbreeder** [goonstation/goonstation#12135]
### Labels

[BUG][MINOR]

### Description

There is some strange overlay of rain, and a darkness circle near my character while in the VR murderbox

### Steps to reproduce

1. Go to VR
2. Go into the murderbox
4. Walk around until this overlay appears

### Expected Behavior

Murderbox being free of overlays and visual distractions

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25937686/203636109-20c8e8c4-640b-4561-bcb8-621c9d607c0b.png)
It seems to happen on the west side?
It doesn't happen in the preparation room though, except on the walls bordering the murderbox

**Comment by frawhst** [comment]
This is the overlay for the afterlife botany area 'below' the murderbox- I wonder if the areas somehow got messed up
![image](https://user-images.githubusercontent.com/67879783/203692308-f98b0077-49d2-434f-92ad-76ad53bbbe51.png)

**Comment by ZeWaka** [comment]
could just be clientside corruption methinks
