### ISSUE TITLE
Click dragging utility belt to move it, doesn't move it.

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1214]
[BUG]

**Describe the bug**
Click dragging the utility belt to drag it to another tile doesn't move it, instead gives the message "I need to wear the utility belt for that."

**To Reproduce**
1. Be borg
2. Click drag utility belt to move it to another tile.
3. Recieve "I need to wear the utility belt for that." message and item doesn't move.
4. Be sad.

**Expected behavior**
The item to move and no message as I'm not trying to wear it.

**Comment by trerri** [comment]
WHY DOES IT SAY I AND NOT YOU LIKE THE REST OF THE GAME HNNNNNNNNG

**Comment by Tiggersaurus** [comment]
I DONT KNOW
