### ISSUE TITLE
Air canister fills pocket O2 with unbreathable air

### ISSUE THREAD

**Issue by thegrb93** [goonstation/goonstation#12154]
### Labels

[BUG]

### Description

Air canister fills pocket O2 with unbreathable air despite having same chemical composition as normal atmosphere

### Steps to reproduce

1. Put pocket o2 in large 'Air' canister
2. Set large output pressure and open release valve.
3. Close release valve and eject pocket o2
4. Try breathing pocket o2

### Expected Behavior

Able to breath the pocket o2 air

**Comment by FlameArrow57** [comment]
Not exactly a bug, just need to increase the release pressure of the pocket o2 tank when breathing from it, don't know the minimum value for that

**Comment by pali6** [comment]
When the tank is pure O2 X moles of oxygen go into you in one breath. When it's air X moles of air go into you but only 21% of that is oxygen. Maybe the oxygen tank could be smart about it and auto adjust by default unless you turn that off? Could be good QoL

**Comment by thegrb93** [comment]
I see. The sleeping gas canisters in medbay also have the same problem. Trying to thing of a good solution...

**Comment by thegrb93** [comment]
How about a warning indicator on the 'activate internals' ability if the tank isnt breathable.

**Comment by pali6** [comment]
Could be good yea
