### ISSUE TITLE
Cloneable after DNR and Ghosting after RP Respawn cooldown

### ISSUE THREAD

**Issue by Obengrad** [goonstation/goonstation#12207]
### Labels

[BUG][MINOR]

### Description

If you set yourself as DNR, ghost, and then the timer on respawn ticks down, you are able to be cloned once it comes off cooldown, which tends to happen while you're selecting a new character, forcing you to do it again and probably take the 20 min respawn time.

### Steps to reproduce

1. Set DNR
2. Cryo
3. Ghost
4. Wait until Respawn becomes available
5. You are now cloneable, enabling you to be cloned before you are able to respawn as a new character.

### Expected Behavior

I expect that the DNR sticks while I'm choosing a new character, and that it hopefully doesn't stay after I respawn.

**Comment by nefarious6th** [comment]
#11329 - related
#9110 - cause
