### ISSUE TITLE
Sea4 refuses to react to its ignition temperature

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#1221]
[BUG]

**Describe the bug**
Sea4 does not seem to react to its activation temperature, no matter if in container, poured onto a wall or on the floor. You can go well beyond 474K, it still won't do anything. Additional note: I had 125u of it in the small fuel tank

**To Reproduce**
1. Acquire Sea4
2. Try heating it while it's in the container
3. Also try heating it while it's poured on the floor/wall
4. Notice that despite your efforts, absolutely nothing is happening

**Expected behavior**
Sea4 actually doing something after reaching its activation temperature

**Comment by ZeWaka** [comment]
comment if not fixed but this should do it
