### ISSUE TITLE
Small tree sprites are missing

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#12249]
### Labels

[BUG]

### Description

Small tree sprites like the dead plant & captain's bonsai are missing.

### Steps to reproduce

1. Look at the captain's tree.
2. Notice it's a floortile.
3. Screm.

### Expected Behavior

I expect a tree not to be made out of floor tiles.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/84296283/204981979-4b4c08ba-963b-43cf-bfc5-b15b5ec12873.png)

![image](https://user-images.githubusercontent.com/84296283/204982093-e653f7fb-7ce8-41ae-a6e2-a4611d7be72a.png)

**Comment by flappybatpal** [comment]
Fixed with https://github.com/goonstation/goonstation/commit/7c49ba9cb6dce52504772cf7150c8f90547d30b6
