### ISSUE TITLE
Flock: I broke pathfinding a little bit

### ISSUE THREAD

**Issue by amylizzle** [goonstation/goonstation#12265]
### Labels

[BUG]

### Description

Looks like flock are trying to path onto invalid tiles when adjacency is allowed

### Steps to reproduce

1. Spawn a flock somewhere
2. Watch the drones for a while
3. They'll try to path bad
4. Cry a bit

I *think* the behaviour triggers when there's a nearby target that is next to a wall/window, but no paths exist to the empty tile next to it. For example, the CE's office on Clarion - the drones try to get at the crate containing the RCD, but if neither door is converted, they try to path into an unconverted window instead.

### Expected Behavior

Pathing should path only on to valid tiles

**Comment by UrsulaMejor** [comment]
Also affects chickens
