### ISSUE TITLE
Cell Cables tool for AI shells (the round ones) do not function.

### ISSUE THREAD

**Issue by mordent-goonstation** [goonstation/goonstation#1234]
[BUG]

**Describe the bug**
Attempting to use the "Cell Cables" tool on an APC (either to give charge or to draw charge) does not function. No message presents itself.

**To Reproduce**
1. Be AI
2. Deploy to a drone
3. Equip Cell Cables
4. Use on an APC
5. No effect

**Expected behavior**
For the Cell Cables to deliver/draw charge (depending on mode), as they do for a cyborg.

**Comment by Adharainspace** [comment]
looks like this is because of a mismatch, it doesnt seem like ai shells are of type mob/living/silicon/robot, and jumper cables check for that in line 458 of apc.dm
```else if (issilicon(user))
    if (istype(W, /obj/item/robojumper))
        if (!istype(user, /mob/living/silicon/robot))
            return
```

**Comment by Tiggersaurus** [comment]
They still don't work as a note :( I want to fix APC charge pls.

**Comment by mordent-goonstation** [comment]
Fixed in https://github.com/goonstation/goonstation/pull/3135.
