### ISSUE TITLE
Able to instantly die

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#12347]
### Labels

[BUG] [MINOR] 

### Description

You're able to succumb instantly

### Steps to reproduce

1. click the suicide verb, it should show a menu of suicide methods
2. click the suicide verb again while the menu is open
3. it shows you the 'are you sure you wish to succumb?' dialogue despite you not actually suiciding
4. you decide to succumb
5. medical is baffled by your 0 damage corpse

### Expected Behavior

I expect that there be some kind of check to see if you are actually dying when you succumb.

**Comment by thegrb93** [comment]
Isn't this the same as selecting to hold your breath twice? I thought it was intentional so you don't have to wait out holding your breath.

**Comment by thegrb93** [comment]
Maybe add a health check here https://github.com/goonstation/goonstation/blob/faa5b48a8ea3a72c59d7c4c06f39e217e2a675ba/code/mob/suicide.dm#L111
