### ISSUE TITLE
Murderbox viewing sanctuary zone is pretty busted

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#12340]
### Labels

[BUG][MAJOR]

### Description

The sanctuary zone in the murder box allows you to cut off peoples limbs with katanas OR shoot into the murderbox with nukie snipers OR sleepypen people. probably other things as well.

### Steps to reproduce

1. Go into the sanctuary murderbox zone with a sniper or katana or pen
3. shoot people inside the murder box proper with a wall percing weapon (they can't shoot you back)
4. Use a katana to cut the limbs off the people in the sanctuary zone
5. Sleepy pen the people in the sanctuary zone

### Expected Behavior

No shooting outside, no sleepypen, no katana delimb, ect

**Comment by flappybatpal** [comment]
Two separate issues, shooting is due to map design, sleepy pen etc is due to lack of sanctuary checks.

**Comment by flappybatpal** [comment]
Part fixed with #16681
