### ISSUE TITLE
AI appears to be linked to a deconstructed law rack

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#12367]
### Labels

[BUG]

### Description

After being killed and rebuilt as an AI, had no laws and could not be linked to a new law rack.

### Steps to reproduce

1. Have AI linked to regular law rack with a laser module inserted
2. Kill AI
3. Build new law rack somewhere (possibly not necessary?)
4. Deconstruct original law rack
5. Rebuild AI
6. AI has no laws, still has the laser module ability, and can't be re-linked to a new law rack

### Expected Behavior

The AI should probably link to the new law rack? Or at least be lawless but linkable? Also the laser ability should go away.

**Comment by amylizzle** [comment]
rebuild as in: "take brain out of dead AI and put it in new shell" or "repair dead AI so it comes back to life"?

**Comment by amylizzle** [comment]
Yeah, I can't replicate this. Killing the AI, blowing up the rack, rebuilding the rack, rebuilding the AI in a variety of orders doesn't seem to trigger it.

**Comment by TobleroneSwordfish** [comment]
God knows then, thanks for trying
