### ISSUE TITLE
Getting ejected out of the cryotube without having my organs healed

### ISSUE THREAD

**Issue by Finalgamer10** [goonstation/goonstation#12373]
### Labels

[BUG]

### Description

I was ejected out of the cryotube almost instantly after i was put into to have my organs healed. They were still damaged when i got out

### Steps to reproduce

1. Only have organ damage.
2. Get put into a cryotube.
3. Get ejected out of the cryotube immediatly without having your organs healed.

### Expected Behavior

Expected to have my organs healed in the cryotube and then be ejected, since per wiki, cryoxadone also heals organ damage.

### Additional Information & Screenshots

When i was put inside the cryotube, i only had medium liver damage to my knowledge. 
So i should not have had any oxy/tox/burn/brute damage when i was put inside.

**Comment by thegrb93** [comment]
I think intended since they only have damage sensors and not organ sensors. Could be wrong though.

**Comment by Retrino** [comment]
cryo does heal organ damage. the tube itself checks your basic four damage types and ejects when there is no damage. wanting it to sense for organ damage would be a feature request
