### ISSUE TITLE
Disappearing die from quickly rolling

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#12401]
### Labels

[BUG]

### Description

If you roll a die, then pick it up and quickly attempt to roll it again, it will just disappear. Poof!

### Steps to reproduce

1. Roll a die (use in-hand, not throw)
2. Pick it up
3. Quickly try to roll again (use in-hand, not throw)
4. It disappears!

### Expected Behavior

The die should not disappear

**Comment by pali6** [comment]
fixed by https://github.com/goonstation/goonstation/commit/14a2d92b23e5597af9aa5cc708a35361325deaa4
