### ISSUE TITLE
Wasp corpses don't get affected by conveyor

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#12410]
### Labels

[BUG] [MINOR]

### Description

Yeah

### Steps to reproduce

1. Get wasp
2. Kill it on a conveyor
3. Doesn't move?

### Expected Behavior

Corpse moves

### Additional Information & Screenshots

It isn't anchored
![image](https://user-images.githubusercontent.com/67879783/207766537-51b58377-1285-4dc5-823b-b367f2f9f8d3.png)

**Comment by TealSeer** [comment]
Duplicate of #16539
