### ISSUE TITLE
John Bill's shuttle disappears

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#12428]
### Labels

[BUG]

### Description

Under *some circumstances* John Bill's shuttle can vanish, it makes the arrivals sound but just doesn't appear. Anyone in the area where it should be when it leaves is teleported to the other end as normal.

### Steps to reproduce

1. ???
2. Logs indicate someone used a pod portal nearby shortly before it happened, unsure if related.

### Expected Behavior

I expected John not to retire

### Additional Information & Screenshots

This mess appeared under the diner dock.
![image](https://user-images.githubusercontent.com/20713227/208216624-218f6b1d-038b-47a9-a8ba-7905d81784bb.png)

**Comment by frawhst** [comment]
likely related to #12284
