### ISSUE TITLE
Shower null reagent runtime (shouldn't be possible???)

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#12439]
### Labels

[BUG] [RUNTIME]

### Description

Somehow a reagent which wasn't actually contained in a shower made its way into `shower.reagents.reagent_list`, causing a lot of runtimes.

### Steps to reproduce

1. Put reagents in a shower
2. ???
3. Runtimes

### Expected Behavior

No runtime

### Additional Information & Screenshots

Relevant lines:
https://github.com/goonstation/goonstation/blob/48157cebffef7383445e37c1de4e67bad7190884/code/obj/machinery/shower.dm#L60-L66

The issue arises from line 63- every id in `reagent_list` should point to a `/datum/reagent` instance, but somehow one was pointing to null, causing a runtime on line 65.
Runtime:
```dm
[03:33:52] shower.dm,65: Cannot read null.id
[03:33:57] shower.dm,65: Cannot read null.id
[03:34:02] shower.dm,65: Cannot read null.id
```

**Comment by pgmzeta** [comment]
I tried a couple different ways of reproducing, but I am honestly at a loss as to what would do this. Maybe some weird chain-reaction?
