### ISSUE TITLE
cant call a map vote

### ISSUE THREAD

**Issue by kaedon142** [goonstation/goonstation#12460]
### Description

cant call map vote

### Steps to reproduce

1. attempt to start a map vote
2. get results

### Expected Behavior

map vote starts

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/81059014/208599750-54910655-5f3f-4dc9-81c2-392cbb7ec6e2.png)

**Comment by kaedon142** [comment]
im trying to do it on my private server and cant seem to fix it

**Comment by wolfolotl** [comment]
you can uncomment one of the map defines in your local repo's instance of the goonstation/_std/__build.dm file to set your server's map!

**Comment by kaedon142** [comment]
which part?

**Comment by wolfolotl** [comment]
lines 105-125 just about, though not all of the listed maps are currently maintained or going to compile

**Comment by kaedon142** [comment]
what if i uncomment all of them?

**Comment by kaedon142** [comment]
also do i have to remove every map but the one I want?

**Comment by amylizzle** [comment]
In `__build.dm` you must uncomment *one* of the `#define MAP_OVERRIDE_` and recompile. Map switching at runtime is done using the goon server infrastructure, and is not accessible for private servers. If you want that functionality, you'll need to roll your own.

Closing as wontfix.
