### ISSUE TITLE
Chemical combustion generators seem to have a misplaced decimal for resource requirements

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#12473]
### Labels

[BUG]

### Description

The new chemical combustion generators require a whacky amount of resources

### Steps to reproduce

1. scan chemical combustion generator
2. put into fabricator
3. hm, that doesn't seem right

### Expected Behavior

6 copper and 8 steel bars seem like a bit much for printing, so I'm opening this in case it wasn't intended

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/208963668-a51a0abf-2d16-41db-a138-965016f5f218.png)

**Comment by Conchuckter** [comment]
Wacky
