### ISSUE TITLE
Body color and hair color(wig) not accurate for Lizards.

### ISSUE THREAD

**Issue by Fredric80100** [goonstation/goonstation#12515]
### Labels

[BUG][MINOR]

### Description

Body colors/Hair(Wig) aren't accurate for Lizards.

### Steps to reproduce

1. Give a color value to the 'Top Detail' 'Middle Detail' or 'Bottom Detail' preferably a lighter value.

### Expected Behavior

Colors aren't accurate and seems to be dimmed down, happens more on lighter colors.

### Additional Information & Screenshots

![Screenshot 2022-12-26 003239](https://user-images.githubusercontent.com/92319687/209493296-ad16d11d-1f0f-40cd-8669-c6445df7bbcb.png)
![Screenshot 2022-12-26 003402](https://user-images.githubusercontent.com/92319687/209493306-a37274a0-8fe0-4004-b696-c07ead0d4d4f.png)

Human to Lizard with exact same values.

**Comment by Retrino** [comment]
pretty sure this intended

**Comment by Tarmunora** [comment]
rgb components for lizard colors are clamped, yes
