### ISSUE TITLE
Manta's Long Range Mining Teleporter Doesn't Work

### ISSUE THREAD

**Issue by KamikazeMongoose** [goonstation/goonstation#1259]
[BUG]

**Describe the bug**
If you stand in the teleporter and turn it on, you'll get the animation for teleporting and then go nowhere.

**To Reproduce**
1. Use the long range teleporter

**Expected behavior**
Teleportation to the trench

**Screenshots**
N/A

**Additional context**
I can't hit rocks, I need help.

**Comment by MarkNais** [comment]
https://discordapp.com/channels/182249960895545344/298827721604071425/727310824598798397
The trench mining prefab did not exist (no teleport destination)

**Comment by MarkNais** [comment]
Didn't exist in the last round of Manta either

**Comment by Adharainspace** [comment]
i changed the lrt to use landmarks instead of coordinates a while ago, i wonder if manta wasnt updated?

**Comment by Gerhazo** [comment]
Can confirm tunnel snake (the mining outpost prefab) didn't spawn at all as of a recent round.

**Comment by MarkNais** [comment]
I wouldn't call it the tunnel snake anymore. The version that had the crushers hasn't been on live for months.
