### ISSUE TITLE
Character setup preview uses old floor tiles sprites

### ISSUE THREAD

**Issue by ATDoop** [goonstation/goonstation#12602]
### Labels

[BUG] [TRIVIAL]

### Description

the character creation preview uses the old floor tile sprites

### Steps to reproduce

1. open character setup
2. look at preview
3. see old sprites

### Expected Behavior

character preview uses the new floor tiles

### Additional Information & Screenshots

![dreamseeker_2023-01-01_18-17-49](https://user-images.githubusercontent.com/1959416/210187836-5e123fd2-b1bd-4bc7-8cfd-7d6f9e9d1b54.png)

**Comment by ZeWaka** [comment]
fixed sometime
