### ISSUE TITLE
no one can see fun art

### ISSUE THREAD

**Issue by CoolKakapo** [goonstation/goonstation#12647]
### Labels

[BUG]

### Description

no one can see the monkey i painted on a painting

### Steps to reproduce

1. get a canvas
2. make a cool painting(any painting)
3. show it off to people
4. they only see a blank canvas

### Expected Behavior

they should see the cool monkey with a lightsaber in a cave i painted

### Additional Information & Screenshots

<img width="257" alt="image" src="https://user-images.githubusercontent.com/120601289/211034631-1b3d9c1b-16a2-4e31-8abe-dc3de116e211.png">

they cant see this

**Comment by ZeWaka** [comment]
weird can't repro
