### ISSUE TITLE
Roundstart plates don't hold food correctly

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#12662]
### Labels

[BUG] [MAPPING] [MINOR]

### Description

The food is unconnected to the plates

### Steps to reproduce

1. Open Oshan Laboratory
2. Look at the plates in: Mining, cafeteria, southern carousel area
3. try to pick up said plates

### Expected Behavior

The food should be on the plate and picked up together

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/51260013/211150226-72da2257-f95a-49c9-980a-9f09438d32b8.png)

**Comment by TheTyrant25** [comment]
turns out this applies to all plates in clarion too.
Not too much of a stretch to assume it's on every map

**Comment by frawhst** [comment]
https://github.com/goonstation/goonstation/commit/e620318d42ad7fe92d830077e792f307c9479860
