### ISSUE TITLE
Oshan Toxins not working proper

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#12663]
### Labels

[BUG] [MAJOR]

### Description

It's very difficult to use oshan toxins as heat leaks

### Steps to reproduce

1. Go scientist, go oshan, go toxins
2. start a burn to heat up some plasma
3. the heat shields   fail to shield heat
4. the room heats up to an unbearable degree
5. you are forced to apply burn patches to yourself or fully suit up in order to use oshan toxins

### Expected Behavior

The heat shields actually keep the heat out, the room not heat up (like in every other toxins lab)

### Additional Information & Screenshots

It's been like this for a long time from what i can tell. I am fairly certain that this isn't `possibly intended` since no other toxins work like that, but who knows? If it is intended, just lemme know i guess.

**Comment by TheTyrant25** [comment]
P.S. Why hasn't this been reported before? only reason i can think of is it being intended or people just thinking it. Or just not bug reporting, either one

**Comment by CaioFrancisco** [comment]
Or people simply avoid Oshan toxins. I mean, I've never seen anyone use the outpost for actual toxins.

**Comment by TheTyrant25** [comment]
they avoid it because its broken -_-

**Comment by TheTyrant25** [comment]
![image](https://user-images.githubusercontent.com/51260013/215013955-02b070eb-221d-445a-b7d1-cc689ed123eb.png)
The wiki states that they are "vacuum sealed mixing rooms", so definitely not intended behaviour i would say.
