### ISSUE TITLE
I renamed the AI while dead

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1267]
[BUG]

**Describe the bug**
This one is a bit complicated.  So, if you get turned into an AI, but for whatever reason never get around to choosing your AI name (for instance, being AFK) and then get your brain removed from the AI and have a new brain put in there (as might happen if you were AFK) and then go and choose an AI name (if, hypothetically, you hadn't closed your client and came back from being AFK and noticed the popup), then the AI that replaced you will get renamed.

**To Reproduce**
1.  Get turned into an AI
2.  Do not select a name but leave the prompt open.
3.  Get taken out of the AI
4.  Have someone else put into the AI
5.  Let them select their name
6.  Select your name
7.  Watch the confusion

**Expected behavior**
I'd expect the chosen name to be applied to your ghost, rather than the AI using your former shell.

[BUG]

**Comment by ZeWaka** [comment]
need the exact input dialogue message

**Comment by ThePotato97** [comment]
> 
> 
> need the exact input dialogue message

They're probably talking about
![image](https://user-images.githubusercontent.com/10260415/94241212-43c69680-ff0c-11ea-9c20-50ee4a1ad94d.png)
