### ISSUE TITLE
Self-Spectating Ghost Bug

### ISSUE THREAD

**Issue by ThatsMamaLuigiToYouMario** [goonstation/goonstation#12727]
### Labels

[BUG] [MINOR]

### Description

Clicking on yourself as a ghost will teleport you to coordinates 1,1.

### Steps to reproduce

1. Become a ghost via dying or observing
2. Click on yourself to spectate
3. Get teleported to 1, 1 on the map.

### Expected Behavior

I'd expect for nothing to happen when I click on myself to spectate.

**Comment by pali6** [comment]
fixed by https://github.com/goonstation/goonstation/commit/01edcdf56ba44da37c503c1c521bbbf718fb1b20
