### ISSUE TITLE
Werewolf defensive howl doesn't block melee attacks?

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#12726]
### Labels

[BUG][MAJOR]

### Description

I was told that it gave you a 60% chance to negate a melee attack but in my testing it never triggered

### Steps to reproduce

1. Be werewolf
2. use defensive howl
3. attack a monkey in a room full of monkeys
4. observe as you don't block any attacks?

### Expected Behavior

to block roughly 60% of attacks

**Comment by Wisemonster** [comment]
NPC monkeys tend to have jank in their code, so they might be ignoring the defensive howl. Not sure if this affects actual players.

**Comment by CheffieGithub** [comment]
I'll do some more testing to see if it is just monkey jank

**Comment by CheffieGithub** [comment]
![image](https://user-images.githubusercontent.com/113442598/212473043-b91cfb4c-1ea5-490e-9f0e-146f94699fbf.png)
seems to not be working at all yeah

**Comment by CheffieGithub** [comment]
was hard to test this since the status effect is hardcapped to 15 seconds

**Comment by CheffieGithub** [comment]
upped to major since it completely breaks one of an antags abilities - the fire thing
