### ISSUE TITLE
Wrestlemap AI screen inside of an airlock

### ISSUE THREAD

**Issue by TheRealMrN** [goonstation/goonstation#12737]
### Labels

[BUG] [MINOR]

### Description

Same as title

### Steps to reproduce

1. Find an airlock with the AI screen in question

### Expected Behavior

For an AI screen to not be inside of an airlock

### Additional Information & Screenshots

![Screenshot_85](https://user-images.githubusercontent.com/100310349/212410243-912f2644-87b0-476f-a470-a96d433837bd.png)

**Comment by nefarious6th** [comment]
this one's on me 😓I'll fix soon
