### ISSUE TITLE
Runtime when injecting a genetic ability that has an ability bar button while DNA ability bar is open

### ISSUE THREAD

**Issue by Sovexe** [goonstation/goonstation#1275]
[BUG][RUNTIME]

**Describe the bug**

File | ability_parent.dm
-- | --
Line | 603
Error | Cannot execute null.add object().

**To Reproduce**
1. Have DNA ability bar open
2. have the `datum/bioHolder/proc/AddEffect` proc execute against your mob trying to add an effect to you (most commonly called when injecting a gene, NOT including activators)
3. on line `598` of `ability_parent.dm` the following line `var/mob/M = get_controlling_mob()` sets M to a value of null. This is because `get_controlling_mob()` tries to get the mob from `abilityHolder`'s `owner` var which is null in the case
4. receive runtime, ability button does not appear until you either close and reopen the bar, or add a new power (in which case the new power won't appear but the one you added just prior will)

**Expected behavior**
1. Inject ability with DNA ability bar open
2. ability appears on bar 

**Additional context**
This also applies for when abilities are removed, though the instead of failing to add an ability bar button it fails to remove it.

**Comment by amylizzle** [comment]
Can't replicate. Pretty sure this is fixed.
