### ISSUE TITLE
Using Syndicate Explosive Entry Device (SEED) renders you unable to move 

### ISSUE THREAD

**Issue by SimianC** [goonstation/goonstation#1276]
[BUG]

**Describe the bug**
Using the SEED renders you unable to move after your vehicle explodes. Player is able to use objects in in-hand and interact with surroundings. Observing the player shows the Ship HUD, but it isn't visible to them. Entering and exiting another pod fixes the problem.

**To Reproduce**
1. While piloting the vehicle, activate SEED.
2. Wait to be ejected and for the vehicle to explode.
3. Freeze in place. 

**Expected behavior**
After being ejected from the vehicle, the player should be able to move and (hopefully) avoid the explosion.

**Comment by PrimeNumb** [comment]
Can confirm reproducible
