### ISSUE TITLE
Nadir artifact ejector pipe leads to hydroponics disposal chute

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#12851]
### Labels

[BUG]

### Description

Flushed a very bad artifact and it came out of the botany disposal chute...

### Steps to reproduce

1. Eject an artifact
2. It comes out of the botany disposal chute for some reason

### Expected Behavior

Don't send a black hole artifact to botany

### Additional Information & Screenshots

It took a path kinda like this
![image](https://user-images.githubusercontent.com/25157685/214067367-c429f500-27bd-4214-b94d-6f15ec771537.png)

**Comment by Kubius** [comment]
What likely happened here is that someone fell in alongside the black hole artifact and the biofilter to keep people from getting launched out into acid also brought the artifact along with. This still isn't where that should have ended up, though; fix coming soon.

**Comment by Zamazenta** [comment]
> What likely happened here is that someone fell in alongside the black hole artifact

that would be me, woops.
