### ISSUE TITLE
Donut3, One Way Ticket chute can be activated from a distance

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#1285]
[BUG]

**Describe the bug**
Stand from a distance and click on the chute. You'll pull the lever despite being out of range.

**To Reproduce**
1. Read above

**Expected behavior**
Chute telekinesis isn't a thing

**Comment by Tenryumi** [comment]
That's unusual... The One Way Ticket isn't a specific object, it's an instance of a transport chute. Meaning this is a problem with transport chutes and not just the One Way Ticket.
