### ISSUE TITLE
Magboots can anchor you to space

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#12890]
### Labels

[BUG][minor]

### Description

You won't get space drift with magboots, even though the magnetism would imply it's sticking you to the station structure only.

### Steps to reproduce

1. Get magboots, jetpack and space wear
2. go out into space, observe your space drifting when you let go of movement
3. Activate magboots
4. Stop movement, you can precisely position in the middle of space

### Expected Behavior

space drift continuing

**Comment by Chatauscours** [comment]
" This isn't really a bug, it's an intentional feature. Mostly from the days of space wind being a pain in the ass but still. " - Sword, on commit above.
