### ISSUE TITLE
Nadir's crashed transport trench prefab has "fix me" tiles under the crates

### ISSUE THREAD

**Issue by TheRealMrN** [goonstation/goonstation#12904]
### Labels

[BUG] [MINOR]

### Description

Same as title. Don't know if Nadir's prefabs are the same as on Oshan

### Steps to reproduce

1. Find the crashed transport prefab (With the stun turrets)

### Expected Behavior

Floor to not ask to fix itself

### Additional Information & Screenshots

![Screenshot_88](https://user-images.githubusercontent.com/100310349/215205721-ff0b39a7-dd46-462e-bcf8-8e65ff6ffac7.png)

**Comment by NightmareChamillian** [comment]
courtesy pinging @Kubius

**Comment by Kubius** [comment]
This isn't a Nadir-exclusive prefab, I believe.
