### ISSUE TITLE
FLOCK Shuttle instant round end

### ISSUE THREAD

**Issue by GoldenKeyboard** [goonstation/goonstation#1291]
[BUG]

**Describe the bug**
On shifts with FLOCKs as an antag, once the shuttle leaves it instantly arrives.

**To Reproduce**
1. Play a shift where FLOCKs exist
2. Shuttle Arrives
3. Shuttle Departs
4. Shuttle INSTANTLY Arrives again

**Expected behavior**
The normal two minute delay before arriving.

**Screenshots**
![image](https://user-images.githubusercontent.com/12817816/86284346-b7c4fd00-bbb0-11ea-890e-ee526d4cc9b3.png)

**Additional context**
It also appears that the anticipated shuttle delay is reset to six minutes?
This isn't a one time occurrence, this has happened before under same factors. Normally I would have submitted a bug report sooner but I wanted to ensure that it was indeed FLOCK causing the issue.

**Comment by Sovexe** [comment]
I don't know that this is specific to flock. I've seen this issue occur a handful of times now.

**Comment by GoldenKeyboard** [comment]
It appears that #https://github.com/goonstation/goonstation/pull/1293 will solve this

**Comment by GoldenKeyboard** [comment]
Because of the merging of PR #1293 this issue is now resolved!

**Comment by MarkNais** [comment]
More so, this issue has occurred outside of flock rounds, but there's been two recent occurrences in flock rounds.
In otherwords it my be related to flock, but the root cause is likely outside of it.
