### ISSUE TITLE
Cyborgs can collect a chorus of ringing phones in their ears

### ISSUE THREAD

**Issue by prismfingers** [goonstation/goonstation#12952]
### Labels

[BUG]

### Description

Cyborg can dial a phone and have it ring in their rings long after moving away.

### Steps to reproduce

1. be cyborg
2. find a phone
3. have no tool selected
4. shift click on phone while adjacent
5. initiate prank call
6. walk away and repeat 2-5 as often as you like

### Expected Behavior

Maybe cyborgs shouldn't be able to make phone calls if they can't hold the phone. Let alone hearing the ringing after walking away.

**Comment by Retrino** [comment]
shift click thing was removed
