### ISSUE TITLE
Teleport to is borked

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#1295]
[BUG]

**Describe the bug**
Teleport to doesn't work for ghosts (the chat kind)

**To Reproduce**
1. Right click a name in chat when dead
2. Somehow manage to click the right name and the "teleport to" option in the dizzyingly fast chat
3. You don't teleport to anything

**Expected behavior**
I expect clicking the name to bring me to the person without any fancy right click bullshit.

**Comment by ZeWaka** [comment]
this is admin stuff, don't think ghosts should have this even pop up??
