### ISSUE TITLE
Pizza vendor in catering storage on nadir is facing the wrong way

### ISSUE THREAD

**Issue by TheRealMrN** [goonstation/goonstation#12963]
### Labels

[BUG][TRIVIAL]

### Description

same as title

### Steps to reproduce

1. Get to the pizza vendor

### Expected Behavior

for it to face away from the wall

### Additional Information & Screenshots

![Screenshot_92](https://user-images.githubusercontent.com/100310349/216739390-44b184ee-76f1-4d18-8318-246b02f8a70b.png)

**Comment by Kubius** [comment]
Pizza vendors are unanchored for some reason. It probably got bumped.

**Comment by TealSeer** [comment]
Cannot reproduce, see above
