### ISSUE TITLE
Spiders are helpless

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#12983]
### Labels

[BUG]

### Description

Cannot use help intent as spider

### Steps to reproduce

1. Get mind transplanted into a spider queen
2. Click anywhere with help intent
3. Everything acts as if you have harm intent
4. Weep, as you cannot hug people back after they snuggle you

### Expected Behavior

I expected the intent system to actually work

### Additional Information & Screenshots

Goon 3 Morty Feb 5 2023. Round was going on at 5:00 - don’t have an exact timestamp for when it started. Also, I was an ice spider queen specifically

**Comment by amylizzle** [comment]
Did you try changing intents? It may just be that the HUD was not updated. I am unable to replicate this.

**Comment by Roninnozlo** [comment]
> Did you try changing intents? It may just be that the HUD was not updated. I am unable to replicate this.

It did change in the hud. Sorry I didn't get back to you about this quick enough...
