### ISSUE TITLE
Cog1 PTL room camera is called "Space 2"

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#12988]
### Labels

[BUG]

### Description

The security camera in the cog1 ptl room is called "Space 2", for some reason.

### Steps to reproduce

1. View camera "Space 2" on security cameras

### Expected Behavior

It should have the correct name

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25157685/217000729-904ee66a-607b-446d-b358-5f88e8ea1eed.png)
this is the specific camera

**Comment by frawhst** [comment]
if space is so good why isn't there a

**Comment by BatElite** [comment]
![image](https://user-images.githubusercontent.com/31984217/217210300-f3c1afdd-5502-4637-aaec-d736f9452534.png)
oh
