### ISSUE TITLE
HoP Headset claims to be able to hear the Security frequency, but can't

### ISSUE THREAD

**Issue by LikeLakers2** [goonstation/goonstation#12986]
### Labels

[BUG]

### Description

The HoP Headset, despite claiming in its description that it can hear the Security frequency, but not speak over it (not since the incident), is unable to hear the Security frequency.

### Steps to reproduce

1. Wear a HoP headset.
2. Notice that you never hear the Security frequency unless you have a security-enabled headset within your hands or pocket.

### Expected Behavior

I would expect to be able to hear the Security frequency with the HoP headset, as per the description. Alternatively, I would expect that the description not mislead users into believing that it can hear over the Security frequency.

### Additional Information & Screenshots

The relevant code:
https://github.com/goonstation/goonstation/blob/971a292941f916d247a8847b60fde3f40d196794/code/obj/item/device/radios/headsets.dm#L191-L210

Notice how `secure_classes` lists the Security frequency, but `secure_frequencies` does not. This would imply that `secure_classes` is the list meant for what the headset can hear, while `secure_frequencies` is the list meant for what the headset can communicate on -- which begs the question, why does `secure_classes` not take effect?

**Comment by Mister-Moriarty** [comment]
Fixed by #12989,
