### ISSUE TITLE
Being Cold Allows You To Develop Multiple Colds

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#13006]
### Labels

[BUG]

### Description

Being cold for a while causes you to get the cold disease, however you can get multiple colds if you stay cold for too long.

### Steps to reproduce

1. Be in a cold environment
2. Develop a cold
3. Stay in a cold environment
4. Develop more colds

### Expected Behavior

To not develop multiple colds

**Comment by FlameArrow57** [comment]
#12599
