### ISSUE TITLE
Wearing a bedsheet cape sets your mob's "blinded" value, as if you were wearing a full bedsheet.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#1305]
**Describe the bug**
Wearing a bedsheet cape will have your mob's "blinded" variable be set to 1. Your vision isn't actually obstructed or anything of the sort, but the game considers you "blinded" and stuff like vampire's glare/hypnotize abilities depending on eyesight can't function, which clashes with the caped vampire look.

**To Reproduce**
1. Become a vampire, whose abilities depend on having eyesight.
2. Wear a bedsheet cape.
3. Glare ability doesn't work, your mob's "blinded" variable is set to 1.

**Expected behavior**
Not being counted as blinded.

**Comment by Gerhazo** [comment]
After some people's observations, turns out this only applies to admin-spawned bedsheet capes.

When you make a cape out of a bedsheet, it only changes some things as to turn the bedsheet into a cape but it's still just considered to be a bedsheet instead of spawning an actual bedsheet cape (*scream).

The discrepancy in some variables causes different interactions between the two.

This can probably be fixed by just setting block_vision = 0 in the parent bedsheet/cape type. The process of turning a bedsheet into a cape turns it to 0 but bedsheet/cape types by themselves don't change it and have it remain as 1.

**Comment by Tarmunora** [comment]
Closed by #1310
