### ISSUE TITLE
tgui error

### ISSUE THREAD

**Issue by FlyzerMizer** [goonstation/goonstation#13086]
### Labels

[BUG]

### Description

 at https://cdn.goonhub.com/tgui/tgui.bundle.js?v=1babf85526fd2cab658e16931f140bbad3e1980d:1:1

### Steps to reproduce

1. try to open any tgui and the only thing that appears is the termos error

### Expected Behavior

open the correct tgui

**Comment by ZeWaka** [comment]
not enough info
