### ISSUE TITLE
Script error on Genetics console

### ISSUE THREAD

**Issue by TheOnlyZac** [goonstation/goonstation#13106]
### Labels

[BUG]

### Description

While using the genetics console, the console window was suddenly replaced by a TermOS script error

### Steps to reproduce

1. Have someone step into the genetics scanner
2. Use the genetics console to research their genes

### Expected Behavior

I expected the console to not throw an error

### Additional Information & Screenshots
Reported by: theonlyzac
On server: Goonstation 1 Classic: Heisenbee
Map: Oshab Laboratory

Here is the stack trace that appeared with the error message:
`Script error at https://cdn.goonhub.com/tgui/tgui.bundle.js?v=a2b7e7214e2a2efcb44a8c370f7b5d426b8afed0:0 User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; GWX:DOWNLOADED; Zoom 3.6.0) State: {"ckey":"theonlyzac","interface":"GeneTek","window":{"key":"[0x20468cc]-main","size":null,"fancy":1,"locked":0,"mode":"dark"}}`

![gmljP4njcx2](https://user-images.githubusercontent.com/7002063/219532417-12624ed1-9c34-474a-9271-8eafb5d92b1e.png)

**Comment by ZeWaka** [comment]
not enough to repro
