### ISSUE TITLE
Placing a weldingtool on a reinforced table burns eyes

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#13104]
### Labels

[BUG]

### Description

When you click a reinforced table with a weldingtool, it'll play the sfx and (if no protection) give eye damage, even if it places the tool on the table

### Steps to reproduce

1. click an r-table with lit welding tool
2. ow oof owie my eyes

### Expected Behavior

eyes to not be hurt

### Additional Information & Screenshots

was able to accurately reproduce a whole bunch of times.

![image](https://user-images.githubusercontent.com/96703882/219475875-1beb5141-98ed-4399-9817-1273520973a4.png)
![image](https://user-images.githubusercontent.com/96703882/219476002-29c3d738-3d61-4b48-9b58-c8e05f20dd08.png)

**Comment by M-Earthfire** [comment]
It probably shouldnt burn your eyes still, should it?

**Comment by NightmareChamillian** [comment]
mmhm, yeah, it shouldn't
