### ISSUE TITLE
Helmet signaler assemblies are uncraftable

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#1316]
[BUG]

**Describe the bug**

Cannot craft helmet signalers with a helmet and a signaler. Literally unplayable. And securitrons are uncraftable literally from scratch.

**To Reproduce**
1. Get helmet
2. Get signaler
3. Make em kiss
4. They dont kiss

**Expected behavior**

Signaler goes in helmet.

**Additional context**

Thought I was doing something wrong with my branch. Turns out same thing happens on live!

**Comment by zjdtmkhzt** [comment]
The signaler needs to be screwdrivered first so it can be modified, then you will be able to attach it to a helmet to make an assembly.
Perhaps we should add a message when a user skips this step, to make it more clear.
