### ISSUE TITLE
Quantum linked deconstructed objects

### ISSUE THREAD

**Issue by HBS-System** [goonstation/goonstation#13173]
### Labels

[BUG]

### Description

Deconstructing an item twice using difficult timing creates a duplicate, quantum linked deconstructed item

### Steps to reproduce

1. Begin deconstructing something.
2. Right before the object deconstructs, click the object to deconstruct it again. The timing for this is a pain in the ass and may take several attempts!
3. You will know you get the bug when you initiate another deconstruct despite it already being deconstructed. Let this finish!

### Expected Behavior

I expect to be unable to deconstruct an object to get two quantum linked boxes!

### Additional Information & Screenshots

When constructing one and attempting to construct the other, the original object will be teleported to the spot you constructed the second item, allowing you to drop free flashes batons or stuns, wait 10 minutes then steal them right out of everyone's inventories by constructing the secondary boxes, but only if you drop it after making it or make it on the floor!

![dreamseeker_CZKYOr1Adh](https://user-images.githubusercontent.com/34522718/221033749-fa919891-a8d9-4e9b-b0eb-9f901d934f33.png)

![dreamseeker_7VNlJGwTsB](https://user-images.githubusercontent.com/34522718/221033764-22407def-6e5a-483d-ab15-bf98b694e923.png)

![dreamseeker_x50K64yPHc](https://user-images.githubusercontent.com/34522718/221033784-074f7d08-4a35-4a68-9470-b55c8a8af02a.png)

![ShareX_Ozs0Dd5yuE](https://user-images.githubusercontent.com/34522718/221033801-691eeec8-fb9a-4514-bdea-b7daae0601c6.png)

this was a disaster of a bug report.

**Comment by HBS-System** [comment]
Holy shit, there. fixed the report

**Comment by Tarmunora** [comment]
probably fixed by https://github.com/goonstation/goonstation/commit/2358ce520f0d548ee7ba8dcd7943ab071430abf4
