### ISSUE TITLE
Chem duplication using wooden doors

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#13171]
### Labels

[BUG]

### Description

Placing a bucket with any amount of chemicals in it on a wooden door, then opening said door will duplicate the buckets chemicals.

### Steps to reproduce

1. Build wooden door
2. Fill a bucket with something
3. Place the bucket on the door
4. Open the door but don't walk under it
5. The bucket is dropped and still full, despite a puddle being made
6. Collect the puddle and you have 2x the amount you started with

### Expected Behavior

Don't do that

**Comment by TobleroneSwordfish** [comment]
Fixed in f1f4b25
