### ISSUE TITLE
Borgs recharging drain apcs very quickly

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#13202]
### Labels

[BUG]

### Description

Borgs, when recharging in a station, draing an apc very quickly, often resulting in the apc losing power

### Steps to reproduce

1. Be a borg
2. Run low on power
3. Go to a recharge dock
4. Enter it
5. Notice the room lose power shortly after entering the recharge dock

### Expected Behavior

For borgs recharging to not depower a room.

**Comment by nefarious6th** [comment]
Duplicate of #13156
