### ISSUE TITLE
Cyborg Docking Stations overcharge occasionally, causing massive APC usage even when the borg's cell is already topped off.

### ISSUE THREAD

**Issue by LikeLakers2** [goonstation/goonstation#13219]
### Labels

[BUG] [MAJOR]

### Description

Cyborg Docking Stations occasionally overcharge the cyborg's cell, even when the borg's cell is already (or mostly) topped off, causing massive usage from the APC power cell.

### Steps to reproduce

1. Insert a borg into a docking station
2. Allow the borg's cell to finish charging
3. Leave the borg in the docking station, and inspect the APC
4. Note occasional spikes in power usage, despite the borg's cell being fully charged.

### Expected Behavior

I would expect the cyborg docking stations to not use incredible amounts of power while the borg is already topped off.

### Additional Information & Screenshots

(Click the arrows next to the text to show the relevant videos!)

<details>
<summary>From a round on the 24th, before b6d80021a2a80c35f652b0acc9c0fb4cf15657ba</summary>

This is with a 15000 PU power cell.

https://user-images.githubusercontent.com/1008889/221709489-3a767564-73c9-498f-b62a-8fae27175512.mp4
</details>

<details>
<summary>And from a more recent round (today), after b6d80021a2a80c35f652b0acc9c0fb4cf15657ba</summary>

This is with the APC's default power cell (which I believe starts at 2500 PU).

https://user-images.githubusercontent.com/1008889/221709441-f65440fc-dd34-4455-82fd-42db21462870.mp4
</details>

(Please note the power cell differences noted above each video, as they explain why the newer recording shows more percentage lost each cycle.)

The changes made in b6d80021a2a80c35f652b0acc9c0fb4cf15657ba between these two recordings seem to help with the issue at hand, by reducing the usage from the APC... though even with its current usage, you can see how this bug would easily cause the APC to drain just by a borg sitting in the dock.

Additionally, it's worth noting how the excess power in a borg's cell is simply wasted - meaning that not only is the dock occasionally overcharging, but outright wasting power in trying to top off the borgs.

**Comment by LikeLakers2** [comment]
To be clear, I am aware of #13202. However, this issue regards borgs overcharging, whereas that issue is about charging normally. Therefore, I feel it's a separate issue.

**Comment by Azrun** [comment]
Great write-up by the way!

**Comment by LikeLakers2** [comment]
Thank you! c:
