### ISSUE TITLE
Round-Start-Shocked Door near Robotics on Donut 3 cannot be interacted with by Ghostdrones

### ISSUE THREAD

**Issue by LikeLakers2** [goonstation/goonstation#13215]
### Labels

[BUG]

### Description

The door that starts off shocked, in the maintenance area near Robotics on Donut 3, cannot be interacted with in any way by Ghostdrones (except by using the screwdriver on it, but that doesn't mean much).

### Steps to reproduce

1. Try to interact with that door.
2. Find that you can't.

### Expected Behavior

Ghostdrones would be able to interact with it, either by opening/knocking on it with a non-tool click, or by using tools other than the screwdriver

### Additional Information & Screenshots

Ghostdrones can still fly through it, they just cannot interact with it.

Here is a video of me trying to interact with it, at first with nothing in my tool slot, then with the Omnitool:

https://user-images.githubusercontent.com/1008889/221496406-bb5cb82f-bc4c-4e15-ab52-da652e98b792.mp4

**Comment by Sord213** [comment]
Donut 3*

**Comment by flappybatpal** [comment]
This door has aicontroldisabled, expected behavior.
