### ISSUE TITLE
Conspicuously shuttle shaped hole in the nadir ocean lighting

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#13225]
### Labels

[BUG] [MAPPING] [MINOR]

### Description

The blue tint is missing from where the shuttle should spawn

### Steps to reproduce

1. Start a round on nadir (i was an observer but i don't think that was important)
2. navigate to escape
3. oh
![(null)scrnshot1](https://user-images.githubusercontent.com/51260013/221767276-01b1ceec-848a-4a6c-88e5-c17ae9ae8201.png)

### Expected Behavior

The colour of the ocean be uniform

### Additional Information & Screenshots

posting the image again here just in case.
![(null)scrnshot1](https://user-images.githubusercontent.com/51260013/221767276-01b1ceec-848a-4a6c-88e5-c17ae9ae8201.png)

**Comment by RelentlessGarbage** [comment]
Is there acid in those tiles, or is it only a visual glitch?

**Comment by TheTyrant25** [comment]
![image](https://user-images.githubusercontent.com/51260013/222054979-f358333a-f383-41b3-a92e-58f471ce1b96.png)

The missing hole is for the john's bus shuttle thing, and it's visual only, the acid is still there and still burns
