### ISSUE TITLE
AI Monkeys and item arms

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1323]
[BUG]

**Describe the bug**
AI Monkeys can throw the item they have attached as an arm

**To Reproduce**
1. Replace monkey arms with rubber ducks
3. aggro monkey
4. monkey throws duck and can now punch you damaging you

**Expected behavior**
them not be able to throw it

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/86491740-8b88b800-bd39-11ea-8c4e-c775332de678.png)

**Comment by Tarmunora** [comment]
Item arms WHY
