### ISSUE TITLE
Secure briefcase inventory stays open and items can be taken after lock

### ISSUE THREAD

**Issue by soleilan** [goonstation/goonstation#13265]
### Description

If you have the inventory open and then you lock the briefcase, the inventory stays open. You can take stuff out, but not put it back in.

### Steps to reproduce

1. Open secure briefcase inventory
2. Lock it shut
3. Grab stuff out of it anyway

### Expected Behavior

For you not to be able to interact with stuff in it

**Comment by nefarious6th** [comment]
duplicate of #12069

**Comment by soleilan** [comment]
shit you right
