### ISSUE TITLE
The plasmastone catches on fire!x23

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1326]
[BUG]

**Describe the bug**
horrendous lag caused by setting the plasma stone directly on fire
**To Reproduce**
1. heat plasma stone with wilder aka hit it with welder in hand
2. it catchs fire
3. it be in a box of say 40,
4. they all catch fire
5. horrendous lag

**Expected behavior**
not to horribly lag

**Comment by Carbadox** [comment]
is this really a bug or just "lots of things happening at once and causing lag"?

**Comment by pali6** [comment]
The latter.
