### ISSUE TITLE
Reloading powercell in inv breaks the hud 

### ISSUE THREAD

**Issue by Whootookgaming** [goonstation/goonstation#13288]
### Labels

[BUG]

### Description

When you try to reload a gun or stun baton with a power cell while the power cell is inside a object it makes the inv you are currently using to go to the side making it impossible to click on items requiring you to re open the slot, while using hud mithrill 

### Steps to reproduce

1. Have a power cell and something that needs a power cell
2. Put a power cell in a inv item like a belt 
3. Click on powercell with item that needs said power cell
4. And boom your hud should be on the side making it impossible to click on anything 

### Expected Behavior

Not for the hud to break when reloading 

### Additional Information & Screenshots

![Capture](https://user-images.githubusercontent.com/127061302/222995314-a9a1ffd8-a192-47d4-afef-67b2b4961036.PNG)

**Comment by FlameArrow57** [comment]
#7002
