### ISSUE TITLE
pest spawn event frogs robogib

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#13315]
### Labels

[BUG][minor]

### Description

As title.

### Steps to reproduce

1. turn into a frog from a spawn event
2. gib
3. see error

### Expected Behavior

blood and gore

### Additional Information & Screenshots

I died from the effects of being forcefed a ghost chili juice pill, in case the chem has anything to do with it

**Comment by pgmzeta** [comment]
#21691
