### ISSUE TITLE
MapDiffbot 2 doesn't handle mob change diff correctly

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#13313]
### Description

When comparing diff between map changes, mobs aren't highlighted in red.

### Steps to reproduce

1. make a mapping change that deals with mobs
2. view the diff
3. cry when you can't tell what mobs are changed

### Expected Behavior

All diff is highlighted for ease of viewing and review

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/113442598/223397126-0a489a5f-4fa6-4b2d-926d-0604290bf5ac.png)

Case of object critter to mob critter

**Comment by Mister-Moriarty** [comment]
You may report this at https://github.com/spacestation13/BYONDDiffBots/issues.

**Comment by CheffieGithub** [comment]
reported there
