### ISSUE TITLE
[BUG] As AI, doors automatically open right after manually disrupting their power, or dropping the bolts

### ISSUE THREAD

**Issue by tron359** [goonstation/goonstation#1332]
As an AI, open the door interface, and drop the door bolts. The doors will immediately open and lock into place.

As the same, disrupt the backup and main power, the door will immediately open before powering down.

**Comment by MarkNais** [comment]
Please follow the bug submission template next time.

**Comment by flappybatpal** [comment]
Not reproduced. Doors behave as expected.
