### ISSUE TITLE
Changeling granting control to a hivemind member with different UI bugs out.

### ISSUE THREAD

**Issue by Spell-Tech** [goonstation/goonstation#13329]
### Labels

[BUG]

### Description

If a changeling who is using default UI settings grants control to a hivemind member who uses TGUI, the controlling player will have a weird mess of both UIs combined.

### Steps to reproduce

1. Turn on TGUI
2. Get eaten by a changeling who uses default UI
3. Have the changeling grant control to you
4. UI freaks out

### Expected Behavior

I expected to keep my UI setting I had before getting eaten.

**Comment by FlameArrow57** [comment]
#12314
