### ISSUE TITLE
Cog1 engineering power room blinds nonfunctional

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#13332]
### Labels

[BUG][mapping]

### Description

The blinds between the power room and mechlab don't lower.

### Steps to reproduce

1. Go to the power room
2. Flip the blinds switch
3. nothing happens

### Expected Behavior

Functional blinds

### Additional Information & Screenshots

Probably an issue of areas

**Comment by Kubius** [comment]
Just checked map and the blind switch in the engineering power room is indeed not in the same area, nor paired with an ID to those blinds, so it does appear to be a mapside issue. (Those blinds should also likely be single blinds.)

**Comment by Sord213** [comment]
Fixed....
