### ISSUE TITLE
Cell chargers take in TOO MUCH power

### ISSUE THREAD

**Issue by trollbreeder** [goonstation/goonstation#13337]
### Labels

[BUG][STATION-SYSTEMS][MAJOR]

### Description

Cell chargers, when loaded with an empty battery, draw in about 125 kilowatts of power, which is ridiculous to say the least

### Steps to reproduce

1. Go to a place with a cell charger (ex. Robotics)
2. Put an empty battery cell into the charger
3. Check the APC equipment load:  expect to see 126 kW (normal load is 0.3 kW)
4. Expect to see the lights turn off, then the computers and the airlocks

### Expected Behavior

That the load does not increase to exceeding 2x-4x what the TEG can output when charging a measly little battery

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25937686/224108034-c6e3f541-01e7-452a-b244-b22cbcd5df7b.png)

**Comment by paneras** [comment]
Can confirm, same thing happened in EVA after replacing a power cell.

**Comment by MeggalBozale** [comment]
I'm seeing a normal 0.3kW added when I attempt to reproduce this with all of the cell types in Cogmap 2's robotics by placing an uncharged power cell into the cell charger, then observing the equipment power draw. Did you do anything else to cause this to happen?

**Comment by soleilan** [comment]
bandaid fixed by b96bbd7
