### ISSUE TITLE
Other players can't hear detached skeleton heads while holding

### ISSUE THREAD

**Issue by RhapsodySL** [goonstation/goonstation#13341]
### Labels

[BUG]

### Description

If a skeleton player detaches their head and holds it in their inventory, they can see the floating text in their inventory. Other players cannot see them typing in this state. This behavior is fine and expected. However, if _another_ player is holding the skeleton head, then they can't hear the skeleton player at all, and the floating text doesn't appear in their inventory. Ideally, a player holding another player's skeleton head should be able to hear the skeleton player provided the head is in their hand.

### Steps to reproduce

1. Play as a skeleton, and detach your head
2. Hold your head in your hands, note how you can see the floating text above the head in your inventory when you talk
3. Give the head to another player, then type in chat. Note how the other player can't hear you talk, and no floating text appears above the head in their inventory.

### Expected Behavior

Other players should be able to hear the skeleton speak while holding their head. Ideally everyone can hear them (since you have to drop the head to hear the skeleton again regardless of who is holding the head), but only the player holding the head being able to hear the skeleton would also make for some interesting opportunities.

**Comment by Chatauscours** [comment]
Fixed by #13932
