### ISSUE TITLE
Character glitches when treads are equipped

### ISSUE THREAD

**Issue by paneras** [goonstation/goonstation#13345]
### Labels

[BUG]

### Description

When a player has treads, some parts of the character sprite will disappear and will bug out when equipping or unequipping items (backpack sprite is duplicated, character becomes fully invisible when facing a certain way, etc.)

### Steps to reproduce

1. Go to robotics
2. Get a surgery to get cool treads
3. Sprite glitches out

### Expected Behavior

Sprite does not glitch out

### Additional Information & Screenshots

Another minor issue, although not a bug, is that when equipping treads, you are still wearing boots and legwear. Some boots of course have status effects and it does not make any sense for both treads and boots to be equipped. A solution would be to automatically unequip boots and legwear when a player gets their legs chopped off, or prevent the surgeon from operating unless pants are removed. You could then have a leg with a boot on it which would be pretty cool.

**Comment by TheTyrant25** [comment]
this ties into the overall jankiness of limb code

**Comment by TealSeer** [comment]
Hopefully fixed in https://github.com/goonstation/goonstation/commit/dfe2096953affe9a96f1ebf9d39c6b3553260ba6
