### ISSUE TITLE
AI Shells Do Not Use The New Cyborg Talking Sound

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#13343]
### Labels

[BUG]

### Description

AI shells (the round ones, at least) do not use the talking sound that was recently given to cyborgs

### Steps to reproduce

1. Be AI
2. Enter round shell
3. Talk
4. Notice a distinct non-robot sound to it
5. Cry from you fleshy sounding robot mouth

### Expected Behavior

For it to use the cyborg talking sound

**Comment by virvatuli-gh** [comment]
this isn't a bug. the changelog explicitly says _cyborgs_ have a new talking sound, not _silicons_
