### ISSUE TITLE
Cyborg vocal pitch doesn't effect new talk sounds

### ISSUE THREAD

**Issue by Monoblaster** [goonstation/goonstation#13350]
### Labels

[BUG]

### Description

The cyborg vocal pitch command does not effect the new talk sound but does effect emotes like scream.

### Steps to reproduce

1. Change your vocal pitch to low
2. Talk
3. Scream
4. The pitches are very different

### Expected Behavior

For vocal pitch to have a noticable effect on chat sounds.

**Comment by soleilan** [comment]
i'm *pretty* sure pitch affects new talk sounds? granted emotes are always going to be higher very different pitch

**Comment by soleilan** [comment]
i'm *pretty sure* pitch affects new talk sounds. granted emotes are always going to be very different pitch. maybe the talk sounds could get bigger pitch variations but I'm like 99% sure pitch affects them just fine. @virvatuli-gh pls confirm im not crazy

**Comment by virvatuli-gh** [comment]
This is incorrect, it does effect the talking vocal pitch, however said vocal pitch also varies natively as well. If you try to use the low pitch, you will have a ~baseline~ lower pitch and it will still vary slightly up and down, then if you try to set it to the high pitch, you'll notice a much higher baseline. This functionality is to prevent the same pitch being played line to line, avoiding monotonous sounds.
