### ISSUE TITLE
Deploying to a shell as AI causes connection problems

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#13353]
### Labels

[BUG]

### Description

Deploying to a shell, specifically the round ones, will occasionally cause a reconnect

### Steps to reproduce

1. Be AI
2. Try to deploy to a shell
3. Connection issue

### Expected Behavior

For a connection issue to not happen when deploying to a shell

**Comment by flappybatpal** [comment]
Duplicate of https://github.com/goonstation/goonstation/issues/8688
