### ISSUE TITLE
Phone displays wrong GUI when ringing

### ISSUE THREAD

**Issue by paneras** [goonstation/goonstation#13362]
### Labels

[MINOR]

### Description

When calling someone using the physical phone, the GUI will display "LINE BUSY" every time, even though no one ever uses it.

### Steps to reproduce

1. Pick up the phone, baby!
2. Call someone
3. Notice "LINE BUSY" displayed on the Phone GUI.

### Expected Behavior

For the text to be displayed be "RINGING" or something similar, expect when the line is actually busy.

**Comment by DisturbHerb** [comment]
Not a bug. Was intended when the interface was implemented.
