### ISSUE TITLE
Scuttlebot locker

### ISSUE THREAD

**Issue by crasscrab** [goonstation/goonstation#13378]
### Labels

[BUG]

### Description

If a scuttlebot is locked in a locker user is unable to exit out of the scuttlebot view. 

### Steps to reproduce

1. Place scuttlebot in locker
2. Lock or weld (havent actually tried welding locker/closet but probably has same effect) locker. 

### Expected Behavior

Should be able to exit scuttlebot viewer/control if this happens.

**Comment by TobleroneSwordfish** [comment]
soul captured
