### ISSUE TITLE
In game bug report is broken

### ISSUE THREAD

**Issue by ATDoop** [goonstation/goonstation#13384]
### Labels

[BUG]

### Description

Using the in game bug report button doesn't send an issue to github. I dunno if it's a problem on the game side or a problem with the bot but it hasn't posted in around a week, and a bug I reported using the button never showed up, so I assume something is wrong.

### Steps to reproduce

1. Press bug report
2. Report bug
3. No issue on github

### Expected Behavior

Bug report reports bugs

**Comment by DisturbHerb** [comment]
successfully reproduced. most likely an issue with the bot or communications to the bot.

**Comment by DisturbHerb** [comment]
Fixed as of #13398.
