### ISSUE TITLE
Spy Thief Stowaway bug

### ISSUE THREAD

**Issue by ProperPickle** [goonstation/goonstation#13385]
### Labels

[BUG]

### Description

Spy Thief with stowaway trait doesn't get the headset uplink

### Steps to reproduce

1. Have the stowaway trait
2. Be selected as a spy thief
3. Not have PDA as a result of stowaway trait
4. In notes only have a PDA uplink code and a normal headset
5. Be very sad as you can do almost nothing without the uplink

### Expected Behavior

I expected to get an uplink headset and an applicable uplink code.

**Comment by pgmzeta** [comment]
stowaway is now a latejoin job, and so can't roll spythief
