### ISSUE TITLE
Syndicate borg frames do not retain their syndicate status when deconstructed and rebuilt

### ISSUE THREAD

**Issue by SolarWraith** [goonstation/goonstation#13396]
### Labels

[BUG]

### Description

Whenever a borg gets completely deconstructed after being assembled with a syndicate frame they do not regain its antag status upon being rebuilt with the same frame. (antag : In this case the meaning of a syndicate robot antagonist status)

### Steps to reproduce

1. Construct a borg with a syndicate frame
2. Activate it and they should have a pop-up as usual for the antag status
3. Disassemble the borg completely, when they ghost they will be told they no longer retain their antag status
4. Assemble the borg and activate it with the disassembled parts, the borg will no longer have a pop-up as expected and will simply be a normal borg

### Expected Behavior

I expected the syndicate frames to retain their antag status even after a borg gets completely disassembled. It may be an intentional mechanic however that is something unspecified so I thought I'd create a bug report just in case this is an actual bug.

**Comment by frawhst** [comment]
Definitely not intended, I thought I fixed this. Probably related to antag datumization?
