### ISSUE TITLE
Wasp egg crossbow only spawns wasps on half its projectiles

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#13391]
### Labels

[BUG]

### Description

When a wasp egg bow is shot, it shoots 4 eggs but only 2 spawn wasps.

### Steps to reproduce

1. Get a wasp egg bow
2. Shoot it and see 4 projectile eggs
3. Only 2 wasps spawn :(

### Expected Behavior

All 4 eggs should spawn a wasp

### Additional Information & Screenshots

I asked if this was intentional or not and it seemed like it is not intentional and it should be spawning 4.

**Comment by RubberRats** [comment]
Did a bit of testing on local. Seems like which projectiles actually spawn the wasps is completely random. Also managed to get it to spawn 3 somehow.
