### ISSUE TITLE
Ghost critters see the wanted

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1340]
[BUG]

**Describe the bug**
Toggle Arrest status in the ghost tab does not properly turn off when becoming a ghost critter, thus ghost critters are able to see crimers

**To Reproduce**
1. toggle arrest status as ghost
2. become ghost critter
3. see the crimers

**Expected behavior**
not to be able to see the crimers as a ghost critter

**Additional context**
problem does not exist with Toggle Health

**Comment by moonlol** [comment]
Duplicate of #1163
