### ISSUE TITLE
You can weld player crafted wooden and bamboo furniture shut

### ISSUE THREAD

**Issue by RelentlessGarbage** [goonstation/goonstation#13402]
### Labels

[BUG]

### Description

Exactly as the title says. Making furniture out of thouroughly non-weldable materials (i.e. wood and bamboo) still allows them to be welded shut.

### Steps to reproduce

1. Grow or obtain wood or bamboo construction materials
2. Use them to make a Dresser
3. Use a lit welder on the dresser
4. Succeed in welding shut the wooden/bamboo dresser, despite it being made of highly combustible organic fiber.

### Expected Behavior

I expected to be unable to weld wood, based on common-sense understandings of how wood works.

### Additional Information & Screenshots

This may be intentional behavior by the developers, but I'd suggest that things made of wood should not be weldable. It's not like steel is that hard to come by as a botanist anyways, if you wanted to make containers that could be welded shut.

**Comment by Retrino** [comment]
not really a bug, the material doesn't exactly catch on fire and burn.. feature request
