### ISSUE TITLE
glass shards from tables and windows do not stack together

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#13413]
### Labels

[BUG][minor]

### Description

As title.

### Steps to reproduce

1. break a glass table
2. break a window
3. try to use the shard from one on another
4. no stacking

### Expected Behavior

for these to stack with each other

### Additional Information & Screenshots

probably one of the two is spawning the glass subtype of the shard and the other is spawning the shard base type, then setting its material to glass.

**Comment by NightmareChamillian** [comment]
@ whoever ends up fixing this: I have some code in the pipeshot crafting document that differentiates, but doesn't treat the two glass shard types as separate things. Could probably reuse that.
