### ISSUE TITLE
Borgs can put their items into trash bags

### ISSUE THREAD

**Issue by Ormakent** [goonstation/goonstation#13426]
### Labels

[BUG]

### Description

Just as in the title

### Steps to reproduce

1. Find a trash bag
2. Left click on it with a borg's tool
3. Said tool is now in the bag. Borg can fix their tool by dropping the empty slot on their toolbar and reselecting the tool from the tool inventory. Humans can take out the tool out of the trash bag and obtain a usable copy of the item (interactions of which are out of the scope of this issue).

### Expected Behavior

Restrict borgs from clicking trash bags with their items.

**Comment by TobleroneSwordfish** [comment]
fixed in #13439
