### ISSUE TITLE
OpenDream procpath bits need to be updated 

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#13420]
With the recent BYOND update, the syntax to access proc type at compile time (see .....) has been made official - the temporary named OpenDream ones need to be updated as such.

**Comment by ike709** [comment]
To be more specific, `opendream_procpath` needs to be replaced with `__PROC__` (or `__TYPE__` if you don't want the proc name to be included). These new keywords are the BYOND 515 equivalent of `.....`
