### ISSUE TITLE
Some of the leftover long/infinite range interactions with borg

### ISSUE THREAD

**Issue by Ormakent** [goonstation/goonstation#13425]
### Labels

[BUG]

### Description

Just a couple of borg interactions with machines/objects which should probably not have extended range based on how the rest of them were changed in the past.

### Steps to reproduce

1. Open the hatch on a stomper unit (with crowbar). You can now remotely remove the cell from stomper unit from anywhere within vision range by left clicking on it.
2. Left click on a lamp (tripod + lightbulb assembly made in nano-fab) from any distance within vision range, it will break down into its 2 parts. I haven't tested other stuff made in nanofab because frankly I've never seen it being made, but there probably are some more interactions like that there.
3. Open up a quantum telescope and just leave it on your screen, it will never go away and it will work even on different z-level. Could be especially annoying if you block access to other people trying to use it for the entire round.
4. Get into cyborg recharging dock and open the name change field. Leave the dock without choosing a name or closing the input field. You can now change your name anywhere at any point if you desire to do so (still only once).

### Expected Behavior

1-2. Just can't do remotely.
3. Have the console access either fade out after about 10 tiles like other consoles or just close.
4. Close the name input field after exiting the dock.

**Comment by soleilan** [comment]
1-2 should probably be fixed, 3 someone tgui telescope :) and 4 is so trivial I don't even think I'd bother to fix, could open up some fun interactions

**Comment by soleilan** [comment]
1-3 been fixed, I don't care about 4 but I'll keep the issue open
