### ISSUE TITLE
AI Turret Control panel on Atlas spawns underneath the window

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#1343]
[BUG]

**Description**
On Atlas in the AI Core, the turret control panel is layered beneath the windows and grille, making it impossible to interact with without using the clunky ctrl+alt+shift+click technique.

**To Reproduce**
N/A, it is a mapping issue occuring at roundstart

**Expected behavior**
The control panel should be at the uppermost layer, above the grille and windows, much like how the AI Core Shield button is.

**Screenshots**
Current behavior. Note that the panel isn't even visible 
![image](https://user-images.githubusercontent.com/28785926/86519458-d8878f80-be08-11ea-9703-5e40fb9ce24d.png)

Expected behavior, based on the Goonhub Atlas map
![image](https://user-images.githubusercontent.com/28785926/86519589-133df780-be0a-11ea-9e0d-76a6ba04b99e.png)

When you right-click the window
![image](https://user-images.githubusercontent.com/28785926/86519545-acb8d980-be09-11ea-9986-ee87ae7bd03d.png)

When you use alt+shift+click on the floor to the left of where the panel should be visible (where the panel's actual loc is). This is a screenshot of the Status panel, of course. While the panel is interactable from here, even as AI, it is still a workaround.
![image](https://user-images.githubusercontent.com/28785926/86519471-f8b74e80-be08-11ea-9e16-fae99113bd0d.png)

**Additional context**
I believe core shield buttons had similar issues recently, wherein they would visibly be underneath the window/grille and would require a similar technique to access. This has already been fixed and I would imagine a similar fix might occur for the control panel?

**Comment by pali6** [comment]
Fixed by some recent plane changes. Can't be bothered to find the commit.
