### ISSUE TITLE
Higher range protection makes bullets hurt more (technically)

### ISSUE THREAD

**Issue by ThePastTenseOfYeetIsYote** [goonstation/goonstation#13447]
### Labels

[BUG]

### Description

The more ranged protection you have, the more you bleed.

### Steps to reproduce

1. Get a staff assistant with 1 ranged protection. 1 shot of .38 from detectives revolver at point blank does 35 brute and removes about 10 blood.
2. Get captain chad with 4.5 ranged prot. 1 shot of .38 from detectives revolver at point blank does 7.78 brute and removes about 50 blood.
3. Get a power gamer CHUD with 6 ranged prot. 1 shot of .38 from detectives revolver at point blank does 5.83 brute and removes about 70 blood.

### Expected Behavior

More ranged protection means more ranged protection, currently your blood just falls out.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/57043547/227771191-a572a75e-b213-42d9-9c40-ff2741d559f0.png)
![image](https://user-images.githubusercontent.com/57043547/227771206-5da5c542-c9c3-449e-8c8f-3081b848a263.png)
![image](https://user-images.githubusercontent.com/57043547/227771272-1b1f3e68-7ae9-4c2a-ab41-0c671b664928.png)

**Comment by RubberRats** [comment]
This got fixed in 0ff2756

**Comment by MeggalBozale** [comment]
Can confirm, tried to test this bug in a private server and the bleed was worst for those unarmored,
Unarmored:
![dreamseeker_8OPpgi8hTk](https://user-images.githubusercontent.com/27376947/228525539-3af3c346-299d-46df-bd6a-8abe67a38c68.png)
Light vest (security):
![dreamseeker_scWMBtgOKH](https://user-images.githubusercontent.com/27376947/228525606-eb1f3ea2-bfb9-4b7d-b7ca-7f5a6f548e3a.png)
Heavy vest (armory):
![dreamseeker_a5IIawunxE](https://user-images.githubusercontent.com/27376947/228525647-a4a23e65-cd65-460f-bb25-725e1ddc8a5e.png)
