### ISSUE TITLE
SecHUD eyes don't block flashes

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#13465]
### Labels

[BUG] [MAJOR]

### Description

While having secHUD eyes implanted, they don't prevent you from getting flash stunned

### Steps to reproduce

1. Get secHUD eyes implanted
2. Run into a portable flasher, or get flashed by someone else
3. Even when having both of them, the flash only gets deminished, in contrast to a single polarized eye preventing flashes (unless you have extra vulnerability)

### Expected Behavior

Since the wiki states they work as sunglasses, I expected them to prevent flashes as well.

**Comment by soleilan** [comment]
huh, I swear they worked like, a week ago?

**Comment by Sord213** [comment]
As far as I know, this is intentional. The sechud glasses security gets are just a pair of sunglasses with the sechud attached. The eyes just give you the overlay.
