### ISSUE TITLE
Crematorium produced a victim's invisible head

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#13494]
### Labels

[BUG][minor][needs reproducing]

### Description

I found an invisible head in the crematorium that also had no eyes. I get the feeling it was supposed to be disposed but ended up accessible on accident

### Steps to reproduce

Cremate some folks I guess? The bug happened by chance, and since it's a 10% roll on anything in the mob to drop when cremating so you might want to artificially speed up the process when testing this on local.

### Expected Behavior

no invisible heads at least

### Additional Information & Screenshots

The body had a head when it went into the crematorium and I think their mutantrace was skeleton. I don't believe the body was rotting. An examine of the body didn't show missing eyes, but IDK if that's blocked by wearing sunglasses.
Among the remains were also the victim's skull, which I figure I'd mention because the head normally has a reference to one.

The head is in my left hand in this screenshot
![image](https://user-images.githubusercontent.com/31984217/228648574-267d7294-24eb-438f-a6f0-728c807c9fef.png)

Apologies for the vagueness, can't exactly investigate this stuff when I run into it live.

**Comment by TheTyrant25** [comment]
this seems... quite specific
wonder how this happened...
