### ISSUE TITLE
Auto-catwalks don't work in map editors.

### ISSUE THREAD

**Issue by CaioFrancisco** [goonstation/goonstation#13500]
### Labels

[BUG]

### Description

Auto-catwalks show the "FIX ME!" sprite on map editors, unlike in normal gameplay.

### Steps to reproduce

1. Open up your favorite map editor
2. Look at any catwalks
3. "FIX ME!" "FIX ME!" "FIX ME!"

### Expected Behavior

For it to not use the "FIX ME!" sprite

### Additional Information & Screenshots

This is probably happening because map editors aren't running `update_icon`, and instead are just using the default icon_state of catwalks, which I didn't update in my PR, because I trusted the auto-catwalk system would do the heavy-lifting of picking the right sprite. Well, it doesn't in map editors. Here's a few screenshots of it happening:
![image](https://user-images.githubusercontent.com/36608862/228835175-9f1066a7-ebe9-4836-8614-70c255e4b8cd.png)
![Screenshot_610](https://user-images.githubusercontent.com/36608862/228835542-e609bb13-5a3b-4990-b6ca-2dc857dc28dd.png)

**Comment by TheTyrant25** [comment]
fairly certain this is no longer the case
