### ISSUE TITLE
Pikaia have no cooldown for their flip/suplex

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#13568]
### Labels

[BUG]

### Description

as above

### Steps to reproduce

1.find a pikaia
2.let it grab you
3.scream
4.die a horrible death being suplexed to death

### Expected Behavior

not that

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/63602513/229869122-0ba82750-9da8-4047-8fe7-129a01921e03.png)

**Comment by RelentlessGarbage** [comment]
Wrestler belt Pikaia

**Comment by TobleroneSwordfish** [comment]
fixed in ab989ec
