### ISSUE TITLE
Using Wide Area Spawn to make Turfs makes dense objects not dense anymore

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#136]
**Describe the bug**
Use Wide Area Spawn tool to spawn some floor somewhere, underneath dense objects like tables and computers and doors. You'll be able to walk right over them

**To Reproduce**
1. Spawn some floors under a table with Wide Area Spawn
2. Walk over the table

**Expected behavior**
Turfs should change, but not the objects on those turfs

**Screenshots**
N/A

**Additional context**
N/A

**Comment by mybluecorners** [comment]
this is because of the `checkingcanpass` thing - the var gets wiped when turfs are deleted, so turf replacements need to use the ReplaceWith() proc or some variation of it to carry over relevant data
