### ISSUE TITLE
blank/empty ingredient in chef cake crew objective

### ISSUE THREAD

**Issue by pgmzeta** [goonstation/goonstation#13664]
### Labels

[BUG]

### Description

crew objective for chef missing an ingredient

### Steps to reproduce

1. Roll the chef job
2. Get crew objectives
3. One of the ingredients is empty in the objective

"Objective #2: Create a custom, three-tier cake with layers of eggplant, , and slice of pie infused cake in any order."

### Expected Behavior

ingredients all exist/are shown

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/91498627/231601658-4d1cce55-b56f-42ff-bd5a-32f98712575c.png)

**Comment by CaioFrancisco** [comment]
Frequent problem that nobody bothered to fix yet. I think you'll find a similar issue by searching it here.

**Comment by mloccy** [comment]
Not able to repro any more. Suspect this was fixed in 23bd1dff656
