### ISSUE TITLE
/mob/living/critter/spider/baby is deadly now and atlas has 8 of them

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#13673]
### Description

Formerly, the baby spider critters were basically harmless and wouldn't attack anyone. The new mobified spiders will attack people on sight, and will also sometimes kill and drain random monkeys to become even more powerful.

### Steps to reproduce

1. Load atlas
2. Enter maint
3. Die?

### Expected Behavior

Should probably be replaced with bumblespiders or removed altogether

### Additional Information & Screenshots

relayed by mbc

**Comment by wolfolotl** [comment]
wait this isn't intentional?

**Comment by frawhst** [comment]
They didn't attack pre-mobification, so we could file it under emergent gameplay but it's technically unintended
