### ISSUE TITLE
*spin-ning an item no longer displays a message in the chat 

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#1367]
**Describe the bug**
*spin-ning an item no longer displays a message in the chat 

**To Reproduce**
1. Hold an item in hand
2. Open chat and type *spin
3. Item spins in hand
4. But no text

**Expected behavior**
Text should appear about how the user spins the item in their hand

**Additional context**
I think I remember a certain change that adjusted something to how Clown juggling works, I believe that that might have caused this bug,

**Comment by zjdtmkhzt** [comment]
I think #1370 should have fixed this, are you still experiencing the issue?
