### ISSUE TITLE
Items can fit in a small container by using the hotkey

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#13687]
### Labels

[BUG] [MAJOR]

### Description

Medium sized items can be added to a wrestling belt (and probably other containers as well) by using the V hotkey instead of clicking

### Steps to reproduce

1. Get a normal sized item and a belt with an open slot (I used the thunderdome spear and plasma rifle in particular)
2. Press the quick wear hotkey (V by default)
3. It will bypass size restrictions and go into the belt

### Expected Behavior

I expected the belt to only accept properly sized items, regardless if you click or quickwear

### Additional Information & Screenshots

![hotkey](https://user-images.githubusercontent.com/62149527/232206457-f1a253ec-8645-4adc-9ef9-4bcf101c1f30.png)

**Comment by Exester509** [comment]
Further testing has revealed that it can hold unwearable items up to bulky size, as shown by this image.

![glitch2](https://user-images.githubusercontent.com/62149527/232206874-be7751d6-bf10-47d7-ac16-c97b266df952.png)

**Comment by FlameArrow57** [comment]
Fixed in #13023 https://github.com/goonstation/goonstation/pull/13023/commits/16a46705410d2038bd5c5e7c20a1e1046a4ffe5b
