### ISSUE TITLE
Experimental Health Implant not working when exploded.

### ISSUE THREAD

**Issue by RukertJoe** [goonstation/goonstation#13686]
### Labels

[BUG] [MAJOR] [SECRET]

### Description

This bug occurs when implanted with the Experimental Heath Implant, If gibbed you are not cloned at the secret pod bay cloner.

### Steps to reproduce

1. Implant the Experimental Health Implant at the secret pod base.
2. Implant Microbombs inside of you
3. Get into critical and explode microbombs inside of you
4. Proceed to not get cloned.

### Expected Behavior

I expected to be cloned after exploding with microbombs since I had the health implant before the explosion.

### Additional Information & Screenshots

![Screenshot (22)](https://user-images.githubusercontent.com/130830531/232204853-eb515809-1893-487c-a4fb-c27e426a3409.png)

**Comment by MetricDuck** [comment]
It doesn't clone you, it just auto scans you
