### ISSUE TITLE
Record sleeves don't spawn their contents

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#13705]
### Labels

[BUG]

### Description

See above, I assume this is related to the storage datums PR as it was testmerged at the time

### Steps to reproduce

1. Spawn a `/obj/item/storage/box/record/radio/host`
2. Observe that it is empty

### Expected Behavior

I expected records for the radio host to play

### Additional Information & Screenshots

#13023

**Comment by FlameArrow57** [comment]
Fixed by #13023 [d659fb6](https://github.com/goonstation/goonstation/pull/13023/commits/d659fb62a5410f5e15bf283a2804c2ba6347cbfc)
