### ISSUE TITLE
Holding a storage item in your off hand and clicking it with your other hand moves the storage instead of opening it

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#13721]
### Labels

[minor]

### Description

Previously clicking a storage in your off-hand would open it; now it just moves it to your other hand.

### Steps to reproduce

1. Hold box in hand
2. Click with other hand
3. Doesn't open!!

### Expected Behavior

title

### Additional Information & Screenshots

probably caused by https://github.com/goonstation/goonstation/pull/13023
Reported by Vanni on the discord, haven't verified myself

**Comment by FlameArrow57** [comment]
Yeah #13023, fixed by #13023 https://github.com/goonstation/goonstation/pull/13023/commits/5d2d20075714f4073d6ce9de6df8c9828694a38f
