### ISSUE TITLE
Ethereal Cats randomly meow without input from the player

### ISSUE THREAD

**Issue by LikeLakers2** [goonstation/goonstation#13720]
### Labels

[BUG] [MINOR]

### Description

Ethereal cats randomly meow without the appropriate input from the player, taking away player agency in how they might wish to play their ethereal cat

### Steps to reproduce

1. Get prompted to spawn as a random pest
2. Become Ethereal Cat
3. Notice that you sometimes meow without manually performing the \*scream or \*meow emotes.

### Expected Behavior

Ethereal cats wouldn't meow without input from the player

### Additional Information & Screenshots

Meow.

**Comment by CheffieGithub** [comment]
Fixed by 569fdf4.
