### ISSUE TITLE
Parallax starts off enabled the next round if you turn it off

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#13724]
### Labels

[BUG]

### Description

If you disable parallax and continue playing until the next round, it will appear on again

### Steps to reproduce

1. Turn parallax off
2. Round finishes
3. Continue into next round
4. See parallax on

### Expected Behavior

For parallax to stay off

### Additional Information & Screenshots

The checkbox that appears next to the parallax selection will show to be off when parallax is enabled the next round too.

#13667

**Comment by Mister-Moriarty** [comment]
Fixed by [ce36112](https://github.com/goonstation/goonstation/pull/13667/commits/ce36112c95ca658c5d3d35c191f33f6c0e2c45a6).
