### ISSUE TITLE
Nuclear operatives appear as role MODE in section Other in crew credits

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#13743]
### Labels

[BUG]

### Description

At the bottom of TGUI crew credits, nuke ops appear as role MODE

### Expected Behavior

For nuke ops to only appear in the Antagonists section

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/53062374/232938399-64438d33-a895-4288-89da-6c24e13ee955.png)

**Comment by Chatauscours** [comment]
Same for wizards, salvagers, etc.
Intended with the datumisation by the looks of it, up to a dev to decide

**Comment by Chatauscours** [comment]
https://github.com/goonstation/goonstation/commit/11a534fe54537d6756f439d66d693cb4f4ab8e81
