### ISSUE TITLE
Windoors use full door welded overlays

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#13753]
### Labels

[BUG]

### Description

`/obj/machinery/door/airlock/pyro/glass/windoor`s don't have their own welded overlays apparently, leading to this

### Steps to reproduce

1. Weld a windoor shut
2. Observe

### Expected Behavior

I expected the welding overlay to only be along one side of the door

### Additional Information & Screenshots
ugly!!!1
![image](https://user-images.githubusercontent.com/20713227/233248342-ef9d2d29-89df-498f-8078-900543cc3cff.png)

**Comment by Piesuu** [comment]
The windoor has a special welded overlay, that being `fdoor_weld` (displayed below)
![image](https://user-images.githubusercontent.com/109899867/233650699-bf3f8f88-4093-46f9-b3a8-6fd1e0aa88b0.png)
I've managed to replicate the bug and the door is using the proper overlay, just one image with the proper path. It is simply doubled, somehow?
