### ISSUE TITLE
You feel food_energized!

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#13758]
### Labels

[BUG] [TRIVIAL]

### Description

Instead of the actual "energized" or whatever, it shows its name in the code

### Steps to reproduce

1. Get something that makes you energized
2. Consume it
3. See the message mentioning food_energized instead of  "energetic" or whatever it should say

### Expected Behavior

I expected it to not use the code name, but a more normal one ingame

### Additional Information & Screenshots

![Perfectly normal](https://user-images.githubusercontent.com/62149527/233418263-3ab24857-7a89-40e6-94a8-a04f1f40bf6b.png)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/9bd1d0269ba45daca5e7b19067572e788d8ce72b
