### ISSUE TITLE
Recalling the shuttle as a borg

### ISSUE THREAD

**Issue by SolarWraith** [goonstation/goonstation#13769]
### Labels

[BUG]

### Description

It is possible to recall the shuttle from a COMMASTER computer as a borg, even though AI cannot do it by default.

### Steps to reproduce

1. Be a borg.
2. Login to a computer with COMMASTER installed.
3. Recall the shuttle if it's on it's way (cannot be recalled if it's 2 minutes before it arrives to the station).

### Expected Behavior

I expected the borgs to not be able to recall the shuttle as they are a silicon similar to AI.

### Additional Information & Screenshots

Not sure if this is an intended feature or an oversight as I was able to do this as a borg in one of the rounds.

**Comment by Piesuu** [comment]
https://github.com/goonstation/goonstation/blob/1cf7198fcdc46ac636562bfd4793def2461250c8/code/modules/networks/computer3/communication.dm#L123-L125 This directly prevents the AI but not Cyborgs from calling the shuttle. `isAI(usr)` should either be added onto with `issilicon(usr)` or this snippet should be commented out entirely.
