### ISSUE TITLE
Mimics are hard to observe as ghost

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#13788]
### Labels

[BUG]

### Description

In order to observe a mimic as ghost you have to search the "Observe" menu for what object they're disguised as

### Steps to reproduce

1. ghost
2. attempt to observe mimic
3. you dont know what they're disguised as so good luck

### Expected Behavior

See something obvious or easy to find in the observe menu to observe them

**Comment by pali6** [comment]
some time ago I changed it to use real name, fixed
