### ISSUE TITLE
Disaster round failed to create wraith

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#13795]
### Labels

[BUG]

### Description

Wraith does not spawn on disaster

### Steps to reproduce

1. Players trigger disaster via sol.
2. Round starts normally
3. No wraith shows up

### Expected Behavior

Wraith is supposed to spawn

### Additional Information & Screenshots

[3:3.6] Ellthorn (Ellthorn) [T] [DEAD] Late join: assigned antagonist role: wraith. 
[3:38] (blank) Didn't GC: [0x3000184] /mob/new_player -- name Ellthorn, iconstate , icon  

No runtimes or debug. Player says they readied up but were not let in and got stuck on title screen.
Wow we event have video!

https://cdn.discordapp.com/attachments/890223070999101480/1099237394135392266/wen_u_wana_play.webm

**Comment by nefarious6th** [comment]
Fixed by 6379213
