### ISSUE TITLE
Crawling Monstrosities from the harbinger wraith portal also attack their summoning wraith, including while they're intangible??

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#13806]
### Labels

[BUG]

### Description

Title.

### Steps to reproduce

1. Be harbinger wraith
2. Open portal with crawling monstrosities
3. Get killed

### Expected Behavior

They will damage and kill you if you're manifested. They don't seem to damage you if you aren't manifested. 
This is on another branch technically, but I'm 90% sure nothing I touched would change their AI behavior.

### Additional Information & Screenshots
Other summons don't seem to do this.
![image](https://user-images.githubusercontent.com/67879783/233810593-4db9fdbe-9b73-4175-82e5-eeb4a32e9865.png)

**Comment by CheffieGithub** [comment]
are they still objects?

**Comment by frawhst** [comment]
> are they still objects?

Yep, `/obj/critter/mechmonstrositycrawler`
