### ISSUE TITLE
Getting your hair cut from someone using the goon hud while using the tghud moves all sprites to the goonhud positions

### ISSUE THREAD

**Issue by Merlin1230** [goonstation/goonstation#13819]
### Labels

[BUG]

### Description

Basically, if you're using the TG hud and someone thats using the goonhud just uses the scissors to open up the barber menu, for some reason all of the sprites of everything move to where they would be on the goonhud, without actually changing the hud TO goonhud. Taking the items off and putting them back on moves them to their normal spots

### Steps to reproduce

1. Use the TGhud, be enjoying it
2. Ask your friend that uses the goonhud to cut your hair
3. Have your hud be ruined

### Expected Behavior

the sprites should stay in their slots

### Additional Information & Screenshots

this is SO jank
![image](https://user-images.githubusercontent.com/76177064/233868454-a46ba428-d5e8-44de-836f-cbf967dbb9a4.png)
also, I dont know if this happens when someone using a TG hud tries to cut your hair, just my best guess is that its something funky with the hud of who is cutting you maybe? I dont know, I havent looked at the code

**Comment by CaioFrancisco** [comment]
Not caused by who's cutting the hair. It's caused by the preview mob defaulting to the GoonUI, and the clothes mirroring probably breaks the position of the user's clothes on the GUI.
