### ISSUE TITLE
Rev rounds do not seem to end when the last revhead is brigged

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#13832]
### Labels

[BUG]

### Description

Rev rounds don't seem to end when the last revolutionary head is cuffed and brigged

### Steps to reproduce

1. Get last revhead
2. Cuff them
3. Buckle to bed in brig
4. Wait 10 - 30 seconds

### Expected Behavior

For the round to end

### Additional Information & Screenshots

Maybe it needs to be longer, but I remember it would maybe be 10 seconds before they're registered and the game ends. Doesn't seem to be the case any more

**Comment by pali6** [comment]
Hmm the checks in there seem correect and buckling to a bad does indeed set canmove to false

**Comment by FlameArrow57** [comment]
Was able to get it to end immediately by having two revheads buckle cuffed in the brig. Upon killing one of them the round immediately ended

**Comment by FlameArrow57** [comment]
Works now, as of #18773
