### ISSUE TITLE
Parallax shows space instead of black on underfloor effects

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#13835]
### Labels

[BUG]

### Description

Floor moving effects do not display a black underfloor correctly

### Steps to reproduce

1. Use an ability that moves a floor tile
2. Observe space is shown underneath instead of black void

### Expected Behavior

Black underfloor like before parallax

### Additional Information & Screenshots

Caused by #13667

Affected abilities:
- Admin floor cluwne gib
- Damn (super fart bible interaction and admin gib)
- Reveal (/datum/targetable/gimmick/reveal)
- Move floor (/datum/targetable/gimmick/movefloor)
- Power hammer special attack

**Comment by Mister-Moriarty** [comment]
Fixed by [`5503280`](https://github.com/goonstation/goonstation/pull/13667/commits/55032803d2882c4e8d4977a56f14e5382daf0a0b).
