### ISSUE TITLE
Gaps in the cog1 comms dish antenna

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#13917]
### Labels

[BUG][trivial][mapping]

### Description

There's slight but noticable gaps between the lattice and grilles because the grilles don't extend to the edges of the turfs

### Steps to reproduce

N/A

### Expected Behavior

Something that looks visually connected

### Additional Information & Screenshots

These gaps wouldn't have existed before perspective grilles

![image](https://user-images.githubusercontent.com/31984217/235378124-e9c64a7a-956f-44fb-b255-aeada958c7ec.png)

**Comment by flappybatpal** [comment]
Fixed by https://github.com/goonstation/goonstation/commit/21b3502d285c1b25ee1915dc816a436932794014
