### ISSUE TITLE
you can see the parallax thru translucent walls

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#13914]
### Labels

[BUG]

### Description

as above

### Steps to reproduce

1. alloy together a decently translucent metal "dont forget there does need to be metal in it"
2. create walls, 
3. alternativly use the transmute function in the one admin thing

### Expected Behavior

probably shouldnt? not sure if bug or not

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/63602513/235360858-7a4bc7e9-7f1e-4a64-8f94-5c81d805ecab.png)
you can see the star thru the floor here
![image](https://user-images.githubusercontent.com/63602513/235360879-f7d96aeb-480c-48b0-adae-a4b2d43a4eda.png)
here you can see an asteroid in the behind wall

**Comment by gunwithaman** [comment]
honestly looks pretty cool

**Comment by flappybatpal** [comment]
You should probably just see the generic steel underfloor plating that you see when using a crowbar to remove the floor tile.
