### ISSUE TITLE
Monkey clothes

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#1392]
[BUG]

**Describe the bug**
Monkey cannot wear safari clothes without it looking bizarre

**To Reproduce**
1. get a monkey
2. get a safari outfit
3. put safari outfit on monkey

**Expected behavior**
clothes fit to monkeys body.

**Screenshots**

**Additional context**

**Comment by Tarmunora** [comment]
Going to assume a lack of monkey sprite for safari uniform - not all jumpsuits have monkey resprites, as it's a thing that is done on a case-by-case basis

**Comment by Carbadox** [comment]
anyone have any thoughts about perhaps opening a project/adding monkey clothes sprites an existing project

**Comment by Studenterhue** [comment]
![image](https://user-images.githubusercontent.com/78634918/115504453-f8782a80-a245-11eb-8501-bd79f8138a9d.png)
Can confirm they still look off after the human resprite.

**Comment by DimWhat** [comment]
Currently tackling this issue.
