### ISSUE TITLE
Transposed scientist speech appears while dead

### ISSUE THREAD

**Issue by unfunnyperson** [goonstation/goonstation#13963]
### Labels

[BUG]

### Description

transposed scientists appear when viewing chat while dead

### Steps to reproduce

1. Die
2. Watch transposed scientists talk in chat despite the fact they are not in fact players

### Expected Behavior

Transposed scientists to stay quiet instead of filling chat

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/77701409/236085135-49425517-b97a-4f6b-83e7-307d9325c5a3.png)

**Comment by CheffieGithub** [comment]
while it could be annoying for some this is intended, anything said by a mob is put into chat. you can enable local only hearing to stop it. doesn't mean it can't be changed so that only mobs with minds show up to observers.

**Comment by frawhst** [comment]
Should probably just prevent clientless critter speech from appearing to ghosts, since this will just get messier as more things are modified (even though most critters don’t talk)
