### ISSUE TITLE
Phase shift is acting wonky.

### ISSUE THREAD

**Issue by phyvo1** [goonstation/goonstation#1397]
[BUG]

**Describe the bug**
I had a round as wiz on oshan. Whenever I used phase shift I would phase for awhile and the SNAP BACK to a previous location I passed through. Basically, the spell was locking my position before actually stopping my ability to move. This happened whether or not I had a staff while phasing.

**To Reproduce**
1. Play on oshan???
2. Be a wizard
3. Use phase shift.

In case it's hard to reproduce for some reason:
I picked fireball, shocking touch, blind, and rathan's

**Expected behavior**
Given what I remember of wizard in the past the proper change would be to, I think, move the lockin time to the end for phase shift and actually lock in movement. It's a little hard for me to say if that's also the case for staffless phase shift, I don't remember that one as much, so take this with a grain of salt. In any case playing wizard would be easier with proper feedback as to when phase shift locks in your position.

**Comment by zjdtmkhzt** [comment]
Pretty sure this has been the case with the genetics mutation as well for as long as I can remember.
It's about time we fix it, it's super annoying!
