### ISSUE TITLE
Security does not always receive death alerts

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#14009]
### Labels

[BUG]

### Description

Alerts for security death alerts are not always received

### Steps to reproduce

Not sure

### Expected Behavior

For death alerts to always be received

### Additional Information & Screenshots

Noticing that there will be security members that die, but a death alert was never received for them.

**Comment by TheColorCyan** [comment]
I noticed and it's probably because implants give CURRENT location of the body after delay, but as far as i know implants self destruct. If you do same with secass you still get the death alert of the current place of the body. Also no alert when body gets gibbed before the delay.

**Comment by FlameArrow57** [comment]
https://github.com/goonstation/goonstation/commit/d523647535451e32259d6cf5c6620fb2d99df166
