### ISSUE TITLE
Health analyzers show a player's preference name for the round for their organs

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#14037]
### Labels

[BUG]

### Description

Using a health analyzer will show a player's preference name for their organs

### Steps to reproduce

1. Wizard player chooses a name other than the name of the character they went into the round with
2. Scan them with health analyzer with organ scan upgrade when they have damaged organs

### Expected Behavior

For the player's actual name, or maybe appearance name instead, to be shown

**Comment by nefarious6th** [comment]
verified. also does this if you're running around without a face or voice a la acid or the agent card + voice changer.

**Comment by gear-space** [comment]
Had a PR recently that changed this for salvagers https://github.com/goonstation/goonstation/commit/97f203615c756a9698baa67b53df70bf5d673931 Unsure if doing this for Wizard/Clown/other jobs that get renames is how we want to handle that or not.

**Comment by AXLFAN2000** [comment]
Fixed by #18624
