### ISSUE TITLE
Engineering borgs unable to use deconstruction tool

### ISSUE THREAD

**Issue by Daktangle** [goonstation/goonstation#1406]
[BUG]

Borgs are not able to deconstruct structures built from mechanic box frames using the new interface, regardless of which slot they have the tools in.

1. Click on machine with deconstruction tool
2. Click on either the screwdriver or multitool popout
3. Nothing happens, deconstruction stage does not advance

**Expected behavior**
Using either the screwdriver or multitool popout while the relevant tool is selected in the omnitool should complete the deconstruction step.

**Additional context**
Tested with a handheld omnitool as a human, works correctly thus ruling that out as the issue.

**Comment by Tarmunora** [comment]
Could not reproduce

**Comment by Daktangle** [comment]
I'll have a look again, see if i missed a step.

**Comment by Daktangle** [comment]
Ah ha! You need to have the omnitool selected, not the deconstruction device like humans can. A little unintuitive, should I close the issue?
