### ISSUE TITLE
Deconstructing a structure once removes the need to use screwdriver and multitool if reconstructed

### ISSUE THREAD

**Issue by Daktangle** [goonstation/goonstation#1407]
[BUG]

**Describe the bug**
Once a structure has been made from a mechanic box frame and subsequently deconstructed, if reconstructed you do not need to use either a screwdriver or multitool to deconstruct it again.

Additionally the sprite gets bigger after being deconstructed the first.

**To Reproduce**
1. Use soldering iron on box frame
2. Follow deconstruction steps
3. Box frame sprite is now larger than it was originally
4. Use soldering iron on box frame
5. Go to deconstruct and it will automatically break down the structure without needing a screwdriver and multitool

**Expected behavior**
Deconstructing should always need a screwdriver and multitool

**Comment by Tarmunora** [comment]
Box frame being larger is not a bug
I *think* that not needing additional decon steps after being deconned/reconned once is also not a bug
