### ISSUE TITLE
borg APC cable text is messed up

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#14098]
### Labels

[BUG][trivial]

### Description

Using the APC cables results in text for onlookers that suggests they're being charged somehow.

### Steps to reproduce

1. Have a borg that's not you discharge an APC near you
2. See error

### Expected Behavior

Not weird text

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/31984217/f79ad822-ffd7-47f1-9759-fef826737036)
I was not Cyborg Omega-99

**Comment by nefarious6th** [comment]
Duplicate of #10346 ? Or related?
