### ISSUE TITLE
Can't cancel genetic powers' targeting reticle.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#1409]
**Describe the bug**
Can't cancel the targeting reticle for genetic abilities like telepathy or fire breath, the same way you can do on things like changeling's neurotoxic sting.

**To Reproduce**
1. Give yourself telepathy.
2. Click the ability, cursor turns into targeting reticle.
3. Try clicking the ability again, targeting reticle doesn't go away.

**Expected behavior**
Being able to cancel targeting.

**Comment by flappybatpal** [comment]
Fixed with #14bfef945afce91ef0aaba41f89c6911ab4cf6aa
