### ISSUE TITLE
AI And HoS Unable To Be Rolled On Disaster Gamemode

### ISSUE THREAD

**Issue by Mister-Moriarty** [goonstation/goonstation#14091]
### Labels

[BUG]

### Description

When attempting to join at roundstart on a Disaster round, the HoS and AI roles appear to be unable to be rolled.

### Steps to reproduce

1. Set the gamemode to Disaster.
2. Set your favourite job to AI or HoS.
3. Declare Ready.
4. Remark that you have spawned as a Staff Assistant, or job that is noticably not HoS or AI.

### Expected Behavior

To be spawned as an AI or HoS, depending on favourite job.

### Additional Information & Screenshots

This occured in a disaster round on Nadir on Goonstation 3: Morty.
I attempted to roll HoS, and spawned as a Staff Assistant, noticing on both the end of round credits, and start of round announcements that no HoS was selected. Another player expressed over LOOC that they had attempted to roll AI, and were spawned as a Staff Assistant, noticing that no AI was selected. Other roles may be affected.

**Comment by nefarious6th** [comment]
we did have an AI on this disaster round; someone else rolled it

**Comment by Chatauscours** [comment]
It is entirely possible to role those roles, I did it myself a few times. I do believe that disaster simply ignores preferences.

**Comment by Retrino** [comment]
they do spawn
