### ISSUE TITLE
Skeleton mobs have a lot of helmet slots

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#14204]
### Labels

[BUG] [MINOR]

### Description

When you spectate a skeleton mob, it has many more head slots than what you'd expect

### Steps to reproduce

1. Have skeletons spawn in the random room (unsure if they're the wizard or wraith ones)
2. Spectate one while being a ghost
3. Notice the sheer amount of hats they can wear

### Expected Behavior

I expected beings with just one head to be able to wear just one hat

### Additional Information & Screenshots

![Hydra moment](https://github.com/goonstation/goonstation/assets/62149527/a348200f-474d-489f-93ea-c614756c27b7)

**Comment by RSG250** [comment]
pretty sure this is intentional

**Comment by pali6** [comment]
actually yeah this should probably only be true for adminspawn skeletons
fixed here https://github.com/goonstation/goonstation/commit/8b004a94a6c8ecda2141224706fe6a9d940ea0bf
