### ISSUE TITLE
Antag critter can fly strelka pod

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1421]
[BUG]

**Describe the bug**
While observing someone as lil space spider, they were able to enter and control the Strelka pod. Not sure this is intentional behaviour?

**To Reproduce**
1. Become lil space spider through antag critter event.
2. Board the Strelka.
3. Pewpew people with lasers.

**Expected behavior**
I know they have many legs but for them not to fly it is expected.

**Comment by Tarmunora** [comment]
Any mob can pilot pods unless specifically exempt (ghostcritters I believe are)

**Comment by PrimeNumb** [comment]
This is not a bug - like yass mentioned it's something any mob can do. I double checked with mbc and it's working as intended.

Closing this.
