### ISSUE TITLE
sec buddies get stuck in a weird loop on cog 1 in cargo lobby

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#14232]
### Labels

[BUG]

### Description

ive noticed that secbuddies get stuck in a weird loop in cog1 cargo lobby

### Steps to reproduce

1. observe sec buddies near cargo on cog1
2. watch as they never leave the lobby when normally they should be patrolling the station

### Expected Behavior

normal patrol behaivor

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/63602513/a267a696-4744-4e77-b67d-f8e966bd7766)
even when the door is open they dont go thru it
![image](https://github.com/goonstation/goonstation/assets/63602513/2ea8062c-0d39-457e-a560-76c005dc1454)
even if they chase the crimer far, they will eventually normally patrol back here and get stuck again

**Comment by Chatauscours** [comment]
Yeah, saw it happen multiple times. Probably a mapping issue
