### ISSUE TITLE
herb did an oopsie and screwed up /obj/item/clothing/under/gimmick inheritance

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#14249]
### Labels

[BUG]

### Description

`/obj/item/clothing/under/gimmick` should not runtime upon instantiation with `CHECK_MORE_RUNTIMES` enabled.

### Steps to reproduce

1. Compile the game with z2 and with the `CHECK_MORE_RUNTIMES` define enabled.
2. A sailor uniform (with the type path `/obj/item/clothing/under/gimmick`) causes a runtime upon instantiation.

### Expected Behavior

For it to not runtime.

### Additional Information & Screenshots

This is my fault, I set `/obj/item/clothing/under/gimmick/yukata` as an abstract type not realising that it affected the parent types as well. Oups.

**Comment by pali6** [comment]
fixed by  d643747
