### ISSUE TITLE
Cog 1 Engine is hotwired after rework

### ISSUE THREAD

**Issue by Ormakent** [goonstation/goonstation#14378]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. Play Cog1?

### Expected Behavior

Engine not hotwired? (what are these fields sometimes)

### Additional Information & Screenshots

![hotwire bug](https://github.com/goonstation/goonstation/assets/35436986/c82320e8-877a-48d1-ad73-7fe5f0aecd6b)

The two wires in red square are not connected to anything and they have same output as engine. I assume the cold loop monitor in blue square somehow connects all the wires (brown going through top and bottom and 2 red ones on left/right) and thus the hotwire is born.

**Comment by pali6** [comment]
fixed by https://github.com/goonstation/goonstation/commit/22ae567793e4eb41203c53d8e15e7f12cedb3035
fucking bullshit statmeters crap
