### ISSUE TITLE
Fishing Supplies Vendor interface issues

### ISSUE THREAD

**Issue by Varshie** [goonstation/goonstation#14429]
### Labels

[BUG]

### Description

Upon inserting enough research tickets the 'redeem' button vanishes entirely. You can still click it to redeem items despite this.

### Steps to reproduce

1. Earn research tickets through the upload terminal
2. Insert them into the fishing supplies vendor
3. the UI seems to break

### Expected Behavior

The button you are clicking should be visible.

### Additional Information & Screenshots

![1XYR1Z5rV3](https://github.com/goonstation/goonstation/assets/71558290/b464c375-eae5-4fb4-8438-3e926d836e6b)

**Comment by Gannets** [comment]
I think this might be a tgui thing which is why I haven't had much luck with it.
