### ISSUE TITLE
Angler job spawns with two PDAs

### ISSUE THREAD

**Issue by Varshie** [goonstation/goonstation#14428]
### Labels

[BUG]

### Description

The Angler spawns with two PDAs (a civilian one and a botany one) and no cash and/or trinkets

### Steps to reproduce

1. Late join as an Angler

### Expected Behavior

The Angler should probably only spawn in with one, and should have a trinket or cash in line with other jobs.

**Comment by Gannets** [comment]
Fixed by #14423
