### ISSUE TITLE
Odd Sprite Issue With New Aquatic Research Terminal

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#14441]
### Labels

[BUG]

### Description

People will appear above the aquatic research terminal, even if it doesn't make sense

### Steps to reproduce

1. Get an aquatic research terminal
2. Go a tile above it
3. Notice you are somehow on top of it

### Expected Behavior

To not appear on top of it

### Additional Information & Screenshots

![Goonstation 1 Classic_ Heisenbee_ Development Lab Lambda 6_6_2023 8_24_36 PM](https://github.com/goonstation/goonstation/assets/87689371/604c3e9b-a4a4-4984-ba2a-7cae2c31a22d)

**Comment by Gannets** [comment]
There's some layer stuff I was doing to get the tickets to appear above the terminal, that's probably causing this.
