### ISSUE TITLE
Thermoelectric Generator Inlet Pressure on Cold Loop Drops to 0KPa on the Generator Display

### ISSUE THREAD

**Issue by wmann95** [goonstation/goonstation#1445]
[BUG]

**Describe the bug**
The thermoelectric generator on cogmap 1 starts up just fine, good pressure and heat on hot side with the furnaces, good pressure and cold temp on cold side. It starts running, keeps running for some amount of time, then all of a sudden the generator display shows that the Cold Loop Inlet Pressure drops to 0 KPa with no intermidiate, just instantaneous drop. This would normally indicate that there must not be pressure on the inlet of the generator, cold loop side, however the pressure meter directly before it (the one I can read from my character) shows a value significantly higher than 0 KPa, usually around 4-700 KPa. Note that this whole process is done with plasma. I've, at this point, put more than 4 tanks of plasma into the cold loop with no indication of a burst pipe or leak out to space. If it were a burst pipe, I'd see the plasma, as has happened before. It shouldn't be leaking out to space because both sides of the pressure release and purge pipes are sealed shut and usually go untouched from game start.

**To Reproduce**
1. Start up thermoelectric generator as normal.
2. Watch as it rev up, filling the cold loop side with additional plasma if need be.
3. Watch as the cold speeds up and speeds up, eventually just goes to 0 KPa.
4. Get confused as to why this is happening.

**Expected behavior**
I would expect that, if the meters are reading values greater than 0, so too should the generator.

**Screenshots**

![Screenshot (27)](https://user-images.githubusercontent.com/57637101/87232791-c3be7500-c38f-11ea-8c3b-dba9e762f5ef.png)
![Screenshot (28)](https://user-images.githubusercontent.com/57637101/87232784-b0aba500-c38f-11ea-96ad-6d564728993c.png)

**Video**

I took a video of my attempt at getting the engine running with the issue, or at least perceived issue, in it. If need be, I can comment relevant time codes.

https://www.youtube.com/watch?v=3dTDFUVQlAk

**Comment by trerri** [comment]
ime this is one of those horrible "known issue; could not reproduce." seems like we're gonna have to wait until "atmos is fixed" but it seems like it's gonna take a while and the removal of hellburns

**Comment by wmann95** [comment]
I mean if it were a one time thing I'd completely understand... unfortunately it's happened on every round I've played, and has been seen with other people who are more experienced. It's just sort of game breaking.

**Comment by Tarmunora** [comment]
Duplicate of #432

**Comment by wmann95** [comment]
Thank you for pointing that out, Tarmunora. I thought I had included 0kpa in my search terms before posting this issue. Sorry about the duplicate.

**Comment by MarkNais** [comment]
The means may be different, but the bug is the same.

**Comment by wmann95** [comment]
Then let's hope that this leads to further looking into it not necessarily being linked to hell burning, as I've done none of that, not even really connected at all. I do have a video that show's my process, if that helps show any differences.

**Comment by moonlol** [comment]
Ive had this bug a lot but it never affected my power output
