### ISSUE TITLE
plaguebringer wraith can spam the final curse

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#14460]
### Labels

[BUG]

### Description

when you have someone with all 4 curses and you use the final curse on them it doesn't go on CD and can throw you into negative points (???)

### Steps to reproduce

1. be wraith
2. plaguebringer
3. curse someone with all the curses
4. curse them with the one that kills them
5. you can keep cursing them even though you already did it
6. when it ends go into wraith points debt

### Expected Behavior

it goes on cooldown

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/93528889/4c418048-3237-44fd-8565-0e3dcfac6eb0)

**Comment by deathrobotpunch** [comment]
L
