### ISSUE TITLE
You guys should look at this seems very urgent

### ISSUE THREAD

**Issue by deathrobotpunch** [goonstation/goonstation#14469]
### Labels

[BUG]

### Description

So I was looking at the bug forum when I saw this, it seems very urgent and needs to be explained https://github.com/goonstation/goonstation/issues/14388#issue-1740966063 link to the bug report

### Steps to reproduce

1. 

### Expected Behavior

Not whatever that was

**Comment by flappybatpal** [comment]
This is a standard TermOS error screen. These interfaces use browser functionality to display complicated user interfaces and if it crashes you get a detailed error message.
