### ISSUE TITLE
Angler starts with two PDA

### ISSUE THREAD

**Issue by Glamurio** [goonstation/goonstation#14472]
### Labels

[BUG] [Trivial]

### Description

When latejoining as Angler, you start with a PDA in your belt and one in your pocket

### Steps to reproduce

1. Latejoin as Angler.
2. Check your belt and pocket slots.

### Expected Behavior

Probably should only have one PDA

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/51779813/71c840b5-3132-4924-807d-04a9ab761ca6)

**Comment by deathrobotpunch** [comment]
He needs one for fishing and the other for home use obv

**Comment by TobleroneSwordfish** [comment]
Might have been fixed? Can't reproduce on local

**Comment by Gannets** [comment]
I got this one 👍
