### ISSUE TITLE
Medical Training (possibly) bugged

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1452]
[BUG]

**Describe the bug**
From my understanding, the Medical Training trait is supposed to do three things.  Reduce the chance of fumbling during surgery, reduce the damage dealt by fumbling during surgery, and reducing the damage dealt by successful surgery.  It seems to be doing the second one, and possibly the third, but it doesn't appear to be doing the first.  In my experience it almost seems to be increasing the fumble rate, but I haven't actually recorded the results of my surgery attempts with and without the Medical Training trait so I can't be sure.

**To Reproduce**
1. Perform surgery a very large number of times in a controlled setting with the Medical Training trait, recording how many fumbles happen, as well as the damage resulting from every surgery step.
2. Perform identical surgery a very large number of times in a controlled setting without the Medical Training trait, recording how many fumbles happen, as well as the damage resulting from every surgery step.
3. Compare the results for steps 1 and 2.

OR

1. Just look at the relevant portions of the code to see if anything looks like it could be causing a problem.

I recommend the second, personally.

**Expected behavior**
I expect people with Medical Training to fumble during surgery less.  I might be wrong about that being the intended behavior, however, but I definitely don't expect them to fumble more.

[BUG]

**Comment by moonlol** [comment]
Medical training trait only seems to give you better chances for certain surgeries (headspider and bee removal). otherwise it just allows you to have no screwup chance. Without the trait there is always a chance of screwup but with Medical Training you _can_ have no screw up. Medical training does make you deal less damage sometimes (depends on the damage. medical training allows 0 damage where without there will be always atleast 2).

**Comment by Gerhazo** [comment]
Has been explained as I was writing this but difference between medical training is:

If you don't have medical training, you always have at minimum a slight chance to mess up despite any preparations.
If you have medical training, if you have the perfect circumstances and preparations (anesthetic, painkiller drugs, etc) you can have no chance of messing up at all.

**Comment by flappybatpal** [comment]
Appears to be no bug here.
