### ISSUE TITLE
Weird Bug With Click Dragging Items From Hands

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#14552]
### Labels

[BUG]

### Description

Click dragging an item from you off hand to you back pack treats it as if you are still holding that item in your hand.

### Steps to reproduce

1. Put something in your hand
2. Switch to the other hand that doesn't have said item
3. Click drag that item to an empty backpack slot
4. Swap to now empty hand
5. Press q
6. Notice the item teleport out of your backpack onto the ground

### Expected Behavior

I expect the item to not have quantum properties in my backpack/hand

### Additional Information & Screenshots

https://github.com/goonstation/goonstation/assets/87689371/37232c00-0fe0-4c77-9dd4-5a5c78f676f2

**Comment by TealSeer** [comment]
Can't reproduce
