### ISSUE TITLE
Dispensary interlink appears to be totally non functional

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#14569]
### Labels

[BUG]

### Description

Dispensary interlink does not show any items in it's menus

### Steps to reproduce

1. Add a pill or syringe to dispensary supply chute
2. Interact with it 
3. See no entries on the menu
4. Head to a dispensary interlink
5. Interact with it 
3. See no entries on the menu

### Expected Behavior

Menus to be populated

**Comment by TobleroneSwordfish** [comment]
Couldn't reproduce, probably a broken pipe
