### ISSUE TITLE
Deconstruction Devices do not fit in Aurora MKII utility belt

### ISSUE THREAD

**Issue by SimianC** [goonstation/goonstation#1460]
[BUG]

Chief Engineers spawn with a deconstruction devices spawn on their Aurora MKII utility belt, but they can not be stored on the belt after being removed; Engineer utility belts do not have this issue as it was fixed a few days ago. 

1. Spawn as Chief Engineer 
2. Remove the deconstruction device from the belt.
3. Attempt to store deconstruction device on belt.

**Expected behavior**
The Aurora MKII utility belt should store deconstruction device with no issues.

**Comment by UrsulaMejor** [comment]
Should be fixed as of 40 minutes ago; is it still happening?

**Comment by UrsulaMejor** [comment]
just doublechecked, it's fixed
