### ISSUE TITLE
No means to make soup on Donut 2

### ISSUE THREAD

**Issue by medsal15** [goonstation/goonstation#147]
**Describe the bug**
Donut 2 is missing the required facilities for making soup

**To Reproduce**
1. Go in Donut 2's kitchen
2. Notice lack of stove, soup pot, etc.

**Expected behavior**
There should be one on Donut 2 too.

**Comment by pali6** [comment]
Donut 2 isn't really a supported map and the only way to actually get there is more of an easter egg.

**Comment by F-OS** [comment]
I wouldn't mind taking the time to fix this up, Dount's always been a cool map. will make a PR later today.
