### ISSUE TITLE
Teleport components glow overlays are affected by electroplating

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#14705]
### Labels

[BUG]

### Description

^

### Steps to reproduce

1. Electroplate a teleport component to something dark
2. Anchor and activate it
3. Observe the overlay being much harder to see

### Expected Behavior

I expected literal beams of light to not end up made out of mauxite

**Comment by zjdtmkhzt** [comment]
should also be checked if one can manage to get paint to affect it or something. maybe also colorful reagent?
