### ISSUE TITLE
Donut 3 misnamed btton

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#1470]
[BUG]

**Describe the bug**
The southern button in toxin that controls the exhuast vent is labeled as "Pad Public-Access Lockdown" when it should be labeled for the exhaust vent 

**To Reproduce**
1. Look at button

**Expected behavior**
Named for vent exhaust
**Screenshots**

**Additional context**

**Comment by Tenryumi** [comment]
fuck
