### ISSUE TITLE
Lighters explode now

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#1474]
[BUG]

**Describe the bug**

If you leave a lit lighter on the ground, after a while it will explode into a huge fireball and melt a hole in the floor. Might be heating itself up and/or containing more fuel than it should.

**To Reproduce**
1. Light lighter
2. Drop on floor
3. Wait
4. It explodes!

**Expected behavior**

An explosion, but not one that goes through the floor like that!

**Additional context**

Works great against blobs!

**Comment by Xkeeper0** [comment]
Fixed by #1658 according to @BatElite
