### ISSUE TITLE
Lethal frostburn after consuming minimed pills

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#14778]
### Labels

[BUG]

### Description

Got stunlocked to death by frostburn effects after eating a minimed pill

### Steps to reproduce

After buying and swallowing pills from a minimed, I had a spam of frostburn effects stunning and damaging me to death
Later on in the round I bought an epinephrine pill from the same vendor and it was fine.
Earlier in the round I took a few tips of this nonsense I made, I've also explored nadir's trench but I had a suit on, I don't think my body temp was cold

### Expected Behavior

To not get quasi stunlocked to death after eating an epinephrine minimed pill

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/6396368/62c814bf-ed20-4e71-a6c1-7ea3ff8aa403)
![image](https://github.com/goonstation/goonstation/assets/6396368/40cb92b8-cce6-4fe0-9cf8-8c06664c7faf)
The minimed:
![image](https://github.com/goonstation/goonstation/assets/6396368/56d4ac1e-0d3a-49e9-a615-fb6f25536490)
The nonsense:
![image](https://github.com/goonstation/goonstation/assets/6396368/bbd9ffde-1a4f-4815-a3fa-06b9bbf771c4)
![image](https://github.com/goonstation/goonstation/assets/6396368/5b33f3f2-edfb-4c87-a7f0-15a1da14b47e)

**Comment by zjdtmkhzt** [comment]
Were you a saurian? Did you possibly get thermal vulnerability from the uranium or other radioactivity without noticing?

**Comment by zjdtmkhzt** [comment]
I tried it and I don't think you even need to be a dinosaur, so I assume you just had thermal vulnerability from your dan soup.
So I think this is working as intended, whether or not a small burn patch should do 170 burn damage on a person with thermal vulnerability is another matter...

**Comment by Garash2k** [comment]
Ohhhhhh thermal vulnerability from radium/unstable mutagen sounds like very likely to be what was going on, thanks for the insight!
