### ISSUE TITLE
Tiki Burger cannot be cooked

### ISSUE THREAD

**Issue by jan-antilles** [goonstation/goonstation#1478]
[BUG]

**Describe the bug**
When the ingredients for the Tiki Burger are assembled and placed in the oven for the correct time, the output is Smoldering Mess.

**To Reproduce**
1. Place Dough, Monkey Meat, Coconut Meat, and Pineapple Slice in the oven.
2. Set the oven timer to 9 seconds on High.
3. The output is Smoldering Mess.

**Expected behavior**
The output should be Tiki Burger.

**Screenshots**
Available upon request.

**Additional context**
Based on talking with Rookie, it appears that this issue may be due to the order of the list of recipes that the oven checks for when cooking the food. It is possible that the oven sees the ingredients for Monkeyburger before checking for Tiki Burger, and since the time is set to 9 sec on High, it turns the Monkeyburger into a Smoldering Mess.

**Comment by ZeWaka** [comment]
fixed by 3637bce
