### ISSUE TITLE
Glowstick trees lose their glow

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#14787]
### Labels

[BUG]

### Description

When transferring a glowstick tree to a plant pot, they lose their glow - the tray keeps glowing while the pot doesn't

### Steps to reproduce

1. Plant a glowstick tree in a hydroponics tray
2. When the tree is fully mature and ready to harvest, it emits a soft rainbow glow
3. Use a trowel to pick up the tree, do not harvest it
4. Place the tree in a plant pot using the trowel
5. The tree is in the plant pot, but it does not glow; the now empty hydroponics tray glows instead
6. Sulk

### Expected Behavior

I expected the hydroponics tray to not glow, and for the pot to glow, as that is where the tree was now located

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/100481985/bcf902cc-9f74-4f7b-9010-5c21cffc7a8d)
A picture of the issue

Round ended sometime around 5:20 PM EST 6/30/2023 MM/DD/YYYY on Goon3 RP: Morty

**Comment by TobleroneSwordfish** [comment]
631e015
