### ISSUE TITLE
Unable to access upgrade click dragged into the borg charger

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1481]
[BUG]

**Describe the bug**
On dragging an upgrade into the charger, borg attempt to "pick up" said item. On entering the charger you cannot install or eject the upgrade.

**To Reproduce**
1. Be borg
2. Drag doc goggles upgrade into the charger
3. Enter charger and try to install upgrade

**Expected behavior**
To not have the upgrade become inaccessible

**Additional context**
Liking linked to borg trying to pick them up?

**Comment by Tiggersaurus** [comment]
I've noticed that every click drag for borg they try to pick things up, like dragging botany plants into satchel. It's strange.

**Comment by mordent-goonstation** [comment]
Oof, I wonder what's changed in the past few days?

**Comment by Tiggersaurus** [comment]
Modules bug too when dragged into the charger.

**Comment by Tiggersaurus** [comment]
Possibly this? "Click+drag can be used to hit one item with another item now. This is mostly a QoL / learning thing"

**Comment by mordent-goonstation** [comment]
> Possibly this? "Click+drag can be used to hit one item with another item now. This is mostly a QoL / learning thing"

Almost certainly. Link it!

**Comment by Tiggersaurus** [comment]
https://github.com/goonstation/goonstation/pull/1270#issue-442160130

Seems to be part of that according to the change log, well it has no number according to the change logs but mbc did both. All forms of click drag to move things across tiles is broken for borg. Might it explain the steel tile bug also? Guess we'll find out.

**Comment by Tiggersaurus** [comment]
Mark linked this https://github.com/goonstation/goonstation/commit/b99b3d5a23bf5214f7fed0e8b303790285c05827 think it's the same bug root.

**Comment by Tiggersaurus** [comment]
The tile dragging is fixed with mark's update but the upgrades aren't.

**Comment by makkipakki** [comment]
Also an issue with hats, not just upgrades! Anything that is inserted into the cyborg docking stations is broken if click-drag is used.

**Comment by Tiggersaurus** [comment]
Even with the make-your-own-borg fix, click drag on tiles/charger is still bugged for borg.

**Comment by Tiggersaurus** [comment]
This is now fixed HOWEVER borg can no longer click drag anything across tiles yeeeeeeeeee

**Comment by Tiggersaurus** [comment]
Bump. Borg still can't click drag across any tiles anymore *sadborg*

**Comment by Tiggersaurus** [comment]
This is also affecting click drag for ore piles as miner borg. Pls fix.

**Comment by Studenterhue** [comment]
Looks like this has been patched, for you can insert modules, upgrades, and hats into a charger and install them as a borg correctly now. Click-dragging ore together as borg works now too. Dunno what fixed it exactly, but #5587 is my wager.
