### ISSUE TITLE
There's No PCs/Printers On Donut 2

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#14842]
### Labels

[BUG]

### Description

There's no PCs/printers on donut 2, making doing things involving them impossible

### Steps to reproduce

1. Go to Donut 2
2. Try to find a PC/printer
3. Fail

### Expected Behavior

For there to be a few PCs/printers

**Comment by TealSeer** [comment]
intended, there are a few ThinkDOS computers on station and the lack of printers is because the DWAINE network exists solely on the zeta research outpost
