### ISSUE TITLE
Mobster suit on monkeys using human sprite

### ISSUE THREAD

**Issue by Glamurio** [goonstation/goonstation#14877]
### Labels

[BUG] [Minor]

### Description

The mobster suit is missing a sprite on monkeys

### Steps to reproduce

1. Be monke
2. Wear mobster suit
3. Become walking suit

### Expected Behavior

Have a sprite

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/51779813/b3ffad93-31d5-40f0-9103-04a898df9168)

**Comment by CheffieGithub** [comment]
fixed by #14932
