### ISSUE TITLE
Cannot pick up twisted shrapnel

### ISSUE THREAD

**Issue by MemeTroubadour** [goonstation/goonstation#1492]
[BUG]

Hello. While playing Janitor, I came across some twisted shrapnel in maintenance hallways and was not able to pick it up.
I was able to pull the shrapnel and remove it using a wet sponge, but not pick it up. 

To reproduce :
1. Find twisted shrapnel
2. Attempt to pick it up (left click with empty hand/right click > pick up)
3. Nothing will happen and the shrapnel will stay on the ground

I was told by a mentor that I'm supposed to be able to pick up the shrapnel and even recycle it for metal. After I told them I couldn't, they told me to make a report.

I did manage to clean it off using a sponge. I think it pretty much had the same behaviour as a critter corpse.

Hoping I'm either dumb or this can get fixed. Thank you for your work.

**Comment by zjdtmkhzt** [comment]
I think the kind of twisted shrapnel this is about is the kind that is mostly left for decorations when mechanical things break, which is pretty much gibs but for machines?
So I don't think it's supposed to be pickup-able, the mentor was probably referring to things like scraps that sometimes arrive with the mineral magnet.
