### ISSUE TITLE
Botany Mass Producing Toxin

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#1494]
**Describe the bug**
A certain line of splicing leads to Botany mass producing toxin.

**To Reproduce**
1. Splice Lemon, Lime, Oranges together. 
2. Splice that seed into Carrots.
3. Splice garlic and onions togtheher.
4. splice the seed from step 1 and 2.
5. Splice that seed into Clear Corn.

**Expected behavior**
Should result in extracting into Triple Citrus, Holy Water, and Ethanol.

Instead, extracts into Triple Citrus, Holy Water, Ethanol, and 2u Toxin.

**Comment by Tarmunora** [comment]
Not a bug - one of the gene strains available for onions to mutate is toxin production, which adds toxin to the product
