### ISSUE TITLE
Smelling salts do not clear haloperidol

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#14976]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Someone with haloperidol from guardbuddy syringes
2. Use smelling salt ampoule on them

### Expected Behavior

For the haloperidol to be cleared

**Comment by Chatauscours** [comment]
I don't think that haloperiol is supposed to be cleared by the salts, not according to the wiki https://wiki.ss13.co/Chemicals#Ammonium_Bicarbonate . 
(Plus likely balance reasons since haloperidol is a counter to stims)

**Comment by TealSeer** [comment]
As stated, code does not clear haloperidol, intended
