### ISSUE TITLE
bedsheets and welding masks don't blind/darken the screen as intended

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#1498]
[BUG]

**Describe the bug**
Wearing bedsheets and welding masks doesn't change your view as it normally should

**To Reproduce**
1. Put on a welding mask
2. See that it doesnt darken your vision
3. Put on bedsheet
4. See that it doesnt blind you

**Expected behavior**
These items should affecting your seeing

This might also affect blindfolds though I havent tested that.

**Comment by zjdtmkhzt** [comment]
I believe this is a duplicate of #1322 , good to know that it also affects welding masks though!
