### ISSUE TITLE
Cyborg can build their own shells with new clickdrag change.

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1505]
[BUG]

**Describe the bug**
So as borg I managed to build a borg and insert my own module into the rewriter something that normally needs a human. I very much assume this is a bug because lol we don't need no humans currently :P 

**To Reproduce**
1. Be borg
2. Click drag arm or leg or chest onto robot frame
3. Build your own borg and overtake humanity

**Expected behavior**
To require humans to build things like this as previously (heck I'd be happy with a change like this but don't think it's intentional)

**Comment by MarkNais** [comment]
I suspect something to do with MBC's QOL commit, as my recent-ish `anchor` PR would only make things "worse" for click-drag, not more-permissive.
#1405

**Comment by Tiggersaurus** [comment]
Ye I figured it was likely that, also affects click drag on tiles and charger for Borg. This addition to the bug was just amusing.

**Comment by mordent-goonstation** [comment]
Yeah, this is definitely unintentional. I haven't got time to fix right now, so pinging @mybluecorners to see what needs doing to prevent the cyborg uprising.

FWIW, I'm fine with cyborgs adding parts to frames, just not the brain -> head part of that (or the brain -> open and empty finished cyborg head, which I don't know if also works as it's a mob).

**Comment by Tiggersaurus** [comment]
I totally agree with the adding parts but not head. Otherwise rogue borg would be able to panc -> debrain -> new borg friend!

**Comment by mybluecorners** [comment]
fixed yesterday, didnt notice this report 
https://github.com/goonstation/goonstation/commit/81f9f634fddf53243acf458a7c435184eca4d16f
