### ISSUE TITLE
Atropine does not clear saxitoxin

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#15088]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Have saxitoxin in you
2. Take atropine

### Expected Behavior

For atropine to clear the saxitoxin

### Additional Information & Screenshots

Used to find this out, in bloodstream
Saxitoxin - 5.227u -> 4.687u
Atropine - 9.77u -> 8.69u

**Comment by FlameArrow57** [comment]
I think I was in that case, but I could be wrong. It's not clear at all reading the wiki though

**Comment by TealSeer** [comment]
Could not reproduce, behavior worked as Earthfire described
