### ISSUE TITLE
confused selflight mask on ghosts at centcom shuttle

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#151]
**Describe the bug**
Ghost creates a halo of darkness.

**To Reproduce**
1. Get eaten by ling
2. Kill ling
3. Respawn as ghost
4. Teleport to shuttle

**Expected behavior**
Ghosts shouldn't have simplelights
**Screenshots**
![image](https://user-images.githubusercontent.com/63235460/78698195-40116a00-7902-11ea-9cc4-cd3693d33c3d.png)

**Comment by pali6** [comment]
Those aren't simplelights per se and I suspect that this is the good old byond sprite bug because it's the first time I see this.

**Comment by mybluecorners** [comment]
this doesn't look like sprite bug, bc the sprites are showing their proper images. It looks like lighting in general is confused here, like the shuttle should be pitch black but instead its fullbright, and the only place that is showing light layer is the aura around the player ghost

**Comment by pali6** [comment]
Probably fixed kinda.
