### ISSUE TITLE
Attempt to mutate immutable material runtime with erebite in an RTG

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#15133]
### Labels

[BUG]

### Description

see screenshot

### Steps to reproduce

1. Presumably spawn a `/obj/machinery/power/rtg/erebite_loaded`
2. 713 runtimes

### Expected Behavior

I expected less immutable mutation!

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/20713227/ec94d1c9-6c73-4730-ab5f-8ad7b90bc336)

**Comment by amylizzle** [comment]
Fixed by #15191
