### ISSUE TITLE
Sealed away forever in the cool labcoat

### ISSUE THREAD

**Issue by MintyPhresh** [goonstation/goonstation#15168]
### Labels

[BUG] [Trivial] [Clothing] [sprites]

### Description

Cool Medical Labcoat appears not to become unbuttoned on the UI

### Steps to reproduce

1. unbutton the labcoat
2. observe the inventory panel it rests on as the colors on the arms of the labcoat shift, but the labcoat seems to stay closed

### Expected Behavior

the unbuttoned labcoat will appear unbuttoned

**Comment by Retrino** [comment]
the sprite may convey the lighter color between the two sides as being the inner lining of the coat, but im honestly not sure. its definitely closer together than most unzipped coats

**Comment by Retrino** [comment]
hi me from the past. yeah this isnt a bug there are two different sprites that show up for the buttoned and unbuttoned states
