### ISSUE TITLE
Hypospray deleting chems

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#1516]
[BUG]

**Describe the bug**
The hypospray seems to just delete strange reagent when you put them in.

**To Reproduce**
1. Have hypospray
2. Have strange reagent
3. Add the reagent to the hypospray
4. Be sad

**Expected behavior**
To NOT have it deleted

**Screenshots**

**Additional context**

**Comment by zjdtmkhzt** [comment]
Hyposprays delete anything that is not on a whitelist of non-harmful medical chems (unless they are emagged).
Seeing as Strange Reagent causes damage when injected into living humans, it is not on the list.

**Comment by Tarmunora** [comment]
Not a bug
