### ISSUE TITLE
Everything appears as antag in the upgraded observer menu

### ISSUE THREAD

**Issue by soapcyst** [goonstation/goonstation#15186]
### Labels

[BUG]

### Description

The antag section of the upgraded observer menu has every observable entity. the other sections are normal. also every entity has [0]

### Steps to reproduce

1. join game as observer
2. open observer menu
3. see "turn on dnr to see antags" and see the antag list as having everything.
4. turn on dnr
5. Still see everyone in the antag list.

### Expected Behavior

I expected to see just the DNR message with it off and the antags with it on

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/58966116/48f6d29f-16d9-4fae-957f-a039d9c78591)

**Comment by soapcyst** [comment]
On the next round the issue did not repeat. the round this happened was https://goonhub.com/rounds/160611

**Comment by amylizzle** [comment]
Oh that's weird.

**Comment by amylizzle** [comment]
I think this might have happened because the test-merge was updated mid-round. I guess TGUI resources were updated and pushed to the client for the DM side changes.
