### ISSUE TITLE
Dropping items with Q as borg makes them invisibile

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#1518]
[BUG]

**Describe the bug**
Title

**To Reproduce**
1. Be Cyborg
2. Equip an item into a slot
3. press Q

**Expected behavior**
Nothing to happen

**Comment by Xkeeper0** [comment]
This isn't a bug. For cyborgs, `Q` unequips an item.

**Comment by Adharainspace** [comment]
im pretty sure q just slots the item back into your module, right?

**Comment by UrsulaMejor** [comment]
only instead of putting it back in your module it just makes it invisible and keeps it in your slot without unequipping it (at the time I made this report)
