### ISSUE TITLE
AI can be converted to being a revolutionary by a rev beating to crit one of their shells.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#1520]
**Describe the bug**
~~According to a report, an AI shell being revflashed causes them to convert to being a revolutionary.~~ Being beaten to "critical" by a revolutionary causes AI shells and by extension AI to be converted to a revolutionary. They can see other revolutionaries and all other things involving being a revolutionary.

**To Reproduce**
~~1. Deploy to AI shell (eyebot drone with tools).
2. Shell is flashed by a headrev with the revflash.
3. The AI is now considered a revolutionary.~~
1. Deploy to AI shell (eyebot drone with tools).
2. Shell is beaten below 0 health by a head rev (14 attacks with a law upload board works well)
3. The AI shells are now considered revolutionary.

**Expected behavior**
The AI not being brainwashed.

**Comment by glassofmilk** [comment]
Make it a feature!

**Comment by Gerhazo** [comment]
The rev flash conversion seems to have an ishuman check, which makes this kind of unlikely and even weirder.
Just in case the revflash is a red herring, there's also the code that handles converting someone if you beat them into crit, possible cause?
https://github.com/goonstation/goonstation/blob/c574c8bc4def262ae193df378b6b661e1d03ab49/code/mob/melee_attack_procs.dm#L1033
converting on attack doesn't seem to have checks, but I'm not sure if a shell can get to <0 health without just exploding
unless they got attacked again before the explosion finished or something

**Comment by j-awn** [comment]
![image](https://user-images.githubusercontent.com/69046355/89809378-773e9480-db09-11ea-8a0b-e1b7e6f72cbc.png)

I think your hunch is right- I beat the AI shell into crit, and it became a rev.

**Comment by j-awn** [comment]
Updated reproduction steps:

**To Reproduce**
Steps to reproduce the behavior:

1. Deploy to AI shell (eyebot drone with tools).
2. Shell is beaten below 0 health by a head rev (14 attacks with a law upload board works well)
3. The AI shells are now considered revolutionary.
