### ISSUE TITLE
Reloading a M1992 Pistol by clicking the gun on the ammo doesn't update ammo tooltip

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#1524]
[BUG]

**Describe the bug**
Reloading a M1992 Pistol by clicking the gun on the ammo doesn't update ammo tooltip, causing the ammo to continue to say in the tooltip that it has "15 bullets left", even though it's actuallly empty

**To Reproduce**
1. Hold an M1992 pistol in hand and empty it into the nearest staff assistant
2. Click on a pistol mag to reload the gun
3. Hover over the pistol ammo to view the tooltip

**Expected behavior**
For the ammo to say "0 bullets left"

**Screenshots**

**Additional context**
Might happen with other guns, too, but this is the gun I discovered the bug with.

**Comment by Boxlta** [comment]
This also works with zip guns and .22 ammo with basically the same setup

**Comment by Studenterhue** [comment]
Looks like #5519 has fixed this bug, for the most part.
