### ISSUE TITLE
Borg can be emagged by Vampire screech maybe?

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1527]
[BUG]

**Describe the bug**
After the vampire did Chiroptean (sp?) screech all the borg in the area became emagged. This is the second this has personally happened to me.

**To Reproduce**
1. Be borg
2. Be in the vampire screech radius
3. Get emagged

**Expected behavior**
To not be emagged?

**Comment by PrimeNumb** [comment]
It seems to me that the original intent was to just disable radios, and this may have been an oversight.

Issue is in `screech.dm:60-64`. Be aware that silicons are a subtype of `/mob/living/` when fixing.

**Comment by Azrun** [comment]
Duplicate of merged PR [2153](https://github.com/goonstation/goonstation/issues/2153)
