### ISSUE TITLE
Shift clicking on eject material from a fabricator opens fab window in Internet Explorer

### ISSUE THREAD

**Issue by Ormakent** [goonstation/goonstation#15330]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. shift click on eject material
2. profit

### Expected Behavior

not do that prob

### Additional Information & Screenshots

was a borg if that matters

![Screen Shot 2023-08-10 at 11 45 20](https://github.com/goonstation/goonstation/assets/35436986/a8d1f1a9-f4f5-4b2b-a8d8-fa6e6a38541e)

**Comment by CaioFrancisco** [comment]
BYOND jank, we can't fix it.
