### ISSUE TITLE
Kondaru armory door doesn't support N2O

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#15390]
### Labels

[BUG]

### Description

See title

### Steps to reproduce

1. N2O leak from armory
2. See picture

### Expected Behavior

For it to go on the tile the door is on

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/53062374/cd2fdd32-4c45-43cd-86a2-3f178cc18b3a)

**Comment by BatElite** [comment]
Spread onto the tile fine on my local
