### ISSUE TITLE
Skateboard - disappearing items

### ISSUE THREAD

**Issue by Emcee-Gore** [goonstation/goonstation#1540]
[BUG]

**Describe the bug**

If you are driving around on a skateboard, throw an item that is in your hand while driving said skateboard and then get off of the skateboard by crashing into someone for example; that thrown item is nowhere to be seen.

**To Reproduce**
1. Get on skateboard
2. Drive said skateboard
3. Throw any item that is in your hand
4. Get off of the skateboard by for example crashing into someone

**Expected behavior**
The item that you have thrown should EITHER be thrown to the place while you are still on the skateboard...or the item that has been thrown should re-appear on the skateboard tile once you are crashing off of it.

**Screenshots**

**Additional context**

**Comment by ZeWaka** [comment]
this is probably an issue with any vehicle

**Comment by Emcee-Gore** [comment]
Matter of fact pods seem to be the exception. If you drop an item while within a pod - then leave said pod the item will drop on the tile of the pod.

Not sure about throwing though.

**Comment by ZeWaka** [comment]
needs generalized vehicle.contents dropper for all exiting
