### ISSUE TITLE
Waste bag has a missing sprite/texture for monkeys

### ISSUE THREAD

**Issue by Ormakent** [goonstation/goonstation#15414]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. Watch monke enjoy its old Garry's Mod days while wearing waste bag

### Expected Behavior

monke enjoy its homelessness in peace

### Additional Information & Screenshots

![Screen Shot 2023-08-14 at 14 56 07](https://github.com/goonstation/goonstation/assets/35436986/2debf142-3476-46cd-ad35-d30065b38858)

**Comment by TealSeer** [comment]
Fixed in #15478
