### ISSUE TITLE
Hypo spray doesnt warn when in storage.

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#1543]
[BUG]

**Describe the bug**
The hypo spray doesn't give the needed warning for harmful chemicals when it is stored in a belt or backpack. It just says the chem is added but that chem is in fact deleted.
**To Reproduce**
1. Have hypo spray
2. Have harmful chem
3. Put hypo spray into backpack
4. Try to fill it
5. Be sad

**Expected behavior**
For the warning to show up rather than just deleting the chem

**Screenshots**

**Additional context**

**Comment by zjdtmkhzt** [comment]
Can confirm, this is also the case for the NT syringe gun and automenders.
