### ISSUE TITLE
Dimension Shift on shuttle

### ISSUE THREAD

**Issue by Sbmhawk** [goonstation/goonstation#15442]
### Labels

[BUG]

### Description

Dimesion shifting on a shuttle brings your camera to the new area after the shuttle starts/gets to centcomm, but then teleports you back when you leave the shift.

### Steps to reproduce

1. Get dimensional shift
2. Use dimensional shift on the shuttle before it lands.
3. See that your camera is now with the shuttle in centcomm
4. Use dimensional shift again
5. Be teleported to the channel
6. See error

### Expected Behavior

I expected to be brought with the shuttle, or for my camera to have not moved at all.

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/39737078/559a31ed-9e99-4f9e-bb38-af78f42fe452)

**Comment by Retrino** [comment]
basically  a repeat of #15184
