### ISSUE TITLE
Stun gloves have broken icons

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#15457]
### Labels

[BUG]

### Description

They have the funny purple checkerboard of death

### Steps to reproduce

1. Make stun gloves
2. Observe purple squares
3. (Possibly has something to do with the amount of mutations this person had, but I'm assuming it's just the gloves)

### Expected Behavior

I expected no purple squares

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/20713227/3fa5e353-3708-4a0f-b74f-4f35bd5f370a)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/b39f7952cd5cb7656504a39c45e200174c296bd2
