### ISSUE TITLE
Double AIs spawning with SICC core

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#15472]
### Labels

[BUG]

### Description

If a roundstart AI chooses missile arrival or mail order (honestly, I don't know which one it was, I wasn't the AI that shift) a second sicc core can spawn in the original spot, allowing another AI to join when one exists already

### Steps to reproduce

1. Have the OG spawn with a spacebux purchase that will have them end up not immediately on station
2. Sicc core exists
3. Profit

### Expected Behavior

Presence of roundstart AI should in general mean a SICC doesn't spawn

### Additional Information & Screenshots

Could be due to lag. idk

**Comment by trollbreeder** [comment]
this bug used to happen before the SICC, but it wasnt a problem because it was only a cardboard box that spawned in the core, not an entire second AI
