### ISSUE TITLE
Fermids can't be fully stunned from security weapons

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#15470]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Use baton, taser, or flash on fermid
2. It will receive stuns but never go down after enough batons/tases

### Expected Behavior

For the fermid to have full stun where it can't do any actions

### Additional Information & Screenshots

Fermids can still receive full stun when they are attacked with stamina dealing weapons

**Comment by Wisemonster** [comment]
Pretty sure this is intentional for certain mob critters, to keep them from being easily beatable

**Comment by CheffieGithub** [comment]
fermids have `no_stamina_stuns = TRUE` so them getting stunned by stamina damage at all is the real issue here. It should be more obvious that this is the case though.
