### ISSUE TITLE
Radbow initial charge doesn't show it as fully charged

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#15471]
### Labels

[BUG][MINOR]

### Description

Title

### Steps to reproduce

1. Buy radbow
2. Inspect sprite, shows it having no charge

### Expected Behavior

For it to show full charge

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/80327c39ab6df7dda21ec1f17b414dbde41a8e03
