### ISSUE TITLE
Artlab heater does not heat chem barrels

### ISSUE THREAD

**Issue by keiyakins** [goonstation/goonstation#15484]
### Labels

[BUG]

### Description

Artlab heater does not heat chem barrels

### Steps to reproduce

1. produce chem barrel
2. put a bunch of chemicals in it. Probably the ingredients for meth, let's be honest.
3. drag it to artlab and put it on the heater
4. turn the heater on
5. nothing happens

### Expected Behavior

the chemicals heat up and eventually, if appropriate, react

**Comment by TobleroneSwordfish** [comment]
fixed in b4dd095 (assuming this was before that commit, time is hard)
