### ISSUE TITLE
blob biopoint regen broken on highpop

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1560]
[BUG]

**Describe the bug**
When there's a lot of people on the server, the time between biopoint generation ticks increases drastically.  I've seen it take over ten seconds to regenerate biopoints, which makes actually doing anything in combat nearly impossible.

**To Reproduce**
1. Be a blob when the server has 80 or so people on it.
2. Spend biopoints.
3. Time how long it takes for them to come back.

**Expected behavior**
Blobs should be able to actually fight back and not sit there helplessly unable to even attack.

Edit:  Using my complete lack of knowledge I would guess that it's like the earlier shambler bug where DNA points wouldn't deplete properly because it wasn't respecting that mult thingy.  Thing is, as I see it, making it respect that mult thingy would only fix the problem for larger blobs, since small blobs have maximum biopoint pools much closer to their regeneration rate, which would lead to an enormous number of biopoints being wasted.  (For reference, in the round I noticed this I had, at one point, a regeneration rate of~ 5 and a maximum pool of around 7ish.)

**Comment by pali6** [comment]
Fixed by whatever PR did blob Life mult changes.
