### ISSUE TITLE
RP overflow ignores job priority for antags. 

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#1564]
[BUG]

**Describe the bug**
I dont have gang leader as an option yet i was picked as it with the 6 people online.
Not sure if this is isolated to gangs so i generalized it

**To Reproduce**
1. Have Gang leader not checked
2. Get gang leader

**Expected behavior**
To not spawn as gang leader

**Screenshots**

**Additional context**

**Comment by Carbadox** [comment]
Not so much a bug as it is just the game forcing players as antags due to low server pop.
