### ISSUE TITLE
Anvils cannot be deconstructed

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#15699]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Harm intent
2. Use wrench on anvil

### Expected Behavior

For anvil to be deconstructed somehow?

### Additional Information & Screenshots

Help message for it says it can be deconstructed. Regardless, it's immovable and dense it seems?

**Comment by Sord213** [comment]
I was able to deconstruct the anvil as a borg just fine. Not sure why it doesn't work for humans.

**Comment by MeggalBozale** [comment]
Anvil code tries to place the wrench on first if possible, which borg's cannot, so they get to the code for deconstruction?
