### ISSUE TITLE
Almost every caution stripe on donut 3 is a mule dropoff decal

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#15703]
### Labels

[BUG]

### Description

Almost every caution stripe on donut 3 is a mule dropoff decal

### Steps to reproduce

1. look at the decals under doors etc on donut 3
2. MULE dropoff decal
3. cry

### Expected Behavior

normal caution stripes

**Comment by Sord213** [comment]
it doesn't _really_ affect anything since they don't do anything codewise but may as well change them for clarity I guess
