### ISSUE TITLE
scissors do 0 stamina damage

### ISSUE THREAD

**Issue by Adharainspace** [goonstation/goonstation#1572]
[BUG]

**Describe the bug**
scissors do 0 stamina damage when hitting people

**To Reproduce**
1. obtain scissors
2. hit someone with it
3. that person looks at their stamina

**Expected behavior**
it should have done 20 stamina damage

**Additional context**
made on behalf of someone w/o a GH account where the bug report button didnt work for them

**Comment by UrsulaMejor** [comment]
seems to be true of scalpels, but not garden trowels. I think this might be an issue for items with:
AddComponent(/datum/component/transfer_on_attack)

**Comment by UrsulaMejor** [comment]
On further testing, also doesn't work for circular saws or enucleation spoons. I think this is a result of them being surgical items.

**Comment by TemporalOroboros** [comment]
It might be a side effect of them having piercing damage? Last I checked that was a bit strange, at least on scalpels.

**Comment by Tarmunora** [comment]
`code\obj\item.dm:1213`
