### ISSUE TITLE
Acoustic guitars are not available from cargo

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#15779]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Check cargo available items to request

### Expected Behavior

For acoustic guitar to be available

### Additional Information & Screenshots

Electric guitar is available still

**Comment by Mantweerp** [comment]
Believe this is due to Goon1's updates being stuck

**Comment by FlameArrow57** [comment]
Available now :p
