### ISSUE TITLE
Coolest genebooth feature is BROKEN

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#15781]
### Labels

[BUG]

### Description

Genebooth claims to change eye color but Doesn't

### Steps to reproduce

1. Get someone in a gene booth
2. Click the orange wrench icon to change how they look (Hair, skin color, etc.)
3. Change eye color
4. Preview's color changes :)
5. Hit confirm
6. Eject occupant of booth
6a. remove blindfold from occupant if they have one
7. What the hell? It's not changed, NT LIED to me

### Expected Behavior

I expected my shadow monster creature to have glowing red eyes and not barely visible purple ones

**Comment by Roninnozlo** [comment]
Also, separate kind of bug:
Roachpeople's chitin color is based on skin color. You can't modify it in the genebooth, though. Actually, you can; You just have to modify the color with the subject being a human, THEN change them to a roach.

**Comment by AXLFAN2000** [comment]
Testing in a local, eye colour seems to update properly now.  Reopen if problem reoccurs
