### ISSUE TITLE
Map stuck on donut2 on goon4 sylvester

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#15782]
### Labels

[BUG][ADMIN]

### Description

It has been donut2 for approximately 48 hours, despite map votes voting for other maps.

### Steps to reproduce

1. Join sylvester
2. it is donut2

### Expected Behavior

"The next map is Kondaru!" to lead to kondaru.

### Additional Information & Screenshots

Possibly due to admin manually setting map for the next round and not changing it back (this has happened before, but then again, if it were that simple to fix it would have probably been fixed by now, so idk)

**Comment by flappybatpal** [comment]
It's known, a backend issue needs to be resolved.

**Comment by TheTyrant25** [comment]
i know it's known, it's more for documentation and logging and awareness than anything

**Comment by TealSeer** [comment]
Think it's safe to close this as both servers are fine now
