### ISSUE TITLE
Horsedrone not dropping the correct loot.

### ISSUE THREAD

**Issue by Sbmhawk** [goonstation/goonstation#15799]
### Labels

[BUG]

### Description

Horsedrone only drops a cursed horse mask, instead of the other listed loot.

### Steps to reproduce

1. Code-dive into the horsedrone, see what SEEMS to be the dropped loot being overridden.
![image](https://github.com/goonstation/goonstation/assets/39737078/44961c0b-06f9-4fdc-855d-f014e91ccbec)

2. Kill horsedrone, through much luck and preparation (or admin tools).
3. See it only drops a single horsemask.
4. Be annoyed at how much work you put into it.

### Expected Behavior

I expected the drone to drop the list of what's in the code.

### Additional Information & Screenshots

I could be heavily misunderstanding the code, the code ^ and the comments on it seem to indicate an attempt to override the droploot.
![image](https://github.com/goonstation/goonstation/assets/39737078/0870ee00-573e-46fd-a57f-f78cadabd4e8)

This does not work however.

code/obj/critter/drone.dm
Line 1172-1247

**Comment by Sbmhawk** [comment]
I did end up killing it on live, my disappointment was immeasurable.

This might seem like a heavy droplist, extremely too much, but consider what is required to summon a horsedrone in the first place, much less kill one. (it shoots maxcaps every time it shoots :) )

If its summoned the shuttle is most likely already called, or about to be called, so I dont think its that bad.

**Comment by pali6** [comment]
![image](https://github.com/goonstation/goonstation/assets/358431/f47b432f-66f9-48e2-97cd-b9e30fe7066c)
cannot reproduce
