### ISSUE TITLE
being in a body bag lets you survive cremation

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#15806]
### Labels

[BUG][MINOR]

### Description

being cremated while inside of a closed body bag doesn't cremate you

### Steps to reproduce

1. be in a closed body bag
2. get cremated
3. live unharmed

### Expected Behavior

cremation

### Additional Information & Screenshots

probably applies to all other things like lockers

**Comment by UrsulaMejor** [comment]
Verified bug
