### ISSUE TITLE
New wood material can't be used to change reinforced tables

### ISSUE THREAD

**Issue by pattern-moth** [goonstation/goonstation#15845]
### Labels

[BUG][MINOR]

### Description

If you have a wooden plank from the cargo warehouse, you can click on a reinforced table to make it into a fancy wooden table (like you see in the bar). If you use wood cut from a tree, it does not work.

### Steps to reproduce

1. Grow and cut down a tree for wood.
2. Attempt to use the wood on a reinforced table.

### Expected Behavior

Previously, wood cut from a tree was able to be used on reinforced tables to change the appearance.

**Comment by MeggalBozale** [comment]
Thinking about removing the /obj/item/plank and just replacing all uses of it with the material plank. Will link the pr if I finish it.
