### ISSUE TITLE
Lanyard turns into an ID

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#15852]
### Labels

[BUG][OBJECTS]

### Description

When a dead body is loaded into the enzymatic reclaimer, the lanyard appears to transform into an ID.

### Steps to reproduce

1. Die as a tourist (or just with a lanyard)
2. get your body stuffed into the enzymatic reclaimer
3. right click the pile of your belongings

### Expected Behavior

I expect the lanyard to stay one.

### Additional Information & Screenshots

The lanyard in question:
![image](https://github.com/goonstation/goonstation/assets/51260013/ddf4891f-12aa-48a0-9616-98667c23f0a9)
The real ID (top line) vs the lanyard one (bottom line)
![image](https://github.com/goonstation/goonstation/assets/51260013/31efe3b4-5b16-4bd8-9b06-61b8eef3ad99)
The sprite in world changed as well.

**Comment by MeggalBozale** [comment]
I shoved in a dummy with a custom spawned lanyard and couldn't reproduce this.
![dreamseeker_b5MspeDVnm](https://github.com/goonstation/goonstation/assets/27376947/12dc2fce-dcb5-41fb-8be9-cbc81a97bee8)
However, respawning as a tourist (WHY did I have to add a new /datum/job/daily/friday to the jobs controller for this) did cause this bug to be reproduced. It's probably job code. fix wip
