### ISSUE TITLE
Bug regarding making chair out of wood sheets

### ISSUE THREAD

**Issue by CrystalClover** [goonstation/goonstation#15999]
### Labels

[BUG]

### Description

Chair was very dark and had description of "You shouldn't be seeing this! It is made of wood."

### Steps to reproduce

1. Craft wooden chair out of wooden sheets

### Expected Behavior

have the chair look like noraml wooden chairs

### Additional Information & Screenshots

![Capture](https://github.com/goonstation/goonstation/assets/94804240/966d161b-eb70-4c0f-8ec1-5e8e7b6b3fab)

**Comment by UrsulaMejor** [comment]
fixed
