### ISSUE TITLE
Contraband sticker+spacesegway=???

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#16021]
### Labels

[BUG]

### Description

well i did it again, i found another obscrue ass bug, do above and you get a sprite of yourelf on segway while your off it
also works with other stickers

### Steps to reproduce

1. stick a contraband sticker to a space segway
2. get on
3. move
4. notice sticker disappears
5. get off
6. your still on segway?

### Expected Behavior

not this but its funny

### Additional Information & Screenshots

![d30a137777893cac6274862bb31afbaa](https://github.com/goonstation/goonstation/assets/63602513/5e136848-36bd-4f97-a8a9-4f314d5cf006)
![86e2ee1d822127e624172b258dc13bc6](https://github.com/goonstation/goonstation/assets/63602513/3423c534-a170-4a7e-93ac-929b3fee5ce4)

**Comment by Mantweerp** [comment]
Is the same for the buffer (and presumably all other things which put your character on it and move)
