### ISSUE TITLE
Mousetrap pipe bomb went off only after putting it in backpack

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#16025]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. (Not sure if this happened but a mousetrap pipebomb may have went off after being stepped on, and wasn't destroyed)
2. Pick up mousetrap pipebomb
3. Click satchel with it
4. It goes off

### Expected Behavior

For the mousetrap pipebomb to be deleted on activation, or when attacked

**Comment by UrsulaMejor** [comment]
Unable to replicate
