### ISSUE TITLE
An observer was chosen as the one to control frost bats WHY????

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#16023]
### Labels

[BUG] [P-Major]

### Description

I dont even know just watch the clip

### Steps to reproduce

ACTUALLY UNSURE

Maybe something like
1. be vampire
2. have ghost over u
3. frost bat ability
4. issue??? maybe?

### Expected Behavior

NOT THAT

### Additional Information & Screenshots

WHAT ON EARTH DID I JUST WITNESS? HOW?

https://github.com/goonstation/goonstation/assets/27376947/ff4d3835-6b73-43f8-93b2-300f527a9eb4

Maybe they were standing over the vampire when they used the ability??? I DONT KNOW
Round on Goonstation 1 at approx. 9:12PM EST

**Comment by TobleroneSwordfish** [comment]
yass said they fixed it

**Comment by MeggalBozale** [comment]
awesome
