### ISSUE TITLE
[Critical] Botany mister doesn't fill botany grow trays anymore

### ISSUE THREAD

**Issue by Catsinamansuit** [goonstation/goonstation#16073]
### Labels

[BUG]

### Description

Botany mister no longer fills botany trays.

### Steps to reproduce

1. Turn on botany mister
2. Tray contents remain unchanged, mister contents remain at 100%

### Expected Behavior

Mister is supposed to fill the trays.

**Comment by zjdtmkhzt** [comment]
caused by 3724ac5267825ed62b657954daadbd734cca1c25 i believe

**Comment by Catsinamansuit** [comment]
Did.  They forget to label the botany trays as a open container?  Not really sure.  Thanks for picking this up by the way.  Appreciate it.

**Comment by TobleroneSwordfish** [comment]
Fixed by 0e2444f but I'll let zjd and Tyrant argue over the open containerness of plantpots: #16076 #16075
