### ISSUE TITLE
Extracting from sliced dread only gives bread reagent

### ISSUE THREAD

**Issue by Monoblaster** [goonstation/goonstation#16126]
### Labels

[BUG]

### Description

I exctracted the reagents from sliced dread using the Reagent Extractor and only got bread reagent

### Steps to reproduce

1. Make Sliced Dread
2. Put it in the reagent extractor
3. Extract it
4. Get bread

### Expected Behavior

For it to give me 10u of ectoplasm the forum says it has

**Comment by UrsulaMejor** [comment]
Slicing bread leads to it overwriting the reagents of the sliced bread with the divided reagents of the loaf. This makes sense, except every single breadloaf doesn't have its reagents properly set
