### ISSUE TITLE
UI positions inside of pods are off

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#16124]
### Labels

[BUG]

### Description

Entering a pod increases the area the UI covers, causing some of the UI elements to become cut off

### Steps to reproduce

1. Find a pod
2. Enter pod
3. Notice UI elements are cut off

### Expected Behavior

For the UI elements to not be cut off

### Additional Information & Screenshots

![Goonstation 3 Roleplay_ Morty_ Main Channel Science Garrison 69 9_29_2023 9_47_42 PM](https://github.com/goonstation/goonstation/assets/87689371/12e784b2-2ec7-4d9e-bf89-99b9105829f9)

**Comment by DisturbHerb** [comment]
More likely than not, your display settings are not set to `Stretch to fit`. Feel free to re-open if this is not the case.
