### ISSUE TITLE
Assigned nukeop even though role is disabled

### ISSUE THREAD

**Issue by REDJAY12** [goonstation/goonstation#1613]
[BUG]

**Describe the bug**
I was assigned nukeop despite having that role disabled in character setup.

**To Reproduce**
1. Uncheck nukeop.
2. Play a few rounds until randomly chosen to be nukeop.

**Expected behavior**
Disabled antagonist roles should not be randomly assigned. Alternatively, nukeop antagonist roles should be correctly flagged per role selection.

**Screenshots**
![image](https://user-images.githubusercontent.com/65835998/88464476-0d778700-ce89-11ea-90b7-3c384900c965.png)
![image](https://user-images.githubusercontent.com/65835998/88464564-d0f85b00-ce89-11ea-8a83-e1e30620997f.png)

**Comment by moonlol** [comment]
if pop is low enough you can be forced into an antag role

**Comment by REDJAY12** [comment]
Shouldn't that pull from the enabled roles list? If the server randomly lands on a nukeop round before checking roles but nobody has it enabled I would recommend that it re-roll the round type. Being a singular nuke agent on a server as a noob is nearly impossible. Side note, this did happen once before on a well-populated server (40+) but I assumed it was a fluke then.

**Comment by PrimeNumb** [comment]
As stated previously, not a bug. Server rolls gamemode first, then tries to pick players from those with antag tokens enabled and those with the role enabled and if that fails, random people will be eligible for selection. Changing this requires a non-trivial amount of legwork and would most definitely have a number of implications on gamemode distribution. I'd probably move such a discussion to the [Ideas & Suggestions](https://forum.ss13.co/forumdisplay.php?fid=8) subforum.

Being a solo nuclear operative shouldn't be happening though unless it's lowpop.

**Comment by REDJAY12** [comment]
Understood, I appreciate the explanation. I'm not looking to inconvenience the devs with a big project suggestion, so all's good. I'll just have to get good for next time, ha.
