### ISSUE TITLE
Incorrect speech bubbles for whispering

### ISSUE THREAD

**Issue by RubberRats** [goonstation/goonstation#16140]
### Labels

[BUG]

### Description

When you whisper, the little speech bubble that comes out when you say something appears incorrectly.

### Steps to reproduce

1. Wait for someone to sing
2. Whisper
3. Your speech bubble comes out as a musical note despite you not singing.

### Expected Behavior

Whispering to use its own bubble

### Additional Information & Screenshots

As far as I can tell, it uses the bubble for the last message said on the server. I was able to notice it using both versions of the musical note bubble and the exclamation mark.

**Comment by wolfolotl** [comment]
I don't think whispering _has_ its own bubble nor was it intended to? so this is not a bug

**Comment by RubberRats** [comment]
Maybe I should be more clear. The bubble was coming out as a musical note despite me not singing. As far as I can tell, it is instead copying the bubble from the message directly before, which in this case was somebody singing.
