### ISSUE TITLE
Skeleton heads never stop after being thrown

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#16157]
### Labels

[BUG] [MUTANTRACE]

### Description

If you, as a skeleton, detach your head and throw it, it flies until it hits a wall.

### Steps to reproduce

1. Go to cogmap1. Be a skeleton.
2. Open all the doors along a straight line in the west primary corridor. Remove walls if needed.
3. Go to the very northernmost part of said straight line
4. detach your head, pick it up
5. throw it downward
6. it flies all the way through the station from near security and stops near medbay.
7. force your headless body to run the length of the station to go pick it up (optional)

### Expected Behavior

I expect it to stop after a distance, like most thrown items.

### Additional Information & Screenshots

This bug was found and then repeatedly checked while on local, not on the live server.

**Comment by UrsulaMejor** [comment]
isn't this specifically trying to emulate bowling with your own head, like in a cartoon?

**Comment by UrsulaMejor** [comment]
Confirmed feature

**Comment by TheTyrant25** [comment]
whoops
