### ISSUE TITLE
Cogmap 1 rancher kitchen chute doesn't work

### ISSUE THREAD

**Issue by Monoblaster** [goonstation/goonstation#16151]
### Labels

[BUG][MINOR][MAPPING]

### Description

Using the rancher's kitchen chute on cog 1 ejects them back out at the chute

### Steps to reproduce

1. Put a chicken on the chute
2. Use it
3. Watch as the chicken comes back out

### Expected Behavior

For the chicken not to come back

**Comment by TheTyrant25** [comment]
can't seem to reproduce on local. might be to do with secret repo? idk

**Comment by UrsulaMejor** [comment]
the chickens are breaking the chutes by clonging around
