### ISSUE TITLE
M90 causes message spam (and thus lag) against armored targets.

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1616]
[BUG]

**Describe the bug**
Shooting someone with the M90 machine gun will result in significant lag if it's used against armored targets.

**To Reproduce**
1. Get someone with an M90 to shoot you while you are wearing armor with ranged resistance.
2. Note how you get 16 chat messages in an extremely short time frame. (You are hit by the bullet!/Your armor softens the hit! repeated 8 times.)

**Expected behavior**
Well, technically this is completely expected based on how it works (there's two different messages so the messages can't stack) and I am honestly shocked it took me this long to notice but I guess I'll say I expect not to have a lagspike every time a popular nukie weapon is used.

**Additional context**
I imagine getting the "your armor softens the hit" message to be part of the same message as the "you are hit by the bullet" would help by letting the messages stack but not being a programmer I have no idea how easy or hard of a task that would be to change.

**Comment by flappybatpal** [comment]
These messages no longer result in lag.
