### ISSUE TITLE
New Halloween hats render below potted plants

### ISSUE THREAD

**Issue by Ormakent** [goonstation/goonstation#16163]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. equip giraffe hat
2. stand tile under some bush

### Expected Behavior

prob should render above bushes when outside of bush tile

### Additional Information & Screenshots

![Screen Shot 2023-09-30 at 15 52 30](https://github.com/goonstation/goonstation/assets/35436986/9d7bb22a-fb92-4fd2-a13f-ef7f72dfc763)

**Comment by TobleroneSwordfish** [comment]
We simply do not have the technology for conditional layering afaik.
