### ISSUE TITLE
Orwell is actually george in diguise

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#16178]
### Labels

[BUG]

### Description

if ORWELL gets into a downed/dead state, they become george

### Steps to reproduce

1. beat orwell to death(kinda impossible since there immortal like george nowm but do it anyway)
2. see george  at some point?

### Expected Behavior

orwell not turn into george

### Additional Information & Screenshots

![d43c91650f437eaf9eed54cbc0b26500](https://github.com/goonstation/goonstation/assets/63602513/5a9d715b-417e-493d-9c32-a440f224a38e)
this is actually a picture of ORWELL getting stung by wasps, not george

**Comment by MeggalBozale** [comment]
1984
