### ISSUE TITLE
Haunted lockers suffocate occupants

### ISSUE THREAD

**Issue by Magmahunter** [goonstation/goonstation#16188]
### Labels

[BUG]

### Description

People inside of a haunted locker immediately start suffocating as long as the locker is closed

### Steps to reproduce

1. Make a soulsteel locker.
2. Have a ghost haunt the locker.
3. Get a living player inside the locker.
4. Watch as the living player inside starts taking suffocation damage until either released or dead.

### Expected Behavior

Haunted lockers used to be breathable before, I expected this to not have changed

**Comment by MeggalBozale** [comment]
![image](https://github.com/goonstation/goonstation/assets/27376947/8d0f757e-5306-4f47-bb3f-cdbdc07b5340)
#8303 @frawhst can reopen this if this was unintentional, but considering the comment and the explicit code change I'm inclined to call this not a bug
