### ISSUE TITLE
Cable spawners brokey

### ISSUE THREAD

**Issue by TheTyrant25** [goonstation/goonstation#16203]
### Labels

[BUG]

### Description

They do not detect surrounding wires

### Steps to reproduce

1. map using them
2. look at them

### Expected Behavior

I expect them to work (sobbing)

### Additional Information & Screenshots

Brought to my attention by cheffie. Posting this as a reminder for me to actually work on it.
![image](https://github.com/goonstation/goonstation/assets/51260013/4c69eea2-5e48-4bed-8ef1-f42820d96079)

**Comment by UrsulaMejor** [comment]
![image](https://github.com/goonstation/goonstation/assets/50289389/431af5ee-c6bc-458c-8324-892056ca0e39)

![image](https://github.com/goonstation/goonstation/assets/50289389/a4db3409-608b-4bef-b846-772880eebc39)

![image](https://github.com/goonstation/goonstation/assets/50289389/6f58077e-54bc-4c45-9995-d3830729bcdc)

**Comment by TheTyrant25** [comment]
melterfrog emoji
these auto cables are the bane of my existence
why did i make them
