### ISSUE TITLE
People who can see ghosts can physically interact with the AI eye

### ISSUE THREAD

**Issue by trollbreeder** [goonstation/goonstation#16215]
### Labels

[BUG][MINOR][SILICONS]

### Description

People with ghostvision such as ghost busters are able to do things to the AI's eye as if it were a regular living mob

### Steps to reproduce

1. Wear a ectoplasmoleic imager to see ghosts
2. Get the attention of an AI so they look at you so that their eye is near you
3. Click the eye on any intent
4. Ghostbuster shakes AI, trying to get their attention! Ghostbuster shoves AI! Ghostbuster punches AI! Ghostbuster punches AI and lands a devastating hit!

### Expected Behavior

I expected clicking on the AI eye to do nothing. I expected there to be nothing you can do to an AI eye except see it and point at it.

### Additional Information & Screenshots

In this image, Scanline is an AI looking right next to Bust. Bust has ghost vision.
![image](https://github.com/goonstation/goonstation/assets/25937686/8a1f86b6-3544-4d0c-acd6-cf45ab61d77f)
Doing this to an AI eye doesn't actually hurt the AI or anything, it just makes impossible chat messages.

**Comment by RSG250** [comment]
pretty sure its a "feature" or a side effect, who doesnt want to stick googly eyes on the ai eye

**Comment by MeggalBozale** [comment]
Has been a feature for ages and I'm inclined to close this

**Comment by UrsulaMejor** [comment]
essentially an ascended bug. we have no intention of fixing these interactions unless they become problematic.
