### ISSUE TITLE
ACTUALLY CRITICAL Pickling a turbine crashes everyone who comes into viewing range of it

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#16219]
### Labels

[BUG] [CRITICAL]

### Description

Pickling a turbine crashes the game of all who look at it

### Steps to reproduce

1. Pickle the turbine
2. You crashed congrats
3. Try rejoining if you can do that
4. You crash again
5. Uh oh

### Expected Behavior

CANT pickle a turbine and more importantly diff materials on a turbine does NOT crash people

### Additional Information & Screenshots

SOURCE: Discord, BushBug (Russell Would) [_leaffish] [Original Message](https://discord.com/channels/182249960895545344/890223070999101480/1158576087895384164)
(Compressed)

https://github.com/goonstation/goonstation/assets/27376947/26e7e16d-de48-4b79-8d17-1b7e9b386ecd

**Comment by TheColorCyan** [comment]
the perfect duo
jean nuclear reactor and pickled turbine

**Comment by MeggalBozale** [comment]
leah said its fixed
