### ISSUE TITLE
Wood Sheet Requisition Issue

### ISSUE THREAD

**Issue by CrystalClover** [goonstation/goonstation#16217]
### Labels

[BUG]

### Description

Wooden Sheets are only counted by number of stacks, rather than stack amount, so a Req requiring 8 planks will need 8 1 planks stacks instead of a single 8 plank stack

### Steps to reproduce

1. find requisition requiring wooden planks
2. place stack of 10 planks into crate
3. see that it only counts as 1 plank

### Expected Behavior

for however many planks are in the stack to be taken into account

**Comment by MeggalBozale** [comment]
Nah I probably caused this ill fix it

**Comment by Kubius** [comment]
Known issue, should be getting fixed in #16194

**Comment by UrsulaMejor** [comment]
duplicate of #16192
