### ISSUE TITLE
NT Bandana lacks correct captialisation

### ISSUE THREAD

**Issue by 444Portal** [goonstation/goonstation#16237]
### Labels

[BUG] [TRIVIAL]

### Description

The NT bandana appears as a 'nt bandana' on examine, on tooltips, its a 'Nt bandana'

### Steps to reproduce

1. Spawn in as NTSC/Spawn a NT Bandana
2. Show the tooltip or examine yourself with it
3. Cry

### Expected Behavior

For tiny gramatical errors to not exist. If only!

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/76797216/f3681dd5-f79e-41d7-970b-d379e6a15401)
![image](https://github.com/goonstation/goonstation/assets/76797216/22ad4e9a-28d4-43d2-9270-d6ea4e88e031)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/9f16988de8d7ff1b49df3bd633792943d8e0cd08
