### ISSUE TITLE
Syndicate Weapons Vendor descriptions are off

### ISSUE THREAD

**Issue by 444Portal** [goonstation/goonstation#16239]
### Labels

[BUG] [TRIVIAL]

### Description

Quite a few descriptions are wrong or just weird

### Steps to reproduce

1. Become a Nuclear Operative
2. Check the Vendor
3. See all the issues described in Additional Information

### Expected Behavior

For everything to be correct

### Additional Information & Screenshots

-Branwen belt has four magazines, five counting the one loaded, not three
-Predator belt has three .357, four in total, not two
-Heavy Weapons Specialist has five LMG belts, not three, six counting the one loaded
-Infiltrator's EMAG should be capitalized, same with Scout
-Firebrand description says 'incendiery' not incendiary  
-Vendor's header just says 'Materiel' same with the Security Weapon Vendor

**Comment by Tarmunora** [comment]
not changing the vendor header because tgui
