### ISSUE TITLE
Spontaneous plant species jump without splicing.

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#1626]
**Describe the bug**
Plant spontaneously turned into a different species with no plant model, and with the wrong reagents for a spontaneous splice.
Upon planting, the seed became a "Fix this shit" model, was named White Fungus, and had Space Fungus and Omnizine in it.  It harvested as a White Cannabis leaf, and would sell as Medical Herbs.

**To Reproduce**
I have no idea how to reproduce this error.  Happened when planting a White Cannabis seed in 
http://goonhub.com/rounds/89846

About 45 minutes into the round, at a guess. 

**Expected behavior**
A White Cannabis plant to grow.

**Screenshots**

**Additional context**

**Comment by ZeWaka** [comment]
pooling thing fixed
