### ISSUE TITLE
Cyborgs can take stomper's cell out but cannot put them back in

### ISSUE THREAD

**Issue by Monoblaster** [goonstation/goonstation#16327]
### Labels

[BUG][TRIVIAL][SILICONS]

### Description

As a cyborg you can open up a stomper's panel and take out the cell but cannot put the cell back in

### Steps to reproduce

1. Be a cyborg
2. Use a crowbar on a stomper unit
3. Click on the stomper unit with no item to take the cell out
4. Scream as you cannot put the cell back in

### Expected Behavior

For cyborgs to either not be able to take the cell out or to be able to put the cell back in

**Comment by Retrino** [comment]
this isnt exactly a bug, screwing yourself over by decelling your stomper is indeed annoying but being unable to put it back wouldnt be unintended behavior. recommend making a qol post about it on forums instead
