### ISSUE TITLE
Door to the room east of Engineering on Donut 2 is called "Autolathe Storage"

### ISSUE THREAD

**Issue by TealSeer** [goonstation/goonstation#16351]
### Labels

[BUG] [MAPPING] [TRIVIAL]

### Description

Room is labelled with a machine that doesn't exist

### Steps to reproduce

1. Load donut 2
2. Look

### Expected Behavior

Name it something not made up

**Comment by BatElite** [comment]
Judging from the old changelog autolathes were replaced by manufacturers mid december 2010, that's some vintage door names
