### ISSUE TITLE
Golden AKM lacks a back sprite/doesn't use one

### ISSUE THREAD

**Issue by 444Portal** [goonstation/goonstation#16373]
### Labels

[BUG] [MINOR]

### Description

Converting a AKM to its golden version through the 'Helios' medal reward causes its back sprite to become a pink/black 'missing textures' sprite

### Steps to reproduce

1. Get an AKM
2. Use the Helios medal reward on it
3. Equip it on the back

### Expected Behavior

To see the golden rifle on my back

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/76797216/cc648ba0-796f-4651-84a2-e4fce295ec85)
![image](https://github.com/goonstation/goonstation/assets/76797216/3afa34d2-8391-407b-9f34-9d47f70a74a5)

**Comment by AXLFAN2000** [comment]
Fixed by https://github.com/goonstation/goonstation/commit/c0eb6ed6391a08895f0cce88e46e96fb494bcb8d
