### ISSUE TITLE
Sheep AI breaks permanently after partnering

### ISSUE THREAD

**Issue by kbsmilk** [goonstation/goonstation#16385]
### Labels

[BUG] [MAJOR]

### Description

After partnering once successfully, the next one will fail and trigger the bug. Once this starts, the sheep doesn't move, eat, or fight. It only grows wool and starves to death.

### Steps to reproduce

1. Get two sheep in a pen and wait for them to partner. It could be Dolly and another sheep, or 2 brand new sheep from Cargo.
2. Wait for the success message: "The ewe looks sheepishly at the ram! The ram looks baashfull!" Then watch both sheep carefully.
3. Once they start partnering a second time, *some unknown thing* cancels the action bar. Often it's the initiator sheep doing a wander move, or a feed move, during the action bar.
4. The initiator sheep gets its AI back, but the target sheep does not. It will stand where it was, or where it gets pulled, forever.
5. The initiator sheep will periodically try to partner with the now-catatonic target. The action bar will most often get canceled before it completes.

### Expected Behavior

Action bar doesn't get canceled by anything ever. Or the AI gets reset correctly. Or both

### Additional Information & Screenshots

Rarely, after many attempts, the partnering action bar completes on a catatonic sheep, and they regain AI. I only observed this happen once, and got a video of it.
Here's 4 clips I took of the bug triggering:
Vid 1, ram AI breaking: https://youtu.be/J-4uUF2ECk8
Vid 2, the same ram from Vid 1, getting its AI fixed: https://youtu.be/4t8a3pjDE9s

Vid 3, the very same ram breaking, but it never got better and starved eventually: https://youtu.be/98NZ36vgdkI
Vid 4, a different pair of sheep, also with the ram losing its AI: https://youtu.be/bR3LD8HTXH8

**Comment by UrsulaMejor** [comment]
![hachi-palitinho](https://github.com/goonstation/goonstation/assets/50289389/03d77729-a546-4607-87eb-e7179f695f9e)

**Comment by UrsulaMejor** [comment]
Looking into it
