### ISSUE TITLE
HVAC nullspace 

### ISSUE THREAD

**Issue by stupidratfromss13** [goonstation/goonstation#16436]
### Labels

[BUG]

### Description

A worryingly consistent way to nullspace someone

### Steps to reproduce

1. Acquire an HVAC
2. deconstruct the HVAC (not to the point where it's an item that you can pick up but when you click on it with the deconstruction tool it begins the action bar to turn it into a deconstructed frame)
3. Apply glue to the HVAC
4. Throw someone onto the HVAC
5. Deconstruct the HVAC
6. ???
7. Profit 

### Expected Behavior

It used to let you drag people around while they were inside the frame but now it's just a nullspace

**Comment by unfunnyperson** [comment]
fixed by #2b8c09c
