### ISSUE TITLE
Ghost Critters can spawn infinite gibs with a sloppy joe

### ISSUE THREAD

**Issue by CaioFrancisco** [goonstation/goonstation#16445]
### Labels

[BUG]

### Description

Ghost Critters, when attempting to eat a Sloppy Joe, spawn the gibs from eating it but don't eat it at all. Spamming the sloppy joe will spawn infinite gibs.

### Steps to reproduce

1. Be a robot cockroach.
2. Loot the kitchen for food.
3. Try to munch on that delicious sloppy joe.
4. Realize it spawned the gibs without you really eating it.

### Expected Behavior

For the gibs to not spawn.

**Comment by Retrino** [comment]
repeat #14978

**Comment by CaioFrancisco** [comment]
mb
