### ISSUE TITLE
Produce crate fruit have no reagents

### ISSUE THREAD

**Issue by Monoblaster** [goonstation/goonstation#16487]
### Labels

[BUG][MINOR]

### Description

Fruit that you get from cargo produce crates (except carrots) do not have their expected reagents

### Steps to reproduce

1. Order a produce crate from cargo and receive it
2. Grab an apple from it and compare it to a grown apple
3. See the produce crate apple has no apple juice while the grown apple does
4. Scream in agony

### Expected Behavior

Produce crate fruit should have their expected reagents in them

**Comment by pali6** [comment]
the way reagents are currently added to fruit etc. makes this very annoying to fix
