### ISSUE TITLE
Security Helmet Flashlight not working unless unequipped and equipped again

### ISSUE THREAD

**Issue by Legendahkiin** [goonstation/goonstation#1657]
[BUG]

**Describe the bug**
The standard security helmet's flashlight (the helmet you spawn with) does not work unless you take it off and on.

**To Reproduce**
1. Start as a Security Officer
2. Attempt to 'Toggle Hardhat Light (helmet)' (top left) -> doesn't work
3. Take helmet off
4. Put helmet on
5. Attempt to 'Toggle Hardhat Light (helmet)' (top left) -> works

**Expected behavior**
I would expect the helmet's light to work without taking it off and on.

**Comment by MarkNais** [comment]
Confirmed. I suspect it has something to do with the helmet being spawned on the player on-spawn. Like the lighting component not registering properly.

**Comment by Carbadox** [comment]
Test locally, this is no longer an issue.
