### ISSUE TITLE
Guardbuddies no longer send acc_code when recalled

### ISSUE THREAD

**Issue by swatjester** [goonstation/goonstation#1661]
[BUG]

**Describe the bug**
Guardbuddies should, when issued a recall command from the DWAINE console, reply with a packet that includes the key/value pair for the acc_code, which is used by (primarily Mechanics, but anyone with the right cartridge) to "hack" doors, lockers, and other hackable electronics. I confirmed that this behavior works properly as expected on a local server running Goonstation 2020 code. 

On RP Overflow server, on the other hand, the Guardbuddies do not include acc_code as part of the packet when they are recalled. 

**To Reproduce**
1. Spawn round as Mechanic (not strictly required, but saves you time gathering materials)
2. Go to DWAINE terminal at NetCafe
3.  Log in using your ID card and term_login
4. Input "echo registered=Pubbie Jones|nassignment=Staff Assistant|naccess=34 ^ /mnt/term/loginpacket" (without the quotations)
5. input "su" (without the quotations)
6. input "file_send" (without the quotations). 
7. Observe "You are now authorized" indicating you have SU level access.
8. input cd /mnt/control
9. Open PDA, navigate in file browser to Wireless Packet Sniffer, set channel to 121.9 and range to Max, and hit start
10. back on the DWAINE, input prman recall all
11. Observe packets coming in on your PDA, and that acc_code is not among them.

[57:03:1]:data=1495.5; address_1=recharge; sender=0202ec02; 
[57:03:5]:command=recharge_src; data=x=181&y=170; address_1=0202ec02; sender=0202ec11; 
[57:03:6]:command=recharge_src; data=x=182&y=170; address_1=0202ec02; sender=0202ec16; 
[57:03:7]:command=recharge_src; data=x=178&y=170; address_1=0202ec02; sender=0202ec01; 
[57:04:9]:data=4494.5; address_1=recharge; sender=0202dbfd; 
[57:05:3]:command=recharge_src; data=x=182&y=170; address_1=0202dbfd; sender=0202ec16; 
[57:05:3]:command=recharge_src; data=x=178&y=170; address_1=0202dbfd; sender=0202ec01; 
[57:05:5]:command=recharge_src; data=x=181&y=170; address_1=0202dbfd; sender=0202ec11; 
[57:10:9]:data=2996; address_1=recharge; sender=0202ca54; 
[57:11:4]:command=recharge_src; data=x=182&y=170; address_1=0202ca54; sender=0202ec16; 

12. Even restarting the DWAINE terminal and reconnecting to the mainframe, using a different terminal, using a different ID, using a Network Diagnostic Cartridge vs. the Mechanics analyze cartridge , none of it makes any difference. 

**Expected behavior**

Packet should include acc_code with a value in the format " XXXX Alpha XXXX"

**Screenshots**
![image](https://user-images.githubusercontent.com/16358075/88853280-18962400-d1b5-11ea-9205-96290b6ae133.png)

**Additional context**
I checked with multiple people before bugging this, and everyone was under the impression that this is not working properly and it should be validly giving me the acc_code, especially since it works on my own local server running Goonstation 2020.
I checked through the code, and could not find anything that indicates in the code that this was changed recently. All the code *looks* like it should be properly granting this code.

**Comment by swatjester** [comment]
Doesn't work from the RD's station either.

**Comment by glassofmilk** [comment]
I just tried locally, and it's working fine for me. You may need to increase the range on your packet sniffer or use a terminal closer to the network radio.

![](https://i.imgur.com/VJUtcx2.png)

**Comment by swatjester** [comment]
@glassofmilk  - which map/terminal was that?   I'll see if I can get the same results from that one. My packet sniffer range was definitely set to max (see screenshot above) and I've had the same results from the NetCafe, Telescience, Bridge, and RD's office terminals on Oshan.

**Comment by glassofmilk** [comment]
I just tested on Goon2, and it was working fine. I was on Cog1, using the terminal in tech storage.

**Comment by swatjester** [comment]
OK, I was able to do it on Goon 2 on Cog2, as well. So... maybe it's an Oshan specific thing? Or server specific to RP-overflow (or both since that one runs Oshan 24/7)? If it's not too much trouble, could I ask you to check there? If you're still able to do it there, it's definitely just something weird with my process and I'll go ahead and close it out, but I've got a sneaking suspicion it's not gonna work there for you.

**Comment by glassofmilk** [comment]
Ok, I tested on Oshan on RP Overflow, and it worked for me there, too.

**Comment by swatjester** [comment]
Well, since I was able to get it to work everywhere except Oshan, and glassofmilk can get it work on on Oshan, I'm convinced there's some sort of gameplay/map reason that was affecting it, and probably nothing systemic with the buddies/packet system.  I'll close this out as promised.
