### ISSUE TITLE
Guardbuddies break when you stand ontop of them

### ISSUE THREAD

**Issue by Vincent983** [goonstation/goonstation#16641]
### Labels

[BUG]

### Description

When you stand ontop of an angered guardbuddy, it seems to break. with the guard script it totally breaks, and stops following it's assigned person or caring about them, with other modes it has a significantly delayed attack speed when you're ontop of it.

### Steps to reproduce

1. Hit a guardbuddy or it's assigned master
2. it gets angry and follows you
3. you stand ontop to assert dominance
4. the guardbuddy is calmed by this display and completely stops doing anything, needing you to plug it back in and re-wake it to make it resume doing processes.

### Expected Behavior

It should arrest people ontop of it

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/f7d847448bd870eda60e74391ec02a1fbe302945
