### ISSUE TITLE
Blob can't break or spread onto security tape

### ISSUE THREAD

**Issue by CheffieGithub** [goonstation/goonstation#16650]
### Labels

[BUG]

### Description

Security tape creates a completely impassable barrier to blobs

### Steps to reproduce

1. Make blob a crime scene
2. Blob is forced to submit to the tape

### Expected Behavior

It can break it at least

### Additional Information & Screenshots

![Goonstation 1 Classic Heisenbee The Curse of Iudicium Laboratory 69 2023-10-26 192036 (1)](https://github.com/goonstation/goonstation/assets/113442598/c82e6fcc-9e96-4154-926b-f28988af006a)

**Comment by TealSeer** [comment]
Duplicate of #16651
