### ISSUE TITLE
Mentor mouse deafness

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1666]
[BUG]

**Describe the bug**
when entering a person who is deaf as a mentor mouse, you become deaf as well and thus can not hear them.

**To Reproduce**
1. get in pocket of deaf person
2. become deaf

**Expected behavior**
to be able to hear them

**Additional context**
they can still see your whispers apparently

**Comment by pali6** [comment]
People can now reply to mentor mice using F3.
