### ISSUE TITLE
Printed Trench Maps aren't Opening

### ISSUE THREAD

**Issue by MarkNais** [goonstation/goonstation#1667]
[BUG]

**Describe the bug**
Attempting to "use" a printed trench map that spawns on round-start does not open any interface or pop-up.

**To Reproduce**
1. hold a trench map.
2. Press "C", nothing happens
3. Click the map in-hand, nothing happens

**Expected behavior**
A popup of the trench map.

**Comment by pali6** [comment]
You are supposed to examine them to see the map but I'll add this as a feature.
