### ISSUE TITLE
as a ghost, the tool tip for chairs pops up by clicking, its aaaaaaa

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#16745]
### Labels

[BUG]

### Description

as ghost click a chair to spin it, tool tip come up, chat box get filled fast

### Steps to reproduce

1. click chair to spin as ghost

### Expected Behavior

tooltip to not appear for ghost?

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/63602513/12704456-99d9-47b0-9eb3-08d05c2aa376)

**Comment by RSG250** [comment]
it also pops up for walls, tables and stuff, just clicking them 1 time will cause it, its aaaaaa

**Comment by RSG250** [comment]
im a dumby and didnt read the changlog entry completely, didnt notice there was a way to disable them

**Comment by TealSeer** [comment]
This was also properly fixed in https://github.com/goonstation/goonstation/commit/4da1046e40538444cf20efae59004408a26ac63c so they now group the messages properly and will just show up as x2 x3 x4 etc. as normal
