### ISSUE TITLE
triple meth provides not stamina regen or stun reduction

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1674]
**Describe the bug**
Triple meth causes brain damage and appears to do jack shit else.

**To Reproduce**
1. Take triple meth.
2. Sprint.
3. Check your stamina regen
4. Check your stun resistance

**Expected behavior**
You should receive an enormous amount of stamina regen (333 if I'm not mistaken), 98% stun reduction, and horribly confused movement.

[BUG]

**Comment by Tarmunora** [comment]
Because of Reasons:tm: triplemeth only has an effect when you do not have regular meth in you. Pretty sure that was your issue as I could not reproduce this with only triplemeth

**Comment by Cthucky** [comment]
I thought that might be it but the lack of an effect persisted after the meth left my system and the triple meth remained.

**Comment by Tarmunora** [comment]
Triple meth does/should not remain after meth leaves your system
