### ISSUE TITLE
Fireball spell if hitting /obj/window/auto will spawn at you instead

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#16759]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. See picture (Cogmap 2 Net Cafe)
2. Stand at location of elemental
3. Shoot window that's destroyed
![image](https://github.com/goonstation/goonstation/assets/53062374/cd7e199d-7b8a-4fc8-bd13-6ba68caf150a)

### Expected Behavior

For fireball to appear at the window

### Additional Information & Screenshots

Seems it's for /obj/window/auto, but not /obj/window/auto/reinforced. See below for an example of where this doesn't happen
![image](https://github.com/goonstation/goonstation/assets/53062374/4d9b47cb-3bc7-4a3a-b906-4b24293d417c)

Also tested it, it's not caused by https://github.com/goonstation/goonstation/pull/16705

**Comment by pali6** [comment]
Window's bullet_act breaks the window which qdels it and moves it to null. By the time we are on projctile/on_hit the window is in null so in fireflash `range(radius, target)` will be `range(radius, null)` which is by BYOND interpreted as `range(radius, usr)` due to default arguments of range.

**Comment by pali6** [comment]
I feel like centering the fireflash on the projectile instead of on the atom hit should fix this.

**Comment by pali6** [comment]
Hm. It has the unfortunate side effect of centering the explosion on the tile *before* the target:
![image](https://github.com/goonstation/goonstation/assets/358431/edb60970-8f61-4ca6-9d04-93fae6828406)
Maybe I will make it so it uses the current behaviour if possible and falling back to this if the target is gone. (An alternative would be to get the projectile's direction and extrapolate the next step I guess?)
