### ISSUE TITLE
All nuke ops spawned naked in arrivals shuttle

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#16774]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

Not sure

### Expected Behavior

For round to be played as normal

### Additional Information & Screenshots

Nuke ops round that ended shortly after it started, not sure if an admin ended it or not. Apparently there was a runtime in the nuke setup?

Crew won, with operatives alive

**Comment by flappybatpal** [comment]
Null client on https://github.com/goonstation/goonstation/blob/master/code/datums/gamemodes/nuclear.dm#L185
