### ISSUE TITLE
Cyberlivers do not heal Tox when the organholder isalcoholresistant.

### ISSUE THREAD

**Issue by vode-code** [goonstation/goonstation#1677]
[BUG]

**Describe the bug**
When you have alcohol resistance, all the bad effects of on_mob_life of ethanol are prevented by an If checking for isalcoholresistant. One of the bad effects is multiple instances of liver_damage, which is a variable used to deal liver damage at on_mob_life. When you have a cyberliver, it does not deal damage, and has been recently changed to instead heal TOX based on that. It used to heal TOX independently of that, and would heal TOX when you were alcohol resistant. It no longer heals TOX when alcohol resistant, because alcohol resistance prevents all of the bad effects, including liver_damage.

**To Reproduce**
1. Have alcohol resistance.
2. Have a cyberliver.
3. Drink a few sips of bojacks.
4. Heal absolutely no TOX.

**Expected behavior**
After having sufficient ethanol, the cyberliver begins healing TOX on_mob_life.

**Additional context**
Ethanol code, which is also where cyberliver behavior is:
[https://github.com/goonstation/goonstation/blob/master/code/modules/chemistry/Reagents-Base.dm](https://github.com/goonstation/goonstation/blob/master/code/modules/chemistry/Reagents-Base.dm)

**Comment by vode-code** [comment]
@Tarmunora please fix what you broke.

**Comment by Tarmunora** [comment]
It inverts whatever liver damage you would have taken as tox healing. If you would take 0 due to alch resist, you get 0 tox healing.
