### ISSUE TITLE
Dispensary interlink sprite layers over darkness

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#16933]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Dispensary interlink is powered off
2. Lights nearby lose power (or maybe in the other order? not sure)

### Expected Behavior

For it to appear below darkness

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/53062374/e41c4f0e-a069-45ae-8265-6bfa95256170)

**Comment by pali6** [comment]
Unable to reproduce. Likely the fill_image's icon_state became `medchem-off` but I have no clue how.
