### ISSUE TITLE
Beepsky can handcuff people with no arms

### ISSUE THREAD

**Issue by Ormakent** [goonstation/goonstation#16946]
### Labels

[BUG]

### Description

title

### Steps to reproduce

I believe the person was katanad during the stun + cuff animation of beepsky.

### Expected Behavior

no arms = no cuffs

### Additional Information & Screenshots

![Screen Shot 2023-11-11 at 16 36 56](https://github.com/goonstation/goonstation/assets/35436986/6fce2b20-c8a1-4c17-a37d-1f6446a635d7)

**Comment by TealSeer** [comment]
Duplicate of #14411
