### ISSUE TITLE
Bee Protection

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1695]
[BUG]

**Describe the bug**
Bees defending the one who hatched them may bee broken

**To Reproduce**
1. Hatch a LOT of bees
2. get hit by monkey
3. bees dont sting

**Expected behavior**
bees should defend me

**Comment by Carbadox** [comment]
Isn't the requirement for bee protection be that you swallow and then "lay" the egg?

**Comment by RSG250** [comment]
even my bee i did that with didnt protect me.
