### ISSUE TITLE
Rad bow charge doesn't show

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#16957]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Buy traitor radbow I think? Either that or it was a spy claim reward
2. No charge, nor after firing it as it recharges

### Expected Behavior

For rad bow charge to show

**Comment by TealSeer** [comment]
Couldn't reproduce both as traitor purchase or spief reward

**Comment by FlameArrow57** [comment]
Still an issue, was having it not work for full charge overlay in game
