### ISSUE TITLE
health scanner upgrades not showing reagents.

### ISSUE THREAD

**Issue by Adharainspace** [goonstation/goonstation#1697]
[BUG]

**Describe the bug**
i tossed an upgrade in my scanner and it didnt show reagents when scanning. also didnt work for glasses. organ scan worked fine. i needed a reagent scanner to get more info than (20u rejuvinating chems)

**To Reproduce**
1. get health scanner
2. add upgrade
3. scan someone with stuff in them
4. get no reagent info

**Expected behavior**
get a list of reagents in em

**Screenshots**

**Additional context**

**Comment by GoldenKeyboard** [comment]
Strange question, but did you make sure the upgrade was actually enabled?

**Comment by Adharainspace** [comment]
> Strange question, but did you make sure the upgrade was actually enabled?

well i didnt know you could disable em i guess. but it also didnt work with my glasses, which i thought the upgrade enabled. i might be dumb though.

**Comment by Tiggersaurus** [comment]
The upgrade starts enabled when you plug it in, didn't even know you *could* disable it. I'll see if I can replicate this when online later, will test on human and Borg 💜

**Comment by Adharainspace** [comment]
this isnt a bug im just extra dumb

**Comment by GoldenKeyboard** [comment]
story of my life, no worries
