### ISSUE TITLE
Player vending machines can eat pda of the owner (with ID in them) when vending chute is open

### ISSUE THREAD

**Issue by NibChocolateeny** [goonstation/goonstation#16974]
### Labels

[BUG][MAJOR]

### Description

as the maker of a player vendor, if you accidentally click on the machine with your pda (with an id in it) while the product chute is loading, you lose the pda and nobody can close the chute afterwards

### Steps to reproduce

1. make a player vending machine and open it up with a screwdriver
2. make the vending machine yours with you pda+ID card (or maybe just Id, I am not sure!)
3. put things in it
4. accidentally put your pda with your id in as well, by mistake
5. realize that you can no longer change any of the values of the vendor, because you haven't got your id!
6. try to put in money so you can buy your id, but have your money get put into the list of items sold instead (chute is open, can't close it)
7. repeat process for anything else you try (screwdirvers to close the panel, other people's pdas - including the admins, so on)

### Expected Behavior

pda with owner ID in it is not able to be put into player vending machine sell list. eating everyones things is bad!

### Additional Information & Screenshots

I think zamujasa saw this in the game - they helped fix it for us. thank you Steph! :>
but I don't think it should happen to start with, its very confusing!

(I am not sure how it was fixed by admins. cutting wires with tools doesnt put them in the machine, but when i tried I couldn't close the chute that way. If there is in-game way to fix, then maybe this is not that bad?)

**Comment by MetricDuck** [comment]
By placing your ID in the vending machine you lose the ability to close the loading chute via the UI. If you can't close the loading chute you can't shut the panel with a screwdriver (as you'd place it inside instead). If can't shut the panel you can't actually vend anything.
