### ISSUE TITLE
TGUI chat TERMOS error

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#16983]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Not sure

### Expected Behavior

No term os error

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/53062374/cf4c7675-5790-4631-b546-bed51cd9a437)

Reconnecting fixes it

**Comment by CheffieGithub** [comment]
fixed by https://github.com/goonstation/goonstation/pull/16708/commits/d547cec2f750f880c98c0bf47ea17fd7c0e38b53 hopefully
