### ISSUE TITLE
mentor mice + PTL lasor

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1699]
[BUG]

**Describe the bug**
You were about to be transferred into another body, but that body was pending deletion! This may fuck everything up so if it does dial 1-800-CODER.

**To Reproduce**
1. spawn as mentor mouse on top of full power ptl

**Expected behavior**
the described bug  not to happen

**Comment by Xkeeper0** [comment]
I'm wagering this is because of a race condition:

* Choose to spawn in on top of the PTL
* New mob created
* PTL laser detonates new mob, `qdel`ing it
* Player transfers into the new mob (which is pending deletion)
* Problem
