### ISSUE TITLE
ghost critters no longer get more than 1 foodbuff per food item

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#17021]
### Labels

[BUG]

### Description

ok so ghost critter used be able max food buff from nibbling say bread (which normally gives 1 minute of extra 20 health) so it was like 9 minutes of it, however at some point something changed, now say you nibble the bread you get the noraml buff  length, the food item then just stops giving more of the buff, ever again to you.

### Steps to reproduce

1. be ghost critter (say space bux bird with 4 health standard)
2. nibble bread to so you survive being punched 1 single time to not die
3. be extremely sad the buff only lasts 1 and can never use the bread to get more buff ever again

### Expected Behavior

previous buff stacking behavor

### Additional Information & Screenshots

im looking thru the change log and i cant seem to find what changed this behavior??
am i blind?

side note: ive always personally found it saddening that the space bux ghost bird purchase only has 4 max health like??? why?
already limited to tiny items, and cant exhaust food items. why do bird have die in 1 punch :(

**Comment by Xkeeper0** [comment]
> side note: ive always personally found it saddening that the space bux ghost bird purchase only has 4 max health like??? why?
already limited to tiny items, and cant exhaust food items. why do bird have die in 1 punch :(

it's pay to wing not pay to win 😎

**Comment by pali6** [comment]
Not a bug.
