### ISSUE TITLE
Shocking Touch can hurt arcfiends??

### ISSUE THREAD

**Issue by NewyearnewmeUwu** [goonstation/goonstation#17020]
### Labels

[BUG]

### Description

Ei Nath, or at least the arc from it, can hurt arcfiends?.

### Steps to reproduce

1. Be arc
2. get hit by Ei Nath
3. take damage

### Expected Behavior

I expected this to not happen.

### Additional Information & Screenshots

Might be a fluke or smth IDK but I took damage at several points by being hit by the Shocking Touch. Intentional?

**Comment by frawhst** [comment]
Arcfiends aren't immune to all electricity, they basically just have SMES + baton immunity (ie tasers still work)
