### ISSUE TITLE
light/darkmode inconsistencies

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#17047]
### Labels

[BUG]

### Description

lightmode seems to not be working for some popups. chat is fine, and some menus (character setup for example) still work in lightmode

### Steps to reproduce

1. have darkmode off
2. open a list of some sort, hairs in this case
3. see issue

### Expected Behavior

lightmode be across all windows

### Additional Information & Screenshots

![Screenshot (381)](https://github.com/goonstation/goonstation/assets/73998720/b842afe4-7a81-4f7b-9b3f-b666e93aeb06)

**Comment by frawhst** [comment]
fixed in [a3f4f10](https://github.com/goonstation/goonstation/commit/a3f4f1053942c90c432410a9f3a8a9797d2c2457)
