### ISSUE TITLE
Door breaching rounds only cause a flashbang effect if going through a door

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17052]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Shoot door breaching round at a wall

### Expected Behavior

For flashbang effect to always happen

### Additional Information & Screenshots

Maybe this isn't a bug? Saw the effect was happening if it went through doors, but not any time else

**Comment by Tarmunora** [comment]
Not a bug, this is how they are meant to work
