### ISSUE TITLE
Law rack had two laws on clicking it while only having one law in it

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17064]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Law rack has one law in it maybe?
2. Ion storm happens
3. Click law rack to see current laws

### Expected Behavior

For only one law to be given back

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/53062374/4bef2025-ddd8-4508-82fb-aa5045e86953)

On Nadir

**Comment by amylizzle** [comment]
Not a bug, intended ion storm effect.
