### ISSUE TITLE
Unable to swim in spoilerzone pool

### ISSUE THREAD

**Issue by Dwezeldorf** [goonstation/goonstation#1712]
[BUG]

**Describe the bug**
While inside the secret VR adventure zone accessed from the space diner, after jumping in the pool using the diving board and letting the jump "time out" as opposed to selecting a location with the crosshair, you are unable to move at all.

**To Reproduce**
1. Enter the VR adventure zone.
2. Go to the pool and use the diving board, allowing the jump to time out.
3. Try to swim out of the pool.

**Expected behavior**
Being able to swim to the ladder and get out of the pool.

**Comment by DimWhat** [comment]
This pool is now liquids last I checked. I remember getting stuck there once and a few rounds later the pool was no longer a weird turf.
