### ISSUE TITLE
Syndicate hotbox lighter has no contraband value

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17134]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Wear sechuds
2. See someone holding syndicate hotbox lighter

### Expected Behavior

For contraband flag to show

**Comment by MeggalBozale** [comment]
![image](https://github.com/goonstation/goonstation/assets/27376947/4adb6189-8e47-426a-be47-cb5e77957005)
Sov weighed in that this does not really need a contra value, I think? I think. If not I'll open a PR giving it some value since it's just a one-liner

**Comment by imawxome** [comment]
it really is just an extra hot lighter, no reason that it should be "illegal"
