### ISSUE TITLE
TGChat: Custom text highlight color automatically resets to yellow unprompted

### ISSUE THREAD

**Issue by trollbreeder** [goonstation/goonstation#17145]
### Labels

[BUG][MINOR][UI]

### Description

When changing the color of a text highlight in TGChat, after a few seconds it resets back to #ffdd44 (default yellow color), even after saving.

### Steps to reproduce

1. Open TGChat settings
![image](https://github.com/goonstation/goonstation/assets/25937686/dfd6c671-2a25-4d02-947f-ce831b603506)
2. Change the color of a highlight
![image](https://github.com/goonstation/goonstation/assets/25937686/6e970902-a918-42c9-9462-49fb1db10c45)
3. Wait roughly 10 seconds. You can do anything or nothing while waiting, even saving.
4. Click a TGUI element.
5. The higlight's color that you changed resets back to its default of #ffdd44
![image](https://github.com/goonstation/goonstation/assets/25937686/3bfea766-5d9d-4dd5-a74d-02fce87935cb)
 

### Expected Behavior

I expected that the new color I gave the text highlight remains there when I don't edit it, and does not get reset to yellow.

**Comment by pgmzeta** [comment]
tgchat unmerged
