### ISSUE TITLE
Ice spider table pathing is broken

### ISSUE THREAD

**Issue by qrqwerqwr** [goonstation/goonstation#1727]
[BUG]

**Describe the bug**
Ice spiders will attempt to path under tables, but they are unable to actually pass under them. This causes the spiders to run against tables until they are killed.

**To Reproduce**
1. Spawn ice spiders
2. Watch as your plan is foiled by a table

**Expected behavior**
IIRC, baby spiders still have the tablepass flag, and should be able to walk under tables. Adult spider shouldn't be able to, for balancing purposes

**Comment by amylizzle** [comment]
Verified, but I think the best fix would be to re-do spiders as mobcritters because currently they `/obj/critter` and that is bad.

**Comment by amylizzle** [comment]
https://github.com/orgs/goonstation/projects/6/views/1
