### ISSUE TITLE
Broken botany sprite

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1728]
[BUG]

**Describe the bug**
The plant styreline rocstal gives a Fix This Shit image.
**To Reproduce**
1. Get strange seed styreline (I assume that's where it's from)
2. Splice with something, not sure what it was spliced with.
3. See sprite error

**Expected behavior**
The get a plant image.

**Additional context**
I assume this is the same issue the other plant sprites have been having with splices?

**Comment by Tiggersaurus** [comment]
Adding: This is a Houttuynia C Cataria plant. has fix this shit sprite

**Comment by ZeWaka** [comment]
pooling issue fixed this
