### ISSUE TITLE
Dual Monitor clicking off

### ISSUE THREAD

**Issue by halloaki** [goonstation/goonstation#1729]
[BUG]

**Describe the bug**
When you click, it will click around 3 tiles under you. The game mouse input is based on my second screens resolution instead of my first one. How do I know? Playing the game in my second screen is fine but my first screen it clicks around 3 tiles under where i click(based on ingame medbay tiles...).

**To Reproduce**
I have absolutly no clue, I have a dual monitor settup but 1 screen is bigger than the other

**Expected behavior**
Start game in first screen, play game, clicks click where they click not 3 tiles under

**Screenshots**
Game in second monitor: https://i.imgur.com/DK8UTq5.gif
Game in first monitor (furious clicking to find spots): https://i.imgur.com/NfP1MeQ.gif

**Additional context**
The game worked fine this morning but now its fucked. Tried on TG, worked fine. This seems only to happen on goon RP servers

**Comment by halloaki** [comment]
Update:

What Have I tried so far?
*Basic reconnect
*Restart + force close with task manager
*Unplugging second monitor, starting game

All of these don't solve the solution.

I want to note that I can use the inventory and UI. right clicking is also completely synced with the game. Just the left click is fucked and seems out of sync.

My only solution is to play on my second monitor it seems, which is odd.

Primary screen is : 1980x1080
second screen is: 1680x1050

I did the extra mile and recorder what I get during game play on both screens, hopefully this helps. (Keep in mind this game worked for me perfectly from 10 AM to 1 PM GMT+1 but completly fucked at midnight, incase an update came out idk)

Video: https://youtu.be/ET0MVSszeKM (no clue why youtube gives me .be links but i kinda like it as a belgian)

**Comment by ZeWaka** [comment]
this is really weird.... are you using WINE or something?

**Comment by halloaki** [comment]
> 
> 
> this is really weird.... are you using WINE or something?

No, I am using Windows 10, not a Mac or Linux.

The problem got fixed it seems after i restarted my PC with my second monitor unplugged, and then plug it back in once completely restarted though.

**Comment by Carbadox** [comment]
This doesnt look like its a problem with SS13 or even BYOND plus its even "fixed" for 2 weeks now. I'll close this
