### ISSUE TITLE
Donut 3 upload turrets destroy upload door.

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1730]
[BUG]

**Describe the bug**
Bumbled around as I do as mentor mouse, wandered into the upload on donut 3 and saw the turrets were set to lethal. They fired once and destroyed the door.

**To Reproduce**
1. Enter the AI upload when turrets are set to lethal
2. Get the to trigger
3. Watch door possibly be destroyed.

**Expected behavior**
For turrets not to rek their own doors. With the door destroyed the turrets can reach the outer door. I mean, the turrets shouldn't have been on lethal anyway but ehh.

**Comment by pali6** [comment]
@Tenryumi

**Comment by ZeWaka** [comment]
fixed this i think, reopen if not
