### ISSUE TITLE
Metal Foam eats (explosive) projectiles (and cause no explosion)

### ISSUE THREAD

**Issue by 444Portal** [goonstation/goonstation#17319]
### Labels

[BUG] [MAJOR]

### Description

Metal Foam seems to have some special logic where it gets hit with something and deletes that and itself, I'm not sure if this is actually what's going on though, but, explosive projectiles do not cause an explosion and just vanish when hitting the foam

### Steps to reproduce

1. Find a spare RPG 
2. ..and find some metal foam
3. Aim & Shoot!
4.  No explosion

### Expected Behavior

for the explosion to happen like normal

### Additional Information & Screenshots

Before: 
![image](https://github.com/goonstation/goonstation/assets/76797216/3c730c63-cff9-40fb-bacc-8baa5cfa250c)

After: 
![image](https://github.com/goonstation/goonstation/assets/76797216/b3fbe2bb-39c3-42c7-bf2e-41a5f92ebd06)

**Comment by pgmzeta** [comment]
the metal foam disposes itself before the projectile can get the turf its on, causing the rocket to do nothing

* metal foam code: https://github.com/goonstation/goonstation/blob/121a99201aaa055be2a6c7266457c6768f469eac/code/obj/foamedmetal.dm#L46-L47
* MPRT projectile code: https://github.com/goonstation/goonstation/blob/master/code/modules/projectiles/bullet.dm#L1403-L1405
