### ISSUE TITLE
Misspelled 'completely' as 'complitely' in the admin interaction menu

### ISSUE THREAD

**Issue by 444Portal** [goonstation/goonstation#17321]
### Labels

[BUG] [TRIVIAL]

### Description

admin interacting/'what do' menu has a typo

### Steps to reproduce

1. Find a door
2. `+click it 
3. Scroll down
4. Read typo

### Expected Behavior

for there to be no typos 

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/76797216/2bfb85ca-af05-4b15-a12e-8a271af427c0)

**Comment by Vaskritaya** [comment]
The typo is intended, it's an old injoke.

**Comment by TealSeer** [comment]
intended
