### ISSUE TITLE
Headspider not happening

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#17342]
### Labels

[BUG]

### Description

I saw a changeling die with enough points to headspider, but they became a ghost instead with their hivemind attached to the headspider

### Steps to reproduce

1. Be a changeling
2. Eat some people
3. Die horribly
4. Headspider, but actually become a ghost
5. I tried transferring them into the headspider manually but then when they infected someone the headspider died and that person got changeling powers???

### Expected Behavior

A headspider is released normally

### Additional Information & Screenshots

I hate headspider code

**Comment by TobleroneSwordfish** [comment]
may be fixed by [aef5f78](https://github.com/goonstation/goonstation/commit/aef5f7822531a2f998ee86a2b65888d6a644ef8b)

**Comment by gear-space** [comment]
Ayy, it's me, the surprise changeling! From my side what I saw in the logs below. I became a changling with the popup and everything, a lot of people in my hivemind, and no DNA points (I think, or at least not enough to shamble).
```
The headspider crawls down Experiment 626's throat!
You feel something pushing at your spine...x2
You feel unusually sober.
We have assumed control of the new host.
......
DEAD: ADMIN(LeahTheTech) says, "Yeah I'm really not sure what happened with the headspider but none of it was intentional"
```

**Comment by TobleroneSwordfish** [comment]
We'll assume it did fix it then
