### ISSUE TITLE
Disappearing PTL beam

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1742]
[BUG]

**Describe the bug**
explosions permanetly destroy a ptl beam segment (at least on cog2)

**To Reproduce**
1. set ptl to max
2. detonate some corpses

**Expected behavior**
it not to disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/89690877-948b1d00-d8d5-11ea-82f3-7eb2e1b19332.png)
![image](https://user-images.githubusercontent.com/63602513/89690885-98b73a80-d8d5-11ea-9862-71db7050416f.png)

**Comment by pali6** [comment]
Fixed by 5a743ab
