### ISSUE TITLE
Stealth storage has radbow charge overlays

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17457]
### Labels

[BUG]

### Description

Stealth storage box can have radbow charge overlay

### Steps to reproduce

1. Use stealth storage to copy appearance of radbow that has full charge
2. Use reset verb on stealth storage
3. Keep stealth storage box as-is, or swap its appearance to something else

### Expected Behavior

For the stealth storage to not have radbow overlay

**Comment by MeggalBozale** [comment]
![image](https://github.com/goonstation/goonstation/assets/27376947/b035af22-4a14-41e4-8a4e-f2a5e25ef736)
lol yea
