### ISSUE TITLE
Guardbuddies don't arrest people set to arrest

### ISSUE THREAD

**Issue by Vincent983** [goonstation/goonstation#17468]
### Labels

[BUG][MAJOR]

### Description

Guardbuddies don't arrest people set to arrest.

### Steps to reproduce

1. use the patrol_script command to deploy a guardbuddy
2. set someone to arrest
3. they don't get arrested by the guardbuddy

### Expected Behavior

They should get arrested by the guardbuddy.

### Additional Information & Screenshots

Securitrons were identifying and arresting the marked subject normally unlike the guardbuddies.

**Comment by Chatauscours** [comment]
Iirc that might be intended since guardbuddies are part of sci and not sec.

**Comment by Vincent983** [comment]
https://gyazo.com/5b3fdb99de7c1e5b76679313eb970a17

**Comment by Vincent983** [comment]
![image](https://github.com/goonstation/goonstation/assets/124026007/073b0896-79c1-44c0-9688-80e57568040b)
according to the code comments, patrol_script is supposed to make the guardbuddy emulate a secbot

**Comment by Vincent983** [comment]
nevermind,  I code dived and guardbuddies are dumb  and stupid
