### ISSUE TITLE
Guardbuddies don't pathfind to their docking station if they're too far away.

### ISSUE THREAD

**Issue by Vincent983** [goonstation/goonstation#17472]
### Labels

[BUG]

### Description

A guardbuddy that has been recalled will get the recall command, but if it's too far away it just sits there instead of going to the dock.

### Steps to reproduce

1. Recall active guardbuddy that is far away
2. Guardbuddy receives recall command, stops moving, and sits there until  someone drags them closer to the dock they're supposed to go to

### Expected Behavior

They should be able to pathfind back to their dock if they're able to receive recall commands.

### Additional Information & Screenshots

The approximate distance at which they don't get recalled is 20-30 or so tiles?

**Comment by ZeWaka** [comment]
feature request
