### ISSUE TITLE
Invisible fire elemental

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17512]
### Labels

[BUG]

### Description

A fire elemental became 100% invisible, not revealed by stuns

### Steps to reproduce

Not sure

### Expected Behavior

No invisible fire elemental

### Additional Information & Screenshots

Happened in a round that ended a few minutes before this report was made

Didn't check if thermals would work, but assuming not, since they weren't being revealed by stuns or bullets

**Comment by Tarmunora** [comment]
transparium issue, fixed
