### ISSUE TITLE
Error when opening empty stocking

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#17511]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Click on empty stocking

### Expected Behavior

No chat error

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/53062374/4fd53074-2410-4b82-9442-93b1728ca029)

**Comment by Tarmunora** [comment]
If you had already gotten something from the stocking, then the message wasn't in error, now was it?

**Comment by FlameArrow57** [comment]
Oop, misread
