### ISSUE TITLE
Restarting/reconnecting the client switches back from TG controls to goon controls every time

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#1756]
[BUG]

**Describe the bug**
Title

**To Reproduce**
1. Have TG controls enabled
2. Restart/reconnect the game
3. Notice that your controls setup has changed back to goon controls
4. Scream

**Comment by moonlol** [comment]
did you save your character profile after changing?

**Comment by TTerc** [comment]
I did. There is also another problem with ALL the menu settings changing back to default after joing another ss13 server. But it's just the controls setup that changes after each reconnect/restart

**Comment by pali6** [comment]
Possibly fixed by `src.mob.reset_keymap()` into client/New (after tg_controls is set).

**Comment by TTerc** [comment]
Yep, I did some testing and the issue seems to have disappeared, which I'm glad about!

I guess I'll just close it then
