### ISSUE TITLE
Mining Oupost - Mining Gizmo Not Functional?

### ISSUE THREAD

**Issue by LHex01** [goonstation/goonstation#1757]
Right so, according to [this wiki page](https://wiki.ss13.co/Mining_Outpost) after setting up the mining magnet, I'm supposed to hit the magnet chassis and then the lower left corner of the magnet square area with the mining gizmo. Though hitting it with said tool doesn't really work, no text informing some sort of linking. And after attempting to activate the magnet there isnt any clearance, even though there is. Am I missing a few steps or this feature _deprecated_ and no one really cared to update it?

_I have reasons why I rather work at the mining outpost don't shame me_

**Comment by BatElite** [comment]
Did you by any chance hit the catwalk in lower-left corner? Because for the gizmo to work you need to hit the lower-left tile of space inside the frame instead. The in-game messages for the gizmo state that more clearly than the wiki does.

**Comment by LHex01** [comment]
Ah, thanks mate.
