### ISSUE TITLE
Cyborg module rewriter interface isn't found

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#1760]
[BUG]

**Describe the bug**
The module rewriter is unusable because an interface isn't found.

**To Reproduce**
1. Use the module rewriter
2. Get a window with "Interface CyborgModuleRewriter was not found."

**Expected behavior**
For whatever fancy UI it got recently to load.

**Additional context**
It's only failing on the server it seems (tested on LRP), it shows up fine on local.

**Comment by BatElite** [comment]
@mordent-goonstation I think this might be in your ball park?

**Comment by mordent-goonstation** [comment]
Kinda sorta. It appears to be an issue with the latest files not being provided by the CDN despite being in the right place on the `master` branch, so outside of my area to fix but the relevant nerds have been prodded.

**Comment by mordent-goonstation** [comment]
Solved by some CDN fixes.
