### ISSUE TITLE
Lings fail hijack for spawning limb critters(?)

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#17613]
### Labels

[BUG] [MINOR]

### Description

A ling that kills and/or absorbs everyone but has critters on the shuttle of their own loses hijack

### Steps to reproduce

1. Ling with hijack
2. Escape with limbcritters
3. Fail objective

### Expected Behavior

Ling critters dont count as other people

### Additional Information & Screenshots

There was also a linged corpse on the shuttle along with a newly made eyespider. Not sure which of those counted.
![image](https://github.com/goonstation/goonstation/assets/27376947/bd971aed-6784-4ff8-b772-0db436d74d6a)

**Comment by TobleroneSwordfish** [comment]
Should be fixed in #18222
