### ISSUE TITLE
Giving item spam

### ISSUE THREAD

**Issue by BinaryGears** [goonstation/goonstation#17632]
### Labels

[BUG] [REQUEST]

### Description

Spaming give item causes user UI to overflow with request

### Steps to reproduce

As explained to me by the person that kept spamming it all round:
1. Have an item.
2. Use the "SPACE" + "CLICK" shortcut to offer to pass item to individual.
3. Keep doing step 2 many times really quickly.
4. As the person who this is being done to, you will get a warning message that the UI has encountered some type of error. 
5. Profit for the troll who kept doing to people all round. 

### Expected Behavior

I would expect that there would be some form of cool down or inability to try to pass an item until the other user has declined/accepted or message has timed out.

### Additional Information & Screenshots

I should have grabbed screenshots but did not think to, although this should be very easy to replicate with 2 users. 
I am not sure if the person doing this was using some kind of external macro, or just clicking really fast.

**Comment by pgmzeta** [comment]
#18434
