### ISSUE TITLE
You burst out of the blood-stained oily frog jumpsuit!  Your leg muscles shrink back to normal.

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1772]
[BUG]

**Describe the bug**
Oh god why

**To Reproduce**
1. Wear frog jumpsuit
2. Become fat
2b. in that order
3. AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Expected behavior**
that not to happen

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/89824999-f049e600-db21-11ea-8643-c81728fe7d54.png)

**Comment by pali6** [comment]
Hm I don't get why that happens. The suit should just give you an ability. Maybe bioholder rebuilds something. But even that shouldn't matter. 💀
