### ISSUE TITLE
New borg/drone bulb tool

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#1775]
[BUG]

**Describe the bug**
Sometimes when fitting the light, it inserts it but the colour does not change e.g. to purple.

**To Reproduce**
1. Be engi or civi borg
2. Use bulb tool on light fixture that has a bulb in already
3. Sometimes the bulb fits but doesn't change colour

**Expected behavior**
To be able to line the station with purple bulbs >.>

**Additional context**
I haven't found out any correlation for bulbs that work and those that don't. If you add another colour after it sometimes fixes it but not always ..

**Comment by BatElite** [comment]
If anyone goes to fix this before I do, the problem is in the queue process for lighting (look for "dirty_flags & D_COLOR") setting queued lights to bright white instead of the intended colour. I haven't figured out a good fix for it yet.
