### ISSUE TITLE
ThinkDOS SigCatcher currently Useless

### ISSUE THREAD

**Issue by MarkNais** [goonstation/goonstation#1783]
[BUG]

**Describe the bug**
SigCatcher never caught any packets over the wire. Map was Oshan, computer in the AI upload foyer, connected to the PNet grid.

**To Reproduce**
1. Login and launch SigCatcher
2. Set it to "on" (or auto)
3. Never catches anything, despite my PNet comp showing lots of traffic.

**Expected behavior**
Shows at least mainframe pings.

**Comment by amylizzle** [comment]
It's because this is a wireless terminal, despite the data terminal connector underneath it.
