### ISSUE TITLE
Crotch in server chat (not sent by player)

### ISSUE THREAD

**Issue by VibratingLizord** [goonstation/goonstation#17898]
### Labels

[BUG]

### Description

I see the word crotch in a server message (not player)

### Steps to reproduce

1. Eat organic jelly bean
2. See this (RNG based I believe) 
![Screenshot 2024-01-24 152420](https://github.com/goonstation/goonstation/assets/159331648/71a13266-24cd-4bc9-9093-7159393d7db7)

### Expected Behavior

I expected to not see crotch

### Additional Information & Screenshots

i did not want to see crotch on my family friendly goonstation

**Comment by frawhst** [comment]
<img width="625" alt="image" src="https://github.com/goonstation/goonstation/assets/67879783/ee06a249-d4d1-457e-965d-87149194b1a6">
what

**Comment by TobleroneSwordfish** [comment]
fixed 💀 https://github.com/goonstation/goonstation/commit/b8220a6782db2d8350653f67c5f20510a0c19354

**Comment by VibratingLizord** [comment]
thank you

**Comment by TheTyrant25** [comment]
bug hall of fame
