### ISSUE TITLE
Wizard random-name being too long to be submitted by player

### ISSUE THREAD

**Issue by IPling** [goonstation/goonstation#17904]
### Labels

[BUG]

### Description

A wizard round-start random-name called ''Vermoulian the Dream-Walker'' was generated, but the name is too long to actually use.

### Steps to reproduce

1. Spawn as wizard
2. Get lucky enough for ''Vermoulian the Dream-Walker''
3. Too long to submit

### Expected Behavior

I expected that I should be able to accept the name.

### Additional Information & Screenshots

We could also nuke ''Vermoulian the Dream-Walker''.

![image](https://github.com/goonstation/goonstation/assets/137294088/ef335ce5-6dda-4a6d-9679-4e7ab87ee52a)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/258249ddd047cbb9be4eebbf254d82995b8f31fd
