### ISSUE TITLE
Plasmastone / other gas-releasing mats do not respect blocking objects when releasing gas

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#17911]
### Labels

[BUG] [MINOR]

### Description

Gas-releasing material in enclosed spaces will release gas outside when triggered

### Steps to reproduce

1. Wall off plasmastone
2. Trigger gas release
3. Notice plasma outside of container
4. Your immersion is ruined

### Expected Behavior

Gas releasing materials do not release gas outside of such an enclosement

### Additional Information & Screenshots

![dreamseeker_RreN5DqH0e](https://github.com/goonstation/goonstation/assets/27376947/354d5a58-8c58-44fb-999d-cfe04aec5276)

**Comment by Tarmunora** [comment]
plasmastone by design releases plasma in a 3x3 centered around it to speed things up
