### ISSUE TITLE
Reinforcing flooring clears gas overlays

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#17910]
### Labels

[BUG] [TRIVIAL]

### Description

Plating flooring using rods removes the gas overlay
### Steps to reproduce

1. Get a floor without the floortile on it (Floor plating) which is simulated, e.g. with plasma or some other distinctly visible gas
1.5 (optional) do it in a 1x1 room so it's more obvious
2. Reinforce the floor using rods of any material
3. Notice gas overlay is gone
4. Be sad

### Expected Behavior

Reinforcing floors preserves gas overlay

**Comment by Tarmunora** [comment]
Visual error only - the gas is still present, only the overlay is gone

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/739372d9843218df207f90799d1364ae38082f38
