### ISSUE TITLE
Wizards that obtain spells from VR, also obtain them outside of VR, allowing for infinite spells.

### ISSUE THREAD

**Issue by IPling** [goonstation/goonstation#17923]
### Labels

[BUG][MAJOR]

### Description

A wizard entering VR, going into killbox and picking up a nother spellbook. Each purchase made in the spellbook doesnt give the VR character its spells, but when VR is left all of the purchased spells were given to the real-life wizard.

### Steps to reproduce

1. Be wizard.
2. Teleport to arcade and enter VR
3. Go into murderbox
4. Pick up WIZARD.EXE
5. Use spellbook to obtain spells
6. See spells werent given to VR character
7. Exit VR
8. See the spells given to the real-life character
9. Destroy the crew now that you are unstoppable

### Expected Behavior

That the purchased wizard spells in VR, stay in VR.

### Additional Information & Screenshots

This can allow a wizard to obtain all spells in the spellbook in seconds of a round starting, how did nobody find this sooner?

**Comment by pgmzeta** [comment]
Repercussion of antagonist `datum`-ization.
