### ISSUE TITLE
Goonhub Maps are all blank

### ISSUE THREAD

**Issue by 444Portal** [goonstation/goonstation#17956]
### Labels

[BUG] [MAJOR]

### Description

Any map (example: https://goonhub.com/maps/donut3) shows up completely blank, with nothing on it but the default space background.

### Steps to reproduce

1. See APIv2 News
2. Head to https://goonhub.com/maps/donut3
3. See a lack of Donut 3
4. Cry

### Expected Behavior

Expect to see the maps

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/76797216/eaa5cec9-0c51-4b46-9267-ce029f1cd25a)
![image](https://github.com/goonstation/goonstation/assets/76797216/4a0fed76-f002-402a-9400-279a1802dd1f)

**Comment by Wirewraith** [comment]
Fixed
