### ISSUE TITLE
Rev gibwave doesn't happen

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#1796]
[BUG]

**Describe the bug**
At around 35-45 minutes (i forget which), Centcomm should send a message about revolutionary activity being detected on station.  Some time after that (usually around 50-55 minute mark IIRC), Centcomm should send a message about the revheads being identified and then everyone explodes.

**To Reproduce**
1. Be in a rev round.
2. Have the revs not do anything for some boneheaded reason.
3. Watch the round hit 70+ minutes.
4. Pray to the admins for salvation in the form of fiery death.

**Expected behavior**
Everyone go boom if revs are lazy.

**Additional context**
Centcomm doesn't seem to be autocalling the shuttle on gang either, which could be related.  Maybe the call isn't related to shift time but rather a certain number of ticks in the life loop?  Could also explain mapvote going on for too long.

**Comment by zjdtmkhzt** [comment]
I know for a fact that recently (less than 1 week ago, I think) we had a rev round that ended with everyone being gibbed at the 50 (?) minute mark or something.
Can't remember if there was a warning message before though, I can't remember seeing one and most other people seemed quite surprised by the gibbing as well.

**Comment by pali6** [comment]
Unable to replicate. Could be delay due to lag somehow? Or a runtime somewhere?
