### ISSUE TITLE
Ghost Critters teeny tiny hammer

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#1798]
[BUG]

**Describe the bug**
ghost critters with hands such as space mouse can hold the teeny tiny hammer
this is bad cause the teeny tiny hammer does 5 damage
**To Reproduce**
1. pick up hammer at ship alert button
2. you now have 5 damage

**Expected behavior**
not have that happen

**Additional context**
can also break the button glass.

**Comment by pali6** [comment]
rip critters activating the station alert
