### ISSUE TITLE
Mail Mislabeling in Vending Machines

### ISSUE THREAD

**Issue by WillHuff** [goonstation/goonstation#17986]
### Labels

[BUG]

### Description

Mail placed in vending machine appears as belonging to someone else from the same department

### Steps to reproduce

1. Place mail into vending machine, mail shows up under an individual's name
2. Mail dispensed belongs to one of their colleagues from the same department 

### Expected Behavior

I expected mail to show up in the vending machine with the correct name

**Comment by pgmzeta** [comment]
#21647
