### ISSUE TITLE
[BUG]Mining magnet on the mining station doesn't work after setup

### ISSUE THREAD

**Issue by gurking** [goonstation/goonstation#1800]
**Describe the bug**
The mining magnet on the mining station (Atlas) doesn't work after setup. It displays this message: "Uh oh, something's gotten really fucked up with the magnet system. Please report this to a coder!"

**To Reproduce**
1. Setup the magnet
2. Open the interface
3. Retrieve an asteroid

**Expected behavior**
An asteroid appears

![magnet](https://user-images.githubusercontent.com/18533061/90047656-8de41780-dcd2-11ea-8273-ad3541b969f4.png)

**Comment by Mysteryman64** [comment]
So, just as a potential work around. You can force it to still pull an asteroid by toggling the Automatic Mode until it starts pulling one in, and then toggling it back off. 

I haven't had a chance to test whether it works with Quantum Telescope locations though.

**Comment by RSG250** [comment]
a little insight into this from my experience, 
the mining outpost magnet does not function as it normally should if the the Station Z level does not have a Mining Magnet, such as Atlas.  

As mentioned above a way to get around this is to set it to automatic mode.

the magnet at the outpost has NEVER worked with QT roids from my understanding as well.

**Comment by pali6** [comment]
Fixed by a recent commit that I'm too lazy to dig up.
