### ISSUE TITLE
Infinite broken tiles and toolbox

### ISSUE THREAD

**Issue by Monoblaster** [goonstation/goonstation#18008]
### Labels

[BUG][MINOR]

### Description

You can create a tiles and toolbox by adding floor tiles to it's inventory wether you want to or not. After that you wonder where your actual toolbox is after putting yourself in a pile of tiles and toolbox.

### Steps to reproduce

1. Get a empty blue toolbox and floor tiles
2. Open the toolbox's inventory by clicking it
3. Add the floor tiles to the toolbox's inventory by clicking a inventory ui space with the floor tiles in hand
4. See that a tiles and toolbox was made on the floor and your toolbox is gone
5. Notice the inventory is still open with the floor inventory ui
6. Make many broken tiles and toolbox by adding floor tiles to this inventory

### Expected Behavior

I am able to add floor tiles to my toolbox

**Comment by TobleroneSwordfish** [comment]
Fixed in ad91fe3
