### ISSUE TITLE
Goonstation doesn't seem to track any round progression or game activity to player account

### ISSUE THREAD

**Issue by Virel** [goonstation/goonstation#18036]
### Labels

[BUG][MAJOR]

### Description

After starting playing again this past weekend, the game seems to not count any sort of statistic of rounds completed or even time played. Spacebux are shown to be earned at end of round, but not banked for use, and goonhub shows 0 rounds and time played. As a result, cannot select roles that are based on number of rounds played, such as team antagonists, security officer, and so on.

### Steps to reproduce

1. Join Goonstation server as player "Virel"
2. Complete a round, whether declared ready before round start or as late-join
3. Receive end of round stats, payout, etc
4. Continue to next round, no spacebux available.
5. Check goonhub - player stats all at 0, except for deaths.

### Expected Behavior

Accurate tracking of player account activity based on time in game.

### Additional Information & Screenshots

The BYOND account used is over a decade old, dating back to 2012. I've also been informed of a recent API overhaul, so perhaps the account is just sort of invisible to the game for tracking purposes.

**Comment by Wirewraith** [comment]
This should be resolved now. Please re-open a ticket if the issue presents again.
