### ISSUE TITLE
Donut 2 south solars room is fullbright for no discernable reason

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#18056]
### Labels

[BUG] [Trivial]

### Description

The room for solars in donut 2 is fullbright like every time and its wierd

### Steps to reproduce

1. Load up donut 2
2. go to solars
3. its really bright
4. be confused

### Expected Behavior

Room is not infinity lumens

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/27376947/f4ad2d88-3b03-4619-b79d-c74ccd77589b)

**Comment by Sord213** [comment]
![Screenshot_831](https://github.com/goonstation/goonstation/assets/71185626/aae2a57a-b352-4f19-867f-818dcd011691)
Looks fine on my local and the live servers.
