### ISSUE TITLE
The Artifact Lab pitcher is mostly pointless

### ISSUE THREAD

**Issue by darkChozo** [goonstation/goonstation#1812]
[BUG]

**Describe the bug**
The pitcher in artlab lets you throw an object at a speed determined by the pitcher's power setting. However, the force stimulus provided to an artifact by a thrown object is determined by that object's thrown damage value, not its speed. For artifact research, this makes the pitcher pretty pointless, since it doesn't really do anything that you couldn't do with your arms.

Aside from being rather misleading (I spent a fair bit of time playing around with the power setting trying to get artifacts to activate), this also makes force-triggered artifacts rather difficult to activate, since they'll frequently need a 15+ damage object to do so (the possible stimulus range looks to be 3-30).

**To Reproduce**
1. Obtain a force-triggered artifact.
2. Change its required stimulus to 11 (vars > artifact > triggers > the force trigger > stimulus_amount)
3. Load a 10 damage fire extinguisher into the pitcher and fire it at the artifact at 100 power. The artifact shouldn't activate.
4. Change stimulus_amount to 10.
5. Fire the extinguisher at the artifact at 1 power. The artifact should activate.
6. Repeat the above tests with regular throwing, and observe the same results.

**Expected behavior**
The pitcher should allow you to provide a controlled stimulus to artifacts, like the other artlab gadgets.

**Additional context**
Discovered this by playing around with artifacts on a local server and by peeking through the codebase.

**Comment by RSG250** [comment]
Ive never had luck with the pitcher, to the point i resort to using potassium explosions in the test chameber to activate force activaed arts

**Comment by darkChozo** [comment]
As far as I can tell force activation is largely tied to how much damage you can do in one hit with a thing, which in practice means that you need explosives/actual weapons a lot of the time. IMO that's not necessarily a bad thing, but it isn't super obvious from in-game/wiki sources.

**Comment by zjdtmkhzt** [comment]
Using the pitcher should definitely be more effective than just bashing the object with a fire extinguisher, though, we should change this.

**Comment by pali6** [comment]
IIRC the pitcher changes the wrong parameter of throwing things. Instead of changing the strength of the throw it changes the range or something like that. (At least that's what Azungar said like 8 months ago, not sure if he fixed it back then.)

**Comment by darkChozo** [comment]
The pitcher throw changes the [speed and range](https://github.com/goonstation/goonstation/blob/a5c08aadc7902717f1aa840b538185d878d7f67e/code/modules/networks/computer3/mainframe2/misc_terms.dm#L3761) of the throw, while the artifact checks the [item's throwforce](https://github.com/goonstation/goonstation/blob/42b63693c09ea5dd2f407074089ebe239a4cf521/code/obj/artifacts/artifacts.dm#L140), which seems to just be a static damage number. I didn't actually see a way to throw an object harder/more forcefully (presumably so people don't get instagibbed by toolbox cannons), so I'm guessing that the easy solution is just to change artifacts so they consider speed as a component to a force stimulus.

**Comment by Tarmunora** [comment]
I'd say to let the pitcher add temporary throwforce a la rock-it launcher - if people want to make toolbox cannons with a device that launches a single item at a time and needs to me manually loaded (I think), let them imo
