### ISSUE TITLE
Achilean MLM pride flag mitosis

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#18151]
### Labels

[BUG]

### Description

INFINITE GAY PEOPLE EVERYWHERE FOR FREE

### Steps to reproduce

1. Acquire a folded up Achilean MLM Pride Flag (other MLM flag doesnt work)
2. click on wall with flag
3. Flag is cloned to wall, still folded, not deleted from your hand
4. see attached image

### Expected Behavior

I expected the flag to disappear from my hand and appear on the wall unfolded.

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/100481985/92040897-d0ff-41aa-87eb-767150fcbce0)

**Comment by DisturbHerb** [comment]
lol
