### ISSUE TITLE
Magnesium has behaviors it shouldn't according to the wiki. Also burns infinitely with no effect.

### ISSUE THREAD

**Issue by ghost** [goonstation/goonstation#1815]
[BUG]

**Describe the bug**
The root of the bug is that magnesium should not make a pile unless 10 units are present. When oldsmoked, the entire affected area is covered in magnesium piles. When those piles are lit they burn infinitely with little to no effect. For some reason, adding magnesium to a hellsmoke mix makes it affect a larger radius.

**To Reproduce**
1. Heat 90u of magnesium in a beaker
2. add aerosol(oldsmoke)
3. wait a second or two for all the piles to appear
4. repeat with 40u phlog and 50u magnesium
5. stand on the burning magnesium and note that it does nothing

the fires should appear only after step 4. they may also appear underground(not sure why on this one)

**Expected behavior**
I expected it to maybe make the hellsmoke a bit hotter and give more of a burn, maybe it would leave behind one or two piles that would burn and deal damage. I wasn't really sure

**Screenshots**
Video demonstration of a sample hellsmoke mix with magnesium.
https://discordapp.com/channels/182249960895545344/383743035894267905/744065899589271604
note the fire under the lattices is the magnesium piles that are on fire. They persisted for at least 5 minutes plus however long it took for me to type this out.

**Additional context**
Very destructive and fun hellmix.

**Comment by flappybatpal** [comment]
The burn behavior seems normal.

**Comment by amylizzle** [comment]
Bug no longer present.
