### ISSUE TITLE
Clarion Anti-Bio crate has armory requirement despite not being in armory.

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#18181]
### Labels

[BUG]

### Description

Clarion Anti-Bio crate has armory requirement despite not being in armory.

### Steps to reproduce

1. Set the map to clarion
2. Have all access
3. Attempt to open anti-biological crate
4. Access denied

### Expected Behavior

Crate should unlock

**Comment by 444Portal** [comment]
This is normal and isn't a bug afaik. It's fairly typical for some maps to have their anti-bio crate outside armoury and still retaining the armoury lock. See: Clarion, Kondaru and Donut 3

**Comment by JORJ949** [comment]
If its intentional then I think that should be changed, if it is intentionally outside of armory why give it armory access?
