### ISSUE TITLE
Wizard seen on arrivals shuttle during round loading

### ISSUE THREAD

**Issue by j-awn** [goonstation/goonstation#1819]
[BUG]

**Describe the bug**
I saw a wizard on the arrivals shuttle when the round was loading. The game mode was "secret". This wasn't a big deal, except I imagine seeing nukies on the arrival shuttle could spoil a nuke round for the antags.

**To Reproduce**
Start a round with a wizard
See someone holding a staff on the arrivals shuttle during round loading

**Expected behavior**
To not have antags spoiled during round loading

**Comment by pali6** [comment]
Known bug and I hate it but to fix it one would have to untangle the mess that is roundstart mob spawning and then reorder it.

**Comment by Carbadox** [comment]
Wasn't / isn't there a fade in effect that was supposed to band aid this?

**Comment by pali6** [comment]
There is but lag and other factors can cause it to fail because, well, it is a band aid.
