### ISSUE TITLE
Item Arm Icons Layer Under HUD, Remain when you become Ghost

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#182]
**Describe the bug**
When you attach an item as an arm, the item icon doesn't appear above your HUD, so you can't interact with it to change settings/reload/etc. The icon is still there, just under the HUD. The icon persists after death, permanently attaching itself to your ghost HUD and being annoying.

**To Reproduce**
1. Get your arm replaced with an item
2. See error
3. Die and ghost without removing the item arm
4. See other error

**Expected behavior**
The item should appear above the HUD so it can be interacted with. The item should also not remain on the HUD after you die/change mobs.

**Screenshots**
[Not appearing on HUD](https://cdn.discordapp.com/attachments/182254397999415296/698288460745670666/unknown.png)
[Right clicking reveals it's under the HUD](https://cdn.discordapp.com/attachments/182254397999415296/698288791345037422/unknown.png)
[Appearing on HUD after death](https://cdn.discordapp.com/attachments/182254397999415296/698288255468044318/unknown.png)

**Additional context**
N/A

**Comment by ZeWaka** [comment]
.layer or .plane issue
