### ISSUE TITLE
Using a Penlight on a Cyborg completely flashbangs them for a second

### ISSUE THREAD

**Issue by 444Portal** [goonstation/goonstation#18201]
### Labels

[BUG] [MINOR]

### Description

As the title says. Doing so turns their screen pure blinding white for a second or two. No stun, no nothing. Just hurting my eyes.

### Steps to reproduce

1. Get a hold of a penlight
2. Find your local friendly robot
3. Left click
4. Watch them weep as they can't see

### Expected Behavior

Either doing nothing or some witty text about how they don't have proper eyes/some kind of play on how flashes stun them

**Comment by DGC9Crew** [comment]
looks like #9352 forgot to remove a line, which still applies the flash effect to other mobs
