### ISSUE TITLE
Goonhub's Debris field map on Ocean maps

### ISSUE THREAD

**Issue by Esstoo** [goonstation/goonstation#18253]
### Labels

[BUG] [MINOR]

### Description

Ocean maps on Goonhub show the Debris Field despite the fact it doesn't exist on said maps.

### Steps to reproduce

1. Go to "Maps" on Goonhub
2. Select Either Oshan or Nadir
3. Switch to "Debris Field"
4. Oh god my eyes

### Expected Behavior

Debris Field option shouldn't be there

### Additional Information & Screenshots

![image_2024-03-20_164004817](https://github.com/goonstation/goonstation/assets/88528068/451da7ad-7947-4663-9b7d-91792aefb13a)

**Comment by Wirewraith** [comment]
Fixed, along with map viewer enhancements.
