### ISSUE TITLE
Centcomm Power Warning Announcement Always Fires on Non-TEG maps

### ISSUE THREAD

**Issue by MarkNais** [goonstation/goonstation#1828]
[BUG]

**Describe the bug**
The NT engine-start announcement fires even when power has been secured on non TEG maps.

**To Reproduce**
1. Be on a map that uses non-TEG power
2. Start the engine before the time limit (10 or 15 minutes)

**Expected behavior**
No report when the engine has been started in time.

**Additional context**

**Central Authority Update**
Power Grid Warning
Reports indicate that the engine on-board NSS Manta has not yet been started. Setting up the engine is strongly recommended, or else stationwide power failures may occur.

**Comment by Tiggersaurus** [comment]
Totally a feature
