### ISSUE TITLE
Empowered Meta-Neural Antenna can listen to gang radio channels

### ISSUE THREAD

**Issue by 1aidan2b2** [goonstation/goonstation#18316]
### Labels

[BUG]

### Description

If you have empowered meta-neural antenna, you can listen to gang radio

### Steps to reproduce

1. Get a gang round
2. Get empowered meta neural antenna
3. Get a gang member to send a message on gang radio, or wait for "boss" to say something.

### Expected Behavior

You'll be able to see the gang's radio message

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/bea2a65886af3f6e70669acad5c28bf9b9fa8cb3
