### ISSUE TITLE
Clown ID cannot be touched

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#18357]
### Labels

[BUG]

### Description

The Clown ID cannot be touched, or otherwise grabbed without switching it's place with another id or pda

### Steps to reproduce

1. Be clown
2. Try to grab your id
3. Fail
4. Try to swap with your pda
5. Succeed, but you can't use your id to interact with things

### Expected Behavior

For my id to not be covered in super lube

**Comment by Wisemonster** [comment]
For some reason, it fixed itself later in the round? Also to note, I had the heavy sleeper trait

**Comment by 444Portal** [comment]
related to / duplciate of #18173
