### ISSUE TITLE
Cyborg's power shovel lacks a sprite

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#18359]
### Labels

[BUG]

### Description

The power shovel in the cyborg engineering module on oshan lacks a sprite

### Steps to reproduce

1. Be on oshan
2. Be a borg
3. Get an engineering module
4. Look for the power shovel
5. Notice the lack of sprite

### Expected Behavior

For it to have a sprite

### Additional Information & Screenshots

![Goonstation 1 Classic_ Heisenbee_ Oshan Laboratory, Abzu 3_29_2024 10_34_41 PM](https://github.com/goonstation/goonstation/assets/87689371/73c97f2f-e1d2-4642-9312-32f5318cf82a)

**Comment by 444Portal** [comment]
fixed by #18375
