### ISSUE TITLE
Mining drill has no sprite

### ISSUE THREAD

**Issue by someuntakenusername** [goonstation/goonstation#18363]
### Labels

[BUG]

### Description

Custom mining drill has no visible sprite

### Steps to reproduce

1. Make a chitin mining drill with a rock handle
2. ???
3. drill is invisible

### Expected Behavior

The drill has a visible sprite

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/48699758/399945f7-7274-4b4c-b14c-8383fe10f9e7)

**Comment by pgmzeta** [comment]
fixed in 194d73e
