### ISSUE TITLE
Remotely eat someones brain (with fair amount of prep)

### ISSUE THREAD

**Issue by Valtsu0** [goonstation/goonstation#18458]
### Labels

[BUG]

### Description

Remotely eat someones brain by delaying the accepting of the prompt

### Steps to reproduce

1. Take someones brain out
2. begin to eat it, but leave the popup open
3. put the brain back in
4. Use SR to revive them
5. (optional) say a one liner like "You are already dead"
6. Press yes on the brain eating popup
7. You will eat your targets brain and they will instantly die

### Expected Behavior

To not be able to do that

### Additional Information & Screenshots

Silicons are fine with their brain being in your stomach

**Comment by TobleroneSwordfish** [comment]
fixed in a568e95
