### ISSUE TITLE
SecHUD flags not showing on examine with sechud

### ISSUE THREAD

**Issue by avanth89** [goonstation/goonstation#18479]
### Labels

[BUG]

### Description

SecHUD flags not showing on examine.

### Steps to reproduce

1. Set someones secflag in secmate.
2. Examine someone.
3. No secflag shown on examine.

### Expected Behavior

SecHUD flags to show on examine.

### Additional Information & Screenshots

Marked several people during a round. Not a single one had their SecHUD flag showing on an examine.

![Screenshot 2024-04-12 182609](https://github.com/goonstation/goonstation/assets/21094381/b0d328c5-740a-4fda-9640-fb0c3e83b1c4)
![Screenshot 2024-04-12 182617](https://github.com/goonstation/goonstation/assets/21094381/07b3a148-208c-4628-9d3d-7ec43d8bec0e)

**Comment by pgmzeta** [comment]
SecHUD flags currently only show when the person has a criminal status set, but I don't think it is communicated anywhere.

**Comment by avanth89** [comment]
Might not be, but I'm fairly certain I had tested after flagging as well. I can run a local later to double check!
