### ISSUE TITLE
Items moved from tray into crate teleport back when tray is moved

### ISSUE THREAD

**Issue by FluffiestFloof** [goonstation/goonstation#18519]
### Labels

[BUG]

### Description

Items moved from tray into crate using click and drag method teleports back when tray is moved.

### Steps to reproduce

1. Put item(s) on tray, similar to the one in roboticist bay or medical.
2. Click drag the item(s) to a closed crate so it does the 'put in' animation.
3. Optional: Move the crate anywhere, it doesn't seem to matter?
4. Move the tray, all the items that were moved from it are suddenly back.

### Expected Behavior

Expected for this to not do that.

### Additional Information & Screenshots

It doesn't seem to duplicate items so at least there is that. It also does the same thing if the crate is open or closed so it seems to be related to the click and drag behaviour.

**Comment by pgmzeta** [comment]
Dupe #16052
