### ISSUE TITLE
Invisible Arrows that become useless when plucking them from a mob 

### ISSUE THREAD

**Issue by CatzCatzCatz** [goonstation/goonstation#18530]
### Labels

[BUG]

### Description

Upon plucking out an arrow from a mob, it puts arrows into your hand. However, the arrows cannot be used to stab people like it usually does and the sprite is invisible. Dropping or throwing them seems to fix the issue.

### Steps to reproduce

Stab a mob using an arrow. 
Pluck out the arrows and realize that the arrows are invisible and outright useless.

### Expected Behavior

The arrows should not be invisible and should still be able to function as an arrow.

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/107842263/78ae0b65-61ed-451e-93dd-1abf09d76ccf)

**Comment by CaioFrancisco** [comment]
sounds very much like a runtime

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/035b4b9fed6107e6ebc5f736f4aaebc7222a3bab

> sounds very much like a runtime

no runtime actually
