### ISSUE TITLE
Chemicompiler will run forever if the ran script is empty

### ISSUE THREAD

**Issue by cogreaper** [goonstation/goonstation#1855]
[BUG]

**Describe the bug**
If there are no instructions for the chemicompiler to execute, it will run forever.

**To Reproduce**
1. hit save and click 1
2. note that it is now running and unresponsive

**Expected behavior**
It should probably just exit immediately

**Additional context**
I found it on accident when pasting in my code, for whatever reason it input blank stuff.

**Comment by pali6** [comment]
Unable to reproduce.
