### ISSUE TITLE
Setting HoS on high priority may not be picked

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#18556]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Someone sets HoS on high priority, another person sets it on medium priority
2. The person who set it on medium priority is picked as HoS

### Expected Behavior

For person who set it on high priority to be picked

**Comment by pgmzeta** [comment]
Were you a security officer instead of the head of security?

**Comment by FlameArrow57** [comment]
> Was the high priority HoS a security officer instead?

Yeah

**Comment by NightmareChamillian** [comment]
linking #18879 as that might fix it

**Comment by JORJ949** [comment]
> > Was the high priority HoS a security officer instead?
> 
> Yeah

I believe this was patched recently, the priority security officer slots were overriding any HoS preferences but this should be fixed
