### ISSUE TITLE
Can't move flaming trash cans

### ISSUE THREAD

**Issue by cropseyy** [goonstation/goonstation#18559]
### Labels

[BUG]

### Description

Barrel is an immovable object and I am an unstoppable force

### Steps to reproduce

1. Try to move the flaming barrel
2. Fail
3. Try to unscrew the barrel
4. Fail
5. Try to deconstruct the barrel
6. Fail
7. Be confused

### Expected Behavior

I expect to be able to move or make a barrel to fufill my trash goblin dreams.

**Comment by TealSeer** [comment]
Feature request
