### ISSUE TITLE
ShowChoices is slow

### ISSUE THREAD

**Issue by pali6** [goonstation/goonstation#1864]
[BUG]

**Describe the bug**
ShowChoices is slow for reasons that are mysterious. No one has been able to reproduce it on different machnes than the live server.

**To Reproduce**
1. Login to a live server
2. Open Character Preferences
3. Rapidly change your gender multiple times per second
4. See server lag

**Expected behavior**
No lag.

**Comment by pali6** [comment]
Ok, I'm putting the rest into comments because this feels like ravings of a madman and not a bug report:

`generate_select_table` was what I tracked down ShowChoices lag to in the end, but as I said it wasn't even the proc itself that showed up on the profiler, just that tick usage was way up after the call compared to what it was before the call. But at this point I suspect that neither the profiler nor `world.tick_usage` is to be trusted. I removed all lagchecks and sleeps and peppered ShowChoices with stuff like `logTheThing("[__LINE__] [world.tick_usage]")` to find the culprit on the dev server.

Relevant history in the develop branch is after the commit 95a064c but I suspect that the branch's history got rewritten several times so that commit is likely non-existent now.

I was unable to reproduce such lag by just creating absolutely massive heaps of various string operations.

I made a verb that calls `generate_select_table` 30 times and a verb that is just ~~copypasted~~ manually inlined code of `generate_select_table` in a for loop that runs 30 times. The former was slow, the latter was fast:
![image](https://user-images.githubusercontent.com/358431/90553521-cb461a80-e194-11ea-9f67-2c35065c8fdd.png)

As I tried to investigate further the slowdown suddenly disappeared when I added some unrelated global procs. For a while I thought it might be something line byond's internal proc name resolution being slow due to some hash table clashes. So I reverted the relevant commits back to a state in which everything was slow and the slowdown was still gone. It makes no sense.

A reasonable assumption is that the OS plays a role but ZeWaka tried profiling locally on a Linux machine and it was still fast.

This might or might not be related to how sometimes procs that do string operations are orders of magnitude slower than they should be (usually on lowpop RP). Think along the lines of "opening the ID access console lags the whole server for 2 minutes". It happens / used to happen unpredictably and without any sensible reason. Mostly on the RP server (could long rounds be relevant?). Restarting the server usually fixed it but not always.

Number of players on the server has no effect on this issue.

**Comment by pali6** [comment]
Good luck.

**Comment by 2aa63b1b-7113-4f5a-8da3-7e8c95459c2c** [comment]
`traitPreferences.updateTraits(user)` might be a potential source of slowdowns as well, do we really need to be rebuilding the traits every single time you update your gender?

**Comment by pali6** [comment]
Could be but during the testing I removed that line completely and it made no change on it being slow.

**Comment by ZeWaka** [comment]
not an issue anymore haha
