### ISSUE TITLE
Deployable turrets (N.A.R.C.S.) can't be rotated on live servers

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#18661]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Be on live server
2. Use wrench to try to rotate deployable turret (N.A.R.C.S./NARCS)

### Expected Behavior

For the turret to be rotatable

### Additional Information & Screenshots

It works on local, maybe something in the secret module that breaks it on public servers?

**Comment by TobleroneSwordfish** [comment]
Can't reproduce

**Comment by FlameArrow57** [comment]
> Can't reproduce

Idk, maps I've tried it on are the Cogmap1 and Nadir roundstart spawn NARCS turrets. Whenever I play as HoS, never seems to work to rotate them, using wrench from a toolbox

**Comment by Tarmunora** [comment]
Could not reproduce on live

**Comment by FlameArrow57** [comment]
I recorded it not working here, on the server 1 round that ended just a few minutes ago

https://streamable.com/zc7jol

**Comment by FlameArrow57** [comment]
Also I tried it through starting a server through dreamdaemon.exe, just being a player (not admin or host) and it didn't work through that either

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/798915e843ff3e74d2cbd66544a930285ac29037
