### ISSUE TITLE
Debris field cloner blueprints have broken material requirements

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#18687]
### Labels

[BUG]

### Description

The cloner blueprints in debris field only require 0.1 steel/glass/copper for each piece

### Steps to reproduce

1. Get the cloner blueprints from debris field
2. Put them into a fabricator
3. Mass produce cloners since they cost nothing!!!

### Expected Behavior

Proper material requirements

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/141e8e2d1c3f2434b2f1e88d0a82597b4f085df4
