### ISSUE TITLE
Incorrect traits shown on characters not in the first slot. Correct are traits used when playing.

### ISSUE THREAD

**Issue by avanth89** [goonstation/goonstation#18745]
### Labels

[BUG]

### Description

Selecting a different character shows wrong traits

### Steps to reproduce

1. Load character in slot two.
2. Go to the traits tab.
3. Traits from slot one character are shown.

### Expected Behavior

Traits from slot two character are shown.

**Comment by mordent-goonstation** [comment]
Likely caused by https://github.com/goonstation/goonstation/commit/84bd34afb6987cbc425a10307a846760536ed3c5

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/77bc52d5dd411b5556d6782290ee436a3edfde01
