### ISSUE TITLE
The grody gizmo (meat gun) from meatstation can be put in the belt slot, basically removing your belt slot forever.

### ISSUE THREAD

**Issue by Xkallubar** [goonstation/goonstation#18867]
### Labels

[BUG]

### Description

The grody gizmo latches to your arm when you pick it up, and cannot be dropped, but it can also be put in the belt slot by pressing E (at least on /tg/ style controls) and since it cannot be removed, it will just be stuck there taking up your belt slot forever.

### Steps to reproduce

1. Pick up grody gizmo
2. Press E/put it in your belt slot

### Expected Behavior

It shouldn't be able to go in your belt slot

**Comment by TobleroneSwordfish** [comment]
fixed in 5b9a59d
