### ISSUE TITLE
Clicking "respawn" when in the afterlife bar lets you spawn clones of yourself

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#18881]
### Labels

[BUG][minor]

### Description

title. Lets you dupe.

### Steps to reproduce

1.  be dead and chilling in afterlife bar
2. click respawn
3. die again somehow
4. two yous

### Expected Behavior

respawn should probably wipe/remove your body.

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/96703882/4c26acef-14fb-4644-86dc-4e8a6599368e)
was reproduced three times in the same round

**Comment by pgmzeta** [comment]
cc81369
