### ISSUE TITLE
Capsule machine sprite does not change when pryed back up

### ISSUE THREAD

**Issue by Goat-Real** [goonstation/goonstation#18901]
### Labels

[BUG]

### Description

When prying back up a capsule machine, the sprite of the machine does not fix itself and stays on the fallen down sprite

### Steps to reproduce

1. Throw someone into a capsule vendor
2. Pry the capsule vendor back up

### Expected Behavior

For the capsule vendor to stand upright

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/126099705/7eb2a36b-ed3a-43ac-b4d7-79f3602e4c43)

**Comment by RelentlessGarbage** [comment]
@NightmareChamillian This is a separate bug; this covers the fact that the capsule machine's sprite does not update when pried back up. The overlay bug in #9757 is still present, though.
@ZeWaka Were you the one to write the code for the capsule vendor?

**Comment by ZeWaka** [comment]
No
