### ISSUE TITLE
Mining hammer bug

### ISSUE THREAD

**Issue by kawadamol** [goonstation/goonstation#18940]
### Labels

[BUG] [MINOR]

### Description

When you replace a powercell from a turned on mining hammer it turns off but you can still do the special smash with no energy costs

### Steps to reproduce

1. Grab a mining hammer
2. Turn it on
3. Use powercell on hammer
4. When the hammer is turned off due to the powercell change use harm intent to use the smash special

### Expected Behavior

I expect that the hammer doesn't allow you to use the special when its turned off

**Comment by pgmzeta** [comment]
`Exception has occurred: undefined proc or verb /obj/item/mining_tool/powered/hammer/update inhands().`
