### ISSUE TITLE
Reinforced steel sheets spawned from broken walls unstackable with other reinforced steel sheets

### ISSUE THREAD

**Issue by zagoon** [goonstation/goonstation#1899]
[BUG]

**Describe the bug**

> You can't mix different reinforcements!

Reinforced steel sheets that spawn when a wall is broken via disassembling, bombing, or other damage that strips girders are considered a separate material from reinforced steel sheets that are spawned at roundstart or crafted by hand and cannot be stacked with either. The sheets can only be stacked with other sheets stripped from walls unless the reinforcement is removed and used to craft new reinforced sheets.

**To Reproduce**
1. Fuck up some reinforced walls
2. Attempt to combine the reinforced steel sheets that spawn on the destroyed walls with a reinforced steel sheet that was crafted or taken from tool storage

**Expected behavior**
Sheets of the same dang name and material to stack normally.

**Comment by Carbadox** [comment]
Fixed some time ago
