### ISSUE TITLE
Humans can put heavy cyborg arms on themselves

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#19043]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Be human, missing arm
2. Click self with heavy cyborg arm while on a surgery table

### Expected Behavior

To not be able to put it on

### Additional Information & Screenshots

I think this is a bug? Cyborgs can't click drag them onto people, they get an error message saying "That arm is too big to fit on [person]'s body!"

**Comment by Retrino** [comment]
humans can also put them on other humans, it honestly should just be standardized to allow them to fit. really not much of a reason not to

**Comment by Tarmunora** [comment]
> I think the clickdrag behaviour is the bugged one. That sounds like heavy arms at one point were too heavy, and so eine just forgot to adjust the the click-drag interaction.

Actually the bug was that a thing in item-arm code was incorrectly bypassing the restrictions on attaching sturdy/heavy robot arms as prosthetics
also https://github.com/goonstation/goonstation/commit/21c91c2d4da6354981f1ae9e3a5fce8e895f7eea
