### ISSUE TITLE
Duplicated items in Oshan Labs telesci facilities 

### ISSUE THREAD

**Issue by libbmaster** [goonstation/goonstation#1906]
[BUG]

**Describe the bug**
The "Adventure crate" in Oshan Lab's telesci room contains duplicate items

**To Reproduce**
1. Visit the Oshan Labs teleporter room
2. Open the Adventure crate
3. Note the duplicate items (two "notes from mom", two sandwiches, etc)

**Screenshots**
![ScreenShot_20200823010558](https://user-images.githubusercontent.com/56776242/90972313-f78bcf00-e4e5-11ea-97c8-359b863d27c5.png)

**Comment by Michaellaneous** [comment]
Found the issue, map spawns an adventure crate and then fills it with those items, despite the adventure crate already having those.
Will create a  PR later.
