### ISSUE TITLE
PIN UI Keypresses Often not Working

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#19071]
### Labels

[BUG][UI]

### Description

Pressing keys such as enter or backspace after the PIN UI opens doesn't do anything

### Steps to reproduce

1. Open the PIN UI by swiping an id card at a manufacturer/vending machine
2. Press enter
3. Nothing happens

### Expected Behavior

The UI to submit after pressing enter or delete a number after pressing backspace

### Additional Information & Screenshots

Sometimes the keypress works the first time, sometimes it works after mashing the key multiple times, and sometimes it never works at all.

It always works without issue by clicking the ui before the keypress, hinting at some sort of autofocus issue.

The UI in question  
![image](https://github.com/goonstation/goonstation/assets/6396368/3765785f-9354-442c-9e0f-aaeb818d08e5)

**Comment by MeggalBozale** [comment]
Yeah it should really autofocus and just allow you to hit enter / keys anytime. Don't know why it doesn't right now.

**Comment by Garash2k** [comment]
Autofocus issues got fixed at some point since then
