### ISSUE TITLE
Mobile chemicompiler breaks when a script that works with the normal chemicompiler is used

### ISSUE THREAD

**Issue by cogreaper** [goonstation/goonstation#1909]
[BUG]

**Describe the bug**
inserting the following script into the mobile chemicompiler breaks it assuming beakers 1 and 2 are inserted and 1 is full.
+}+)-'@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

**To Reproduce**
1. fill beaker 1 leave beaker 2 empty
2. insert into a normal chemicompiler
3. the script works
4. insert into a mobile chemicompiler
5. it breaks

**Expected behavior**
I expect it to work the same in both

**Screenshots**

**Additional context**

**Comment by MarkNais** [comment]
Fixed by @Tarmunora
