### ISSUE TITLE
Bee wool does not stack properly

### ISSUE THREAD

**Issue by ghost** [goonstation/goonstation#1910]
[BUG]

**Describe the bug**
Bee wool loses materials when stacked

**To Reproduce**
1. shear several bees with scissors
2. note the quantities of wool
3. attempt to stack them
4. you should now have an amount of bee wool equal to the number of stacks and not the quantity they contained

**Expected behavior**
I expected 7 bee wool and 3 bee wool to make a stack of 10 not of 2

**Screenshots**

**Additional context**

**Comment by Michaellaneous** [comment]
Here are my findings:
Shearing a bee always results in one piece of beewool being dropped.
At some point (it seems rather random), a random piece of single beewool that has not been picked up will display the same stack amount as the stack in your hand. 
However, this only applies to the number that gets added to a sprite. The item description will yet display a different amount. Other random pieces of beewool have the same issue, but do not display a stack size on the sprite.

**Comment by ZeWaka** [comment]
@Xkeeper0

**Comment by MetricDuck** [comment]
Tested today - stacks of bee wool become "bee wool bee wool", and separating them out shows that the bee wool is now made of bee wool (with the sprite modified to boot). The described stacking issues were unproduceable at least.
