### ISSUE TITLE
Pizza vending machine can be permabricked with mechcomp

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#19106]
### Labels

[BUG][minor]

### Description

When using mechcomp to get free machine pizzas, the machine will vend one of each pizza, then refuse to make any more pizzas of the types you vended.

### Steps to reproduce

1. Attach some kind of mechcomp trigger to a pizza vending machine, set to Vend Random.
2. Trigger the thing to vend a couple times
3. Open the machine's UI and try to select one of the options it vended. (They spawn with 100c so no need to bring money)

### Expected Behavior

Free pizza! Or at least paid pizza after the free ones run out.

**Comment by MetricDuck** [comment]
Throw code doesn't understand the concept of an infinite product

**Comment by MetricDuck** [comment]
Fixed in 913cccd
