### ISSUE TITLE
Steel and Copper are treated as high density matter and high conductive material respectively

### ISSUE THREAD

**Issue by Krosesuleyk** [goonstation/goonstation#19222]
### Labels

[BUG][MAJOR]

### Description

As per the title, the fabricator is treating these resources as something they definitely aren't.

### Steps to reproduce

1. Find a fabricator, for my attached examples I used a robotics one.
2. Make sure the fabricator only has base resources (i.e. Steel, Copper, Glass).
3. Find a recipe requiring either High Density Matter, High Conductive Material, or both.
4. See that they can be fabricated.

### Expected Behavior

These base materials shouldn't have such high value to the fabricator.

### Additional Information & Screenshots

Here is a list of materials in the fabricator, and a picture with several underlined objects which it shouldn't be able to make.

![materials](https://github.com/goonstation/goonstation/assets/171211561/36b74f24-d677-4e02-8559-443a76091d12)
![Screenshot (29)](https://github.com/goonstation/goonstation/assets/171211561/6b22afb3-dcd7-4712-a076-743c0f0217e9)

**Comment by Sbmhawk** [comment]
@MeggalBozale

**Comment by MeggalBozale** [comment]
Already fixed in #19218, I thought?

**Comment by Krosesuleyk** [comment]
> Already fixed in #19218, I thought?

This was on nightshade if that changes anything. I took those screenshots like an hour ago though.

**Comment by MeggalBozale** [comment]
> > Already fixed in #19218, I thought?
> 
> This was on nightshade if that changes anything. I took those screenshots like an hour ago though.

It does, actually, that's important. Nightshade doesn't get builds as frequently. Devs need to update nightshade for the changes to be reflected there.

**Comment by MeggalBozale** [comment]
I'm going to close this as completed as it's fixed whenever nightshade recompiles, let me know if it keeps happening tomorrow. Thank you for the bug report!

**Comment by MeggalBozale** [comment]
Hi,
It's returning that steel passes for high density matter, and that is intentional logic, as that was equivalent to DEN-1 previously (which steel satisfies.)
