### ISSUE TITLE
TGUI: Text color palette issue when using ProgressBar

### ISSUE THREAD

**Issue by PrimeNumb** [goonstation/goonstation#1924]
Some issues regarding colors might pop up in the future wrt the `ProgressBar` component. Picking the background color of the progress bar, or god forbid, having multiple background colors depending on state may severely limit your text color palette.

Example: 

![](https://cdn.discordapp.com/attachments/747543044579917878/747560306859049080/unknown.png)

One (albeit slightly hacky) fix is to introduce `text-shadow`:

![](https://cdn.discordapp.com/attachments/747543044579917878/747560394729717930/unknown.png)
(`font-weight` was also used)
(do note that this property is unavailable below IE9)

Any clever general solutions to this might be of interest to tgstation as well.

**Comment by ZeWaka** [comment]
this is just a color theory issue, nothing to do with tgui
