### ISSUE TITLE
Wraiths and poltergeists move WAY too fast when manifested and might be able to pass through objects??

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#19263]
### Labels

[BUG]

### Description

Maybe they accidentally gained the ability to sprint? Not sure, but it's definitely too fast.

### Steps to reproduce

1. Be wraith
2. Get manifested
3. GO FAST

### Expected Behavior

I expected them to be slow and vulnerable like they used to be

**Comment by Sbmhawk** [comment]
can confirm, I saw the same thing
