### ISSUE TITLE
Incorrect Item Interaction on Same Tile as Player/NPC

### ISSUE THREAD

**Issue by WillHuff** [goonstation/goonstation#19285]
### Labels

[BUG]

### Description

Item left clicking through the right click menu does not behave as expected

### Steps to reproduce

1. As a reproducible example, remove John Bill's cigarette.
2. Use the right click menu to left click/ pick up the cigarette while the cig is on the same tile as John.
3. The player instead shakes John Bill.

### Expected Behavior

I expected the cigarette to be picked up.

**Comment by MeggalBozale** [comment]
Duplicate of #16386

**Comment by MeggalBozale** [comment]
Oh sorry i meant #1780
