### ISSUE TITLE
Wraith Bug - Revenant does not generate Biopoints

### ISSUE THREAD

**Issue by Soldat778** [goonstation/goonstation#1937]
[BUG]

Overflow RP Wraith doesn't seem to generate Biopoints during their Revenant ability, or their abilities are just untouchable. When I saw this, the icons for the abilities were blanked out. At first, due to this being my first time being Wraith, I thought I just had to beat the snot out of someone, but then the Goonstation wiki says that I should just generate Biopoints super fast anyway, which I could not.

1. Become the Wraith antagonist.
2. Build up enough points to use the Revenant ability.
3. Revenant any corpse.
4. See bug; no abilities are able to be used.

What I had expected:
The images in the top left should have lit up, but they never did, meaning I couldn't use them.

**Comment by MetricDuck** [comment]
This is an instance of #4935.
