### ISSUE TITLE
Custom keybinds reset when reconnecting

### ISSUE THREAD

**Issue by PrimeNumb** [goonstation/goonstation#1940]
[BUG]

**Describe the bug**
Title. Been an issue for a while but figured I might put it up here at last.

**Expected behavior**
To actually load and use your custom keybinds.

**Comment by pali6** [comment]
My guess: cloud stuff is loaded in client/New, keybinds are reset in mob/Login, mob/Login somehow happens before client/New?
Sidenote: why isn't cloud stuff on /datum/player instead, it'd make more sense.

**Comment by pali6** [comment]
Likely fixed by 122346bea76745f4bc9efafaf7ba0f48c3e34b52.
