### ISSUE TITLE
Using "empty all into chute" option on feed grinder sometimes makes it not produce anything

### ISSUE THREAD

**Issue by trazodont** [goonstation/goonstation#19418]
### Labels

[BUG]

### Description

no food for chickens ):

### Steps to reproduce

1. Fill satchel with produce
2. Smack against feed grinder and select empty all into chute option
3. Listen to grinder go all round but not actually process everything, meaning you have to put food in there one by one to get any feed in return. It still works after it bugs out, but using the empty all into chute option wont result in any feed.

### Expected Behavior

give chicken feed :3

**Comment by TobleroneSwordfish** [comment]
Fixed
