### ISSUE TITLE
plasmastone no longer counted as significant power source

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#19514]
### Labels

[BUG][materials]

### Description

https://github.com/goonstation/goonstation/pull/19057 moved the radioactivity threshold for significant power sources (POW-2) from 2 to 3, which I believe to be an oversight since that PR is only supposed to be a conversion.

### Steps to reproduce

N/A

### Expected Behavior

making spicy items with plasmastone

**Comment by MeggalBozale** [comment]
soon
