### ISSUE TITLE
Some medals are missing from goonhub

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#19544]
### Labels

[BUG]

### Description

Some medals do not appear on goonhub, but are visible and counted in the in-game medal list.

### Steps to reproduce

1. Check your medals on goonhub
2. Notice the number doesn't match the in-game number
3. Find that "To the Moon!" and "Virtual Ascension" medals are missing on goonhub

### Expected Behavior

All my medals should appear on goonhub.

### Additional Information & Screenshots

In-game
![image](https://github.com/goonstation/goonstation/assets/25157685/99b3508d-1c23-46e1-ad71-ea8a62f63deb)
Goonhub
![image](https://github.com/goonstation/goonstation/assets/25157685/ed7c2fb4-7a03-457b-8f78-da7818591ff7)

**Comment by Wirewraith** [comment]
Some medals are marked as "hidden" from public display and won't show up on Goonhub, but will show up via that ingame command. I will add something to the player view page on Goonhub to show that a player has earned hidden medals, though.
