### ISSUE TITLE
Empty middle names don't stay empty

### ISSUE THREAD

**Issue by Smearfo** [goonstation/goonstation#19570]
### Labels

[BUG][MINOR]

### Description

The middle name selection can be left empty, but seems to set itself to a random name afterwards.

### Steps to reproduce

1. Set middle name to be empty
2. Save and close character editor
3. Disconnect and reconnect to server
4. Reopen character editor
5. Random middle name

### Expected Behavior

For the middle name slot to remain empty.

**Comment by Retrino** [comment]
repeat
