### ISSUE TITLE
Hot Toddies are unmakeable

### ISSUE THREAD

**Issue by j-awn** [goonstation/goonstation#1958]
[BUG]

**Describe the bug**
You can't make a hot toddy, only half-and-half and bourbon.

**To Reproduce**
1. Fill a container with equal parts bourbon, lemon juice, and sweet tea, in any order. 
2. Observe that the container now holds a 2:1 ratio of half-and-half to bourbon.

**Expected behavior**
The room should suddenly be filled with a festive aroma by a delicious hot toddy.

**Comment by Carbadox** [comment]
thats wierd, i tested it myself when I first added it and seemed to work fine. Did you try adding the sweet tea last or mixing it all in a cocktail shaker? I believe the recipe for the hot toddy should take priority in both methods

**Comment by j-awn** [comment]
Yeah, I'm not sure what was going on. There's a typo in the definition, but I can confirm I just made it.
