### ISSUE TITLE
Pods are sometimes unpilotable with multiple people inside

### ISSUE THREAD

**Issue by DicksonOrmus** [goonstation/goonstation#197]
My partner and I loaded a nuke into the pod, got in, and neither of us could fly the pod, it just wouldn't move for either of us, even after we got out and got back in
It worked for flourish tho.

**Comment by Gannets** [comment]
Not unique to manta sadly. I've observed this bug across several maps. Sometimes leaving and re-entering the pod fixes it, other times it doesn't.

**Comment by pali6** [comment]
I'm pretty sure this happens because `pilot` stays at null or points to something invalid (like a mob that left).

**Comment by pali6** [comment]
I made some related fixes, this might have also gotten fixed by accident.

**Comment by Tarmunora** [comment]
Going to assume that this is fixed. If not we can always reopen this
