### ISSUE TITLE
OSHAN BUG - DWAINE term_ping does not show AI mainframe

### ISSUE THREAD

**Issue by Recusor** [goonstation/goonstation#1972]
[BUG]

**Describe the bug**
Made a new dwaine console on OSHAN, did term_ping lots of other devices showed up but not the AI mainframe so i could sneakily type to AI.

**To Reproduce**
1. Make a new DWAINE machine that boots properly etc with wired network card over data terminal
2. boot up, enter term_ping
3. Look for AI Mainframe

**Expected behavior**
I should be able to see the AI mainframe, unless the AI was made during the shift, which was not the case this time im 99% sure

**Screenshots**

**Additional context**

**Comment by pali6** [comment]
The data terminal is not connected to the nearby cables, needs a tiny mapping change.

**Comment by MarkNais** [comment]
I'm so sad I missed the cables in #1506
