### ISSUE TITLE
Zewaka's jokes suck

### ISSUE THREAD

**Issue by ike709** [goonstation/goonstation#19747]
### Labels

[BUG]

### Description

See title. He told me to make this.

### Steps to reproduce

1. Listen to him tell a joke
2. Don't laugh
3. Repeat

### Expected Behavior

I expect jokes to be humorous.

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/5714543/0be0e7ab-b771-465a-934e-a541175a1e0f)

**Comment by ZeWaka** [comment]
can't repro

**Comment by ike709** [comment]
1984
