### ISSUE TITLE
Medibot DeathLoop but without the death

### ISSUE THREAD

**Issue by ZexMaxwell001** [goonstation/goonstation#1977]
[BUG]

**Describe the bug**
you get stuck in a loop of paralysis, knockdown and suffocation. however the suffocation effect is too short to die from it.

**To Reproduce**
Get stabbed by 2 medibot syringe 

**Expected behavior**
if you get stuck in this loop. you should die.

**Screenshots**
![image](https://user-images.githubusercontent.com/1289187/91519284-c7627880-e8b7-11ea-8b9d-d7bb853475d6.png)

**Comment by UrsulaMejor** [comment]
While admittedly not great gameplay, this is not a bug. I suggest you post on our ideas and suggestions forum: https://forum.ss13.co/forumdisplay.php?fid=8

if you ever get stuck in a situation like this where you're stuck and would rather just die, the "suicide" and "succumb" commands will kill you 99% of the time.
