### ISSUE TITLE
If a wheelchair is destroyed while in use the rider will crawl at walk speed permanently

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#19782]
### Labels

[BUG] [MINOR]

### Description

After having my wheelchair exploded I moved at full speed

### Steps to reproduce

1. Be in a wheelchair and legless (stumped trait)
2. Have wheelchair destroyed (explosives / blob attack)
3. Knocked to floor at normal walking speed
4. Retain walk speed whenever you crawl for the rest of the round

### Expected Behavior

Be slow like normal

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/97d12b77a9059c1df120eb97e4412a03fa836e5b
