### ISSUE TITLE
Can't swap egun cells

### ISSUE THREAD

**Issue by ryebek** [goonstation/goonstation#198]
**Describe the bug**
Title. You hit the egun with the cell, no message. Doesn't swap, but also doesn't say "X hits the energy gun with the power cell!"

**To Reproduce**
1. Have egun
2. Click on egun with power cell
3. No message
4. Cell hasn't swapped

**Expected behavior**
The cell is able to be swapped into the egun.

**Comment by PrimeNumb** [comment]
Fixed in https://github.com/goonstation/goonstation/pull/201
