### ISSUE TITLE
John Bill is lifeless

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#19845]
### Labels

[BUG]

### Description

John Bill's "Life()" never runs, for some reason.

### Steps to reproduce

1. Put John Bill in space
2. He doesn't freeze or suffocate
3. Put John Bill next to a shitty grill
4. He doesn't comment on, or try to operate the grill (this is so sad)
5. Observe that John Bill never moves, emotes, talks, or any of the other things he is supposed to do

### Expected Behavior

I want his Life() to run so that I can make him grill stuff for me!

**Comment by pgmzeta** [comment]
on local, if john's bus goes to the owlery (or i jump to the bus at the owlery) he wakes up

**Comment by Zamazenta** [comment]
> on local, if john's bus goes to the owlery (or i jump to the bus at the owlery) he wakes up

Looks like its gotta be some weird jank with the way the bus works then. I experimented with adding a john to the space diner and that one worked fine, and adding a bit of code to have that one immediately get teleported to the bus also works with no issues. It's only the one that spawns directly on the bus that has this issue.

**Comment by soleilan** [comment]
fixed by https://github.com/goonstation/goonstation/commit/ddccca33dbaa0f41bfb5ef4a29d9edad10a9b4cb
