### ISSUE TITLE
Right click menu wrong sprites

### ISSUE THREAD

**Issue by Croissant-Man** [goonstation/goonstation#19891]
### Labels

[BUG]

### Description

the beakers full of medical chems look like bags?

### Steps to reproduce

1. get trench meteor
2. get medical crate
3. right click examine
4. beakers look like bags
5. that's not right

### Expected Behavior

beakers to show as beakers

### Additional Information & Screenshots

![image](https://github.com/goonstation/goonstation/assets/146139722/ccfa6555-b82d-4d43-b11e-ba18072cfa13)

**Comment by TealSeer** [comment]
Duplicate of #14793
