### ISSUE TITLE
Manta lighting fuckery

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#199]
**Describe the bug**
Loosing a singulo on Manta produces unexpected effects

**To Reproduce**
1. Loose a singulo on Manta
2. Repair floor
3. See error

**Expected behavior**
Lighting should ideally be not shit

**Screenshots**
![image](https://user-images.githubusercontent.com/63235460/79044054-5588db80-7c03-11ea-9862-9151e13028ac.png)

**Comment by pali6** [comment]
Fixed in fe8f65e.
