### ISSUE TITLE
Blood level does not appear to change after resurrection via Strange Reagent 

### ISSUE THREAD

**Issue by RColquhoun** [goonstation/goonstation#19950]
### Labels

[BUG]

### Description

After a patient is resurrected with Strange Reagent, any attempt to increase their blood level is not visible via the Health Analyzer

### Steps to reproduce

1. Allow patient to die with a low blood level. Values I have seen are 5 and 235.
2. Resurrect patient by Strange Reagent.
3. Inject patient with blood, filgrastim or saline-glucose.
4. Scan patient with Health Analyzer every few seconds.

### Expected Behavior

The patient regains blood as usual, and the Health Analyzer displays the blood level increasing. 

### Additional Information & Screenshots

I have seen a patient with blood levels as low as 5 function mostly as normal, albiet with symptoms similar to mild hypo/hypertension. So my best guess is it's a bug with the Health Analyzer and not a functional inability for the player's body to regain blood. 

There is a possibility that all the cases I've seen have involved blood loss specifically via a vampire, but I don't know that for sure.

**Comment by Tarmunora** [comment]
caused by #19256

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/88e64de60dacb4ca36ecec78b30caaf28745c3b1
