### ISSUE TITLE
Borg able to view revolutionary overlay

### ISSUE THREAD

**Issue by Ttcket** [goonstation/goonstation#19965]
### Labels

[BUG]

### Description

Borgs created through means other than surgery able to view rev overlay.

### Steps to reproduce

1. Be human
2. Get injected with nanites during revolutionary mode
3. Turn into borg
4. Continue to be able to view rev overlay

### Expected Behavior

Be unable to view rev overlay anymore.

**Comment by TobleroneSwordfish** [comment]
Fixed in [49d3dc5](https://github.com/goonstation/goonstation/commit/49d3dc5e624edf15f133d49ba73e9a24b932f626)
