### ISSUE TITLE
ChemiCompiler is Dumping Double

### ISSUE THREAD

**Issue by MarkNais** [goonstation/goonstation#2000]
[BUG]

**Describe the bug**
The ChemiCompiler is doubling dumping operations. Regular transfers between beakers are unaffected. Transfers to "r13" (trash) remove twice the amount of register ax.

**To Reproduce**
1. Insert a filled beaker to r2
2. input, save, and run `+'+}+++++++++++)@`  (dump 1u from r2)
3. Remove the beaker and examine it. It holds 48u.

**Expected behavior**
After running the above code, the beaker holds 49u.

**Comment by MarkNais** [comment]
Did further testing:
Only trashing is doubled. Regular transfers are unaffected.

**Comment by MarkNais** [comment]
I spent 10 minutes looking into CC code for this bug (I've dug into CC code before)...
No idea why this is happening.

**Comment by TDHooligan** [comment]
i'm not massively familiar with how byond is working on these processing loops, but  could be two instances of the chemicomp loop working on it at once, one incrementing just before the other managest to adjust ax? 

perhaps create a duplicate sx, tx and ax reference to test if it's something being hit twice at once. i'm currently at work so a little helpless to do it myself
