### ISSUE TITLE
Rusted airlock in void is solid, turning the void into a trap that you can't leave

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#20018]
### Labels

[BUG]

### Description

The rusted airlock in the void acts like a wall and cannot be walked through.

### Steps to reproduce

1. Go to the void
2. Try to get to the end
3. You get blocked by a rusted airlock

### Expected Behavior

I can walk through it

### Additional Information & Screenshots

Happened on an oshan round specifically, although probably not related.

**Comment by pgmzeta** [comment]
this affects the cog1 rusted airlock by disposals

**Comment by TobleroneSwordfish** [comment]
Fixed in 286e2c4
