### ISSUE TITLE
white cat ears no longer white

### ISSUE THREAD

**Issue by Jeanfeels** [goonstation/goonstation#20123]
### Labels

[BUG]

### Description

the sprite for cat ear headbands no longer has the right colours when white

### Steps to reproduce

1. acquire 150 bucks
2. go to clothing booth
3. buy white cat ear headband
4. observe how grey and greenish they are
5. lament existence because you're a mime main and now they don't fit your hair at all (optional) 

### Expected Behavior

for white cat ears to be white

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/d57c8f04-67d8-434f-aa2a-b595e74da8ae)
see? not white anymore. in fact when worn they are slightly green around the edges which looks really bad

**Comment by Retrino** [comment]
not a bug, the cat ears are white. more of a request to make them brighter, but thats for forums/a pr
