### ISSUE TITLE
Two-handed weapons cant be used in-hand

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#2027]
[BUG]

**Describe the bug**

Two-handed weapons can't be used in-hand, normally.

**To Reproduce**
1. Get two-handed thing
2. Overwrite its attack_hand proc with a thing that does something
3. Use it in-hand
4. Doesnt do the thing

**Expected behavior**

It do the thing.

**Additional context**

This is why I removed haircutting from the sledgehammer.

**Comment by Kyle2143** [comment]
This is strange. I've made a 2 handed item that can be used in-hand. I'd be surprised someone changed 2 handed weapons since then.

**Comment by pali6** [comment]
This doesn't quite make sense? `attack_hand` is for attacking it with an empty hand (which you don't have). If you want to use it in your hand define `attack_self` instead.
