### ISSUE TITLE
Brig Chutes randomly breaking

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#20308]
### Labels

[BUG] [MAJOR]

### Description

Brig chutes will randomly break

### Steps to reproduce

1. Brig prisoner
2. Set timer
3. Chute opens
4. Suspect enters
5. Chute trunk (sometimes) breaks

### Expected Behavior

the chute to not break out of nowhere

**Comment by Retrino** [comment]
this happens if the person tries to bust out of the pipe before it fully flushed them away. movement keys cause you to bang around in there and inevitably break it

**Comment by JORJ949** [comment]
Cooldown fixed in a74c6ab
