### ISSUE TITLE
Build-A-Vend does not accept mechcomp inputs

### ISSUE THREAD

**Issue by cringeybabey** [goonstation/goonstation#20362]
### Labels

[BUG][MAJOR]

### Description

Build-A-Vend machines don't vend items when recieving an input signal from a linked component, such as a button. This happens regardless of whether you select "Vend random" or "Vend by name", and regardless of what the input signal is.

### Steps to reproduce

1. Build a vending machine frame, insert the components, and turn it on.
2. Unlock it with a screwdriver and click it with a multitool.
3. Open the wire panel, unlock the machine, and turn on the loading chute.
4. Insert a couple random items into the machine.
5. Turn off the loading chute and lock the machine.
6. Place a button and wrench it into place.
7. Click the button with the multitool, then click "connect component".
8. Click the Build-A-Vend with the multitool and select "vend random".
9. Stop linking with the multitool, then press the button.
10. Nothing happens.

### Expected Behavior

I expected pressing the button to vend a random item from the machine.

### Additional Information & Screenshots

Reporting on 8/18/2024, goon #3

**Comment by soleilan** [comment]
I believe them ignoring commands is intended, but should probably be unable to connect it at all

**Comment by cringeybabey** [comment]
Why would this be intended if it works just fine with normal vendors? I had a couple fun ideas relating to this, so that's a little disappointing to hear

**Comment by MetricDuck** [comment]
It doesn't work currently because player vending machines store their products in a differently named product list to normal vending machines, so mech comp commands are interacting with an empty list.

Would be simple enough to either strip out the mechcomp signals or create custom ones that use the correct list, I'll flip a coin

**Comment by MetricDuck** [comment]
I disabled the functionality entirely for now, as just allowing it to throw arbitrary items would enable the creation of rather potent turrets... One for a forum thread discussion perhaps.
