### ISSUE TITLE
Claiming lawbringer reward drains some battery and pops a message?

### ISSUE THREAD

**Issue by trazodont** [goonstation/goonstation#20376]
### Labels

[BUG]

### Description

idk lawby weird

### Steps to reproduce

1. be hos
2. claim lawby

### Expected Behavior

not drain my battery (20% is nuts, it was lower i just screenshotted it a bit later)

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/2714cf80-a5c9-4fbb-b529-9c12d1b8342e)

**Comment by RubberRats** [comment]
Was the cell in the energy gun you used fully charged? If it's not, the missing charge will carry over when you convert it.

**Comment by trazodont** [comment]
> Was the cell in the energy gun you used fully charged? If it's not, the missing charge will carry over when you convert it.

Claimed right outta the locker, never fired it says it fires on its own as your claiming it.

**Comment by Retrino** [comment]
ok so fun fact about this one, the reason the cell isnt full is because it is actually shooting the job reward claim menu. ?????.

**Comment by trazodont** [comment]
> ok so fun fact about this one, the reason the cell isnt full is because it is actually shooting the job reward claim menu. ?????.

Gotta detain that mfing detain menu

**Comment by JORJ949** [comment]
Fixed in #21096
