### ISSUE TITLE
Armory door health seems unusually low

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#20411]
### Labels

[BUG]

### Description

I haven't actually timed it, but the new unhackable armory doors seem to go down to damage noticeably faster than before.

### Steps to reproduce

1. Look at code to find number
2. Or hit one a bunch and count

### Expected Behavior

I expect the armory doors to continue to be the sturdiest doors on station.

### Additional Information & Screenshots

If I'm understanding the code correctly, it looks like the new armory doors are based off of regular airlocks, which have 600 health, while command airlocks (which they used to be if my memory isn't terrible) have 800.

**Comment by JORJ949** [comment]
It depended from map to map before whether it was a sec airlock or command, feel free to PR a health buff if you think it needs it
