### ISSUE TITLE
"i'm in" medal not awarding skin

### ISSUE THREAD

**Issue by adamok5002** [goonstation/goonstation#20440]
### Labels

[BUG]

### Description

is "i'm in" medal not awarding an AI skin like it is suposed to

### Steps to reproduce

1. Achieve 40k(?) medal, receive AI skin
2. Goonhub registers medal change
3. Skin not awarded

### Expected Behavior

Skin to be awarded

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/96cf81af-63c9-47bc-baa1-76031f69ee07)
![image](https://github.com/user-attachments/assets/703e3f05-16ab-4416-8e05-9e6251ef7efb)

**Comment by Cherman0** [comment]
Casued by case sensitivity: It looks for `"I'm In"`, the medal is `"I'm in"`

**Comment by Cherman0** [comment]
Should be fixed by [#20446](https://github.com/goonstation/goonstation/pull/20446)
