### ISSUE TITLE
Getting cloned clears your Job + Job Benefits

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#205]
**Describe the bug**
Getting cloned nulls your job, or something. I don't know exactly what it is in code terms, but this has a cascade of effects. For instance, this means that cloned security officers can be hit with Sleeper Agent event. You also lose your job traits, like faster cuffing or chair flip immunity.

**To Reproduce**
1. Join as security officer
2. Die, then get cloned
3. Get chair-flipped

**Expected behavior**
Job should be transferred with the mind, independent of changing mobs or being cloned.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Connie-Dun** [comment]
A few other effects I've noticed in the past is that this also makes you stop gaining job XP for the shift, and makes you unable to claim your job-specific rewards.

**Comment by Tarmunora** [comment]
@flrsh Did your cloning change fix this?

**Comment by Tarmunora** [comment]
Will test this

**Comment by Tarmunora** [comment]
This has been fixed
