### ISSUE TITLE
PDA Flashlights do not work properly if activated in hand

### ISSUE THREAD

**Issue by ATDoop** [goonstation/goonstation#2051]
[BUG]

**Describe the bug**
Toggling the PDA flashlight while it is in your hand causes the light to disappear if you equip the PDA.
**To Reproduce**
1. Hold your PDA in your hand
2. Activate the flashlight
3. Equip the PDA by putting it in your ID slot, belt, or pocket.
4. The light disappears.

**Expected behavior**
The light should not disappear.

**Screenshots**

PDA flashlight is activated while held in hand
![dreamseeker_2020-09-03_16-40-39](https://user-images.githubusercontent.com/1959416/92165037-67faf000-ee04-11ea-8b05-b8f4c603d233.png)

PDA light disappears once equipped
![dreamseeker_2020-09-03_16-40-48](https://user-images.githubusercontent.com/1959416/92165046-6c270d80-ee04-11ea-8430-20ca7365f7c9.png)

**Comment by pali6** [comment]
Ah hell, probably getting removed in `dropped` without checking what the new location is.
