### ISSUE TITLE
You can roll assistant jobs with them unwanted

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#20566]
### Labels

[BUG] [MAJOR]

### Description

Not roll a job i have unwanted

### Steps to reproduce

1. Have Research assistant unwanted
2. Roll headrev
3. Be forced into research assistant despite job prefs (See additional info for prefs)

### Expected Behavior

Not roll unwanted job

### Additional Information & Screenshots
https://goonhub.com/rounds/187516 (Under the Antagonists tab you can see that I rolled headrev assistant)
I always seem to get forced to be staffie headrev aswell with preferences like this where it makes me staffie instead of anything in a higher pref though this could be intended revolution behaviour.
![image](https://github.com/user-attachments/assets/46d904cd-b94b-4ccb-8339-aff303a3d8fd)

**Comment by TobleroneSwordfish** [comment]
errrr @Sord213
