### ISSUE TITLE
Hairy trait doesn't work for observers

### ISSUE THREAD

**Issue by nova2053** [goonstation/goonstation#20567]
### Labels

[BUG] [TRAITS]

### Description

Observing a round as a normally hairless mutantrace with the "hairy" trait doesn't give you hair

### Steps to reproduce

1. Select a saurian, bovine, or blattodean character with the hairy trait in character setup
2. Join round as observer

### Expected Behavior

I expected to have hair, since I chose the hairy trait

### Additional Information & Screenshots

Mutantrace characters with hair who joined the round normally still had real hair, so this seemingly only applies to observers.
Just for clarification, you don't get hair as a ghost OR in the afterlife bar if this bug happens.

**Comment by TobleroneSwordfish** [comment]
Fixed in 78e917a
