### ISSUE TITLE
long scarves can no longer be made

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#20585]
### Labels

[BUG]

### Description

when attempting to knit a long scarf, the option will not be in the radial

### Steps to reproduce

1. stack 5 yarn balls
2. click with knitting needles
3. observe lack of long scarf

### Expected Behavior

be able to knit long scarves

### Additional Information & Screenshots

doesnt work with both regular and crochet needles
![image](https://github.com/user-attachments/assets/38d1fb3d-4df6-4787-92d8-6d9587bf7b10)

**Comment by UrsulaMejor** [comment]
fixed with ded9862
