### ISSUE TITLE
Cannot update cloudsaves when at cloudsave cap

### ISSUE THREAD

**Issue by Xkeeper0** [goonstation/goonstation#20584]
### Labels

[BUG]

### Description

overwriting cloud saves does not seem to actually work. why is there a short description when it's almost always the title

### Steps to reproduce

1. log into goon 4
2. load cloud save "lizard"
3. edit traits to remove "bald" and add "hairy"
4. save cloud save "lizard", get "savefile saved!"
5. load cloud save, old traits are loaded
6. join server 3, load lizard cloud save, old traits are loaded

this also affects flavor text and profile name (not the char name, the _profile_ name)

possibly related to #[19573](https://github.com/goonstation/goonstation/issues/19573)  whicho nly mentions occupations

### Expected Behavior

cloud saves actually work

### Additional Information & Screenshots

https://discord.com/channels/182249960895545344/890226559691157524/1281370002561437768

**Comment by Tarmunora** [comment]
could not reproduce. try again after https://github.com/goonstation/goonstation/commit/d0425e5bb3b5c089a0108e55dfb3b1751238838d goes live and see if it still reports success or not I guess

**Comment by Xkeeper0** [comment]
saving over my prevoius save and immediately loading it loads the old data here.

**Comment by soleilan** [comment]
#19573
from my old testing, the saved file only "syncs" after the server restarts for the next round, at which point you can hit load and actually get the save, before the server restart hitting load will only give you the old save no matter how much you press save

**Comment by Tarmunora** [comment]
🤷 in live testing, I can hop on 4, override one of my cloudsaves, load it, and the changes load fine
then swap to server 3, load the overridden cloud save, and the changes load fine there too.
No clue why single-server cloud stuff would be having issues, but for cross-server, the thing to note is that cloud saves are fetched on first connection, so once you've already connected to a server, cloud saves made on a different server won't get propagated over

**Comment by Tarmunora** [comment]
API bug. Mitigation is to be at at most 14/15 savefiles for now.

https://github.com/goonstation/api/issues/45?ts=4
