### ISSUE TITLE
Interaction menus are blank white

### ISSUE THREAD

**Issue by qrqwerqwr** [goonstation/goonstation#2058]
[BUG]

**Describe the bug**
Whenever I open an interaction menu, like someone's inventory or a machine interface, it appears normal except that I can't interact with it at all besides closing it. If I try to reopen the menu, or any other interaction menus, it turn blank white with only the window options at the top. Restarting byond rarely works, and the only "fix" I've found is making a chemical group in a chem dispenser and then using it to fill a beaker. I've noticed a couple of times that it's shown and error while attempting to reach a certain web address. This leads me to believe that byond is unable to reach the address where inventory and such is being hosted.

**To Reproduce**
1. Open any interaction menu
2. Close the interaction menu
3. Attempt to open any interaction menus
4. Get flashbanged by your monitor

**Expected behavior**
I expect the interaction menus to show what they are meant to display
**Screenshots**
https://ibb.co/0Xf39mv
https://ibb.co/jw1MSPj

**Additional context**
It only started recently, after the changes to the UI

**Comment by Carbadox** [comment]
Most likely an issue on the users side with Internet Explorer
