### ISSUE TITLE
Saurian scale/hair colors too saturated with hairy trait

### ISSUE THREAD

**Issue by nova2053** [goonstation/goonstation#20590]
### Labels

[BUG] [TRAITS]

### Description

Choosing the hairy trait in character setup and joining a round as a saurian causes your scale colors to be brighter than they should be

### Steps to reproduce

1. Load a saurian character with hairy trait
2. Declare ready for round (unsure if it needs to be before roundstart)
3. Wait for round to begin

### Expected Behavior

I expected my scale/hair colors to be desaturated as they were before

**Comment by TobleroneSwordfish** [comment]
Fixed by using the fix proc in this fix commit: ceaf430
