### ISSUE TITLE
Obsidian crown uses deplete when you ram a wall with a pod 

### ISSUE THREAD

**Issue by new525** [goonstation/goonstation#2060]
[BUG]
**Describe the bug**
When you ram a pod into wall while wearing the obsidian crown it doesn't teleport you but does count as being hit, If you ram three walls you'll instantly die in your pod. It doesn't appear to leave a particle field but it's probably just in the pod.

**To Reproduce**
1. Wear obsidian crown
2. Enter Pod
3. Begin ramming said pod into walls 

**Expected behavior**
I didn't expect it to count as being hit

**Comment by Carbadox** [comment]
Tested locally, this is longer an issue.
