### ISSUE TITLE
Tiny little red/grey stripes on some pipe ends still

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#20600]
### Labels

[BUG]

### Description

^

### Steps to reproduce

1. Go to atlas engine room
2. Look at the north inlet port pipes
3. Tiny little itty bitty stripes

### Expected Behavior

I expected no stripes

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/7f6d1c70-7271-4959-ac42-20fb2ff48ba7)

**Comment by TobleroneSwordfish** [comment]
@Laboredih123

**Comment by Laboredih123** [comment]
i honestly dont see a problem please circle them

**Comment by Laboredih123** [comment]
wait hm

**Comment by Laboredih123** [comment]
not a bug
