### ISSUE TITLE
Ghost drones can create empty stacks of floor tiles

### ISSUE THREAD

**Issue by ATDoop** [goonstation/goonstation#2062]
[BUG]

**Describe the bug**
If you pick up a stack of floor tiles with your magtractor and use every tile in the stack, your magtractor will still be holding a tile stack when it should be depleted. If you then drop this stack and examine it, it'll tell you it has 0 tiles left in the stack.

**To Reproduce**
1. Be a ghost drone
2. Use your magtractor to pick up a stack
3. Deplete stack
4. Drop your now empty ghost stack and examine it

**Expected behavior**
The stack should disappear when it runs out of tiles and is dropped.

**Screenshots**
![dreamseeker_2020-09-04_17-04-24](https://user-images.githubusercontent.com/1959416/92284760-c2618280-eed0-11ea-8694-5c5e1850d383.png)

**Additional context**
I tested this with a stack of metal sheets and couldn't reproduce the issue, it may only effect floor tiles.

**Comment by DabirSA** [comment]
Still happening.
![image](https://user-images.githubusercontent.com/17720989/93030763-71166900-f61d-11ea-9310-14f11b6948d0.png)
