### ISSUE TITLE
Planting something in a tray that had a synthetic cat produces an immediately dead plant

### ISSUE THREAD

**Issue by trazodont** [goonstation/goonstation#20621]
### Labels

[BUG]

### Description

synth cats cause dead plants

### Steps to reproduce

1. plant a synthetic cat strange seed, let it grow
2. once it pops from the tray, plant something else in the same tray
3. observe dead plant

### Expected Behavior

not be dead :)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/3fdb82176efa937b54ab18f9bab23c4bba2c67ea
