### ISSUE TITLE
Some Oshan areas sometimes contain no air at roundstart

### ISSUE THREAD

**Issue by pali6** [goonstation/goonstation#2063]
[BUG]

**Describe the bug**
Oshan bar and the east hallway (near engineering) sometimes start airless. It doesn't happen consistently and never happened to ma locally. I reckon it's some kind of a race condition. Possibly air group getting initialized before the turfs' air gets set but that makes no sense because it happens in New. 

**To Reproduce**
1. Start a round on Oshan 
2. Look into the bar or into the hallway, there's a chance there's no air there

**Expected behavior**
Air.

**Comment by MarkNais** [comment]
What I've noticed: The "stair" turfs in the east hallway often have an airless soundscape when walking over them.
