### ISSUE TITLE
Duplicate Cryokinesis

### ISSUE THREAD

**Issue by AnonymousUserTheOnly** [goonstation/goonstation#20662]
### Labels

[BUG]

### Description

There are two instances of Cryokinesis in the gene pool.

### Steps to reproduce

1. Get lucky and see both appear in one person, or try to combine the invalid one with glowy.

### Expected Behavior

The typical expectation is for the cryokinesis to fuse with glowy to make Cold Resistance.

### Additional Information & Screenshots

Not sure what the odds are of the bad instance, but it has an identical appearance to the good instance.  The **only** tell of it being the bad instance is it not combining in the storage with valid combinations.  This creates confusion because of expecting it to combine and it failing to combine.

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/4d937f7e5a82a2455ffe580479467e77502637c5
