### ISSUE TITLE
New Changes to Cloning Render Genetic Analysis Mode Inoperable

### ISSUE THREAD

**Issue by Slazzy** [goonstation/goonstation#2069]
[BUG]

**Describe the bug**
Due to the recent changes to the cloning mechanic that now has a body "prepped", genetic analysis mode cannot be enabled.

**To Reproduce**
1. Open cloning computer UI.
2. Select genetic analysis mode.
3. Act confused when nothing happens.

**Expected behavior**
Turn on genetic analysis mode when selected on the cloning computer.

**Screenshots**
N/A

**Additional context**
Apparently in the coding there is a check for 'is cloner occupied' before allowing the genetic analysis mode to be enabled.  As there is now always a body in it, the mode cannot be enabled.

**Comment by ZeWaka** [comment]
might be fixed by @flrsh or @Xkeeper0 ?

**Comment by flrsh** [comment]
Fixed in #2160!
