### ISSUE TITLE
Cloning Pod Stops Functioning Mid-cycle

### ISSUE THREAD

**Issue by Slazzy** [goonstation/goonstation#2070]
[BUG]

**Describe the bug**
When attempting to clone someone, the cloner activates but then stays at a certain percentage (around half) and will not complete the cycle.  Attempting to clone another individual has no effect either.  The cloner is for all intents and purposes inoperable.

**To Reproduce**
1. Select individual for cloning.
2. Cloning procedure starts.
3. Select pod, see current progress indicator - does not proceed.
4. Attempt to restart that individual or another's cloning process to no avail.

**Expected behavior**
Complete the cloning process to allow for proper operation of the cloner.

**Screenshots**
N/A

**Additional context**
Wish I had specific rounds noted.  This has happened four or five times to station's I've been on.  Talking in Discord, there seems to be some consensus from others that have seen it that it was individuals that were cloned multiple times already, but I cannot confirm this for the occasions it occurred in my games.  

This first occurred a couple weeks ago and the most recent occurrence for me was Friday night at around 10-11pm Eastern (may have been after the most recent update to cloning).  The issue existed before this update, however.

**Comment by Tiggersaurus** [comment]
Can confirm this. Tried to troubleshoot at the time, seemed like it thought there was both someone in and not in the pod at the same time. Had someone stuck in for 20+ mins while the biomatter slowly drained.

There was plenty of biomatter at the start of clone, unable to force eject them out.

**Comment by ThePotato97** [comment]
Closing as it seems to have been fixed
