### ISSUE TITLE
Afterlife Apparel vendors create duplicate listings

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#20806]
### Labels

[BUG][MINOR]

### Description

Afterlife bar apparel vendors erroneously have their original listings

### Steps to reproduce

1. Go to afterlife bar
2. See that the /afterlife subtype just addes to the original listing because it create_products calls the parent type first
3. See duplicate listings

### Expected Behavior

afterlife to probably not be a subtype of each and instead be afterlife/security or a var

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/367018d9-4b05-4bba-a527-45280adc5a00)
Our culprit code:
![image](https://github.com/user-attachments/assets/ed52b80b-b257-4873-8f5b-ecf222f1e092)

**Comment by Retrino** [comment]
grrr
