### ISSUE TITLE
Player Panel is unstyled

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#20822]
### Labels

[BUG]

### Description

No interface style on the Player Panel

### Steps to reproduce

View player panel. Light or Dark Mode does not matter.

### Expected Behavior

Some pretty styling and to respect Dark Mode.

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/7f3ed600-d8bb-44a9-b14c-4a937b29c4bb)

**Comment by ZeWaka** [comment]
Should be fixed now
