### ISSUE TITLE
Can't change dispense amount on reagent dispensers

### ISSUE THREAD

**Issue by MintyPhresh** [goonstation/goonstation#20839]
### Labels

[BUG]

### Description

Dispense amount slider seems broken.

### Steps to reproduce

it's scroinched.
![image](https://github.com/user-attachments/assets/e365ef43-3c3d-4c23-9ef0-b7f503e96c21)

### Expected Behavior

I think I should be able to click it

**Comment by mordent-goonstation** [comment]
Patched in #20833
