### ISSUE TITLE
Input Name Popup Pitch Black

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#20851]
### Labels

[BUG]

### Description

Join as a job that lets you choose a name?  Good luck, you can't see what you're writing!

### Steps to reproduce

1. Join as Clown, Test Subject, et cetera
2. Not see letters.

### Expected Behavior

See letters.

**Comment by TobleroneSwordfish** [comment]
Seems like an issue with TGUI lightmode

**Comment by TobleroneSwordfish** [comment]
Closing in favour of #20978
