### ISSUE TITLE
Borg became short-sighted.

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#2085]
[BUG]

**Describe the bug**
As an AI, the cyborg I was in spontaneously became short sighted.

**To Reproduce**
I am not sure how to reproduce. I uploaded into an shell right before an ion law hit, if that is useful?

**Expected behavior**
Not to be short sighted like a human with the short sighted gene?

**Screenshots**

![image](https://user-images.githubusercontent.com/68360623/92322603-6f322180-efef-11ea-82da-8e1199741008.png)

**Additional context**

**Comment by Tiggersaurus** [comment]
I've had similar once before, but it was like I had the blind trait. I never reported it coz at the time (a few months ago) I just assumed it was admin shenanigans on assjam >.>

**Comment by amylizzle** [comment]
There's not really enough information here to do anything with this bug. Yes, borgs can have the shortsighted effect applied to them, but there shouldn't be any cases where it is except admin shenanigans. Closing.
