### ISSUE TITLE
Reverse-Engineering gas

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#2086]
Using the power of the mechanic lab you can analyze gas clouds and make them (they do not stay the same gas that you scanned, they just default to a cloud)

**BUG**
1. Get a device analyzer
2. Find a ckoud of gas, this could be miasma or maybe a toxic fart
3. Scan the cloud
4. Use the analzyer on the ruckingenur kit and blueprint it
5. Put it in the Reverse-Engineering Fabricator and get a frame of it
6. Use a soldering iron on the frame
7 .Good job, you have a useless cloud and just wasted 3 material

**Expected behavior**
The Analyzer shouldn't be able to scan clouds

**Comment by pali6** [comment]
Hahaha, reverse engineering fart clouds, we reached peak Goonstation.

**Comment by Tarmunora** [comment]
fixed by https://github.com/goonstation/goonstation/commit/29044248c4c1f1c6194f7323eac03bf262c2373d
