### ISSUE TITLE
Fabric from cutting jumpsuits is unusable in fabricators

### ISSUE THREAD

**Issue by MintyPhresh** [goonstation/goonstation#20939]
### Labels

[BUG]

### Description

Title.

### Steps to reproduce

1. Cut a jumpsuit into fabric using a pair of scissors.
2. Load it into a fabricator.
3. Click on the fabricator, bringing up the UI.
4. Fabric is spit back out.

### Expected Behavior

Fabric should be usable in fabricators.

**Comment by TobleroneSwordfish** [comment]
cf724ff
