### ISSUE TITLE
Puritan corpse explosion breaks cryo cells

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#2095]
[BUG]

**Describe the bug**
In an effort to save my malformed puritan husk, someone tried to stick me in a cryo cell. My body of course gibbed, but the cryo cell still displayed that there's a body inside of it. This breaks the cell as you cannot interact with it anymore.

**To Reproduce**
1. Stuff puritan inside cryo
2. Puritan corpse gibs
3. Cryo broke, medbay cries

**Comment by PrimeNumb** [comment]
Doesn't actually break the cell, it's just the icon that doesn't update properly. You can still interact with it normally, and doing anything that triggers an icon update (like turning it on and off) will "fix" it. Not great, but not as severe of a bug.

**Comment by virvatuli-gh** [comment]
ancient, no longer applicable bug
