### ISSUE TITLE
Invisible wall atlas toxins ship

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#20955]
### Labels

[BUG] [MAJOR]

### Description

There is an invisible wall in atlas toxins

### Steps to reproduce

1. Atlas round
2. look around toxins
3. invisible wall half way down

### Expected Behavior

No invisible wall

### Additional Information & Screenshots

![image](https://github.com/user-attachments/assets/cbc11313-9c5d-4e3e-a6a0-e3f3d5bff6e8)
its here

**Comment by TobleroneSwordfish** [comment]
Fixed in 780cc67
