### ISSUE TITLE
Chameleon Perma Invis

### ISSUE THREAD

**Issue by ZephyrTFA** [goonstation/goonstation#2096]
[BUG]

**Describe the bug**
When you move with chameleon cloak activated, or in fact do anything, you stay cloaked.

**To Reproduce**
1. Get Chameleon mutation
2. Use Chameleon mutation
3. Do something that should break cloak, such as interacting with something on a different tile or moving.
4. You stay cloaked anyway

**Expected behavior**
The cloak to be disrupted as intended when you move or perform any action.

**Additional context**
Rodney can confirm this as I may have used it in a round and gotten scolded by him for it.

**Comment by flappybatpal** [comment]
I fixed this but broke it again today. I turned off and turned on the power after getting it from a genebooth (assumed it was off) then relatively soon after moved exactly as the cloak turned on and it became stuck enabled.

I can't see a logical flaw as cloak is removed by a signal that is attached to the cast, OnLife should always be getting called, TIME is always updating and the other checks should pass...
