### ISSUE TITLE
AI Eyes can be stamcrit

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#21010]
### Labels

[BUG][MINOR]

### Description

When disarming/punching an AI eye they lose stamina and can be stamcrit

### Steps to reproduce

1. Be able to see AI eyes (ectogoggles, eyes, etc)
2. Disarm/punch AI eye a lot
3. AI eye "falls over" and does the cut-off message of a normal stamcrit

### Expected Behavior

My incorporeal eye to not have stamina

**Comment by TobleroneSwordfish** [comment]
Is this too funny to fix though?
