### ISSUE TITLE
void terrainify isnt properly accounting for cargo

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#21060]
### Labels

[BUG]

### Description

when a map has the void generation, it will occasionally have pretty severe blockages in front of cargos import and export. (sometimes unbreakable things)

### Steps to reproduce

1. void instead of space
2. see rng has cursed you with mass blockages in the cargo line
3. cry and make a mechcomp seller to cope

### Expected Behavior

like normal terrainify, leave the path for cargo clear

**Comment by Azrun** [comment]
Would have assumed this would be handled by d80109fcd but the cleanup might not be properly handled due to trying to use the global proc.

**Comment by Azrun** [comment]
Found it!
