### ISSUE TITLE
Former canbombs still glow

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#211]
**Describe the bug**
Dud canbombs revert to normal canisters but still keep the simplelight

**To Reproduce**
1. Make dud canbomb
2. Trigger detonator
3. The glow has not disappeared

**Expected behavior**
Canisters never glow on their own

**Screenshots**
![image](https://user-images.githubusercontent.com/63235460/79067154-c8ef2380-7cbd-11ea-814d-d561fd8f76d5.png)

**Comment by ZeWaka** [comment]
to fix this, handle the light created on canbombs properly in the dud branch of the explosion proc

also consider switching to simplelight
