### ISSUE TITLE
friday hos slot not showing up despite it being friday and not having played hos

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#21113]
### Labels

[BUG]

### Description

title says it all- game counted me as illegible to friday HoS

### Steps to reproduce

probably needs reproducing. joined late previous round as secoff, couldn't find hos in jobs during roundstart, slot unable to be taken in latejoin

### Expected Behavior

head the securities :(

### Additional Information & Screenshots

![Image](https://github.com/user-attachments/assets/a0a5b44f-2557-425a-a281-8fbfa8db092b)
![Image](https://github.com/user-attachments/assets/46702cc5-443d-4ee9-9ea5-3dbcd4ae8732)

**Comment by Retrino** [comment]
timezone issue? the times are kinda wonky if youre going off est or cst, it opens thursday night and ends friday night

**Comment by 444Portal** [comment]
time zone issue, its 1AM on UST which is what the server uses, its a saturday morning now
