### ISSUE TITLE
Vision modifiers interfering with each other

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2113]
[BUG]

**Describe the bug**
Vision modifiers tend to interfere with each other resulting in either both not functioning or only 1 of them functioning

**To Reproduce**
quickest way to reproduce would be
1. Have Meson Goggles on
2. Get X-Ray/Night Vision Mutation
3. See error
Alternatively
1. go to DOC at faint signal an purchase Ecto Eye and Meson Eye
2. Install Both in self
3. Cant see ghosts with meson Eye on (not sure if you can while its off either tbh)

**Expected behavior**
I expect them to combine effects of both honestly rather than fuck with each other

**Screenshots**
Ill add screen shots in the future if i get the chance to

**Additional context**
Its really hard to hunt ghosts if all the lights are off.

**Comment by pali6** [comment]
Yeah, known, vision life process is an abomination and I need to forge the weapons to slay it.

**Comment by frawhst** [comment]
probably fixed by the props update? xray and night vision certainly work now
