### ISSUE TITLE
AI Shell names will sometimes have "the" added to them

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#21181]
### Labels

[BUG][TRIVIAL]

### Description

AI shells will sometimes be SHELL/the AI NAME

### Steps to reproduce

1. Pick an AI name thats an actual word(????) like "friend"
![Image](https://github.com/user-attachments/assets/e28b43d6-1b0d-405e-9633-1fd5891f9570)
2. Deploy to a shell
3. Be SHELL/the friend
 ![Image](https://github.com/user-attachments/assets/eff0f83e-0270-4c06-bcc7-8753be377ee6)

### Expected Behavior

Shell name to be accurate

### Additional Information & Screenshots

![Image](https://github.com/user-attachments/assets/6b993b2d-726e-45bb-b14e-bc7e654069b3)
Reason I think is because it calls the actual thing itself, ive seen this used for chat stuff so it is probably adding "the" automatically as friend is a word, should probably call mainframe.name instead or something.

**Comment by 444Portal** [comment]
happens when the first letter is lower case
