### ISSUE TITLE
the crawling monstrosity

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#21197]
### Labels

[BUG]

### Description

the summon "crawling monstrosity" from the harbinger portals do nothing

### Steps to reproduce

1. see the crawling monstrosity near portal
2. lament that it does not move
3. does not attack
4. it do make a funny noise though once in awhile

### Expected Behavior

it to do something

**Comment by TobleroneSwordfish** [comment]
Fixed in aa71de6
