### ISSUE TITLE
ArtLab heater pad stops glowing blue if temp is low enough

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#2120]
[TRIVIAL]

**Describe the bug**
Once the artifact lab heater pad reaches roughly 245 K, it stops glowing blue and returns to the default black sprite.

**To Reproduce**
1. Set heater pad to a low temperature
2.Observe that it goes from black, to blue, back to black

**Expected behavior**
The pad continues glowing blue while the temperature is low.

**Comment by ThePotato97** [comment]
Look like there's a gap in the overlays, I'll fix it.
![image](https://user-images.githubusercontent.com/10260415/92551305-95f19180-f255-11ea-9c95-8d4767a20ca3.png)
