### ISSUE TITLE
Tracking Implant GPS track not live updating

### ISSUE THREAD

**Issue by Dazzelmist** [goonstation/goonstation#21244]
### Labels

[BUG]

### Description

Tracking implant has to be manually updated to give "live" location of the target.

### Steps to reproduce

1. Shoot person with tracking implant (via implant gun)
2. Try to track on GPS
3. Notice it only shows you the location of when you clicked track and doesnt track the target "live"
4. Be very frustrated as sec and keep clicking track to see where the target has gone

### Expected Behavior

I expected the tracker to live update so i can properly chase the crimer

### Additional Information & Screenshots

Not sure if bug or intended.
Just posting this to make sure.

**Comment by Tarmunora** [comment]
For now at least, this is intended behaviour

**Comment by Dazzelmist** [comment]
Ah alrighty.
Thank for the response :>
