### ISSUE TITLE
Black rectangle blocking avatar in Clothing Booth

### ISSUE THREAD

**Issue by DGC9Crew** [goonstation/goonstation#21281]
### Labels

[BUG]

### Description

A weird black rectangle is blocking the character avatar in the clothing booth

### Steps to reproduce

1. Want to get sick clothing in clothing booth
2. Put cash money inside
3. Go inside
4. what in visual bug is this

### Expected Behavior

To not have a black rectangle blocking my view

### Additional Information & Screenshots

![Image](https://github.com/user-attachments/assets/19ccfb2d-5a7c-4bb6-9441-a75975e08825)
![Image](https://github.com/user-attachments/assets/6d324e21-6d81-4d22-93ae-2d0ca9ef48e7)

Not sure what triggered it, as in prior rounds it worked just fine.

**Comment by DisturbHerb** [comment]
This issue concerns hoodie hair masks. Paging @Glamurio

**Comment by Glamurio** [comment]
Couldn't replicate on live branch, prooobably caused by a test merge of #18190
