### ISSUE TITLE
Hair dye does not change the colour of all of your hair layers, just one

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#2128]
[BUG]

**Describe the bug**
As the title says. I have been aware of it for a long time but I did not care about it enough to post a report. Having ugly hair after using a dye yet again changed my mind

**To Reproduce**
1. Have a hairstyle that consists of 3 layers
2. Dye your hair
3. Your hair is ugly now
4. Scream

**Comment by Superlagg** [comment]
Does it do this when you set the bottle to color all layers? It changed recently so that you can select which layer gets dyed.

**Comment by TTerc** [comment]
Oh, I was not aware of that change. I'll test it later and close the issue if that solves it. Might be just me being dumb

**Comment by TTerc** [comment]
Yeep, just me being dumb
