### ISSUE TITLE
PDA Not Receiving Any Messages with Ringer & Send/Receive On

### ISSUE THREAD

**Issue by itsloley** [goonstation/goonstation#21291]
### Labels

[BUG]

### Description

my PDA wasn't receiving any messages for the entire round, i had my ringer on and send/receive on and never got any paycheck notifs, security alerts, etc

### Steps to reproduce

i'm really not sure, i was in a round from the start and only got one message for the entire duration. it happened once right after i tried changing my scanner from gas to forensics (in the file manager), and it was working right before that

### Expected Behavior

to recieve messages!

**Comment by itsloley** [comment]
forgot to add the 'major' tag to this :s

**Comment by itsloley** [comment]
after another round it seems like it happened right after i tried changing my scanner from gas to forensics (in the file manager), it was working right before

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/pull/18190?ts=4#discussion_r1837173144
