### ISSUE TITLE
Robots duplicate shot foam darts

### ISSUE THREAD

**Issue by AlsoKnownAsAlias** [goonstation/goonstation#21313]
### Labels

[BUG]

### Description

Foam dart projectiles duplicate after hitting a robot

### Steps to reproduce

1. fire a foam dart gun at a robot (I've tested it to work on a firebot, guardbuddy, medibot, cleanbot, floorbot, and securitron. It did not work on the mulebot)
2. the foam dart duplicates. one hits the bot and falls to the floor, the other continues on through the bot.

### Expected Behavior

I don't expect the conservation of energy to be violated

### Additional Information & Screenshots

![Image](https://github.com/user-attachments/assets/2b72c27b-1699-4513-aaf0-ac06e476e45f)
![Image](https://github.com/user-attachments/assets/42081c87-ccd6-4201-b5a1-d6c7dc95846e)

**Comment by AlsoKnownAsAlias** [comment]
this seems similar to https://github.com/goonstation/goonstation/issues/8700

**Comment by pgmzeta** [comment]
The issue is that drop_as_ammo gets called both in on_hit and on_max_range_die, since hitting the bot doesn't result in the projectile stopping as they're not dense
