### ISSUE TITLE
Blindfold causes eye damage while welding

### ISSUE THREAD

**Issue by Mikeistaken** [goonstation/goonstation#21378]
### Labels

[BUG][MINOR]

### Description

Blindfold causes damage to eyes despite not being able to see

### Steps to reproduce

1. Get a blindfold
2. Wear the blindfold
3. use a welding tool on something
4. eye damage ensues

### Expected Behavior

to not gain eye damage (or atleast reduce eye damage) when welding

### Additional Information & Screenshots

I'm not sure if its intentional or not to promote the use of a welding helmet, but for it to give less visibility then the welding helmet, you'd think that it would protect your eyes at least a little bit

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/77de052a86073d6a7e708652ecc8798df77d7b00
