### ISSUE TITLE
Breaching charges in quick succession occasionally only trigger one ex_act

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#21403]
### Labels

[BUG][MAJOR]

### Description

breaching charges placed immediately after each other occasionally only trigger one ex_act 

### Steps to reproduce

1. Place 2 breaching charges on an object (in my case a law rack) in quick succession
2. ![Image](https://github.com/user-attachments/assets/c314a59f-1d61-4a6c-bcc4-0065c4a2405d)
3. Observe how sometimes law rack only does one ex_act

### Expected Behavior

Breaching charges to cause individual ex_acts

### Additional Information & Screenshots

![Image](https://github.com/user-attachments/assets/c4d665b8-3dd0-4a0e-9273-8cec7781d1af)
it works _sometimes_

**Comment by Tarmunora** [comment]
Simultaneous or near-simultaneous explosions will stack, adding together, to save on processing
