### ISSUE TITLE
Rajaijah doesn't cause fighting to happen

### ISSUE THREAD

**Issue by jan-antilles** [goonstation/goonstation#2140]
[BUG]

**The Bug**
When dosed with Rajaijah, my character did not take any aggressive actions against anyone, despite having the chat messages, shaking, brain damage, and stumbling associated with Raj poisoning.

**To Reproduce**
1. Be dosed with Rajaijah, the Madness Toxin
2. Stand near the pitiful mortals that you could totally fight, like, right now
3. Despite messages about hulking up and flipping out, observe that you are not compelled to actually flip out

**Expected behavior**
 The AI should take over my character and begin robusting everyone around me.

**Screenshots**
![Goonstation RP Overflow Mars Correctional Construct Golf 2020-09-10 015646](https://user-images.githubusercontent.com/67385345/92696179-217b2900-f30f-11ea-8844-7adf4274328c.png)

These people are too alive to have been in contact with me. (The straightjacket was placed on my character after the effect had worn off, but we were RPing it out.)

**Comment by pali6** [comment]
Possibly also affects other stuff like the crown created lich.

**Comment by Tarmunora** [comment]
closed by https://github.com/goonstation/goonstation/commit/f73c51a35ef4739a0723396778ff14a0d14eaba1
(addendum: void_crown lich doesn't set it's AI to aggressive anyways)
