### ISSUE TITLE
AI Law rack doesnt get breached by breaching charges

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#21402]
### Labels

[BUG][MAJOR]

### Description

Law racks need minimum 6 breaching charges to blow, maximum 12

### Steps to reproduce

1. Slap a breaching charge onto a law rack
2. ![Image](https://github.com/user-attachments/assets/d1272e1b-8f88-4285-85c8-1c00e4ce718e)
3. Observe how breaching charge only does an ex_act of 3, unlike the previous 1

### Expected Behavior

2 Breaching charges should consistently destroy a law rack

### Additional Information & Screenshots

Almost definitely came with the fix for instantly melting down nuclear reactors.

**Comment by Tarmunora** [comment]
Actually, breaching charges not 2-shotting law racks is probably a good thing, and was a happy accident of another change
