### ISSUE TITLE
Security computer UIs do not autoscroll

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#21421]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Log into security computer and open Secmate
2. Enter in security records for someone
3. See it working, but it not auto scrolling to the bottom to most recent updates

### Expected Behavior

For it to scroll downwards as new text is output on the computer

**Comment by mordent-goonstation** [comment]
Duplicate of #21387.
