### ISSUE TITLE
Security headset antag description doesnt clear

### ISSUE THREAD

**Issue by JORJ949** [goonstation/goonstation#21440]
### Labels

[BUG][MAJOR]

### Description

The "good." part of the security headset description will stay regardless of who is looking at it if an antag has looked at it.

### Steps to reproduce

1. Have an antagonist look at a security headset description, showing the "Good." part at the end of the description that is exclusive to antags
2. Arrest said antagonist and confiscate their headset 
3. Observe how the headset has the "Good." part still in the description.

### Expected Behavior

the description should update when someone else looks at it.

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/2cb6f82b3aae61eb72ffcb0bedb7d49ea9d5dea7
