### ISSUE TITLE
`turf.ReplaceWith(/turf/simulated/floor/mauxite)` does not properly set the `icon_state` of the new tile

### ISSUE THREAD

**Issue by amylizzle** [goonstation/goonstation#21483]
### Labels

[BUG]

### Description

Replacing a turf with a mauxite turf doesn't render properly

### Steps to reproduce

call `turf.ReplaceWith()` with a path to a turf that has a material icon state
turf is replaced, but defaults to icon_state "floor" when it should be "floor$$material"

### Expected Behavior

Should render mauxite tiles properly

**Comment by TobleroneSwordfish** [comment]
Fixed in 862cde7
