### ISSUE TITLE
fire extinguisher works incorrectly when a borg puts CLF3 in a fire extinguisher and puts it back

### ISSUE THREAD

**Issue by Dale-sl** [goonstation/goonstation#2158]
[BUG]

**Describe the bug**
after putting CLF3 in a fire extinguisher as a borg, the fire extinguisher's handle breaks and it can't be used. However, by putting the extinguisher back into the module tab and taking it back out, it is refilled with foam and able to be fired, making the extinguishing sound without actually firing any foam.

**To Reproduce**
1. put clf3 in a fire extinguisher as a borg
2. put the extinguisher back into the module tab -- it might matter whether you just put it back or swap it out with a different item
3. take the extinguisher back out

**Expected behavior**
the handle should remain broken and the extinguisher empty -- although, maybe having the extinguisher being able to be fixed would be a good idea as having a module be broken forever doesn't seem like a good idea.

**Comment by Tiggersaurus** [comment]
Do you mean Fluorosurfactant foam and not clf3? As to knowledge Borg extinguisher can only hold foam as funny as spraying acid on meatbags would be 👀

That aside, I'll see if I can replicate this when I'm next on!

**Comment by Tiggersaurus** [comment]
I can't seem to replicate this with the foam tank. Keeping it on the bar, it fills fine and the safety stays off and you can spray. Odd.

**Comment by Dale-sl** [comment]
I replicated the bug earlier with a different chemical -- namely fluorosulfuric acid -- so I'm guessing you're not putting CLF3 in the extinguisher first. I'm using civilian borg and making chlorine trifluoride via the bucket and the chem machines, then putting it in the fire extinguisher. This results in a message that the extinguisher has ruptured and breaks it, which I'm thinking is expected behavior, the problem is that by putting it back and taking it out repeatedly the broken handle message goes away and attempting to spray creates a sound but no spray.

**Comment by Tiggersaurus** [comment]
Funnily enough I dont make a habit of trying to put clf3 in fire extinguishers as borg. To my knowledge borg ones *only* hold foam. I would assume they're white listed.

**Comment by Dale-sl** [comment]
that isn't true, at least according to to my testing; you can put anything in a borg fire extinguisher that you can put in a normal one -- give it a shot, i've put lube in one as a rogue borg before and it worked as normal.

**Comment by Tiggersaurus** [comment]
I've tried before and it didn't work. Maybe something changed since then. Unsure if intended.

**Comment by Sovexe** [comment]
apparently I fixed this on accident in #2167

modules repairs are already handled by roboticists
