### ISSUE TITLE
Golden "grab" icon with "Midas Touch"

### ISSUE THREAD

**Issue by crizzeone** [goonstation/goonstation#216]
You can just golden the "grab" icon that appears in your hand when you grab someone.

1. Get the "Midas Touch" Gene Power
2. Grab someone
3. Use "Midas Touch" and select "grab" in the list
4. See "Gold Grab"

I think this is useless and not necessary to be a part of the game, because it just effects this icon

It even doesnt look cool

**Comment by pali6** [comment]
The only fix I'll accept is making the gold icon look cooler!

**Comment by Gannets** [comment]
Midas UI is a undocumented feature. 🥇
