### ISSUE TITLE
packets have the power to pry open or close unpowered and bolted doors

### ISSUE THREAD

**Issue by XtuRnaL** [goonstation/goonstation#21628]
### Labels

[BUG][MAJOR]

### Description

sending a packet to a door has the door carry out the request, be it working, bolted, unpowered, or the last 2 combined

### Steps to reproduce

1. set up any packet for a bolted or unpowered door
2. send the packet
3. watch as the bolts mean nothing and mystery power charges the door enough to pry it open

### Expected Behavior

packets should not allow for doors to break their own bolts and the laws of thermodynamics

### Additional Information & Screenshots

video of the bug being performed below
https://github.com/user-attachments/assets/2405e7a6-f18e-4489-b07e-fe05517142a8

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/be5493812c9943d9469f707a507f1ad7ab005697
