### ISSUE TITLE
Inappropriate names of sprites in human_head.dmi 

### ISSUE THREAD

**Issue by jan-antilles** [goonstation/goonstation#2162]
[BUG]

**Describe the bug**
Two of the sprites in human_head.dmi have inappropriate/offensive names: specifically "tardbaby" for an alien head and "epileptic" for a head that flashes psychedelic rainbow colors.

**To Reproduce**
1. look at them
2. this is not the we that we want to be

**Expected behavior**
Used or not, the name of sprites should be consistent with Goonstation's standards of appropriate language.

**Screenshots**
![headsprites](https://user-images.githubusercontent.com/67385345/93000389-d8350000-f4ed-11ea-8795-eaf113160178.JPG)

**Comment by Sovexe** [comment]
de9e162370872e57aa9391b4faa434c6860543d9
