### ISSUE TITLE
BUG: Headspider victims do not join hivemind

### ISSUE THREAD

**Issue by Recusor** [goonstation/goonstation#2164]
[BUG]

**Describe the bug**
When a victim is headspidered, after a delay the ling takes over. It seems like it should be intended that the victim join the hivemind but they dont seem too. This is an assumption.

**To Reproduce**
1. Spawn as a changeling
2. Have at least 10 DNA points.
3. Die
4. Spawn Headspider
5. Enter host
6. Wait to take control and see that victim is not in hivemind.

**Expected behavior**
I really think victim should join hivemind.

**Screenshots**

**Additional context**

**Comment by flappybatpal** [comment]
Cannot reproduce locally, victim becomes member of hivemind.
