### ISSUE TITLE
Canister Bomb note feature non-functional

### ISSUE THREAD

**Issue by DegenerateGroundState** [goonstation/goonstation#2184]
[BUG INTERFACE BOMB]

**Describe the bug**
You're supposed to be able add a note to a Canister Bomb's interface by adding a piece of paper to the ignitor/multitool/plasma can assembly before attachment to the canister, like you can do with flashes, atmo analyzers, bike horns etc. You can still attach the paper to it but the note isn't shown anywhere on the bomb's fancy new interface.

**To Reproduce**
1. Build a canister bomb assembly
2. Write something on a piece of paper
3. Click on assembly with paper
4. Attach to canister
5. Click canister
6. Observe the absence of any note

**Expected behavior**
I'd expect a note to show up like it is supposed to.

**Screenshots**
N/A

**Additional context**
Wiki says its supposed to add a note to its interface and I'm at least 30% certain thats what it did years ago when I last made a canister bomb.
[The Wiki Entry](https://wiki.ss13.co/Construction#Canister_bomb)

> A sheet of paper and a pen (Adds a note to the canister bomb interface.)

**Comment by PrimeNumb** [comment]
Oversight on my part. Will have a look at it when I got time, but if someone wants to take a stab at it feel free.

Notes used to look like this on the old interface:
![](https://i.imgur.com/w5iZ2nB.jpg)
(Although it scaled horribly and would go outside the bounds of the UI given enough text)

**Comment by ThePotato97** [comment]
This is fixed in my tgui paper port, which will be finished soon™
![image](https://user-images.githubusercontent.com/10260415/95815824-70085280-0d15-11eb-9e3b-61bcd15bafaa.png)
