### ISSUE TITLE
Wanted Poster Station printer functionality missing/wiki inaccurate?

### ISSUE THREAD

**Issue by DegenerateGroundState** [goonstation/goonstation#2185]
[BUG WIKI SECURITY PRINTER]

**Describe the bug**
The Wanted Poster Station allegedly is capable of printing a poster to every printer on the station, but as far as I can tell this functionality doesn't exist. Perhaps it was obliterated by an interface update, was never implemented, or the wiki is simply in error? 
See [The Wiki Entry](https://wiki.ss13.co/Security_Objects#Wanted_Poster_Station) 

> A computer for making wanted posters. Simply enter a name, search the Security database or swipe a camera photo for a mugshot, set a reward, add some additional notes, and voila, you have a poster! **Afterwards, you can either send it to all printers on the station** or print some out to plaster around yourself.

**To Reproduce**
1. Click the Wanted Poster Station
2. Click print
3. Observe the only option being to specify how many copies
4. Observe the lack of any other printer related options on the station's interface
5. Try to feed a printed poster back into the station
6. Remember that only allows you to scan in photos for mugshots
7. Wonder if anyone ever looks at your posters

**Expected behavior**
I'd expect there to be an option somewhere to print the poster to every printer, as described on the wiki.

**Screenshots**
N/A

**Additional context**
Sounds like a pretty good feature, its hard to carry around a bunch of posters since an individual piece of paper takes up the same amount of room as a riot launcher.

**Comment by Conchuckter** [comment]
Currently printers can't print posters and there isn't a file type for them. Also the poster stations aren't setup for packets.
