### ISSUE TITLE
portable computers do not connect to the network while placed on data terminals (im dumb not a bug)

### ISSUE THREAD

**Issue by predmetparfuyit86** [goonstation/goonstation#2190]
[BUG]

**Describe the bug**
the wiki states that portable computers can connect to the network by being placed ontop of a data terminal however ingame this is not the case

**To Reproduce**
1. accquire a portable computer
2. place it ontop of a data terminal
3. The portable computer hasnt connected to the network 

**Expected behavior**
the computer connects to the network

**Screenshots**

**Additional context**

**Comment by glassofmilk** [comment]
In order to connect to the network, you'd need to first make sure the network adapter is in wired mode. Then, the easiest way to check for network connectivity would be booting with TermOS and running term_ping. I haven't had any issues with this, but I haven't done it in the last few weeks

**Comment by predmetparfuyit86** [comment]
> In order to connect to the network, you'd need to first make sure the network adapter is in wired mode. Then, the easiest way to check for network connectivity would be booting with TermOS and running term_ping. I haven't had any issues with this, but I haven't done it in the last few weeks

ah ok i get my info from the wiki which just said "put it on a data terminal" how do i delete this bug report?
