### ISSUE TITLE
Military boot footstep sound plays too frequently when walking

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#2196]
[TRIVIAL]

**Describe the bug**
When wearing military boots and in 'walk' mode, the footstep sound plays unreasonably quickly. This might be an issue with walking and all footstep sounds; I haven't tested enough to say.

**To Reproduce**
1. Wear military boots
2. Set yourself to walk
3. Walk around and hear the rapid footstep sounds

**Expected behavior**
The footsteps would play at the same frequency as running, or slower even.

**Video**
Video of the behavior here-
https://vimeo.com/458918216

**Comment by zjdtmkhzt** [comment]
So, is this something that happens _sometimes_ or do you just feel walking footstep noises are too frequent all the time?

**Comment by frawhst** [comment]
I noticed the issue in one round, I can test a bit more today to see if it’s a consistent issue. The footstep sounds while walking were playing roughly twice as fast as the sounds while running.

**Comment by frawhst** [comment]
I checked the boot code, and this isn't actually a bug. Anything with 'step_lots = 1' just steps really fast while walking. Closing for now.
