### ISSUE TITLE
Actions Process Hangs on Donut3

### ISSUE THREAD

**Issue by lilywhites** [goonstation/goonstation#2202]
[BUG]

**Describe the bug**
Actions Process Hangs on Donut3

**To Reproduce**
1. Be on Donut3, generally on higher populations
2. Notice actionbars fill up to full but never actually execute - most of the crew will have automender, table-vault or handcuff symbols stuck above their heads
3. See error, receive ahelps
4. Go to Main Loop Context under the debug verbs tab and kill the Actions process to get things moving again

**Expected behavior**
Seamless, silky action-doing

**Additional context**
I've seen this issue take place 3 times now, always on Donut3.

**Comment by ZeWaka** [comment]
railings?

**Comment by Sovexe** [comment]
possible runtime


File | action_controls.dm
-- | --
Line | 217
Error | Cannot modify null.transform.
```
proc name: updateBar (/datum/action/bar/updateBar)
  source file: action_controls.dm,217
  usr: null
  src: /datum/action/bar/icon/otherIt... (/datum/action/bar/icon/otherItem)
  call stack:
/datum/action/bar/icon/otherIt... (/datum/action/bar/icon/otherItem): updateBar(1)
/datum/action/bar/icon/otherIt... (/datum/action/bar/icon/otherItem): onUpdate()
/datum/action/bar/icon/otherIt... (/datum/action/bar/icon/otherItem): onUpdate()
/datum/action_controller (/datum/action_controller): process()
Actions (/datum/controller/process/actions): doWork()
Actions (/datum/controller/process/actions): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(Actions (/datum/controller/process/actions), 0)
```

**Comment by pali6** [comment]
Is this still happening? I fixed the runtime Sov posted.

**Comment by frawhst** [comment]
haven't seen or heard of this since, considering it fixed
