### ISSUE TITLE
Books taken off of a bookshelf lack a sprite

### ISSUE THREAD

**Issue by robertmanbob** [goonstation/goonstation#221]
**Describe the bug**
Books taken off of a bookshelf lack an item sprite.

**To Reproduce**
1. Click a bookshelf, select a book
2. Realize the book is in your hand, but it lacks a visible sprite
3. Put the book back on the shelf, die inside.

**Expected behavior**
Books have the sprite that they'd normally have outside of when taken off of a bookshelf.

**Screenshots**
Here's a gif: https://i.imgur.com/XPEaVQr.gifv
Though I only show it happening with the one book, the same bug happened with both of the books on the shelf.

**Additional context**
There *is* an in-hand mob sprite with books taken off of the shelf.

**Comment by ZeWaka** [comment]
@Adharainspace re: #194

**Comment by Adharainspace** [comment]
initially and tentatively saying that i cant reproduce this. was the round before this nuke? were these books already on the bookshelf?

**Comment by robertmanbob** [comment]
Actually, I'm pretty certain the round before was a nuke round on Manta. I have no idea if the bookshelves were broken during or before the nuke round, though.

**Comment by pali6** [comment]
I hope I fixed it in 462680a

**Comment by pali6** [comment]
Nevermind, not fixed. Apparently it's because it's trying to pull the icon from the icon file (which doesn't exist on the live server) instead of using the rsc.
