### ISSUE TITLE
When AI ejects beakers or drink containers...

### ISSUE THREAD

**Issue by DicksonOrmus** [goonstation/goonstation#2213]
[BUG]

When the AI ejects beakers or drink containers from a dispenser, it ejects it to wherever the ai's camera eye is.    This essentially gives any ai with a beaker in a chem dispenser the ability to firebomb any location on the station.

**To Reproduce**
1. find drink or chem dispenser with container in it
2. move camera eye where you want to put beaker
3. Hit eject
Beaker is now at said location.

**Expected behavior**
drink should eject on dispenser square

**Comment by Tarmunora** [comment]
fixed by https://github.com/goonstation/goonstation/commit/97a6fe2296e7c2480986cc86a094e09f8eeeeb4f
