### ISSUE TITLE
Ranged Blood Drain Disappearing on Vampire after clone

### ISSUE THREAD

**Issue by JargonRaven** [goonstation/goonstation#222]
**Describe the bug**
Playing vampire, I lacked ranged 

blood drain after being cloned.

**To Reproduce**
1. Be a vampire
2. Be cloned, lack ranged drained

**Expected behavior**
Be a vampire, having ranged blood drain throughout the round, without change.

**Screenshots**
![Goonstation Roleplay NSS Clarion 2020-04-12 180953](https://user-images.githubusercontent.com/48487476/79081541-6cefc380-7cec-11ea-9380-68fea34e4742.png)
**Additional context**
I am uncertain if I started the round with ranged blood drain even, but, that is definitely when I first noticed it, so that is at the earliest when I can prove I didn't have it.

**Comment by ZeWaka** [comment]
Likely related to #205

**Comment by Adharainspace** [comment]
im gonna test to see if this is still a thing, since #205 was fixed 2 days ago

**Comment by Adharainspace** [comment]
it is still a thing
