### ISSUE TITLE
Blood created by organs doesn't have forensics

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#2220]
[BUG]

**Describe the bug**
Blood stains created from an organ contain no forensics when scanned.

**To Reproduce**
1. Explode a human
2. Locate a blood stain that has been created by an organ
3. Scan with sec PDA or similar
4. Check blood data

**Expected behavior**
Forensics would contain ID

**Screenshots**

![Untitled](https://user-images.githubusercontent.com/70909958/93603864-83492c00-f9bc-11ea-96ce-478a3c51ed26.png)

**Comment by pali6** [comment]
Fixed by 2032655
