### ISSUE TITLE
Cyborgs are able to produce infinite glass with the glass recycler

### ISSUE THREAD

**Issue by Varshie** [goonstation/goonstation#2223]
[LABEL] -->
[BUG]

**Describe the bug**
Cyborgs are able to insert their glass containers into the glass recyclers repeatedly. The inserted item also becomes unusable for anything other than more glass duplication, as it becomes a standard item with no ability to contain reagents while still counting as glass.

**To Reproduce**
_1. Be a cyborg with the chemistry or medical module.
2. Hold a beaker or drinking glass in an active hand and insert it into the recycler.
3. Keep placing it in the recycler for infinite recycled glass.
4. A lot of glass but the inserted item will become useless afterwards. Attempting to add reagents to the item will instead splash them over it instead and there is no indication of what it's containing._

**Expected behavior**
Cyborgs probably shouldn’t be able to insert any of their tools into the recycler.

**Screenshots**
![GlassDupe](https://user-images.githubusercontent.com/71558290/93670341-a8a86980-fa92-11ea-9656-c588ef9eece6.png)
_Note in the image below there is no indication of contained reagents:_
![GlassDupe2](https://user-images.githubusercontent.com/71558290/93670381-e0afac80-fa92-11ea-8788-6365e138dcbc.png)

**Additional context**
Tested/discovered with the chemistry/medical cyborg modules, I don’t think there’s any reason why it won’t happen while using the brobocop module's beer/drinking glass.

**Comment by Tarmunora** [comment]
fixed by https://github.com/goonstation/goonstation/commit/2328cac2bdea8c94345a6e80c4d2a4c29b5a61cf
