### ISSUE TITLE
Polymorph to monkey but not back

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2228]
[BUG]

**Describe the bug**
you can polymorph into a monkey but cant polymorph back into a human, this confuses me

**To Reproduce**
1.use polymorph gene abilty on monkey
2.become monkey
3.use on human
4.stay monkey

**Expected behavior**
either not polymorphing into a monkey or being able to polymorph out of being a monkey

**Comment by cyclingLinguist** [comment]
I had this same problem! 

When I used the polymorph ability on humans after I was a monkey my name changed to match the human but I still stayed in the form of the monkey and could only ever chimper.

**Comment by Superlagg** [comment]
> I think it is something to do with
> `if(owner.bioHolder?.mobAppearance?.mutant_race) owner.set_mutantrace(owner.bioHolder.mobAppearance.mutant_race)`
> 
> set_mutantrace never gets set back to human or default or whatever
> The appearance of the human still gets copied but doesn't appear visually because mutantrace is monkey I guess. That would also explain why I was seeing a weird human silhouette overlaid on my monkey body after trying to polymorph back into a human. I could be totally wrong about all this, tho. I don't know DM like at all and just have some basic general hobby coding experience.

You are pretty much spot on with why this is happening. I should know, I coded that mess!

someday I'm gonna define human as a form of mutantrace. Cus like 80% of the problems I get from messing with mutantraces is going from mutant to nonmutant. 

but till then, I could just throw in an `else set_mutantrace(null)`, rearrange the first `if` to just check for an appearanceholder and/or if they're a thing that can be mutantraced without exploding into runtimes. 

Till till then, you can always seek out your local neighborhood lizard and transform into them!
