### ISSUE TITLE
Blob ambassador doesnt spawn with id

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2236]
[BUG]

**Describe the bug**
Blob ambassador doesnt spawn with id

**To Reproduce**
1. spawn as blob ammasador
2. no id

**Expected behavior**
have an id in the backpack or something

**Comment by Arivias** [comment]
The wiki states that ambassadors start with no access. Unless the other ambassador types have ids, then this is probably intentional.

**Comment by ZeWaka** [comment]
request a feature change if you want this to not occur
