### ISSUE TITLE
Arms falling off during leg surgery

### ISSUE THREAD

**Issue by TDHooligan** [goonstation/goonstation#2241]
[BUG]

**Describe the bug**
If performing leg surgery and your leg falls off because stapling didn't happen, your arm falls off, dropping another leg on the floor, removing your arm.

**To Reproduce**
Perform leg surgery
(Possibly?) attempt to re-attach wrong leg
Wait
Your arm falls off

**Expected behavior**
Your leg falls off.

**Comment by amylizzle** [comment]
Can't reproduce. Arm and leg fell off normally, and left an arm and leg behind.
