### ISSUE TITLE
Plasma tank on back sprite missing

### ISSUE THREAD

**Issue by DegenerateGroundState** [goonstation/goonstation#2247]
[BUG SPRITE]

**Describe the bug**
The sprite for wearing a plasma tank on your back seems to be missing, this is a shame because it used to freak people out when you fill one with o2

**To Reproduce**
1. Get a plasma tank
2. wear on back slot
3. notice no change to your character's sprite

**Expected behavior**
I'd expect there to be a scary sprite!

**Screenshots**
![plasspritemissing](https://user-images.githubusercontent.com/23085959/93947706-f095ed80-fd2b-11ea-92ea-2169f37daceb.png)

**Additional context**

**Comment by ThePotato97** [comment]
I'll look into it 🐱‍💻

**Comment by ThePotato97** [comment]
The plasma tank has no wear image icon

**Comment by pali6** [comment]
I had no idea you even could wear plasma tanks on your back.

**Comment by DegenerateGroundState** [comment]
> 
> 
> I had no idea you even could wear plasma tanks on your back.

it used to be advantageous due to capacity if I remember correctly
also you can always put it on someone else's back without removing the plasma first!
