### ISSUE TITLE
Vampire liver failure pseudo-fixed by coffin

### ISSUE THREAD

**Issue by DegenerateGroundState** [goonstation/goonstation#2257]
[BUG]

**Describe the bug**
I drank way too much liquor as a vampire and killed my liver, so I coffin-escaped and regenerated. This got rid of all my booze and toxin damage, but when I got out I racked up more TOX like my liver was dead. Okay fine, maybe the coffin doesn't repair livers, except when I scan myself it says all my organs are in perfect condition! 

**To Reproduce**
1. Be Vampire
2. Suffer Liver Failure
3. Coffin Regenerate
4. Get out, still suffer TOX damage, use health analyzer

**Expected behavior**
Seems like either it shouldn't fix the liver and it should still show up as dead, or it should fix it and the damage should stop accumulating.

**Screenshots**
![bustedlivervamp](https://user-images.githubusercontent.com/23085959/94155429-74f08980-fe6e-11ea-85c9-0f8e3e8b9211.png)

**Additional context**
I was drinking Bloody Scary's by the way. Wish there were a special message or something with those for Vamps!

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/4f30626b0cb6ac62ff0f0cf39df805854f746863
