### ISSUE TITLE
Light pops no longer burst fuel tanks

### ISSUE THREAD

**Issue by DicksonOrmus** [goonstation/goonstation#2270]
[LABEL] -->
[BUG]

**Describe the bug**
Light tanks used to pop fuel tanks, but with the new spark system this is no longer the case.  I tested it over three rounds as AI yesterday or the day before

**Expected behavior**
spark flies and ignites fuel tanks similar to how welder bombing works.

I don't think this was an intentional omission, just an oversight from when the sparks got changed.

**Comment by pali6** [comment]
I'm pretty sure this is actually a feature.

**Comment by Tarmunora** [comment]
Large (4000u) tanks are supposed to detonate from a burst light, small (item size) are not

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/35e8e0d45f33cb9d01ed40837cbe843bade25c84

**Comment by DicksonOrmus** [comment]
It is the large 4000u tanks that do not burst from light

**Comment by DicksonOrmus** [comment]
Phnice looks like ya fixed it
