### ISSUE TITLE
Plantmaster Mk3 UI spam as borg

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#2273]
[BUG]

**Describe the bug**
On using the Plantmaster in botany as borg, everytime someone else uses the machine I get spammed with the UI popping up. Very very frustrating.
**To Reproduce**
1. Be borg.
2. Add fruit to plantmaster via satchel
3. Try to get on with growing things while a human uses the plantmaster
4. Get spammed to fuck with UI popups.

**Expected behavior**
To not be spammed.

**Comment by ZeWaka** [comment]
tgui would fix
