### ISSUE TITLE
Borg got confused movement after wrestler attack.

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#2276]
[BUG]

**Describe the bug**
After being punched by a wrestler, I was stuck with confused movement for the rest of the round.

**To Reproduce**
1. Be assaulted by a wrestler - at least a punch and a kick.
2. Somehow have confused movement.

**Expected behavior**
To take damage, but be able to walk normally.

**Screenshots**

**Additional context**
Changing my legs out, re-seating my brain in the same body did not fix the issue.  Being moved to a new body did fix the issue.

**Comment by makkipakki** [comment]
I asked Kamades to submit this report when he mhelped about it, as it reminded me a lot of the report I submitted awhile back regarding borgs being permaslowed by the Vampire's frost bats. I suspect it may be a similar issue?
[https://github.com/goonstation/goonstation/issues/1298](url)

**Comment by Tarmunora** [comment]
probably misstep not being handled in a sane manner on borgs

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/30afca82d2cf07df7b7e81ce8b4881ec522e0e13
