### ISSUE TITLE
Airlocks show a zero if you try viewing the wires.

### ISSUE THREAD

**Issue by MaintClown** [goonstation/goonstation#2279]
[BUG]

**Describe the bug**
Just a zero in the top-left corner if you make a new door with an RCD. Not sure if it's the drone RCD or RCDs in general.

**To Reproduce**
1. Go to a door.
2. Screwdriver.
3. Multitool.

**Expected behavior**
Wires that have not transcended beyond our mortal dimension.

![screenshot204](https://user-images.githubusercontent.com/63614296/94363531-cf693000-0090-11eb-80c6-91ce5aa7a790.png)

**Comment by ThePotato97** [comment]
I'll look into it

**Comment by ThePotato97** [comment]
You were a ghost drone right?
