### ISSUE TITLE
PDA scan can be used on ablity icons

### ISSUE THREAD

**Issue by libbmaster** [goonstation/goonstation#2285]
[BUG]

**Describe the bug**
Clicking on an ability icon while a PDA with the atmos analyzer upgrade installed is in hand will scan the _Icon_.
 
**To Reproduce**
1. Hold a PDA with the atmos analyzer upgrade
2. Click on an ability button.
3. Note that the UI is "scanned"

**Expected behavior**
You cannot analyze the atmo contents of UI

**Screenshots**
![ScreenShot_20200927011246](https://user-images.githubusercontent.com/56776242/94373024-67d2d500-00d0-11eb-9e8f-c3f0c2eb5fbd.png)

**Comment by cyclingLinguist** [comment]
Woah, meta! That's a weird bug!
