### ISSUE TITLE
Nuclear Operative victories are being counted as losses.

### ISSUE THREAD

**Issue by Gannets** [goonstation/goonstation#2293]
[BUG]

**Describe the bug**
Successful nuke rounds are being counted as losses by the game and by the leaderboard.

**To Reproduce**
1. Observe a nuke ops team successfully detonate their bomb, destroying the station.
2. See the victory image overlay appear.
3. See that the chatlog shows a crew victory instead.
4. Be horribly mislead about the state of nuke ops balance due to incorrect stats.

**Expected behavior**
For nuke ops to get a victory credit when they explode the station.

**Screenshots**
![image](https://user-images.githubusercontent.com/8319565/94378316-82349f00-0120-11eb-92d4-a6e3b588fbb4.png)

**Additional context**

**Comment by pali6** [comment]
fixed yesterday by some random commit
