### ISSUE TITLE
Stuck orbiting coffin as vampire

### ISSUE THREAD

**Issue by chemistrymain2** [goonstation/goonstation#2298]
[LABEL]
[BUG]

**Describe the bug**
I was a vampire and used my return-to-coffin ability while in crit. I was stuck orbiting the vampire coffin, while in crit, slowly suffocating, unable to speak. I had used it once before successfully and just seemed to get stuck orbiting it.

**To Reproduce**
1. Be a vampire
2. Be in crit
3. Use the coffin escape behavior?

**Expected behavior**
I enter the coffin and recuperate instead of following it around like a sad grey slug.

**Comment by ThatFiveGuys** [comment]
Unable to be reproduced
