### ISSUE TITLE
Matter Eater mutation does not always display text when eating something

### ISSUE THREAD

**Issue by cyclingLinguist** [goonstation/goonstation#2305]
[BUG]

**Describe the bug**
When some objects are eaten with the ability bar they don't show text in chat.

**To Reproduce**
1. Get Matter Eater mutation
2. Use it on the phone handset in the bar
3. Notice there is no text in chat, just an eating noise

**Expected behavior**
Any time someone successfully uses the ability to eat something it should put the corresponding text in chat.

**Screenshots**

**Additional context**
I'm not sure if the issue occurs with specific items or just randomly.

**Comment by Carbadox** [comment]
Couldnt no reproduce
