### ISSUE TITLE
Wrestler cannot use powers after being cloned

### ISSUE THREAD

**Issue by Sovexe** [goonstation/goonstation#2318]
[BUG]

**Describe the bug**
After being cloned a wrestler keeps their abilities but trying to use them reports "You have to wear the wrestling belt for this."

`var/is_inherent` on `/datum/abilityHolder/wrestler` is not being preserved

**To Reproduce**
1. Be wrestler
2. Die
3. Be cloned
4. Try to use an ability

**Expected behavior**
Wrestlers can still wrestle

**Comment by amylizzle** [comment]
I think this is already fixed, I was not able to reproduce it and the wrestler ability has an override on deepCopy which preserves the inherent status.
