### ISSUE TITLE
Being changeling absorbed in VR prevents you from re-entering your body

### ISSUE THREAD

**Issue by schwicky-schwag** [goonstation/goonstation#2322]
[BUG]

**Describe the bug**
If you are absorbed by a changeling while in the VR murderbox, and they use a "Leave VR" button with you still in the hivemind, you will turn into the ghost of your virtual self and will be unable to go back into your body. Your body will still live, but you will be stuck as a ghost without admin intervention.

**To Reproduce**
1. Get absorbed by a changeling in the VR murderbox
2. Have them die or exit VR

**Expected behavior**
I expected to be returned to my body when they left VR, but instead I was turned into a ghost.

**Screenshots**
![image](https://user-images.githubusercontent.com/45479341/94745713-1163d180-0330-11eb-9353-4f42138495fa.png)
![image](https://user-images.githubusercontent.com/45479341/94745718-13c62b80-0330-11eb-85c3-e98b9881cbc4.png)

**Additional context**
While being absorbed by a changeling in VR, you are also unable to succumb while in critical condition to exit VR, nor are you allowed to freely leave the hivemind, the VR changeling must choose to let you out. Normally this isn't a problem outside of VR, but it is pretty annoying and can probably be abused to fuck with people pretty badly.

**Comment by MarkNais** [comment]
Code reverted by #2326.
I made the original patch, but I can't fix this for a while. I'll assign this to me so I can better track it.
