### ISSUE TITLE
Hemochromia Mutation blood pools are wrong colour.

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#2323]
[BUG]

**Describe the bug**
If you have a Hemochromia Type mutation, blood spatters are the correct colour, but if you bleed enough to make a puddle, it remains standard red.  Footprints trailing out of that pool are also standard red.

**To Reproduce**
Get a Hemochromia Type mutation.
Cut yourself, you'll make a blood spatter.  Cut again, bigger spatter.  Third time, you make a pool and it turns red like standard blood.

**Expected behavior**
The blood pool and footprints to be the colour of your blood.

**Screenshots**

![image](https://user-images.githubusercontent.com/68360623/94750631-bc31bb00-0343-11eb-95bb-6e58194638e6.png)

**Additional context**

**Comment by ZeWaka** [comment]
fluids don't work with blood color iirc

**Comment by cyclingLinguist** [comment]
Yes. See: https://github.com/goonstation/goonstation/pull/2057

> Note that the blood liquid code is a mess and thus I've decided to not touch it for now. Due to this, liquid blood (pools of blood) will always be the default red color. This will remain the case until someone fixes liquid blood.
Since footprints and stains aren't liquid, however, the correct blood colors does get displayed on them, so atleast we can paint the halls rainbow.

#2057

**Comment by ZeWaka** [comment]
Not a bug, this is a feature request then.
