### ISSUE TITLE
No latejoin spooktober roles available despite spooktober being enabled

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#2337]
[BUG]

**Describe the bug**
Title. I figured I'll just report it

**To Reproduce**
1. Click Declare Ready after the round starts
2. Notice the absolute lack of spooktober roles
3. Be sad

**Expected behavior**
I want to play as discount dracula :(

**Comment by RSG250** [comment]
yea were is ghost hunter?

**Comment by TTerc** [comment]
Looks like that's not the case anymore
