### ISSUE TITLE
[BUG] Possessed Zoldorfs cannot suicide

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#2360]
Attempting to suicide as a Zoldorf outputs the message "You're already dead, you goof," damning the user to remain inside the box for the rest of the round unless someone else signs a contract.

**Comment by Sovexe** [comment]
From past conversation with Dryad I believe this was an intentional side effect of signing away your soul to a demon

**Comment by pali6** [comment]
Fixed.
