### ISSUE TITLE
Paper Bin Icon disappears in backpacks

### ISSUE THREAD

**Issue by Legendahkiin** [goonstation/goonstation#2378]
[BUG]

**Describe the bug**
When picking up a paper bin, putting it in a backpack, then taking it out again, to finally put it in a backpack again, the icon disappears / becomes invisible. This makes it so you can't remove it again. You can still remove paper from the bins, but not the actual bin anymore. Only tested with the standard backpack.

**To Reproduce**
1. Pick up paper bin (drag-click grab intent onto character sprite)
2. Put in inventory (e.g. backpack)
3. Drag-click grab intent back onto sprite (to get in hands)
4. Put the paper bin in inventory again.

**Expected behavior**
The paper bin icon should still be showing,

**Comment by Carbadox** [comment]
could not reproduce
