### ISSUE TITLE
WannaBEE does not create enough bee for bee

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#2389]
[BUG]

**Describe the bug**
The WannaBEE Spooktober job has a special mutation that generates the bee reagent, infecting them with the bee disease and causing them to continuously vomit out bees.  However, it doesn't generate bee fast enough to overcome the rate at which it decays.  Instead, bee seems to hover around 1.2u, which is not enough to infect.  If you add bee, it will decay until it hits 1.2u.

**To Reproduce**
1. Be WannaBEE
2. Use reagent scanner or upgraded health analyzer to check quantity of bee (reagent)
3. Use health analyzer to note lack of bee (disease)
4. Fail to cough up bee (bee)

**Expected behavior**
Bees

[BUG]

**Comment by RSG250** [comment]
i actually haven't had this issue all that much? like at all really, on goon 4 every time i do wannaBEE do actually cough up bees, there might be issues on goon2 and other though maybe do to lag?

**Comment by RSG250** [comment]
actually yea it does seem to do that after awhile

**Comment by zjdtmkhzt** [comment]
Yeah, I think mutations may not have mult yet? At least some of them, including the drunk mutation. (Which bee is a subtype of.)

**Comment by frawhst** [comment]
seems fixed. or maybe we just reduced lag. idk
