### ISSUE TITLE
Sketchy D-5 LsBee patch is actually just LSD

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2390]
[BUG]

**Describe the bug**
Sketchy D-5 LsBee patch is actually just LSD

**To Reproduce**
1. by LsBee patch from Sketchy D-5
2. monsters instead of bee hallucinations
3. see error.

**Expected behavior**
bee hallucinations

**Comment by ZeWaka** [comment]
@Nebulacrity

**Comment by ThePotato97** [comment]
https://github.com/goonstation/goonstation/blob/9be0283fd4ac05f3d4d96994ea61673f501dd14d/code/datums/commodity.dm#L782
should be
https://github.com/goonstation/goonstation/blob/3b9b968d6ae6cf4f1ba7730c29d225ed51b0ceb9/code/modules/chemistry/tools/patches.dm#L321

**Comment by Nebulacrity** [comment]
Odd, then again I didn't touch patches. After all, it wasn't me who made the LSBee stuff, I only made RGBee stuff.
