### ISSUE TITLE
LSBEE BEE and CHROMATIC BEE dont protect bee mom

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2415]
[BUG]

**Describe the bug**
LSBEE BEE and CHROMATIC BEE dont protect bee mom

**To Reproduce**
1. make appropriately mentioned bees
2. get attacked by monkey or something
3. bee no help

**Expected behavior**
bee protect

**Additional context**
everytime i get attacked by a something and my little colorful buddy doesnt come to the rescue I get sad

**Comment by pali6** [comment]
Unable to replicate.

**Comment by RSG250** [comment]
maybe it was a fluke or something idk, closing since unable to replicate.
