### ISSUE TITLE
Map, Wiki, GitHubm Forum and Bug Report buttons are broken.

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#2417]
[BUG]

**Describe the bug**
Pressing any of the buttons at the top right corner of Byond opens a malformed link, eg:  http://%22https//goonhub.com/maps/horizon%22
instead of
Https://goonhub.com/maps/horizon

**To Reproduce**
1. Press button
2. Get a bad link

**Expected behavior**
The appropriate website to open.

**Comment by MarkNais** [comment]
Yeah I had this happen too, for pressing Map. Thanks for making the report! (I was too busy as a Nukie)

**Comment by ThePotato97** [comment]
http://www.byond.com/forum/post/2624266 already fixed in the latest version of byond

**Comment by ThePotato97** [comment]
http://www.byond.com/forum/post/2625077 new issue slightly related

**Comment by Sovexe** [comment]
already resolved BYOND issue. Update clients.
