### ISSUE TITLE
Vampire Steal Blood ability does not "consume" the blood globs

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#2423]
[BUG]

**Describe the bug**
Using the vampires Steal Blood ability pulls the blood out of targets but they'll only float around you and won't be absorbed, leaving you with no blood gain. 

**To Reproduce**
1. Use blood steal ability on someone
2. Watch as the blobs fly around and

**Expected behavior**
Use ability, get blood, ????, profit

**Additional context**
Entering a pod seems to let you claim the blood but it doesnt always work, as sometime it just smacks the pod and dissapears.

**Comment by jan-antilles** [comment]
Yeah, this one has been problematic, especially because it makes the vampire extremely obvious. There's no stealth when the giant red balls of blood hover around you indefinitely.

**Comment by Tarmunora** [comment]
oh no projectile bug

**Comment by ryebek** [comment]
The ability also doesn't actually drain any blood from the target, it appears. Have fun Tarm!

**Comment by Tarmunora** [comment]
i fix
