### ISSUE TITLE
throwing/slipping breaking frequently during assjam

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2427]
[BUG]

**Describe the bug**
throwing/slipping breaking frequently during assjam cause is unknown

**To Reproduce**
1. unknown starting step
2. throw something
3. it spin in place

**Expected behavior**
not broken

**Comment by Tarmunora** [comment]
Probably somehow related to @moonlol 's timestop interacting oddly with the throwing rework

**Comment by pali6** [comment]
Fixed in some old commit.
