### ISSUE TITLE
Mentors are able to bypass DNR

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#2434]
[BUG]

**Describe the bug**

**Apparently this can occur to anyone, not just mentors. Unsure if it's actually a bug but I'll leave this up unless coders think it isn't an issue**

As a mentor, when you join in as an observer to help someone, spawning in as a mentor mouse bypasses the DNR that is supposed to be set. This is a problem, as ghost antag selection becomes available. I was able to spawn in as both a late-joining werewolf and antag critters after dying as a mouse. After I died as the werewolf, my brain was still set to DNR and I could not be borged, but that apparently did not matter for the antag selection.

**To Reproduce**
1. Be mentor
2. Mouse around, helping people
3. Eat too much poisoned cake, die
4. You are now eligible for antag spawning

**Expected behavior**
DNR should not be able to be bypassed when it comes to antag selection. If a brain is DNR then they forfeit any more participation in the shift in a meaningful way, like being an antag.

**Screenshots**
![image](https://user-images.githubusercontent.com/68257280/96209826-89d8ae00-0f3e-11eb-9e77-186d873a25dd.png)

Also, I want to mention that this has been an issue for at least a month, but this is the first time I was able to replicate it. I had it happen previously but I wasn't sure if it was admin shenanigans or not.

**Comment by ThePotato97** [comment]
The random ghost antag selector doesn't check DNR for anyone.

**Comment by virvatuli-gh** [comment]
I'll update the title and description to reflect that then. Still unsure whether or not it's intentional

**Comment by ryebek** [comment]
I've checked the code, and DNR is in fact being checked during ghost antag selection, so the original issue is most likely whats going on. I'll look into it.
