### ISSUE TITLE
Escape Shuttle does not remove certian floor effects of floors in its arrival area upon arrival

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2441]
[BUG]

**Describe the bug**
Shuttle did not delete Neutron radiation effect from the floor tiles that were placed in its arrival zone, thus the floors in the shuttle irradiated people with neutron radiation

**To Reproduce**
1. place Neutronium floor tiles in shuttle landing area
2. escape shuttle arrives
3. walk on said area

**Expected behavior**
floors not be neutron irradiated

**Comment by RSG250** [comment]
did some testings turns out same happens with the mining shuttle, with both kinds of radiation.

**Comment by ZeWaka** [comment]
due to `Del`?

**Comment by Tarmunora** [comment]
fixed by f70872ca50a8ba96808b887b4a83aea408072d63
