### ISSUE TITLE
Powerpick damage display is bugged

### ISSUE THREAD

**Issue by qrqwerqwr** [goonstation/goonstation#2469]
[BUG]

**Describe the bug**
The damage shown when inspecting the powerpick is the same, 15 blunt,  in both its on and off state. If you test this damage, you will find that it only does 15 damage in its powered on state. The powered off state does around 7 damage.

**To Reproduce**
1. Obtain a powerpick from mining
2. Look at its supposed damage
3. Notice that it is the same when powered on, and while off

**Expected behavior**
The damage should not be shown as 15 for both states.

**Additional context**
Just a labeling bug, nothing serious. I did think the powerpick was overpowered though until I tested it.

**Comment by zjdtmkhzt** [comment]
Probably another case where the tooltip isn't rebuilt after changing the stats, I think the powerhammer may have had something similar in the past.

**Comment by Tarmunora** [comment]
fixed by 7d30a4f0386d1e20f41678ae4dece6b906e345e8
