### ISSUE TITLE
Player monkeys can no longer be heard by humans with monkeyspeak

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#2495]
[BUG]

**Describe the bug**
Reported by katie#4025 on the Discord; humans that acquire the monkeyspeak gene no longer hear what player monkeys say; all speech gets converted to chimpering.

**To Reproduce**
1. Be human with cool friends who are monkeys
2. Get monkeyspeak to talk to your monkey friends
3. Attempt contact
4. Be responded to with nothing but "chimpers"

**Expected behavior**
Ability to speak in intelligible sentences with cool player monkey friends.

**Screenshots**

**Additional context**
Probably from the changes in the player monkey PR a little bit ago.

**Comment by pali6** [comment]
Unable to replicate.
