### ISSUE TITLE
Borgs can place tools on the eldritch altar

### ISSUE THREAD

**Issue by F-OS** [goonstation/goonstation#2506]
**Describe the bug**
Borgs can place tools on the eldritch altar

**To Reproduce**
1. Be borg
2. Place tool on the eldritch altar
3. use tool
4. You have just duplicated the tool.

**Expected behavior**
For borgs to not be able to place tools on the altar

**Comment by Tarmunora** [comment]
fixed

**Comment by Tarmunora** [comment]
probably
