### ISSUE TITLE
fluid_groups.dm,455:Cannot read 0.len

### ISSUE THREAD

**Issue by Sovexe** [goonstation/goonstation#2516]
**Describe the bug**
File | fluid_groups.dm 
-- | --
Line | 455 
Error | Cannot read 0.len 

```dm
Description
proc name: update once (/datum/fluid_group/proc/update_once)
  source file: fluid_groups.dm,455
  usr: null
  src: /datum/fluid_group (/datum/fluid_group)
  call stack:
/datum/fluid_group (/datum/fluid_group): update once(0)
Fluid_Groups (/datum/controller/process/fluid_group): doWork()
Fluid_Groups (/datum/controller/process/fluid_group): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(Fluid_Groups (/datum/controller/process/fluid_group), 0)
```

**To Reproduce**
Unknown

Not entirely certain but I believe this causes the below issue
**Expected behavior**
Fluids combine instead of stack

**Screenshots**
![image](https://user-images.githubusercontent.com/33204415/97113068-57f1e500-16be-11eb-906a-7b88c8cf86c1.png)

**Comment by Tarmunora** [comment]
Disposing during lagcheck

**Comment by Sovexe** [comment]
This should have been addressed in one of my recent fix pushes. Fluid group objects were being set to a value of 0. This was changed to set it to null instead which should be caught by ?. checks

**Comment by Tarmunora** [comment]
bold of you to assume anyone used ?. in there

**Comment by Sovexe** [comment]
16c6a6afffa284216a598087ce3f602602efab36 will fix this runtime. Though there are other spots I'm expecting to be revealed
