### ISSUE TITLE
Deep Fried Dabs does not force dabbing or do anything

### ISSUE THREAD

**Issue by Awfullyfishy** [goonstation/goonstation#2522]
[BUG]

**Describe the bug**
The secret chemical Deep Fried Dabs does not do anything when injected, ingested or splashed.

**To Reproduce**
1. Get Deep Fried Dabs
2. Apply to uncool victim
3. Observe lack of cool dabbing

**Expected behavior**
Deep Fried Dabs should force people to dab, as per the Wiki description.

**Additional context**
I tried multiple times and through pills, injections and splashes. For all I know the Wiki is wrong and it has another effect, but I can't spot any.

**Comment by zjdtmkhzt** [comment]
I tested this live, giving 5 units of DFD to both myself (SA) and a bartender.
While it caused me to dab twice, the bartender did not dab, so maybe there is an issue with it when people do not have the ability to dab?
Then again, maybe I was just unlucky.

Maybe this was somehow broken with recent changes in emote code?

**Comment by Tarmunora** [comment]
Deep fried dabs will attempt to make you dab, but does not remove normal limitations on dabbing. Perhaps if you found something stronger......
