### ISSUE TITLE
Nanite clusters can deconstruct anomalies by moving through them

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#2569]
[MINOR]

**Describe the bug**
If a nanite swarm (the critter) moves through an anomaly/spatial tear, it removes the tear from the tile it moved though.
**To Reproduce**
1. Be on one side of anomaly
2. have a nanite swarm on the other side, targeting you
3. Nanites delete the anomaly to get to you

**Expected behavior**
Nanites are either blocked by the tear, or not blocked while leaving it intact.

**Screenshots**
![Goonstation The Final Day of GlobtumBattle Headquarters One 2020-11-01 012052](https://user-images.githubusercontent.com/67879783/97799136-ed223b80-1be0-11eb-8c50-f4070aea7280.png)
(nanites not pictured.)

**Additional context**

**Comment by ZeWaka** [comment]
lol

**Comment by A4Brogan** [comment]
Nanites: Menders of the Fabric of Space-Time!
