### ISSUE TITLE
"cable crate" available for request in PDA

### ISSUE THREAD

**Issue by corvidae** [goonstation/goonstation#2574]
[BUG]

**Describe the bug**
"cable crate" is an available option to request from the PDA request app as a Janitor.

**To Reproduce**
1. Be Janitor (at least)
2. Go to request some cleaning supplies because Horizon is stinky
3. See a thing saying "you shouldn't see this"
4. Report on GitHub

**Expected behavior**
Not see things that are flagged as "shouldn't see"

**Screenshots**
[https://cdn.discordapp.com/attachments/298827721604071425/772613258079109130/unknown.png](https://cdn.discordapp.com/attachments/298827721604071425/772613258079109130/unknown.png)

**Additional context**
May happen for other positions, haven't tested.

**Comment by Tarmunora** [comment]
bea6dccd45d68f2a84548d38df6f7bcd13ceacb5
