### ISSUE TITLE
Oshan - The tale of the stuck record

### ISSUE THREAD

**Issue by Zergspower** [goonstation/goonstation#2586]
[BUG]

**Describe the bug**
Radio station on OSHAN appears to only allow you to play a record once, and never goes off cooldown after that.

**To Reproduce**
1. Play record
2. Wait
3. Wait even longer

**Expected behavior**
The cooldown timer doesn't seem to go off, so the record you play is the only one you get to play (as in just that one time)

**Screenshots**
"You can feel heat emanating from the record player. You should probably wait a while before touching it. It's kinda old and you don't want to break it."

**Additional context**
I did reeboot and even another player tried without success to interact with it to remove the record.

**Comment by j-awn** [comment]
I just tested this locally, and didn't have any problems taking the disk out. Are you sure you waited long enough? On Oshan and Manta the disk can only be taken out after 500 seconds (8 minutes 20 seconds), which is a bit longer than the 5 minutes on non-underwater maps.

**Comment by Zergspower** [comment]
Yeah, even had other people try it with the same message. Regardiing the time, i got to play one record at shift start and i was never able to get it back out. Could have just been a one-off bug
