### ISSUE TITLE
Can't remove reagents from inserted container in reagent extractor

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#2607]
[BUG]
The buttons to remove reagents from a container in the reagent extractor ('flush all' and individual reagents) don't work when trying to remove from an inserted container. Removing from storage tanks is 100% functional.

**To Reproduce**
1. Insert beaker with reagents into reagent extractor
2. Press a button to remove reagents
3. Nothing happens
OPTIONAL:
4. Transfer reagents into storage tank
5. Remove buttons function as expected
6. ???

**Expected behavior**
Reagents are removed like they are in the storage tanks.

**Additional context**
Experienced consistently over 5+ rounds on different maps.

**Comment by Awfullyfishy** [comment]
From personal experience this happens with containers that aren't supposed to be able to go into the chemical dispenser only. Putting water cooler bottles and fuel tanks in the reagent extractor leads to this behavior of not being able to flush or remove reagents, forcing you to first transfer it to the internal tanks before you can do anything.
