### ISSUE TITLE
Unexpected behavior of air mixtures and space at high temperatures

### ISSUE THREAD

**Issue by Azrun** [goonstation/goonstation#2610]
[BUG]

**Describe the bug**
Unusual behavior of air mixtures adjacent to spaced tiles appear to absorb heat faster than they can be passed to space at HIGH temperatures.  Pressure and temperature get so high they end up being shared BACK into the chamber.

**To Reproduce**
1. Setup righteous chamber burn on COG1
2. Vent Chamber.
3. ....
4. Profit

**Expected behavior**
Space to suck.

**Screenshots**
![image](https://user-images.githubusercontent.com/1017374/98427595-b326be80-2052-11eb-8d9f-21fc39af5938.png)
![image](https://user-images.githubusercontent.com/1017374/98427704-fda83b00-2052-11eb-80da-7ca04abeed34.png)

![image](https://user-images.githubusercontent.com/1017374/98426986-1400c780-2050-11eb-8c1d-96d486430270.png)

**Additional context**
Will look into further if this isn't closed as designed. 😁

**Comment by wapachoo** [comment]
isn't this a hellburn

**Comment by Azrun** [comment]
Hmmm, unable to reproduce this after the fact on current code base.  Gas is clearly venting, just plasma combustion be what it is.

Going to look into questionable behavior of thermal conductive pipes in this setup and close if issue doesn't manifest again.

**Comment by Azrun** [comment]
All seems as it should, _questionable_ behavior was thermal exchange not being retarded by empty pipes vs filled.

All hail plasma.
