### ISSUE TITLE
Sea4 beaker duplication and assembly bug

### ISSUE THREAD

**Issue by Fosacetim** [goonstation/goonstation#2618]
[BUG]

**Describe the bug**
This bug allows you to duplicate beakers full of chemicals. Another bug, probably associated with it, makes it so that, if you signal a beaker assembly set somewhere far away while having the clone of the beaker in your inventory, YOU blow up, not the assembly.
**To Reproduce**
1. Get sea4 in an artbeaker
2. Transfer to a regular beaker
3. Get drunk
4. Take the box out of your backpack, put it in your hand, and click on the box to open its content menu
5. Make a beaker assembly but don't secure it. Try to put it in your backpack. When you get an error message, secure the assembly and set it down.
6. Put the box back in your backpack
7. Open the content menu for the backpack. You should have a second beaker full of sea4 inside your backpack.
8. Walk far away from the beaker assembly and try to signal it. You should explode, instead of the assembly. This is the assembly bug.

**Expected behavior**
I did not expect that a second beaker full of sea4 (I only made enough for 1) would just appear in my backpack. I expected that the assembly would blow up, not me.

**Screenshots**
I got none

**Additional context**
I was playing on a GoonRP2 round at 8:26 PM EST. Maybe an admin can provide the logs for it. I figured out the recipe for sea4 by throwing stuff into an artbeaker.  I isolated the sea4 via the chem dispenser and then transferred it to a regular beaker. I had a box in my backpack and I was drunk. I took out the beaker with sea4 from my backpack, put the box in my hand, and opened the menu for the box. I made an igniter/signaller/ beaker assembly and secured it. I then tried to put it in my backpack by clicking on the backpack with the beaker assembly, but I got an error saying it won't fit into the BOX. A bit odd.

I put the box back into my backpack and clicked on the backpack. The backpack content menu pops up, and lo and behold, within it is a beaker of sea4, not an assembly. But the beaker assembly is right on the ground in front of me. This is the beaker duplication bug.

Anyways, I set down the assembly in the test chamber and walk away. When I signal it, I explode and get gibbed, but the actual beaker ASSEMBLY that I set down in the test chamber did not blow up. I went back to check on the beaker assembly after I got cloned, and it was empty. This is the assembly bug.

**Comment by Fosacetim** [comment]
The map of the round in question was the Manta, in case that's relevant.

**Comment by amylizzle** [comment]
I cannot replicate this, and am I quite sure it's been fixed - sounds like there was maybe a set_loc issue. Also beaker assemblies fit in backpacks now.
