### ISSUE TITLE
Cyberheart surgery doesn't remove heart

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#2626]
[BUG]

**Describe the bug**
Performing the steps for heart surgery on someone with a cyberheart has the completion text but the heart stays inside meaning you are unable to replace a faulty one.

**To Reproduce**
1. Be mediborg or human doctor
2. Do scalp saw scalp saw
3. See success text say that heart has been removed.

**Expected behavior**
To save my roboticists life via heart surgery instead of keeping them alive for 10 mins via meds and screaming.

**Additional context**
Initially thought it was a Borg bug but it didn't work with 2 borgs and a human trying.

**Comment by PrimeNumb** [comment]
Fixed in current master (unknown which commit).
