### ISSUE TITLE
NARCS turret fires at blob overmimnds

### ISSUE THREAD

**Issue by Faulty** [goonstation/goonstation#2627]
[BUG]

**Describe the bug**
When a blob overmind is in front of a NARCS turret (like the one in brig) it will fire at the blob overmind until they leave.

**To Reproduce**
1. Play as blob
2. Inspect armory
3. Get shot at
4. Officers possibly investigate? 

**Expected behavior**
NARCS turret should not fire at blob overminds/ghostly things

**Screenshots**
![narc firing at blob](https://user-images.githubusercontent.com/4073630/98468180-26811b00-218e-11eb-8c0c-27b59c187c39.png)

**Comment by Tarmunora** [comment]
fixed
