### ISSUE TITLE
Radioactive Clothing does not irradiate

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2628]
[BUG]

**Describe the bug**
Wearing radioactive clothing does NOT irradiated you ( i swear at one point it did)

**To Reproduce**
1. make radioactive clothing (easiest way is to use koshmarite, as doing "spawn kosh" gives you the material bar immediatly)
2. equip
3. see that your not being irradiated

**Expected behavior**
radioactive turbo death

**Additional context**
even if you had rad resist the stats symbol in the corners time counter would still go up. so its not radiation resistence messing with it

**Comment by Tarmunora** [comment]
to whoever looks into this: holdertargeting component only counts for things in-hand by default - either fix up on the mat-trigger-on-life component or make a new base component type for it instead of holdertargeting

**Comment by RSG250** [comment]
after poking around abit, i found out a change made about 2 weeks ago in mat_triggersonlife.dm removed the user mob flags from it (MAT_TRIGGER_LIFE) that mob flag is no longer used anywere else other than were its defined
