### ISSUE TITLE
Inventory screen opened by right-clicking and Viewing Inventory will occasionally reopen on its own

### ISSUE THREAD

**Issue by jan-antilles** [goonstation/goonstation#2630]
[BUG]

**Describe the bug**
When I right-click a player and View Inventory in order to search and remove/add worn items to them, and the menu closes when an action is completed or I manually close it, it will occasionally reopen on its own afterwards, interrupting other interactions I am having with the player. 

**To Reproduce**
1. Right-click another player and select View Inventory from the menu
2. Do a thing, or don't and just close the window
3. Continue standing next to them because you are RPing
4. The window pops back up in your face every so often

**Expected behavior**
A window to stay closed when you close it.

**Additional context**
It doesn't happen consistently, which is one of the reasons this has been such a frustrating thing. But it has happened to me often enough as a Sec Officer that I have taken to standing an extra tile away from someone so the window can't get me while I'm typing. I don't know what triggers it!

**Comment by amylizzle** [comment]
Fixed by #9226

**Comment by amylizzle** [comment]
Reopened due to report of this _still_ occurring with the TGUI interface

**Comment by amylizzle** [comment]
Reclosing - report this bug again if it keeps happening.
