### ISSUE TITLE
Chemical Grenades do not accept watering cans.

### ISSUE THREAD

**Issue by Little-Froggy** [goonstation/goonstation#2632]
[BUG]

**Describe the bug**
On the wiki here: https://wiki.ss13.co/Being_A_Better_Traitor it mentions that chemical grenades accept watering cans. They currently do not. I assume that's intentional, in which case the wiki should be updated, but otherwise this bug report is valid.

**To Reproduce**
put the chemical grenade pin in the casing, then try to add a watering can.

**Expected behavior**
A message mentioning the container being too large should pop up.

**Comment by Tarmunora** [comment]
wiki was in error - has been corrected
