### ISSUE TITLE
Obscure Murder Method in Afterlife Bar Sanctuary

### ISSUE THREAD

**Issue by aberrantQuesrist** [goonstation/goonstation#2646]
[BUG] [OVERSIGHT]

In the sanctuary zone in the afterlife bar, where no murder or aggressive action is supposed to be possible, you can very much do that. Death always finds a way, as they say. Using the feature with matches, (which are easily vendible from the kitchen area in the afterlife bar) you can put them out on other players thus causing burn and brute damage, and eventually death. It's a ton of effort to successfully accomplish and incredibly unlikely to be too disruptive as it took me about nine matchbooks to kill Shitty Bill, but I figured it was an issue worth bringing to attention.

To Reproduce:
1. Die and enter the afterlife bar
2. Locate a matchbook (present in sanctuary zone and infinitely vendible from the FoodTech machine in the kitchen)
3. Light matches and use them on your victim in the sanctuary zone
4. Watch the damage climb
5. Observe death if you have that much patience.

Expected behavior:
Using matches on other players or NPCs in the sanctuary section of the afterlife bar will cause damage and eventual death.

Screenshot:
[https://imgur.com/t35XawB]

Additional context:
I think I've covered this issue thoroughly enough.

**Comment by amylizzle** [comment]
won't fix
