### ISSUE TITLE
Monkey stealth mode

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#2649]
The bug basically makes you be on a diffrent layer than most objects such as crates, beds and barricades

1.Become a monkey
2.Find a bed
3.Crawl under the bed
4.Walk away from it instead of crawling on top of it
5.You can now hide behind any objects. aka not only a bed. The big problem with this if you build items like barricades they fully cover you so only right clicking them will reveal that a monkey is in the planks.

Make it so you automatically exit this state when moving from the bed you hid under.

**Comment by vode-code** [comment]
I also saw a spaceman moved onto a surgery table and off a few times layer below the surgery table.
they were not layered below a regular table after I tabled them.

**Comment by amylizzle** [comment]
Can't hide under beds anymore
