### ISSUE TITLE
Borg Comm update causing normal borgs to see all channels but not reply

### ISSUE THREAD

**Issue by Zergspower** [goonstation/goonstation#2656]
[BUG]

**Describe the bug**
REF: [goonstation/goonstation] Pull request opened: #2654 Ai cyborg comms

**To Reproduce**
Play Borg
see all comms
unable to reply to all comms

**Expected behavior**
I believe this PR was meant strictly for the AI Shells and not all borgs, or if it was for all borgs we cant reply to those channels

**Screenshots**

**Additional context**
beep

**Comment by pali6** [comment]
I believe the problem is in the fact that the borg has the AI radio inside themselves no matter what and as such can hear sounds coming from it. Maybe instead of the current way of doing it the borg could use AI mainframe's radio instead of its own AI radio.
