### ISSUE TITLE
VR Lycanthropy Burned my Retinas

### ISSUE THREAD

**Issue by SGuivenne** [goonstation/goonstation#2657]
[BUG]

**Describe the bug**
Turning into a werewolf in VR, and then logging out of VR retains the canine vision, resulting in everything being yellowish and shitty.  This happens if you're killed as a werewolf in VR Too

**To Reproduce**
1) Go into VR
2) Become a werewolf
3) Get murdered or log out of VR while still a wolf

**Expected behavior**

Nothing, its a video game its not real bro.

**Comment by amylizzle** [comment]
Not reproducible, already fixed.
