### ISSUE TITLE
strange behavior with silver handcuffs

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#266]
I had silver handcuffs in my belt slot due to lack of room but I managed to get my hands on a utility belt.  I equipped my belt with the inventory button, and it and the silver handcuffs vanished, giving me the message "The silver handcuffs disintegrate.x71".  Clicking on the now empty belt slot gave that same message.  Attempting to equip something else to it with the equip button made that vanish as well, giving that message.  I removed my jumpsuit in the hopes that all the items would return from limbo, but my jumpsuit vanished as well.  The silver handcuffs disintegrate.x70  Clicking the now empty jumpsuit slot gave the message as well after that.  Oddly enough, I could still put things back in my pockets/ID slot, and the jumpsuit sprite was still on my character doll.

1. Equip silver handcuffs in your belt.
2. Use the equip button to equip something else.
3. Take your jumpsuit off.
4. Click the empty slots.

**Comment by Gerhazo** [comment]
Specific issue: an infinite loop happens, where, from the point you try to take the silver handcuffs off your belt:
1) u_equip is called on the handcuffs
2) u_equip reaches belt condition and calls unequipped on the handcuffs there
3) handcuffs' unequipped proc checks if they're silver and then calls qdel on them
4) after being qdeled, item disposing tries to unequip the item again, which goes back to step 1)
