### ISSUE TITLE
Cant place light fixture on walls

### ISSUE THREAD

**Issue by Oaklizard-2047** [goonstation/goonstation#2662]
[BUG]

**Describe the bug**
When i click the wall with a light fixture, it wont start installing it, even with valid condition. This has happened for a few rounds now.

**To Reproduce**
1. Make a light fixture
2. Click on wall with light fixture
3. See error

**Expected behavior**
A light fixture should've been installed alongside with the lines saying I'm installing them

**Additional Notes**
This happened after the update. Before the update it works just fine

**Comment by pali6** [comment]
Unable to replicate. Were you standing orthogonally adjacent to the wall? Being just diagonally adjacent doesn't work because then it's unclear which side of the wall you want to attach the light to.

**Comment by Oaklizard-2047** [comment]
somehow it is fixed now. im going to close this issue
