### ISSUE TITLE
Zoldorf broken on Clarion

### ISSUE THREAD

**Issue by Sbmhawk** [goonstation/goonstation#2667]
[BUG]

**Describe the bug**
Giving a signed weird burrito to Zoldorf says "It is not signed yet" on the map Clarion

**To Reproduce**
Buy a weird burrito from zoldolf
unravel it
sign it
give it to zoldorf
become zoldorf(or, not become zoldorf)

**Expected behavior**
to become zoldorf

**Comment by corvidae** [comment]
This appears to be happening on Cog1 as well.

**Comment by alexeric123** [comment]
Huh, what might also be releated is that it did not work on goon main, but it did on overflow, I was able to get into cog1 zoldorf on main overdlow.

**Comment by amylizzle** [comment]
Old, intermittent bug that hasn't been re-reported and can't be reproduced. Closing.
