### ISSUE TITLE
I oblitrated the nuke

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#268]
**Describe the bug**
I used a pile of erebite right next to the nuke to effectively delete it, and from what i can gather its supposed to be immune to explosions.

**To Reproduce**
1. mining satchel full of erebite 
2. dump next to nuke
3. explode

**Expected behavior**
nuke not deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/79493082-92c7e180-7fe6-11ea-875d-6fc67e6ff06f.png)

**Comment by PrimeNumb** [comment]
Should definitely be high priority since it breaks the entire gamemode if people used it regularly.

**Comment by Tarmunora** [comment]
Could not reproduce
