### ISSUE TITLE
Ghostdorfs can be electrocuted

### ISSUE THREAD

**Issue by SGuivenne** [goonstation/goonstation#2687]
[BUG]

**Describe the bug**
Manifested souldorfs, if they ghost into an electrified grille will be electrocuted
**To Reproduce**
Sign infernal contract
Soul Manifest
Walk into engine room
be stunned by electrical discharge 

**Expected behavior**
Nothing, I'm a goddamn ghost

**Comment by Sovexe** [comment]
probably because the zoldorf ghost is actually a hacked together `mob/living` just pretending to be a ghost with early return an a bypass to `CanPass`
