### ISSUE TITLE
Hunter mask not giving thermal vision as stated on the wiki.

### ISSUE THREAD

**Issue by alexeric123** [goonstation/goonstation#2692]
[BUG]

**Describe the bug**
Hunter mask does not give thermal vision, (not able to see targets through walls) as stated on the goon wiki " mask, which lets you spot people behind walls "
https://wiki.ss13.co/Predator

**To Reproduce**
Be predator/hunter
get your gear
go out in the hall, which you saw no one in
get blasted by a sec standing there

**Expected behavior**
Being able to see humans through walls.

**Comment by Carbadox** [comment]
Seems to be a bug related to screen tint not working properly (EG welder masks making your screen darker)

**Comment by Cthucky** [comment]
IIRC the old thermal vision was intentionally removed from the hunter mask because you can get them in the QM mask crates but I could be wrong.

**Comment by ZeWaka** [comment]
thermal vision i think has just been broken forever
