### ISSUE TITLE
Crazy Lighting

### ISSUE THREAD

**Issue by KB2222** [goonstation/goonstation#2741]
[BUG]

**Describe the bug**
I was playing one shift and i stepped over to someone. Just before i could speak, everything turns very "bloomy", as seen in the screenshot. i could not fix it and it even crashed byond. this may be an issue with byond or goon, im not sure.

**To Reproduce**
just walk around

**Expected behavior**
Nothing

**Screenshots**
![image](https://user-images.githubusercontent.com/65749123/99598083-fecc5700-29c6-11eb-9e8d-56b705602bd8.png)

**Additional context**

**Comment by pali6** [comment]
Internal byond bug, we can't fix.
