### ISSUE TITLE
Stock Market glitches

### ISSUE THREAD

**Issue by Godridge** [goonstation/goonstation#2744]
[BUG]

**Describe the bug**
sometimes allowed to buy tons of stocks for no money, also gives account tens of thousands of free credits

**To Reproduce**
Sorry, I can't really say exactly what caused this, just using the stock market

**Expected behavior**
not doing this

**Screenshots**

**Additional context**

**Comment by amylizzle** [comment]
Nowhere near enough information to even test bug.
