### ISSUE TITLE
[BUG] Swapping power cells in pockets deletes one but duplicates the other

### ISSUE THREAD

**Issue by mralexs5** [goonstation/goonstation#2745]
**Describe the bug**
Swapping power cells in pockets deletes one but duplicates the other

**To Reproduce**
1. Take phaser
2. Have power cell in pocket
3. Attempt to swap the cells
4. The cell in the gun is deleted, but the cell in the pocket is temporarily duplicated. The duplicate cell is named simply power cell. The cell disappears when one cell is placed in another item. 

**Expected behavior**
Power Cell swapped normally

**Screenshots**
https://streamable.com/piwi2n

**Comment by frawhst** [comment]
no longer seems to happen. likely fixed by the cell refactor
