### ISSUE TITLE
VR Chess board-bugs and problems.

### ISSUE THREAD

**Issue by Emcee-Gore** [goonstation/goonstation#2776]
[BUG]

**Describe the bug**
**You cannot castle the king.**

Not sure but worth checking out if - En Passant - works or does not work as well.

Also Emily said the board is wrong with them tiles and stuff,...
Cursed board!

**To Reproduce**
1. Set your king and tower up like you would do normally.
2. Notice...castling is an illegal move.

**Expected behavior**
I expected a castling move.

**Screenshots**
![image](https://i.imgur.com/jdsxrun.png)

**Comment by pali6** [comment]
It seems that to castle you need to clickdrag the king onto the rook according to the code.

**Comment by amylizzle** [comment]
Closing as not a bug. Seems like just an unintuitive feature on a rarely used thing.
