### ISSUE TITLE
AI camera tracking interrupted by airbridge

### ISSUE THREAD

**Issue by BenLubar** [goonstation/goonstation#2790]
[BUG]

**Describe the bug**
If the AI  is tracking someone and they walk onto an airbridge (and presumably also if they walk out of an airlock into space), the camera loses track of them despite still being able to see them.

**To Reproduce**
1. Be AI
2. Track a crew member
3. The crew member walks across an airbridge (such as on Cogmap)
4. Camera loses tracking for a few seconds

**Expected behavior**
Since the camera can see the entire airbridge, it would make sense to keep tracking.

**Comment by ZeWaka** [comment]
'Space' area?

**Comment by amylizzle** [comment]
Cannot replicate, must have been fixed already.
