### ISSUE TITLE
Cannot use almost anything to do with left mouse

### ISSUE THREAD

**Issue by Boxlta** [goonstation/goonstation#2793]
[BUG]

**Describe the bug**
Cannot use almost anything to due with left mouse (IE: Picking up items, Grabing items from bags and belts, click draging, observing, firing guns, using flockmind nanospray, injectors on other people)
Doesnt effect(Abbilitys, Things out of game window, (IE: Status tab and similar)

**To Reproduce**
Fairwarning(This only seems to be happening to some people)
Attempt to do something listed above
Thing does not happen, item is not picked up, or similar

**Expected behavior**
Things happening like picking up items or similar

**Additional context**
Is rather hard to play game,
Is not my mouse, works fine with any other game, select to this farty party spaceman
Sometimes they do work for short periods of time before going back to being broken
Tried on both newest version of Byond and older version

**Comment by pali6** [comment]
Do you use a dual monitor setup? Do you use Overwolf or another similar app that creates overlays on top of games? (Even if you don't have it enabled for ss13 it can cause issues.)

**Comment by Boxlta** [comment]
Hhm, overwolf may have something to do with it but it may not be it, ive never had problems with it before
Ill try full exiting on overwolf then testing

**Comment by Boxlta** [comment]
Hhm, yeah, overwolf seemed to be the problem, perhaps a note about it?

**Comment by pali6** [comment]
Good idea, added to FAQ: https://wiki.ss13.co/index.php?title=Game_FAQ&type=revision&diff=39372&oldid=39194
