### ISSUE TITLE
Committing suicide in the Afterlife makes you a ghost of a ghost, prevents respawning in the round

### ISSUE THREAD

**Issue by SGuivenne** [goonstation/goonstation#2804]
[BUG]

**Describe the bug**

**To Reproduce**
1. Be brutally murdered
2. Enter the afterlife bar
3. Kill self via head removal
4. Unable to respawn, now a generic assistant ghost

**Expected behavior**
To be able to return to the regular afterlife

**Comment by Boxlta** [comment]
This should become a feature, Quantum ghost stacking, ghost of a ghost of a ghost

**Comment by Yellow-Mushroom** [comment]
Tested this on a local and server, the respawn timer not only remains ticking while you are in the Afterlife bar, but even getting decapitated and dying keeps your respawn timer ticking (doesnt reset it) and visible

**Comment by SGuivenne** [comment]
> Tested this on a local and server, the respawn timer not only remains ticking while you are in the Afterlife bar, but even getting decapitated and dying keeps your respawn timer ticking (doesnt reset it) and visible

So this was poorly phrased but you cannot return to your original body after dying in the afterlife bar like that.
