### ISSUE TITLE
Command Bar default 'Say "' command is impossible to manually delete

### ISSUE THREAD

**Issue by vode-code** [goonstation/goonstation#2813]
[BUG]

**Describe the bug**
The command bar has a command that will show up by itself which is: > say "
Thing is, it's impossible to delete that command's text via backspace and you have to clear all, so it's quite clunky to use.

**To Reproduce**
1. Try to delete the command say "
2. Fail.

**Expected behavior**
Either the say " is fully cleared on backspace, or it starts being cleared one character at a time, not nothing.

**Comment by flrsh** [comment]
There's a button that says `Chat` on the lower right. If you click it, it should toggle this behavior.
