### ISSUE TITLE
wearing your own butt on your head doesn't count if it has blood or other crap on it

### ISSUE THREAD

**Issue by BenLubar** [goonstation/goonstation#2834]
[BUG]

**Describe the bug**
The test to see whether a staff assistant is wearing their own butt assumes the butt will be named "[name]'s butt" with no other words.

**To Reproduce**
1. Be a Staff Assistant
2. Objective: Make sure that you are wearing your own butt on your head when the escape shuttle leaves.
3. Get your butt cut off by the nice doctor.
4. Wear it like a hat.
5. Play the rest of the round as normal.
6. You're wearing a butt covered in random crap, which is not considered to be the same as a butt.

**Expected behavior**
Your butt is on your head, so you completed the objective.

**Screenshots**
![image](https://user-images.githubusercontent.com/4257305/100401224-7e3cd480-301e-11eb-8d7a-bcb0f3bd17b4.png)
![image](https://user-images.githubusercontent.com/4257305/100401232-8268f200-301e-11eb-914e-4b373602d2e1.png)

**Additional context**
I hope you enjoyed reading the worst bug report title ever.

**Comment by PrimeNumb** [comment]
Fixed as of https://github.com/goonstation/goonstation/pull/3546/files
