### ISSUE TITLE
Vent capture unit kit disappears when cancelled very late into the action

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#2837]
[minor]

**Describe the bug**
When using a VCU kit, if you cancel the action by moving while the bar is almost full, the vent-power-thingy isn't built, but the VCU kit disappears. It's possible that the sprite just became invisible, because I didn't check the surrounding tiles; still, buggy.

**To Reproduce**
1. Dig a hole, deploy VCU
2. When the action bar is almost full, move off the tile
3. You don't have the VCU kit, but also don't have the built VCU

**Expected behavior**
VCU is either built or the kit is still in my hand

**Comment by pali6** [comment]
I can't replicate this exact bug. However, a related bug which I assume actually happened occurs when you pick up the unbuilt vent capture unit. In that case the capture unit does get built but it's built *inside of you*.
