### ISSUE TITLE
Chest implants broken after tail merge

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#2842]
[BUG]

Implant a chest item without sewing it in. The item will never drop if inserted into a monkey unless it is gibbed or reclaimed.

**To Reproduce**
1. Accidentally place your scalpel in a monkey trying to figure out how to give it a tailectomy
2. Notice that it never falls out.
3. Reclaim or gib the monkey otherwise you're S.O.L.

**Expected behavior**
Item falls out of monkey.

**Additional context**
Tails are detached from their owner by placing them in the reclaimer.

**Comment by Sartorius7** [comment]
Yes the chest implant was unsecured, so I have no idea what was happening here

**Comment by Superlagg** [comment]
I couldn't replicate this happening. What were the exact steps you took that resulted in the thing getting stuck in the monkey?

**Comment by Sartorius7** [comment]
Accidentally sawed the monkey's chest open, sawed open the tail, scalpel got stuck in chest and wouldn't drop like it usually did. Might be lag related?

**Comment by Sartorius7** [comment]
I was thinking of arms!
