### ISSUE TITLE
Backpack sprite covering the hair sprite (tail PR related?)

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#2846]
[BUG]

**Describe the bug**

As the title says
It looks ugly and suspect it's also kinda related to the tail PR

**To Reproduce**
1. Have long hair
2. Notice it looks weird, being covered by the backpack

**Comment by TTerc** [comment]
well okay now I'm just gonna close this since it's a duplicate

**Comment by comradef191** [comment]
(#2845 Is the other Issue in question for those wondering)
