### ISSUE TITLE
Cloning Lizards Creates Horrible Hybrids

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#2847]
[BUG]

**Describe the bug**
https://cdn.discordapp.com/attachments/412408851980222465/782025149062184970/unknown.png
https://cdn.discordapp.com/attachments/412408851980222465/782025497017843752/unknown.png
https://cdn.discordapp.com/attachments/412408851980222465/782025928662057000/unknown.png

**To Reproduce**
1. Clone a lizard person
2. See Bug

**Expected behavior**
Cloned lizard to be a full lizard and not a horrible mutant

**Screenshots**

**Additional context**

**Comment by Sartorius7** [comment]
In addition, this results in people not maintaining their colors or hairstyles when changed from human to mutant race.
