### ISSUE TITLE
Miasma will kill ghostcritters too damn quick

### ISSUE THREAD

**Issue by A4Brogan** [goonstation/goonstation#2850]
[BUG]

**Describe the bug**
Got to be an awesome critter after getting gibbed? Too bad, since the crew leaves corpses around, the inevitable miasma clouds will wipe out your health in about a minute, have fun waiting another 6-10 minutes to try again!

**To Reproduce**
1. Become critter
2. walk into miasma
3. Watch as your 4 health is gone in a minute or so.

**Comment by Carbadox** [comment]
(Unintended) Feature and not bug. Critters have very little health and miasma deals tox damage

**Comment by Carbadox** [comment]
Will close due to not being a bug
