### ISSUE TITLE
Ghost drones not inhabited by players can be pulled by others, drone recharger still occupied

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#2854]
[BUG]

**Describe the bug**
Pulling a ghost drone out of the charger (Non-player controlled) in Cogmap1 does not stop the animation and lets you pull them out, still thinking it as in the charger.

**To Reproduce**
1. Be a ghost drone
2. Have a non-player ghost drone be in a recharger, recently manufactured.
3. Pull the drone out of the recharger
4. Lightning animation still plays, cannot use charger, drone is still animated as if in charger.

**Expected behavior**
Either unable to pull out drone, or able to and charger acts as if it left on its own.

**Screenshots**
[https://i.imgur.com/HLkCSn7.png](url)

**Additional context**
Probably should either not be able to pull them out or able to. Also should try out what happens if a player inhabits a drone pulled from the charger.

**Comment by pali6** [comment]
Note: this only applies to ghostdrone factory rechargers in which drones get created. If a non-player-controlled drone is in another recharger moving it turns off the recharger.
