### ISSUE TITLE
Cannot open things as AI/Cyborg

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#2856]
[BUG]

**Describe the bug**
After crashing or otherwise randomly, I'll become unable to open specific menus, such as turret control, fabricator menus, etc.

**To Reproduce**
1. Crash on round start/during round while you play a cyborg or AI
2. Notice you can't open a GUI menu, and that's weird.
3. Be mad and relog
4. See error is fixed

**Expected behavior**
I can open the GUI menu with no issues.

**Additional context**
It might be that some flag isn't reset or that the GUI is under the window, I'm not quite sure.

**Comment by amylizzle** [comment]
Not really enough here to debug. Sounds like the byond client got into a weird state.
