### ISSUE TITLE
Invincible as borg

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#2857]
[BUG]

**Describe the bug**
I crashed on game start on Oshan Lab (second time this happens on Oshan specifically) and went about my business.
When I was caught in a explosion, my arms and legs were reportedly destroyed. However, they were fine and I retained full functionality.

**To Reproduce**
1. Crash on round start as borg on Oshan
2. Get caught in explosion
3. Notice your limbs are missing on health thing, but not visually or funcitonally
4. You are invincible?

**Expected behavior**
Your limbs die. You lose their functionality.

**Additional context**
Might be Oshan Laboratory specific, not sure. Crash might also not be necessary. Probably was a pipe bomb.

**Comment by amylizzle** [comment]
There's not really enough information to replicate this in any meaningful way. It sounds like a weird edge case that hasn't been reported again. If it *does* happen again, I'm sure someone will bug report.

**Comment by amylizzle** [comment]
I think I meant to close this with my last comment. Whoops.
