### ISSUE TITLE
Cloner spits out cloned human with no mind

### ISSUE THREAD

**Issue by Nihisohel** [goonstation/goonstation#2860]
[BUG]

**Describe the bug**
Cloner refuses to transfer mind to cloned human. 
Seems inconsistent as some rounds the cloner works and others does not.

**To Reproduce**
1. Die with a body and brain inserted in it
2. Stick body inside of clone scanner
3. Scan and clone the body
4. Body comes out as "Cloned human" with the body's cosmetics

**Expected behavior**
My mind in cloned human.

**Screenshots**
https://gyazo.com/7d285ebaa4f63a241d8d4010f9ad370a - My bodies although one is missing the hair oddly enough

**Additional context**

**Comment by alexeric123** [comment]
I'm having the same problem, I'm trying to clone this guy, and they come out as a "cloned human" with no mind.  They also seem to have flavor text, which I assume is from the person I'm trying to clone.

**Comment by Superlagg** [comment]
Awesome, my bugfix not only didn't fix cloning, but it broke it even worse. Sounds like a runtime.

**Comment by Superlagg** [comment]
Tarm fixed it!
