### ISSUE TITLE
Rotten monkeys get human overlay

### ISSUE THREAD

**Issue by flrsh** [goonstation/goonstation#2864]
[BUG]

**Describe the bug**
After a monkey dies and rots, it'll get the human rotten overlay.

**To Reproduce**
1. Spawn a monkey
2. Var edit its `stat` to 2
3. See the human rotten overlay, and the monkey's missing chest and feet (and maybe face?)

**Expected behavior**
Either the monkey does not have a rotten overlay, or it has its specific monkey rotten overlay. 

**Screenshots**
![image](https://user-images.githubusercontent.com/59894319/100523982-0aafda00-317a-11eb-8b74-a99727bc1dc1.png)
![image](https://user-images.githubusercontent.com/59894319/100524329-dc7fc980-317c-11eb-8d60-5d135ac88e54.png)

**Comment by Superlagg** [comment]
ewwwww
