### ISSUE TITLE
input.dm:114 Cannot read null.assailant

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#287]
[BUG] [RUNTIME]

**Describe the bug**
input.dm:114 Cannot read null.assailant

**Comment by flrsh** [comment]
To reproduce:

Grab someone.
Hand them your grab.
Have them try to block with the grab they were just handed.
Their grab + block will eventually disappear, but the blocked status effect will persist, and they will be unable to move.
Every time they try to hit a movement key, they'll cause this runtime.

**Comment by Tarmunora** [comment]
@mybluecorners close this
