### ISSUE TITLE
Porta sci and Nano med file sending issue

### ISSUE THREAD

**Issue by HalfEnder776** [goonstation/goonstation#2883]
[BUG]
[PDA]

**Describe the bug**
when sent the porta sci and nano med apps accepting one of them gives the other (for example accepting porta sci gives you nano med or accepting nano med gives you porta sci never both) so you end up with two of the same app with no real way of getting both. (note clearing messages and asking for them to be resent allows you to get the same glitch but with a different app being sent

**To Reproduce**
1. ask AI for porta sci and nano med 
2. go to messages and accept both files
3. check files only to find you have two of the same app

**Expected behavior**
it's simple getting both the porta sci and nano med as apps in your pda

**Screenshots**
![Screenshot 2020-11-29 161818](https://user-images.githubusercontent.com/64817682/100553882-ca765780-325e-11eb-8867-31de3be2aa4b.png)
![Screenshot 2020-11-29 161759](https://user-images.githubusercontent.com/64817682/100553883-cd714800-325e-11eb-872b-89e6aa19f356.png)

**Additional context**
yes i have enough storage room, before the apps i have 10 slots each takes 4 i have 2 left. also this appears to be an issue with messages themselves as clearing the messages allows you to replicate it with a different combination.

hope this bug report is good enough..

**Comment by amylizzle** [comment]
Bug already fixed.
![image](https://user-images.githubusercontent.com/3855802/179426025-d72abdc3-3577-4e09-bc73-bae4bfc0b023.png)
