### ISSUE TITLE
Bringing Space Tiles... to ABZU!

### ISSUE THREAD

**Issue by Kamades** [goonstation/goonstation#2886]
[BUG]

**Describe the bug**
If you build a mining magnet on the station Z level  (at least Oshan, untested on Manta), and pull in rocks from the Quantum Telescope, sometimes you get a larger rock.  If you do, and then follow it with a smaller rock, all the tiles the larger rock covered but are now uncovered are, in fact, space tiles.

**To Reproduce**
Build a mining magnet
mine
find space in the ocean????

**Expected behavior**
Not space in the ocean, but ocean in the ocean

**Comment by ZeWaka** [comment]
proper fix: disallow mining magnet construction on underwater maps
