### ISSUE TITLE
admin.dm:3400 Cannot read null.mob

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#289]
[BUG] [RUNTIME]

**Describe the bug**
Cannot read null.mob

**Comment by ZeWaka** [comment]
wat this makes no sense: 
https://github.com/goonstation/goonstation/blob/aba391bb33f130561b6306571a3b4581c80b31cd/code/modules/admin/admin.dm#L3400

**Comment by pali6** [comment]
Fixed ages ago by 31df73614d020b91ef548b3e3779aac0ea649180.
