### ISSUE TITLE
unarmed landmines cannot be picked up/dragged/armed

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#2911]
[BUG]

**Describe the bug**
Unarmed landmines (for instance, those on the Cairngorm which I love using) cannot be picked up or dragged.  Since they can't be picked up, they can't be armed.  Since they can't be armed, they can't do anything.  They're totally useless!

**To Reproduce**
1. Click on an unarmed landmine.
2. Click again.
3. Keep clicking.
4. Start crying, screaming "WHY CAN'T I PICK THIS UP" over and over, while still clicking.

**Expected behavior**
Clicking on an unarmed landmine with an empty hand puts it in your hand, allowing you to move it around and arm it.

[BUG]

**Comment by virvatuli-gh** [comment]
Heya, just letting you know that I found the reason why they weren't working and this will be fixed when I'm done making some changes to how landmines function in general.
