### ISSUE TITLE
Constructing firebot with a tinkered fire extinguisher resets the extinguisher to default

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#2912]
[BUG]

**Describe the bug**
When constructing a firebot with emergency toolbox, cyborg arm and a fire extinguisher with custom chemicals (eg. welding fuel + foam instead of water + foam), the resulting bot is armed with a default extinguisher.

**To Reproduce**
1. Empty an extinguisher by shooting all of its load on the floor
2. Fill the extinguisher with something interesting, like neurotoxin, capulettium or whatever. This makes the extinguisher splash some chemicals on the floor when used (Note: the chemical needs to be able to create puddles for it to work). Also fill the extinguisher with some foam, I guess.
3. Create a firebot normally using this tinkered extinguisher, cyborg arm, emergency toolbox and a proximity sensor
4. Make a monkey go fire
5. Bring the firebot next to monkey
6. Firebot shoots foam with water instead of new stuff

**Expected behavior**
Would be quite nice to be able to make firebots shoot some nasty stuff. Or something extra helpful.

**Comment by Carbadox** [comment]
Gonna close this since this is unfortunately how construction works and not really a bug. Good idea for possible feature but forums are probably a better place for keeping track of those.
