### ISSUE TITLE
Drinking sheltergrog makes one human after it wears off.

### ISSUE THREAD

**Issue by 112358sam** [goonstation/goonstation#2922]
[BUG]

**Describe the bug**
After the effects of sheltergrog wear off, the drinker becomes human no matter their prior form.

**To Reproduce**
1. Be non-human. This was discovered as a lizard.
2. Drink sheltergrog.
3. Wait for it to wear off.
4. Revert to human instead of prior form.

**Expected behavior**
I would expect to revert to the species prior to consuming the sheltergrog.

**Comment by Superlagg** [comment]
I think Pali fixed this! Give it a shot, lemme know if it works!

**Comment by Carbadox** [comment]
@pali6

**Comment by 112358sam** [comment]
Sorry, it took me a while to get sheltergrog again. I can confirm it works as expected now. Thanks!
