### ISSUE TITLE
Mysterious white monkey limb

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2927]
[BUG]
@Superlagg 

**Describe the bug**
admin healing a limbless monkey resulted in 1 of the limbs being white and a human limb instead of monkey limb

**To Reproduce**
1. sever all monkey limbs
2. admin heal

**Expected behavior**
no weird white limb

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/101056111-a2d20880-3558-11eb-990f-4741c013aa96.png)

**Comment by Sovexe** [comment]
assigning this to @Superlagg as I believe they have been handling these issues as they've been reported thus far
