### ISSUE TITLE
Floating chat gets left behind in an industrial chute :(

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#294]
[BUG]

**Describe the bug**
The floating chat gets stuck in a disposalholder
**To Reproduce**
1. Enter an industrial loading chute
2. Get spat out the very next tile
3. While the chute's still reopening sprint over it diagonally so you don't fall in
4. See screenshot

**Expected behavior**
Ideally, my speech should run as fast as I do. I don't want some anemic ass voice come on

**Screenshots**
![image](https://user-images.githubusercontent.com/63235460/79577514-1f48d180-80c5-11ea-8023-35741838bda5.png)

**Additional context**
Kondaru

**Comment by Carbadox** [comment]
Tested locally, no longer the casee
