### ISSUE TITLE
Wiping down (bloody) limbs turns them white

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#2946]
[minor]

**Describe the bug**
Limbs, when cleaned with a sponge, turn white (probably the base sprite colouring.
I think the limb might have to have the blood overlay on it for this to happen from what I can tell, but I'm not sure. The only butt I've been able to try (which was bloody) didn't turn white.

**To Reproduce**
1. Get a wet sponge and an assortment of limbs
2. Wipe limbs with sponge
3. See error

**Expected behavior**
No change in skin colour

**Screenshots**
![image](https://user-images.githubusercontent.com/31984217/101217284-5f26ee00-3681-11eb-84cc-e80db48ad701.png)

**Comment by Superlagg** [comment]
atom_forensic.dm:176 `CI.icon = initial(icon)` seems to be the issue.

**Comment by frawhst** [comment]
No longer occurs
