### ISSUE TITLE
Siren helmet stops working upon enterign cargo cart

### ISSUE THREAD

**Issue by Kapu1178** [goonstation/goonstation#2952]
[BUG]

**Describe the bug**
Upon entering the cargo cart, the helmet colors disappear and the siren stops. How am I supposed to be the ambulance without a signal?

**To Reproduce**
1. toggle on siren helmet
2. get in cargo cart
3. Profit
**Expected behavior**
siren + light should function in a cargo cart
**Screenshots**
N/A

**Additional context**
AMBULANCE NO WORK

**Comment by Carbadox** [comment]
similar to #2642
This is more of just an inherent issue with how vehicles work. Vehicles need a rework in general
