### ISSUE TITLE
Defunct E-meter in stocks

### ISSUE THREAD

**Issue by Nihisohel** [goonstation/goonstation#2954]
[BUG]

**Describe the bug**
E-Meters can still be found in Christmas Stockings and somewhat usable albeit a lacking sprite?

**To Reproduce**
1. Become player
2. Join Round
3. Find and dig through nearby stocking
4. Pull out spriteless E-meter from stocking

**Expected behavior**
These are removed right?

**Screenshots**
https://gyazo.com/d924ab6f0950c9da29d171497621ecd3
https://gyazo.com/464d4f45dcc94534d2f0e0e6289eb5bb

**Additional context**
You can also click yourself to view your thetan levels despite its lack of sprite.
I deserve a gift, I've been scammed.

**Comment by BatElite** [comment]
The PR for removing the e-meter (#2756) didn't get merged, but the sprite the e-meter uses (forensic0 in device.dmi) was deleted in #2887 

The seed planter was probably also invisible until about 10 minutes ago.
