### ISSUE TITLE
Mutant and borg arms do not work for monkeys

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#2967]
What should be a normal arm arm when attached to a monkey functions as an item arm for some reason. (Does not include limbs gained through artifacts those are fine for some reason)

1. Become a monkey
2. Get your arms cut off (in my circumstance i had borg arms before this from an artifact so that my affect it)
3. Get them replaced with new ones (tested with wendigo and cyborg)
4. They function like item arms

The brand new limb should function like normal. It probably has something to do with the changes to limbs that happened recently

![Arm bug 1](https://user-images.githubusercontent.com/53524124/101279001-694f0680-37bf-11eb-846e-9dc9dfd6e6f4.JPG)
![Arm bug](https://user-images.githubusercontent.com/53524124/101279004-6c49f700-37bf-11eb-9ef6-74776a99aed4.JPG)

**Comment by Superlagg** [comment]
Mutant and borg limbs shouldnt be attaching there *at all*! Mainly because I don't have sprites for them that don't look downright hecked.

Though, forbidding monkeys from getting cyberlimbs is kind of awful. I'll figure out a solution!
