### ISSUE TITLE
Rev heads don't count as dead if antag critters/pests/in the afterlife bar

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#2977]
[BUG]

**Describe the bug**

**To Reproduce**
1. Be a rev head
II. Become an antag critter, pest, or join the afterlife bar
C. Round doesn't end

**Expected behavior**
Round should end when they all die

**Additional context**
I'm not sure WHICH of the three was the one causing the issue. One rev head became an antag critter via random even. Another rev head became a pest. The last was in the afterlife bar.

**Comment by pali6** [comment]
Critters shouldn't be causing this.
