### ISSUE TITLE
Runtime in jobban.dm when testing on local via vscode

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#2983]
[BUG] [RUNTIME]

**Describe the bug**
as the title says

**To Reproduce**
 try to change job  preferences in character setup before round loads
**Expected behavior**
no runtime runtime bad

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/101498898-9e339880-393a-11eb-94b6-37d9272a9004.png)
![image](https://user-images.githubusercontent.com/63602513/101498963-b1deff00-393a-11eb-96f5-cbc5652c846d.png)

**Comment by RSG250** [comment]
it runtimed 27 times before it let me get to prefences

**Comment by RSG250** [comment]
this runtime also happens when changing job priorty

**Comment by RSG250** [comment]
all i did was change favortie job to staffie and put chief in low
doing this resulted in 83 runtimes

![image](https://user-images.githubusercontent.com/63602513/101500643-befced80-393c-11eb-862d-d801ea7d25cd.png)

**Comment by zjdtmkhzt** [comment]
Might only occur on local copies, because they do not have the ability to use the api to check for jobbans?

**Comment by RSG250** [comment]
happen when people spawn in too

**Comment by pali6** [comment]
fixed by e2dcda0
