### ISSUE TITLE
Histamine production impossibly outpaces removal drugs too much with hyperallergic trait

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#2989]
[BUG]

**Describe the bug**
Twice now a patient with hyperallergic trait with no listed allergy in medical records has had impossible to remove (without admin intervention) levels of histamine.

It basically stayed at around 120u of histamine and couldn't be purged. Things tried: penetic acid, charcoal, anti-histamine, epi, calomel, heart replacement (dropped to 75u then zoomed back to 120u)

**To Reproduce**
1. Have hyperallergic trait
2. Get histamine in system from wasps or similar
3. Have doctor unload purge chems into system

**Expected behavior**
To not need admin intervention to fix histamine.

**Comment by Kapu1178** [comment]
I use Hyper allergic, and I'm able to flush it from 125 with 1 epinephrine shot, and 2 anti-histamine shots. However, this could be due to my slow metabolism as well.

**Comment by Tiggersaurus** [comment]
Yeah hyperallergic was the only chem related one that I saw on the medical records, should have taken a screenshot but was too busy trying to keep them and someone else alive heh.

I don't know if something else was going on, @flrsh even code dived.

The fact it was ridiculously outpacing pentetic acid and calomel did nothing makes me go =/

**Comment by pali6** [comment]
Fixed a while ago by a446dd1d655eade643ba0ef437f651f8ef94d62c.
