### ISSUE TITLE
Genebooth lets you clip through walls

### ISSUE THREAD

**Issue by Kapu1178** [goonstation/goonstation#3044]
[BUG]

**Describe the bug**
Exiting the Gene Booth diagonally lets you enter walls, potentially clipping through them.

**To Reproduce**
1. Hold AW/WD while diagonal from the Genebooth
2. Enter gene booth
3. Exit into wall (Manta Gene Booth shows it clearly)

**Expected behavior**
You shouldnt be able to do this

**Comment by Sovexe** [comment]
3c8d54a0ad30688ba235cf3c06a1ddd93948cb17
