### ISSUE TITLE
Stable mutagen doesn't copy appearance

### ISSUE THREAD

**Issue by PrimeNumb** [goonstation/goonstation#3049]
[BUG]

**Describe the bug**
Title. Name is copied correctly, though.
**Expected behavior**
To copy the appearance.

**Comment by Tarmunora** [comment]
![image](https://user-images.githubusercontent.com/48066662/102025769-c61e6400-3d5f-11eb-9fa4-1fb591634d3b.png)
image of bug

**Comment by Superlagg** [comment]
Does it still do this?

**Comment by Tarmunora** [comment]
don't think so
