### ISSUE TITLE
seal_hair is broken

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#3066]
[BUG]

**Describe the bug**
Hats and helmets with ```seal_hair = 1``` are meant to hide a player's hair, but they don't anymore.

**To Reproduce**
1. Wear anything that's meant to hide hair
2. See error

**Expected behavior**
No hair, for better or worse

**Additional context**
It's been a thing for a little while but I don't remember when I first noticed. I figured someone other than me would notice & report though

**Comment by Superlagg** [comment]
Oh I probably broke something. I'll see if I can fix it!

**Comment by Yellow-Mushroom** [comment]
As a character with medium hair and a very long beard this is something I never knew of, would love to see it fixed so my identity isn’t given away

**Comment by BatElite** [comment]
Solved by Superlagg's patch
