### ISSUE TITLE
You can still buy an E-meter from traders

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#3068]
[BUG]

**Describe the bug**
You can still buy e-meters since their removal via traders, and their sprites are broken.

**To Reproduce**
1. Buy a scanning device from Pianzzi or whatever their name is
2. Receive an e-meter
3. See bug

**Expected behavior**
One shouldn't even be able to buy those at all since their removal.

**Comment by BatElite** [comment]
E-meters weren't removed, but the PR updating the security records thing removed the sprite it was using.

**Comment by ZeWaka** [comment]
Not a bug
