### ISSUE TITLE
Clothes/worn objects dont update visually when changed on a wheelchair

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#3077]
[BUG]

**Describe the bug**
When on a wheelchair, removing items such as a backpack, cutting off bandages, or other such objects, doesnt remove them from your character visually

**To Reproduce**
1. Wear backpack/bandanges/etc
2. Remove them through process or click
3. Witness them still being there
4. Reequiping and deequiping does not solve bug
5. putting something on after sitting in wheelchair then taking off doesnt seem to add to bug

**Expected behavior**
Items should not be visible after taken off

**Comment by pali6** [comment]
unable to reproduce
