### ISSUE TITLE
Cryosleep unit offsetting itself incorrectly

### ISSUE THREAD

**Issue by Kubius** [goonstation/goonstation#3096]
**Describe the bug**
The cryosleep unit often found in crew quarters may sometimes be offsetting by two tiles to the right of its map file position instead of one. This doesn't significantly affect most maps, and doesn't appear to happen every round.

**To Reproduce**
No idea. The issue cropped up on server 2 during a Kondaru round, but a local compile of Cog2 and Kondaru behaved normally.

**Expected behavior**
The ideal behavior would be for the position of the cryosleep unit in map editors to accurately reflect the position it ends up ingame. Barring that, it consistently offsetting by one tile (same as "before") would work.

**Screenshots**
![image](https://user-images.githubusercontent.com/12454065/102550179-04c75d80-4083-11eb-85fc-35afa652374c.png)

**Comment by Sovexe** [comment]
`pixel_x = -32` someone "fixed" it not showing correctly in map editors which caused the issue in game since map editors don't properly show how objects with modified bounds work

it needs to be adjust 32 pixels left in map editors but not ingame to show correctly in both

**Comment by Sovexe** [comment]
map editors don't respect how `bound_x` and `bound_y` offset the object ingame. Best I can do is fix it in strongDMM and fastDMM but it will still look wrong in dream maker

**Comment by Sovexe** [comment]
f0e9aace2f574b18287b31ec2dcbccf1be0fa3ce
