### ISSUE TITLE
Comms computer/Commaster functionality

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#3101]
[trivial]

**Describe the bug**
After restarting the communications console to try and call the shuttle, I loaded up Commaster. The screen defaulted to the previous function that someone was trying to do, which was transmit a message to Centcom. I could not back out of it and use the Call function, even restarting the console, and had to send the message before I could. 

**To Reproduce**
1. Begin sending a message to Centcom (looks like it was partially completed, just the title)
2. Restart console
3. Run Commaster and find it default to the message Centcom screen
4. You cannot engage in any other function in Commaster until it is sent

**Expected behavior**
Restarting should at least allow you to back out of the Message Centcom screen and enable the use of other functions, rather than locking you out of every other function.

**Comment by pali6** [comment]
It might not be properly documented but trying to send an empty message or a message with an empty title cancels it.
