### ISSUE TITLE
Oshan limb loss by falling into trench/deep abyss resets the limb type to the default human variety

### ISSUE THREAD

**Issue by Legendahkiin** [goonstation/goonstation#3104]
[BUG]

**Describe the bug**
Falling into the Deep Abyss on Oshan with special limbs and losing them resets them to their default, human variety.

**To Reproduce**
1. Have a special limb (e.g. space-bear arm)
2. Fall down into the Deep Abyss (not sure if trench also counts?)
3. Lose said special limb 
4. Pick up the now default limb from the floor

**Expected behavior**
The limb that is lost should be the equivalent of what it was when it was on your person.
So a space-bear arm should drop should you have a space-bear arm, and not a regular, human arm.

**Additional context**
Untested with regular trench, but I would assume it works the same -- though I don't know if you can lose limbs by falling into the trench.

**Comment by amylizzle** [comment]
Falling down a trench hole no longer causes you to lose limbs.
