### ISSUE TITLE
Secret wall doors can't be reinforced or attached to reinforced walls

### ISSUE THREAD

**Issue by Efimero** [goonstation/goonstation#3126]
[BUG]

**Describe the bug**
When trying to make a reinforced secret wall door, there is no pathway to craft it and the regular one doesn't attach properly to reinforced walls.

**To Reproduce**
1. Construct two reinforced walls one tile appart **vertically**
2. Construct a girder between them and detach it
3. Plate it to make a secret wall door
4. The door opens horizontally instead of vertically
5. There is also no way to get a reinforced version

**Expected behavior**
Plating a reinforced girder that would give a reinforced wall, but detached, should give a reinforced hidden door.
Both hidden doors should attach properly to other walls regardless of the kind and be able to slide vertically.

**Comment by stonepillars** [comment]
Fixed by #9231
![image](https://user-images.githubusercontent.com/65367576/183291286-8bd66a06-83e5-4631-83df-3e55948b8b0d.png)
