### ISSUE TITLE
fully upgraded med health scanner acts like a normal one

### ISSUE THREAD

**Issue by HalfEnder776** [goonstation/goonstation#3146]
[BUG]

**Describe the bug**
simple i have a fully upgraded health scanner but the scan pop up has no organs or chems

**To Reproduce**
im not fully Shure sadly at some point it just stopped working like an upgraded one

**Screenshots**
![image](https://user-images.githubusercontent.com/64817682/103060677-05765d00-4577-11eb-8cf4-d19bea7d7d93.png)

**Comment by mordent-goonstation** [comment]
I'm confused. What part of that screenshot isn't how you expect a fully upgraded health scanner to work?

**Comment by mordent-goonstation** [comment]
(I suppose the first scan, but I guess follow up question: where these back-to-back scans or did anyone have a chance to interact with the scanner? They can have their upgrades enabled/disabled.)

**Comment by BenLubar** [comment]
since you're holding two scanners, I'm guessing one of them got disabled (use it on itself to toggle through modes)

**Comment by Carbadox** [comment]
Could not reproduce. Scanner was most likely accidently disabled by user.
