### ISSUE TITLE
paper bins recycle paper titles

### ISSUE THREAD

**Issue by BenLubar** [goonstation/goonstation#3149]
[MINOR]

**Describe the bug**
Since about when the paper UI changes happened, paper bins have been producing pieces of paper with existing titles, like "Sales Invoice - Graag" or "Citation: Some Name".

**To Reproduce**
1. Play a round for a while so that some titled paper gets destroyed in one way or another.
2. Pull a piece of paper out of a fresh paper bin (not a paper bin that has had paper added manually)
3. The pizza has not disappeared

**Expected behavior**
Paper should not have a title.

**Comment by Sovexe** [comment]
267dc44c7072e29eec52311f3a9c8f5e8be8b700
