### ISSUE TITLE
Dragging items into crates full of injectors creates a visual glitch

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#3157]
[BUG]

**Describe the bug**
If you click-drag an item into a closed locker/crate that has DNA injectors in it, the injection animation for the injector plays even if it's expended.

**To Reproduce**
1. Have a closed crate with a spent injector in it.
2. Click-drag an item into the crate to stuff the item in said crate.
3. See error.

**Expected behavior**
No animation should play.

**Comment by amylizzle** [comment]
Can't replicate. It's possible you may just be mistaking the changing of the layer of the item in the crate for the animation flick.
