### ISSUE TITLE
No Longer visually blind after exiting cryo

### ISSUE THREAD

**Issue by Zergspower** [goonstation/goonstation#3180]
[BUG]

**Describe the bug**
Blind perk visually goes away (still blind) and I gain normal vision. I'm still however immune to flashes and unable to see emotes as per if i were normally blind.

**To Reproduce**
1. Have blind perk 
2. Have a friend show up out of nowhere and cause you to go to cryo for 72 minutes
3. Leave Cryo

**Expected behavior**
Vision to stay super narrow

**Comment by Carbadox** [comment]
Could not reproduce
