### ISSUE TITLE
Windows deal burn damage.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#3193]
[BUG]

**Describe the bug**
When you grab somebody and slam somebody into a window it does exactly 5 burn damage.

**To Reproduce**
1. Grab somebody.
2. Click on a window with the grab.
3. When they are slammed into the window they will have 5 burn damage.

**Expected behavior**
The monkey should have been dealt 7 brute damage instead of 5 burn. The are being slammed into a solid object, not a fire.

**Screenshots**
![image](https://user-images.githubusercontent.com/40079883/103386363-0f8ee300-4ac4-11eb-86c0-a3839d8ad02c.png)
![image](https://user-images.githubusercontent.com/40079883/103386393-3cdb9100-4ac4-11eb-948a-ecd96030a032.png)

**Additional context**
Maybe it was for an interaction with light bulbs or maybe it was for when the window is near space? It happens with any window though.

**Comment by Tarmunora** [comment]
80e40b9bfb8a4b2ecf98ae0908881e6bd69f4a51
