### ISSUE TITLE
AI PDA unable to interface with teleporting equipment

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#32]
The AI's internal PDA is unable to see and subsequently interface with the following remote controlled equipment:

Port-A-Nanomed
Port-A-Medbay
Port-A-Brig
Port-A-Sci

The programs themselves work, but the individual pieces of equipment do not show up, even after you attempt to 'Scan for Linkable Machinery'

This is a repeating bug that occurs across all rounds, starting sometime yesterday afternoon.

Note: This is one of my first bug reports. If this is insufficiently written or formatted, please let me know and I will correct this issue.

**Comment by ZeWaka** [comment]
Caused by https://github.com/goonstation/goonstation/blob/4059e4be90832b02b1228b1bee3db342094e4f1e/code/obj/item/device/pda2/portable_machinery_control.dm#L107

I changed this the other day from `for (src.our_machinery in src.machinerylist)` which is terrible and does not do what you expect.
