### ISSUE TITLE
AI receiving ALL pda notifications

### ISSUE THREAD

**Issue by Zergspower** [goonstation/goonstation#3202]
[BUG]

**Describe the bug**
playing AI after one of the recent changes to them introduced a sanity breaking 'feature' of any alert being blasted about 6 times over on each channel. So all shipping updates, medical updates, sales from the gene booth etc etc.

**To Reproduce**
1. play AI on a full server
2. Watch as your brain melts

**Expected behavior**
Probably ability to mute individual channels vs an all or nothing approach

**Screenshots**

**Additional context**

**Comment by BatElite** [comment]
#3178 looks like it'll address this issue
