### ISSUE TITLE
Unable to do tricks or fall off skateboard

### ISSUE THREAD

**Issue by SimianC** [goonstation/goonstation#3208]
[BUG] 

**Describe the bug**
After getting onto a skateboard you are unable to perform tricks by grinding on intended surfaces, and you are unable to fall off after colliding with walls or windows. The meter for performing tricks appears but does not fill up. 

**To Reproduce**
1. Click-drag sprite onto a skateboard
2. Move in any direction and attempt to crash into a surface 

**Expected behavior**
Skateboards should perform tricks when colliding into tables, lockers, and other intended surfaces, building meter and giving you a RAD popup. Crashing into walls and windows should cause you to fall off the board.

**Comment by pali6** [comment]
Fixed by 063e6d5. Blame Lummox.
