### ISSUE TITLE
Can't leave latejoin cryo on Kondaru

### ISSUE THREAD

**Issue by TemporalOroboros** [goonstation/goonstation#321]
[BUG]

**Describe the bug**
The arrivals cryo did not eject me as a latejoiner. I was stuck inside the southwest section and could not move.

**To Reproduce**
1. Latejoin on Kondaru
2. Realize that you can't move.

**Expected behavior**
I expected to be ejected from the latejoin cryo.

**Additional context**
There was some adminry going on that round as space was an ocean of blood. I don't see how that could have affected the cryo but I'll put is here anyways.

**Comment by ZeWaka** [comment]
likely fixed in #320
