### ISSUE TITLE
The AI can tuck people into bed remotely.

### ISSUE THREAD

**Issue by BenLubar** [goonstation/goonstation#3217]
[BUG]

**Describe the bug**
The AI can perform drag-and-drop interactions on beds.

**To Reproduce**
1. Locate someone on the same tile as a bed as AI.
2. Drag them to the bed.
3. Drag the bedsheet to the bed.
4. It is now naptime. Somehow.

**Comment by Boxlta** [comment]
This should be a feature

**Comment by Tiggersaurus** [comment]
That fucking adorable 😍

**Comment by BenLubar** [comment]
It's a problem if they're cuffed, but maybe the bedsheet interaction can stay
