### ISSUE TITLE
Can highlight text in the tooltips that show up when you hold alt

### ISSUE THREAD

**Issue by BenLubar** [goonstation/goonstation#3218]
[TRIVIAL]

**Describe the bug**
It'd be nice to add `user-select: none;` to the tooltip style so that the item tooltips that show up when you hold alt can't be highlighted. I'd do it myself, but I have no idea where in the code those are handled.

**To Reproduce**
1. Hold alt and hover over an item
2. I have no idea how I managed to highlight it, but it's happened on multiple occasions
3. The entire tooltip remains highlighted until you manage to click on it (which is hard because it disappears as soon as you mouse away from the item)

**Comment by imizaac** [comment]
OMG Yes I had the same issue. Lemme take this on.
