### ISSUE TITLE
Lab counter storage displays weirdly on TG-style HUD

### ISSUE THREAD

**Issue by Tarmunora** [goonstation/goonstation#322]
[BUG]

**Describe the bug**
When clickdraging a lab counter to yourself on TG-HUD, the inventory popup is off-center and zooms out the screen

**To Reproduce**
1. Turn on TG-style HUD
2. Clickdrag lab counter to your mob while standing next to it

**Expected behavior**
A UI that isn't weird?

**Screenshots**
![image](https://user-images.githubusercontent.com/48066662/79672113-baf54300-8194-11ea-8466-aeefc926bd4a.png)

**Comment by ZeWaka** [comment]
/tg/ inventory offset + larger than normal (7 iirc) slots seems like

I thought we had inventory stacking to handle this
