### ISSUE TITLE
Breaking Pods (as borg)

### ISSUE THREAD

**Issue by alexeric123** [goonstation/goonstation#3220]
[BUG]
Trying to break in a pod, at least as a borg, does not stop the pod anymore. I am unsure if this affects humans too.
I am also not holding any movement keys while trying to break.

**To Reproduce**
1. Be moving in a pod
2. Hold shift
3. The pod is not stopping/slowing down

**Expected behavior**
The pod slowing down/breaking

**Comment by alexeric123** [comment]
Part 2. 
Sometimes, when it does stop, the pod still has some momentum in it, as seen by the pod jerking the other direction when pressing a movement key. Tapping Shift/any key has the same effect.  This makes it so it is VERY hard to use the wormhole ability. (This part, at least i have heard some non-silicons having the same problem)

**Comment by Tarmunora** [comment]
fixed
