### ISSUE TITLE
Minisubs no longer move when a key is not held

### ISSUE THREAD

**Issue by 112358sam** [goonstation/goonstation#3223]
[BUG]

**Describe the bug**
The minisub stops immediately when no movement key is pressed. The sub retains its velocity 'memory' and will still impact a wall at full force if the next key press moves the sub into an obstacle. The sub resumes when the next movement key is pressed. The behavior is distinct from having braking on where speed falls off before coming to stop and must be rebuilt to get back up to speed. 

**To Reproduce**
1. Get in a minisub
2. Attempt to drive

**Expected behavior**
The minisubs on Manta and Oshan used to work with tank controls where the left and right keys turned the sub while the forward and back set speed. Once a speed was set, the sub would continue until a new input or it could no longer move in that direction. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ZeWaka** [comment]
i fix
