### ISSUE TITLE
Patting doctor cyborg on the head interrupts the healing

### ISSUE THREAD

**Issue by BenLubar** [goonstation/goonstation#3233]
[MINOR]

**Describe the bug**
Patting a mediborg on the head interrupts it.

**To Reproduce**
1. Use an automender to heal someone
2. Receive headpats
3. ctrl+s

**Expected behavior**
Don't pat my head that hard

**Comment by flrsh** [comment]
Please don't use the critical label as a joke.

**Comment by Yellow-Mushroom** [comment]
Another issue is that when you start healing another doctor with a auto-mend, it stops them from automending

**Comment by MetricDuck** [comment]
Automenders interrupt other automenders because they call attackby on the first click.

**Comment by ThatFiveGuys** [comment]
Was fixed in #3550
