### ISSUE TITLE
Reinforcing a shuttle wall replaces it with a reinforced normal wall

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#324]
[BUG]

**Describe the bug**
Upon attempting to reinforce a shuttle wall, it replaces it with a reinforced normal wall. This does not seem to be intended behaviour, given that it's immune to all other types of damage.

**To Reproduce**
Steps to reproduce the behaviour:
1. RCD
2. Switch to `RCD_MODE_FLOORSWALLS` and click shuttle wall.
3. It become rwall
4. bad

**Expected behaviour**
either ignore or give message

**Comment by Gerhazo** [comment]
You appear to be able to just flat-out deconstruct them with an RCD as well.
