### ISSUE TITLE
Stuck Beaker Glitch

### ISSUE THREAD

**Issue by CosmicEcho** [goonstation/goonstation#3244]
Picked up a beaker in the pharmacy of Cogmap 2 and the beaker was thoroughly stuck to my hand. Attempting to put it in containers did not work, and I eventually found a way to duplicate the damn thing and hold it in my other hand by putting it in the heater. 

No idea how to reproduce this, but it was likely that a borg had messed with the new chem dispenser UI and found a way to drop the chem beakers they get as tools. Had to be respawned to have it removed from my hands.

**Comment by BenLubar** [comment]
It's quite likely it was a borg beaker based on your description. The chem dispenser isn't properly handling items that cannot be dropped.

**Comment by moonlol** [comment]
Borgs could 'drop' their beakers like this before the new ui

**Comment by pali6** [comment]
fixed by 3a935e8
