### ISSUE TITLE
Changeling + short sightedness does not work as intended

### ISSUE THREAD

**Issue by killeroid356** [goonstation/goonstation#3250]
[BUG]

**Describe the bug**
Exactly what it says in the tin.

**To Reproduce**
1. choose the starting trait that gives you short sightedness and perscription glasses
2. spawn as a ling
3. be unable to see clearly!

**Expected behavior**
the glasses should nullify the short sightedness

**Screenshots**
https://snipboard.io/jmceFb.jpg
if the link does not work i can send the original png

**Comment by Carbadox** [comment]
Do you happen to know what map this was on?

**Comment by killeroid356** [comment]
Oshan, but i presume the bug would persist regardless of map

**Comment by Carbadox** [comment]
I've had a bug before where glasses wouldnt resolve shortsightedness on ocean maps. Could possibly be linked

**Comment by killeroid356** [comment]
Ive played on oshan before with no issue regarding glasses, so im willing to believe its a ling thing

**Comment by amylizzle** [comment]
Unable to replicate, seems like it was already fixed.
