### ISSUE TITLE
Lootcrates don't contain loot

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#3271]
[BUG]

**Describe the bug**
Opening a lootcrate opens the box and gives no reward.

**To Reproduce**
1. Get access to a lootcrate
2. Open it
3. The box opens but nothing happens
Experienced on live server but testing locally with build mode to spawn /obj/lootbox gives this result.

**Expected behavior**
The lootcrate graphic and reward should show, an item should be spawned.

**Comment by ZeWaka** [comment]
pretty sure they don't have random contents, they have to be given contents

**Comment by flappybatpal** [comment]
That would make sense for spawning them using admin tools but in battle royale the airdropped crates (red X marker, glowing yellow) also have no contents.
