### ISSUE TITLE
Ghostdrones can use switches and stuff from a distance

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#3272]
[BUG]

**Describe the bug**
Ghostdrones can now use various electrical things without being next to them. I'm guessing it's a side effect of #3131

**To Reproduce**
1. Become a ghostdrone
2. Do not have any tool selected
3. Click on light switches, APCs etc, from a distance

**Expected behavior**
Ghostdrones need to be adjacent to things they want to use.
I don't know if this necessarily needs to be patched, but it's worth bringing up.

**Additional context**
I've tested this on light switches, APCs and fire alarms. I'm guessing you can also use computers and stuff, but the round was ending by then and I didn't want to poke important stuff as a drone on a live round.

**Comment by pali6** [comment]
I'm fine both with the old and with the new behaviour personally.

**Comment by BenLubar** [comment]
Ghost drones are silicon-based, which causes a lot of stuff like this.

**Comment by BatElite** [comment]
I'm fine with things as they are right now (being a drone enthusiast) but mordent said it wasn't intentional so I brought it up.

**Comment by BatElite** [comment]
Since neither pali nor I see a problem I'll close this issue for the moment, but if something thinks it's a problem they can re-open it,

**Comment by mordent-goonstation** [comment]
Agreed. Unintentional, but I don't see a problem. If for some reason it becomes a problem we can re-visit.
