### ISSUE TITLE
Lingering text box and an inability to move/use UI.

### ISSUE THREAD

**Issue by jaxblonk** [goonstation/goonstation#3273]
[BUG]

**Describe the bug**
A lingering text box from the afterlife bar in the round prior, describing a matchbook, remained through the character confirmation and into the next round, wherein it was found that the cyborg I was playing couldn't move or use their UI elements. 

**To Reproduce**
Steps to reproduce m y behavior:
1. Attempt kermitting sudoku w/ fire in afterlife bar at round end
2. Upon collapsing spam click the matchbook until after timer runs out
3. If the UI element remains on screen through the round timer and into the next round, you might got it, rejoice.
4. Notice metaphorically broken legs.
5. Attempt workarounds with very limited success before quitting and rejoining.
6. No longer Lieutenant Dan.

**Expected behavior**
Movement, primarily? Changing from the default borger boi?

**Screenshots**
I forget to post when I alt+prtsc but there wasn't much to see either I feel. 

**Additional context**
Seeing as I have no idea, well, how to use GitHub whatsoever- but more relevantly wherein the bug began or the extent to which it may be replicable, I'm going into as much detail about the circumstances which brought me there as I can recall, even if it means rambling on with a great deal of pointless drivel or dead ends. 
I simply don't know what might be pertinent. My apologies, and thank you all.

**Comment by pali6** [comment]
Could you please edit your bug report with more details, correct body and a more concise title?
