### ISSUE TITLE
Chicken ghosts are invisible

### ISSUE THREAD

**Issue by pali6** [goonstation/goonstation#3292]
[BUG]

**Describe the bug**
Ghosts of chicken have no sprite

**To Reproduce**
1. Become a chicken
2. Die
3. See no ghost

**Expected behavior**
Chicken ghosts should have a sprite.

**Screenshots**

**Additional context**

**Comment by nefarious6th** [comment]
Not exactly a fix; there's a breed of chicken that is a ghost, so here's the sprites for that edited to be the same transparency as the other mob ghosts. I wouldn't exactly know how to add this anyways and what code things might have to be done to implement, but there's sprites now!
![chickenghosts](https://user-images.githubusercontent.com/72267018/118072241-5d233280-b377-11eb-8d38-4ab28e645cf8.png)

**Comment by UrsulaMejor** [comment]
Someone fixed this a while ago, apparently. It might even have been me. Who knows!
