### ISSUE TITLE
PDA Group Messages Not Working

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#33]
**Describe the bug**
When you try to send a pda message to either a DEPT group or a player-made Group chat, no input box appears for you to put in inputs. DMs still work, though.

**To Reproduce**
1. Join as Staff Assistant
2. Open your PDA Messenger App
3. Try to send a message to DEPT-Security, or the "staff" group

**Expected behavior**
Should prompt an inputbox and then send the message when you press "OK"

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ZeWaka** [comment]
Relevant: https://github.com/goonstation/goonstation/blob/a8c29c015fe3e5a09056c8af989f5639c3431ab3/code/obj/item/device/pda2/base_os.dm#L846-L876

**Comment by ZeWaka** [comment]
Here's  the actual relevant areas.

https://github.com/goonstation/goonstation/blob/a8c29c015fe3e5a09056c8af989f5639c3431ab3/code/obj/item/device/pda2/base_os.dm#L200-L204

https://github.com/goonstation/goonstation/blob/a8c29c015fe3e5a09056c8af989f5639c3431ab3/code/obj/item/device/pda2/base_os.dm#L406-L428

**Comment by glassofmilk** [comment]
Fixed in PR: https://github.com/goonstation/goonstation/pull/79
