### ISSUE TITLE
vehicle.dm:601 undefined variable /datum/movement_controller/pod/var/velocity

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#330]
[BUG] [RUNTIME]

**Describe the bug**
Whenever a space pod rams into a person, a runtime occurs:
undefined variable /datum/movement_controller/pod/var/velocity
in file vehicle.dm at line 601
Space pods' movement controller has velocity_x and velocity_y, but not just a general velocity.

**To Reproduce**
1. Ram into a person when driving a space pod.
2. A runtime will occur.
```
proc name: Bump (/obj/machinery/vehicle/Bump)
  source file: vehicle.dm,601
  usr: 0
  src: SyndiPutt-335 (/obj/machinery/vehicle/miniputt/syndiputt)
  src.loc: the shuttle bay plating (86,280,2) (/turf/unsimulated/floor/shuttlebay)
  call stack:
SyndiPutt-335 (/obj/machinery/vehicle/miniputt/syndiputt): Bump(Arthur Baker (/mob/living/carbon/human/normal/assistant), 1)
```
**Expected behavior**
No runtime errors.

**Comment by pali6** [comment]
Fixed by d9af1ff. (Please don't use `:` ffs.)
