### ISSUE TITLE
Paint dispensers no longer make "clear" paint

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#3314]
[BUG]

**Describe the bug**
Previously when using paint machines, opening up the selection screen and choosing white would allow you to make a clear paint that essentially worked as paint remover. Now, choosing white just causes... well, white paint, so the clear color is unobtainable

**To Reproduce**
1. Repair paint machine
2. Select white as the color
3. No more undo paint

**Expected behavior**
Clicking an item/mob/turf removes the paint on them

**Additional context**
This isn't really a bug, I assume it's intentional with the new way paint colors work, but it seemed worth reporting since there isn't really an alternative to removing paint?

**Comment by pali6** [comment]
What if I made it so sponges could be used to remove paint?

**Comment by Retrino** [comment]
> What if I made it so sponges could be used to remove paint?

This solution would work perfectly
