### ISSUE TITLE
Player controlled critters get stuck on space tiles randomly

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#3345]
[BUG]

**To Reproduce**
1. Move onto a space tile
2. Randomly stop moving
3. Can't grab or throw yourself to get back, so need to suicide or ask for admin intervention

**Expected behavior**
Consistent behavior on space tiles

**Comment by flappybatpal** [comment]
Tested and this initially happened to me but then stopped and couldn't get it to occur again.
Unfortunately I think this is one that requires deep investigation of space movement code.
