### ISSUE TITLE
Entering a minisub doesn't prevent you from being absorbed by a ling.

### ISSUE THREAD

**Issue by partyaddict** [goonstation/goonstation#3347]
[BUG]

**Describe the bug**
Entering a minisub doesn't prevent you from being absorbed by a ling.

**To Reproduce**
1. Let a ling attempt to absorb you
2. Get into a minisub
3. Panic sets in as you don't see the [KILL] bar stop.

**Expected behavior**
To stop the ling absorbing me.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ZeWaka** [comment]
dist check working properly, i imagine - gotta move a tile?
