### ISSUE TITLE
Antag critter gunbot can't equip headset in ear slot

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#3348]
[BUG]

**Describe the bug**
Gunbots have an ear slot, but it wouldn't let me equip a headset to the ear slot.

**To Reproduce**
Try to put on a headset as gunbot. Won't equip

**Expected behavior**
Headset go on ear

**Additional context**
Tried two different headsets

**Comment by TobleroneSwordfish** [comment]
This is because gunbots actually have a builtin intercom headset occupying that slot. Not really sure why, but they do.
