### ISSUE TITLE
Borgs turned to gold by wish granter artifacts grow a human torso as statue

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#3349]
[BUG]

**Describe the bug**
Self-explanatory

**To Reproduce**
1. Wish to be rich as a borg
2. Turn into a statue
3. Notice that you have a human torso and asscrack in statue form

**Expected behavior**
A golden borg statue, not this monstrosity

**Comment by zjdtmkhzt** [comment]
I believe this has been fixed.
