### ISSUE TITLE
Spy-Thief limp removal

### ISSUE THREAD

**Issue by mrprogamer96** [goonstation/goonstation#3386]
[BUG]

**Describe the bug**
I was a Spy Thief in Cogmap 1 in RP1, I had the regeneration mutation so I stole one of my own light robot limps, when I did so my Sprite and Hud where not updated and I was not able to regenerate the "missing" limp and I was still unable to use that arm 

**To Reproduce**
I do not know

**Expected behavior**
I was expecting to have my arm be gone and for it to regenerate at a later time and for my sprite and HUD to update

**Additional context**
I was a geneticist who had a lot of other mutations, I also had the robotic arms from my traits

**Comment by Carbadox** [comment]
Pretty sure regeneration mutation only encompasses healing brute and burn damage and nothing else

**Comment by zjdtmkhzt** [comment]
No, it makes you regenerate limbs as well.

**Comment by mrprogamer96** [comment]
Regen works with limps, it just takes a long time.

**Comment by amylizzle** [comment]
Can't replicate. Player icon is updated as expected, regen restored the limb eventually. Closing.
