### ISSUE TITLE
Replacing glass on glass tables doesn't cost any glass

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#3392]
[BUG]

**Describe the bug**
When a glass table is shattered (Likely by someone being slammed into it), using any glass sheet on the table doesn't take another sheet away. This leads to as many glass shards as you want for (minus the chance to harm yourself) no cost whatsoever.

**To Reproduce**
1. Create a glass table with a metal and glass sheet.
2. Place the table frame into the world
3. Slam a monkey into the table on harm intent with an aggressive grab (I've found it to smash the table quicker)
4. Fix the glass table with a sheet, notice you didn't lose any. (In the event you do, try a non-reinforced glass sheet. That's the type I used when I encountered this bug. Not sure if reinforced changes the result.

**Expected behavior**
You use a glass sheet to replace the broken one from the table.

**Screenshots**
N/A, not needed and wouldn't help.

**Additional context**
Encountered this while making a silly contraption.

**Comment by Carbadox** [comment]
Tested on a local server, this is no longer the case.
