### ISSUE TITLE
Ghost drones are able to use PDAs

### ISSUE THREAD

**Issue by Akarias** [goonstation/goonstation#3420]
[BUG]

**Describe the bug**
Clever ghost drones can communicate directly with the entire station by using a PDA and the group messaging functionality. This stems from the ability to update the PDA UI by "Using the item held in your current hand" either by clicking on the magtractor sprite or using your hotkey etc.

Putting this issue up specifically because of what is stated on the wiki. [https://wiki.ss13.co/Ghostdrone](url)
- Cannot use PDAs or phones.

**To Reproduce**
1. Pickup a PDA with your magtractor .
2. Use the item held in the magtractor either by click the sprite or your hotkey.
3. Click on a UI element of the PDA, it wont update until step 4.
4. Use the item held in the magtractor again to update the PDA UI.
5. Repeat steps 2 through 4 to use a PDA like a normal human. 

**Expected behavior**
Ghost drones can use all PDA functionality like a regular human, including all the bad things...

**Screenshots**
![image](https://user-images.githubusercontent.com/5367361/105400761-4799c980-5c1d-11eb-9ee0-89e71892c1c4.png)

**Additional context**
This isn't the worst thing in the world but someone with malicious intent and knowledge of the current round could do some bad things if they wanted to.

**Comment by alexeric123** [comment]
I've never seen this abused, but I feel like if someone does, they will be gone quick.
