### ISSUE TITLE
Pointing at a mass driver loader will activate it

### ISSUE THREAD

**Issue by Varshie** [goonstation/goonstation#3433]
[BUG]

**Describe the bug**
Pointing as a mass driver loader will activate it. You can do this while you are dead, too.

**To Reproduce**
1. Be alive or dead
2. Point at the mass driver loader
3. It activates as if something was on top of it.

**Expected behavior**
it shouldn't be activating when someone points at it, especially if they are a ghost as it lets them interact with the round in a potentially dangerous way

**Comment by pali6** [comment]
Hahaha.
