### ISSUE TITLE
Wifi components mangle &

### ISSUE THREAD

**Issue by moonlol** [goonstation/goonstation#3438]
[BUG]

**Describe the bug**
When you send a packet through a wifi component with the & symbol which is the default splitter for the individual packet parts it gets a bit mangled
![image](https://user-images.githubusercontent.com/16988779/105552730-4095b880-5cfc-11eb-9bf4-71fa4d56c638.png)
original packet was `address_1=020271b1&message=yeah`
Semicolons seem to work fine in place of &
**To Reproduce**
1. connect a wificomponent to a button
2. setup a wifi component with netid filtering off -> sound synth or use a packet sniffer program
3. send a packet containing &

**Expected behavior**
the & symbol not getting mangled

**Comment by pali6** [comment]
Possibly caused by / related to #3254 ?

**Comment by ZeWaka** [comment]
@BenLubar ?

**Comment by BenLubar** [comment]
are we calling HTML sanitize on the string at some point?
