### ISSUE TITLE
[BUG] Job has multiplied on the preference list

### ISSUE THREAD

**Issue by Reznc** [goonstation/goonstation#3441]
[BUG]
**Describe the bug**
Bartender has managed to clone itself several times on my preferences list.

**To Reproduce**
1. Try to move Bartender to a different position
2. See that it's copied itself, existing in both ranks.

**Expected behavior**
Bartender doesn't exist twice.

**Screenshots**
N/A right now, but will attach them when I can.

**Additional context**

**Comment by zjdtmkhzt** [comment]
Yeah, this is a thing that happens pretty frequently. Not to worry though, it has no influence on what role you get and if you reset your job preferences, it will be gone again.

**Comment by pali6** [comment]
duplicate
