### ISSUE TITLE
Unable to load cloning information onto a data disk

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#3464]
[BUG]

**Describe the bug**
Upon attempting to add my cloning information to a data disk, the "save" buttons are not visible or usable.

**To Reproduce**
1. Scan yourself into the cloner.
2. Insert empty disk without write protection.
3. Be sad that you can't find the save button.
4. See error.

**Expected behavior**
I expected to be able to save my information onto a disk.

**Comment by ThePotato97** [comment]
oops didn't link this closed by #4017
