### ISSUE TITLE
Plasma burn can't go above around 8000 C

### ISSUE THREAD

**Issue by Zonespace27** [goonstation/goonstation#3482]
[BUG]

**Describe the bug**
As of a few days ago, I haven't been able to get a plasma burn hotter than around 8000 C in a burn chamber. I have tried a burn on Cog 1 and Destiny. Several others have reported similar problems.

**To Reproduce**
1. Start up a proper burn in toxins.
2. Take temperature of gas.
3. Wait a minute.
4. Go back to step 2.

**Expected behavior**
The plasma _should_ be heating up to millions of degrees eventually, but caps out at around 8000.

**Screenshots**
Not applicable.

**Additional context**
The TEG and PTL are really inefficient with this bug.

**Comment by nefarious6th** [comment]
Duplicate of #3480. Related to #2808 ?

**Comment by Zonespace27** [comment]
> Duplicate of #3480. Related to #2808 ?

Yep, reported it at the same time as another engineer. I can confirm it's related to #2808.
