### ISSUE TITLE
Chem dispenser amounts doubled on own hosted server.

### ISSUE THREAD

**Issue by Wingboy-code** [goonstation/goonstation#350]
[BUG]

**Describe the bug**
Fresh install of BYOND and latest code pulled for Goonstation following this guide: https://wiki.ss13.co/Hosting_a_server

When using the chem dispensers the amounts are doubled, e.g dispensing 10u will dispense 20u, 20u=40u, 1u=2u etc. The same occurs for removing reagents in the chem dispenser.

Tested on Cog1 and Kondaru and confirmed the same thing happened to another user with a fresh install via discord. Affects Alcohol dispensers as well.

**To Reproduce**
Get a fresh copy of the code, compile and start server.
Use the chem dispensers, the amounts should be doubled than those listed.

**Expected behavior**
Amounts should be as seen and not doubled, impossible to create 5 units for example while this issue exists. 

**Additional context**
Adding reagents via admin works fine, variables on chem dispenser are set correctly from what I can see. I have made no changes to the install.

**Comment by ZeWaka** [comment]
Does this occur on the live server?

**Comment by Wingboy-code** [comment]
Doe's not affect live to my knowledge (was playing with chems last night on the main server).

**Comment by Gerhazo** [comment]
Doesn't affect live, happens on my own local copy as well it seems like, weird.

**Comment by F-OS** [comment]
Does this happen on a new dispenser with absolutely no buttons touched except for a chemical button?

**Comment by Wingboy-code** [comment]
Tests:
Only touched the "Iron" button - dispensed amount is still doubled.
Changed amount before choosing a chemical - dispensed amount is still doubled.

Adding amounts directly from the dispenser as a Borg works correctly.


Also Im gonna slide another possibly relevant issue here since I went to test the above -
Fresh boot of server
Put beaker In dispenser, open dispenser and selected iron.
Dispenser screen shows nothing dispensed.
Close the window and open again and now it is stuck as a white box which closes shortly after a few seconds.
Trying to open the chem dispenser window will just have the white window appear and close.
Only way to fix is to exit client completely and come back in again.

This may be irrelevant to the actual issue and just a bug with BYOND but mentioning it just in case, also worth noting I have experienced this white screen bug on the live servers as well.

**Comment by IHadMyUsernameTaken** [comment]
From what I've tried locally, it seems that the OnClick() proc for the chem dispenser's chui window is called twice when you press any button in this UI, which in turn causes a reagent or reagents to be dispensed twice when you click a button for a reagent or use a button for some reagent group.

The same issue appears to be present with any chui windows buttons, but I haven't found any reason for this behaviour.

**Comment by mordent-goonstation** [comment]
Just stumbled upon this myself while trying to do a new CHUI thing (so it's a CHUI issue rather than a Chem Dispenser-specific issue).

**Comment by mordent-goonstation** [comment]
Unsure as to why right this second, but anecdotally I've found commenting out [this](https://github.com/goonstation/goonstation/blob/48751acff9e8afd644fbb1c25424a7ef036b9a38/code/client.dm#L213) entire `if` block "solves" the problem locally. (Link is to a snapshot of a file at the time of this post, if this file changes you might find it somewhere else.)

I haven't looked into why, but it appears that when this block isn't commented out it results in the `chui.js` file being ran twice on chui windows, which means every event (including clicks on buttons) fires twice.

I'll probably take a closer look at this in the near future, but this should "fix" the problem for people locally for now.
