### ISSUE TITLE
Teleporters on the murderbox are able to be destroyed

### ISSUE THREAD

**Issue by MatheusIsNotAvailable** [goonstation/goonstation#3515]
[BUG]

**Describe the bug**

You can destroy the teleporters on murderbox in VR by using chamaleon bombs

**To Reproduce**

1. Buy 3 or more Chamaleon bombs.
2. Stack them one on top of another.
3. arm one and toss it in.
4. die from the resultant explosion and be unable to come back to the murderbox, I assume this happens because the teleport is destroyed.

**Expected behavior**

the bomb explodes, I die but am still able to come back.

**Additional context**

This also works on the equipment room, before the murderbox

**Comment by Sovexe** [comment]
1c492b73373ccdc0210c8871c1f8fbd35a410600
