### ISSUE TITLE
Borg can lose beakers from modules, causes issues for humans attempting to use them

### ISSUE THREAD

**Issue by Sovexe** [goonstation/goonstation#352]
[BUG]

**Describe the bug**
Borg can lose beakers from modules, causes issues for humans attempting to use them. Chem dispensers don't remove the beakers from hand, don't eject the beaker properly, allow "empty" hands apply chems

**To Reproduce**

1. Borg loses beaker from their module via a bug, human picks up beaker
2.  human puts the beaker in a chem dispenser - it stays in their hand
3. beaker is ejected, a duplicate appears on dispenser
4.  human then picks up the borg beaker with their empty hand - beaker moves from their current hand to new hand
5.  click with "empty hand" - reagents are dispensed

**Expected behavior**
Beaker removed from hand and doesn't create a phantom of itself. Empty hands don't apply chems from a beaker in other hand.

**Screenshots**
Beaker both in hand and in machine at same time
![image](https://user-images.githubusercontent.com/33204415/79821095-d8283e00-835b-11ea-8e5c-2433be23fc68.png)

Beaker ejected from machine and still in hand
![image](https://user-images.githubusercontent.com/33204415/79821118-ec6c3b00-835b-11ea-9f82-377760a18d00.png)

Beaker picked up in left hand as right hand was occupied by phantom beaker. Clicking floor with empty right hand applies beaker contents and drains beaker
![image](https://user-images.githubusercontent.com/33204415/79821167-0dcd2700-835c-11ea-8cd7-4013b39add1b.png)

**Comment by flrsh** [comment]
Upon further testing, it looks like this is a quirk that has to do with borg beakers. Somehow a borg was able to drop their beaker, and Sov picked it up and tried to use it. Borg beakers are supposed to be undroppable (unless you throw them, apparently), and so this happened. Changing major to minor; I'd also appreciate insight as to how the borg was able to drop their beaker in the first place.

**Comment by Tiggersaurus** [comment]
It's less dropping it and more a secondary beaker spawning when you use the chem dispenser the non-standard Borg way - empty hand, click dispenser, highlight beaker, insert beaker. This appearing means that someone can take your "beaker" accidently or on purpose (this happens semi-often to me).

The last time this happened to me someone was able to add chems to the beaker which caused a massive explosion.

**Comment by pali6** [comment]
fixed by 3a935e8
