### ISSUE TITLE
Hairless mutants still have a chance to drop hair when gibbed

### ISSUE THREAD

**Issue by Luxizzle** [goonstation/goonstation#3526]
[BUG]

**Describe the bug**
Mutant races such as lizards still have a chance to drop hair when gibbed.

**To Reproduce**
1. Fart on bible as a lizard
2. See dropped hair

**Expected behavior**
Hairless mutant races shouldn't magically have hair appear when gibbed.

**Comment by Sartorius7** [comment]
Feature imo

**Comment by Superlagg** [comment]
Feature
