### ISSUE TITLE
Windows atmospherics issues

### ISSUE THREAD

**Issue by PrimeNumb** [goonstation/goonstation#3545]
[BUG]

**Describe the bug**
Windows seem to interact with atmos in very strange and unintentional ways. In this instance specifically, a thindow was used to rapidly depressurize a large part of the station.

**To Reproduce**
Dislodge any thindow, I used one near the cogmap1 medbay:
![](https://i.imgur.com/lhuGfCO.png)
Pull it with you to any airlock directly connected to a space turf; I was unable to reproduce this when using an airlock connecting to a catwalk surface. I used the south-west airlock in the cogmap1 escape wing:
![](https://i.imgur.com/oNnzBdi.png)
Open the airlock, keep pulling the thindow and run around for a bit. Observe:
![](https://i.imgur.com/zmp6k6o.png)
For reference, this is the effect opening an airlock has on atmos when you're not dragging a thindow around (for roughly the same duration):
![](https://i.imgur.com/qRc9zJw.png)

**Expected behavior**
Not obliterating atmos.

**Additional context**
Related to https://forum.ss13.co/showthread.php?tid=10637

EDIT: This is not exclusive to thindows. The above can be reproduced using a regular window as well.

**Comment by pali6** [comment]
Could you compare with dragging a non-thin window?

**Comment by pali6** [comment]
Almost certainly caused by the fact that dragging a window (whether thin or not) rebuilds the atmos group. Since the airlock is opened the atmos group gets rebuilt in a way which includes the airlock tile. This atmos group is now touching space which leads to space_fastpath triggering.
