### ISSUE TITLE
Shark on oshan can bite pilot of the car minisub

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#3581]
[BUG]

**Describe the bug**
The shark on oshan can attack and delimb the pilot of the car minisub. Unsure if the normal sub is affected
**To Reproduce**
1. Be in car minisub
2. Find shark
3. Get out of sub to agro the shark
4. Get back in car
5. Lose limb to shark

**Expected behavior**
Shark to attack sub, not the pilot

**Screenshots**

**Additional context**

**Comment by frawhst** [comment]
fixed
