### ISSUE TITLE
Unrobust Canisters and Hot Air

### ISSUE THREAD

**Issue by partyaddict** [goonstation/goonstation#3585]
[BUG]

**Describe the bug**
Observing #2808, it seems like it did a good job on needing to rely less on the RCD. Though a new issue has arisen where canisters have the tendency of bursting. Not even canisters that have like a 200000°C mix in them but regular 20°C canisters (composing of any mix) just like to blow up when it's near hot pipes.

**To Reproduce**
1. Make a hot mix in some pipes (toxins or the engine room will work)
2. Put some canisters near the pipes.
3. ???
4. Burst

**Expected behavior**
For canisters to not burst

**Screenshots**
![image](https://user-images.githubusercontent.com/52793290/106741274-60d64900-6613-11eb-9476-6e1771eaf3df.png)
Obligatory screenshot 

**Additional context**
Pipes are funny, Tagging @Azrun

**Comment by TTerc** [comment]
that wasn't entirely the case that round
the pipe under the reactor statistics computer really likes to burst every time I attempt a pipeburn. So it releases a 50k degree hot gas (that immediately goes down to 10k because of the atmos changes) and emits enough heat for the canisters to burst
I wouldn't call that a bug really

**Comment by Azrun** [comment]
I agree with @TTerc here. Observed behavior should be consistent with pre-#2808, except possibly a little less likely to occur now.  I don't know if we have anything that really cools the contents of the can down when subjected to space, but space is essentially the worst thermal conductor.

Keep the cans away from pipes that can rupture!   I could see this as an argument for adjusting that pipe segment (to not rupture) or rerouting the pipes to better surface the pipe state to the player.
