### ISSUE TITLE
No way to escape "&" or ";" for Mechcomp 

### ISSUE THREAD

**Issue by penny64** [goonstation/goonstation#3590]
[BUG]

**Describe the bug**
You cannot send "&" or ";" in the data fields of packets with MechComp, as they will always be digested into fields.
**To Reproduce**
1. Connect MechComp output to a Powernet component or Wifi 
2. Try to send a packet like "data=command=setmode&light=3"
3. Packet is digested and becomes "data=command=setmode; light=3"

**Expected behavior**
\&, \\, and \; should be escapable characters for this reason, or something similar like "&&" or ";;" to send literals.

**Comment by BenLubar** [comment]
`&` -> `%26`
`\` -> `%5C`
`;` -> `%3B`

**Comment by witheld9** [comment]
> `&` -> `%26`
> `\` -> `%5C`
> `;` -> `%3B`

[Add to wiki]
