### ISSUE TITLE
Bat inhand sprites reversed

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#3598]
When holding a bat and another item, the sprites overlap. Sprites for inhands are flipped, I suppose
![Screenshot (239)](https://user-images.githubusercontent.com/73998720/106877903-efdc7300-669e-11eb-91a9-6f397d3f1b93.png)

**Comment by virvatuli-gh** [comment]
Turns out the L+R inhands are flipped, missing the foreground sprites for both L+R, and the south facing L + north facing R sprites aren't positioned right. Fixed in #3601
