### ISSUE TITLE
Picking up brains bug

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#3599]
[BUG]

**Describe the bug**
Right clicking to pick up a brain that is underneath a body will not pick up the brain, instead pats the body

**To Reproduce**
1. Cut a brain out of a head while on an operating table
2. Right click, under the tab for brain, choose the interact option
3. Pat the body

**Expected behavior**
Not have an interaction with the corpse that is above the brain

**Comment by flappybatpal** [comment]
> pali 01/31/2021
> Known bug, from my testing ages ago it's a byond internal thing that sometimes terminates commands after an apostrophe
> Rightclicking translates to something like pickup Shitty-Bill's-brain but some internal byond thing then makes the command cut off at the apostrophe so you get pickup Shitty-Bill
> Strangely I've been unable to reproduce this in an empty byond project but also have been unable to unreproduce it in gooncode by removing suspicious things that could cause this
