### ISSUE TITLE
Chem dispensers show holy water

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#3605]
Making holy water inside a chem dispenser shows the reagent as holy water. Began happening around the same time as the new UI merge

![Screenshot (237)](https://user-images.githubusercontent.com/73998720/106942307-a5341880-66e9-11eb-9e14-b7d7af86dd8d.png)

**Comment by ZeWaka** [comment]
i fail to see how this is a bug

**Comment by Retrino** [comment]
i was told it was but ¯\_(ツ)_/¯
