### ISSUE TITLE
Aerosol turf effect range is much smaller now

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#3613]
[BUG]

**Describe the bug**
Aerosol now causes turf effects 2 tiles around the initial reaction tile, and it used to affect 4 tiles. Since there were some issues regarding smoke and flamers that were being fixed recently, I think it's unintended

**Screenshots**
![0](https://user-images.githubusercontent.com/62990808/107030895-a03a9c00-67b1-11eb-973a-c4d919c90ec6.png)

**Comment by pali6** [comment]
Yass who is locked out of their github account says "aerosol radius is proportional to aerosol volume". Use more aerosol, this is not a bug.
