### ISSUE TITLE
the mystery of the soulsteel statue and the cargo tug

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#3630]
[BUG]

**Describe the bug**
ok this didnt happen to me specifically but i witnessed it, grody the clown commited self arcplating and turned into a soul steel statue, they died, they posed the statue, got on a cargo tug and then proceeded to drive around, and start collecting stuff by dragging into the cargo tug SOME HOW, they collected tipped over vending machines, bees, animals, people, you name it, this bug report is more or less here so i dont forget it happened. and so we all know about it, it was hella weird

**To Reproduce**
1. commit self arcplate with ssoulsteel, 
2. be dead
3. possess statue after it gets ejected (hopefully it lets ya, its a little iffy)
4. cargotug
5. begin collection (dont know if they did anything else inbetween this and the tug part)

**Expected behavior**
not what i described above

**Additional context**
??????????????????????????????????

**Comment by pali6** [comment]
I'm not sure which part of this is a bug?

**Comment by RSG250** [comment]
the part were they could collect an obscene ammount of things

**Comment by witheld9** [comment]
You wouldn't expect possessed sousteel items to be able to click drag items onto a cart right?

**Comment by RSG250** [comment]
it was the cargo tug, not the cargo cart, there was no cargo cart

**Comment by RSG250** [comment]
grody messaged me a couple days ago and apparently this has been a thing for a long time, as there is a forum thread on the subject (albeit with the floor buffer and soulsteel lockers) on it as aswell https://forum.ss13.co/showthread.php?tid=7958
