### ISSUE TITLE
Shinai bag cannot be taken off normally.

### ISSUE THREAD

**Issue by LadyBirb** [goonstation/goonstation#3644]
[BUG - MINOR]

**Describe the bug**
The shinai bag cannot be taken off by clickdragging it to your hand like other bags, only by swapping it for another backpack or having someone else remove it.

**To Reproduce**
1. put on a shinai bag
2. try to clickdrag it into your hand

**Expected behavior**
the bag should be moved from your back slot to your hand.

**Comment by Carbadox** [comment]
@AwkwardDryad

**Comment by AwkwardDryad** [comment]
i noticed this...it was a bug that popped up around the time click dragging things to self defaulted to an action bar left click

**Comment by AwkwardDryad** [comment]
I'm going to give it a multicontext menu to solve this! i've been needing to anyway. it has intent interactions that i'd like to turn into buttons.

**Comment by AwkwardDryad** [comment]
i'm abandoning development, so this issue is open again

**Comment by Zonespace27** [comment]
Note: can be fixed by dragging the bag's sprite to the ground, just a workaround until a proper fix is made
