### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#365]
[BUG]

**Describe the bug**
Tooltips show in a way they really shouldn't

**To Reproduce**
idk I joined and it worked like this

**Expected behavior**
What normally happens when you hover over items

**Screenshots**
![image](https://user-images.githubusercontent.com/63235460/79902459-d15c0280-8411-11ea-8a15-8e38f286f3f4.png)

**Comment by Tarmunora** [comment]
Could not reproduce @ZeWaka

**Comment by ZeWaka** [comment]
this happens once a year for me. i blame chui or IE being dumb af like always
