### ISSUE TITLE
Meteor shield can last forever.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#3679]
[BUG]

**Describe the bug**
Meteor shields can be turned on forever on the highest power required mode with an odd examine text.

**To Reproduce**
Unknown.

**Expected behavior**
The meteor shield should shut off when it has no power.

**Screenshots**
![image](https://user-images.githubusercontent.com/40079883/107581698-15490f80-6bbe-11eb-9bdf-5efc3d953da9.png)
![image](https://user-images.githubusercontent.com/40079883/107581748-209c3b00-6bbe-11eb-9095-174a6ab23528.png)

**Additional context**
I saw this during a two hour round on RP 2: Sylvester.

**Comment by RSG250** [comment]
simple answer could possibly bee that they are wrenched to wiring to power them. which they can do, and that a new floor was placed underthem after wrenching

**Comment by DimWhat** [comment]
twas not a bug but what RSG said. A mostly obscure mechanic I didn't know.
