### ISSUE TITLE
AI Port-A-Sci is inhibited by conditions on the AI Core's tile.

### ISSUE THREAD

**Issue by Frank-Franks** [goonstation/goonstation#3693]
[BUG]

**Describe the bug**
As an AI if you use the port-a-sci program while your core is sitting on top of an obstacle, it treats wherever you are summoning the port-a-sci to as if it has an obstacle.

**To Reproduce**
1. Be AI, be sitting on a pod, wall, closed locker.
2. summon port-a-sci literally anywhere
3. it no work

**Expected behavior**
Expect port-a-sci to obey conditions at summon site

**Screenshots**

**Additional context**

**Comment by nefarious6th** [comment]
No longer relevant because eb02d6a disallows PDA summoning?
