### ISSUE TITLE
AI cannot use AI Vox in camera/ghost mode

### ISSUE THREAD

**Issue by Kapu1178** [goonstation/goonstation#3696]
[BUG]

**Describe the bug**
AI cannot use the admin-granted AI Vox outside of Mainframe

**To Reproduce**
1. Be in camera mode
2. Turn on VOX
3. Verbs missing

**Expected behavior**
Tyrannical overlord can bark at the insects anywhere any time

**Comment by amylizzle** [comment]
Could not reproduce - looks like it was fixed. 
As core:
![image](https://user-images.githubusercontent.com/3855802/169651723-98011f55-67b0-4cb1-8614-7105494d9af6.png)

As aieye:
![image](https://user-images.githubusercontent.com/3855802/169651740-781b2d63-bba4-4115-8abf-cda2138631dd.png)
