### ISSUE TITLE
Genetics console error

### ISSUE THREAD

**Issue by Luxizzle** [goonstation/goonstation#3705]
[BUG]

**Describe the bug**
Genetics console has a fatal error whenever something enters the scanner

**To Reproduce**
1. Put something in attached scanner
2. See script error

**Expected behavior**
No error

**Screenshots**
![dreamseeker_IESwIGzd3C](https://user-images.githubusercontent.com/14966486/107846924-f4fc9900-6de7-11eb-916b-b75e46376a34.png)

**Additional context**
```
A fatal exception has occurred in the TermOS TGUI subsystem. The current application will be terminated. Please remain calm. Get to the nearest TermOS workstation and send a copy of the following stack trace to: https://github.com/goonstation/goonstation. Thank you for your cooperation. 
 Script error.
   at http://cdn.goonhub.com/tgui/tgui.bundle.js?serverrev=fdf80c37c25c0cd0f8488d4f2eefc7e2371c6dbd:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
State: {"ckey":"luxizzle","interface":"GeneTek","window":{"key":"[0x201eec2]-main","size":null,"fancy":1,"locked":0}}
```

**Comment by mordent-goonstation** [comment]
This is very much likely due to some issue with the bundle at that time. If this can be reproduced still, please feel free to re-open.
