### ISSUE TITLE
Pattern Paint Can slowly turns MiniPutt invisible

### ISSUE THREAD

**Issue by WALPVRGIS** [goonstation/goonstation#3707]
[BUG]

**Describe the bug**
When using a patterned paint can on a MiniPutt (seemed to have no effect on Pods), it becomes very slightly transparent. When the paint is used continuously on the putt (to choose a colour, for example), the transparency seems to increase with each new paint job, until the putt looks like a vague stain on the floor. The pod functions as normal, except now you have a dangerously stealthy vehicle. Not sure if it appears the same way for other players.

**To Reproduce**
1. Acquire a Patterned Paint Can
2. Use paint on MiniPutt more than once
3. Watch as the putt fades away with each new paint job
4. Be sad that your dreams to have a trashy Burberry MiniPutt are not to be

**Expected behavior**
For my pod to not be invisible after testing patterns on it

**Screenshots**
![image](https://user-images.githubusercontent.com/78533030/107857713-ccbe7a00-6e7b-11eb-94de-c801d124fde5.png)
![image](https://user-images.githubusercontent.com/78533030/107857717-d647e200-6e7b-11eb-9a24-d479e9b295c8.png)
![image](https://user-images.githubusercontent.com/78533030/107857724-e9f34880-6e7b-11eb-83c2-e04d5bfeea5b.png)

**Additional context**
Nope

**Comment by MetricDuck** [comment]
![image](https://user-images.githubusercontent.com/86617057/152607135-8ba4b10c-9a7b-4de9-abe5-b2954e42f7d6.png)

Seems to have an affect on pods now: miniputt on the left, pod on the right.
