### ISSUE TITLE
flamethrower.dm:317 Undefined variable /obj/blob_tutorial_walker/var/lastattacked 

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#371]
[RUNTIME]

**Describe the bug**
flamethrower.dm line 317
Undefined variable /obj/blob_tutorial_walker/var/lastattacked

**To Reproduce**
proc name: afterattack (/obj/item/flamethrower/afterattack)
  source file: flamethrower.dm,317
  usr: BLORBY the Blob (/mob/living/intangible/blob_overmind)
  src: the flamethrower (/obj/item/flamethrower/loaded)
  usr.loc: the steel floor (260,10,2) (/turf/simulated/floor)
  src.loc: Pubs McFlamer (/obj/blob_tutorial_walker)
  call stack:
the flamethrower (/obj/item/flamethrower/loaded): afterattack(the steel floor (260,10,2) (/turf/simulated/floor), Pubs McFlamer (/obj/blob_tutorial_walker), 0)
Pubs McFlamer (/obj/blob_tutorial_walker): sprayAt(the steel floor (260,10,2) (/turf/simulated/floor), 8)
Protection from Fire (/datum/tutorialStep/blob/cutscene): SetUp()

**Additional context**
Runtimes in blob tutorial, relating to flamethrower showcase. May or may not cause further issues within the tutorial, a runtime error regardless.

**Comment by ZeWaka** [comment]
@Azrun wants to work on this.

**Comment by Azrun** [comment]
@ZeWaka requesting closure because I don't know how to GitHub
