### ISSUE TITLE
cloning console has evil Syndicate background

### ISSUE THREAD

**Issue by mopcat** [goonstation/goonstation#3715]
[BUG]

**Describe the bug**
cloning consoles for some reason have an EVIL syndicate background from the start of the round, despite being completely unmodified

**To Reproduce**
1. look at cloner console (or build your own)
2. see evil syndicate background

**Expected behavior**
cloner has standard non-evil background when unmodded

**Screenshots**
![image](https://user-images.githubusercontent.com/65687976/107867795-c9ab9580-6e4b-11eb-8580-2458ed2dd801.png)

**Additional context**
dismantling and putting the console back together does not fix this issue

**Comment by nefarious6th** [comment]
Tried this one with building consoles with an admin-spawned cloning board, the spare in Tech storage on Cog2, and re-building the main one. Couldn't replicate in any of those instances.
