### ISSUE TITLE
Batons still swap cells instantly

### ISSUE THREAD

**Issue by MatheusIsNotAvailable** [goonstation/goonstation#3735]
[BUG]

**Describe the bug**
Batons still can swap cells instantly and with no progress bar, unlike all other cell swap weapons
**To Reproduce**
1. Get a baton and a cell from the loadout machine
2. click baton with cell

**Expected behavior**
for the progress bar to appear and for it to not be instant like every other cell swaping weapon

**Comment by Camryn-Buttes** [comment]
I thought the cell-swapping bar was specifically only intended to be for ranged weapons

**Comment by Tarmunora** [comment]
It's a case of small cell code being a bunch of copypaste between guns, batons, and mining tools, and only guns got changed

**Comment by Studenterhue** [comment]
It appears #5599 fixed this issue, because stun batons now correctly have the cell-swapping bar.
