### ISSUE TITLE
Secbots don't cuff people anymore

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#3780]
[BUG]

**Describe the bug**
Title. #3276 says that "Secbots can be set to not cuff people under a certain threat level, instead just stunning them and gloating." But it seems all of them start with this setup on default, which I think isn't intentional...?

**To Reproduce**
1. Be targetted by a secbot
2. It stuns you but doesn't cuff you

**Comment by TTerc** [comment]
@Superlagg

**Comment by Superlagg** [comment]
Heck, I thought I fixed that. Guess not! I'll fix it though
