### ISSUE TITLE
Mechanic's frame segway/sleeper bug

### ISSUE THREAD

**Issue by Anormalcar** [goonstation/goonstation#3788]
**Describe the bug**
This is a bug that is similar to jugglemancy if used with a sleeper, but a living taxi if used with a segway.

**To Reproduce**
1. Scan a segway or sleeper with the "device analyzer"
2. Construct segway or sleeper
3. Deconstruct segway or sleeper, during such you go inside at the same time or as an alternative during which you get someone to go inside of the segway or sleeper
4. Wait for deconstruction to end
5.  You can now pick up the frame with the person inside of the frame

**Expected behavior**
It interrupts the mechanic deconstructing the segway/sleeper

**Additional context**
This bug does allow people to move when it is a segway being used, but if it is a sleeper and they move it... turns them into a giant humanoid parasite that needs internals to survive.

**Comment by nefarious6th** [comment]
@Azrun any idea on the segway half of this? i can't find the decon flags and proc anywhere in vehicle.dm for the segway

**Comment by Azrun** [comment]
> @Azrun any idea on the segway half of this? i can't find the decon flags and decon proc anywhere in vehicle.dm for the segway to then add the ejection proc to

Since it is scanned it starts as deconstruct-able.
https://github.com/goonstation/goonstation/blob/7e9e61813b0835c3895b82d35645adf1c0a6b80d/code/obj/item/tool/electronics.dm#L296

**Comment by Azrun** [comment]
> @Azrun any idea on the segway half of this? i can't find the decon flags and decon proc anywhere in vehicle.dm for the segway to then add the ejection proc to

Thanks for the @, I would not have thought you could deconstruct vehicles. I did a little searching for relevant issues but it seems I failed hard. Cheers @nefarious6th
