### ISSUE TITLE
Dead hen clucks

### ISSUE THREAD

**Issue by SebastianWaterhouse** [goonstation/goonstation#3795]
[BUG]

**Describe the bug**
Dead hen clucks when pet

**To Reproduce**
1. Allow hen to die (possibly only of old age)
2. Pet hen
3. Hen clucks

**Expected behavior**
Hen doesn't cluck

**Screenshots**
![image](https://user-images.githubusercontent.com/5074117/108636169-3674f000-7449-11eb-861a-c8c31b5a8ae7.png)

**Comment by nefarious6th** [comment]
Duplicate of #3620 . Someone let these poor chickens rest!

**Comment by BatElite** [comment]
Duplicate & fixed according to Emily
