### ISSUE TITLE
Runtime in bot_parent.dm, line 341

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#3830]
[BUG]

**Describe the bug**
Runtime in bot_parent.dm, line 341
Exception has occurred: cannot read from list

**To Reproduce**
Not sure, happened while testing on Manta

**Comment by Superlagg** [comment]
Looks like a bot has a path, that path is either not a list or has no entries, and its trying to access an entry in that invalid list to see if it should get frustrated. When did you notice this happen?

**Comment by Carbadox** [comment]
Round start on Manta
