### ISSUE TITLE
Dead mutantrace characters use human rotting overlay

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#3832]
[BUG]

**Describe the bug**
Dead mutantrace characters use human rotting overlay

**Expected behavior**
Either shouldnt be there (EG blob ambassadors) or use the proper one (eg monkeys)

**Comment by Carbadox** [comment]
possibly tied to your work? @Superlagg

**Comment by Superlagg** [comment]
> possibly tied to your work? @Superlagg

Kinda related, but mostly because I havent made any new decomposition overlays for the mutantraces. Its less a bug and more a lack of sprites and/or funky color-handling proccery.
