### ISSUE TITLE
MediBots can walk towards and inject people through cloning pods

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#3842]
[BUG]

**Describe the bug**
MediBots can walk towards and inject people through cloning pods and most likely other containers too.

**To Reproduce**
1. Sit in cloning pod 
2. Watch medibot approach you
3. Watch it inject you with healing stuff 

**Expected behavior**
MediBots shouldnt be able to interact with players inside of things

**Comment by zjdtmkhzt** [comment]
@Superlagg I have also heard people complain that beepsky now finds people in lockers/phase shift, etc...
Probably the same issue?

**Comment by PrimeNumb** [comment]
Fixed as of https://github.com/goonstation/goonstation/pull/3852
