### ISSUE TITLE
'eliminate all other operatives' objective counts ghost drone players as alive

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#3853]
[MINOR]

**Describe the bug**
If a traitor dies and becomes a ghost drone, and that drone survives until the end of the round, you'll fail the 'eliminate all other operatives' objective

**To Reproduce**
1. Be traitor
2. Deviously murder your fellow operatives
3.  One becomes a ghost drone
4.  Fail your objectives
5.  Cry into your pillow

**Expected behavior**
The objective doesn't count ghost drones as 'alive'

**Comment by BatElite** [comment]
Don't know what happened here but ghostdrones shouldn't pass the carbon check in code. My best guess is someone went into cryo?

**Comment by LadyBirb** [comment]
Possibly related: I saw a traitor who became a ghostdrone after dying and still succeeded at the "stay alive until the end" objective. Ghostdrones might count as alive for all objectives, not just this one.

**Comment by Xkeeper0** [comment]
Not sure if this is related to this specific problem, but during a revolution round, a head got a random event antag critter respawn as a fire elemental. Even though the "Targets" list in the game panel's antag window was empty, the round did not end until the fire elemental was gibbed by me.
