### ISSUE TITLE
Unable to change RegEx Replace Component's regex through signals

### ISSUE THREAD

**Issue by nikandros576** [goonstation/goonstation#3862]
[BUG]

**Describe the bug**
Changing a RegEx Replace Component's (RERC) regular expression through it's "set regex" input does not affect the "replace string" input. Instead it uses the default regex or the last regex that was set manually.

**To Reproduce**
 1. Get two Buttons, a RegEx Replace Component(RERC), two Sound Synthesizers, multitool, and wrench
 2. Place down the RERC
 3. Click on the RERC with a multitool, select "Set Pattern", and enter ^[a-z]{5}
 4. Click on the RERC with a multitool, select "Set Replacement", and enter HELLO
 5. Place down a Button to the left of the RERC
 6. Click on it with a multitool, click on "Set Send-Signal", and enter hello world
 7. Connect the Button to the RERC and set it to "replace string"
 8. Place down a Button above the RERC
 9. Click on it with a multitool, click on "Set Send-Signal", and enter [a-z]{5}$
10. Connect the Button to the RERC and set it to "replace regex"
11. To the right of the RERC and the Button with the regex, add a Sound Synthesizer for each
12. Connect the Button and the RERC to their respective Sound Synthesizer
13. Click on the Button with hello world and it should output HELLO world to the synthesizer
14. Click on the Button with the regex, the RERC should show the Button's regex value when looked at
15. Click on the Button with hello world

**Expected behavior**
Expected output is hello HELLO, but instead it outputs HELLO world.

**Code**
checkstr (replace string & signal input) does not use the var "expression" to perform a regex replace
https://github.com/goonstation/goonstation/blob/1cb496648c6b5d02a043ae8da2785b56169565e0/code/WorkInProgress/MechanicMadness.dm#L1293

setregex (signal input) only sets the var "expression"
https://github.com/goonstation/goonstation/blob/1cb496648c6b5d02a043ae8da2785b56169565e0/code/WorkInProgress/MechanicMadness.dm#L1308

Thus I am unable to change the regex through signals.

**Comment by glassofmilk** [comment]
There's some other weird stuff going on in here as well. For example, `setReplacement` and `setRegexReplacement` do the same thing expect the latter method never updates the expression field. The expression field itself isn't used in the `checkstr` method - it looks like it's only used for building the tooltip.

I think that this component should probably be reworked to completely remove the expression field. `expressionpatt`, `expressionrepl`, and `expressionflag` should be tracked separately, and there should be both manual configs and mechcomp inputs to alter the values of each of these fields. It would be cool to be able to set the entire pattern/replacement/flags string at one time, but I have zero clue how to break those apart while not messing up the regex pattern itself.
