### ISSUE TITLE
Broken goon and github links in-browser

### ISSUE THREAD

**Issue by Gremyrivolk** [goonstation/goonstation#3863]
[BUG]

**Describe the bug**
Buttons linking to outside sources are prefaced by %22 and capped with ", breaking the link

**To Reproduce**
1. Click on the "Map", "Wiki" or "Github"

**Expected behavior**
Clicking the button brings up the correct associated page.

**Additional context**
This has been a problem for a while but I couldn't report it because the bug report button had been broken.

**Comment by comradef191** [comment]
Wasn't this fixed a few BYOND patches ago?

Pretty sure you just need to update BYOND.

**Comment by comradef191** [comment]
Wasn't this fixed a few BYOND patches ago?

Pretty sure you just need to update BYOND.

**Comment by ZeWaka** [comment]
@Gremyrivolk yup update your byond
