### ISSUE TITLE
Dream Eggs give no effect

### ISSUE THREAD

**Issue by Gremyrivolk** [goonstation/goonstation#3864]
[BUG]

**Describe the bug**
Eating a dream chicken egg no longer gives the regenerative stasis buff.

**To Reproduce**
1. Raise a dream chicken
2. Eat their egg

**Expected behavior**
Eating a dream egg puts you to sleep and gives you the regenerative stasis buff.

**Additional context**
It may be be specifically tied to eating if you aren't sufficiently hurt, although I have eaten dream eggs previously and that has never been a problem.

**Comment by frawhst** [comment]
Can't reproduce- used dream eggs multiple times in a recent round and had them consistently work each time.

**Comment by Gremyrivolk** [comment]
> Can't reproduce- used dream eggs multiple times in a recent round and had them consistently work each time.

This is a pretty old issue - it was only really a problem during the eating rework, and that has since been reverted.
