### ISSUE TITLE
Clicking on a chicken with feed feeds it twice

### ISSUE THREAD

**Issue by Gremyrivolk** [goonstation/goonstation#3868]
[BUG]

**Describe the bug**
Feeding a chicken directly feeds it twice, once when the progress bar starts and once when it ends

**To Reproduce**
1. Grind food at the feed grinder
2. Feed the feed bag to a chicken by left clicking on it.

**Expected behavior**
Hand-feeding a chicken feeds it once, when the progress bar ends.

**Comment by UrsulaMejor** [comment]
Couldn't replicate. Was probably fixed sometime in the last year by someone else!
