### ISSUE TITLE
browserOutput.dm,293: bad output, runtime on local server

### ISSUE THREAD

**Issue by F-OS** [goonstation/goonstation#388]
[RUNTIME]

**Describe the bug**
Runtime with an unknown cause on local server:

[17:27:23] browserOutput.dm,293: bad output
proc name: icon2base64 (/proc/icon2base64)
  source file: browserOutput.dm,293
  usr: (src)
  src: null
  call stack:
icon2base64(/icon (/icon), "5b2639f41f5c0dd7ec58840d8a917e...")
bicon(the scan white (/obj/item/reagent_containers/pill/cyberpunk))
/datum/reagents (/datum/reagents): handle reactions()
/datum/reagents (/datum/reagents): add reagent("synthflesh", 3, null, 293.15, 0, 0)
the scan white (/obj/item/reagent_containers/pill/cyberpunk): New(the pill bottle (???) (/obj/item/storage/pill_bottle/cyberpunk))
the pill bottle (???) (/obj/item/storage/pill_bottle/cyberpunk): make my stuff()
the pill bottle (???) (/obj/item/storage/pill_bottle/cyberpunk): New(the floor (68,263,2) (/turf/unsimulated/floor/yellow))

**To Reproduce**
Unknown

Byond is fully updated, pulled a few minutes ago, no code edits made to any files or procs even slightly related to browseroutput or ??? pill spawning, everything should be working fine. This is very strange.

**Comment by pali6** [comment]
Unable to reproduce despite creating over 500 ??? pills.
