### ISSUE TITLE
Stickers can be stored inside of a full container by sticking them on

### ISSUE THREAD

**Issue by Lythine** [goonstation/goonstation#3881]
[BUG]

**Describe the bug**
Attaching a sticker to a container such as a backpack will stick it to the container AND put it inside the container. This works even when the container is full of items. This is most noticeable by using artifact analysis forms, as other stickers seem to become invisible inside of the container.

**To Reproduce**
1. Make a container full
2. Click on the container with any sticker

**Screenshots**
![image](https://user-images.githubusercontent.com/60405592/109677274-8178bc80-7b47-11eb-9b27-2c843a1ae286.png)

**Comment by FlameArrow57** [comment]
More than a month, closing since no auto close
