### ISSUE TITLE
Feeding ghosts

### ISSUE THREAD

**Issue by smitherzz6** [goonstation/goonstation#3911]
[BUG]

**Describe the bug**
Can feed the ghosts

**To Reproduce**
1. Have Ectosensor Eye
2. Feed Ghost
3. Happy fed ghost

**Expected behavior**
Not to feed the ghost

**Screenshots**

**Additional context**

**Comment by Carbadox** [comment]
Duplicate of #3916 
Will close this one since the other is more detailed
