### ISSUE TITLE
signing a cluwne contract causes anything in hands to vanish

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#3935]
[BUG]

**Describe the bug**
When being transformed into a cluwne by signing a demonic contract, anything in the cluwned person's hands vanishes.  If they signed it themselves this will certainly result in the pen disappearing, and may result in the contract disappearing without giving the chaplain a new one.

**To Reproduce**
1. get a cluwne contract and a demonic pen
2. hold both in hands
3. sign contract
4. pen and contract vanish

**Expected behavior**
Stuff in hands remains in hands, chaplain doesn't permanently lose a pen/contract.

Edit:  This also occurs with the macho man contract, and I'd guess with the yeti one as well.

**Comment by Camryn-Buttes** [comment]
The yeti contract is single use anyway, so the disappearance shouldn't matter.

But yeah, I'll go ahead and fix these.

Expect a patch later today.
