### ISSUE TITLE
Guardbuddy AI tends to get stuck in stun loops.

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#3943]
[MAJOR]

**Describe the bug**
There's a couple of issues with guardbuddies and related keeping players down indefinitely, which seem to stem from trying to cuff someone who is already cuffed.

One thing that happens is if multiple buddies are chasing you and one manages to cuff  you, that one will move on as expected but the others keep repeatedly start trying to cuff you and firing. The result is basically a permastun.

They also sometimes cancel the cuffing action partway through, keeping you stunned in the process. This one usually resolves itself after a few attempts.

**To Reproduce**
Easiest way I know to show this is in the debris field, but attacking a couple spawned buddies also works:
1. Get into the facility in that has the taser secbuddies roaming around
2. Get spotted and tased
3. See permastun
(4. I'd suggest full healing yourself a couple times to see how individual buddies mess up, it's not all consistent)

**Expected behavior**
They incapacitate you, cuff you if they have ability, then go away (at least as long as you're cuffed)

**Additional context**
My example and experience is with the debris field secbuddies, which make that particular bit practically impossible without stun protection, but I've also just earlier seen a mentorhelp from someone who got permastunned by a regular buddy. The behaviour of any single buddy isn't consistent for this bug, but additional buddies getting stuck is.

**Comment by Xkeeper0** [comment]
I've definitely seen buddies get stuck attempting to stun and cuff people -- they'll sit on top and constantly flash or otherwise attack people.
