### ISSUE TITLE
Dissassembling incubator frames returns an inert "Item" named item that cannot be re-assembled

### ISSUE THREAD

**Issue by Gremyrivolk** [goonstation/goonstation#3947]
[BUG]

**Describe the bug**
Disassembling chicken egg incubators with a wrench returns a nesting box and an unusable item with the incubator frame sprite and the name "Item" that cannot be wrenched, screwed or soldered back on.
**To Reproduce**
1. Hit a egg incubator with a wrench
2. Take the "Item" and try to re-assemble it.

**Expected behavior**
Wrenching an incubator produces a nesting box and a rebuildable incubator frame.

**Comment by zjdtmkhzt** [comment]
Could not reproduce.
