### ISSUE TITLE
Mineral magnet affects tiles outside of magnet area

### ISSUE THREAD

**Issue by vortex1942** [goonstation/goonstation#3953]
[BUG]

**Describe the bug**
The mineral magnet when activated will delete floor tiles and items that are on tiles directly connected to the catwalks

**To Reproduce**
1. Place floor tiles starting from the magnet left corner going south.
2. Turn the magnet on
3. Tiles will vanish with any items on them

**Expected behavior**
The mineral magnet should not affect tiles outside the magnet area 

**Screenshots**

![Goonstation 2 Classic Bombini Legendary Hell 13 2021-03-09 213438](https://user-images.githubusercontent.com/22815407/110458224-a0ff7e80-811f-11eb-8d69-989fdb39070a.png)

[Only the tiles which were not directly connected to the magnet catwalk still remain]

**Additional context**
This deleted my attempt of making 3 mineral magnets :(

**Comment by 112358sam** [comment]
Did some testing. This only impacts tiles directly south of the magnet. Other sides are not impacted. I'll keep looking and see if I can find what is causing the issue.
