### ISSUE TITLE
Computer glow overlay appears over items

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#3975]
[BUG]

**Describe the bug**
In certain instances the new computer glow overlay added in #3956 will appear over items, causing a weird graphical bug.

**To Reproduce**
1. Put ID card in ID computer
2. Take ID card out
3. ID card is under glow overlay

**Screenshots**
![Screenshot_346](https://user-images.githubusercontent.com/71185626/110836494-bd0d3800-8265-11eb-9325-1fc32b86116a.png)

**Comment by witheld9** [comment]
I think this is the expected result of overlays- the original PR actually has this behavior in the screenshot.

**Comment by pali6** [comment]
Settiing `src.screen_image.blend_mode = BLEND_ADD` in the computer glow code might help.
