### ISSUE TITLE
becoming a frog via sheltergrog sometimes completely disables emotes

### ISSUE THREAD

**Issue by mopcat** [goonstation/goonstation#4038]
[BUG]

**Describe the bug**
becoming a frog via sheltergrog and going back to human when it's depleted will sometimes completely prevent you from doing ANY emotes

**To Reproduce**
1. drink sheltergrog
2. become frog
3. wait for sheltergrog to wear off
4. attempt to use emotes

**Expected behavior**
ability to use emotes is retained upon transition from frog to human

**Comment by Carbadox** [comment]
duplicate of #3811
