### ISSUE TITLE
Buckshot projectile plays the gunshot sfx ten times at once, resulting in blown eardrums

### ISSUE THREAD

**Issue by Carbadox** [goonstation/goonstation#4039]
[BUG]

**Describe the bug**
Buckshot projectile plays the gunshot sfx ten times at once, meaning the sound is WAY too loud 

**To Reproduce**
1. Fire a tactical shotgun or riot shotgun with buckshot
2. Hear ridiculously loud noise
3. Tear your headphones off in pain

https://cdn.discordapp.com/attachments/757702893959774348/821335619670245396/Desktop_2021.03.16_-_10.47.52.01_-_Copy.mp4

**Comment by virvatuli-gh** [comment]
This isn't a bug as that's an experimental ammunition that is unobtainable currently ingame, purely for testing purposes. It plays a sound for each projectile in the shell, which is more byond stuff than anything else.
