### ISSUE TITLE
Monkeyize while cuffed (for example as a changeling) leaves you permanently cuffed.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#405]
[MAJOR]

**Describe the bug**
Until recently, removing handcuffs relied on the unequip call, which I've modified here #311 as it caused a bunch of issues: handcuffs can be equipped on some slots like the belt slot and in certain scenarios where handcuffs break(delete) on removal (like silver handcuffs) they'd treat taking them off your belt as uncuffing and delete themselves while you're trying to take them off, leading to a bunch of issues that have been detailed in that PR.
Right now that issue has been fixed, however some parts of the code still linger and treat removing handcuffs as unequipping them, one particular example of which is the bug specified in the issue title.

**To Reproduce**
1. Spawn yourself in as a changeling and cuff yourself.
2. Use lesser form.
3. You'll turn into a monkey, continue being handcuffed: you retain the handcuffed status effect but your mob's .handcuffs is set to null, it becomes impossible to uncuff.

**Expected behavior**
For regular handcuffs, they fall to the floor, for special handcuff types, they delete themselves upon monkeyizing.

**Additional context**
When monkeyizing, ```unequip_all()``` is called on the mob. Handcuffs are within that list.
```unequip_all()``` gathers all the items on the person and then calls ```/mob/living/carbon/human/u_equip(obj/item/W)``` on each one. (line 1932 on human.dm at time of writing). The condition the cuffed handcuffs will fall into are at the ```else if (W == src.handcuffs)```, at time of writing line 2029 of human.dm.
The code there just sets ```src.handcuffs = null``` and then tries to ```update_clothing()```. Afterwards, ```unequip_all()``` continues execution(after calling forementioned ```u_equip()``` and proceeds to drop the items at the mob's feet, which in this case means that the mob's .handcuffs variable is set to null and the handcuffs drop to the floor, however they are still considered as handcuffed in terms of the status effect.

This can be partially fixed by replacing the code in u_equip with a ```src.handcuffs.drop_handcuffs(src)``` call. The handcuffs behave properly in such case, except a mild issue remains in that the remaining code of ```unequip_all()``` continues to try and drop the cuffs on the player's feet. With normal cuffs this means no difference from gameplay-standpoint (but some redundant actions code-wise), whereas with special cuffs that break on removal, it teleports them back on the player's feet after they had ```qdel()``` called on them, which means they've been scheduled for deletion and awkwardly linger there before disappearing a few seconds later after the delete queue catches up.

**Comment by ZeWaka** [comment]
definitely due to my refactor

**Comment by pali6** [comment]
Unable to replicate. Probably got fixed in the meantime.
