### ISSUE TITLE
Miasma coming out of nowhere

### ISSUE THREAD

**Issue by Bierkraan** [goonstation/goonstation#4051]
[BUG]

**Describe the bug**
Miasma spawning out of no where

**To Reproduce**
Don't know

**Expected behavior**
No miasma

**Screenshots**
![Schermafbeelding 2021-03-17 172314](https://user-images.githubusercontent.com/66524545/111501701-7e83eb80-8745-11eb-84f7-3190456823db.png)

**Additional context**
This happend yesterday to where miasma was coming out of the reclaimer whilst there was no body in the reclaimer nor in the pipes

**Comment by ZeWaka** [comment]
no reproduction
