### ISSUE TITLE
health totals sometimes freeze below 100%

### ISSUE THREAD

**Issue by Camryn-Buttes** [goonstation/goonstation#4054]
[BUG]

**Describe the bug**
Occasionally, my total health will get stuck at 92% or 97% or something similar, even though I don't have any tox, burn, brute, or oxy damage.

Health scanners will show no damage, but will show my health total as 92% or whatever.

The health indicator in the top right will also get stuck below full health

**To Reproduce**
I've had a difficult time reproducing it consistently, unfortunately.

**Expected behavior**
Uhhh, not this???

**Screenshots**
None, sadly

**Additional context**
It sucks

**Comment by PrimeNumb** [comment]
Probably caused by changes to max health

**Comment by Camryn-Buttes** [comment]
here's a screenshot of the bug:

https://cdn.discordapp.com/attachments/789221420445859860/823243505223729172/dreamseeker_ChLJMDDzaf.png

**Comment by Camryn-Buttes** [comment]
Hrmmm, it seems that eating food that provides a maximum health buff can end the glitched state

**Comment by ThatFiveGuys** [comment]
Can confirm if its still a thing its a bitch to reproduce, fucked around with changing max health to no success

**Comment by ZeWaka** [comment]
we can reopen if reproducible
