### ISSUE TITLE
Wraith (as Revenant) push abilities do not work on anchored objects

### ISSUE THREAD

**Issue by MrMagolor** [goonstation/goonstation#4065]
[BUG]

**Describe the bug**
When in Revenant form, the Wraith gets a Push ability that lets them push objects around. However, this does not work on objects that are anchored, such as airlocks and girders. This is a bad thing, since if you spent 1000 points to become a revenant you shouldn't be stopped by such simple things as walls and doors.

**To Reproduce**
1. Be wraith
2. Possess body as a revenant
3. Use Push ability on a girder/airlock/etc,
4. The chat says you hurl it away from you but nothing happens

**Expected behavior**
For the Push ability to allow you to throw all obstacles in your path away.

**Additional context**
I've also heard it doesn't work at throwing mobs either but I didn't test that yet.

**Comment by Carbadox** [comment]
Balance isnt really a bug
