### ISSUE TITLE
fluorosulfuric acid balloons don't melt headgear when thrown

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#4075]
[BUG]

**Describe the bug**
Balloons filled with fluorosulfuric acid do not melt the headgear of someone hit by them.

**To Reproduce**
1. Fill a balloon with 10u of fluorosulfuric acid (sufficient to melt headgear in a glass or when poured)
2. Throw at target
3. Target still has hat and mask

**Expected behavior**
Clown melts wizard hat with style.

**Additional context**
If the balloon bursts when filling it your mask/hat melt which may be a bug because I don't recall TOUCH reactions happening in other cases where the balloon bursts.

**Comment by PrimeNumb** [comment]
Might've been changed when pali fixed a few bugs with `throw_impact` about 9 months ago (which also fixed the bug that allowed drinking glasses to apply reagents when smashed). I don't remember if balloons used to apply reactions before this but if that is the case then maybe just add that functionality similar to how it was added to drinking glasses.

See https://github.com/goonstation/goonstation/pull/1242/files
