### ISSUE TITLE
Baby monitor cameras do not show up on rancher's camera network

### ISSUE THREAD

**Issue by Gremyrivolk** [goonstation/goonstation#4083]
[BUG]

**Describe the bug**
None of the cameras labeled to connect to the Rancher's baby monitor (/obj/machinery/camera/ranch) actually show up on the camera selection of said baby monitor (/obj/item/device/camera_viewer/ranch), despite both being on network = ranch. Attempting use a baby monitor TV pulls up a camera selection menu where "Cancel" is the only option.

**To Reproduce**

1. Attempt to use a baby monitor on any in-rotation map that has baby monitor cameras
2. See error

OR

1. Place a baby monitor camera on a test map
2. spawn in as a rancher on that map and use your monitor TV
3. see error

**Expected behavior**
Using a baby monitor screen pulls up an option menu where you can select and view from a ranch network camera.

**Comment by Sovexe** [comment]
they need c_tags

unique c_tags too because the handheld tv they use is garbage and can't handle two of the same

**Comment by geneva-breaker** [comment]
ty for fixing this i was not aware of the c_tag uniqueness thing for the handheld
