### ISSUE TITLE
Glass chicks only grow up into roosters

### ISSUE THREAD

**Issue by MrMagolor** [goonstation/goonstation#4089]
[BUG]

**Describe the bug**
Any glass chick, whether hatched from a glass egg or from another egg hatched by a glass rooster, will always grow up into another rooster.

**To Reproduce**
1. Get a glass egg
2. Hatch the glass egg
3. Get only glass roosters
4. Have the glass roosters hatch other eggs into more glass roosters

**Expected behavior**
For glass chickens to function the same as other chicken species in terms of gender.

**Additional context**
It was like 10 glass roosters - I regret not taking a screenshot of the fact that it was only those. But I might just be superbly unlucky, though I doubt it.

**Comment by ZeWaka** [comment]
you're unlucky.
