### ISSUE TITLE
Stocks Machines Broken

### ISSUE THREAD

**Issue by KamikazeMongoose** [goonstation/goonstation#4090]
[BUG]

**Describe the bug**
I've noticed lately that there aren't very many corporations in the stocks computer really hitting it off, even during long rounds. I actually opened up the events two rounds in a row earlier and noticed that there are no news events populating for any corporation. Without these, the stocks machines are very useless as no shares will ever go beyond 1-5 points up/down from their starting value, even over the course of several hours.

**To Reproduce**
1. Look at stonks computer
2. Click on the events link
3. Refresh a few times in confusion and then get sad

**Expected behavior**
At round start the corporations will have upcoming events, announcements, and PR events. They will continue to populate for each corporation throughout the round.

**Comment by MetricDuck** [comment]
Fixed by #7297
