### ISSUE TITLE
Metal Sheets on glass table produces steel shards

### ISSUE THREAD

**Issue by A4Brogan** [goonstation/goonstation#4108]
[BUG]

Describe the bug
Weird oversight in the glass table produces metal shards instead of scrap

To Reproduce
1.Break the glass table. remove glass shards if desired
2. Use metal sheets on frame
3. Wait for someone to break the steel
4. STEEL SHARDS OW

**Expected behavior**
If I remember correctly, we have a metal equivalent item, in the form of [material] scrap

**Comment by Fluidhelixtw** [comment]
I've also noticed this bug. However, around half the times i try it the steel sheet is converted into a normal glass table and i do not know why. Other times it is as described.
