### ISSUE TITLE
Getting absolutely wasted by thrown objects as a cyborg will kick you to deadchat

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#4123]
[BUG]

**Describe the bug**
If you get killed extremely quickly by thrown objects as an AI shell, you go straight to deadchat. You can still recall to your mainframe, but if you hold off on doing so you can talk to the ghosts. In addition, your HUD will say 100% for all bodily damage. During this time I was still 'in' the shell, but unable to function, in the same way that you can reenter your human corpse and shimmy around.

**To Reproduce**
1. Get smashed in the face by 50 metal sheets from a graviton as an AI shell
2. Die, sort of
3. Talk to ghosts.

**Expected behavior**
A standard 'kicked back to mainframe'.

**Screenshots**
forgot to take any :(

**Additional context**
Round was http://goonhub.com/rounds/105020

**Comment by geneva-breaker** [comment]
wildin

**Comment by Xkeeper0** [comment]
I verified that this happens sometimes, but not what _causes_ it yet.

* This happens to all cyborgs, not just AI shells
* The `part_chest` is destroyed and removed from the mob.
* `stat` is set to `2`, indicating a dead mob.

Normal cyborgs do not "die" in the typical sense; their head part being destroyed or their brain being removed ghosts them, and having the chest unit destroyed also causes them to fall apart.

> SHELL/Zamujasa has been hit by the brick.
> SHELL/Zamujasa's left arm breaks off!
> SHELL/Zamujasa has been hit by the brick.
> SHELL/Zamujasa's chest unit is destroyed!

There was no "...falls apart with no chest unit to hold it together!" message. Additionally, it was impossible for anybody to meaningfully interact with the cyborg -- they could select actions but they would never complete.

It looks like the "falls apart" message happens in `code\mob\living\life\statusupdate.dm`:
```
		if (robot_owner)
			if(!robot_owner.part_chest)
				// this doesn't even make any sense unless you're rayman or some shit

				if (robot_owner.mind && robot_owner.mind.special_role)
					robot_owner.handle_robot_antagonist_status("death", 1) // Mindslave or rogue (Convair880).

				robot_owner.visible_message("<b>[owner]</b> falls apart with no chest to keep it together!")
				logTheThing("combat", robot_owner, null, "was destroyed at [log_loc(robot_owner)].") // Brought in line with carbon mobs (Convair880).
```

I'm not sure what code path causes the death to trigger without destroying the borg, but this seems to be a fairly recent development.
