### ISSUE TITLE
Car stuck in trench on Oshan forever

### ISSUE THREAD

**Issue by JackTrysGames** [goonstation/goonstation#4128]
[BUG]

Car cannot escape Trench on Oshan Laboratory

**To Reproduce**
1. Obtain car through admin shenanigans or hand crafting
2. Drive straight into the trench
3. Wormhole fails because "System not installed in ship!", there are no ramps, cars can't climb ladders
4. Be forced to leave the car in the trench after multiple failed attempts

**Expected behavior**
I expected the wormhole to open so I could escape the trench and survive.

**Additional context**
I was using the Warp-1 engine with an Engineering minisub converted to a car via admin shenanigans. I had 2 crates in the cargo hold.

**Comment by alexeric123** [comment]
Not a bug, you have to find the sea elevator using your trench map on the PDA.
