### ISSUE TITLE
Cigarettes laced with chems that give messages when ingested still give messages about it to cyborgs when worn

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#4137]
[BUG]

**Describe the bug**
After putting on a cigarette that's lit and laced with something like enriched MSG a cyborg will still get the message even though they have no lungs

**To Reproduce**
1. Get a cigarette laced with something suitable
2. Light it
3. Put it into a cyborg dock
4. Make a cyborg wear it
5. Now the cyborg has lungs and can taste things?

**Expected behavior**
Cigarette does not apply any reagents when on a cyborg so things like this don't exist

**Screenshots**

**Additional context**
I got an Enriched MSG cigarette from a pro puffs packet since i wanted to look like a detective cyborg, put it on and bam.

**Comment by geneva-breaker** [comment]
oh man i really like this haha

**Comment by Camryn-Buttes** [comment]
This is a very, very, VERY old bug.

It used to actually transfer some effects of the chems to the borgs too.

This allowed brobots to get high. At the time, I was told this was a feature.

**Comment by frawhst** [comment]
feature
