### ISSUE TITLE
Almost irreversible bug with beakers

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#414]
[BUG]

**Describe the bug**
Everybody knows chemborgs suck. Fortunately ever since chem dispensers have had their new UI, a chemborg can click a dispenser with an empty hand and click the "beaker" slot with a borgbeaker to use the dispenser normally. Unfortunately, upon beaker ejection, a "ghost" beaker is created, which contains no reagents despite the appearance and can get stuck on hands (even when they're removed).

**To Reproduce**
1. Be chemborg
2. Click chem dispenser with empty hand
3. Equip beaker, click "beaker" button
4. Eject beaker after having done your chem stuff
5. See that you have duplicated your beaker: one's in your hand, one's on the dispenser
6. Be a human
7. Pick up beaker
8. The beaker's icon X coordinate will go insane
9. You cannot drop, throw, lose, disarm, pickpocket, sever the beaker
10. Clicking chem dispensers "loads" a beaker into them directly
11. Other interactions seem to work similar-ish to having a beaker itemarm (please research)
12. You are able to get this icky shit on both hands and become completely useless.

**Expected behavior**
This might be fixed by making beakers return in your hand when ejected (like the "return cash" button on vendors), and making the chem dispenser one-person-only, with others being able to open the UI but not observe, making chemborgs get their beaker back immediately when just outside of interaction range, much like phone cords.

**Additional context**
This is a really nasty bug, admins can't fix it without really fucking up your mob

**Comment by moonlol** [comment]
i found returning the beakers to borg inventory removes the ghosts

**Comment by Tiggersaurus** [comment]
> i found returning the beakers to borg inventory removes the ghosts

I found that some of the time this doesn't work, especially if someone grabs your beaker *twitches*

This can happen with any module with a container eg bucket, beaker, that you can place in things like the chem dispenser, I think one of the botany machines does it too?

**Comment by MarkNais** [comment]
If experienced this as well. I've also completely lost a beaker once, without being able to get it back in any way (might be this bug, wasn't paying enough attention).
I've made a habit to quickly "store" the beaker after ejection, or to insert it into a heater.

**Comment by pali6** [comment]
fixed by 3a935e8
