### ISSUE TITLE
Unexpected paper UI error

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#4145]
[BUG]

**Describe the bug**
I am unsure of what the bug is, I am simply dumping the error log here as I was advised to do by the very helpful crash UI.

`Script error.
   at http://cdn.goonhub.com/tgui/tgui.bundle.js?serverrev=3f89a1a7518138af569a7678b49e3ff022b77f07:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)`

**Additional Context**
There is very little additional context. This occurred when I tried to use a pen to write on a paper I had pulled from a bin, with the paper being on a table, and after having tried multiple papers and pens. Occurred ~90 minutes into the round on Goon2/Bombini.

The exact same error (ctrl+f'd to ensure it was the same) occured when I tried to use a marker instead of a pen. Also occurred when attempting to read a blank paper.

Also occurred with the exact same error on Goon1 when I hopped over to test there.

BYOND version is on Stable and is Up To Date.

**Comment by ZeWaka** [comment]
cdn issue with versioning and servers, not currently feasible to fix, likely a ci2 thing when that's finished
