### ISSUE TITLE
Cap's bathroom radio can pick up the bar in kondaru

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#4153]
[BUG]

**Describe the bug**
When you are in the bar in kondaru the bridge intercom for whatever reason can pick you up. And thus you can be heard from the bridge for whatever reason.

**To Reproduce**
1. Hang out in the bar.
2. Speak nonchelantly in the back of the bar.
3. Be heard in the bridge 
4. Maping pls.
**Expected behavior**
Not be picked up by bridge intercom in the bridge

**Screenshots**
![image](https://user-images.githubusercontent.com/40079883/112709416-72a3d200-8e87-11eb-8c8d-2a290bb56415.png)
![image](https://user-images.githubusercontent.com/40079883/112709451-cc0c0100-8e87-11eb-980c-570f0e22da47.png)

**Additional context**
On kondaru in goon 4

**Comment by Kubius** [comment]
Checked the map and the intercom is definitely on the tile of the floor, not the wall. Uncertain what's causing this to malfunction.

**Comment by Xkeeper0** [comment]
This affects both bridge intercoms in this screenshot (the one in the bathroom and the one in the room to the right of it by the databank), to be clear.

**Comment by flappybatpal** [comment]
For whatever reason this no longer occurs.
