### ISSUE TITLE
Cloning pod sprite doesn't update after removing mindslave module

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#4156]
[BUG]

**Describe the bug**
When you remove a mindslave cloning module someone placed on the cloning pod the sprite does not change back to the standard pod icon.

**To Reproduce**
1. Put mindslave cloning module on clonepod
2. Remove mindslave module with screwdriver

**Expected behavior**
Icon would update back to normal

**Comment by Xkeeper0** [comment]
I'm pretty sure this also happens when you attach the module as well, if it's already in "clone prep" mode
