### ISSUE TITLE
Airlocks still work in unpowered station areas

### ISSUE THREAD

**Issue by Kubius** [goonstation/goonstation#416]
[BUG]

**Describe the bug**

Airlocks still open without APC power. Tested locally with these configurations:

- Equipment power manually off, cell charged
- Equipment power auto-off, cell not charged
- Equipment power manually off, cell not charged
- Equipment power auto-off, no cell

Have not tested this on a live game server yet, so can't confirm whether this is exclusively a test-build issue or a more widespread one.

**To Reproduce**

1. Go to an unpowered area, or power down an area.
2. Attempt to open an unpowered door without a crowbar.
3. Succeed.

**Expected behavior**

Doors not opening when they don't have power.

**Additional context**

Gooncode 10f6e030, built through vscode. Bug encountered and tested on Kondaru.

**Comment by rockwithagun** [comment]
Just tested this on live, airlocks still work for configurations 2 and 3.

**Comment by pali6** [comment]
Fixed by d996c7b
