### ISSUE TITLE
Cloning Console does not meaningfully vertically stretch

### ISSUE THREAD

**Issue by mordent-goonstation** [goonstation/goonstation#4181]
**Describe the bug**
Increasing the height of a Cloning Console window does not increase the amount of data visible.

**To Reproduce**
1. Clone scan lots of people
2. Resize the window
3. Note that the area that is vertically scrollable does not expand

**Expected behavior**
Expanding the window size increases the scrollable area.

**Comment by ThatFiveGuys** [comment]
fixed by #9789
