### ISSUE TITLE
Engineer cyborgs have infinite floor tiles

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#4188]
[BUG]

**Describe the bug**
If you use over 500 floor tiles as an engineer module cyborg your floor tiles don't end, they even go negative in fact!

**To Reproduce**
1. Get an engineering moduel
2. Use the 500 tiles on something
3. Put down more
4. You have now created infinite flooring

**Expected behavior**
The number is actually finite

**Screenshots**
![ss13 floor tile bug](https://user-images.githubusercontent.com/53524124/113220301-3f948080-9283-11eb-9c16-2827cbfafba5.JPG)

**Additional context**

**Comment by Calyxman** [comment]
Can confirm, this has happened to me before, also see my bug report on this. #4168

**Comment by frawhst** [comment]
fixed as of #4188
