### ISSUE TITLE
You no longer receive spacebux if you don't complete your crew objectives.

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#4207]
[BUG]

**Describe the bug**
Title. As completing objectives is supposed to give you spacebux bonuses, not determine wheter you receive your spacebux at all, I believe it's unintended

**To Reproduce**
1. Escape on the shuttle alive while not completing your crew objectives
2. Realize you haven't received any spacebux at all

**Comment by pali6** [comment]
This doesn't seem to be the case. I know spacebux isn't awarded for some reason but crew objective completion isn''t it.

**Comment by pali6** [comment]
![image](https://user-images.githubusercontent.com/358431/113504701-0d607880-953a-11eb-9ef9-a60b9548924b.png)
