### ISSUE TITLE
Various traitor objectives not completing/worded poorly

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#4209]
[MINOR]

**Describe the bug**
Testing traitor objectives, both of the ones listed did not complete despite definitely fulfilling the objective requirements.

Steal the horse mask! Did not complete despite having the horse mask in my inventory, may mean to wear it instead? If so should be worded better.

Stay alive until the end! Did not complete despite me being 100% alive when the shuttle landed. May mean be alive offstation? If so should be worded better.

**To Reproduce**
1. Get objectives
2. Complete objectives
3. Objectives not completed, stinky greentexter

**Expected behavior**
Regardless of whether or not you care about objectives, they should at least _work_ for the players that want to attempt them.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/68257280/113479199-a8ceec00-945b-11eb-9392-b23b179072d7.png)

**Comment by MatheusIsNotAvailable** [comment]
Afaik, the item having the bloody prefix or the puke one is what causes it to not count as being stolen despite you having it with you, idk what is up with the escape alive one , I think I have had the opposite happen and get the green text even though I was clearly dead when it landed.

**Comment by Kubius** [comment]
Completion code for item theft objectives:

`	check_completion()
		if(steal_target)
			if(owner.current && owner.current.check_contents_for(steal_target, 1, 1))
				return 1
			else
				return 0
`

Completion code for stay alive objective:

`	check_completion()
		if(!owner.current || isdead(owner.current))
			return 0
		if(isghostcritter(owner.current))
			return 0

		return 1
`

Neither of these seem like they should be breaking at a glance.

**Comment by eX-n0x** [comment]
Gave it a few attempts to try and replicate any completion issues. Didn't have any trouble even with bloody items and the like. Not sure what might have caused whatever to happen but hopefully it's just some off glitch of sorts.
