### ISSUE TITLE
mentor mouse bug

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#4214]
[BUG]

when mousing someone who has their mob deleted in some way, ie getting thrown out of the shuttle/running into the ptl/getting loafed, you will forever be trapped in a small corner of space being simultaneously dead and alive.

1- Hop into a pocket
2- Have the person do one of the mentioned methods
3- Observe that you are now stuck in space, unable to suicide because you are technically already dead

**Comment by frawhst** [comment]
Tried messing with for a little while, and haven't found a fix, but I did get this when walking into the PTL with a mouse in my pocket (said mouse was indeed stuck in a corner of space):
`ADMIN LOG: Tried to transfer mind of mob the admin mouse ([0x3000048], *no client*/admin mouse ) to qdel'd mob the awesome admin mouse ([0x3000042]) God damnit. Un-qdeling the mob and praying (this will probably fuck up).`
