### ISSUE TITLE
General "Not getting spacebux" issue

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#4220]
[BUG]

**Describe the bug**
Sometimes, you don't get any spacebux despite... being in the round?
This issue has been talked about a lot on discord but I couldn't find a github issue relating to it (other than the one attributing it to crew objectives), so here one is.

New(?) development: antags are also affected by this. See Screenshots.

**To Reproduce**
1. Play a round
2. No bux

**Expected behavior**
Get the bux

**Screenshots**
![image](https://user-images.githubusercontent.com/67879783/113538983-7fb07780-9591-11eb-9cd4-58f0a7e1c073.png)
(me not getting bux despite being a nukie)

**Comment by TTerc** [comment]
was fixed in ee4463e88d17cf72358ad0e2ece9b0837f96ad73
