### ISSUE TITLE
Spontaneous intelligence cores don't have players "bound" to them

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#4222]
[BUG]

**Describe the bug**
If you spawn in as a cyborg that has one in their head and get it taken out the brain is no longer registered to you and you will not be able to play even if the brain is put into your first body, or any body for that matter.

**To Reproduce**
1. Latejoin as a cyborg
2. Have your brain taken out 
3. Someone puts the brain into another cyborg body
4. You don't control it

**Expected behavior**
The brain is "bound" to a player when they join just like with normal brains

**Screenshots**

**Additional context**

**Comment by frawhst** [comment]
fixed as of #5967
