### ISSUE TITLE
Jailbird doesn't actually set you to arrest

### ISSUE THREAD

**Issue by ModDownloading** [goonstation/goonstation#4230]
**Describe the bug**
Taking the jailbird trait doesn't seem to make you set to arrest when you join (I've tested it only when joining an ongoing game, not roundstart). In addition, the notes tab seems to be empty.

**To Reproduce**
1. Make a character with Jailbird
2. Join a game in progress
3. Wave your arms around in front of a securitron and see what happens

**Expected behavior**
You are set to arrest when joining and have crimes detailed in your notes.

**Additional context**
The 20% chance for conspiracy theorist to get weird objectives might be broken when not joining roundstart too, but that could just be my terrible luck.

**Comment by Carbadox** [comment]
Could not reproduce
