### ISSUE TITLE
Monkeys can't sing properly

### ISSUE THREAD

**Issue by KamikazeMongoose** [goonstation/goonstation#4234]
[BUG]

**Describe the bug**
Whenever you sing as a monke, you get the italics over your head but you don't get the purple italic text in the chat log. I tried it with both local and general radio and it just shows up like regular text.

**To Reproduce**
1. Try to sing a Nickelback song over General Radio
2. Sadness

**Expected behavior**
Whenever you sing with %, it's supposed to show your text in purple italics in the chat log.

**Comment by pgmzeta** [comment]
Haven't been able to reproduce this - likely fixed between when this was filed and now :)?

**Comment by TobleroneSwordfish** [comment]
yep, seems to be fixed
