### ISSUE TITLE
Mining Field random location: Sleeper Chief Engineer TEG location

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#4238]
[BUG]

**Describe the bug**
Find location on mining map, fly to it. Go through sequences of locked doors. Arrive at final locked door and it just doesn't open sometimes.
Sometimes I click it a lot and it opens, sometimes I click it once and it opens five minutes later.

**To Reproduce**
Go to TEG sleeper agent lore location.
Go through button doors.
Arrive at last button door.
Door does not open.

**Expected behavior**
Door opens when the button is pushed, like it used too.

**Screenshots**
![Sleeper Location](https://user-images.githubusercontent.com/81885952/113786960-2a4aa680-9708-11eb-9040-37fb3bb35ed0.png)
![Broken Door](https://user-images.githubusercontent.com/81885952/113786967-2dde2d80-9708-11eb-97a1-dd18a6b161bb.png)

**Additional context**
Please help i'm stuck!

**Comment by RSG250** [comment]
funny thing is i thing just clicking on the door with an empty hand opens it _somehow_

**Comment by Azrun** [comment]
> funny thing is i thing just clicking on the door with an empty hand opens it _somehow_

Yeah pretty sure I've only magically opened the door.  Seems like the default level of the manifolds cause them to get qdel() based on how the prefab is loaded. 🤷
