### ISSUE TITLE
HoS appearing as taken but there wasn't one on shift

### ISSUE THREAD

**Issue by Arthur-Holiday** [goonstation/goonstation#4248]
[BUG]

**Describe the bug**
HoS appearing as taken despite no HoS spawning and it allowing for a NTSO to join without a HoS
**To Reproduce**
1. Have the game select you as HoS
2. Unready up before you spawn
3. Late join as NTSO, notice Head Of Security appears as a taken Job

**Expected behavior**
For HoS to not appear as taken when there isn't any on shift.
**Additional context**
I haven't tried to reproduce this yet so the method I said might not work at all, but that is what I did. The map was Horizon, I don't know if that changes anything relating. The method might also work on all other roles and make them appear as taken. It also was changeling round.

**Comment by nefarious6th** [comment]
Cryo'd maybe? Cryo without ghosting doesn't free up the spot on selection. Not totally sure how hivemind interactions would work with this, but maybe they got got too?

**Comment by MatheusIsNotAvailable** [comment]
No, I talked with Pali to confirm something weird had happened, something happened I just am not sure how and why it did, if it never happens again we might as well close this report though. Glad it isn't common atleast.

**Comment by MetricDuck** [comment]
If there was a wraith in round it could be related to #7364?

**Comment by ThatFiveGuys** [comment]
Hasnt been replicated in a year, pretty sure that this was a fluke or accidentally fixed
