### ISSUE TITLE
Cyborg/human(?) putting a wire under themselves while on a moving conveyor belt generate a ton of runtimes, cyborgs get stuck indefinitely.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#425]
[MINOR] [RUNTIME]

**Describe the bug**
If a cyborg (also humans I believe) places a wire under themselves while on a moving conveyor belt (tested on Oshan conveyor belts), they get stuck in place forever while generating runtimes.
mob.dm line 243 undefined variable /turf/simulated/floor/plating/random/var/anchored.
To fix, had to manually null their mob's buckled var to null with varedit.
From very brief testing, humans seem to also generate runtimes, but they get automatically unbuckled and aren't stuck forever.

**To Reproduce**
1. Be a cyborg with wiring tool in your module.
2. Stand on a moving conveyor belt.
3. Place wire under yourself.
4. You are now stuck and also generating a lot of runtime errors.

proc name: Move (/mob/Move)
  source file: mob.dm,243
  usr: (src)
  src: Cyborg Psi-88 (/mob/living/silicon/robot)
  src.loc: the steel floor (121,146,1) (/turf/simulated/floor/black/grime)
  call stack:
Cyborg Psi-88 (/mob/living/silicon/robot): Move(the steel floor (120,146,1) (/turf/simulated/floor/black/grime), 8, null)
Cyborg Psi-88 (/mob/living/silicon/robot): Move(the steel floor (120,146,1) (/turf/simulated/floor/black/grime), 8)
Cyborg Psi-88 (/mob/living/silicon/robot): Move(the steel floor (120,146,1) (/turf/simulated/floor/black/grime), 8)

**Expected behavior**
I haven't fiddled with tying people to conveyor belts. I'm not sure how it should work and whether this issue only affects moving conveyor belts or ones standing still as well. That said at the very least it probably shouldn't be generating errors or getting things stuck permanently.

**Comment by ZeWaka** [comment]
I'd love to see this call stack, lol

**Comment by Gerhazo** [comment]
> I'd love to see this call stack, lol

Added! (it's very easy and consistent to reproduce)

**Comment by Azrun** [comment]
Have fix for reported issue.  Borgs ends up in a goofy state as they can't use their omnitool, so going to try and squash that unless that is desired behavior. 😱
