### ISSUE TITLE
Being shoved in a GeneTek Scanner opens the genetics window

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#4272]
[BUG]

**Describe the bug**
Exactly what the title says

**To Reproduce**
1. Get shoved in genetics scanner
2. Window opens

**Expected behavior**
A window is not expected to open when you're shoved in the scanner

**Comment by 112358sam** [comment]
I was under the impression this was a feature since it significantly eases communication between the geneticist and subject about what genes they want and gives the subject something to watch while waiting in the scanner.

**Comment by mordent-goonstation** [comment]
I *think* this was an intended feature. It's not necessarily one I hugely agree with - makes sneakily messing with people's genes much trickier - but I think the benefit (namely: engaging the occupant a little) outweighs it. @ThePotato97 ?

**Comment by ThePotato97** [comment]
@BenLubar

**Comment by BenLubar** [comment]
Yes, this is intended.
