### ISSUE TITLE
Shambler grab vs Shambler

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#4286]
[BUG]

**Describe the bug**
When a shambler grabs a person with a grab, its just a grab. It doesn't upgrade. Your normal grab is an aggressive grab.
When a shambler grabs a shambler that other shambler gets locked in place and can't move. And also has their model dragged onto the other shamblers model. If the other shambler starts to devour, the only possible option to interrupt the grab is a lucky disarm, since the grabbed shambler cannot move to interrupt.

**To Reproduce**
Shambling Abomination against another ling.
Grab them.
They now can't move as if they were instantly pinned to the ground.
Hard to shove with gigantic shambler model overlaying itself over other gigantic shambler model.

**Expected behavior**
I get grabbed, I don't get instantly pinned to that spot and can move away to break devour. I can now continue fighting as normal, uselessly punching the other shambler in the face till he runs out of DNA.

**Screenshots**

**Additional context**
First damn time I've ever seen it happen. Other ling called it a "Feature" and not a bug. Heres the report anyways.

Edit edit edit.

**Comment by Carbadox** [comment]
Pretty sure this is a feature,
