### ISSUE TITLE
[BUG]Actions severely delayed

### ISSUE THREAD

**Issue by remles1337** [goonstation/goonstation#4296]
[BUG]

**Describe the bug**
When trying to interact with another player that is moving the actions either dont happen at all or happen much later same with opening a text box or looc box to write something, boxes show up all at once or dissapear immediatly,

**To Reproduce**
1. be on harm or grab intent
2. click on a player when both are moving
3. nothing happens till later when it all happens at once or not at all

**Expected behavior**
to hit them or grab them or be able to use a text box as intended.

**Screenshots**

**Additional context**
happened multiple times, other players didnt have the same issues.

**Comment by swinglow20** [comment]
Skill issue

**Comment by NightmareChamillian** [comment]
this is called lag.

**Comment by flappybatpal** [comment]
Please don't post skill issue even as a joke, thanks.
