### ISSUE TITLE
Robuddies cannot be built with tool modules

### ISSUE THREAD

**Issue by pitaden** [goonstation/goonstation#4315]
[BUG]

**Description**
When trying to build a robuddy, it is impossible to add a tool module. After building a robuddy, it does nothing when it spots a criminal or gets attacked. If a newly built robuddy is attached to a dock, using `prman list` at a dwaine terminal will display the buddy as having the "GUN" module, despite having no gun or module attached.

**Steps to reproduce:**
1. Add a power cell to a robuddy frame
2. Click the frame with a tool module. You should normally be able to add a module at this step, but instead you'll hit the frame.
3. The same will happen at any other step of the building process

**Expected behavior**
After adding a power cell and before adding a mainboard, it should require you to add a tool module before continuing construction

**Screenshots**
![bonk](https://user-images.githubusercontent.com/32023715/114569384-8b0f3d00-9c3a-11eb-87e6-0ec925d0925f.png)

**Additional context**
This happens with both PR-4 and PR-6 frames.

**Comment by virvatuli-gh** [comment]
This is because the process for building buddies has changed with some of the recent PRs. The tool module is added last, after you add the arm and finalize the buddy. Not a bug, just a different process now.
