### ISSUE TITLE
Cannot transport people on rolling beds anymore

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#4373]
[BUG]

**Describe the bug**
The very act of trying to use medbay's rolling beds in their intended role is broken. When buckling someone to the bed, as soon as you try to move the bed it auto-unbuckles them. This happens regardless of whether or not you've tucked them in or if they've laid down themselves.

**To Reproduce**
1. Your patient has a tummy ache and can't get to the shuttle themselves
2. Solution: buckle them to the bed and wheel them to the shuttle yourself!
3. As soon as you try this, the bed unceremoniously dumps them onto the floor
4. Damn Nanotrasen for shipping the patented Quick-Eject Bed System to medbay by mistake

**Expected behavior**
The rolling bed to work like a rolling bed, buckling the patient into the bed should also transport them on the bed when you pull it.

**Additional context**
This is broken at least back to February of this year. This does not occur with wheelchairs, they are functioning properly.

**Comment by TTerc** [comment]
found the guilty fcfe8e4425e442c29a8956d63cfc4af3829de28a
but not sure how to fix it without breaking a thing that this commit fixed
