### ISSUE TITLE
Unicode Cuneiform does not display in the text above head

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#4397]
[BUG]

**Describe the bug**
This bug prevents unicode cuneiform from appearing above a characters head, and often is glitched in chat EX: 𒀼𒐼 𒄑𒍝 becomes Ð¼𒐼 𒄑𒍝 and || || above the head

**To Reproduce**
1. Go to Speak
2. Enter Sumerian Cuneiform
3. See glitch

**Expected behavior**
It should be expected that Cuneiform works like all other unicode symbols in game

**Screenshots**

**Additional context**

**Comment by pali6** [comment]
BYOND issue. Can't fix.
