### ISSUE TITLE
You get wanted for public pissing in botany

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#4403]
[BUG]

This is a very annoying issue when you want to create a lot of saltpetre, and even if the botany is completely empty, the cams automatically set you wanted for "public urination". This makes every securitron get on your ass which can be quite frustrating for a botanist who can't do too much about securitrons.

**Comment by mordent-goonstation** [comment]
Use a bathroom like a human? Cut the cameras temporarily?
