### ISSUE TITLE
Securitron Oversight

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#4409]
[BUG]

**Describe the bug**
Hey, although most people probably know, but I figured i'd put it in writing so it doesn't get sideburnered again. Currently Securitron's use Metal Cuffs which take an average of roughly 50 seconds to undo and you can't interact or get pushed, etc. What they're "suppose" to use is zip ties from what I'm hearing from everybody on the discord, so this is just to make something tangible to look back on so it gets fixed. Nukies will cry tears of joy when this gets changed.

**To Reproduce**
1. Do a real and/or not real crime and have securitrons decide that you can't live any longer. 
2. Get hit once or twice with batons and get stunned for 20 seconds. 
3. Get cuffed by metal cuffs and cry cause you know it's gonna take a minimum of a minute and 30 seconds to get uncuffed, if everything goes right with stun+rough 50s timer.

**Expected behavior**
Repeat steps 1 & 2.
3. Get cuffed by zip ties and get annoyed at beepsky and sigh, wait for your stun to wear off and wait the 15 seconds instead of the minute it takes for metal cuffs.

**Comment by penny64** [comment]
Was the securitron a "tool" like Beepsky?

**Comment by Kubius** [comment]
Fixing this.
