### ISSUE TITLE
Cat ears attached to radio headsets don't show up on sprites

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#4446]
[BUG]

**Describe the bug**
Cat ears attached to radio headsets do not show up on the character sprites

**To Reproduce**
1. Buy cat ears
2. Attach to headset
3. Wear

**Expected behavior**
To be Very Cute

**Additional context**
Maybe it's a layering problem with the hair? Normal cat ears do show up just fine when they're in the head slot.

**Comment by Tarmunora** [comment]
Layering issue for sure

**Comment by nefarious6th** [comment]
😔

**Comment by LadyBirb** [comment]
I could still see a couple pixels sticking out when I did this so yeah it's just being layered under hair.

**Comment by nefarious6th** [comment]
Fixed by a15bd51
