### ISSUE TITLE
torpedo clone bug

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#4452]
the torpedo console on manta will cause you to be permanently stuck if you cancel camera view on it. 

1- enter the view where you can aim where to fire the torpedo
2- use the cancel camera view verb
3- you are now stuck

the way to get out of this is to be dragged into a crate and pulled away. normal attempts to pull and grab you seem to not work. after being out in a crate, there will be a clone that will stay until someone else uses the console. 

seemingly the only way out of this if alone is to be drunk, the stagger chance will free you

**Comment by imnotjames** [comment]
Related to #1588 ?

**Comment by flappybatpal** [comment]
Not really an issue. You just have to press Q or E to exit.
