### ISSUE TITLE
AIs are unable to adjust intercoms

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#4478]
[BUG][MAJOR]

**Describe the bug**
AIs appear to be wholly unable to adjust any intercoms, including internal ones, seemingly regardless of whether or not they are in camera view mode. Their configurations may be viewed as normal, but inputs do not have an effect.

**To Reproduce**
1. Play as an AI
2. Access the UI of any of your internal radios or any intercom. Being in your mainframe or in your AI eye will not really matter.
3. Attempt to interact with any UI element (excluding the close-window button)
4. It will not actually adjust any settings. Notably, you will see that the eye is Orange regardless of distance or if you have recalled to your mainframe. If you are recalled, the UI will be greyed out. This applies equally to both internal radios and intercoms.

**Expected behavior**
The AI is to, as normal, be able to interact with the UI of any intercom, internal or not, at any range under really any circumstances, rather than never being able to adjust their settings at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/28785926/116009480-f4eaf780-a5e7-11eb-8ddd-da786ade8aeb.png)
^ What appears when you open an intercom's UI

![image](https://user-images.githubusercontent.com/28785926/116009491-0df3a880-a5e8-11eb-97fd-81c9928f4d45.png)
^ While you can still interact with the UI elements as shown above, it will not have an effect and will immediately revert back to normal. In this case, it'd revert back to the appearance of the first image once I stop attempting to adjust the frequency.

![image](https://user-images.githubusercontent.com/28785926/116009525-39769300-a5e8-11eb-93d4-47f9da92b3cd.png)
^ This was taken while camera view was cancelled. While greyed out, you can still interact with UI elements, but again they will not have an effect. 

**Additional context**
This was discovered solely as a Latejoin AI, and as such this may have been the cause of this bug if it has not yet been noted.

The MAJOR tag was added as this completely stops the ability to access radios, which stops AIs from intercom snooping, disabling primary radio to talk to people in person, etc.

**Comment by Luxizzle** [comment]
Big oopsie, probably because intercoms are items.
