### ISSUE TITLE
AIs are unable to track people from their names on the radio

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#4479]
[BUG]

**Describe the bug**
AIs appear entirely unable to track people from clicking on their names on the radio. They can still be tracked from the Track list, but not otherwise.

**To Reproduce**
1. Play as an AI
2. Click on anyone's name on the radio.
3. Nothing happens

**Expected behavior**
The AI is to, as normal, be able to track people by clicking on their names, or at least be told that the person is not on the cameras if they can't be tracked.

**Screenshots**
![image](https://user-images.githubusercontent.com/28785926/116009609-a12cde00-a5e8-11eb-8e14-5566cf1f128b.png)
^ The text that appears on the bottom of the window (where the name of whatever your mouse is hovering over shows) when I hovered my mouse over someone's name 

![image](https://user-images.githubusercontent.com/28785926/116009644-e5b87980-a5e8-11eb-9cad-10da5190121f.png)
^ Ditto, but someone else

**Additional context**
This was discovered solely as a Latejoin AI, and as such this may have been the cause of this bug if it has not yet been noted.

I am tempted to add the MAJOR tag but as a workaround in the form of the Track list exists, I'm gonna not add that unless I'm told that I probably should.

**Comment by frawhst** [comment]
Experienced the radio name thing as a roundstart AI as well yesterday. Not limited to latejoins.
