### ISSUE TITLE
nukies flamethrower damage bug

### ISSUE THREAD

**Issue by rando212** [goonstation/goonstation#4486]
**Describe the bug**
the vega flamethrower does extra damage when it hits a target plus the fire damage this extra damage goes through fire resit and can hit the nukie himself even though he has 100% fire resist

**To Reproduce**
1. take vega flamethrower with 100% fire resist suit
2.run forwards and shoot in the same direction hoping for the fire to lag behind and hit yourself
3. see massive fire damage occur on the nukie even through 100% fire resist is on

**Expected behavior**
for the extra damage to be blocked by fire resist the same way fire damage does

**Screenshots**

**Additional context**

**Comment by Studenterhue** [comment]
Possibly a side effect of bfe8939 ,

**Comment by TobleroneSwordfish** [comment]
Going to say this is fixed as I can't reproduce it
