### ISSUE TITLE
Blind wizard

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#4503]
[BUG]

**Describe the bug**
taking the blind trait and getting selected to be the wizard deletes your VISOR

**To Reproduce**
1. take blind trait
2. get selected for wizard
3. VISOR go poof

**Expected behavior**
VISOR doesnt deleted

**Additional context**
id rather not have to deal with the stress of hoping either medbay or qm is kind enough to let me print a visor before they decide to assault me.

**Comment by flappybatpal** [comment]
Does not occur for me on local testing with a blind wizard.

**Comment by imnotjames** [comment]
I was pretty sure it had happened when I had tested it last but locally I cannot get it to happen again.

**Comment by MetricDuck** [comment]
Bug is still open, can be reproduced by either:
- Spawning as a wizard via the random antagonist event
- Respawning with Soulguard (per flappybatpal's comments on the PR)

I was unable to test late-join wizard.

**Comment by MetricDuck** [comment]
Closing because dupe
