### ISSUE TITLE
Term OS error

### ISSUE THREAD

**Issue by nicROJ** [goonstation/goonstation#4506]
Script error.
   at http://cdn.goonhub.com/tgui/tgui.bundle.js?serverrev=c4e167175093ced75c6281ce390214c9e0adc8ec:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"ownerex","interface":"CharacterPreferences","window":{"key":"[0x2102323a]-main","size":null,"fancy":1,"locked":0}}

**Comment by FlameArrow57** [comment]
Idk if anything can be interpreted from this
