### ISSUE TITLE
drain the blood syringe style

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#4507]
[BUG]

**Describe the bug**
when drawing from a corpse using a syringe it doesnt stop after 3 times like it should leading to drawing way more than you should

**To Reproduce**
1. get a corpse and syringe
2. draw mode
3. click corpse like theres no tommorrow

**Expected behavior**
auto stop at after the 3rd time and switch to inject like it used too

**Additional context**
maybe causing runtimes?

**Comment by 112358sam** [comment]
Tested on local and everything seems to be working correctly. Spam click draws three times and then just says syringe is full. Has this been fixed?

**Comment by Carbadox** [comment]
couldnt recreate
