### ISSUE TITLE
Energy barrier tennis

### ISSUE THREAD

**Issue by trerri** [goonstation/goonstation#451]
[BUG]

**Describe the bug**
Sec barrier special attack can bounce energy projectiles indefinitely

**To Reproduce**
See screenshot

**Expected behavior**
The server doesn't die

**Screenshots**
![image](https://user-images.githubusercontent.com/63235460/80340412-e0531280-8860-11ea-9c61-1358dd71d80f.png)

**Additional context**
fix this shit

**Comment by ZeWaka** [comment]
Needs hp or limiter

**Comment by Tarmunora** [comment]
Fixed by #891 @ZeWaka
