### ISSUE TITLE
The Faustian Bargaining Kit has some issues.

### ISSUE THREAD

**Issue by ErwinSnowden** [goonstation/goonstation#452]
[BUG]

**Describe the bug**
From what I can tell in the code, the Faustian bargaining kit has code that doesn't execute properly in terms of what it's supposed to do, an example of this is yeti's not retaining the signer's mind and instead ghosting them when it's clearly supposed to as there is a designed Faustian yeti GUI alert for when it's signed. Not only this but the damage reversal contract seems to work as intended but the actual mutation given doesn't do anything with newer combat code, probably because of neglect from reworks when it should be one of the most powerful contracts. On top of this, code involving narcolepsy doesn't trigger with monkeys well, as such the well-rested contract no longer affects them in the ways of yore. 

**To Reproduce**
1. Use a contract of yeti on someone with a mind, they will be given no control over it
2. use a contract of reversal on someone, have them get shot with a shotgun (with slugs or buckshot), they will die or at least take damage.
3. use a well-rested contract on a monkey and they will sleep for about 2 seconds and then get up for another 8 intermittently, if you don't know how, hold contract in hand and pen in the other and force sign them.

**Expected behavior**
I expect the contracts to work, they don't, as such individuals hate me for lying to them and ends up with me getting grudged over a genuine misconception.

**Screenshots**
I don't have any as it's a rather rare pick and traitor chaplains aren't seen very often.

**Additional context**
The Faustian bargaining kit could use a real rework as the weapons in their current state are either too overpowered and lacking in ability or not costly enough to the traitor as a whole, there are unused infernal abilities that could be unlocked by higher-end bargainers who amass enough souls, furthermore the eldritch tome is almost never seen because of its appalling 3% chance to happen and I get why it's rare but it could use a serious change. Usually people don't even combo the faustian bargaining kit with anything so it costing more for more potent abilities later on would be more satisfactory and give more of a reason to not just give away access for powers knowing that a taser and stunbaton can easily dunk them even with their OP melee.

**Comment by Carbadox** [comment]
I believe Camryn Buttes resolved this some time ago
