### ISSUE TITLE
Can't put Fish from wholetuna cordata in the chicken feeder

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#4528]
[BUG]

White Silkies need to eat fish in order to grow into something else, but the fish Botanists can do does not even fit in the feed machine! Very disappointing.

**Comment by Gremyrivolk** [comment]
You have to slice the fish with a knife to get their filets first.

**Comment by vocalpocal** [comment]
why can't they just eat the whole fish, without fish cleaning?

**Comment by nefarious6th** [comment]
I assume chicken feed grinders can grind anything with food pathing (/obj/item/reagent_containers/food/snacks/ingredient).
Wholetuna cordata harvests into fish, which is just /obj/item/fish/random and not specifically pathed as an edible food item. Sugarcane does this too.

**Comment by ThatFiveGuys** [comment]
Fixed with them now accepting any object
