### ISSUE TITLE
You can't put someone into cryogenic storage if they have no arms

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#4531]
[BUG]

**Describe the bug**
lol. You can't put someone in cryo storage if they don't have arms. It gives the error that you can't put them in if they're restrained. Not having arms and being grabbed technically is restrained. The person also can't cryo themselves because, again, no arms.

**To Reproduce**
1. Lose arms
2. Attempt to cryo
3. Attempt to get put in cryo by someone else
4. :(

**Expected behavior**
Either they can cryo themselves or someone else could shove them in cryo

**Comment by frawhst** [comment]
I fixed this ages ago
