### ISSUE TITLE
Health Analyzer no longer changes sprite based on upgrades

### ISSUE THREAD

**Issue by N0no** [goonstation/goonstation#4539]
[BUG]

**Describe the bug**
The health analyzer stays on it's default unupgraded sprite even when upgrades are enabled

**To Reproduce**
1. Get an upgraded health analyzer
2. See that the sprite doesnt change

**Expected behavior**
Health analyzer sprite changes colour based on upgrades

**Screenshots**

**Additional context**

**Comment by nefarious6th** [comment]
Potentially fixed by #4573 
Not able to replicate on the newest version of master, so it was fixed somewhere along the line.

**Comment by TTerc** [comment]
yeah, it was recently fixed, as Nef said
