### ISSUE TITLE
custom eyebrows sit above glasses

### ISSUE THREAD

**Issue by TDHooligan** [goonstation/goonstation#4540]
[BUG]

**Describe the bug**
custom eyebrows from the player customiser sit above glasses such as the Spectroscopic goggles

**To Reproduce**
1. use custom eyebrows in the character setup
2. wear glasses

**Expected behavior**
eyebrows sit below glasses

**Screenshots**
![image](https://user-images.githubusercontent.com/6061314/116766915-f0c63c00-aa24-11eb-8968-109ae6a8c73e.png)

**Comment by DimWhat** [comment]
This also applies to lizards as their head detail overlaps any eyewear.

**Comment by DimWhat** [comment]
Fixed with commit 1374708
