### ISSUE TITLE
Using a syndicate clown mask on someone already wearing a mask deletes the clown mask

### ISSUE THREAD

**Issue by Camryn-Buttes** [goonstation/goonstation#4549]
[BUG]

**Describe the bug**
The title should be self evident

**To Reproduce**
1. Buy a syndicate clown mask
2. Use it on someone with a mask
3. cry

**Expected behavior**
Either the mask to not work or for it to dislodge the other mask they were already wearing.

**Comment by imnotjames** [comment]
Given it's a syndicate item, I think forcing it on and forcing them to drop their current mask makes sense.
