### ISSUE TITLE
Credits in Crates Not Counted

### ISSUE THREAD

**Issue by Ronovo** [goonstation/goonstation#455]
[BUG]

When you put credits into a create, and ship them out of cargo, it does not count. For example, if you put in your starting cash, like 500 credits, and send it off, it will only register as 10 credits. 

**To Reproduce**
1. Start As QM
2. Put starting credits into crate
3. Ship crate through outgoing
4. Generic "10 Credits" message appears

**Expected behavior**
Credits should be counted to ship's budget

**Comment by ZeWaka** [comment]
probably not checking money.amount or whatever it is properly
