### ISSUE TITLE
Headspider assumed control of new host immediately and changeling player kept control of the body after headspider was removed

### ISSUE THREAD

**Issue by jan-antilles** [goonstation/goonstation#4551]
[BUG]

**Describe the bug**
A changeling (Nathan White) was killed, and it released a headspider, which latched onto the nearest crewmember, Fleur DeLaCreme. Nathan took over Fleur's body immediately, but a few other crewmembers saw it and screamed for surgery. Despite some confusion and yelling Fleur was rushed to surgery, and the headspider was successfully removed, which ejected everyone in Nathan's hivemind... including Fleur. Leaving Nathan alone in Fleur's body. Nathan had control over Fleur for the rest of the round while Fleur and the other former hivemind watched as ghosts.

**Expected behavior**
The headspider takes a bit of time to assume control, and if it is removed, the original owner of the body gets to keep it.

**To Reproduce**
1. Be a changeling with enough DNA to headspider
2. Get deservedly slain
3. Release a headspider and go for the person who slayed you
4. Immediately have control
5. Have said person rushed into surgery and have the headspider cut out
6. You still have the body, instead of the body's original owner

**Additional context**
The round where this occurred:
https://goonhub.com/rounds/107414

**Comment by ZeWaka** [comment]
see #5054

**Comment by amylizzle** [comment]
I couldn't reproduce this, but it sounds like it might be intermittent?
