### ISSUE TITLE
Securitrons still see through cloaking

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#4552]
[BUG]

**Describe the bug**
I spawned in as a Hunter and had fun going around scaring people until a legion of securitrons saw through my cloak and slapped me silly. This is not supposed to happen as per #3961 

**To Reproduce**
1. Be cloaked antagonist
2. Securitrons cannot stand cloaked antagonists
3. Feel the wrath of the baton for merely standing there cloaked

**Expected behavior**
For the PR that supposedly fixed this to work

**Comment by MatheusIsNotAvailable** [comment]
You sure they weren't beepskies? Beepsky can still see trough cloaking, I remember testing it and it working fine, guessing something broke it somehow

**Comment by virvatuli-gh** [comment]
They were securitrons, yes. Possible reason maybe: they detected my spear in my hand as contraband and that negated my cloaking? Dunno just a shot in the dark

**Comment by virvatuli-gh** [comment]
Unable to reproduce my own bug 😫
