### ISSUE TITLE
glowy man cant into shirt properly

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#4556]
[BUG]

**Describe the bug**
glowy main sprite, screen facing arm is layered under cloths (assistant jump suit for example) and doesnt go thru shirt arm hole,

**To Reproduce**
1. be glowy man
2. shirt
3. notice how arm is behind back when facing to the sides

**Expected behavior**
arm go thru arm hole

**Comment by nefarious6th** [comment]
Flashy mutantrace? Icon state is "psyche" in the dmi
