### ISSUE TITLE
barrer handheld artifact and SPEED 

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#4568]
[BUG]

**Describe the bug**
Barrier handheld artifact ignores its cooldown if you hit something in your inventory with it, so spam click an item in your pocket with it to see the effect

**To Reproduce**
as above

**Expected behavior**
not that, unknown if it affects others

**Additional context**
fun fact: opening a storage container, like back pack, has no cooldown

**Comment by zjdtmkhzt** [comment]
I believe I fixed this in #5330 .
