### ISSUE TITLE
Guardbuddies are unable to use shotguns

### ISSUE THREAD

**Issue by COOLVAPE** [goonstation/goonstation#4587]
[BUG]

**Describe the bug**
Guardbuddies are unable to use the shotgun - they cannot rack the slide.

**To Reproduce**
1. give guardbuddy a shotgun
2. they can't rack the slide, and fire like you would expect.
**Expected behavior**
if guardbuddies can accept a shotgun, they should be able to use it successfully.

**Comment by Carbadox** [comment]
This issue has been resolved
