### ISSUE TITLE
Nukeops Infil kit (possibly) contains wrong chameleon projector

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#4591]
[BUG]

**Describe the bug**
There are two chameleon projectors in the game.  One is a gimmicky traitor item that lets you scan certain objects and then impersonate them while moving very slowly, while the other is an item (either sold by C.A.R.L. or found in surplus crates, I forget which) that gives you a random, illusory identity when used.  The nukeops infiltrator crate contains the first one, which I expect is not the intended one.

**To Reproduce**
1. Go into murderbox
2. Buy infiltrator crate
3. Open and check contents

**Expected behavior**
I would expect the infiltrator to get an item that actually helps in infiltrating instead of a silly gimmick item.

**Additional context**
It could be intentional, I suppose.

**Comment by alexeric123** [comment]
The first thing you mentioned is the chameleon projector, the second is the holographic disguiser. The cloaking device gives invisibility outside of thermals

**Comment by Camryn-Buttes** [comment]
Not a bug.

Chameleon projector is, in general, significantly more useful than the holographic disguiser

**Comment by Cthucky** [comment]
I could have sworn that I had read that it was supposed to be the holographic disguiser but going back through the changelogs reveals that it's clearly not so I'm completely wrong here.  Closed the issue.
