### ISSUE TITLE
Labeling cyborgs removes their names

### ISSUE THREAD

**Issue by KamikazeMongoose** [goonstation/goonstation#4592]
[BUG]

**What is the bug?**
It can take a long time to get someone to rename your cyborg to something you asked for and it takes seconds to slap a label on the cyborg and revert it to a default cyborg name (cyborg mu-1234 etc). Even after getting the label removed, you still keep the defaulted name and have to bug someone to rename you again.

**To Reproduce**
1. Label a cyborg (that doesn't have the default generated name)

**Expected behavior**
It should just be the chosen cyborg's name plus the label.

**Comment by penny64** [comment]
I've been wanting to adjust the labler to use name instead of real_name, let me look into it

**Comment by BatElite** [comment]
Is there a (technical) reason not to make the cyborg renaming thing update real_name?

(or let borgs self-rename for that matter)

**Comment by penny64** [comment]
> Is there a (technical) reason not to make the cyborg renaming thing update real_name?
> 
> (or let borgs self-rename for that matter)

I misunderstood the problem it was like inside of atom.dm , and it always used initial(src.name)

I fixed everything in a PR
