### ISSUE TITLE
Putting ghost hair onto cyborgs damages, stuns and does other things that it shouldn't do to cyborgs

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#4617]
[BUG]

**Describe the bug**
If you put ghost hair that you sometimes get from busting ghosts and decide to put it on a cyborg they will emote, get damaged, get stunned and a couple other things

**To Reproduce**
1. Get ghost hair
2. Put hair on cyborg
3. The cyborg is in pain

**Expected behavior**
 This shouldn't be a thing and also ghost hair without this would be amazing because it looks goofy af on cyborgs

**Screenshots**

**Additional context**

**Comment by Sartorius7** [comment]
It's due to the material properties of the hair. Like fibrilith, ectofiber has the "itchy" property and affects the wearer.
