### ISSUE TITLE
hitting an atm with a pda that has your id in it

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#462]
[BUG]

**Describe the bug**
hitting an atm with a pda that has your id in it no longer scans your id, at least when trying so from the left and right side
**To Reproduce**
1. hit atm with pda that has id card in it
2. id not scanned
3. see error.

**Expected behavior**
i expect it to scan the card.

**Comment by Gerhazo** [comment]
Did it definitely use to actually scan before or is this moreso a missing feature?

**Comment by RSG250** [comment]
yes, it did
