### ISSUE TITLE
Purchasing Security Assistant gear should probably not leave you with 0.1 tokens left

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#4626]
[BUG]

**Describe the bug**
When buying SA gear at the vendors, you're still left with 0.1 of a token. Huh.

**To Reproduce**
1. Be a part-time VO or a SecAss.
2. Buy gear from the vendor with your token.
3. See error.

**Expected behavior**
I expected my token to be _**eated.**_

**Screenshots**
![image](https://user-images.githubusercontent.com/66253095/117529253-efdf6c80-b019-11eb-91a9-e5cbe7492ec1.png)

**Comment by penny64** [comment]
This is intentional and hilarious

**Comment by Tarmunora** [comment]
foxed
