### ISSUE TITLE
Kudzu people are being given the bandage overlay

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#4658]
[BUG]

**Describe the bug**
As per the title, when Kudzu people emerge from a bulb, they're given a fully bandaged overlay. Silly and weird, but can't possibly be intentional.

![image](https://user-images.githubusercontent.com/68257280/117642752-ab58eb80-b155-11eb-8a5f-1c7718212e8a.png)

![image](https://user-images.githubusercontent.com/68257280/117643105-0ab6fb80-b156-11eb-9895-726786279520.png)

**Comment by Carbadox** [comment]
This issue is no longer the case
