### ISSUE TITLE
Silicons can be itemgrabbed

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#4673]
[BUG]

**Describe the bug**
You are able to circumvent the inability to grab silicons by using items that have contextual grabs. Such as wires, cloth, garrotes, guns and possibly more.

**To Reproduce**
1. Pick up an item able grab people, such as wire.
2. Click on a borg with grab intent
3. Grab the borg
4. This shouldn't be possible

**Expected behavior**
Being unable to grab the borg like how you normally can't.

**Screenshots**
None available. I made this from a phone.

**Additional context**
Silicons are only able to escape these grabs by pressing Z. They have no ability to resist besides the Z button.

**Comment by Awfullyfishy** [comment]
I personally think it's nice being able to carry a damaged Cyborg or move them around with wires, but it should be easier for them to escape. Medical Cyborgs can at least defib you to immediately release your grab.

**Comment by imnotjames** [comment]
I think setting `canbegrabbed` to 0 for cyborgs will solve this.
