### ISSUE TITLE
murderbox test dummy button prints to everyone, not just presser

### ISSUE THREAD

**Issue by nnystyxx** [goonstation/goonstation#468]
[BUG]

**Describe the bug**
When a player presses the test dummy button in the murderbox, everyone else in the 'box gets the message "Creatin dummy for you, you dummy", not just the player that pressed it.

**To Reproduce**
1. hang out in the murderbox with someone else
2. have them press the button
3. wow whoa you got the message too

**Expected behavior**
The button should only give the message to the person who pressed it, not the observers too. Or at least address all of them and not just the one guy as a compromise.

Maybe it could be 'you dummies', which works because now you've got at least two dummies in the murderbox, the test dummy and the dummy that pressed it.

**Comment by moonlol** [comment]
ah sorry i was coping code from cleaner button and im usually the only person in murderbox
