### ISSUE TITLE
Storage can be used to bypass unequp procs

### ISSUE THREAD

**Issue by imnotjames** [goonstation/goonstation#4681]
[BUG]

**Describe the bug**

If you hit an item with a toolbox or backpack, that thing will enter the backpack. 

It does not follow many of the hooks, so this can be used to remove unremovable items such as the cluwne shoes.

**To Reproduce**
1. Get Cluwne Shoes
2. Wear Cluwne Shoes & feel like an idiot
3. Hit cluwne shoes with backpack in hand
4. Cluwne shoes in backpack!

**Expected behavior**
You are cursed to forever wear those shoes

**Comment by Tarmunora** [comment]
fixed
