### ISSUE TITLE
Floorbots continuously put water on floor on Oshan

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#4686]
[BUG]

**Describe the bug**
FloorBots. On Oshan Lab, they continually just put Water on the Floor, and never mop it back up.
Results in a completely flooded area almost every time.

might occur on manta as well, not tested. happens almost every match, no hull breaches either.

**To Reproduce**
1. Map be Oshan
2. watch floorbot
3. oh no flood

**Expected behavior**
no flood

**Comment by 112358sam** [comment]
Has this been addressed? I cannot replicate it on local. If there are no holes in the floor, the floorbot just sits idle and if there are, it fills them in and stops the flooding. Outside of emagging the floorbot, it never seems to cause floods.

**Comment by ZeWaka** [comment]
iirc fixed
