### ISSUE TITLE
Cyborg Typewriter Sprite Disappears Permanently

### ISSUE THREAD

**Issue by COOLVAPE** [goonstation/goonstation#4687]
[BUG]

**Describe the bug**
The cyborg typewriter sprite will suddenly disappear after use. (I believe it happened after i saved something i had written.)
**To Reproduce**
1. Use the typewriter
2. write something
3. save it 
4. typewriter sprite disappears permanently

**Expected behavior**
the typewriter sprite would remain visible

**Screenshots**

**Additional context**
its just a blank space on the item slot and in your equipped item bar

**Comment by nefarious6th** [comment]
Fixed by 91b4049?

**Comment by COOLVAPE** [comment]
yes, this is fixed now

**Comment by COOLVAPE** [comment]
fixed by https://github.com/goonstation/goonstation/commit/91b404982892bc167f9211ae1cfc0e1568740d6c
