### ISSUE TITLE
emagged floorbots cannot be hit by melee attacks

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#4701]
[BUG]

**Describe the bug**
You cannot hit emagged floorbots with melee attacks, not even with ground targeting.  Ranged attacks work fine.

**To Reproduce**
1. Emag a floorbot
2. Attempt to break with melee weapon of choice

**Expected behavior**
The annoying thing removing the floors should respond to percussive maintenance.

**Comment by Tarmunora** [comment]
9d57a2d
