### ISSUE TITLE
3D Photos

### ISSUE THREAD

**Issue by Likteer** [goonstation/goonstation#4724]
[BUG]

**Describe the bug**
3D photos when using a camera on a large object.

**To Reproduce**
1. Find something big like a pod
2. Take a picture
3. (Optional) Drop it for better view

**Expected behavior**
A photo of just the tile I was aiming for, or a photo showing the downscaled-enough pod..

**Screenshots**
![obraz](https://user-images.githubusercontent.com/68878861/118304750-5e736d00-b4e7-11eb-8343-478b9cb85497.png)

**Comment by ThatFiveGuys** [comment]
Fixed
