### ISSUE TITLE
micro/macrobombs do not activate on ling absorption

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#4741]
[BUG]

**Describe the bug**
Being killed via ling absorption does not activate any microbombs or macrobombs.

**To Reproduce**
1. Implant yourself with bomb of choice.
2. Get eaten by ling.
3. Where's the kaboom?
4. There was supposed to be an earth-shattering kaboom.

**Expected behavior**
I expect an explosion immediately followed by raucous laughter in deadchat and a very confused ling.

**Additional context**
This could have been an intentional change, but I don't recall ever seeing it in a changelog and I feel like it would have been big enough to warrant one.

**Comment by Zonespace27** [comment]
Unable to recreate this, as seen [here](https://imgur.com/a/bNiVZ2i).
The branch I recorded that on is up-to-date as of 4 hours ago

**Comment by imnotjames** [comment]
Did you try the `suicide` but couldn't at some point before that?

**Comment by Tarmunora** [comment]
could not reproduce
