### ISSUE TITLE
Unkillable/Soul Shield does not copy traits

### ISSUE THREAD

**Issue by imnotjames** [goonstation/goonstation#4752]
[BUG]

**Describe the bug**

When you die and the `unkillable_respawn` proc is called, your traits don't copy over but bio-effects and abilities copy over.

**To Reproduce**

1. Take `Athletic` trait
2. Become a Wizard and take the Soul Shield spell
3. Throw yourself into the crusher
4. You're no longer a baseball wizard?!

**Expected behavior**

Unkillable keeps the traits you've picked

**Comment by Tarmunora** [comment]
72e5459
