### ISSUE TITLE
Health implants not displaying correct health

### ISSUE THREAD

**Issue by ThePooba** [goonstation/goonstation#4753]
[BUG]

**Describe the bug**
I expect the health implant to tell me how damaged i am

**To Reproduce**
1. Have health implant
2. get damaged
3. see that you have full health
4. notice you are walking slow, scan self,
5. 60 brute damage and the health implant dont care

**Expected behavior**
Knowing when you are dying

**Screenshots**
![healthbug](https://user-images.githubusercontent.com/81843097/118383238-42d89700-b5b9-11eb-89cd-354c3df341d5.png)

**Comment by Tarmunora** [comment]
dcd37b0
