### ISSUE TITLE
Sechud icons are lost on reconnecting or leaving mob and re-entering.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#4769]
**Describe the bug**
If you reconnect, or otherwise re-enter your mob, i.e. as an admin through set-observe and set-play (while giving it a second to remove the overlays), the images in your client are gone and you won't see sechud icons (for example contraband) anymore until you take off your sechud glasses and put them on again.

For reference, this doesn't occur with the medical prodoc goggles.

**To Reproduce**
1. Put on sechud near a perp with an icon.
2. Reconnect or set-observe and set-play to re-enter your body (wait a second for the overlay to be removed).
3. The icons are gone until you remove and put the sechud on again.

**Expected behavior**
Being able to still see the icons, like with the prodoc goggles.

**Additional context**
Prodoc goggles work fine, so it might have to do with discrepancies between how they handle the overlay images.
The sechud sunglasses' screen tint is still present, even though the icons are gone.

pali recommends use of COMSIG_CLIENT_LOGIN and COMSIG_CLIENT_LOGOUT signals to handle it. If prodocs use some hacky workaround instead of that, maybe it'd be good to port them over too, but that can probably be resolved separately.

**Comment by Gerhazo** [comment]
notice: is being worked on

**Comment by Carbadox** [comment]
Should be resolved with this #4789

**Comment by Gerhazo** [comment]
> Should be resolved with this #4789

Re-opening for the moment, #4789 adds the framework for handling adding icons to clients, but #5359 is the actual implementation/overhaul using it for sechuds and prodocs, which I'll link to this issue.
