### ISSUE TITLE
Miasma smoke is generated from a corpse in a body bag.

### ISSUE THREAD

**Issue by Kyle2143** [goonstation/goonstation#477]
[BUG]

**Describe the bug**
Miasma smoke is generated from a corpse in a body bag.
**To Reproduce**
1. Kill someone.
2. Place corpse in body bag.
3. Wait until it starts to rot and produce miasma.
4. See that miasma is spreads.
**Expected behavior**
I'd assume that the body bag would either delay a body from rotting so that it wouldn't spread miasma, or at least contain the miasma until it's opened.

**Additional context**

**Comment by Gerhazo** [comment]
I think this happens with bodies in any container, even if within another human (through being eaten after being deep fried, the body lingers around inside the person until it starts to decompose and the living human starts generating miasma).
