### ISSUE TITLE
Cannot see chat box

### ISSUE THREAD

**Issue by Randomidk** [goonstation/goonstation#4771]
[BUG]

**Describe the bug**
I can't see the chatbox on goonstation, it says "Loading... if this takes longer than 30 seconds" text, and never actually loads,
the character setup is also broken, it gives me a TermOS error, and a white screen when i reopen it,
i can play the game and still see my own text in-game but i don't think i can see other's text.

**To Reproduce**

- Step 1: i dont know how

**Expected behavior**
The chatbox to appear and the character menu to work

**Screenshots**
[https://i.imgur.com/TNvBZ7x.png](url)

**Additional context**
I have a similar issue on other servers

**Comment by imnotjames** [comment]
This sounds like a local issue with your computer.  Perhaps an antivirus or some other tool that's blocking it?

**Comment by Randomidk** [comment]
> This sounds like a local issue with your computer. Perhaps an antivirus or some other tool that's blocking it?

I don't have any antivirus installed, also it worked fine before on my laptop, i still use windows 7 on my pc though, might it be because of that

**Comment by Pockets-byte** [comment]
I'm having this issue as well on wine, aka on IE 7
