### ISSUE TITLE
wrestlemap is missing a list of cameras on 'show camera list' for the AI

### ISSUE THREAD

**Issue by COOLVAPE** [goonstation/goonstation#4788]
[BUG]

**Describe the bug**
When you click 'Show Camera List' as AI on wrestlemap, it doesn't show a list of cameras.

**To Reproduce**
1. click show camera list on wrestlemap
2. see that it just shows 'cancel'
**Expected behavior**
A list of named areas for cameras should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/77637753/118760617-1d5dbe80-b841-11eb-8a4b-f5740fe5c4c9.png)

**Additional context**
You can still see through cameras as per normal, but there's no list of cameras on the list.

**Comment by Carbadox** [comment]
General dev response is that they're not gonna support out of rotation maps
