### ISSUE TITLE
Synthmeat infusions not working/don't affect chance of planting specific mutations

### ISSUE THREAD

**Issue by freshoob** [goonstation/goonstation#4800]
[BUG]

**Describe the bug**
The recent addition of new Synthorgans as Synthmeat mutations should be allowing for infusions to increase the chance of getting certain mutations, but this appears to not work properly. I've repeatedly tested infusing simethicone for Synthbutts and compost for Synthappendixes but the resulting plants don't appear to differ from what would be expected from the normal mutation chance upon planting.

**To Reproduce**
1. Infuse a Synthmeat seed with one of the allowed infusions (compost for Synthappendix is an easy one).
2. Plant seed.

**Expected behavior**
The infused seed should at the very least be more likely to have the mutation corresponding to what was infused (even if it's still not guaranteed each time). But over multiple attempts, this appears to have no affect on the chances of getting that infusion's corresponding mutation. If it IS affecting the chance, it is so low that the infusions are borderline-useless.

**Comment by flappybatpal** [comment]
Typical chances are 10-20%, these new variations are 4-10% so they are pretty low.

**Comment by freshoob** [comment]
@flappybatpal is each infusion a roll of the chance to mutate percent for each variant? So with Synthappendix being at 6% in the code, should each infusion of compost have a 6% chance for the seed to become a Synthappendix plant?

I just infused 4 Synthmeat seeds with compost, 15-20 times each to the max damage before they'd be destroyed, and none of them became a Synthappendix upon planting. This was with earlier infusing 30 Synthmeat seeds each one time with compost, and getting one Synthappendix from planting them all.

I'm not getting any better chances of getting a particular variation by infusion above just planting un-infused Synthmeat seeds over and over and rolling the 4-10% chance until I get the one I want. If I've just been unlucky and each infusion has that 4-10% chance as I wrote at the top of this comment (meaning you should infuse a single seed over and over to raise the chance), you still only get 15-20 chances to infuse a single seed, so as a system of helping to get particular variants, the infusions aren't really useful since you can just plant seeds over and over instead.

Also of concern is if even if the infusions are working, the seeds could be rolling the Synthmeat mutation chance at the moment they are planted still, so the infusions do nothing since the resulting plant is rolled from the entire table of possible Synthmeat mutations.

**Comment by avimour** [comment]
This was fixed when #9890 was fixed!
