### ISSUE TITLE
permanent pocket card deck

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#4804]
[bug - minor]

**Describe the bug**
If you take a deck of cards and put it in your pocket, you are unable to remove it from your pocket again and clicking with an open hand just brings up the context menu for interacting with the deck again. Using the "pick up" command on the context menu does not work.

**To Reproduce**
1. Buy a pack of cards and make them into a deck
2. Need to buy more cards, so store the deck in your pocket to make more room to buy more cards
3. Get enough cards and try to remove the deck from your pocket
4. Keep bringing up the context menu every time you try to click on the cards with an open hand
5. Try using the "pick up" command on the context menu to no avail

**Expected behavior**
I expected that I'd be able to remove my 60 Space Credit Spacemen the Grifening Pre-made Deck from my pocket and also have my pocket open again to shove haggis into.

**Additional context**
Clickdragging from my pocket into my hand also doesn't work.

**Comment by nefarious6th** [comment]
Duplicate of #5001

**Comment by flappybatpal** [comment]
Fixed by the Pick Up action in #5050
