### ISSUE TITLE
Character is pitch black

### ISSUE THREAD

**Issue by lolJamesR** [goonstation/goonstation#4812]
[BUG]

**Describe the bug**
This bug has happened once to me, basically when you join, your character is like PITCH black, hair, skin, eyes, so on, clothes are not affected

**To Reproduce**
1. join game
2. character might be pitch black

**Expected behavior**
to join the game and have my character to look how i made it to look

**Screenshots**
![image](https://user-images.githubusercontent.com/79608599/119164572-7b162480-ba54-11eb-9899-1b2a354e69c5.png)

**Additional context**

**Comment by blackrep** [comment]
Any chance you had the mildly mutated trait picked? This looks like it might just be the `Melanin Stimulator` body mutation.
![image](https://user-images.githubusercontent.com/84296283/119764956-510f9880-be80-11eb-8ea0-c786fa72a10e.png)
