### ISSUE TITLE
THE AMAZING FLYING REED ORGAN

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#4814]
[BUG]

**Describe the bug**
telekinetic pull can fling around the reed organ, additionally reed organ can go over tables for some reason

**To Reproduce**
1. get telekinetic
2. unsecure the reed organ
3. click drag like crazy

**Expected behavior**
should fling it around considering how much damage it does with its size

**Additional context**
my sides are in orbit

**Comment by BatElite** [comment]
Should be resolved by #4817
