### ISSUE TITLE
Railing in impossible position on Cogmap

### ISSUE THREAD

**Issue by Trobador** [goonstation/goonstation#4816]
[BUG]

**Describe the bug**
In the ranch on Cogmap, one railing is placed in such a way that makes it impossible to replace in the same position if you decide to move it. It shares the same tile as the feed grinder which cannot be moved.

This screenshot shows the situation I accidentally created when trying to move the grinder. The railing was initially on the same tile as the grinder and oriented in the opposite direction. I cannot move the railing back to its original position.

![image](https://user-images.githubusercontent.com/35611827/119187049-14573200-ba79-11eb-9c91-753d19087fea.png)

**To Reproduce**
1. Unscrew the railing
2. Pull the railing away from the feed grinder tile
3. The railing can no longer be placed on the tile 

**Expected behavior**
I expected there to be ways to rotate the railing, move it on the grinder's tile or to move the grinder itself like most machines. I'm unsure if this is the right place for this report since it's less of a bug and more of a feature gap.

While I'm at it, one problem I had with the Ranch is that on some maps, the grinder is out of reach from inside the chicken coop, which is annoying when laying down feed. This is why I wanted to move it in the first place before noticing it wasn't even necessary on Cog.

**Comment by Carbadox** [comment]
You can deconstruct railings and make new ones in whatever direction you want by just facing in said direction
