### ISSUE TITLE
New from botany: Fractional crop harvesting

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#4822]
[minor]

**Describe the bug**
I somehow managed to harvest half a crop. None of the actual objects harvested seemed to have anything wrong with them, though. I never did find that half tomato.

**To Reproduce**
1. Harvest plant
2. Get half crop?

**Expected behavior**
Whole Crops Only

**Screenshots**
![image](https://user-images.githubusercontent.com/67879783/119226392-ac770a80-babd-11eb-9e0e-8719e60e40d7.png)

**Additional context**
I was like 12 splices deep at this point. Might have something to do with it.

**Comment by Tarmunora** [comment]
wat

**Comment by Tarmunora** [comment]
60d31bc

**Comment by millicentjwi** [comment]
this happens when your plant has the Stunted Yield gene, and the amount of produce rounds down (iirc?), thought it really should say 6 instead of 6.5

**Comment by frawhst** [comment]
> this happens when your plant has the Stunted Yield gene, and the amount of produce rounds down (iirc?), thought it really should say 6 instead of 6.5

Ah, the plant did have stunted yield! Thanks, I was wondering how this happened.
