### ISSUE TITLE
Floorbots can steal tiles from you

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#4823]
[minor]

**Describe the bug**
If you pick up a tile that a floorbot was going after, the bot will 

**To Reproduce**
1. Get some floor tiles and a crowbar (for ease).
2. Quick-replace a normal tile near a floorbot and wait for the bot to target the floor tile left on the ground.
3. Pick up the floor tile with your stack.
4. The floorbot will now chase after you and if you let it, steal the stack of tiles out of your hand.

**Expected behavior**
For the bot to give up when you pick up the tile.

**Comment by penny64** [comment]
Please please keep this

**Comment by DisturbHerb** [comment]
Pleeeease keep this.

**Comment by TTerc** [comment]
it's not the bot stealing the floortiles from you, it's you stealing from them!
the poor floorbot just wants their stuff back

**Comment by PrimeNumb** [comment]
Would be cool if this behavior was made intentional and cleaned up a bit (so the bot doesn't chase after you forever).

**Comment by Yellow-Mushroom** [comment]
I love this sm

**Comment by BatElite** [comment]
If we're making it intentional, consider having them shout angrily at you

**Comment by ThatFiveGuys** [comment]
Now a feature tm
