### ISSUE TITLE
Trying to place Orion pistol case in stealth storage breaks pistol and contents of case

### ISSUE THREAD

**Issue by scrcr0** [goonstation/goonstation#4835]
[BUG]

**Describe the bug**
Trying to put an Orion pistol into a stealth storage box seems to break the pistol (removes the 10 rounds it comes pre-loaded with and stops it from firing). Putting the box the Orion comes into that same storage box also deleted all the contents. The stealth storage box then disappeared. 

**To Reproduce**
1. Spend traitor points on the suppressed pistol.
2. Spend traitor points on the stealth storage.
3. Take pistol out of case and put in pocket. 
4. Try (accidentally or not) to put the case into the stealth storage.

**Expected behavior**
Either the pistol case goes into the stealth storage, or it doesn't. Pistol remains functional, and the magazines inside the case remain accessible.

**Additional context**
Maybe I'm misunderstanding the functionality of the stealth storage, but this doesn't seem right to me.

**Comment by Tarmunora** [comment]
Could not reproduce. Are you sure you weren't just getting confused with how the stealth storage will camouflage itself as the first item you click on it with?

**Comment by scrcr0** [comment]
Okay I think I know what happened now. I may have tried to place the pistol into the stealth storage, which then camouflaged the stealth storage AS the pistol, and consumed the pistol in the process. Examining the pistol did give a text message along the lines of 'contains 4/7 items', and the thought never occurred to me that the pistol was now just a weird looking box. Chalk it up to misunderstanding the function of the stealth storage, and not a bug. Odds are the pistol and magazines all ended up inside the _not-a-pistol-but-a-box_ and I was very confused.
