### ISSUE TITLE
Ghost drone factory camera wizardry

### ISSUE THREAD

**Issue by N0no** [goonstation/goonstation#4844]
[BUG]

**Describe the bug**
When I fell into the industrial loading chute in the ghost drone factory, my body was ejected but my camera stayed focused on the chute, I could still move as normal but the camera was stationary. When I fell back in and was re-ejected the bug was fixed, not sure if this is a rare thing or an actual bug that needs fixing.

**To Reproduce**
1. Go to ghost drone factory
2. Fall in the industrial loading chute
3. Bug described above

**Expected behavior**
My camera would follow my body

**Comment by BatElite** [comment]
Can get this to happen consistently at least on the factory type that cog1 uses by pushing against the ghost catcher pad (which can't be move through) and then going diagonally past the flusher.
