### ISSUE TITLE
Having a negative max health breaks health scanner readouts

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#4845]
[trivial]

**Describe the bug**
If your max HP is negative, health scanner readouts go all wonky.

**To Reproduce**
1. Have negative max HP- I've seen this done through cloning generally, but I believe there's other ways.
2. Health scan yourself
3. Huh

**Expected behavior**
Not... sure, honestly. I think the most intuitive way to do it would just always read as if they had 100 max HP- scanning someone with 10 max HP and seeing "10%" makes sense, as seeing "100%" doesn't actually tell you how much health they have.

**Screenshots**
A very dead target dummy with -20 max hp:
![image](https://user-images.githubusercontent.com/67879783/119260615-72bf0600-bb88-11eb-856b-fdf5c98eaf21.png)

**Comment by Tarmunora** [comment]
b3826ea
