### ISSUE TITLE
Kudzu People Death Bug

### ISSUE THREAD

**Issue by KamikazeMongoose** [goonstation/goonstation#4846]
[BUG]

**Describe the bug**
If you die and come back as a Kudzu person, the moment your body returns to life, you get kicked out of your body. It'll stand there drooling and helpless while you become stuck as () the ghost. You can't be cloned because you are no longer tied to the brain that was in your body. Without admin intervention or a previous scan, you're perma dead.

**To Reproduce**
1. Die on kudzu

**Expected behavior**
Come back as a kudzu person.

**Additional context**
It happened twice in a row for me. I watched as Mr. Green tried various ways of bringing me back, but to no avail. Even when the body died it still said I had no corpse to return to.

**Comment by DimWhat** [comment]
I swear if this is from synthbrains

**Comment by DimWhat** [comment]
Good news! It is!
