### ISSUE TITLE
Using wires to a pipe frame before adding chems makes the whole cable stack disappear

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#4855]
[BUG] 

**Describe the bug**
Pipeframing swallows cables if used in incorrect order

**To Reproduce**
1. Create pipeframe from metal sheets to begin making a pipe bomb
2. Do not add chems (like WF) yet
3. Add cables

**Expected behavior**
Pipeframe should either succesfully accept cables or just tell you to not add them yet, but the entire cable stack you used disappears. There is either a "You stuff the synthrubber-insulated copper-cable coil into the first pipe" or "You stuff the synthrubber-insulated copper-cable coil into the second pipe." message, but nothing really happens

**Comment by BatElite** [comment]
Not a bug, you're accidentally adding cable to the thing for some extra effect (don't know which).

Maybe there's some merit in making that step take like 10 or so cable.
