### ISSUE TITLE
playsound runtime on startup

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#4856]
[BUG] [runtime]

**Describe the bug**
File | sound.dm
Line | 152
Error | list index out of bounds

</div></div></div></div></div></div>

proc name: playsound (/proc/playsound)
  source file: sound.dm,152
  usr: the ill-looking fellow (/mob/living/carbon/human/future)
  src: null
  usr.loc: the sleeper (/obj/machinery/sleeper/future/dead_man_sleeping)
  call stack:
playsound(the ill-looking fellow (/mob/living/carbon/human/future), 'sound/items/zipper.ogg', 30, 0.2, null, 2, 0, 1, 0)
the white jumpsuit (/obj/item/clothing/under/color/white): equipped(the ill-looking fellow (/mob/living/carbon/human/future), 14)
the ill-looking fellow (/mob/living/carbon/human/future): force equip(the white jumpsuit (/obj/item/clothing/under/color/white), 14)
the ill-looking fellow (/mob/living/carbon/human/future): equip if possible(the white jumpsuit (/obj/item/clothing/under/color/white), 14)
the ill-looking fellow (/mob/living/carbon/human/future): equip new if possible(/obj/item/clothing/under/color... (/obj/item/clothing/under/color/white), 14)
the ill-looking fellow (/mob/living/carbon/human/future): New(the sleeper (/obj/machinery/sleeper/future/dead_man_sleeping))
the sleeper (/obj/machinery/sleeper/future/dead_man_sleeping): New(the floor (276,167,3) (/turf/unsimulated/floor/white/grime))

**To Reproduce**
1. Compile and run
2. Runtime

**Expected behavior**
for my for-in loop to not get itself an out-of-bounds index

**Additional context**
Experienced on a local by 2 people. Unsure on live.

**Comment by imnotjames** [comment]
I'll try to replicate.  I think if we rewrite 

https://github.com/imnotjames/goonstation/blob/master/code/modules/spatial_hashing.dm#L4:L5

to be

```
#define GET_NEARBY(A,range) spatial_z_maps[A.z]?.get_nearby(A,range)
```

It should fix this?

**Comment by imnotjames** [comment]
That previous comment was wrong!  While the value would be null, the list out of bounds exception is because `A.z` does not occur in the list so a runtime is thrown.  In this case, the `A.z` is `0` which is invalid as a Z-level because they're 1-indexed.

This reliably happens during prefab generation (in particular, the ship stuck in time) at the start of the game but it's unclear what caused this to _start_ happening.
