### ISSUE TITLE
Auto tables sometimes don't generate correctly in a prefab

### ISSUE THREAD

**Issue by Lythine** [goonstation/goonstation#4879]
[BUG]

**Describe the bug**
Auto tables _sometimes_ don't link up in a prefab, notably ones with one connection to a northern table.

**To Reproduce**
1. Make prefab with auto tables.
2. See bug. Sometimes.

**Expected behavior**
The tables would link up like normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/60405592/119582868-6bb81380-bd93-11eb-99dd-2c365721b2b6.png)
![image](https://user-images.githubusercontent.com/60405592/119582873-6f4b9a80-bd93-11eb-9042-34f36f3f7b05.png)

**Comment by Carbadox** [comment]
What's the prefab?
