### ISSUE TITLE
spritebug - left hand zippo inhand is a few pixels off

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#4881]
[trivial]

**Describe the bug**
The inhand for the zippo lighter is off to the left when held in the left hand. Looks floaty.

**To Reproduce**
1. Hold zippo in left hand
2. It floats

**Expected behavior**
Zippo in the correct Zippo position

**Screenshots**
![zippo1](https://user-images.githubusercontent.com/67879783/119599553-10d5ea80-bd9a-11eb-89df-03b7c8d32ee5.png)
Right hand zippo- fine, looks like I'm holding it
![zippo2](https://user-images.githubusercontent.com/67879783/119599551-10d5ea80-bd9a-11eb-873a-5d967b28d6b3.png)
Left hand zippo- floats in the air

**Comment by virvatuli-gh** [comment]
fixed in [55cab97](https://github.com/goonstation/goonstation/commit/55cab97e88d6bb184697c54b4e3adac72dad952a)
