### ISSUE TITLE
Cannot Closed Powered Airlocks with Crowbar

### ISSUE THREAD

**Issue by penny64** [goonstation/goonstation#4885]
[BUG]

![image](https://user-images.githubusercontent.com/13049028/119679029-e36a5a80-bdf4-11eb-96b9-def41ecb8e46.png) ![image](https://user-images.githubusercontent.com/13049028/119679080-ecf3c280-bdf4-11eb-8233-19e29815e4f2.png) ![image](https://user-images.githubusercontent.com/13049028/119679511-44922e00-bdf5-11eb-8bfb-0d36fd453048.png)

**Describe the bug**
Powered airlocks cannot be forced closed
**To Reproduce**
1. Try to crowbar a door closed
2. Receive a message that you failed to open it
3. All of the atmosphere leaves

**Expected behavior**
Anyone can crowbar any airlock closed

**Screenshots**

**Additional context**
Only seems to be some external airlocks?
Is this just the message emagged airlocks emit?

**Comment by frawhst** [comment]
Seems likely that the door was just emagged- emagged doors seem to give that message, and I couldn't find any issues with regular doors. Better messages added here- 706532428bca459a007e6bdc264c4632f8e7644b
