### ISSUE TITLE
byond version 514.1555 cant interact with corpes

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#4895]
[BUG]

**Describe the bug**
cant interact with player corpses at all and monkey corpses
**To Reproduce**
1. see dead man
2. right click tile they are on
3. dont show in menu
4. click dead man
5. dont cant touch them

**Expected behavior**
none of bug that be

**Comment by Sovexe** [comment]
http://www.byond.com/forum/post/2686741

Probably this

**Comment by RSG250** [comment]
closeing since its a byond bug and not a goonstation bug probably
