### ISSUE TITLE
Infinitely-Long-Lasting Spatial Tear

### ISSUE THREAD

**Issue by Studenterhue** [goonstation/goonstation#4903]
[BUG]

**Describe the bug**
Spatial tears (as in the long, jagged, impassible red lines that stretch across the entire z-level) spawn from the associated event but do not disappear as supposed to. Instead of disappearing within five minutes, it seemingly never goes away, with one reportedly going on for over 30 minutes.

**To Reproduce**
1. Have a spatial tear event occur.
2. Observe that it does not pass away.
3. Scream

**Expected behavior**
They should be clearing away after a few minutes.

**Screenshots**
There's a runtime that seems to be associated with this bug, shown below:
![image](https://user-images.githubusercontent.com/78634918/119771868-583ca380-be8c-11eb-8e70-421bc412f581.png)

**Comment by imnotjames** [comment]
We're calling `START_TRACKING` but then calling `STOP_TRACKING` in https://github.com/goonstation/goonstation/blob/master/code/modules/events/spatial_tear.dm#L49

This was introduced in https://github.com/goonstation/goonstation/commit/8a16f304bda1b8bea9666060f30702348e107c21

**Comment by imnotjames** [comment]
@Kubius just tagging you cause you'd introduced the change

**Comment by imnotjames** [comment]
I wonder if this is because of the DM_BUILD version weirdness.. Is this happening on the live servers?

If it's local servers, what build of DreamMaker are you using?

**Comment by Studenterhue** [comment]
This is indeed happening (or happened perhaps) on the live servers.
