### ISSUE TITLE
Some people invisible to ghost drones

### ISSUE THREAD

**Issue by isaacashtox** [goonstation/goonstation#4919]
I noticed some people don't even have the static silhouettes that the ghost drones see. Tried restarting and reconnecting but the issue persisted. Same across rounds and different maps.
![image](https://user-images.githubusercontent.com/22652691/119746123-eee97000-be4c-11eb-93f7-36d9ec44f145.png)

**Comment by BatElite** [comment]
Duplicate of #4477, but will post some findings in that issue
