### ISSUE TITLE
Heath Scanner foreign object false positive.

### ISSUE THREAD

**Issue by mrprogamer96** [goonstation/goonstation#4929]
[BUG]

**Describe the bug**
The heath scanner picks up bullets that are in hand and not in the body has foreign objects.

**To Reproduce**
1. have a bullet in hand
2. scan the person holding it
3. See error

**Expected behavior**
The scanner to not pick up any false positives

**Comment by nefarious6th** [comment]
Can confirm this is a thing; was in the round when this happened.
