### ISSUE TITLE
Afterlife bar  cigarettes

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#493]
[BUG]

**Describe the bug**
Afterlife bar cigarette machine requires money. and its stock is not infinite.

**To Reproduce**
1. go to get cigarette
2. be sad it costs money
3. See error

**Expected behavior**
no money needed.

**Comment by MarkNais** [comment]
Don't you spawn with money in your pockets? Just walk out and back in to get more money. Though that won't fix the stock issue.

**Comment by RSG250** [comment]
miners dont spawn with money in pocket, as well as a few other jobs.

**Comment by pali6** [comment]
not a bug
