### ISSUE TITLE
Revenant ability bug - wrong abilities are visible/disabled

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#4935]
[BUG]

**Describe the bug**
When you're in revenant mode as a wraith, your special new revenant abilities are visible, but redded-out like you don't have enough points to use them. However, when used, they're totally functional. On the flip side, your regular wraith abilities are visible and appear usable, but don't let you cast them (which is how it's supposed to work. I just shouldn't be seeing them).

While testing this, I found some BONUS BUG:
The way this causes your abilities to lay out, any ability buttons the body you're inhabiting has (PDA light, internals, fire extinguisher, or just about any active genetic ability) cover your revenant abilities, making the covered ones unusable. Also, once the revenant dies, these unusable abilities (the ones tied to the body) are stuck on your screen until you revenant someone else.

**To Reproduce**
1. Become revenant
2. See wacky abilities

**Expected behavior**
The revenant abilities are redded out only if I don't have enough points to use them, and the regular wraith abilities aren't visible at all. Also my PDA light and internals buttons don't render my revenant powers unusable.

**Screenshots**
![image](https://user-images.githubusercontent.com/67879783/119987017-66b4b900-bf79-11eb-90d3-ac34ed231179.png)

**Comment by Zonespace27** [comment]
can reproduce both bugs
