### ISSUE TITLE
Cable coils manufactured through general manufacturer do not inherit insulating material

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#4943]
[BUG]

**Describe the bug**
While experimenting around with matsci I found that cable coils made by the general manufacturers don't inherit the insulating material used. Instead a default synthrubber insulation is always pumped out. This effects certain features of matsci that rely on the quality of the insulating material (e.g. the captain's antique laser gun).

**To Reproduce**
1. Empty a general fabricator of all its materials
2. Place some electrum in the general fabricator (gold + cobryl alloy) for the conductor
3. Place some wendigo hide in the general fabricator for the insulator
4. Print a new cable coil from the general manufacturer
5. Notice you've received a "synthrubber-insulated electrum-cable coil" despite using wendigo hide instead of synthrubber
6. *scream

**Expected behavior**
The general fabricator should respect the insulating material used, and pump out a wendigo hide-insulated cable.

**Screenshots**
![image](https://user-images.githubusercontent.com/84296283/120073813-f0db4b00-c067-11eb-8cf9-42f956ef8d46.png)

**Additional context**
Tried a couple other materials such as synthblubber and fibrilith all to the same result.

**Comment by zjdtmkhzt** [comment]
That's weird, I am pretty sure that _used_ to work!

**Comment by zjdtmkhzt** [comment]
The issue here is that the insulating material here needs to have an electrical conductivity of less than 1 for some reason. 
To my knowledge, no material has such a low conductivity stat, so it only works with materials that do not have a conductivity stat at all.

![image](https://user-images.githubusercontent.com/35579460/120083164-0d5aa000-c0c7-11eb-920a-d027fd36941e.png)

**Comment by zjdtmkhzt** [comment]
Although it's weird that the system chooses wendigo hide in the first place, seeing as it has a conductivity of 45, and as such should not count as an insulative material at all, so there may be a deeper issue here with material selection?
