### ISSUE TITLE
Unactivated gun artifacts can be shot point-blank

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#4947]
[BUG]

**Describe the bug**
Artifact guns can be fired at people point blank even if they're not yet activated.

**To Reproduce**
1. Spawn/find a gun artifact that's unactive.
2. Attack a victim point-blank.
3. Gun fires, victim goes owie.

**Expected behavior**
The artifact doesn't go pew

**Additional context**
Found this on local, if that matters any.

**Comment by zjdtmkhzt** [comment]
smh stupid point blanking why can't you just be normal
