### ISSUE TITLE
Dreaded AI Mainframe Noise

### ISSUE THREAD

**Issue by Emcee-Gore** [goonstation/goonstation#495]
[BUG]

**Describe the bug**
A round on Manta just now - when clicking on the AI button "Return to Mainframe" it will do so but the view will be covered in Noise. It is impossible to see onces surroundings. Just interaction bars from others are visible - indicating that the camera is at least centered on the AI core.

**To Reproduce**
1. Play AI - click on the "Return to Mainframe" button.
2. Unsure if part of this problem - but I have transformed into the participation ribbon in the round. Then cancelled said transformation.

**Expected behavior**
Pretty much a noisy screen.

**Screenshots**
https://i.imgur.com/Y3dAE84.png

**Additional context**
A similar case of something like this has happened before.
Months ago I posted it on the forums and this time around it seems to be a tad different. Requiring no restart for fixing.
https://forum.ss13.co/showthread.php?tid=13986
To fix the view - simply exit the Mainframe again.

**Comment by mybluecorners** [comment]
Followed your steps, could not reproduce at this time
