### ISSUE TITLE
Crowbaring airlocks open/closed doesn't play any sounds 

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#4955]
[BUG]

**Describe the bug**
As the title says

**To Reproduce**
1. Attempt to crowbar a depowered airlock open/closed
2. Be sad because it doesn't play any sounds

**Comment by virvatuli-gh** [comment]
fixed in [505ebb5](https://github.com/goonstation/goonstation/commit/505ebb5b592b36f8c9f723e37aeab71df8a9ecae)
