### ISSUE TITLE
Logging out of the game and relogging while in a pod breaks the pod UI/HUD

### ISSUE THREAD

**Issue by Drago156** [goonstation/goonstation#496]
[BUG]

**Describe the bug**
Basically if you log out of the game and come back through the byond hub while you were in a pod, you won't get any of the UI/HUD buttons and the only ways out of the pod is destruction, admin help, or the new pod interaction menu

**To Reproduce**
1. Enter a pod
2. Log out of the game entirely
3. Log back into the game
4. Spawn in the pod with no pod UI/HUD

**Expected behavior**
I've honestly know about this bug for ages, as have others I presume, so I expected this to happen exactly.

**Screenshots**
Didn't have any available, but I think it's pretty easy to imagine the pod view without the HUD

**Additional context**
Kyle apparently said the reason why this in particular has never been fixed was because it kept getting forgot about, so I guess this is a good time to finally patch this up

**Comment by Kyle2143** [comment]
Yeah this has been annoying. There has always been the "ship_exit" verb to get out when this has happened to the hapless player. But it's still tedious. It likely can be fixed somewhere in client.dm login or something where it's not calling the hud update proc if they are in a pod. Will look into it soon.

**Comment by Kyle2143** [comment]
Fixed.
