### ISSUE TITLE
Strange behaviour when quick equipping belts

### ISSUE THREAD

**Issue by ThePooba** [goonstation/goonstation#4963]
[BUG]
When equiping a belt, say the aurora belt, using the V key, if you have your backpack open, it will both equip the belt and dump everything it can into the backpack.

1. Open backpack
2. Pick up belt
3. Press V to quick equip belt
4. Watch as the inventory of the belt flies into the backpack and it gets wrapped around your waist in one fell swoop

I expect it to just equip the belt or transfer the inventory. Its very annoying to have my toolbelt dumped into my backpack every time i join as CE

**Comment by nefarious6th** [comment]
Sounds related to #4583 ; reading the V as trying to put it in the backpack initially maybe, which causes item transfer, and then identifying it as being equipped on belt slot?

**Comment by TobleroneSwordfish** [comment]
Fixed at some point.
