### ISSUE TITLE
The sauna is unrealistically cold

### ISSUE THREAD

**Issue by vuonojenmustaturska** [goonstation/goonstation#497]
[QOL]

**Describe the bug**
/obj/machinery/sauna_stove has a default temperature of 50 celsius, which is not even warm as far as saunas go. A 50'C sauna cannot be enjoyed by anyone, I would say 70'C is the absolute minimum.

**Expected behavior**
Saunas are generally enjoyed between temperatures of 80 to 100 C.

**Comment by geneva-breaker** [comment]
This is likely a geographical difference, as the sauna was coded by the finniest finn who's ever touched the goon codes. also 100°C is lethal cmon buddy

**Comment by Tarmunora** [comment]
>Implying that NT wouldn't install a sauna that reaches lethal temperatures

**Comment by vuonojenmustaturska** [comment]
100'C is completely fine and an enjoyable sauna temperature, personally I find them to start getting worse after 110'C. I don't know anyone who has fried themselves in a sauna. 

If my word is not good enough, here's a random mishmash of quotes from reputable random google results: 
![image](https://user-images.githubusercontent.com/20017308/80758999-3cf34d80-8b3f-11ea-9394-a6ce50525807.png)
![image](https://user-images.githubusercontent.com/20017308/80759019-48467900-8b3f-11ea-8f1a-cf373f6c58c0.png)
![image](https://user-images.githubusercontent.com/20017308/80759148-82b01600-8b3f-11ea-9a4e-ac69631f4c75.png)

Here's also a link to a reddit thread on the subject: https://www.reddit.com/r/Finland/comments/ekutfp/what_temperature_is_normal_in_a_finish_sauna/

**Comment by Carbadox** [comment]
don't really see any point in keeping this open. if anyone thinks otherwises, feel free to reopen this
