### ISSUE TITLE
nuclear operative space helmets dont fit on lizard sprites

### ISSUE THREAD

**Issue by unfunnyperson** [goonstation/goonstation#4976]
[BUG]

**Describe the bug**

**To Reproduce**
1. Be a lizard
2. equip nukeop space helmet
3. sprite is weird

**Expected behavior**
it to fit correctly

**Comment by Zonespace27** [comment]
Unclear if this is an issue similar to some hairstyles clipping through helmets, or something bigger?
Mind sending a screenshot here?

**Comment by DimWhat** [comment]
It's the snout clipping through. It's a consistant thing with several helmets that can be solved by making a new sprite.
