### ISSUE TITLE
replacing player borg parts doesn't update visually

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#4982]
[BUG]

**Describe the bug**
A roboticist replaced my light legs with treads. The treads still appeared as light legs on my sprite.

**To Reproduce**
1. Latejoin as an intelligence creation core borg
2. set name, change paint and eye color, pick module, as one does
3. have your light legs replaced with treads because youre slow as hell
4. treads appear as light legs

**Expected behavior**
treads to appear on the cyborg sprite.

**Additional context**
I'm not sure how much of the customization in step 2 affects this if at all, but I felt it was worth mentioning in case it is directly related to one of those.

**Comment by Yellow-Mushroom** [comment]
I was there for this, I’m pretty sure when the legs were removed (and not replaced) they were missing, but when I would put the tread on, the light leg would just return.
