### ISSUE TITLE
Coating bullets in silver ad-infinitum

### ISSUE THREAD

**Issue by Studenterhue** [goonstation/goonstation#4991]
[BUG]

**Describe the bug**
You can dip a .38 speedloader/.22 magazine in a beaker of silver reagent multiple times, even though it's supposed to only let you do it once. It doesn't make the bullet any more effective; it just wastes silver. 

**To Reproduce**
1. Procure a speedloader of .38 bullets or a magazine of .22 bullets. Any type will do, but I did notice a separate bug where .22 HP ones don't work.
2. Procure a beaker with at least 40 units of silver. While you need just 20 to make silver bullets, you need more than that to replicate this bug.
3. Click on the beaker with the ammo to dip it in silver. It should take 20 units of silver from the beaker.
4. Repeat 3 and notice the game doesn't stop you from coating them in silver multiple times.

**Expected behavior**
I expected the game to prevent me from coating the bullets in silver further, since something similar happens if you try to coat silver handcuffs in silver again, and the code seems to suggest this shouldn't be happening.

**Comment by Tarmunora** [comment]
b2ae684
