### ISSUE TITLE
Examining a gun loaded with silver bullets doesn't mention it having silver bullets

### ISSUE THREAD

**Issue by Studenterhue** [goonstation/goonstation#4996]
[BUG]

**Describe the bug**
If you coat some bullets with silver and load them into the relevant gun, using Examine doesn't mention if they're silver, even though you are meant to get a message. You get the same text as if you had regular, non-silver bullets inside.

**To Reproduce**
1. Make some silver bullets (take a .22 magazine/.38 speedloader and click on a beaker with at least 20 units of silver).
2. Load them into a suitable gun
3. Examine the gun.
4. Notice it doesn't mention if the bullets inside are silver.

**Expected behavior**
Based on the code in gun.dm., Examining the gun should tell you in the description that the gun is loaded with silver bullets.

**Comment by Tarmunora** [comment]
064238f
