### ISSUE TITLE
Concussion grenade runtimes when used with 40mm launcher

### ISSUE THREAD

**Issue by virvatuli-gh** [goonstation/goonstation#5002]
[BUG]

**Describe the bug**
As per the title, the concussion grenade runtimes and does some wacky stuff when loaded into the 40mm riot launcher. Upon detonating on a mob, the grenade's effect will play forever, as well as drop a perfectly fine grenade at the mob's feet. In effect, you could have unlimited concussion grenades by loading it into the riot launcher.

**To Reproduce**
1. spawn concussion grenade from pod wars
2. load it into the 40mm riot launcher using the conversion sleeve
3. launch at mob
4. get runtime and other wacky stuff

**Expected behavior**
The grenade should detonate on impact with the mob, play the effects once, and not respawn itself.

**Screenshots**
![concglitch](https://user-images.githubusercontent.com/68257280/120436972-997df900-c34d-11eb-95ae-2c6d3a243159.gif)

![2021-06-02 02_45_50-Runtime Viewer](https://user-images.githubusercontent.com/68257280/120436959-94b94500-c34d-11eb-9b86-b3fd39b9c990.png)

**Comment by Kyle2143** [comment]
Fixed in commit c945c3214b591d982425e3cffe63f2bcb45608a0
