### ISSUE TITLE
Cyborg docks can fix damage even when the number of "welding fuel available" reads 0

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#5010]
[BUG]

**Describe the bug**
When you normally go to fix brute damage on cyborgs using the docks you get a popup saying how much fuel to spend which dictates how much damage is healed, now you'd expect the "Welding fuel/Cable coils available" to dictate if you can heal or not if the number is 0 but you can heal with any value being displayed

**To Reproduce**
1. Get a cyborg hurt
2. Put them into dock
3. Waste all fuel/coils healing said cyborg over and over again 
4. Get them damage again
5. You can fix still fix them when the dock has run out of what it says it needs to do so, be confused

**Expected behavior**
A value of 0 means you can't fix the respective damage types

**Screenshots**

**Additional context**
This was done with a cyborg dock made with mechlab

**Comment by flappybatpal** [comment]
Looks like a simple fix. Looks like we remove fuel at https://github.com/goonstation/goonstation/blob/d3b4cf4abb3f84f8ad8955df6dc580400982ca20/code/modules/robotics/robot/robot_docking_station.dm#L352 but never bother to actually check if there is fuel before doing a repair.
