### ISSUE TITLE
You can pick up items with bear arms

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#5011]
[BUG]

**Describe the bug**
If you have a bear arm and try to pick up an item normally you get a message telling you that since you have no thumbs you can't really do that but click dragging an item onto your hand slot works and still lets you pick it up

**To Reproduce**
1. Get a bear arm or 2 attached to you
2. Find something to pick up
3. Click drag said item onto your hand slot
4. My bear arms have thumbs now

**Expected behavior**
You cannot pick up items this way

**Screenshots**

**Additional context**

**Comment by flappybatpal** [comment]
Fixed by #8602
