### ISSUE TITLE
Multiple item trader crates lacking bought items

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#5030]
[BUG]

**Describe the bug**
After purchasing 5 uqill and 5 erebite in a single transaction from Gragg, the resulting shipment only had 5 uqill and erased the stock of erebite that Gragg had without having sent any.

**To Reproduce**
1. Add 5 uqill and 5 of any resource that gragg sells that is limited to 5
2. Purchase the crate and open it 
3. Only 5 uqill, no sign of any other ores

**Expected behavior**
The crate coming with both uqill and example ores.

**Additional context**
I've had this done with Cerenkite and Erebite, but i'm sure it works with all of the ores that Gragg sells.

**Comment by Carbadox** [comment]
Verified issue with all traders
