### ISSUE TITLE
ALL cardboard boxes can be destroyed with items inside

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#5031]
[BUG]

**Describe the bug**
After purchasing any supply crate that is in a cardboard box from cargo, if you hit it with anything that does brute you'll crush the crate and the items inside without a trace of either. I don't think there's a minimum amount of brute required for this to happen, just anything that can inflict brute damage, even if its just one damage. I've had this happen a few times and I've gotten around to bug reporting it now.

**To Reproduce**
1. Purchase any supply crates that come in a cardboard box.
2. Accidentally/purposefully smack it with anything that could do brute damage as a weapon.
3. The crate has "Crumbled/crumpled" and the items have gone with it, without a trace.
4. RIP crate.

**Expected behavior**
Crate isn't destroyed, ideally. But if it is destroyed, have the items remain behind regardless.

**Screenshots**

**Additional context**
Had this happen a few times buying utility belts or any of the other crates that come in with cardboard boxes.

**Comment by Momoberry** [comment]
I'd like to note this does include OTHER crates hitting cardboard crates as well.

**Comment by Tarmunora** [comment]
ad8f900
