### ISSUE TITLE
Emagged secbot yells a lot and doesn't move

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#5037]
[BUG]

**Describe the bug**
A securitron I emagged as a wraith just stood in place yelling every second or so. Exact text is in the attached image

**To Reproduce**
1. Emag securitron
2. It doesn't smack anyone, and instead yells
3. ???

**Expected behavior**
Secbot goes on a justice rampage

**Screenshots**
![image](https://user-images.githubusercontent.com/67879783/120912150-b5311a00-c641-11eb-9d33-14a27e444048.png)

**Comment by Superlagg** [comment]
Does this happen to every emagged secbot?
