### ISSUE TITLE
Headspider near instant body takeover

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#5054]
[BUG]

**Describe the bug**
I got hit by a ling headspider, got a 10s stun, got out of the stun, said one word to someone, and then walked one tile when I lost control of my body.

It is supposed to work in stages last I check, 1-4, but this seem like it went straight to full takeover.

**To Reproduce**
Be ling/victim
Headspider/get headspidered
Check how long it takes?

**Expected behavior**
Get headspidered, see that I either have to immediately surgery this out, or die, knowing I have only about a minute to survive.
If its an RNG thing, why is it the last few times i've seen it, its been instant like this? Has something changed?

**Screenshots**

**Additional context**

**Comment by flappybatpal** [comment]
I'm not a disease expert but as far as I can tell this has 13% chance per tick to progress (however long a tick is) until it reaches stage 4 and has 40% chance to takeover so the duration could be so the minimum duration could be three disease ticks?

Doesn't seem like a bug more of a balance question of controlling RNG. As I said on Discord I think this is a case for a feature addition to give diseases minimum and maximum ticks per stage advancement, which maladies have for minimums.
