### ISSUE TITLE
sunglasses go over hair again

### ISSUE THREAD

**Issue by Retrino** [goonstation/goonstation#5067]
[BUG]

**Describe the bug**
originally, glasses went over hair, before being fixed to go under it. recently, its layered over hair again. 

**To Reproduce**
1. put on glasses. they will be over the hair. 

if this is intentional, i suppose it would somewhat make sense, since glasses acted weird with eyeshadow and such. honestly, it would make more sense to have a variable for them, rather than place them over the entirety of all hair layers, because what nerd wears glasses over their hair?

**Comment by nefarious6th** [comment]
the unwinnable battle...
Intentional with 1374708 but a good reminder nonetheless

**Comment by BatElite** [comment]
It is winnable (probably), but someone needs to prod hair drawing code
