### ISSUE TITLE
Rubber chickens are invisible

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#5107]
[minor]

**Describe the bug**
(this PR is referring to a junk item, afaik there's no rubber chickens in ranching except maybe if you do the matsci chickens with rubber)

The rubber chicken item doesn't have a sprite in-game

**To Reproduce**
1. find a rubber chicken in a duck egg (or just spawn one in really)
2. (Don't) see error

**Expected behavior**
Visible junk chicken

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/31984217/121611402-6f68bd00-ca58-11eb-8422-8db9149eeabc.png)

**Additional context**
I don't know where the sprite went if it didn't just get lost.

**Comment by Studenterhue** [comment]
Looks like #5437 has fixed this, since they have a proper sprite in-game now.
