### ISSUE TITLE
paint opacity when applied to cloths

### ISSUE THREAD

**Issue by Crackaduck** [goonstation/goonstation#5109]
[BUG]

**Describe the bug**
the bug in question is most apparent on colorful berets or white cloths, paint on clothing is too translucent, and doesn't resemble the color being applied to it.

**To Reproduce**
1. repair the paint machine
2. select your color of choice
3. apply paint to either colorful beret, or a white/grey piece of clothing

**Expected behavior**
the clothing should take on much more color from the paint, but instead it appears very translucent and unrepresentative of the color choice made

**Screenshots**
I dont have one on me right now, but was prompted to make a bug report by others as a discussion on it came up, as this has always bothered me since the paint change.

**Additional context**
I was big into paint, as such I was the one who first discovered the black paint grief method, I only did it once I believe, but as such, I've always felt I had a personal hand in the change made to the paint
here's a pre change image of me larping as ocelot from MGS3 
![image](https://user-images.githubusercontent.com/78562088/121616197-6cf26d00-ca30-11eb-92e0-d51dc638ecd4.png)

**Comment by DimWhat** [comment]
This isn't a bug, it's a 100% intended effect caused by a change to how the paint machine works.
