### ISSUE TITLE
Cannot eject prisoner from Port-A-Brig

### ISSUE THREAD

**Issue by Daktangle** [goonstation/goonstation#511]
[BUG]

When trying to eject the occupant of the Port-A-Brig using the Right Click Menu they are not ejected, and the verb command appears in the command bar, but that also does nothing.

**To Reproduce**
1. Have someone inside the Port-A-Brig
2. Make sure the Port-A-Brig is unlocked
3. Attempt to eject occupant using Right Click Menu

**Expected behavior**
The occupant should be ejected on top of the Port-A-Brig

**Comment by Tiggersaurus** [comment]
This is also affecting Borg chargers.

**Comment by mybluecorners** [comment]
tested - strangely, the move_eject verb does not work when i call it via the right click command but it DOES work when I call the proc directly in varedit.

... maybe a byond bug? not sure why it would be refusing to respond to the verb being triggered in one way and not the other

**Comment by Daktangle** [comment]
Update: bug appears to affect the right click -> eject ID function with PDA's as well

**Comment by mybluecorners** [comment]
For anyone experiencing this issue write your BYOND version too!

**Comment by Daktangle** [comment]
513.1521 for both Tiggersaurus and me.

**Comment by ZeWaka** [comment]
BYOND bug. Fixed.
