### ISSUE TITLE
Captain Spacebux Satchel

### ISSUE THREAD

**Issue by hazelmaecry** [goonstation/goonstation#5111]
_Description_
When playing as captain, after having bought one of the spacebux bags, claiming the satchel will revert your new bag into the default captain satchel.

_Steps to reproduce the behavior:_
1. Buy any of the new spacebux bags.
2. Start a shift as captain.
3. Claim the satchel.
4. Cry because you've lost your fancy new bag.

_Expected behavior_
Claiming the satchel should turn your bag into the satchel version of your spacebux bag, not the captain's bag.

**Comment by 112358sam** [comment]
Tested this on local and I could not reproduce it. Looking at the code it looks like it just checks whatever type of backpack is in the user's backpack slot, and that seems to be working as intended. Has this been addressed already?

**Comment by Vaskritaya** [comment]
This occurred to me just today. I spawned as a latejoin medical doctor and changed my Studded Backpack into a satchel, and it became a medical satchel instead.
