### ISSUE TITLE
Cargo Computer Unrepairable

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#5117]
[BUG]

**Describe the bug**
Bomb blew up the last remaining cargo computer.
Use screwdriver to fix broken cargo computer screen.
Cargo computer menu comes up, uninteractable.
Cannot remove broken glass to fix broken computer.
Unrepairable.

**To Reproduce**
1. Break your favorite cargo computer
2. Try to repair it like every other console/computer repair
2a. Like, screwdriver glass, crowbar panel out, cut wires, screwdriver board, crowbar board out, wrench console. Then the whole thing would be gone.
3. It doesn't unscrew the panel, it instead brings up an unusable cargo computer panel.
4. Scream (Ctrl + S)

**Expected behavior**
Cargo computer breaks.
I unscrew the panel.
I replace the panel
I go back to work.

**Screenshots**

**Additional context**
Scream

**Comment by frawhst** [comment]
bug stems from the fact that cargo computers aren't actually consoles, even though they look like them (and are called 'consoles').

**Comment by 112358sam** [comment]
Can't assign issues without triage, but I am testing a branch that would fix this for both types of cargo computers.
