### ISSUE TITLE
Heads impaled on spikes will float above the spike hover above the spike

### ISSUE THREAD

**Issue by vortex1942** [goonstation/goonstation#5118]
[BUG]

**Describe the bug**
When heads are put onto a spike they hover above the spike.

**To Reproduce**
1. Combine a head with a rod
2. Head will now be floating

**Expected behavior**
Heads should be impaled on the spike not floating on it

**Screenshots**
![image](https://user-images.githubusercontent.com/22815407/121769872-5e7b9100-cba9-11eb-90e1-8c513540ee21.png)

**Comment by nefarious6th** [comment]
duplicate of #4578
