### ISSUE TITLE
Spacebux clothing/visual purchases don't work for Borg

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#515]
[BUG]

**Describe the bug**
When choosing something on the spacebux list that would alter the appearance of starting Borg, it is bought but nothing appears ingame. I reported this over a month ago but guess it got missed when things went open source. I think it started around the time the clothing booth was added.

**To Reproduce**
1. Purchase Golden Hat
2. Be borg
3. Start game with no hat.
4. Be sad borg

**Expected behavior**
To have fabulous clothing bought with spacebux.

**Comment by pali6** [comment]
Can someone confirm whether this is still a bug? I vaguely remember fixing it.

**Comment by Tiggersaurus** [comment]
You did fix yes! Sorry I forgot to close it =\
