### ISSUE TITLE
AI can see the actions of ghosts

### ISSUE THREAD

**Issue by stonepillars** [goonstation/goonstation#5162]
[BUG]

**Describe the bug**
AI cores can see the actions of ghosts (Farts, Points are of particular concern)

**To Reproduce**
1. Be AI
2. Have a ghost point at something, or fart, or flip, or scream. Or any other emote that makes a visible message in chat.

**Expected behavior**
AI should not be able to see the actions of ghosts. Particularly points.

**Screenshots**
![image](https://user-images.githubusercontent.com/65367576/122206383-4ccb0f80-ce6f-11eb-9468-846f1fa8224b.png)

**Additional context**
This is has been a bug for like months I always assumed it was intended.

**Comment by Camryn-Buttes** [comment]
Technically a bug, but maybe an emergent feature at this point?

Been around for ages at this point, would feel weird not to have it.

**Comment by penny64** [comment]
With the Ouija board and everything it's pretty clear even to players that AIs are ghosts, it just works

**Comment by ThatFiveGuys** [comment]
Feature tm
