### ISSUE TITLE
Volume settings show your current setting as 'default', rather than the actual default

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#5176]
[trivial]

**Describe the bug**
When setting your sound channel volumes (radio, emote, etc) the pop-up shows the default volume. Except it doesn't, because it actually just shows the current setting, but says that's the default. 

**To Reproduce**
1. Set your radio music volume to anything, hit enter
2. Open the radio volume settings again
3. The setting you just set is now listed as the default.

**Expected behavior**
The default volume of the channel is actually listed.

**Screenshots**
![radio2](https://user-images.githubusercontent.com/67879783/122349017-a7f91280-cf00-11eb-8542-91c0b92a74d5.png)
![radio1](https://user-images.githubusercontent.com/67879783/122349020-a891a900-cf00-11eb-9149-7b1aeb486b87.png)

**Comment by zjdtmkhzt** [comment]
Those are both good things to know, perhaps we should just display both?
