### ISSUE TITLE
Tray hit stuns user, not the victim

### ISSUE THREAD

**Issue by UrsulaMejor** [goonstation/goonstation#518]
[BUG]

**Describe the bug**
When you hit someone with a tray, you get knocked down instead of them

**To Reproduce**
1.  Grab a tray
2. Hit someone with it
3. Fall down

**Expected behavior**
The person you hit should fall down, not you. Either that or nobody should.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Adharainspace** [comment]
aaa
