### ISSUE TITLE
Speech changing mutation makes me unable to speak through my radio headset by the prefixes like ";" ("Frontal Gyrus Alteration Type-BT " in this case.)

### ISSUE THREAD

**Issue by ReginaldCZ** [goonstation/goonstation#5182]
[BUG]

**Describe the bug**
When I have a speech changing mutation, like Frontal Gyrus Alteration Type-BT, which replaces some of my said words by the "butt" one, it also replaces the radio prefixes, which if it happens, makes me randomly unable to speak through the radio as if the prefix for example ";" is replaced by "butt!", I don´t speak through the public radio channel.

**To Reproduce**
1. Get somehow some speech-changing mutation, like the Frontal Gyrus Alteration Type-BT.
2. Try talking through your radio headset by the chat prefixes. Try it on the public radio channel (";") and the radio channel of your department (for example ":e" - Engineering department radio channel).
3. Find out that you are for some reason unable to talk through the radio headset.

**Expected behavior**
The prefix shouldn´t be replaced by butt word and so I should be able to tell my butt thoughts on the radio instead. Or there should be some message if it´s intented behavior, like that my character thinks too much about butts that it forgot to speak through the chosen radio channel.

**Screenshots**
None, as there wouldn´t be any good to show the issue anyway.

**Additional context**
None.

**Comment by KaitlynPickard** [comment]
This bug should be resolved now

**Comment by PrimeNumb** [comment]
Fixed as of https://github.com/goonstation/goonstation/pull/5296
