### ISSUE TITLE
You can get infinite metal sheets from the vendor frame by welding it

### ISSUE THREAD

**Issue by lkcny** [goonstation/goonstation#5184]
[BUG]

**Describe the bug**
You can get infinite metal sheets by welding(supposed to deconstructing) vendor frame repeatedly.

**To Reproduce**
1. Deploy the custom vendor frame
2. Weld the vendor frame
3. Repeat
4. Infinite metal sheets

**Expected behavior**
Should not reproduce metal sheets indefinitely, that's for sure.

**Screenshots**
![70](https://user-images.githubusercontent.com/67675401/122435042-9bdd8580-cfd2-11eb-804b-a1dcbf787d3d.png)
![71](https://user-images.githubusercontent.com/67675401/122435068-a0a23980-cfd2-11eb-85a1-9ae773089222.png)

**Comment by penny64** [comment]
Oops
