### ISSUE TITLE
Syndicate Purge System Clears Paint Job

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#5188]
[BUG]

**Describe the bug**
Attaching a Syndicate Purge System to a pod that has a paint job appears to clear the paint job until the pod weapon is removed.

**To Reproduce**
1. Make a pod with a paint job (I used the syndicate pod + flames paint)
2. Attach a Mk. 2 Scout Laser and notice the paint stays on
3. Remove Mk. 2 Scout Laser and attach Syndicate Purge System
4. Notice that your paint scheme is now gone
5. Remove Syndicate Purge System
6. Notice that your paint scheme has returned

**Expected behavior**
Your paint doesn't go away when attaching the Syndicate Purge System.

**Screenshots**
With Mk. 2 Scout Lasers:
![image](https://user-images.githubusercontent.com/84296283/122470828-847ba980-cf8c-11eb-9875-a085a9482a2f.png)

With Syndicate Purge System:
![image](https://user-images.githubusercontent.com/84296283/122470844-89405d80-cf8c-11eb-92a4-de99b9da7930.png)

**Additional context**
Likely also effects putts as well but didn't test.

**Comment by frawhst** [comment]
The Mk. 3 disruptor also does this.

**Comment by zjdtmkhzt** [comment]
Those weapons do not have the appearanceString set.
