### ISSUE TITLE
When gibbed while wearing the night vision goggles the goggles will appear on your ghosts face

### ISSUE THREAD

**Issue by Alexalmighty502** [goonstation/goonstation#5216]
[BUG] [MINOR]

**Describe the bug**
When gibbed while wearing the night vision goggles the goggles will appear on your ghost's face.

**To Reproduce**
1. Equip the night vision goggles
2. Gib
3. Notice the night vision goggles are still on your face as a ghost

**Expected behavior**
Being a boring ghost with no night vision goggles.

**Screenshots**
![screenshot 3034](https://user-images.githubusercontent.com/4682221/122676287-7d7eb200-d1ab-11eb-9a7c-984baee3d239.png)

**Comment by TTerc** [comment]
Pretty sure it happens with all kinds of eyewear

**Comment by Camryn-Buttes** [comment]
This happens with all forms of eyewear and I'm fairly confident that it's an intentional feature.

**Comment by DimWhat** [comment]
100% intended

**Comment by Alexalmighty502** [comment]
ah sorry then
