### ISSUE TITLE
Singularity Engine Extra Collectors

### ISSUE THREAD

**Issue by AshTheDerg** [goonstation/goonstation#5227]
[BUG]

**Describe the bug**
Unable to add additional Radiation Collectors/Controllers to Donut3 Singularity Engine 

**To Reproduce**
1. Buy new Radiation Collectors and Controller from Cargo
2. Install wiring
3. Install Collectors and Controller
4. Install Full Plasma Tanks
5. Check wires and SMES Computer
6. See no change to power

**Expected behavior**
Additional power from more Collectors/Controller

**Additional context**
Mentors and Admins BOTH have tried to help in game, still unable to get it to work

**Comment by Azrun** [comment]
Appears to work locally building from frames or spawning items directly.  Collectors periodically search for arrays and should provide power to the wired powernet.  
They can even be plopped onto the existing wiring on the left and right sides.
