### ISSUE TITLE
Flashbangs produced from the riot launcher produce no sonic stun

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5239]
[BUG]

**Describe the bug**
A flashbang fired from the riot launcher produces no sonic stun. Anyone with 100% eye resist is totally immune to flashbangs from the launcher. Hand flashbangs function as normal.

**To Reproduce**
1. Acquire security riot launcher.
2. Insert flashbang.
3. Fire next to (not directly at) target.

**Expected behavior**
Identical behavior between riot launcher and standard.

**Additional context**
I see no code that should intentionally treat flashbangs differently when launched from the riot launcher.
Fixing this bug would likely make riot launched flashbangs extremely effective against antags, as timing and throwing grenades correctly is quite difficult.

**Comment by flappybatpal** [comment]
Possibly due to https://github.com/goonstation/goonstation/commit/de3a15bc8869be1a9afe3062208a7a46531f27ac

**Comment by Tarmunora** [comment]
fixed
