### ISSUE TITLE
If a spontaneous intelligences' borg head is destroyed, when their brain is transferred, it kicks them out as a ghost.

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#5277]
[BUG]

**Describe the bug**
If a spontaneous intelligences' borg head is destroyed, when their brain is transferred, it kicks them out as a ghost.

**To Reproduce**
1. Join in as a spontaneous intelligence borg
2. Get your head destroyed
3. Notice as you are consistently kicked out as a ghost and your brain goes cold

**Expected behavior**
It is expected to go like how when you eject the spon intel brain, where you can be transferred to a new borg.

**Comment by Yellow-Mushroom** [comment]
To add, the following list will allow the brain to be transferred just fine:

-borg body being destroyed
-borg’s brain being popped out
-borg head transfer

Inconsistent:
-full borg destruction

never:
-borg head destruction

**Comment by frawhst** [comment]
fixed as of #5967
