### ISSUE TITLE
Shuttle nose falls off when hit with a power hammer

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5297]
[BUG]

**Describe the bug**
Front fall off.

**To Reproduce**
1. Call shuttle
2. Wait for shuttle to depart and be enroute
3. Use power hammer special attack near nose

**Expected behavior**
The front stays on.

**Screenshots**
![image](https://user-images.githubusercontent.com/70909958/123514257-f5f0e180-d689-11eb-8c7a-7db30013881d.png)

**Comment by Tarmunora** [comment]
lmao
