### ISSUE TITLE
Regeneration Is Broken

### ISSUE THREAD

**Issue by Hailstorm77** [goonstation/goonstation#530]
[BUG]

**Describe the bug**
If you get Regeneration and lose a limb, or have organs that are damaged or are bleeding, regeneration will not heal you. In the case with the bleeding you also cannot bandage yourself, I believe this is because of it thinking you aren't bleeding due to having regeneration but you still leak blood and take the damage. When attempting to bandage the bar will freeze after it barely fills up and will not work even if another person tries to bandage you.

Another thing to add in case this matters, I did have that gene that lets you launch your limbs, I don't remember what it's called but that is how I lost my arm.

**To Reproduce**
1. Get Regen
2. Lose a Limb
3. Try to use a bandage
4. It won't work

**Expected behavior**
With Regeneration, the wounds should close themselves and in the case of the organ damage (My lungs were messed up) it should've healed/regenerated them over time. My left arm was also never regenerated and was forever missing.

**Screenshots**
Unfortunately I didn't take any.

**Additional context**
I did have other genes as well, to list the ones I remember,
1. Polymorph
2. Hulk (the muscles had faded)
3. The limb launching one (It was empowered)
4. Cryokinesis
5. Stabilized Regeneration
6. Stabilized Natural Anti-Toxins

**Comment by Tarmunora** [comment]
Could not reproduce @ZeWaka
