### ISSUE TITLE
Touching a floating analysis form can teleport you to a dark void

### ISSUE THREAD

**Issue by A4Brogan** [goonstation/goonstation#5316]
[BUG]

The Bug requires a prison artifact, fully analysed WITH A BUGGED ANALYSIS FORM, and access to the Cargo Bay.

Want a potential way to visit the mysterious plane of darkness? Read on

1. Fully ID and analyze a prison artifact. Slap the form onto the artifact, and get the bug that makes it stick to the floor and the artifact.
2. Send that bad boy off via the QM sell belt.
3. try to pick up the artifact analysis form.
4. Be consumed by the plane of darkness, 

**Expected behavior**
Either the form to be yanked off the floor or to just disappear.
![scrnshot1](https://user-images.githubusercontent.com/4064043/123561763-52322f00-d778-11eb-820f-717c246aa2b4.png)

**Comment by flappybatpal** [comment]
"get the bug that makes it stick to the floor and the artifact."
Any info on this part?

**Comment by zjdtmkhzt** [comment]
Yes, please, that would be very nice.
