### ISSUE TITLE
Kudzu tiles do not protect Kudzumen on the shuttle

### ISSUE THREAD

**Issue by battlefan1942** [goonstation/goonstation#533]
[BUG]

**Describe the bug**
When a shuttle is in transit to centcom Benign kudzu tiles will still be visible, But will treat kudzumen as if they are walking on a non kudzu tile.

**To Reproduce**
1. Place a benign kudzu tile on shuttle
2. Stand on benign kudzu and wait for shuttle to leave
3. Once shuttle is in transit the kudzu tile will no longer protect kudzumen

**Expected behavior**
Kudzumen should be able to ride the shuttle on kudzu tiles

**Comment by Kyle2143** [comment]
Fixed.
