### ISSUE TITLE
Mining fabricator's "webpage" has not been found and picture errors

### ISSUE THREAD

**Issue by ReginaldCZ** [goonstation/goonstation#5335]
[BUG]

**Describe the bug**
When I click on anything from the list in the Mining fabricator's GUI in order to make it (when there are enough resources for it), I have recently started getting many times a HTML error stating that "This webpage isn't available.", which makes me unable to close the window and forces me to restart the client in order to be able to see anything in the game. The button "refresh" which shows in the error also doesn't help. And the window can't be even closed by the alt+F4 key combination.

I have noticed that this bug started happening since the update which started showing the sprites of items under the name of each item in the list of Mining fabricator's items. And also usually instead of these sprites I see html picture error.

**To Reproduce**
1. Join the round as a miner, if possible.
2. Go to the mining fabricator and use it with your empty hand in order to open the list of items.
3. Notice how instead of sprites of items you see just tons of html error pictures.
4. Try making anything there, for which you have enough resources.
5. Enjoy seeing a huge, unclosable window about how some webpage wasn't found forever until you restart the client.

**Expected behavior**
The sprites of items should be shown instead of the html error pictures. And mostly, there should be no HTML errors when I try to make anything on the manufacturer, which then makes me unable to close or even move the window and forces me to restart the client.

**Screenshots**
The error of "Not found webpage.".:
![SS13MiningFabricatorBug](https://user-images.githubusercontent.com/85322220/123833916-25605200-d907-11eb-89e2-030429dd5327.png)

The html error pictures instead of sprites of the items.:
 ![SS13MiningFabricatorBug2](https://user-images.githubusercontent.com/85322220/123833963-31e4aa80-d907-11eb-946b-2912a08e19d7.png)

**Additional context**
None.

**Comment by Sovexe** [comment]
Update your byond to 514.1557
