### ISSUE TITLE
Wizard shuttle magic mirror is invisible

### ISSUE THREAD

**Issue by LadyBirb** [goonstation/goonstation#5349]
[BUG - minor]

**Describe the bug**
The magic mirror on the wizard shuttle is invisible. It still works if you examine it through the rightclick menu so I marked this as minor.

**To Reproduce**
1. spawn in as wizard
2. stare at the wall where the magic mirror is supposed to be
3. notice it is invisible

**Expected behavior**
the magic mirror is not invisible

**Comment by flappybatpal** [comment]
https://github.com/goonstation/goonstation/blob/bffca517da5ca71e85d1b862069db3e66360e8c2/code/obj/item/misc_wizard_stuff.dm#L221
/obj/magicmirror
	desc = "An old mirror. A bit eeky and ooky."
	name = "Magic Mirror"
	icon = 'icons/obj/decals/misc.dmi'
	icon_state = "rip"

Checked the original misc.dmi on GH and that icon state did not exist. This sprite may have been lost.
Don't see anything appropriate in wizard.dmi either.
