### ISSUE TITLE
AI can depower doors with AI control wire cut

### ISSUE THREAD

**Issue by Enakai** [goonstation/goonstation#536]
[BUG]

If an AI has the door menu open while the AI control wire is cut, the AI can still control the door with the old menu.

**To Reproduce**
1. Be the AI
2. Get someone to cut the control wire on an airlock
3. You will still be able to bolt and unpower it, if the menu is still open.

**Expected behavior**
The AI should not have any control over the airlock with their control wire cut.

**Comment by ZeWaka** [comment]
menu likely not running the proper checks in it's Topic switch branch

**Comment by PrimeNumb** [comment]
This is apparently not a bug; it is explicitly mentioned in the code that the AI can bypass the AI control wire if it's been cut, after a short delay.
