### ISSUE TITLE
putting an automender inside a container does not cancel using it

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#5371]
[BUG]

**Describe the bug**
If you use an automender, and then put it inside a container, you will continue to heal with it until you move.

**To Reproduce**
1. Hurt self.
2. Use automender.
3. Put automender inside container while healing.

**Expected behavior**
Automenders cease to function when no longer in physical contact with the person being healed.

**Comment by Alexalmighty502** [comment]
I always thought this was intentional. This also allowed me to save critically injured people that would've otherwise died. I personally like this to be kept in because it adds a sort of skill ceiling to healing someone.

**Comment by MarkNais** [comment]
Could probably be fixed by checking if still in-hands (or in cyborg-active) during updates.
