### ISSUE TITLE
Batons circumvent the aurora belt and leave no attack image when activated.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#5375]
[BUG - MAJOR]

**Describe the bug**
When you attack somebody with a baton with it set to stun, you will ignore at least blocking and the aurora shield effect. Also you will not display an attack image like all other weapons do.

**To Reproduce**
1. Grab a baton and turn it on.
2. Use baton on somebody with an aurora belt.
3. Target will be hit by the baton 100% of the time as well as lacking any image for attacking.

**Expected behavior**
The baton to follow the rules of attacks and display an image as well as be blockable by the belt's special ability

**Screenshots**
Clicking on myself with a baton while wearing an active aurora belt yields no blocks.
![image](https://user-images.githubusercontent.com/40079883/124363277-e7fa0e00-dbff-11eb-8806-2899e0d78833.png)

**Additional context**
Baton code is hell.

**Comment by MetricDuck** [comment]
The attack image has been fixed, but batons still circumvent block chance when applying their stun. Deactivated batons work as expected
