### ISSUE TITLE
Milk jugs turning into milk bottles

### ISSUE THREAD

**Issue by Arthur-Holiday** [goonstation/goonstation#5379]
[BUG]

**Describe the bug**
Milk jugs wich are just re skinned milk bottles go back to looking like milk bottles after you drink out of them.

**To Reproduce**
1. Get milk jug
2. Drink the milk
3. Notice sprite change

**Expected behavior**
For it to stay the same, my guess is that it changes because states for them emptying up never were made.

**Comment by PrimeNumb** [comment]
Introduced in https://github.com/goonstation/goonstation/pull/4719
@nefarious6th
