### ISSUE TITLE
Making chocolate chips via food processor doesn't seem to work

### ISSUE THREAD

**Issue by WALPVRGIS** [goonstation/goonstation#5391]
[BUG]

**Describe the bug**
Putting a candy bar into the food processor is listed on the wiki as the method of obtaining chocolate chips, but I've found that it doesn't work at all. I saw someone else on discord mention this as well.

**To Reproduce**
1. Buy a candy bar from a snack machine
2. Place candy bar into the food processor
3. Food processor spits out unprocessed candy bar
4. Be sad that you have no choc chip :(

**Expected behavior**
For the method of obtaining the ingredient to work as intended, or if this is intended, for the wiki to be updated to reflect this.

**Additional context**
Only tested locally, but the mentions of this issue on discord happened on RP3, afaik.

**Comment by 112358sam** [comment]
Looks like the code checks for the type of input. It looks for /obj/item/reagent_containers/food/snacks/candy and the chocolate bar from the vending machine is /obj/item/reagent_containers/food/snacks/candy/regular. I'll get a PR out in a few minutes.
