### ISSUE TITLE
Sprites get stuck squashed and transparent

### ISSUE THREAD

**Issue by MarkNais** [goonstation/goonstation#5397]
[BUG]

**Describe the bug**
title.

**To Reproduce**
Try to enter a chute by click-dragging
While the animation plays, try to enter again 

upon ejection, your sprite is vertically squashed and partially transparent

**Expected behavior**
The sprite is returned to it's initial state.

**Comment by frawhst** [comment]
fix'd since the squishy sprite part of chutedragging was removed
