### ISSUE TITLE
speech bubbles permanently displayed on sprites

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#5404]
[BUG]

**Describe the bug**
Recently, the speech bubble created by speaking a message has been getting stuck, permanently displaying next to a characters' sprite. This only occurs rarely, but is sure to occur in a round due to the sheer volume of messages and players.

**To Reproduce**
Try talking -> ???? -> if you're unlucky, the bubble doesn't go away for some reason.
No idea, more info is highly appreciated. Joining any round with enough people should present a few cases of it, at least, if confirmation of this bug is needed.

**Expected behavior**
The speech bubble should vanish after a moment like it usually does.

**Additional context**
This seems to be incredibly recent, as in, within the past day or two.

**Comment by Yellow-Mushroom** [comment]
This used to happen to me occasionally but as of today, seemed to happen almost every other round

**Comment by ThatFiveGuys** [comment]
Im pretty sure this is fixed by #8056
