### ISSUE TITLE
actionbars can cause UpdateOverlays runtimes

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#5407]
[BUG][runtime]

**Describe the bug**
Actionbars can cause a runtime in at least one instance (outlined below) but I suspect it happens with anything that interrupts an actionbar and uses `UpdateOverlays`.

**To Reproduce**
This is probably not the only method, but it's the easy one I found:
1. Turn yourself into a monkey, put on a hat and find a table
2. Start an action bar for climbing the table and then cancel it by taking off your hat (putting the hat on doesn't interrupt)
3. Put the hat back on
4. Get stack trace

**Expected behavior**
No crashy

**Additional context**
Problem is probably related to `onStart` and `onDelete` on `/datum/action/bar/icon` directly messing with overlays, the cheeky things. However, since actionbars probably also apply to things that directly manage their overlays I imagine the only "proper" fix for making actionbars not do that is to move everything over to the `UpdateOverlays` method.

**Comment by MatheusIsNotAvailable** [comment]
I think what you could do is go back to putting the icon on the action bar's border instead of on the atom, I put them directly on the owner, so I could also put them on other stuff as needed, might be good to revert the PR that caused this(#5364) until we convert all overlay additions to UpdateOverlays

**Comment by BatElite** [comment]
Oh I didn't realise this was a very recent thing

**Comment by BatElite** [comment]
Fixed by the revert (probably), I think Arthur is taking a different route or something
