### ISSUE TITLE
If you un-possess a hauntium statue of yourself, it sends the statue/your body to 0, 0 baby jail in the void

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#5411]
[BUG]

**Describe the bug**
If you de-possess a hauntium coated statue of yourself, it will be sent to a 0, 0 void, where you cannot move or reposess it, only return to your body

**To Reproduce**
1. Suicide into the Arc plater with Hauntium inside of it
2. Possess statue of yourself
3. Leave status of yourself

**Expected behavior**
The statue should remain where you depossessed it and you should be able to re-enter it

*

**Comment by Yellow-Mushroom** [comment]
Okay so I’ve gotten it to have the same effect twice now, once with a hauntium object, and once with another statue of myself.

testing should be easy since if the statue is still there, you can hop back in then depossess again. 

It doesn’t seem to be every time, but two out of the theee times I tried it, it made the statue zip to 0,0

**Comment by 112358sam** [comment]
I haven't been able to replicate this on local. Was it on a specific map or part of the map? Are there any other details that could potentially be a requirement?

**Comment by Yellow-Mushroom** [comment]
Hrm, both times it was on Manta, and I specifically clicked the de-posses X in the top of the screen, it seemed to be happening pretty consistently for me
