### ISSUE TITLE
Mutini can turn people into vampires/ww

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5447]
[BUG]

**Describe the bug**
Mutini can cause /datum/bioEffect/drunk/random and /datum/bioEffect/drunk/random/unstable.
Both of these pick reagents from all_functional_reagent_ids, the only blacklisted reagents from this are QGP, space plague, omegazine and nitro.
Werewolf is supposed to be blocked from Mutini but will still have an incredibly low chance of Mutini giving you vampire/werewolf serum. These bioeffects can definitely provides enough units to transform you, as demonstrated in the screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/70909958/125169329-96262a80-e1a1-11eb-847b-dca213e00e84.png)

**Comment by frawhst** [comment]
@flappybatpal This is so incredibly rare that I'm personally fine with it existing; your call though
