### ISSUE TITLE
Grave Fever is broken

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#5454]
[BUG]

**Describe the bug**
Grave Fever progresses through its stages normally but has no symptoms.

**To Reproduce**
1. Eat enough grave dust to get infected with grave fever
2. Wait
3. Observe no ill health

**Expected behavior**
To die horribly

**Additional context**
I've only tried this via grave dust, dunno if the vampire ability is broken too but I assume so.
Found on main, and reproduced on local.

**Comment by 112358sam** [comment]
Did some testing. It is caused by grave fever using probmult with a mult value of null. None of the symptoms trigger as this is treated as 0 probability. I'm working on a PR to fix this.
