### ISSUE TITLE
Cyborgs don't seem to take damage from shark drones

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#5493]
[BUG]

**Describe the bug**
Cyborgs seemingly don't take any damage from sharkdrone bullets, other creatures seem to be able to damage them just fine though (example: the spikes from hallucigenia will hurt)

**To Reproduce**
1. Be a cyborg
2. Find a sharkdrone
3. Get shot with 60 bullets and not have your health drop at all

**Expected behavior**
You are damaged normally

**Screenshots**

**Additional context**
Only noticed it with sharkdrones, more sea creatures/space drones could have this same problem

**Comment by Cthucky** [comment]
If I'm not mistaken, cyborgs have some inherent damage reduction and sharkdrone bullets deal 1 damage.  At one point you did take damage, just an extremely small amount that required a shitton of bullets to have a visible health drop, at least on light borgs.

Might be worth checking to see if that's the case here.

**Comment by Zergspower** [comment]
IIRC it was due to the fact it was borgs being insta-gibbed by a sharkdrone - granted it's been a while since i saw it talked about but it's been known for over a year at least

**Comment by Tarmunora** [comment]
> 
> 
> If I'm not mistaken, cyborgs have some inherent damage reduction and sharkdrone bullets deal 1 damage. At one point you did take damage, just an extremely small amount that required a shitton of bullets to have a visible health drop, at least on light borgs.
> 
> Might be worth checking to see if that's the case here.

the bullets do 1 damage each, after the misc multipliers in borg code it gets reduced to 0.4 damage each, and cyborg bullet handling does an early return on damage < 1

**Comment by frawhst** [comment]
Not really a bug, just a strange interaction of features. For now I'll just consider it fine; piddly shark bullets can't penetrate Steel.
or something. idk
