### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by MCWarhammer** [goonstation/goonstation#5498]
I keep getting this error when connecting to Goon1, and it asks me to post it here.

Script error.
   at http://cdn.goonhub.com/tgui/tgui.bundle.js?serverrev=b39e5e873aa68701f62586edda2a4a28ef78d49f:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; wbxapp 1.0.0; Zoom 3.6.0; wbxvdi 1.0.0)
State: {"ckey":"mcwarhammer","interface":"CharacterPreferences","window":{"key":"[0x2101ed83]-main","size":null,"fancy":1,"locked":0}}

Copyright 2046-2053 Thinktronic Systems, LTD.

**Comment by ZeWaka** [comment]
not able to fix with this info
