### ISSUE TITLE
Wizard spellbook description (and spell description) mentions removed telekinesis effect

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#5505]
[trivial]

**Describe the bug**
The spellbook and spell descriptions for Empower still imply that the spell will grant you telekinesis, and don't mention the wrestler bonuses at all:
https://github.com/goonstation/goonstation/blob/2e116d0e8df159dcd84e5cc7625d111b5223eaaf/code/datums/abilities/wizard/mutate.dm#L3
https://github.com/goonstation/goonstation/blob/2e116d0e8df159dcd84e5cc7625d111b5223eaaf/code/datums/abilities/wizard/mutate.dm#L20
https://github.com/goonstation/goonstation/blob/5c08d79aa3f8269ab83cfc8f599decfdeb18f8fe/code/obj/item/uplinks.dm#L1163

**To Reproduce**
1. Read spellbook
2. Incorrect spell description
3. Confusion

**Expected behavior**
The descriptions don't reference the telekinesis effect, and probably tell you about your new wrestleriffic powers.

**Comment by frawhst** [comment]
fixed by a8253286febbdd57fb76990e0b8ec5eb0a3509ac

**Comment by MatheusIsNotAvailable** [comment]
a825328 only fixed the book's description, the spell's messages and description are still the old ones, should probably re open.
