### ISSUE TITLE
Dwarfism inconsistancy

### ISSUE THREAD

**Issue by Vorlice** [goonstation/goonstation#5517]
https://www.youtube.com/watch?v=D6TCkNLdj8E

This video sums it up but I noticed that in certain areas of medbay on cog1, dwarfism is visually canceled out.

Found 7/15/21 on Morty Cog1, Local server time around 14:00-15:00 (2-3pm)
[BUG]

Describe the bug
Dwarfism visually canceling out

To Reproduce
Have dwarfism and move to areas in medbay as shown in video.

**Comment by Tarmunora** [comment]
WAT

**Comment by zjdtmkhzt** [comment]
thindows strike again?
when will it end?

**Comment by BatElite** [comment]
Haven't gotten this to show up on local so far. From that footage it looks to me like the common thing for all the affected turfs was that they were on the same 2 wide vertical column, but aside from that no idea what's going on yet.
