### ISSUE TITLE
Secbots null if destroyed after stunning and trying to stun again

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5518]
[BUG]

**Describe the bug**
Destroying a sec bot when they are between stuns will give a null.

**To Reproduce**
1. Get stunned by Beepsky
2. Destroy Beepsky when they are preparing to stun you again

https://github.com/goonstation/goonstation/blob/ddaab93200d92b1f949e93e8783196d727e46c92/code/modules/robotics/bot/secbot.dm#L572

Andy Kellogg has been stunned with the stun baton by Officer Beepsky!
Andy Kellogg fires Branwen pistol at the wall!
Andy Kellogg fires Branwen pistol at the steel floor!x2
Officer Beepsky is energizing its prod, preparing to zap Andy Kellogg!
Andy Kellogg fires Branwen pistol at the steel floor!
Andy Kellogg twitches.
Officer Beepsky blows apart!

**Screenshots**
![image](https://user-images.githubusercontent.com/70909958/125864288-ef30414c-510a-4479-a378-2c53249a139f.png)

**Comment by ThatFiveGuys** [comment]
Cant find specific commit but I remember this being fixed and upon testing it doesn't runtime anymore so fixed.
