### ISSUE TITLE
Runtime relating to Milk Punch

### ISSUE THREAD

**Issue by Zonespace27** [goonstation/goonstation#5520]
[BUG] [RUNTIME]

**Describe the bug**
File: Reagents-FoodDrink.dm
Line: 117
Error: Cannot execute null.contract disease()

**To Reproduce**
Unsure currently, it occurred for me on Atlas, with nothing related to Milk Punch at all.

**Expected behavior**
Not to runtime.

**Screenshots**
[Runtime Data + Stack Trace](https://user-images.githubusercontent.com/41448081/125872553-9d949d29-8f07-4a9d-9a69-081b7a65aa80.png)

**Comment by Zonespace27** [comment]
@nefarious6th

**Comment by Tarmunora** [comment]
should be fixed
