### ISSUE TITLE
Ghost Goggles stop working with X-Ray mutation

### ISSUE THREAD

**Issue by RagdollWizard** [goonstation/goonstation#5529]
[BUG]

**Describe the bug**
Wear the ectoplasmoleic imager, get the x-ray mutation, no ghosts :(

**To Reproduce**
1. Acquire the Ectoplasmoleic Imager (goggles that let you see ghosts)
2. Get X-Ray mutation from Genebooth
3. See chat messages from ghosts flipping and pointing, but no actual ghosts on the screen
**Expected behavior**
I can still see ghosts even with the x-ray mutation

**Screenshots**

**Additional context**
I still cannot see ghosts even after taking the goggles off and putting them back on.

**Comment by alexeric123** [comment]
Adding onto this, most vision modifiers do not work together, EX: NVG's xray mutation, NV mutation, mesons
