### ISSUE TITLE
Decontructing Deepfryer

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#5539]
<BUG>

**Describe the bug**
Attempted to deconstruct a deepfryer, as it was blocking escape, instead, I deepfried my only deconstructor.

**To Reproduce**
1. Scan and build deepfryers
2. Attempt to deconstruct it
3. Insert deconstructor into deepfryer like some sort of idiot?

**Expected behavior**
1. Scan and build deepfryers
2. Attempt to deconstruct it
3. Deconstruct deepfryer so it gets out of the way.

**Screenshots**

**Additional context**

**Comment by mordent-goonstation** [comment]
Not a bug per se. Deep fryers claim many victims (mechanic PDAs being a common one). Put something in and get it frying prior to hitting with your deconstruction device and it should work.
