### ISSUE TITLE
VR Chess is scuffed and illegal

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#5547]
[BUG][TRIVIAL]

**Describe the bug**
In VR chess, the board is rotated 90 degrees, resulting in the board's square colours not corresponding to an actual board. Furthermore, the kings are on the d file whereas standard chess would place them on the e file; meaning that the queens which are usually on the d file are placed on the e file in VR chess. 0/10, literally unplayable.

**To Reproduce**
1. Enter VR.
2. Try to practice chess theory on the massive board next to the gauntlet.
3. Realise something's up when the a1 square is light coloured.
4. Try to practice your 1. d4 d5 London system line and realise that the kings and queens are on the wrong files.
5. Cry.

**Expected behavior**
For the board position and orientation to be legal per FIDE specifications.

**Screenshots**
![image](https://user-images.githubusercontent.com/66253095/126050967-f4ff5b7f-0baa-4acf-94a4-47b21f1e9576.png)

**Additional context**
I'm a goddamn nerd.

**Comment by WisconsinYuzuru** [comment]
this is so sad. 😔
