### ISSUE TITLE
Zombie hulk hogan's sideviews looks weird.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#5550]
[Bug - Trivial] [Sprites]

**Describe the bug**
Zombie hogan's sprite does not show his hands on the sideviews.

**To Reproduce**
1. See zombie hulk hogan's sideview.
2. Notice a lack of hands.

**Expected behavior**
Hulkster's sprite to letting me see dem hands

**Screenshots**
![image](https://user-images.githubusercontent.com/40079883/126054628-7859725a-e3d8-4e11-9804-af2b05486cfe.png)

**Comment by BatElite** [comment]
time2chunk zombies?

**Comment by DimWhat** [comment]
> time2chunk zombies?

Zombie hulk hogan is actually a critter, so chunking wouldn't help him in this case.

**Comment by flappybatpal** [comment]
Fixed by https://github.com/goonstation/goonstation/commit/92cdb0fc0f28f479f5e19dd577e5119f48c347ba
