### ISSUE TITLE
It's possible for petasusaphilic to give you the Very Syndicate Hat

### ISSUE THREAD

**Issue by KoboldCommando** [goonstation/goonstation#5553]
[BUG]

**Describe the bug**

I am not sure how, but I latejoined a round on goon 1 as scientist, and I had "Cammie Kobold's Autographed Very Syndicate Hat" in my hand.  I suspected shenanigans but confirmed I had no trinket in my backpack so that had to be from the trait.

**To Reproduce**
1. Pick Petasusaphilic
2. Join a lot of rounds
3. Receive ridiculous hat

**Expected behavior**
The code in jobprocs.dm specifically attempts to remove the syndicate hats from the types of tinket it can give you from the trait.  From what I can see you shouldn't be able to spawn with it.  Hopefully someone can figure out what's up.

**Screenshots**
Sadly, Beepski was in arrivals and the ensuing chaos made taking a screenshot slip my mind.

**Additional context**
A friend testing in private has confirmed this can happen.

**Comment by DimWhat** [comment]
![image](https://user-images.githubusercontent.com/40079883/126056771-251313f1-df30-45c0-8564-5ab9f0764a52.png)
Yeah

**Comment by DimWhat** [comment]
Judging by the code in #5208 this applys to every single hat except the syndicate space helmet, the bighat (not the syndicate hat), and the blue barrettes SPECIFICALLY. No other hat is covered by this blacklist. Christ how did this get merged.

**Comment by KoboldCommando** [comment]
VS Code is being an absolute shit.  Go to the bottom of jobprocs.dm

Find the line at the very end that says var/list/hat_blacklist = list(typesof(/obj/item/clothing/head/bighat, /obj/item/clothing/head/helmet/space/syndicate, /obj/item/clothing/head/barrette))

Change that to say typesof() for each of the things individually rather than just once for the whole.  I'm reasonably sure that should work.

Also someone come beat my VS Code with a fire extinguisher.
