### ISSUE TITLE
wire stops reciving power from the geo vent OSHAN

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#556]
[BUG]

**Describe the bug**
when wiring hotspots, if ya cut a wire while the vent is up, or have another wire line join a current one, the wire line stops receiving power from the vent, no matter where the cut was made in the line. only way to fix it is to remove vent and redeploy it.
**To Reproduce**
1. cut wire anywhere in the line between the vent and the smes, or add a new line to the power line with a new source
2. scan with t ray after a moment
3. see no power in line
4. See error and be said

**Expected behavior**
power to be in line and NOT have to redeploy the vent

**Additional context**
Ive had this happen several times and ive forgotten to bug report it each time, and the only time i remember to bug report it is when im not playing at the moment. good times.

**Comment by Enfaeutchie** [comment]
Experienced this today. Wire did not receive power, even directly under the vent. Redeploying did not fix - admin intervention was needed (thanks, efrem!)

**Comment by pali6** [comment]
Unable to reproduce despite trying in multiple different ways. Might have gotten fixed at some point.
