### ISSUE TITLE
Ghost Drones Can't See Lizardpeople

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#5569]
[BUG]

**Describe the bug**
Can't see lizardpeople as a ghost drone, could only tell they were a lizardperson based on their speech.

**To Reproduce**
1. Be a ghost drone.
2. Encounter a lizardperson.
3. Notice the distinct lack of a lizardperson there, but still hear them.

**Expected behavior**
Being able to see lizardpeople as a ghost drone 

**Screenshots**

**Additional context**
I noticed there was a pr that supposedly fixed the mutant race static. Not sure if this bug was because of my bad laptop or not, but if it wasn't, they it appears the bug my still be around.

**Comment by BatElite** [comment]
Had the same thing earlier and I made that PR, oh no

(Will be a day at least until I'm back to my coding rig though)

**Comment by 112358sam** [comment]
Has this been fixed? I could not reproduce it on local.

![image](https://user-images.githubusercontent.com/22460970/137790851-792b8f6e-8a59-40e0-89a9-8322255f6240.png)

**Comment by ThatFiveGuys** [comment]
Unable to reproduce on server too
