### ISSUE TITLE
Red oxygen grenades don't fix the low pressure sound effects

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#5582]
[BUG]

**Describe the bug**
Title. Even if an area has perfectly breathable air again after repressurizing with the grenades, the sounds remain muffled

**Comment by TTerc** [comment]
@Azrun :iiam:

**Comment by Azrun** [comment]
The attenuation to volume is based on the pressure of the tile, were the turfs back to normal pressure at that point?

sound.dm::37 
/proc/attenuate_for_location(var/atom/loc)

**Comment by Azrun** [comment]
Reproduced
