### ISSUE TITLE
Random Event Antags spawn in a gang 

### ISSUE THREAD

**Issue by N0no** [goonstation/goonstation#5607]
[BUG]

**Describe the bug**
When dying as a gang member then spawning as a random event antag (in this case a wrestledoodle), i was placed back into the gang.

**To Reproduce**
1. Join gang
2. Die
3. Spawn as random event antag
4. Be placed back into the gang

**Expected behavior**
They don't do that

Edit: Might also add that my body was gibbed, not sure if that affects this or not though.

**Comment by N0no** [comment]
Upon further testing and looking at the goonhub antag list, it seems like status as a part of the gang is not kept, as I can't get gear from the locker after respawning, though the red/blue G above the head is kept after respawn. Can confirm this also happens to blob overminds aswell.

**Comment by BatElite** [comment]
Probably the same issue that's causing #2065

I'm guessing ganger antag status is kept around for cloning purposes, but not cleared when transferring to something else.

**Comment by ThatFiveGuys** [comment]
Closing this one and leaving #8515 open because this is a dupe and that one is more clear on cause
