### ISSUE TITLE
Can't recharge cargo teleporters

### ISSUE THREAD

**Issue by Zergspower** [goonstation/goonstation#5612]
[BUG]

**Describe the bug**
![image](https://user-images.githubusercontent.com/22140677/127083263-61b8c055-4940-418a-bbd9-d700b454fdc2.png)
Currently unable to insert cargo transporters in the recharger

**To Reproduce**
use a charge
try to charge it

**Expected behavior**
I think something affected it with a different change, but it should recharge or have a replaceable battery that we can charge.

**Comment by Zergspower** [comment]
unrelated, but you can also teleport multiple things as long as at least one charge exists past it charge count. 
![image](https://user-images.githubusercontent.com/22140677/127085007-8944d722-851d-4d78-a7cd-78ce44205bcc.png)

**Comment by Tarmunora** [comment]
should be fixed nowww
