### ISSUE TITLE
Hugging a bee and/or guardbuddy doesn't produce hugs

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#5614]
[BUG]

**Describe the bug**
Hugging a bee doesn't produce hugs, only if they hug you back you'll get it

**To Reproduce**
1. Find a bee or guardbuddy
2. Hug it
3. Attempt to extract hugs from yourself
4. Notice how unhugged you are

**Expected behavior**
I was told that hugging a bee or guardbuddy can produce hugs, and that the bee/guardbuddy doesn't have to hug you back in order to make it.

**Additional context**
Not sure if I was just misinformed about how pure hugs is produced, or if this is a genuine bug

**Comment by Wisemonster** [comment]
My bad, that was supposed to be pure hugs, not love

**Comment by BatElite** [comment]
Will test, but IIRC they do have to reciprocate
