### ISSUE TITLE
Elevator shaft turf uses standard steel tile scorched sprite

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#5615]
[trivial]

**Describe the bug**
If an elevator shaft turf is scorched, it turns into a regular scorched tile. 

**To Reproduce**
1. Welderbomb the elevator shaft on oshan
2. See error

**Expected behavior**
The sprite doesn't update, I guess. It's a hole!

**Screenshots**
Forgot to take one. oops

**Comment by TobleroneSwordfish** [comment]
Fixed by #9135
