### ISSUE TITLE
Duplicating blank patches by filling patch boxes

### ISSUE THREAD

**Issue by HatNJacket** [goonstation/goonstation#5622]
[BUG]

**Describe the bug**
Quickly filling a patch box multiple times to add blank patches

**To Reproduce**
1. Create a box of patches using a CheMaster 3000
2. Create a pile of patches, either by emptying the patch box or by using the CheMaster 3000 to create patches without the box
3. Quickly click-drag the patches to the box multiple times. You should get multiple notifications of quickly filling the patch box. (See screenshot)

**Expected behavior**
The patch box will contain more patches than when you started, however the excess patches will contain no chemicals.

**Screenshots**
[https://prnt.sc/1h40jus](url)

**Additional context**
Some preliminary testing with pill bottles shows that this bug does not affect pills in pill bottles.

**Comment by Tarmunora** [comment]
7f2c4dd
