### ISSUE TITLE
chickens are too powerful for plastic flaps and the crusher

### ISSUE THREAD

**Issue by mopcat** [goonstation/goonstation#5627]
[BUG]

**Describe the bug**
dead chickens cannot pass through plastic flaps without human assistance, nor can they be pushed by conveyor belts into the crusher. this results in the rancher, should they choose to dispose of deceased chickens rather than give them to the kitchen, indirectly clogging the entire disposals line, preventing people from digging through the station's garbage without first getting rid of the chickens

**To Reproduce**
1. send a bunch of dead chickens down a disposals chute
2. find that the chickens are not moving past the plastic flaps
3. end up having to throw a bunch of chickens into the crusher. manually.

**Expected behavior**
the chickens are able to have their dead bodies utterly destroyed by the disposals system without needing human assistance

**Comment by Sovexe** [comment]
https://github.com/goonstation/goonstation/commit/c8caab7afca1f92c99865cc026bcbf92059dab90
