### ISSUE TITLE
Satchels are missing 3 pixels on the frontview.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#5636]
[Trivial]

**Describe the bug**
Satchels make a hand hole too large for the front view thus making it end early and leave 3 pixels out that should be covered by the satchel.

**To Reproduce**
1. Put on a satchel
2. Observe missing pixels

**Expected behavior**
To not be missing 3 pixels on the frontviews

**Screenshots**
![image](https://user-images.githubusercontent.com/40079883/127691283-dcacb6d7-630f-4d8f-af37-43bb9d4af8c3.png)

**Additional context**
All satchels have this issue. Good luck.

**Comment by WALPVRGIS** [comment]
May god have mercy on my soul
