### ISSUE TITLE
sleepy pens target the person whos being held if you try to sleepy pen somebody who is holding someone

### ISSUE THREAD

**Issue by unfunnyperson** [goonstation/goonstation#5649]
[BUG]

**Describe the bug**

**To Reproduce**
1. have someone grab another person
2. use a sleepy pen on the first person
3. grabbed person gets penned instead of the being their grabbing

**Expected behavior**
Sleepy pen to properly target the person who has somebody grabbed

**Comment by Tarmunora** [comment]
not a bug
grabs will use the victim as a meatshield against item attacks as well as projectiles
