### ISSUE TITLE
Talk Show Host doesn't have access to internal door in radio station on map Manta.

### ISSUE THREAD

**Issue by Xoxeyos** [goonstation/goonstation#5652]
**Describe the bug**
Talk Show Hosts don't have access to the "Communications Office" door, behind which holds their equipment.

**To Reproduce**
1. Pick map Manta
2. Become a radio host
3. Go to office, and click on the blue door, titled "Communications Office".
4. Fail to get inside because you don't have access to your record player, or your bedroom.

**Expected behavior**
I should be able to open said doors.

**Comment by Zonespace27** [comment]
The Talk Show Host ends up kinda homeless due to the Comms officer being the (actual) radio host on Manta.
The comms office requires bridge access, by the way

**Comment by WALPVRGIS** [comment]
I've run into this issue while mentoring before and it's weird and confusing, perhaps the Radio/Talk Show Host job should just be made unavailable on Manta? Since there's a different role that takes their place anyhow.
