### ISSUE TITLE
Gunbot antag critters can't pointblank with their gun arms

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#5654]
[minor]

**Describe the bug**
Gunbot critters can't pointblank adjacent people with their gun arms. This means that shooting prone people almost always misses them.

**To Reproduce**
1. Knock a guy down
2. Click them with a gun arm while adjacent
3. Doesn't pointblank them

**Expected behavior**
The gunbot arms behave like regular guns, and allow you to pointblank people/shoot them instantly while adjacent

**Comment by pali6** [comment]
https://discord.com/channels/182249960895545344/298827721604071425/888105359917600818
