### ISSUE TITLE
Unslaughterable Chickens in Carriers

### ISSUE THREAD

**Issue by KoboldCommando** [goonstation/goonstation#5659]
[BUG]

**Describe the bug**
If you attempt to slaughter a chicken that's inside a chicken carrier, it will give you chat messages as if you slaughtered it, and will sometimes produce blood, but the chicken remains intact.  If you then take it out, you can continue to attempt to slaughter, but it never actually becomes meat chunks.

**To Reproduce**
1. Acquire a chicken carrier with a dead hen inside (you monster)
2. Set the carrier on the ground
3. Hit the hen through the carrier with a chainsaw or other butchering implement
4. Notice the messages saying you skin then slaughter the hen
5. Notice a lack of actual changes
6. (optional) remove hen from carrier, attempt to slaughter again, notice no meat

**Expected behavior**
Either you should be able to successfully skin and slaughter a chicken while it's in a carrier, or you should be prevented from attempting.

**Comment by UrsulaMejor** [comment]
Looks like this works now. Sov probably fixed it!
