### ISSUE TITLE
Sleeper agent callout broken

### ISSUE THREAD

**Issue by Alexalmighty502** [goonstation/goonstation#5685]
[BUG]

**Describe the bug**
When a sleeper agent callout is activated it calls out numbers every minute or so causing it to be extremely dragged out.
Most likely caused by #5658.

**To Reproduce**
1.Play on the goon servers
2.have a sleeper agent event activate
3.notice that it states a number every minute or so.

**Expected behavior**
the event taking about 15 seconds or so instead of 10 minutes
**Screenshots**
N/A

**Additional context**
This seems to specifically be public server related because it would've been easily noticed on a private server pre merging

**Comment by flappybatpal** [comment]
https://github.com/flappybatpal/goonstation/blob/ff9e23a7c3a529328b800dde0a682644d0967868/code/modules/events/sleeperagent.dm#L200

This sleep needs to be outside the for loop
