### ISSUE TITLE
Civilian cyborgs can't deposit things in their produce satchels onto tables

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#5686]
[BUG]

**Describe the bug**
A produce satchel used by a human can dump its contents onto a table if you clickdrag it onto said surface, cyborgs cannot do this but they could in the past

**To Reproduce**
1. Fill a cyborg produce satchel
2. Get a table
3. Click drag the satchel onto the table
4. The contents are not dumped, there also isn't a message telling you that cyborgs can't do this so it does not seme intentional

**Expected behavior**
You can dump satchel contents like a human would

**Screenshots**

**Additional context**

**Comment by frawhst** [comment]
b275cb1f8c70a14e2ee9fee4e28ef2167b9902b4
