### ISSUE TITLE
Cyborgs (and maybe AIs) can put an item near them into a fryer regardless of how far it is from them

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#5687]
[BUG]

**Describe the bug**
You can click drag anything that would fit into a deep fryer as a cyborg if the item in question is besides you

**To Reproduce**
1. Find a deep fryer and something else that fits into it
2. Move away from the deep fryer while keeping the other item close
3. Click drag the item onto the fryer
4. The item gets fried

**Expected behavior**
You can only fry things while you're close to the deep fryer

**Screenshots**

**Additional context**

**Comment by Studenterhue** [comment]
Hopefully fixed by 671143a
