### ISSUE TITLE
SecHud icons hide revolutionary status (as a rev)

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#5708]
[BUG]

**Describe the bug**
While wearing sechuds as a rev/headrev, the sechud icons such as arrest status and contraband cover other rev's icons, making them hard to distinguish.

**To Reproduce**
1. Be rev, wear sechuds
2. Look at another rev
3. If they're holding contraband or are set to arrest, you won't see they're a rev until you take the glasses off.
**Expected behavior**
Either the rev icon layers over the sechud icons, or both appear in some sort of stack.

**Additional context**
Has led to me beating up some fellow revs while trying to stay aware of who's implanted. Oops.

**Comment by MetricDuck** [comment]
Oddly, it looks like it's deliberately coded like that - see arrest.dmi
```
if (arrestState != "*Arrest*") // Contraband overrides non-arrest statuses, now check for contraband
				if (locate(/obj/item/implant/counterrev) in H.implant)
					if (ticker.mode && ticker.mode.type == /datum/game_mode/revolution)
						var/datum/game_mode/revolution/R = ticker.mode
						if (H.mind && H.mind.special_role == ROLE_HEAD_REV)
							arrestState = "RevHead"
						else if (H.mind in R.revolutionaries)
							arrestState = "Loyal_Progress"
						else
							arrestState = "Loyal"
					else
						arrestState = "Loyal" 
```
