### ISSUE TITLE
Manta Detective Office wrong tile

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#5724]
[BUG - TRIVIAL]

**Describe the bug**
In the carpeted room in the detective's office, one of the tiles under the desk is still hardwood. It is the only tile like this in the room, so it's clearly an error.

**To Reproduce**
1. go to manta detective's office
2. look at the tiles under the 2-tile wide desk with the camera monitor and cassette players

**Expected behavior**
entire room to be carpeted

**Screenshots**
This is from goonhub, but I noticed it in game a day or two ago.
![image](https://user-images.githubusercontent.com/22992007/129205581-a26fda11-7b3a-44bf-84e5-2935fccab691.png)

**Comment by virvatuli-gh** [comment]
fixed in [00a408c](https://github.com/goonstation/goonstation/commit/00a408c47ac725ad99d323c6b97cc7b068ebe109)
