### ISSUE TITLE
Odd north-facing zippo in-hand sprite

### ISSUE THREAD

**Issue by Zonespace27** [goonstation/goonstation#5730]
[BUG]

**Describe the bug**
When facing north with a zippo in your left hand with the zippo being off, there will be two stray pixels near your right hand.

**To Reproduce**
1. Obtain zippo
2. Face north
3. Have the zippo in your left hand

**Expected behavior**
There not to be hand-extending stray pixels.

**Additional context**
I was using the golden zippo, but it has the same in-hand as the regular zippo.

**Comment by virvatuli-gh** [comment]
fixed in [38fad0b](https://github.com/goonstation/goonstation/commit/38fad0bdf6e864be8c05920c9b0779ba0b66609f)
