### ISSUE TITLE
Coffee carafes showing contents several times

### ISSUE THREAD

**Issue by shrimpboom8** [goonstation/goonstation#5742]
[BUG]

**Describe the bug**
When examined, coffee carafes show their contents several times in a row (e.g. "It is half full of an opaque, dark brown-colored liquid.It is half full of an opaque, dark brown-colored liquid.It is half full of an opaque, dark brown-colored liquid.")

**To Reproduce**
1. Brew coffee with any of the coffee makers aboard the station
2. Remove the carafe from the coffee maker
3. Examine the carafe. 

**Expected behavior**
The contents message should only be displayed once

**Screenshots**
![coffee](https://user-images.githubusercontent.com/31083792/129469392-fa7c6a8b-5186-439d-9ab2-bcd5f4c949e0.png)

**Additional context**
I found this with the one in Cog1 security, but I presume it works on all of them. I do not know if this applies with spectroscopic goggles.

**Comment by flappybatpal** [comment]
This is happening to a bunch of stuff, doesn't seem to be a whole lot of logic to why. Investigating.

**Comment by flappybatpal** [comment]
Here's something fun, this appears to be impossible.

reagent containers do a single call of get_description()
https://github.com/goonstation/goonstation/blob/7a216b5f39e71cfc65ea60374da6e9436a7c4281/code/modules/chemistry/Chemistry-Tools.dm#L88

get_description() does a single call of get_inexact_description()
https://github.com/goonstation/goonstation/blob/7a216b5f39e71cfc65ea60374da6e9436a7c4281/code/modules/chemistry/Chemistry-Holder.dm#L890

get_inexact_description() returns a single string
https://github.com/goonstation/goonstation/blob/7a216b5f39e71cfc65ea60374da6e9436a7c4281/code/modules/chemistry/Chemistry-Holder.dm#L929

No looping, no recursion, nothing to construct a repeat contents list.

**Comment by Tarmunora** [comment]
Could not reproduce

**Comment by flappybatpal** [comment]
Still occurs on live

![image](https://user-images.githubusercontent.com/70909958/130284311-500e73a2-7ef4-4a99-acf9-a0a230818bc2.png)

**Comment by Tarmunora** [comment]
maybe fixed as of 7306a0b then????
