### ISSUE TITLE
Werewolfs can't grab players

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#5755]
[BUG]

**Describe the bug**
As a werewolf, I attempted to aggressive grab a few people, but each time it said I had to remove their mask first.

**To Reproduce**
1. Become a werewolf
2. Grab someone using the grab intent
3. Attempt to upgrade the grab
4. Be stopped by whatever mask they are wearing

**Expected behavior**
I know that in order to choke out someone, you have to remove their mask, but I'm pretty sure simply being able to upgrade your basic grab doesn't require this.

**Comment by Alexalmighty502** [comment]
WW grabs are always aggressive grabs so this isn't a bug

**Comment by PrimeNumb** [comment]
Werewolf grabs use legacy behavior. Unintuitive but not a bug.
