### ISSUE TITLE
CE objective on Donut 3

### ISSUE THREAD

**Issue by fallenScion** [goonstation/goonstation#5757]
[BUG]

**Describe the bug**
CE objective on Donut 3 was to make sure the furnaces were active at end of round. Donut 3 as far as I know is singularity based and doesn't have furnaces.

**To Reproduce**
1. Go to Donut 3
2. Be CE
3. Get objective
4. Be confused

**Expected behavior**
Get an objective that is possible to complete.

**Screenshots**
N/A cause lack of thinking

**Additional context**

**Comment by Azrun** [comment]
Furnaces ordered from Cargo should be sufficient.  It is a little odd though.
