### ISSUE TITLE
Wrestler popup wiki link creates unclosable window

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#5760]
[BUG]

**Describe the bug**
When you spawn as a Wrestler, a rare antagonist, the popup contains a link to the wiki. If you click this link, it actually opens the wiki page within the popup, rendering it unable to be closed,

**To Reproduce**
1. Spawn as Wrestler
2. click the link on the word 'wiki'
3. be unable to close window, at least without nerd shortcuts

**Expected behavior**
I was expecting the link to open the page in my default browser.

**Screenshots**

**Additional context**
This may have workarounds, but I was not bold enough to try alt+f4. probably dumb, since i had to restart anyways to remove the window...

**Comment by FlameArrow57** [comment]
Was fixed
