### ISSUE TITLE
The main chatlog is gone.

### ISSUE THREAD

**Issue by gopherman465** [goonstation/goonstation#5769]
[BUG]

**Describe the bug**
The main chatlog is missing.

**To Reproduce**
1. Connect to server.
2. The chatlog is missing.

**Expected behavior**
The chatlog is not missing.
(I would try to poke around and find out why but anything that would tell me anything requires said missing chatlog.)

**Screenshots**
![Cursed](https://user-images.githubusercontent.com/89278501/130293050-9c5706c3-3649-40cd-9621-a75e6709e1bd.png)

**Additional context**
Recently updated to BYOND 514 as directed by prior login attempts and most recent discord news.

**Comment by Zonespace27** [comment]
I've gotten this bug before, restarting my game and waiting usually fixes it

**Comment by gopherman465** [comment]
I have tried that, unfortunately no dice, reinstalling BYOND now

**Comment by gopherman465** [comment]
Unfortunately reinstalling has not appear to have fixed it

**Comment by Xkeeper0** [comment]
Looks like the solution was clearing IE's cache/cookies/storage. Open IE (windows key + run, `iexplore`) then settings and just clear it all.

![image](https://user-images.githubusercontent.com/1077535/130302893-23e44aef-bc07-4f30-89cb-2e5734c6e199.png)
