### ISSUE TITLE
Radio chat filter not filtering for future messages

### ISSUE THREAD

**Issue by Connie-Dun** [goonstation/goonstation#577]
[BUG]

**Describe the bug**
When you use a chat filter, it hides messages of the selected category as expected, but then doesn't filter later messages even while the filter is active.

**To Reproduce**
1. Have a chatlog with the relevant sort of message, e.g. combat text.
2. Turn on the chat filter for that sort of message.
3. Notice it correctly removes previous instances of the sort of message.
4. Create a further message of that sort and notice it does not filter out.

**Expected behavior**
Filters filter out later instances of the type of message.

**Screenshots**
A message before the filter is applied.

![](https://cdn.discordapp.com/attachments/544752070306168835/706931665217257482/unknown.png)

A message after the filter is applied. Note that we still see the whispertext because it is regular speech, not radio talk. As expected, the radio talk is filtered out.

![](https://cdn.discordapp.com/attachments/544752070306168835/706931690358177873/unknown.png)

Saying a message over radio while the filter is still active. It does not filter it out as expected.

![](https://cdn.discordapp.com/attachments/544752070306168835/706931707474870278/unknown.png)

**Additional context**
On the round I learned of the issue, I encountered it with combat logs. However, I was not able to replicate it while testing. On neither the original round nor the test round was I able to replicate it with the regular speech filter.

**Comment by ZeWaka** [comment]
unable to reproduce for all filters

**Comment by ZeWaka** [comment]
able to reproduce for just radios

**Comment by ZeWaka** [comment]
only able to reproduce for radios.
