### ISSUE TITLE
Using the spectroscopic googles returns an error

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#5770]
[BUG]

**Describe the bug**
Using the spectroscopic goggles to view chems returns /list.

**To Reproduce**
1. Equip spectroscopic goggles
2. Look at your tea
3. Notice it's full of /list

**Expected behavior**
Seeing what chems are actually in the container, not /list

**Screenshots**
![2021-08-20](https://user-images.githubusercontent.com/87689371/130303754-3966ff21-5ea9-4b84-be44-a83cf6968557.png)

**Additional context**

**Comment by Tarmunora** [comment]
fcc943a should have fixed
