### ISSUE TITLE
Medibot Mobs Can Inject Outside Their Injection Radius

### ISSUE THREAD

**Issue by KB2222** [goonstation/goonstation#5773]
[BUG]

**Describe the bug**
Medibot mobs are capable of injecting their chemical payload while you are outside of their 3x3 area, and the action bar will not cancel when you leave either.

**To Reproduce**
1. Be Attacked by a Medibot mob 
2. Leave the usual injection radius
3. Still get injected with their chemicals, despite being outside of their 3x3 radius

**Expected behavior**
Once you leave the injection radius, their action bar _should_ cancel, and they'll no longer inject you.

**Screenshots**
None
**Additional context**
The specific kind of medibot I am referring to are the ones spawned during disaster rounds, and some other places.

**Comment by Tarmunora** [comment]
Those kinds of medibots will not cancel their inject action if you leave range, instead they will try to get back within range, and failing that will spew the chems they would have injected into the air as smoke

**Comment by KB2222** [comment]
Didn't see any smoke powder cloud, my bad. I'll be closing this issue.
