### ISSUE TITLE
Medical Director has improper permissions

### ISSUE THREAD

**Issue by arch-linux** [goonstation/goonstation#5777]
[BUG]

**Describe the bug**
When the medical director spawns in his office (Cogmap 1), in his locker is a tranquilizer gun. If you pick this weapon up, you are immediately attacked by the securitron stationed in medbay. 

This is due to the Medical Director not spawning with weapon rights -- if the intent is for the medical director to be able to utilize the weapon in his locker then his permissions should reflect this.

**To Reproduce**
1. Spawn as Med Director.
2. Open Locker -> pick up tranq gun.
3. Get tackled by every securitron in radius.
4. Become furious.

**Expected behavior**
I expected to be able to utilize the tranq gun when required, maybe even carry it in my inventory until its needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/7141078/130337527-6952fa1c-5d06-4995-aa43-802f705acbf9.png)

**Comment by mordent-goonstation** [comment]
Unless I'm seriously mistaken, this is a feature. Devs, feel free to re-open if you disagree.
