### ISSUE TITLE
Television-style Security Camera monitor changes appearance when disassembled

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#5791]
[BUG - MINOR]

**Describe the bug**
The TV-style security camera consoles seen in places such as the detective or janitor office appear to just be reskins of the standard monitor, at least on manta. This means a screwdriver can be used to begin disassembling them. Doing so will cause them to revert to the normal computer-style security camera monitors.

**To Reproduce**
1. Go somewhere with the security camera monitors that look like TVs, such as manta detective's office.
2. use a screwdriver on the monitor and wait, as you would when disassembling a terminal.
3. see error

**Expected behavior**
While I found this when trying to see if I could move the console around, in retrospect the expected behavior is that using a screwdriver simply fails to do anything other than hit the monitor.

**Screenshots**
![image](https://user-images.githubusercontent.com/22992007/130396767-ea912b1f-3aa3-416f-b1e2-696a94e05aee.png)

**Additional context**
I only tested this on Manta. Monitors such as the ones in other detective offices were untouched.

**Comment by MatheusIsNotAvailable** [comment]
This happens because these are just the camera computers with a different icon
