### ISSUE TITLE
Spacebucks Mail Order sends you to azone on Manta

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5799]
[BUG]

**Describe the bug**
Having an existing Mail Order delivery spacebucks purchase on Manta sends you to the requisitions azone.

**To Reproduce**

**Cannot reproduce locally due to lack of map changes!**
1. Have existing mail order purchase from a previous round
2. Map is Manta

**Expected behavior**
Get delivered to cargo.

**Comment by Supermichael777** [comment]
Also occurs on ocean if large numbers of people pick it

I suspect its because you get pushed/thrown into the export area
