### ISSUE TITLE
sleeping is impossible

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#580]
[BUG]

**Describe the bug**
the sleepin verb is missing from the local tab when near a bed, this makes getting rid of food poisoning impossible
**To Reproduce**
1. stand on bed
2. try to sleep
3. see error

**Expected behavior**
i need my sleep damn it

**Comment by mordent-goonstation** [comment]
If you buckle yourself to the bed and press "Rest" and wait a little bit you should fall asleep. If that's not the case feel free to add to this bug report!

**Comment by trerri** [comment]
it's even quicker with *faint, never knew about the sleep verb
