### ISSUE TITLE
C-Saber Nerf or Bug?

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#5802]
[BUG]

**Describe the bug**
Was rampaging, shameful me. Ran into someone and I got shoved. Being smart, and apparently old fashion, I turned my C-Saber off, and then went to go baton them.
They shoved me again, so, my Saber TURNS ON, WHEN OFF, AND SMACKS ME IN THE FACE. I then took out a barrier, and they shoved me again, and my Saber turned ON AGAIN, and smacked me in the face.

**To Reproduce**
Be a power gamer and put the C-Saber on your arm, because why get disarmed and lose 7tc by a defib?
Have the C-Saber off, and allow someone to shove you.
C-Saber, that was off, for cautionary reasons, turns on and smacks you in the face.
Immediately become confused, as to why its turning on, and if it turns on when shoved, why doesn't it turn off?

**Expected behavior**
Turn off my C-Saber for safety reasons, switch to a different hand to do something, and not have it turn on when its off and rip me to pieces.

**Screenshots**

**Additional context**

**Comment by BatElite** [comment]
I believe c-saber arms turning on when shoved is a deliberate thing

**Comment by ThatFiveGuys** [comment]
Mechanic could be better but not a bug
