### ISSUE TITLE
Organ damage taken from lasers with thermal resist

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5805]
[BUG]

**Describe the bug**
Being shot with lasers while having thermal resist causes no brute/burn damage but still damages your organs.

**To Reproduce**
1. Create a tdummy
2. Give it the thermalres bioeffect
3. Blast it repeatedly with an egun on lethal
4. Check the health for internal injuries

**Expected behavior**
No organ damage

**Additional context**
I'm not sure if energy weapons should even do organ damage with or without thermal res.  It could be a distinction between kinetic and energy, to compensate for the ammo usage concerns that energy doesn't have to worry about.

**Comment by flappybatpal** [comment]
@Tarmunora What do you think on this one?

**Comment by Tarmunora** [comment]
Now that the gene doesn't give full resistance to BURN damage, this is Less Glaring:tm: of an oversight
