### ISSUE TITLE
Disappearing Spy PDA item entry

### ISSUE THREAD

**Issue by Connie-Dun** [goonstation/goonstation#581]
[BUG]

**Describe the bug**
Sometimes the items a spy needs to claim disappear from the spy PDA menu.

**To Reproduce**
1. Look at your steal-menu as a spy.
2. Notice a missing item maybe?

**Expected behavior**
The items should all say what they are, not be invisible.

**Screenshots**

![](https://cdn.discordapp.com/attachments/383743035894267905/707031207942029322/unknown.png)

**Additional context**
The item miiiight have been destroyed - I think it was possibly an heirloom drinking glass, but not sure - in which case you'd expect something like the entry to disappear entirely.

**Comment by pali6** [comment]
I don't see any way how this could happen. Could it be that the particular bounty slot was empty from the start or are you sure there was something there before?

**Comment by flappybatpal** [comment]
It would have been good to know for sure if it was definitely a trinket or limb (could be worked out by the number of trinkets).

The menu is put together when you access the PDA and pulls information from game.active_bounties, which is only made at the bounty update times (every 25 minutes). Things aren't deleted from it even if the item is crushed or equivalent so it should still hold a name. The spy code also checks trinkets/limbs exist at the time they are added as a bounty.

Don't think we can progress on this without more information.
