### ISSUE TITLE
Botanical Ghost Critters

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#5820]
[BUG]

**Describe the bug**
Ghost critters can pick up the garden trowel which is a 5 damage item.

**To Reproduce**
1. be ghost critter (cockroach is what i know what works)
2. find trowel
3. pick up trowel

**Expected behavior**
not be able to pick up 5 damage item

**Additional context**
if they cant pick up the tiny hammer they shouldnt be able to pick up a garden trowel

**Comment by Yellow-Mushroom** [comment]
Sad, I love being able to do all my botany as a ghost critter :(
