### ISSUE TITLE
You can pull yourself to a cryogenic healing pod through thindows

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#5825]
[BUG]

**Describe the bug**
You can pull yourself to a cryogenic healing pod, even if there is a thindow blocking your way

**To Reproduce**
1. have a healing pod next to a cloning pod
2. drag and drop your sprite to the cloning pod
**Expected behavior**
The way is blocked so this shouldn't be possible

**Screenshots**

![image](https://user-images.githubusercontent.com/25270027/131220476-275bb032-654b-4106-b20a-aae290bb97b7.png)
This is from donut 2. I was able to drag and pull myself to the healing pod from the spot marked in X

**Comment by Zamazenta** [comment]
I believe the same thing happens with lockers, although it is possible that has been patched by now.

**Comment by ThatFiveGuys** [comment]
Fixed by #8564
