### ISSUE TITLE
sensor pod

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#584]
[BUG]

**Describe the bug**
using scan feature of a pods sensors puts the part in hand while keeping it in the pod as well

**To Reproduce**
1. scan using pod sensor
2. part in hand
3. bee amazed at the magic

**Expected behavior**
i expect this not to happen.

**Comment by triacontakai** [comment]
Issue stems from this line of code in the scan proc in sensors.dm: https://github.com/goonstation/goonstation/blob/5d28692952b2f9d1e66a01e7df72654485147030/code/modules/transport/pods/sensors.dm#L337

This calls updateDialog() defined in obj.dm, which causes `C.mob` to pick up the item: https://github.com/goonstation/goonstation/blob/a04e5e5bb8ad45245cb32981c2f765b829890cea/code/obj.dm#L259-L263

I'll see if I can go about fixing this
