### ISSUE TITLE
Strange bug when getting monkey cloned

### ISSUE THREAD

**Issue by TonyRegrave** [goonstation/goonstation#5840]
[BUG]

**Describe the bug**
I had previously died during the round and decided to Respawn. After successfully re-entering the game as a new character, I briefly went about my business, before being yanked out of said new character into a monkey body. It seems the medstaff decided to monkey clone my previous character's brain, and it somehow pulled me out of my new character into my old one once more. My second character became Braindead and after some more cloning shenanigans I once again became my first character.

**To Reproduce**
1. Die.
2. Respawn and make a new character.
3. Have your previous brain put into a monkey body.
4. Have the monkey body cloned.

**Expected behavior**
Normally, a monkey cloning should only work if the player is still around as a ghost, and if the player has left or respawned, the brain shouldn't have a consciousness to be scanned into the cloner, from my understanding.

**Comment by frawhst** [comment]
fixed
