### ISSUE TITLE
System update shows incorrect amount for slot machines

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#5860]
[BUG]

**Describe the bug**
Hitting one of the large amount winnings on a slot machine displays the wrong win amount in the system announcement. This is strictly a bug with the amount announced, you actually do earn the correct amount.

**To Reproduce**
1. Play the slot machines.
2. Hit a winning that gives a system announcement.
3. Notice it says you earned 0 credits.
4. Be confused!

**Expected behavior**
The system announcement should display the correct amount.

**Screenshots**
![image](https://user-images.githubusercontent.com/84296283/131607673-14032950-8057-4431-8bb0-ecc710ceb434.png)

**Comment by zjdtmkhzt** [comment]
I was unable to reproduce.
![image](https://user-images.githubusercontent.com/35579460/131722930-fe78136f-2538-4933-8941-14a404f28be2.png)

**Comment by blackrep** [comment]
> I was unable to reproduce.
> ![image](https://user-images.githubusercontent.com/35579460/131722930-fe78136f-2538-4933-8941-14a404f28be2.png)

Issue is specifically with `Big Winner`, the announcement is made before the amount is set correctly:
https://github.com/goonstation/goonstation/blob/16bb9c3fee73a88a58708eef394ca373d53dda24/code/obj/submachine/slots.dm#L167
