### ISSUE TITLE
Guardbuddy arrests don't show the perp's name

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#5866]
[minor]

**Describe the bug**
When a guardbuddy cuffs someone they send out a PDA message similar to what securitrons do. It doesn't properly display the name of the person being detained. I don't really get why it doesn't work though. (code/modules/robotics/bot/guardbot.dm line 2004)
**To Reproduce**
1. Get a PDA that gets guardbuddy mailbot notifications (research director's at least, dunno what else)
2. Anger a guardbuddy and let them detain you
3. See bad message

**Expected behavior**
For the name to show up

**Comment by zjdtmkhzt** [comment]
![image](https://user-images.githubusercontent.com/35579460/131701412-67694d29-3a6a-47f8-be10-12f403eb79d2.png)
This seems to work fine for me, did you do anything weird?

**Comment by BatElite** [comment]
I haven't been doing weird stuff but now that vsc decided breakpoints work again I think I found out what's going on: The single-case arrest task actually just drops itself from the buddy's task list when `drop_arrest_target` is called and leaves the variable itself intact, when the others don't. Very smartly that proc is guaranteed called before the message code needs to do stuff with it. It depends on what task the buddy has internally whee

(Which incidentally means that when it works properly it's using a disposed task but shhh)
