### ISSUE TITLE
Eyespider lacks xray vision

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#5871]
[BUG]

**Describe the bug**
The changeling underling, Eyespider, supposedly has x-ray vision according to the antagonist tips pop-up. However, eyespiders do not have this ability. There is a [part of their code specifying the eye can "see forever"](https://github.com/goonstation/goonstation/blob/a8af69b76e9907b8f2148e6b9d9916cb9423bc27/code/mob/living/critter/changeling_critters.dm#L333) but I lack the code knowledge to understand if this intends to give xray. 

**To Reproduce**
1. Be released as an eyespider after being absorbed
2. fail to have xray vision, despite the popup saying otherwise.

**Expected behavior**
Eyespiders having all their listed abilities, or for xray vision to not be listed as an ability.

**Screenshots**

**Additional context**

**Comment by MeggalBozale** [comment]
The mark ability also seems to have no effect from an eyespider's perspective, I am trying to understand why the code isn't working but I'm really unfamiliar with dm. My only thought is that some variables that _should_ be set aren't set, or some variables were set improperly.
