### ISSUE TITLE
Blobs can't attack pods with a hotkeyed attack if their blobghost is adjacent to the pod.

### ISSUE THREAD

**Issue by lyralvideo** [goonstation/goonstation#588]
[BUG]

**Describe the bug**
If a pod is next to some blob, and the blob overmind attempts to attack the pod while using a hotkey, AND the blob overmind ghost is next to or on top of the pod, the attack will not work. specifically, nothing happens, the attack does not go on cooldown, bp is not spent, no splashes occur, nothing.

**To Reproduce**
spawn some tiles out in space somewhere
spawn a pod next to them
become blob, jump to the space tiles, spawn in, position blob overmind next to pod, assign attack hotkey, hold down hotkey and mash attack on that pod. it will do nothing.
if you move away, you will get expected pod mashing behavior.

**Expected behavior**
the pod to get fucking smashed regardless of position of blob overmind.

**Screenshots**
https://i.gyazo.com/ca70810ff218a5299486e716da4297fd.png <- screenshot me trying to attack a pod with my ghost next to the pod. This is after about 15 solid seconds of spamming shift click on it. as you can see, it is undamaged. (ignore the wreckage, that was caused by previous pods while testing)

https://i.gyazo.com/3656cb2c9b1185d108c23462c8c598ac.png <- screenshot of me beating the shit out of the pod after moving my ghost just one tile away.

**Additional context**
spaceman-discussion thinks this may be caused by the pod context menu. its worth noting that blob overminds can get a "nothing in cargo hold!" message by click dragging the pod to an adjcent overmind, so obviously some forms of pod interaction meant for humans is working with overmind.

**Comment by Tarmunora** [comment]
@mybluecorners Possibly caused by pod multicontext menu?
