### ISSUE TITLE
Macho Man is tweaking out

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5930]
[BUG]

**Describe the bug**
Macho man vibrates constantly.

**To Reproduce**
1. Admin yourself into macho man
2. Vibrate

**Expected behavior**
Macho man has built up far too much of a tolerance to be visually affected.

**Additional context**
This breaks some animations like Atomic Piledriver.

**Comment by Sovexe** [comment]
idk if jitter is intended or not but the animations are fixed c35ad92958f129b5e72e78ccc83e048044aa4e94
