### ISSUE TITLE
Vampire and Holy Water

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#5938]
[BUG]

**Describe the bug**
Holy water was nerfed to have a maximum damage done. Holy water thrown from a pitcher appears to bypass this in some fashion? I've been splashed with holy water since the change. It puts you down pretty bad, but it doesn't crit you. Holywater in a pitcher does way more.

**To Reproduce**
1. Be vampire
2. Get splashed with holy water from a beaker, check damage.
3. Get a pitcher of holy water thrown at you, which injects the water straight into you and does bogus damage.
4. Die.

**Expected behavior**
Holy Water follows the damage cap in all states.

**Screenshots**

**Additional context**

**Comment by BatElite** [comment]
Tested (via graviton-launched pitcher) and it does 110 burn, which is the cap on holy water damage and so I don't think this is bugged. I'm guessing the average holy water pourer doesn't apply enough to hit the cap?

**Comment by RGBDeadSilent** [comment]
For some reason I was under the impression that the damage cap was 90, but you're right its 110 burn damage max, so instant crit.
