### ISSUE TITLE
Heads of staff jobs are not rev heads silly centcom

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#5940]
[BUG]

**Describe the bug**
Captian appeared in the "printout" that gives hints to possible match types, specifically it appeared in the one that hints at revs

**To Reproduce**
1. have it be rev mode?
2.  there be only captian?
3. dont know of a wat to actually reproduce this bug

**Expected behavior**
heads of staff not show up in this hint thing

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/132534089-1dd8aadc-a328-428b-88d4-d107479abb33.png)

**Additional context**
Based on our intelligence, we are 43% sure that if true, someone doing the job of Captain on your station may have been brainwashed at a recent conference, and their department should be closely monitored for signs of mutiny.

**Comment by Zonespace27** [comment]
Printouts are purely random, with no basis on the current round. Personally, I find it funny that Centcomm can believe that the captain's responsible for inciting a revolution.

**Comment by frawhst** [comment]
funny enough to leave in imo
