### ISSUE TITLE
Errors on stimulant and janktank status expiry

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#5958]
[BUG]

**Describe the bug**
Both stims and jank tanks error when expiring.

**To Reproduce**
1. Inject /obj/item/stimpack or /obj/item/implanter/gang.
2. Wait for the status effect to expire

**Expected behavior**
No errors.

**Screenshots**
https://github.com/goonstation/goonstation/blob/db8975f94cca5ba369dca451838a849f305c8ca8/code/modules/status_system/statusEffects.dm#L640
![image](https://user-images.githubusercontent.com/70909958/132831841-c2d034a4-9ca5-4eca-a0e7-a5f781b4c188.png)

https://github.com/goonstation/goonstation/blob/db8975f94cca5ba369dca451838a849f305c8ca8/code/modules/status_system/statusEffects.dm#L1190
![image](https://user-images.githubusercontent.com/70909958/132832898-b64d099c-df41-4c9a-b8ce-1cbf89c0f47d.png)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/09ae741c6130afb6618452775267cdfe55959bcf
