### ISSUE TITLE
As Wraith, Revenant'd a Werewolf corpse after they died. 20 seconds later we both crash and switch souls.

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#5975]
[BUG] [MAJOR]

**Describe the bug**
After following around the rampaging Werewolf for 10 minutes or so, they had gotten caught and were being beat by sec offs west of the chapel of COG2. About 5 seconds after they died, give or take a second or two, I decided to Revenant their corpse to have some fun. I was able to Revenant the corpse, but my character model changed to some weird human sprite, and flashed to another sprite a second after it. I had two Antagonist Ability bars overlapping, one for Werewolf and one for my Original Antagonist, Wraith. I went along and tried to kill the people who killed the Werewolf, but the game was getting choppy and starting to glitch out, with things not working the way they should.  I couldn't use any of the abilities, including the overlapping ones, my attacks as a revenant were acting like regular human attacks, not doing very much damage at all, no werewolf/rev damage at all. Even the stun baton I took from the officer when we were fighting wasn't functioning properly, with it need multiple presses to flip or turn on, which was probably from the performance issues.

I ended up then crashing after fighting for a few seconds, to the point the game just froze and whitescreened. When I closed it and rejoined, I was an Observer and getting a warning Popup that I may be banned if I continue to play since my Ckey had already joined the round and played. What was weirder is the player of the dead werewolf transferred to MY wraith, and my original body was completely deleted from the round, probably including the Werewolf. I had no body to return to and so I roamed around as observer for most of the round, or in the bar until I rolled gunbot and ran around for 3 minutes.

There is a secondary bug here, where the player who got switched into wraith.. I think might have inherited their point score from Werewolf and had it transfer to the wraith. They had 16,000 points or so, from what they said.

**To Reproduce**
1. Spawn as wraith with a werewolf in the round round start.
2. Get enough points to Revenant and pray that the werewolf meets a tragic fate.
3. Revenant the body and become a twisted amalgamation of Were and Reve, forced to live forever as the Werereve.
4. Don't actually live forever, and get beaten to death.
5. Byond goes into Cardiac Arrest and dies, so you close Dream Seeker and reopen it through byond
6. Have your consciousness switched with the person who was inside the corpse of said werewolf, and have them transfer to your wraith body/become a new wraith?

**Expected behavior**
Revenant the Werewolf, having access to at the very least the Revenant abilities, but ideally both ability sets. Rampage as a super antagonist Ghost Werewolf type horror. Noted that the body I used Revenant on was in werewolf form, but I might have been reverted back to human form when I took over their corpse. Looking at the chat log, there's a chance the werewolf abilities could have been active, but just didn't work since I was human, although i couldnt see my points anywhere either. I also inherited their active cooldowns for their used abilities. 

**Screenshots**
https://i.gyazo.com/106905f7add5ba544c069538f1045892.png *Shot of me active as werewolf revenant
https://i.gyazo.com/fa0008cbd8ff561912d0c3717e99e630.png *Observer ban warning and dead chat
https://i.gyazo.com/c6eee3802aff43c145174ce2e44e64dd.png *Quick ahelp report
https://i.gyazo.com/0b4757dc98861229cb6f048b7599f338.png *PostCredits jank

**Additional context**
Wow haha, its a bummer this once in a lifetime antag opportunity was blindsided by an unfortunate and totally unforeseeable bug, it's tragic! I don't think i'll ever recover emotionally, i'm devastated and I don't know if I can go on! Although, maybe a token of antagonistic status could assist me in the recovery effort of this truly tragic attempt on my life that has left me scarred and deformed. ;^)

**Comment by MetricDuck** [comment]
From discord:
![image](https://user-images.githubusercontent.com/86617057/154978612-8acd9c7a-1db8-492f-9c21-fd8a8b0c73fd.png)
