### ISSUE TITLE
Even being uncursed doesn't cure Cluwning

### ISSUE THREAD

**Issue by Sartorius7** [goonstation/goonstation#5994]
[BUG]

**Describe the bug**
Being hit with a bible will remove the cluwne equipment, but the cluwne status carries over

**To Reproduce**
1. Get cluwned by a wizard
2. Get cured by a chaplain
3. Still suffer from the cluwne ailment 
4. Ask an admin to help and not even they can remove the cluwning

**Expected behavior**
Cluwning is reversable by chaplains

**Additional context**
May be related to cloning not carrying over traits? (Known bug)

**Comment by MetricDuck** [comment]
Tested today, I was able to cure a wizards cluwne spell by hitting them with a bible a bunch of times: it removed both cluwneing around and the clumsy ailments, as well as the cursed clothing. It didn't change the name from cluwne though (see #3497). Possible this got fixed already?

I would note you currently cant cure: admin cluwne, contract cluwne or painbow cluwne with the chaplain.
