### ISSUE TITLE
Chugging when your reagent container is full runtimes

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6017]
[BUG]

**Describe the bug**
Chugging when your reagent container is full runtimes (also you chug infinitely). also probably happens when you use an auto injector on someone whos reagent container is full.

was also chugging blood from a pitcher as a vampire. dunno if that factored into it

**To Reproduce**
1. get full reagent container of a preferably slow depleting chem
2. chug something
3. jug longer than thought possible

**Expected behavior**
runtime bad, no run times

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/b0a4097a18a3745919d7c2d58921e1bc1ea4134d probably fixes
