### ISSUE TITLE
Ghost Critters/drones can't go through firedoors

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6034]
[BUG]

**Describe the bug**
When playing as either a ghost critter or a ghost drone, you can't go through doors if a fire lock is active over them.

**To Reproduce**
1. Be a ghost critter/drone
2. Find an active fire door
3. Attempt to go through it
4. Can't

**Expected behavior**
I believe ghost drones and critters at one point could go through fire doors

**Comment by BatElite** [comment]
Side effect of #5974 setting cant_emag on firedoors. Figures that that variable getting used as a stand-in for "this is a special don't-fuck-with door" in a bunch of code would cause an issue
(Note that AFAIK the non-perspective firedoors never let critters pass, also before that PR)

**Comment by BatElite** [comment]
Fixed an while ago, not exactly sure when though
