### ISSUE TITLE
helmets with lights are always lit when dropped

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#6040]
[BUG]

**Describe the bug**
If you turn on and off a helmet with a light on it, such as engineering spacesuit helmets, hard hats, or security helmets, the helmet will always have the light on once dropped

**To Reproduce**
1. Obtain a hard hat, engineering spacesuit, security helmet, etc
2. turn it on while wearing it, later turn it off
3. take the helmet off and put it down, such as on a rack or just dropping it
4. helmet will be casting light like a flashlight, despite being off earlier

**Expected behavior**
Helmets to only cast a light if the light was turned on

**Additional context**
This is most easily noticeable in action on dark rounds on oshan, where engineers will surely wander off into the dark, and will frequently ditch their helmet in engineering once they get back.

**Comment by flappybatpal** [comment]
They also continue to work in backpacks. Helmet/flashlight/PDA light seems like a prime candidate for component.

**Comment by BatElite** [comment]
directional lights (flashlights & helmets, not PDA AFAIK) are already a component

**Comment by FlameArrow57** [comment]
Seems to not be an issue anymore
