### ISSUE TITLE
Detective isn't spawning with his Id

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6046]
[BUG]

**Describe the bug**
Detectives are not spawning with their id on them

**To Reproduce**
1. Choose to spawn as a det
2. Spawn as det
3. Lack an id

**Expected behavior**
To spawn with a detectives id

**Screenshots**

**Additional context**
Not sure if it's because I bought the bee egg spacebux purchase, but I did notice the previous rounds det also didn't have an id on him

**Comment by DisturbHerb** [comment]
Did you wake up in a locker or crate? Stowaways don't get issued an ID.

**Comment by Wisemonster** [comment]
No, I spawned in my office without those traits

**Comment by ThatFiveGuys** [comment]
Assumed to be fixed considering time gap and impact that would be noted if this bug was still around
