### ISSUE TITLE
Handcrafted katanas can be turned into a commander's scabbard using medal rewards

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#6050]
[BUG]

**Describe the bug**
You can turn a handcrafted katana into a commander scabbard by claiming medal rewards, giving it more damage and a different special.

**To Reproduce**
1. Obtain handcrafted katana
2. Place handcrafted katana into commander's scabbard sheath
3. Claim "NT-SO Commander Uniform" or "CENTCOM Administrator Uniform" medal rewards
4. Katana gets turned into a commander's scabbard.

**Expected behavior**
You can't put a handcrafted katana into a commander's scabbard sheath.

**Additional context**
Issue seems to be on line 1288 of misc_weapons.dm (?)

**Comment by pali6** [comment]
Should be fixed by dfa01f9af83a513ecb9e78b95befdbb8d8a0dd75
