### ISSUE TITLE
Ghost spawn antag werewolf has captin level ID

### ISSUE THREAD

**Issue by Supermichael777** [goonstation/goonstation#6054]
[BUG]

**Describe the bug**
As a ghost, accepted prompt to late-join as antag, werewolf specifically. when spawned in noted i had gold all access id and generic pda, despite being dressed as an assistant.  Map was OSHAN LAB.

**To Reproduce**

1. Be a ghost in the ghost garden
2. accept spawn prompt
3. Get spawned as werewolf

**Expected behavior**
Id and PDA mach uniform

**Comment by Gerhazo** [comment]
Can't seem able to reproduce locally by forcing the event to happen.
The code itself also explicitly does a staff assistant equip.
