### ISSUE TITLE
Camryn Stern figurine wrong path

### ISSUE THREAD

**Issue by MetricDuck** [goonstation/goonstation#6061]
[BUG]

**Describe the bug**
I wanted to look at the figurine code & icons out of curiosity but it looks like the "\improper Camryn Stern" donator figurine is pathed bad.

**To Reproduce**
1. Open goonstation/code/modules/items/gimmick/figurine.dm.
2. Notice "\improper Camryn Stern" datum is under /datum/figure_info/patreon/vicky, which is the previous entry.
3. See error.

**Expected behavior**
Camryn Stern figurine be labelled good - /datum/figure_info/patreon/camrynstern.

**Screenshots**
N/A

**Additional context**
Haven't done any testing, no idea if this means vicky is unobtainable or camrynstern is unavailable (or maybe neither and it just *works*?).

**Comment by pali6** [comment]
Fixed by 22cb995
