### ISSUE TITLE
Stutter speech from getting caught in a door stuck on borgs

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6070]
[BUG]

**Describe the bug**
When a cyborg gets caught in a door as it closes, the resulting stutter lasts on the borgs permanently 

**To Reproduce**
1. Be a cyborg
2. Get caught in a door and take damage
3. Develop a permanent stutter

**Expected behavior**
Either to not get a stutter, or for the stutter to go away

**Comment by frawhst** [comment]
fixed in #6490
