### ISSUE TITLE
Can't block on the same tile as seats that you can't chairflip off of (Stools)

### ISSUE THREAD

**Issue by Zonespace27** [goonstation/goonstation#6071]
[BUG - MINOR]

**Describe the bug**
When you try to block on a tile with a seat that you can't chairflip off of, you just... don't block at all.

**To Reproduce**
1. Create seat you can't flip off of (bar stool is one)
2. Try to block
3. See error

**Expected behavior**
To be able to block while on the stool's tile

**Comment by BatElite** [comment]
New combat meta emerges

**Comment by frawhst** [comment]
59e8c37
