### ISSUE TITLE
hos-old in worn_js_rank is not resprited for human resprite

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#6078]
[BUG - MINOR]

**Describe the bug**
The sprite in the title, hos-old, is not resprited for human resprite. This sprite is obtainable in-game by using the medal reward for "Dead or alive, you're coming with me" as HoS.

**To Reproduce**
1. be hos
2. use medal reward for old sec jumpsuits
3. jumpsuit fails to fit character

**Expected behavior**
All obtainable sprites should fit properly.

**Additional context**
Since I'm not a HoS and medal rewards don't work on local easily, I haven't actually been able to empirically recreate this. However, I have no reason to believe the code in rewardsLocker is incorrect, and even if it is, it is clearly _intended_ to be obtainable.

**Comment by Nihisohel** [comment]
Can confirm that the sprite is not updated to resprite, meant to write this bug report ages ago

**Comment by Sir-Mora** [comment]
#6085
