### ISSUE TITLE
Putting people inside me similar to the infamous juggling glitch with disposal chutes

### ISSUE THREAD

**Issue by rmeaper** [goonstation/goonstation#6122]
[BUG]

**Describe the bug**
An extension of bug #6072. If you build a linked disposal chute (as described in #6072) in your hand while there is a person in the unconstructed unit, you put them inside of your body. Their voice comes out as "muffled human inside remeaper" and there is no way to get them out short of admin intervention.

**To Reproduce**
Build 2 trunk pipes next to each other with a disposal chute on both. 
Deconstruct one disposal chute.
Have an entity enter the still constructed disposal chute and flush
Build the unconstructed chute in your hand. 
You now have an entity inside of you.
???
Profit

**Expected behavior**
The flush to have kicked them out of the pipe.

**Screenshots**
I![image](https://user-images.githubusercontent.com/91395489/135309285-25c29ce0-c8b5-4c18-89ef-0675a54afa6e.png)

**Additional context**
This is really funny and I think that it could be worked into a feature, but ATM is broken as hell.
Also the deconstructed unit becomes a bulky item, rather than a tiny one.

**Comment by penny64** [comment]
Deconstructed items are supposed to be bulky, only new frames are small

**Comment by MetricDuck** [comment]
Fixed in 80dc21f
