### ISSUE TITLE
Fabricated satchels always spawn with internals and a crowbar past the cutoff time

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6127]
[BUG]

**Describe the bug**
After the time in which latejoins spawn with guaranteed internals and a crowbar, fabricated satchels (from the clothing fab) also receive those items in their box.

**To Reproduce**
1. Wait some time (varies for RP and classic I believe)
2. Print satchel
3. Get free crowbar/o2

**Expected behavior**
No free shit

**Comment by ThatFiveGuys** [comment]
This works for crew lockers too btw.
