### ISSUE TITLE
Depowered engine control console turns into a torpedo tube

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6153]
[minor]

**Describe the bug**
what the fuck

**To Reproduce**
1. Go on manta
2. Turn off engine control room APC
3. See torpedo tube???

**Expected behavior**
No torpedo tube

**Screenshots**
![image](https://user-images.githubusercontent.com/67879783/135733460-8a2988b8-d866-4c89-9bfa-fcf357984109.png)

**Additional context**
Turning the APC back on sets the sprite back correctly.

**Comment by Vaskritaya** [comment]
pretty sure this is being caused by there being no nuclearcomputer0 and it looking for a nonexistent iconstate, then defaulting to that. working on it
