### ISSUE TITLE
I "observed" my corpse as i was gibbing.

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#618]
[BUG]

**Describe the bug**
I "observed" my corpse as i was gibbing, which locked up my client making me restart it, spawned back in as an observer rather than my ghost.
was suiciding using the russian hootvolver, must have clicked on self to fast resulting in this.

**To Reproduce**
1. was suiciding using the russian hootvolver (or regular, wasnt paying attention), must have clicked on self too fast resulting in this.
2. i dunno, there probable multiple ways this can happen. i dont have much to go on here.

**Expected behavior**
not what happened in the describe bug section

**Comment by Tarmunora** [comment]
Related to #659 ?

**Comment by pali6** [comment]
Most likely fixed either by 745dc4806a3f69087de0fae2e92f6d97072b6d4b or by the fact that the delete queue is now disabled by default. Please scream loudly if that's not the case.
