### ISSUE TITLE
Chanegelings Fail objectives if not in control when the shuttle reaches centcom

### ISSUE THREAD

**Issue by Supermichael777** [goonstation/goonstation#6189]
Was a hivemind member. Master handed off control to AFK near EOR. Brought master body to centcom. Master registered as body destroyed. Round ended ~9:15 PM EDT 9/5/21  on nightshade 1.

**Comment by nefarious6th** [comment]
duplicate of #5621

**Comment by TheTyrant25** [comment]
duplicate of #5621 and presumably fixed by #13571
