### ISSUE TITLE
Hellbound Zoldorf Candidate Not Deleted

### ISSUE THREAD

**Issue by iod6239** [goonstation/goonstation#62]
**Describe the bug**
If you sell 100% of your soul to Zoldorf and then try to become the new Zoldorf, when you get sent to hell your old body says it vaporizes (intended) but instead just strips down and still stands there, braindead. (Not intended.)

**To Reproduce**
1. Sell 100% of your soul to a Zoldorf.
2. Sign a Zoldorf contract.
3. Give it to a Zoldorf which can pass on its status.
4. Anybody else nearby will see the bug above occur.

**Expected behavior**
The old body should be stripped and deleted, not just stripped.

**Comment by Adharainspace** [comment]
i cant find the code where this is handled. maybe @AwkwardDryad could help me out with locating where i should fix this?

**Comment by AwkwardDryad** [comment]
check zoldorf.dm or vending.dm

its in the booth() proc somewhere. i dont exactly know how much of my original code survived the 2016-2020 port though.

**Comment by flappybatpal** [comment]
As far as I can see it's here

https://github.com/goonstation/goonstation/blob/5900a26c2036d0c5b579da1d6bb1f66285e40636/code/obj/zoldorf.dm#L229

**Comment by flappybatpal** [comment]
Tested this on live, the player is deleted. was confirmed by another player asked to observe.

As far as I can see the player is deleted in /mob/proc/make_zoldorf and it seems to work just fine.
