### ISSUE TITLE
clean bots dont take reagents no more

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6210]
### Labels

[BUG]

### Description

you can no longer pour reagents into a clean bot

### Steps to reproduce

1. get beaker
2. put oil in beaker
3. click clean bot with beaker
4. be sad

### Expected Behavior

dump reagents into clean bot

### Additional Information & Screenshots

a change to clean bots made it so they dont mop up reagents and have them dumped into there content  (afaik this change was mostly due to oshan arrivals cleanbot) this had the affect of being unable to put ANY regents into them from an outside source. this also affected the antag critter clean bot.

**Comment by Tarmunora** [comment]
fixet
