### ISSUE TITLE
The emergency oxygen tanks of latejoining players sometimes explode violently upon spawning

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6215]
### Labels

[MAJOR]

### Description

Upon spawning past the extra-equipment cutoff, the pocket oxygen tank that late arrivals spawn with will sometimes detonate VIOLENTLY, gibbing the person.

### Steps to reproduce

1. Latejoin
2. Fucking explode

### Expected Behavior

Don't explode????

### Additional Information & Screenshots

Associated logs:
![image](https://user-images.githubusercontent.com/67879783/136638316-787dbaea-ffad-4c4a-9bbb-0abcb7116618.png)
![image](https://user-images.githubusercontent.com/67879783/136638354-397fc374-b670-431f-a5c6-0862c84109f2.png)

**Comment by Azrun** [comment]
Smells like a pooling/unpooling issue.

**Comment by Tarmunora** [comment]
should be fixed now that pooling/unpooling does not exist
