### ISSUE TITLE
If someone is in an admin sit, any ghost observe them by traveling to their name

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#6220]
### Labels

[BUG]

### Description

Title, this is may not be considered a classical bug, but I feel its best to report in case private information or other items ever gets shared from admin to player in physical means that a ghost could read.

### Steps to reproduce

1. Have a player self antag enough to get into an admin sit
2. Go to observe that player to the "Obersve" list ability ghosts get
3. Be a ghost and observing the whacky stuff that a player writes on a piece of paper

### Expected Behavior

I don't know if this is intended, but I feel like ghosts should not be allowed to observe players in admin sits

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/75814831/136647416-523a85e3-b186-4d2b-9028-1688d9182cd4.png)

**Comment by ZeWaka** [comment]
its fine
