### ISSUE TITLE
Hunters Spear, Glass Window behavior

### ISSUE THREAD

**Issue by RGBDeadSilent** [goonstation/goonstation#6245]
First, the format is gone! Wheres my step 1-2-3!

Throwing a Hunting Spear against a glass window does not hit the window, or the grate beneath it. Being able to do so would be a good way for the hunter to break in and out of places, but instead they'll have to do it like a staffie? Hunting Spear is 35 thrown damage by the way (Maybe it has something to do with the stun effect on the spear?)

Ways to produce.
1. Spawn in a hunting spear
2. Throw it against a window, no bonk, no chat message saying you've hit the window
3. Start code diving to figure out whats going on...?

Expected Behavior
1. Be trapped and want to break window.
2. Throw spear against window
3. Window breaks (eventually)

**Comment by flappybatpal** [comment]
They can rip open doors like werewolves.

**Comment by RGBDeadSilent** [comment]
Yes yes yes, i'm aware but i'm a staffie and I stole the cool spear and I want to break WINDOW. UNGA

**Comment by 112358sam** [comment]
I think I found the issue. The throw impact proc overwrites the knife's but does not call the original. I am testing a fix now.
