### ISSUE TITLE
You can't put nuclear ops into the cairngorm sleepers as a third party because anti-harm field won't let you grab them.

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#6278]
### Labels

[BUG] [MINOR]

### Description

Can't put injured or dying operatives into the sleepers on cairngorm because of the anti-harm field around 

### Steps to reproduce

1. Have an operative spawn with a bad mutation or dead, etc. (Oh no.)
2. Spend minutes trying to save them and bring them to the sleepers to put them in.
3. Oh no, can't grab them because anti-harm field.
4. They die and go boom.

### Expected Behavior

To be able to put them in the sleeper to save their life.

### Additional Information & Screenshots

https://i.gyazo.com/754de75d4d22660c9d5bec602cfa7287.png

**Comment by Gannets** [comment]
I'll remove the sanctuary zone from the medbay, makes sense.
