### ISSUE TITLE
TermOS Crash (PowerMonitor)

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#6280]
Error message gotten while checking the power monitor for the whole station, I'm pretty sure the RD was in the process of changing the power cell of an APC that was down to 0%.

> A fatal exception has occurred in the TermOS TGUI subsystem. The current application will be terminated. Please remain calm. Get to the nearest TermOS workstation and send a copy of the following stack trace to: https://github.com/goonstation/goonstation. Thank you for your cooperation. 
>  Script error.
>    at http://cdn.goonhub.com/tgui/tgui-common.bundle.js?serverrev=2e1a4195874b87899d2826e54a0e42be0d04aaad:0
> User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
> State: {"ckey":"garash","interface":"PowerMonitor","window":{"key":"[0x201d7c2]-main","size":null,"fancy":1,"locked":0}}
> 
> Copyright 2046-2053 Thinktronic Systems, LTD.

**Comment by ThatFiveGuys** [comment]
Fixed by #4339
