### ISSUE TITLE
Singularity Inconsistencies. 

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#6287]
### Labels

[BUG] [MAJOR]

### Description

A Singularity only functions when hooked to the initial field generators. It will no longer generate power if it is put into a second containment, and the sprite will continue to grow even if the killbox is contained (Not fully tested, but i've done quite a few runs of it. It may just eventually break out, but i haven't had that happen in testing).

### Steps to reproduce

1. Have contained singularity, any size within 3x3 containment to 11x11
2.  Try to do a larger setup, or multiple singularities and successfully contain the singularity(ies) in the larger setup, via setup, etc. (Note, with multiple singularities, you can start them up in the initial containment but the power they generate will be super janky and not make any sense, hovering around the absolute lowest a singulo can gen.)
3. Singularity no longer outputs proper power, if any at all. It will also grow outside of the field generators, despite them being active. 

This is technically not a "bug", but moreso wacky code and breaks the rules it puts down as a baseline, which is that the singularity doesn't go past the field generators if they have power. Also no longer generating power is a bummer, and makes it so you can't do any experiments with singularity.  

### Expected Behavior

If able to contain the singularity with a second field, it attaches to those and resume its normal power function and does not grow past the field generators.

### Additional Information & Screenshots

Massive singularity not generating energy: https://i.gyazo.com/200ebed11e94b92c5c371be16786e76f.png
Singularity bypassing containment #1: https://i.gyazo.com/9f5e1c2e74b24efeb09f0b2ffa1aa325.png
#2: https://i.gyazo.com/a50597fe69c6d73f323f6b588a54fc73.png
#3: https://i.gyazo.com/45177b2d9475126f6889448718f60511.png 
You can see that despite it being over many things, its box to kill/delete things is still contained. (Probably.)

Here is one with 5 1x1 singularities and what happens to the SMES/Power Output
https://i.gyazo.com/7bca942bca49c9f75a0a4dc155907fcf.png
https://i.gyazo.com/f629158981abf38d772095446f1a6268.png

Here is another layout, same premise as above. This one didn't even start power, so maybe i fucked up wiring? I don't see how tho, and theres an apc. Idk, power fucking weird, make wires standard 2day.
https://i.gyazo.com/e5acc3abf07a306a683486b477a3023e.png
https://i.gyazo.com/ca51d49905c130207932775af362964b.png

This is a supermassive not eating things while in containment. Technically two.
https://i.gyazo.com/476ad8bc599fbd66a1c2db46a5f87d2e.png

Here's one that is just pure jank and i'm not sure why, but just the one contained all of them until power broke because of ??, no clue. https://i.gyazo.com/3013e890e6ba222c4d86fd9034d0194f.png

And here is one that is just for fun, bubsium affects singularities. 
https://i.gyazo.com/4315df7584459a4bd7a1dad2f8e87ce5.png

**Comment by ThatFiveGuys** [comment]
Fixed
