### ISSUE TITLE
Sparks from nanomed and the like no longer set off welding tanks

### ISSUE THREAD

**Issue by ThatFiveGuys** [goonstation/goonstation#6291]
### Labels

[BUG]

### Description

Title, sparks from nanomed (and presumably sparks in general), no longer set off longer set off welding tanks. 

### Steps to reproduce

1. Summon nanomed nearby welding tank
2. See sparks but no fire
3. Repeat a few times to confirm

### Expected Behavior

For fire to occur!

### Additional Information & Screenshots

This bug was probably introduced when heat capacity changes was introduced and the like, I miss this behavior was more fun then electrifying every door.

**Comment by mordent-goonstation** [comment]
This seems like a feature. @UrsulaMejor ?

**Comment by UrsulaMejor** [comment]
I think the new sparks have special code to preserve the fire flashing. Old sparks don'; although,  if you preheat the fuel or use the sparks repeatedly enough they'll likely go off anyways

**Comment by millicentjwi** [comment]
i've been a victim to this when bashing the cargo door in donut 3 (which happens to be right beside a welding fuel tank) and accidentally blowing up the place

it was fuckin HILARIOUS, please keep this in

**Comment by flappybatpal** [comment]
[BatElite](https://github.com/BatElite) is correct, this still occurs it's just random and requires the temperature increase to occur more than once or the tank to already be hot.
Considering welding tank explosions can delete rwalls (what!) I think the current behavior is fine.
