### ISSUE TITLE
Revolution gamemode needs an algorithm for picking the number of revheads.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#6299]
**How revolution gamemode works currently:**
Look for people with the revhead preference enabled. If there are more than 3, get only 3 of them. If there's none, pick one random player without the preference.

**What this means:**
Theoretically if only one person has the revhead preference enabled, or if no one has it enabled, there will be one person picked as an alone revhead in a round that could have even 90 people on it.

**How it should work and is how most gamemodes do it:**
First, based on some algorithm/function, the number of revheads is decided.
Then it looks for people with the revhead preference and tries to get that many, filling in the blanks with people without the preference. (handled by get_possible_enemies(ROLE_HEAD_REV, amount), where the amount should be the number of expected revheads decided on earlier. At the moment the call looks like get_possible_enemies(ROLE_HEAD_REV, 1), hence the earlier mention of a single alone revhead).

**Comment by ThatFiveGuys** [comment]
Oh yeah done actually
