### ISSUE TITLE
The quantum telescope tends to break the game randomly

### ISSUE THREAD

**Issue by AkkoRishtar** [goonstation/goonstation#630]
[BUG]

**Describe the bug**
When opening a pop-up window related to the quantum telescope (either the telescope window itself or a window for the location/asteroid discovered) there is a seemingly random chance of breaking ALL of the pop-up windows in the game, including the job choice window you get when joining a round late. 
Unfortunately I have not found any pattern as to when or why it happens because sometimes I can use the telescope normally for most of the round, only to get the bug towards the end or, sometimes, I might get the bug at the very first time I attempt to interact with the telescope.

**To Reproduce**
Steps to reproduce the behavior
Play a round as a miner, using the telescope for all of the asteroids you pull to the mining magnet. to my experience, the chances of you not encountering the bug are extremely slim

**Expected behavior**
not risking losing a big chunk of the game's functionality when trying to find starstones

**Screenshots**
I will make some the next time I encounter this

**Additional context**
This has been tested only on the public release, not on the official goon server.
This has only been tested on Cogmap 1
The last version I have tested this on was downloaded on May 9th, the day I am making this thread.
The only changes I made were:
making a map override (Cogmap1)
removing a reference to a non-existant file supposed to be located in the +secret folder (wouldn't compile otherwise) 
making myself the host.

**Comment by triacontakai** [comment]
Can you elaborate on what happens when all pop-up windows break? i.e. what happens when you try to open them?

**Comment by AkkoRishtar** [comment]
It opens the pop-up and shows a browser-like "check your connection" screen with an option to reload it, you should be familiar with it since it sometimes happens during normal gameplay except, in this case, reloading it doesn't help. 
I'll try reproducing it tomorrow so I can post more details and screenshots. Sorry for not doing it now, I'm in Europe and it's nighttime here.

**Comment by AkkoRishtar** [comment]
I'm closing the issue because I  stopped getting the error. My guess is that I was doing something really specific to get the bug and I have no Idea what It was
