### ISSUE TITLE
Conveyor belts transfer their momentum to to objects on top of them when unpowered during ?Movement?

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#6311]
### Labels

[BUG][MINOR]

### Description

I'm still not 100% on the exact cause, but crates and other items will retain the momentum of the conveyor if power goes out while they're on the conveyors and/or moving on them. This causes crates to travel in the direction the conveyor was going forever, and they become a massive pain to transport and organize. And you can't rebuild crates with sheets, so it's very not kosher.

### Steps to reproduce

1. Order items and have them arrive onto the conveyor.
2. Power goes out while many items are on the conveyor or moving in some way while the conveyor is active
3. Crates retain the momentum of the direction they were originally going towards, despite no movement from conveyors.

### Expected Behavior

Crates fully stop without stealing momentum/travel, and no longer move.

**Comment by frawhst** [comment]
3f1b88898fcf3541e0cebaa09b274da93e8c4b1c
