### ISSUE TITLE
Inconsistent interactions with thindows

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#6313]
### Labels

[BUG][MINOR]

### Description

You're able to phase through thindows if you click drag into a container on the other side.

### Steps to reproduce

1. line up against a thindow with a locker/disposals/etc
2. Click drag yourself into it.
3. Be on the other side.

### Expected Behavior

Thindows block this.

### Additional Information & Screenshots
Can skip ahead like 15 seconds, recorded a bit earlier than intended. 
https://streamable.com/p5podk

**Comment by ThatFiveGuys** [comment]
Fixed by #8564
