### ISSUE TITLE
Use of some characters results in their HTML code

### ISSUE THREAD

**Issue by Arthur-Holiday** [goonstation/goonstation#6326]
I wasn't really able to replicate this consistently but sometimes when you say something like ```'```it outputs ```&#39;```(the symbol's HTML code) instead

![Captura de Tela (222)](https://user-images.githubusercontent.com/74429191/137512773-c8cad8de-02af-4bd6-bab1-851565788a95.png)

**Comment by ZeWaka** [comment]
fixed iirc
