### ISSUE TITLE
Fixing Captain's Antique Laser Gun with artifact power cell converts the cell into a default 200pu cell

### ISSUE THREAD

**Issue by Mechanelize** [goonstation/goonstation#6328]
### Labels

[BUG]

### Description

When crafting/fixing the Captain's Antique Laser Gun putting in an artifact as the power cell changes the artifact power cell into a normal 200pu non self charging power cell.

### Steps to reproduce

1. Attempt to fix Captain's Antique Laser Gun with an artifact power cell
2. Use any other small power cell to swap out the internal battery
3. Normal 200pu cell comes out instead of artifact power cell

### Expected Behavior

The Antique Laser Gun accepts the artifact power cell and uses its self-recharging abilities and retains its power capacity.

**Comment by zjdtmkhzt** [comment]
This has to do with the power cell component for energy guns automatically added the right cell of the type that is set in the "cell" var of the gun, I think. If someone else wants to make a fix for this, feel free, I may not be in the mood to change stuff that has to do with components in the near future.^^

**Comment by zjdtmkhzt** [comment]
seems fixed to me due to f7608b0b7b99fb72b42d4aa4f262fccefded940d!
