### ISSUE TITLE
Holding audio log in hand only records the speaker

### ISSUE THREAD

**Issue by Crystalwarrior** [goonstation/goonstation#6329]
### Labels

[BUG]

### Description

Using audio log when it's in your hands will only record your own speech.

### Steps to reproduce

1. Pick up audio log
2. Start recording
3. Ask another person to talk
4. Stop recording
5. Play it back
6. Only your speech will be recorded.

### Expected Behavior

I expected it to not make a difference whether I'm holding the recorder in my hands versus having it on the floor. It should function the same either way.

**Comment by DisturbHerb** [comment]
Per the wiki, this appears to be intended behaviour. Stinky, I know.

**Comment by Crystalwarrior** [comment]
> Per the wiki, this appears to be intended behaviour. Stinky, I know.

I mean even so, it can change. I can't think of any reasons not to make it more intuitive - what is the point of being intentionally unintuitive? I dunno the intent of this behavior but it's problematic, you guys agree with that right?

**Comment by Zonespace27** [comment]
> > Unintuitive? Maybe. Intended? Yes.
> 
> Question. Why?

It's meant so you can talk into the recorder without anyone else's messages being shown

**Comment by virvatuli-gh** [comment]
Intended functionality is not an issue, if you think it can be improved then that's a matter of making a PR to do so.
