### ISSUE TITLE
You can drop "Blocks'

### ISSUE THREAD

**Issue by Sovexe** [goonstation/goonstation#634]
**Describe the bug**
Blocks can be dropped and thrown

**To Reproduce**
1. Block
2. Drop or throw it

**Expected behavior**
Block is deleted when dropped or thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/33204415/81487317-920f1d80-9229-11ea-85a7-c3973530391e.png)

**Comment by mybluecorners** [comment]
resolved, recent dropped() fixes broke garbage collection / qdel for grabs
