### ISSUE TITLE
Orange-Aid half-cures blindness trait

### ISSUE THREAD

**Issue by Zonespace27** [goonstation/goonstation#6356]
### Labels

[BUG]

### Description

When drinking orange-aid, your blindness gets removed & readded every cycle, leading to you be able to see.
In addition (thanks Vask) nearsightedness gets removed too.

### Steps to reproduce

1. Take blind / nearsighted trait
2. Drink orange-aid
3. Remove VISOR / prescription glasses

### Expected Behavior

Orange-Aid and its chems shouldn't fix trait blindness

**Comment by Vaskritaya** [comment]
As you might imagine, this also occurs with nearsightedness.

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/306c4cf82cfc66676d0e6527313f0dca8c95ba0d
