### ISSUE TITLE
Chemicompiler (sorta) duplicates cyborg beakers

### ISSUE THREAD

**Issue by Smearfo** [goonstation/goonstation#6360]
### Labels

[BUG]

### Description

The chemicompiler ejects cyborg beakers onto the floor, while still keeping them in the cyborg's hands

### Steps to reproduce

1. Play as chemistry cyborg
2. Insert internal beaker into chemicompiler
3. Eject beaker from chemicompiler
4. Observe new quantum-entangled floor beaker

### Expected Behavior

For the chemicompiler to either return cyborg beakers back to the cyborg, or not accept them in the first place.

### Additional Information & Screenshots

The cyborg cannot use the hand beaker when too far away from the floor beaker, and can remove the floor beaker by storing the one in their hands
Along with this, the cyborg can also insert the same beaker into all of the chemicompiler's slots

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/cc8440134a92bb6fa66c05eea09c7a59e708b7a9
Cyborg beakers should no longer fit in the chemicomp - perhaps in the future it could work like the chemdispensers?
