### ISSUE TITLE
Inconsistent interactability with computers/machines for AI/cyborgs

### ISSUE THREAD

**Issue by mordent-goonstation** [goonstation/goonstation#639]
[BUG]

**Describe the bug**
Some computers/machines cannot be interacted with by the AI unless their AI eye is next to the computer/machine. Ditto for cyborgs (but not necessarily the same machines).

Confirmed for:
* Power Monitoring Computer (AI eye)
* Chemical/drink dispensers (can open interface but not interact with unless adjacent to as cyborg)

Feel free to comment with others.

**To Reproduce**
1. Be an AI/cyborg.
2. Notice that certain machines can have their interfaces opened from afar by not interacted with from afar.
3. Notice that certain machines cannot have their interface opened from afar.

**Expected behavior**
Consistency: if the interface can be opened from afar by either cyborgs/AI, it should be able to be opened from afar by both; if the interface can be interacted with from afar by either cyborgs/AI, it should be able to be interacted with from afar by both.

Note that if a cyborg can interact with something while adjacent (only), this does not necessarily mean the AI needs to be able to interact with it.

**Additional context**
Various checks at the start of either `attack_hand` or `Topic` calls are inconsistent. A utility macro/proc should be created to check for appropriate range/type (the current `in_range` proc is used for some things other than computers, e.g. IV stands, so while it could be tweaked to work better some regression testing would be needed) and used across the spectrum of computers/machines this applies to.

**Comment by zjdtmkhzt** [comment]
You can also open the atmos can GUI while not being next to the can, but trying to interact with any of the buttons will close the GUI instead of performing the action.

The telesci console can be used while not being next to it, but it seems that the information in the window is only updated if you are next to it.

**Comment by Azrun** [comment]
Looking into this.
