### ISSUE TITLE
Bald Trait's Wig Doesn't Match Hair Color On Roachs

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6404]
### Labels

[BUG]

### Description

The wig recieved from the bald trait does not match the color you set for your hair if you choose the roach trait

### Steps to reproduce

1. Make some hair
2. Choose the roach trait
3. Choose the bald trait
4. Spawn in
5. Notice hair isn't colored correctly

### Expected Behavior

To get a wig with the same color as my hair when I choose to be a roach

### Additional Information & Screenshots

![2021-10-22](https://user-images.githubusercontent.com/87689371/138507997-2ba30969-a1cf-48b0-b374-3c4733cf95a8.png)

**Comment by flappybatpal** [comment]
This is the same as lizards and due to the mutant_appearance_flags FIX_COLORS.
* FIX_COLORS clamps the RGB values of the customization colors betwen 50 and 190. Keeps them from getting too dark or oversaturated
