### ISSUE TITLE
MechComp Special Character Formatting Errors

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#6408]
### Labels

[BUG]

### Description

With certain components, special characters (namely: &'") seem to break, turning strings like &'" into `&amp;&#39;&#34;`. This heavily interferes with packets due to the addition of semicolons which break packets sent via MechComp.

### Steps to reproduce

1. Try to set a value or pass a signal with any of the following characters `& ' "` in a MechComp component
2. Notice that some Components will get angry and interpret your simple characters as formatting gibberish like `&amp;&#39;&#34;`
3. Be sad when it cuts off your packets and fucks with your ability to process and transmit messages

### Expected Behavior

Special characters should not turn into shit like &amp;&#39;&#34;

### Additional Information & Screenshots

The following components experience issues when trying to SET an internal value to any of the aforementioned Special Characters (e.g setting Send-Signal):
- Signal Builder Component
- Wifi Signal Splitter Component (Unable to directly confirm; did not go off when its trigger field was set to "' and the signal `"'=test` was passed through it)
- Signal-Check Component
- OR Component (Unable to directly confirm; did not go off when its trigger field was set to &'" and the signal &'" was passed through it)
- Toggle Component(? Uncertain about this one)
-  Button Panel (When inspected, the panel will correctly display the special characters, but will fail to properly format them when they actually send the signal)

The following were tested to NOT have these errors:
- Buttons
- AND Component
- Delay Component
- Pressure Sensor
- Relay Component

The following have issues with *transmitting* signals containing special characters:
- Radio Scanner Component
- Signal Builder Component

Notably, WiFi components do not experience issues transmitting nor receiving special characters. PNET components, however, have issues with transmitting and likely receiving special characters (Uncertain about receiving; tested with both a PNET comp and packet sniffer for receiving packets which both had incorrectly formatted characters outputted from the same signal)

This is PROBABLY all of the components with problems, but it's very likely that I missed one. But, all of the important ones are listed here. I tried to be as thorough as I could, despite how sleepy I am right now! (I also didn't go through all components, just ones that I remembered had fields that could be set and ones that could transmit values)

**Comment by MetricDuck** [comment]
Still a thing - whilst it screws up your regex components, in regular signals usage it doesn't actually affect the packets as they figure it out.

For the ampersands it's caused by:
In ie: the regexreplace it's caused by this line: `mod = strip_html(sanitize(html_encode(mod)))//U G H`
