### ISSUE TITLE
spritebug - Scorched grass tiles are black voids

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6421]
### Labels

[trivial]

### Description

When a grass tile is scorched, it becomes an unclickable dark void.

### Steps to reproduce

1. Scorch a grass tile (flamethrower probably works)
2. See issue

### Expected Behavior

Not this

### Additional Information & Screenshots

![grassbug2](https://user-images.githubusercontent.com/67879783/138587375-80ce6023-b796-4194-9ddc-b454eb1e1387.png)
![grassbug1](https://user-images.githubusercontent.com/67879783/138587377-29581933-d7f4-4c76-8847-9d8b45f8ad23.png)

**Comment by MetricDuck** [comment]
Fixed in #8699
