### ISSUE TITLE
TGUI (and potentially other things?) breaking locally after having too many images in browserassets.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#6426]
**Disclaimer: this only affects the game running locally**

### Description

Following 6d0b29a150ae71130e063bffb448dec156682a83, which added a bunch of nukeops radio callsign icons and to pair with it a bunch of images, TGUI stopped working locally for mysterious reasons, displaying only a white box.

After some manual testing, I found out that out of the 26 images added (for each callsign letter), if I deleted at least any three of them, TGUI would work again. Any less and it would refuse to load.

This wasn't limited to the callsign images, duplicating images in other folders would also cause this issue.

pali believes there might be some race condition and/or BYOND limitations at play, but isn't certain of what's happening exactly either.
**They've submitted a workaround in c312880ac7fb1c1953b705cd071d47f59e6b9722, but that doesn't fix the underlying issue** and might apparently and/or does result in other things not working/loading.

As mentioned, **this only affects the game running locally**, the live server grabs the resources from the CDN instead.

### Steps to reproduce

On a commit after 6d0b29a150ae71130e063bffb448dec156682a83 but (for easiest reproduction) before c312880ac7fb1c1953b705cd071d47f59e6b9722

1. Notice TGUI windows not loading.
2. Remove some images from the browserassets folder as was described earlier.
3. Notice TGUI windows loading again.

### Expected Behavior

Working properly without breaking after an arbitrary amount of files.

**Comment by ThatFiveGuys** [comment]
Im willing to bet this is fixed
