### ISSUE TITLE
The mining magnet only pulls in one square when there is no space.

### ISSUE THREAD

**Issue by keiyakins** [goonstation/goonstation#643]
[BUG]

**Describe the bug**
The mining magnet only pulls in one square when there is no space.

**To Reproduce**
1. Activate mining magnet
2. There's only one square.

**Expected behavior**
An entire asteroid, like normal

**Screenshots**
![image](https://user-images.githubusercontent.com/161285/81506398-9edc5180-92bb-11ea-88dc-ed404ebd200b.png)
(shown while it was pulling. Sorry. I would get a better one but I'm out at z5 now)

**Additional context**
It was during a round with no space, and that one square shows space... but one of the admins said that the effect should be purely visual so I'm reporting it as a bug.

**Comment by UrsulaMejor** [comment]
The space thing is likely unrelated; space was still there, just invisible.

**Comment by keiyakins** [comment]
I tested it a couple rounds later when there was space, and it works fine.
