### ISSUE TITLE
Rolling Fire Elemental in the Afterlife Bar does not bring you on-station

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#6458]
### Labels

[BUG]

### Description

Title, if you roll Fire Elemental (and I assume this would work for any antag critter) while in the Afterlife bar, you will not appear on station, but instead will be turned into one in the bar.

### Steps to reproduce

1. Go to afterlife bar (The literal bar with the ring & drinks, though testing other areas may help)
2. Get selected for antag critter (Fire elemental worked for me)
3. Notice you are the antag critter, but not on the station

### Expected Behavior

I expected to be teleported on-station to terrorize the station members at my own convenience.

### Additional Information & Screenshots

I experienced this while playing on the main server at a very high population (121 players!)  so this may have factored into it.

Screenshots should not be needed as I don't believe they would do much to help.

Exiting the bar in this state seems to trigger something to kill you before making you a ghost.

**Comment by frawhst** [comment]
c5ca610c558e5c8278dc211ee4f05fc21b85033b
