### ISSUE TITLE
Chest items are activated upon any interaction.

### ISSUE THREAD

**Issue by Smearfo** [goonstation/goonstation#6472]
### Labels

[BUG]

### Description

Surgically implanted chest items seem to activate upon any interaction with your sprite, when the wiki says it's only upon being attacked or farting.

### Steps to reproduce

1. Surgically activatable item into chest
2. Click on yourself, or have someone else click on you
3. Item activates, regardless of whether it was an attack or not

### Expected Behavior

For items to only activate via being attacked or farting, or for the wiki to reflect the current activation methods

**Comment by frawhst** [comment]
^
