### ISSUE TITLE
Antagonist cleanbot weirdness with water/steam

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6477]
### Labels

[BUG]

### Description

When you're a cleanbot and you wade through high water (or any high fluid pool, really) the reagents fill you up. This is understandable, but annoying, as it leaves no room for the Fun reagents. However, if the water boils off while inside you, it becomes a steam reagent which creates `fluid` tiles when you apply it to tiles.

### Steps to reproduce

1. Be cleanbot
2. Get water inside you with a high body temperature
3. Water "evaporates", remains inside you as steam
4. When cleaning tiles, `fluid` tiles are created

### Expected Behavior

Firstly, I didn't expect fluids to pour into me. Fairly funny though, so I can excuse it. Secondly, I would expect steam to either FULLY boil off (i.e. evaporate out of me) or just work without creating these were pseudofluids.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/67879783/139355918-7543b131-f918-4505-90ac-541f1b980ab4.png)

**Comment by 112358sam** [comment]
Found a potential fix, testing now.
