### ISSUE TITLE
Gwydoin Tranquilizer pistol isn't actually scilenced

### ISSUE THREAD

**Issue by Crackaduck** [goonstation/goonstation#6478]
Now I know its still considered one of the more powerful syndicate weapons, and that's the reason it's ammo was recently nerfed, however: The pistol remains a simple reskin of the brawen pistol, and the suppressor does nothing to actually make the weapon more silenced, and while I cant say this with confidence, but it seems to me almost as if the 9mm bullets it can fire/share with the brawen are more quiet than its normal shots. Ultimately I'd like to see it changed into a actually suppressed gun, and either use its own unique subsonic rounds, or have some sort of effect that dampens the audio played when its shot.

**Comment by virvatuli-gh** [comment]
Closing this because it's not really an issue (but an opinion) and the sound effect and aesthetic is more of a reference to Goldeneye than an actually suppressed weapon like the syndicate .22 (which sounds and acts actually suppressed).
