### ISSUE TITLE
Blood consumed from container never depletes as vampire

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#6488]
### Labels

[BUG]

### Description

Blood that you drink from a container as a vampire never depletes, forever showing on scanners and preventing consumption of other chemicals.

### Steps to reproduce

1. Be vampire
2. Find huge blood puddle
3. Scoop it up and drink it
4. The blood never depletes and eventually you reach chem limit

### Expected Behavior

The blood depletes like any other chemical would

### Additional Information & Screenshots

My character is a cow, possibly related since it has milk for blood? Maybe this is normal behavior? I play with all antags disabled so I only rarely get to play when its forced on late join.
![image](https://user-images.githubusercontent.com/25157685/139501764-db4c4699-1c3f-4281-8c90-0a16509be520.png)

**Comment by Tarmunora** [comment]
blood chem appears to have a depletion rate of 0. investigating

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/4c7e948de7730c52f92806b01e57e9b8a20a0d76
