### ISSUE TITLE
Noisey thing artifacts projecting sound far away from artifact

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#6498]
[trivial]
**Description**
Noisemakers for some reason are throwing their sound with the noisemaker in artlab (or wherever) and the sound playing in medbay, not around the artifact. I noticed this happening a couple rounds, where I'd be in medbay and hearing the sound but the noisemaker is in artlab. But when you go to artlab there's no sound coming from the artifact.

**Steps to reproduce**

- Activate noisemaker artifact
- Noise is projected ~30ish tiles to the right

**Expected Behavior**
Noise comes from the artifact

**Additional Information & Screenshots**
Video demonstration, artifact is in artlab and silent. When moving to medbay you hear the sound.
https://www.youtube.com/watch?v=cyq_x5tLt4s

Unrelated note: When I went to make this new issue it didn't give me the template for some reason.

**Comment by BatElite** [comment]
WRT the non-issue thing: I found the template doesn't happen if you go through the in-game bug report link

**Comment by MetricDuck** [comment]
Noisemaker artifacts have been removed with #8662
