### ISSUE TITLE
GPS takes you through space if you have the access needed to get to a location

### ISSUE THREAD

**Issue by Soldat778** [goonstation/goonstation#6499]
### Labels

[BUG]

### Description

The GPS will risk your life in order to get you to a location faster, even if you lack internals. Found on Cogmap 1.

### Steps to reproduce

1. Spawn as a job with maintenance access, such as a Janitor.
2. Use the GPS verb to locate a room that is across the map.
3. Find that the GPS may require you to go to the location in question through space.

### Expected Behavior

The GPS should not endanger your life just to get you to an area quicker.

**Comment by MetricDuck** [comment]
You could fix this by adding catwalks to the exclude list in the get_path_to() proc called in SomepotatosStuff (see also __std/pathfinding.dm), but I'm not sure if this is a bug or a feature. As it stands it DOES find the shortest path, and would the majority of players prefer speed or safety? Personally I'd lean to the former....

**Comment by ZeWaka** [comment]
wyci
