### ISSUE TITLE
Arcplating doesn't update the tooltip but does in fact update the stats

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#6504]
Stock armor tooltip: https://files.catbox.moe/jsug0i.png
Plated armor tooltip: https://files.catbox.moe/oeeyg5.png
Stats with stock armor: https://files.catbox.moe/4fqaz8.png
Stats with plated armor: https://files.catbox.moe/5aklqv.png

**Comment by frawhst** [comment]
fixed as of f14aae7
