### ISSUE TITLE
You can slip on smoke

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#6505]
### Labels

[BUG]

### Description

Smoked reagents, such as Miasma clouds and hotboxed cannabis are now slippy which does not make any sense.

### Steps to reproduce

1.  Smoke some shit
2. Run over it
3. You slip

### Expected Behavior

No slip

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25270027/139585559-260adaa0-aad8-40c9-9e55-f7f679525b79.png)
![image](https://user-images.githubusercontent.com/25270027/139585566-0a97367d-cd4c-4241-b2ec-cf79efa2e32c.png)

**Comment by pali6** [comment]
fixed
