### ISSUE TITLE
Right clicking breaks blob tutorial

### ISSUE THREAD

**Issue by Thor3005** [goonstation/goonstation#6511]
I was right clicking around when i got to the part in the blob tutorial where it said I could right click to move my camera, but suddenly i somehow lost my role.

**Comment by MetricDuck** [comment]
The blob tutorial area is surrounded by an insta-kill cordon, I was able to replicate this by clicking on the other side of the cordon & promptly dying. I got stuck as a ghost in the blob tutorial room.
