### ISSUE TITLE
Polymorph spell turned me into a bee without a sprite

### ISSUE THREAD

**Issue by imnotjames** [goonstation/goonstation#6517]
### Labels

[BUG]

### Description

The bee I was turned into via polymorph had no sprite and thus was invisible

### Steps to reproduce

1. Polymorph turned me into a `greater domestic space-bee`
2. Bee invisible

### Expected Behavior

Bee visible

### Additional Information & Screenshots

I would send a screenshot but it was an empty sprite so I'd just be showing you the floor.

Occurred on https://goonhub.com/rounds/118485

**Comment by 112358sam** [comment]
I wonder if this may be a conflict due to non-admins being banned from becoming bees. Testing may then fail to reproduce the result since you are an admin on your own local server.

**Comment by imnotjames** [comment]
Also I confirmed with another player that I was indeed I visible but when I picked up items you could see the tiny holding products sprites.
