### ISSUE TITLE
The examine text when hovering over cyborgs shows "Cyborg" instead of their name

### ISSUE THREAD

**Issue by Merlin1230** [goonstation/goonstation#6518]
### Labels

[BUG]

### Description

When you hover over a cyborg while holding alt, the name shows up as Cyborg rather then their name

### Steps to reproduce

1. Wonder what a cyborg's name is
2. Hold alt and hover over said cyborg
3. Be confused when their name just shows up as "Cyborg"

### Expected Behavior

To show their name

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/76177064/139604962-66d70237-7735-4a46-a763-4a20501d29fd.png)

**Comment by pali6** [comment]
Fixed I think
