### ISSUE TITLE
pda interupts

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#652]
[BUG]

**Describe the bug**
pda messages interupt input

**To Reproduce**
1. recieve pda message
2. be amazed how it stops inputs 
3. be sad

**Expected behavior**
it not to interupt inputs

**Additional context**
most noticable when your writing a pda message and recieve one. the writing box becomes unfocused.

**Comment by pali6** [comment]
Does this happen when you have the PDA window closed?
For the PDA window being open I don't think there's any good way to fix it because of byond's clientside limitations.

**Comment by RSG250** [comment]
god its been forever, i think it did but not 100% sure. i just remember that it when i received a pda message (after sending one) while moving about i would get stopped the new pda message would interupt me

and i think open the PDA up? if its in a spot to do so, not sure on this part cause its been awhile
