### ISSUE TITLE
Flavor messages are visible to observers

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6526]
### Labels

[minor]

### Description

Drink flavor descriptions are visible to everyone nearby, not just the drinker.

### Steps to reproduce

1. Have someone else sip something near you
2. You see what they taste!

### Expected Behavior

Flavor is only visible to the drinker.

### Additional Information & Screenshots

Forgot to take one.

**Comment by zjdtmkhzt** [comment]
oof
