### ISSUE TITLE
Range on wifi components seems broken, making them almost unusable.

### ISSUE THREAD

**Issue by Vermonto** [goonstation/goonstation#6540]
### Labels
[BUG]
### Description
Wifi components seem to have a range of 0 now were as they didn't before. It looks as if they aren't sending any packets whatsoever but if you stand on the same tile as them with a packet sniffer, they'll pop up. But any further and you won't detect anything, nor will anything else.
### Steps to reproduce

1. Place a wifi component.
2. Leave it at default settings or change the frequency if you'd like.
3. Hook up a button/any input to the "send radio message" input.
4. Set the send signal to a valid packet.
5. Set up a wireless packet sniffer of some kind to the same freq as the wifi comp, a PDA works the best probably.
6. Press the button and you won't see any packets appear on your packet sniffer.
7. Stand on top of the wifi component and do the same thing, you will see the packet you made get sent.

The above can also be demonstrated with doors or any other packet receiving device.
### Expected Behavior
The wifi component to be able to send a packet a reasonable distance away, I don't remember the exact range.
### Additional Information & Screenshots
Here are some screenshots of my recreating the bug with a door and a wifi component:
The wifi component is 1 tile away from the door and the door doesn't open when the button is pressed.

![1tile](https://user-images.githubusercontent.com/68172154/139801954-36b5c70e-1086-4080-b3b8-dd66f499c57a.png)
The wifi component is 0 tiles away from the door (under it) and the door opens when the button is pressed.
![0tiles](https://user-images.githubusercontent.com/68172154/139801983-321920fd-63ed-4fb0-85a7-4c6f6c948a12.png)

**Comment by penny64** [comment]
@pali6

**Comment by pali6** [comment]
God damn it, I bet it's the same bug as with network cards.

**Comment by pali6** [comment]
People be like "why even make a distinction between 0 and null" >:(

**Comment by pali6** [comment]
Fixed by cb7fbde2a64f4dbf68c29422fab30526a881af8b
