### ISSUE TITLE
Love this one- Photos of computers glow like computers

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6541]
### Labels

[trivial]

### Description

Photos of computers will glow in the dark like regular computer screens.

### Steps to reproduce

1. Take a photo of a computer
2. Throw it in a dark room
3. Glow!!

### Expected Behavior

No glow

### Additional Information & Screenshots

![compu1](https://user-images.githubusercontent.com/67879783/139794651-961fb590-d3ea-48cd-921b-0755d34da500.png)
![copmu2](https://user-images.githubusercontent.com/67879783/139794655-4100d1e2-0701-4eb7-9d11-9b5dc9e02b7d.png)

**Comment by 112358sam** [comment]
Probably related to #4724

**Comment by ThatFiveGuys** [comment]
Also fixed
