### ISSUE TITLE
Using a screwdriver on a television turns it into a Security Cameras console

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#6555]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. Use a screwdriver on a television
2. Wait until it turns into a console
3. Use the screwdriver one more time
4. It becomes Security Cameras

### Expected Behavior

It stays as a television

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25157685/139970525-e25929e2-61a6-4e8d-9129-fb3ee791f931.png)

**Comment by 112358sam** [comment]
Closing since this is a repeat of #5791
