### ISSUE TITLE
Hair overlay from bald trait on character setup screen does not go away

### ISSUE THREAD

**Issue by Arthur-Holiday** [goonstation/goonstation#6578]
### Labels

[BUG]

### Description

Loading a profile that has the trait does not make the  wig overlay go away after you load another profile

### Steps to reproduce

1. Load profile with bald trait and see wig overlay
2. Load another profile that doesn't have it
3. wig overlay still there.

### Expected Behavior

For the wig overlay to go away

**Comment by zjdtmkhzt** [comment]
That's weird.
The preview actually literally puts a wig on the character, but it should go away when it rebuilds for the new character.
