### ISSUE TITLE
Multiple descriptions on examining light fixtures

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#658]
https://github.com/goonstation/goonstation/blob/d0fde98ee22d5643d5bf808541eeef7e67847764/code/modules/power/lighting.dm#L80-L80

For some reason, when examining obj/machinery/light, descriptions are outputted twice.
This is not present on other obj/machinery objects such as mail chutes.

**Comment by UrsulaMejor** [comment]
Doesn't happen when you're a ghost

**Comment by tloy-x** [comment]
It has to do with `base_state`, which for some reason contains the description as well as the icon state. On inspection, `desc `AND `base_state` are both outputted. I fixed this by commenting out the `desc` of every object that also had a `base_state`. I recognize that this is probably not an acceptable fix, but I don't know what else I could do. Maybe is `base_state` didn't contain the description?
