### ISSUE TITLE
Typing while in your corpse is visible to alive players

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#6581]
### Labels

[BUG-minor]

### Description

If you start talking in deadchat while in your corpse, the typing bubble will appear on it

### Steps to reproduce

1. Die
2. Be in your newfound corpse
3. Type about how you just died to dead people
4. Notice your typing bubble appears and is visible to everyone

### Expected Behavior

I cannot vaguely communicate that I'm still online to the living through this bug

### Additional Information & Screenshots

Experienced it on goon main, it does disappear if you leave corpse/stop typing

**Comment by MeggalBozale** [comment]
Not sure how to label this as a minor bug

**Comment by 112358sam** [comment]
For future reference, just tag with [minor] to get the minor bug label.
