### ISSUE TITLE
Observable objects don't properly get rid of observers in disposing().

### ISSUE THREAD

**Issue by ZeWaka** [goonstation/goonstation#659]
Example:
https://github.com/goonstation/goonstation/blob/a3593c48bd1c874ad95a70356240d13652562783/code/obj/machinery/nuclearbomb.dm#L44-L46

The nuclear bomb (and other observable objects) don't clear all the observer references when it's in disposing().

**Comment by pali6** [comment]
How about a component (well, it could be an element but we don't have those yet) on observers that registers a signal to cancel the qdel and instead move the observer to get_turf(src). (Unless they are on a turf already, in which case let them get qdel'd.)

**Comment by pali6** [comment]
Fixed by 6dc0d92d63f14869e8883802e46030e2b880d280
