### ISSUE TITLE
Oshan shuttle flings you in the wrong direction on takeoff

### ISSUE THREAD

**Issue by RagdollWizard** [goonstation/goonstation#6594]
**Describe the bug**
On Oshan, when the escape shuttle takes off to go to Centcomm, you are flung to the right side of the screen if unbuckled. The thrusters are on the left side of the shuttle and momentum disagrees
**To Reproduce**
1. Be on Escape Shuttle on Oshan
2. Don't buckle in
3. Be flung to the right 😡 
**Expected behavior**
Momentum functions

**Screenshots**

**Additional context**

Reported on: Goonstation 2 Classic: Bombini 2021-11-06 00:17:16

**Comment by alexeric123** [comment]
I believe the direction of the fling is random for all shuttles.
