### ISSUE TITLE
Ghosts set off IR Detectors

### ISSUE THREAD

**Issue by TerraGS** [goonstation/goonstation#6599]
### Labels

[BUG]

### Description

IR Detectors are triggered when a ghost crosses their beam

### Steps to reproduce

1. Move over an IR Beam as a ghost
2. The IR Detector will activate in response to this

### Expected Behavior

IR Detectors shouldn't be registering mobs that have no physical presence

**Comment by Zonespace27** [comment]
Fixed by 842e99d
