### ISSUE TITLE
VR NUKIE VEND CAN BE DESTROYED

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6611]
### Labels

[BUG]

### Description

AS THE TITLE SAYS

ALSO THE CLEAN UP BUTTON GOT DESTROYED TOO

### Steps to reproduce

1. DESTROY SOME HOW I DONT KNOW.

### Expected Behavior

FOR IT TO NOT BE DESTROYABLE

### Additional Information & Screenshots

*SCREAM

**Comment by Nexusuxen** [comment]
not a coder but it might be a good idea to include what round this happened in so someone can go log diving

**Comment by flappybatpal** [comment]
Fixed VR buttons
https://github.com/goonstation/goonstation/pull/6674
