### ISSUE TITLE
Atmospheric force fields are completely nonfunctional

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6628]
### Labels

[major]

### Description

Atmospheric force fields block neither gas nor fluid from passing through them.

### Steps to reproduce

1. Get force field
2. Put gas/fluid on one side
3. It seamlessly moves to the other side

### Expected Behavior

The force field blocks the gas/fluid

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/67879783/140878186-6f89b86b-39ee-476d-a02f-cf0d35fe9d57.png)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/230035ecbb5e61ed917fd5867665ee64842e2048
