### ISSUE TITLE
Rail in Donut3 maint has wrong icon direction

### ISSUE THREAD

**Issue by TerraGS** [goonstation/goonstation#6664]
### Labels

[MINOR]

### Description

Rail blocks vertical movement but faces east

### Steps to reproduce

1. Go NW Inner Maint, between EVA and Janitor's Office
2. Attempt to walk vertically along the rails near the foam tank
3. (Optional) right-click to see two rails facing the same direction on this tile

### Expected Behavior

The rail blocking vertical movement should be facing south rather than east

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40574831/141656224-55bfab27-5e5f-4ac5-a24e-e020811287d1.png)

**Comment by TerraGS** [comment]
Adding to this, found a duplicate case right next to the North Outer Maintenance APC.

**Comment by Nexusuxen** [comment]
With the help of regex I've found 3 railings facing Southeast, including the 2 listed above. I'll see if I can find any more not facing the standard 4 directions and fix them accordingly.
