### ISSUE TITLE
Repairing antique laser gun changes the battery inside of it

### ISSUE THREAD

**Issue by zay25325** [goonstation/goonstation#6669]
when repairing the gun, the battery will always be changed to a 200u cell. this can be rather annoying as it can down grade fancy power cells like cerekite. it isn't that bad since you can use a weaker cell then swap out afterwards.

also on a side note: it would be nice if we could get the fancy action bars for repairing the gun, but thats whatever

**Comment by zjdtmkhzt** [comment]
duplicate of #6328
