### ISSUE TITLE
Who list jankiness

### ISSUE THREAD

**Issue by MRLinew** [goonstation/goonstation#6686]
![image](https://user-images.githubusercontent.com/75217127/141707934-e1a7632a-2ef6-447a-a81b-627f3e027dad.png)
As seen in this image, every couple characters or so, theres a gap. This is seen in the image i've posted, in Captain Bravos name, Borran Scails name, Mailman T's name, and more.

**Comment by zjdtmkhzt** [comment]
This seems related to you using the chat highlighting function, doesn't it? 🤔

**Comment by Zonespace27** [comment]
Not a bug, just that the chat highlighter doesn't discern if it's a word or part of one

**Comment by zjdtmkhzt** [comment]
Well, yes, but it is still a bug that it makes the empty spaces, due to the highlighting inserting a new span which causes the margin-right: 10px of the who-list styling to break up the name with an empty space.

**Comment by MRLinew** [comment]
oh your right, i totally missed that

**Comment by zjdtmkhzt** [comment]
Yup, it's an issue with the highlighting css inserting another span, which inherits the margin-right: 10px from the who-list div that the whole thing is in. 😠
