### ISSUE TITLE
the option to automatically capitalize the first letter of your speech messes with emoji

### ISSUE THREAD

**Issue by zjdtmkhzt** [goonstation/goonstation#6693]
### Labels

[BUG]

### Description

the option to automatically capitalize the first letter of your speech messes with emoji

### Steps to reproduce

1. Have option enabled to auto-capitalize speech.
2. Speak emoji.
3. The first emoji will be garbled nonsense.

### Expected Behavior

You speak emoji properly.

### Additional Information & Screenshots

This is due to the copytext() byond proc not handling emoji correctly, treating them as 4 symbols at text.dm:23.

I really can't be bothered to fix something like this myself, but if anyone else wants to, have at it.^^

**Comment by Yellow-Mushroom** [comment]
I’m entirely unsure, but when copy pasting unicode type speeches such as Sumerian, the first symbol/word is always messed up with a strange Đ. 

I have yet to test this, but if a solution is found, it may solve half of #4397

**Comment by zjdtmkhzt** [comment]
If you use the autocapitalization feature that is very likely, yes.
