### ISSUE TITLE
Unable to set Self Made Vending price to 0

### ISSUE THREAD

**Issue by Aivaria** [goonstation/goonstation#6694]
### Labels

[BUG]

### Description

Its currently not possible to set the vending price of an item to 0

### Steps to reproduce

1. Build a selfmade vending machine
2. add items
3. try to set price to 0 - nothing happens
4. setting any price >0 works as intended

### Expected Behavior

I expected to be able to set price to 0 like medical vender have

### Additional Information & Screenshots

https://github.com/goonstation/goonstation/blob/210c88d7484ff84af94b63803e0d665b1c5dc66e/code/modules/vending/vending.dm#L2048

possible source of issue, the input gets parse as NULL instead of 0 when entering a 0.

**Comment by frawhst** [comment]
Fixed in f597830
