### ISSUE TITLE
Admin created auto windows are inconsistent with player created

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#6695]
### Labels

[BUG]

### Description

Admin created windows block North/South travel. Player crafted large windows block all directions.

### Steps to reproduce

1. Use Build Mode to object spawn /obj/window/auto 
2. Attempt to walk through the window from all directions
3. Create a stack of glass, obj/item/sheet/glass/fullstack
4. Craft a large window
5. Attempt to walk through the window from all directions

### Expected Behavior

Identical behaviour from the same type

### Additional Information & Screenshots

Both windows show their type as /obj/window/auto.
They will behave identically, including auto connecting with other pieces but the admin created ones will only ever block North/South no matter how they are connected to other pieces.

**Comment by Sovexe** [comment]
This is because build mode overrides their default direction from `NORTH EAST` to whatever you choose instead
