### ISSUE TITLE
Unfolded paper planes continue to fly like they are folded into planes

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#6697]
### Labels

[BUG] [TRIVIAL]

### Description

If you fold a piece of paper into a plane, then unfold it and throw it, it will continue to fly like it was a plane.

### Steps to reproduce

1. Fold paper into plane
2. Unfold paper into normal boring non-plane shaped paper
3. Throw boring flat paper
4. Paper continues to fly as if it were folded into cooler plane shape

### Expected Behavior

Boring flat paper no fly far

**Comment by pali6** [comment]
I swear I already fixed this issue like twice. Aaa

**Comment by BatElite** [comment]
You can't keep paper down, it wants to be free
