### ISSUE TITLE
Dear god help the singularity is absorbing my AI camera aye

### ISSUE THREAD

**Issue by FlamingLily** [goonstation/goonstation#6702]
### Labels

[BUG] [trivial]

### Description

Title. AI eye gets sucked into the singulo, is not deleted on contact but still pulled in

### Steps to reproduce

1. Be ai
2. Be in camera mode
3. Be near singulo
4. Succ

### Expected Behavior

help let me out the singulo has me (not to get sucked by the singularity)

### Additional Information & Screenshots

Probably what #6451 is trying to convey, though I didn't understand without seeing it myself

**Comment by frawhst** [comment]
fixethe'd 7f92169
