### ISSUE TITLE
living soulsteel/hauntium

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#671]
[BUG]

**Describe the bug**
living soulsteel/hauntium object sometimes straight up disappear when "killed"

in the cause of lockers, it makes me wonder what happens to items inside

**To Reproduce**
1. possessess soulsteel/hauntium object as ghost
2. do living object things
3. get "killed"
4. possible object disappears entirely

**Expected behavior**
the object not to go poof

**Comment by Carbadox** [comment]
Tested locally, no longer the case
