### ISSUE TITLE
Donut 3 Asylum - No Way In/Out

### ISSUE THREAD

**Issue by Redblade121** [goonstation/goonstation#6712]
### Labels

[BUG]

### Description

If you get into the Asylum via missile entry on Donut 3, there is no actual way to get out of it by yourself  out as there are no doors to the actual asylum part of the wing.

### Steps to reproduce

1. Missile Entry yourself into the Asylum
2. Attempt to escape without any outsidee help (Including AI)

### Expected Behavior

I expected there to be a door of some sort that medical personnel, at least, could use to go into/out of the area.

**Comment by zjdtmkhzt** [comment]
We seem to get a lot of questions about that area, particularly by clowns.
Even if there is some obscure way of escaping, seems like it should maybe be reworked a little.

**Comment by Nexusuxen** [comment]
Perhaps a hint or piece of paper hidden somewhere hinting at how to escape? Maybe some crumpled paper that, if you unfold and read it, it's some maintenance worker's notes on planned renovations, saying something like "To Do: Repair bathroom walls" or something

**Comment by Sovexe** [comment]
> We seem to get a lot of questions about that area, particularly by clowns. Even if there is some obscure way of escaping, seems like it should maybe be reworked a little.

There's tools hidden in the wall

![image](https://user-images.githubusercontent.com/33204415/142633519-4592cc5b-f0f0-4dcd-968a-51299ab01511.png)
