### ISSUE TITLE
Battle Royale game mode can spawn you in dangerous areas

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#6724]
### Labels

[BUG]

### Description

Same as tittle, I spawned in a gas cloud that instantly knocked me out with no way to play at all.

### Steps to reproduce

1. exit the ship so you can enter the map
2. get unlucky
(sorry for being vague as this bug rarely happens in a rare gamemode It's hard to get proper info)

### Expected Behavior

not spawning in dangerous areas

**Comment by flappybatpal** [comment]
This was an N20 cloud, perhaps just remove the cannisters.

**Comment by ThatFiveGuys** [comment]
Removed from br
