### ISSUE TITLE
Journalists spawn with a 0 memory audio recorder

### ISSUE THREAD

**Issue by vocalpocal** [goonstation/goonstation#6731]
### Labels

[BUG]

### Description

The audio recording device has a tape that is full at 0%, and is thus unusable

### Steps to reproduce

1. Try to use the audio recorder Journos spawn with
2. fail miserably

### Expected Behavior

There should be some memory left at 0%

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25270027/142644864-a51b6550-eca2-4e44-b2a6-256f7c79ac41.png)

**Comment by Nexusuxen** [comment]
After running a local test I can't seem to reproduce the bug, having respawned myself as a journalist and being able to successfully use the audio log. As a note, it saying "Full" is always present, such as when it's "0% Full". Perhaps the capitalized F is misleading, though.

Maybe someone else can reproduce it?

Image to possibly help
![image](https://user-images.githubusercontent.com/28785926/142676611-757c497b-7156-48f3-a6ab-f05d04fcee70.png)

**Comment by Gannets** [comment]
The UI for these sucks, but I confirmed they work, same as Nexusnexan. Case closed!
