### ISSUE TITLE
Fire extinguishers don't update the percentage of how much they are filled in some cases.

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#6738]
### Labels

[BUG] [MINOR]

### Description

Same as title, the value doesn't get changed and displays how it looked before the chemical add/remove even if wrong.

### Steps to reproduce

1. empty the fire extinguisher
2. put some chemicals inside by pouring it from a beaker

### Expected Behavior

The percentage updates and isn't wrong.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/53602251/142689137-d06573e3-46d0-45f4-b47b-9f7c98b47677.png)

**Comment by ZeWaka** [comment]
think this was fixed
