### ISSUE TITLE
Spy PDAs can dissapear when scanning storing items

### ISSUE THREAD

**Issue by Skittledude60** [goonstation/goonstation#6754]
### Labels

[BUG]

### Description

Spy PDAs can dissapear when trying to scan storing items (Utility belts, boxes)

### Steps to reproduce

1. Be a spy, have a storing item bounty
2. Click on the item with the PDA, it should go inside of the stored item
3. Go into the item inventory, once it's out the item will be scanned and you will get the item, but your PDA will dissapear because it was inside the stored item
4.

### Expected Behavior

I expect to be able to scan the item before the item goes in, and I expect the PDA not to dissapear

**Comment by TobleroneSwordfish** [comment]
Ohhh I see, you have to put your PDA in the storage and then click drag the storage onto it inside the storage. Part of me wants to say that's your fault for not thinking about it for half a second, but we probably shouldn't delete PDAs for the funny so I'll make a PR for this
