### ISSUE TITLE
Flashlight Hud icon does not update when activated through keyboard.

### ISSUE THREAD

**Issue by MitchTheUser** [goonstation/goonstation#6755]
### Labels

[BUG]

### Description

When clicking on the flashlight's Hud icon, it updates to be lit up, but when activating it by clicking a key, c in my case, it does not update to reflect its on status

### Steps to reproduce

1. have flashlight out
2. press key to turn flashlight on
3. observe Hud icon not changing

### Expected Behavior

Flashlight's Hud icon should change when activating it through the keyboard

**Comment by FlameArrow57** [comment]
Was fixed
