### ISSUE TITLE
opaque windows

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6761]
### Labels

[BUG]

### Description

cant see thru windows made from gem stones

### Steps to reproduce

1. process gemstone
2. make it into sheets
3. be sad when window is not see thru

### Expected Behavior

they bee see thru

**Comment by Vaskritaya** [comment]
Gemstones just arent very transparent. This is also a problem when trying to make fashionable material glasses because you wont be able to see through them. Disappointing, but I'm personally not sure if it's really a bug.

**Comment by Zonespace27** [comment]
Not a bug, just slightly confusing matsci properties

**Comment by RSG250** [comment]
pretty sure is a bug, cause they WERE see thru for windows and stuff. now they aint at all
