### ISSUE TITLE
Matches

### ISSUE THREAD

**Issue by Skeinrender** [goonstation/goonstation#6778]
Seems broken matches will work like normal matches, lighting things on fire and the like. It then can be reused and placed in a bag for unlimited lights.

**Comment by TobleroneSwordfish** [comment]
So broken and burnt out matches can still be set on fire, which is normal. What isn't normal is that they seem to burn forever, unlike other flammable items. Oh and lighting things on fire with an infinitely flaming broken match still says "You fumble around with the broken match and try to get it to light, but it's no use." as if you're trying to light the already on fire (but not technically lit) match.

**Comment by ThatFiveGuys** [comment]
Unable to reproduce, presumed fixed
