### ISSUE TITLE
Donut 2 Artlab lacks labels

### ISSUE THREAD

**Issue by TerraGS** [goonstation/goonstation#6802]
### Labels

[BUG]

### Description

Artifact lab on Donut 2 has no artifact labels

### Steps to reproduce

1. Load Donut 2
2. visit artifact lab

### Expected Behavior

Artlab should have labels

**Comment by zjdtmkhzt** [comment]
People still use donut2?

**Comment by nefarious6th** [comment]
fixed at some point
