### ISSUE TITLE
when adding pugs they put a link in the changelog description which poorly loads a webpage into ss13 

### ISSUE THREAD

**Issue by zay25325** [goonstation/goonstation#6810]
usually when you would want  to see the PR page you would click on the arrow which would load the webpage on a web browser, but they added a link into the changelog description and so clicking it attempts to load the page in the game. you can still open the PR page normally through the arrow.

 you can not resize, move, or close the changelog in this state normally but you can still close it with the changelog command

it is still readable but all of github's formatting is lost and clicking on other links inside of it can cause overlapping text

![ss13 bug2](https://user-images.githubusercontent.com/60016762/143724808-04afe128-a78f-4781-8fbd-f26a68069574.png)
![ss13 bug](https://user-images.githubusercontent.com/60016762/143724809-b873aef3-b78a-46c4-955e-f2968b96049b.png)

**Comment by Vaskritaya** [comment]
this might share a root cause with #5760. 

it's been a while since I've clicked a url in a tgui window, they might just all attempt to open the window in the bootleg byond ie browser thing rather than attempt to use the user's default browser to open it.
