### ISSUE TITLE
Minor visual bug with meson + night vision

### ISSUE THREAD

**Issue by TerraGS** [goonstation/goonstation#6818]
### Labels

[BUG]

### Description

Wearing meson goggles with night vision gene removes darkness but leaves radial light overlays

### Steps to reproduce

1. Equip Meson Goggles
2. Gain activated Night Vision gene

### Expected Behavior

Either the overlay should be removed in this instance or the edges of the overlay should match the surrounding light level

**Comment by HBS-System** [comment]
The bug exists for... I believe most forms of nightvision interactions with X-Ray, for example: Meson goggles and Night-Vision Eyes. Big black circle, as if the overlay for the Mesons were overlapping massively.
