### ISSUE TITLE
AI PDA gets assigned to BYOND username rather than AI name

### ISSUE THREAD

**Issue by wolfolotl** [goonstation/goonstation#6819]
### Labels

[BUG]

### Description

The AI PDA does not display messages as being from the AI, but rather, as from the username of the player playing the AI.

### Steps to reproduce

1. Roll AI
2. Check your AI PDA
3. Notice that instead of BeepBoopatron 5000 it says RedDeadRedemptionJoey or whatever
4. Get too embarrassed to message anyone

### Expected Behavior

The name of the AI PDA's owner is the AI, not the player.

**Comment by zjdtmkhzt** [comment]
oh boy I sure hope this isn't a consequence of my actions

**Comment by zjdtmkhzt** [comment]
but it turns out it is
