### ISSUE TITLE
Sounds are being cut off by sound effects

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6824]
### Labels

[BUG]

### Description

Some sound effects (like announcement and pda noises) are cut off if too many of other sound effects (like emotes or wall tapping) are happening.

### Steps to reproduce

1. Have a lot of noise happening (like wall tapping or emotes with noises)
2. Try to have a sound like a pda ringtone or announcement sound effect play
3. Notice the pda ringtone and/or announcement cut off

### Expected Behavior

For the sound effects to not be cut off

**Comment by virvatuli-gh** [comment]
This is a byond sound channel issue and unavoidable. It simply gets overloaded when too many sounds are playing.
