### ISSUE TITLE
Item deletion/unobtainability with One Armed Spaceman

### ISSUE THREAD

**Issue by MDIPurple** [goonstation/goonstation#6840]
### Labels

[BUG]

### Description

Items being deleted or made unobtainable due to a lost limb bug

### Steps to reproduce

1. Have one arm, either through removal or One Armed Spaceman.
2. Place an item in your pocket, and one in your hand.
3. Drag the item in your pocket onto the item in your hand.
4. The dragged item is deleted or made otherwise unobtainable.

### Expected Behavior

Replacing the item in hand with selected item.

**Comment by MetricDuck** [comment]
Probably because of that qdel in one armed, need to check
