### ISSUE TITLE
crate iconstate not updating

### ISSUE THREAD

**Issue by nefarious6th** [goonstation/goonstation#6854]
### Labels

[BUG]

### Description

basic crates iconstate does not update when opened

### Steps to reproduce

1. find basic non-locked metal crate
2. open
3. close
4. notice the icon state does not update

### Expected Behavior

open crates to update their icons to appear open

**Comment by Zonespace27** [comment]
Maybe caused by #6836?

**Comment by Zonespace27** [comment]
7211f64
