### ISSUE TITLE
Snow on grass looks very strange

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#6858]
### Labels

[BUG]

### Description

Snow on grass looks extremely strange

### Steps to reproduce

1.  Play Oshan (probably any map) on spacemas
2.  Observe the monkey dome and botany looking like this
![snow](https://user-images.githubusercontent.com/20713227/144658934-4dc55ff4-dd95-4dfe-91ff-1a0eeba4527f.png)
3. Other people also saw the issue

### Expected Behavior

I expected snow to look normal

### Additional Information & Screenshots

![snow](https://user-images.githubusercontent.com/20713227/144658934-4dc55ff4-dd95-4dfe-91ff-1a0eeba4527f.png)

**Comment by TTerc** [comment]
Should be fixed by 65aa2322b2a6d173c4eb29961982e93c1deb0293
