### ISSUE TITLE
Snow is Depressurizing Rooms

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6859]
### Labels

[BUG]

### Description

Rooms that spawn with snow, such as the genetics biodome and botany, are spawning without air. This might be related to the snow.

### Steps to reproduce

1. Spawn in with spacemas enabled
2. Go to botany or monkey dome
3. Notice a distinct lack of air

### Expected Behavior

For there to be air in them

### Additional Information & Screenshots

Not sure if this is map specific, but Oshan and Donut 3 has this problem.

**Comment by TTerc** [comment]
Fixed in fea6e846a55feabf2fc3ae0fa358bf7d2f597edd
