### ISSUE TITLE
PDA light isn't working

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6867]
### Labels

[BUG]

### Description

Using the pda light doesn't emit any light

### Steps to reproduce

1. Turn on you pda light
2. Notice no light

### Expected Behavior

For the pda light to emit light

**Comment by blackrep** [comment]
Any chance you swapped the PDA module for the high-power flashlight? I've noticed that swapping modules don't actually work until you take it out of your ID slot, put it in-hand, then put it back into your ID slot.

**Comment by Wisemonster** [comment]
I just remembered, mechanics come with a tray scanner module, not a flashlight module
