### ISSUE TITLE
can_reach recursion runtime

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6875]
![image](https://user-images.githubusercontent.com/67879783/145156839-3efc0cb6-96c5-4c99-b188-4bb0940c3c45.png)

**Comment by Zonespace27** [comment]
How was this produced? Or is i a constant error that's happening?

**Comment by frawhst** [comment]
Still happening. I always see this happen on cog1, and it's ALWAYS this table segment:
![image](https://user-images.githubusercontent.com/67879783/150294817-7ba10648-4305-4439-a51d-10ee7715a346.png)
Probably something to do with the thindow, I dunno

**Comment by frawhst** [comment]
Update: related to drinking glass sliding somehow. I forget if someone fixed this, will revisit

**Comment by frawhst** [comment]
Still happening

**Comment by flappybatpal** [comment]
90% sure this is fixed.
