### ISSUE TITLE
Disguiseium - The disguised chemical appears as imcoder in the chem dispenser

### ISSUE THREAD

**Issue by loludied** [goonstation/goonstation#6890]
### Labels

[BUG]

### Description

When scanning with the reagent scanner, the disguised chemical is called properly, but when looking through the chem dispenser it is called imcoder 

### Steps to reproduce

1. Fill a beaker with 40u of water and 20u of ethanol
2. make 2 more beakers, one with first 4 of the chemicals needed to make Disguiseium, other with the last one
3. take a mechanical dropper, use it to drop the first 4 chems(1u of each) into the water + ethanol mix, then drop the last one
4. 5u of chem called imcoder appears

### Expected Behavior

Expected 5u of ethanol to get disguised as water

### Additional Information & Screenshots

When scanning with the reagent scanner, it does work, but when looking through the chem dispenser it appears to glitch
screenies are here to better explain the situation https://imgur.com/a/WURp2fq
Also hesus christus i tried to report this using the gitreports as it is a secret chem but WHAT IN THE GODS NAME ARE THOSE CAPTCHAs, i tried dozens of times and never passed :( look at those bad boys https://imgur.com/a/mGrFI1h

**Comment by zjdtmkhzt** [comment]
The Captchas are currently bugged to have the big circle, yeah. Don't worry, you are not secretly a robot.
