### ISSUE TITLE
Lunchbox spacebux purchase can give Robust Donuts

### ISSUE THREAD

**Issue by Smearfo** [goonstation/goonstation#6893]
### Labels

[BUG]

### Description

When buying a lunchbox via spacebux, one of the possible spawns seems to be security's Robust(ed) Donuts box

### Steps to reproduce

1. Buy Lunchbox from the Spacebux menu
2. Spawn in
3. Receive a box of delicious (but probably unintended) Robust Donuts.

### Expected Behavior

For common lunchboxes to only contain crew-approved meals.

**Comment by DisturbHerb** [comment]
the staffies can have a lil donut as a treat 😊
