### ISSUE TITLE
WRESTLE DOODLE IS WACK

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6896]
### Labels

[BUG]

### Description

SUPLEX FOR DAYS

### Steps to reproduce

1. AGGRESSIVE GRAB MONKEY AS WRESTLE DOODLE
2.SPAM R
3. SCREAM

### Expected Behavior

NOT  SUPLEX FOR DAYS

### Additional Information & Screenshots

https://user-images.githubusercontent.com/63602513/145683389-a1364709-f8f3-4bc0-b4f1-d4c1ce7c62ac.mp4

**Comment by zjdtmkhzt** [comment]
I believe pali fixed this in 146c6bfdad76dd00c14c74875b5c9b9c46a02139.
