### ISSUE TITLE
Can't put coffee mugs on racks

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6899]
### Labels

[BUG]

### Description

You can't put coffee mugs back onto racks after taking them off

### Steps to reproduce

1. Find mug of a rack, usually near a coffee maker
2. Take mug off
3. Try to put it back on

### Expected Behavior

For mugs to be able to be put back on the racks

**Comment by TTerc** [comment]
Fixed in 96e69a6ea91c580adec0cd77916775ceab42b05f
