### ISSUE TITLE
Gem stones are very good for windows 

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6901]
### Labels

[BUG]

### Description

gemstones arent translucent or whaterver any more so you cant see thru windows made from them

### Steps to reproduce

1. make sheets out a of a gem stone
2. make window
3. be sad

### Expected Behavior

i want to be able to see thru my fancy windows

**Comment by TobleroneSwordfish** [comment]
duplicate of #6761 which was also submitted by you

**Comment by Zonespace27** [comment]
Dupe of #6761

**Comment by RSG250** [comment]
wow i didnt realize i already did a report
