### ISSUE TITLE
latejoin job select doesn't condense staffie slots

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#6902]
### Labels

[BUG]

### Description

On the latejoin job selection screen, staff assistant slots are all individually checked off instead of being condensed with a +x.

### Steps to reproduce

1. Join a round that's been going on for awhile.

### Expected Behavior

Tables don't get broken.

### Additional Information & Screenshots

https://i.imgur.com/axwyFoR.png

**Comment by Zonespace27** [comment]
Aloe confirmed they broke it at some point

**Comment by TheTyrant25** [comment]
what broke it was the line
`var/shown = min(max(c, (limit == -1 ? 99 : limit)), maxslots)`
changing this to `var/shown = min(max(c, (limit == -1 ? maxslots : limit)), maxslots)` should fix that right up
