### ISSUE TITLE
Floorbots have absurd amounts of health

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#6903]
### Labels

[BUG]

### Description

Floorbots have WAY more health than any other bot in the game. I'm uncertain they can even die.

### Steps to reproduce

1. Find a floorbot.
2. Bonk it a LOT
3. It just vibes alive and well

### Expected Behavior

Floorbot break when hit.

### Additional Information & Screenshots

Me hitting it a bunch
![image](https://user-images.githubusercontent.com/40079883/145730458-bff92568-6012-4912-81c9-4139d789180a.png)
It has taken no damage 
![image](https://user-images.githubusercontent.com/40079883/145730477-4f359cbb-2e01-43bf-a5a4-a129a78c0ba9.png)

**Comment by TTerc** [comment]
Fixed in 8ff8167650d58b4dc2fae8d75c3277c7bbd1b514
