### ISSUE TITLE
You can pass through AI cores.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#6904]
### Labels

[BUG]

### Description

You are no longer stopped by the big bulky AI core when you attempt to move on the same tile as it.

### Steps to reproduce

1. Go to an AI core.
2. Walk into it as a human
3. Walk through it.

### Expected Behavior

Being blocked by the AI core like I used to be

### Additional Information & Screenshots

Probably has to do with the can_pass changes.

**Comment by amylizzle** [comment]
Can't replicate. AI core is blocking like you'd expect. I'm guessing this was fixed already.

**Comment by ThatFiveGuys** [comment]
Unable to be reproduced
