### ISSUE TITLE
Cyborgs can touch artifacts from any distance

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#6905]
### Labels

[BUG]

### Description

See title. I am unsure if this applies to: Eyebots, AIs, Ghost drones, and if it applies to handheld artifacts.

### Steps to reproduce

1. Be cyborg.
2. Find artifact.
3. Click on it while you are far away.
4. Get a message saying you touch it, and potentially activating it.
5. See error.

### Expected Behavior

I maintain my feeble corporeal capabilities as a cyborg, unable to extendo-reach my arm to touch an artifact halfway across my screen (and theoretically across the map with a camera console)

**Comment by frawhst** [comment]
armchair guess is that this stems from certain types of artifacts being machinery subtypes

**Comment by Nexusuxen** [comment]
I think I activated a silicon prison artifact, and was able to remotely touch a wizard artifact

**Comment by zjdtmkhzt** [comment]
😑

**Comment by zjdtmkhzt** [comment]
It's not actually due to the machine type, but just the fact that the silicon touch is triggered via ai_attack, which also triggers attack_hand, to make it so that cyborgs can touch artifacts, I guess.
Should have a range restriction and stuff.

**Comment by zjdtmkhzt** [comment]
should have been fixed by #6956
