### ISSUE TITLE
things not working

### ISSUE THREAD

**Issue by Markimono** [goonstation/goonstation#6906]
### Labels

[BUG]

### Description

things literally not working

### Steps to reproduce

1. join goonstation server

### Expected Behavior

I expected to be able to make characters or drinks but cant

### Additional Information & Screenshots

I was playing goonstation and there are some things that dont work for me and give me some sort of termos error or something for example I cant setup character so I cant spawn with jobs I want or cant be a bartender because the drink machines dont work i tried other servers and they aren't much better but they're still better because I can create characters make drinks however I cant write on paper cuz I get an ntos error. goon station is by far my favorite server so if you could help me fix it I'd be much obliged (I am also running Byond through crossover on a Mac so that might have something to do with it.)

**Comment by Zonespace27** [comment]
Mind sending a photo of the TERMOS error? Easier to fix with the call stack

**Comment by Markimono** [comment]
> Mind sending a photo of the TERMOS error? Easier to fix with the call stack

right here

![262834956_990693028202146_6676993243365102588_n](https://user-images.githubusercontent.com/61087160/145781886-febad900-0c5e-46ce-83a2-5b86690fbd13.jpg)

**Comment by pali6** [comment]
Could have also happened during outage?
