### ISSUE TITLE
1 of the oshan arrival pods paths dont line up with the holes correctly

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6911]
### Labels

[BUG]

### Description

as the title says

### Steps to reproduce

1. ??????????? hop arrive with right path, refer to attached diagram

### Expected Behavior

not bad path

### Additional Information & Screenshots

![Untitled](https://user-images.githubusercontent.com/63602513/145849832-eff129cd-7cea-4f46-92f0-a29243d32a67.png)

**Comment by TTerc** [comment]
Probably related to the shuttle size expansion PR, I assume Oshan escape and arrivals was moved a bit
Fixed in 4ce7c6afedf743717d376cdefc7275e0e88f614d
