### ISSUE TITLE
vape bypasses the smoke blacklist

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#6916]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. emag the vape
2. fill it with perfect concrete
3. use

### Expected Behavior

empty smoke since that chem is blacklisted from smoke

**Comment by penny64** [comment]
Well, this is only possible with an emag so it doesn't seem totally unreasonable?

**Comment by TobleroneSwordfish** [comment]
Fixed
