### ISSUE TITLE
Empowered Superfarting on a bible does not send you to hell

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#6917]
### Labels

[BUG]

### Description

Being gibbed by the fart prevents you going to hell

### Steps to reproduce

1. Get the superfart ability
2. Empower it
3. Fart on a bible
4. Die and do not go to hell

### Expected Behavior

Be sent to hell

### Additional Information & Screenshots

proc name: cast (/datum/targetable/geneticsAbility/superfart/cast)
  source file: powers.dm,1000
  usr: Test Human (/mob/living/carbon/human)
  src: Superfart (/datum/targetable/geneticsAbility/superfart)
  usr.loc: null
  call stack:
Superfart (/datum/targetable/geneticsAbility/superfart): cast(null)
Superfart (/datum/targetable/geneticsAbility/superfart): tryCast(null)
Superfart (/datum/targetable/geneticsAbility/superfart): handleCast(null)
Superfart (/atom/movable/screen/ability/topBar/genetics): clicked(/list (/list))
TestClient (/client): Click(Superfart (/atom/movable/screen/ability/topBar/genetics), null, "mapwindow.map", "icon-x=17;icon-y=19;left=1;scr...")

**Comment by DimWhat** [comment]
To my knowledge it only ever worked on normal superfart due to how empowered gibs you.
