### ISSUE TITLE
Wall phones become normal phones when called.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#6919]
### Labels

[BUG-MINOR]

### Description

Wall phones can turn into the normal phone sprite after being called.

### Steps to reproduce

1. Call a wall phone.
2. Eventually give up and stop calling.
3. Check the phone.
4. See wack sprite error

### Expected Behavior

The phone to maintain it's sprite after being called.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/145904329-bcd50eec-6a6f-46e7-acdb-145769fc70b5.png)

**Comment by TobleroneSwordfish** [comment]
Does this actually stop the phone from working is that just the standard "no-one ever picks up the bridge phone" issue?

**Comment by DimWhat** [comment]
> Does this actually stop the phone from working is that just the standard "no-one ever picks up the bridge phone" issue?

It goes back to normal after you pick up the reciever.
