### ISSUE TITLE
Dented Crates are missing

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#6926]
### Labels

[BUG]

### Description

Dented crates sprite is missing

### Steps to reproduce

1. go to the place the has the space spider and loot crates in debris field
2. notice empty spots next to crate
3. try to walk into one
4. cant
5. ???????

### Expected Behavior

them to not be missing

### Additional Information & Screenshots

![Untitled](https://user-images.githubusercontent.com/63602513/146026870-e404919f-5fb9-4c91-8637-4e10c641a720.png)

![Untitled](https://user-images.githubusercontent.com/63602513/146027408-c5519894-5294-4991-be3e-2d66fcfb6c67.png)

**Comment by TTerc** [comment]
Fixed in f00dfd589a6e16c49b4c4fa1ee18c2872abb156b
