### ISSUE TITLE
Shooting yourself with the NT Syringe Gun doesn’t work

### ISSUE THREAD

**Issue by getbrecked** [goonstation/goonstation#693]
**Describe the bug**
The NT Syringe Gun that the Medical Director has doesn’t work at all when you shoot yourself with it. It still gives a status message reading that you shot yourself, but chems aren’t actually injected nor does the amount of chems in the gun go down.

**To Reproduce**
1. Fill Syringe Gun with chemicals (I used charcoal)
2. Set to Harm intent so you don’t punch yourself
3. Click on yourself and see amazing chat message telling you that you shot yourself.
4. Realize that it didn’t work and there are no chems in your body, and still chems in the gun.

**Expected behavior**
It would inject the charcoal so I wouldn’t die of toxin damage.

**Comment by zjdtmkhzt** [comment]
I think that is actually because point-blanking with the syringe gun doesn't work at all, in my experience?
It used to work, but I think it doesn't anymore, iirc.

**Comment by ryebek** [comment]
Yeah, I'm pretty sure syringe gun point blanks don't work in general.

**Comment by zjdtmkhzt** [comment]
Just tried it locally and the regular syringe gun seems to be broken as well.

**Comment by Tarmunora** [comment]
Will look into this
