### ISSUE TITLE
Dual wielding katanas causes your target to regrow detached body parts.

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#6934]
### Labels

[BUG]

### Description

If you dual wield katanas and attempt to remove a mob's limbs, tail, and head; generic limbs grow back in their place.

### Steps to reproduce

1. Acquire two katanas.
2. Go ham on a fleshy target, aiming at the arms and legs.
3. Realise that your targe is somehow growing them back.
4. See error.

### Expected Behavior

The target should not unleash their inner axolotl, and should remain de-limbed.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/66253095/146127582-7ccf9574-a6fd-46ba-b40b-ed8fc8a1c0d7.png)

**Comment by Zonespace27** [comment]
I propose this be bug of the year (we have that, right?)

**Comment by Conchuckter** [comment]
I wasn't able to recreate this, has anyone else?

**Comment by 112358sam** [comment]
Also unable to replicate this. Used two traitor katanas swapping back and forth as I targeted limbs. None grew back. Used a tdummy for testing. I wonder if this was just a result of the target having the regeneration mutation?
