### ISSUE TITLE
mechcomp pressure sensors dont work

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#6937]
### Labels

[BUG]

### Description

title, they never get triggered

### Steps to reproduce

1. setup a pressure sensor fully correctly
2. connect it to a light
3. walk over it (doesnt get triggered)

### Expected Behavior

it should get triggered

### Additional Information & Screenshots

this happened on a test server
i hope i didnt just mess up the setup and mistook if for a bug

**Comment by ThatFiveGuys** [comment]
You probably just messed it up, these things work fine
