### ISSUE TITLE
Guard buddies On Donut 3 will not work

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#6939]
### Labels

[BUG]

### Description

Guard buddies on donut 3 will not work, even after setting their patrol scripts on

### Steps to reproduce

1. Go to Donut 3
2. access the guard buddies controls from dwaine
3. Use the patrol_script command on the buddies
4. Notice how they refuse to move

### Expected Behavior

For the guard buddies to patrol, not sit around.

### Additional Information & Screenshots

Not sure if this is a problem on other maps. Might also be the bug that causes the buddies to not return to their charging pads when their batteries get low.

**Comment by Zonespace27** [comment]
I was able to use guardbuddies just a few days ago on a donut 3 local, unsure if this bug may have just been a one-off.

**Comment by zjdtmkhzt** [comment]
I assume this was the general pathing issue, which was solved in f2d9347.
