### ISSUE TITLE
The captcha for reporting bugs doesn't work.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#6944]
### Labels

[BUG]

### Description

Reporting a bug without a github account is impossible, the captcha is incomprehensible for anyone to actually report anything with it.

### Steps to reproduce

1. Report a bug without an account.
2. Reach the captcha section
3. It's incomprehensible.
4. Question humanity.

### Expected Behavior

Be able to actually see what I'm supposed to type.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/146626585-700f7290-77bd-42c3-87c3-e8dc58da5883.png)
Captcha sucks.

**Comment by Nexusuxen** [comment]
`to be fair I can't seem to solve any captchas, so I don't see the issue`

In all seriousness I've seen several people complain about this over the past couple weeks so it's definitely not just you

**Comment by zjdtmkhzt** [comment]
That is an issue with gitreports, not us, I think. https://github.com/schneidmaster/gitreports.com/issues/235

They seem unresponsive though. 🤔
