### ISSUE TITLE
Spacemas tree behaves strangely with lighting

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#6945]
### Labels

[minor]

### Description

The spacemas tree appears lit even when it shouldn't.

### Steps to reproduce

1. See lit tree in full darkness
2. be confused

### Expected Behavior

Tree is lit according to the proper environment

### Additional Information & Screenshots

![fucky-spacemas](https://user-images.githubusercontent.com/67879783/146637333-71e70631-2275-40b6-b1ff-c79349697d3c.png)

**Comment by ThatFiveGuys** [comment]
https://github.com/goonstation/goonstation/blob/master/code/modules/holiday/spacemas.dm#L447 Not a bug
