### ISSUE TITLE
Santa teleport bugs

### ISSUE THREAD

**Issue by alexeric123** [goonstation/goonstation#6953]
### Labels

[BUG]

### Description

Santa cant teleport into security on donut 3, i am not sure if its part of an underlying bug

### Steps to reproduce

1.  Spawn as santa on donut3
2. try to teleport into sec to give them some gifts
3. teleport does nothing
4. see error

### Expected Behavior

Teleporting into sec as the ablility states

**Comment by Zonespace27** [comment]
a012378

Not a bug

**Comment by alexeric123** [comment]
All of security is teleblocked? weird
