### ISSUE TITLE
NARCS and nukie turrets can't be aimed anywhere but south

### ISSUE THREAD

**Issue by Merlin1230** [goonstation/goonstation#6962]
### Labels

[BUG]

### Description

Using the wrench to try and aim a turret doesn't aim them at all

### Steps to reproduce

1. Deploy a NARCS/NAS-T
2. Turn it on
3. Click on it with a wrench
4. try and aim it somewhere
5. be confused as it still looks south

### Expected Behavior

The turrets should be aiming to the spot you click

### Additional Information & Screenshots

They also deploy south no matter which direction you face
Haven't tested the NAS-T quick deploy thing but I imagine its the same

**Comment by Zonespace27** [comment]
d92ff5a probably broke it

**Comment by frawhst** [comment]
Hm, I definitely tested this. Will investigate later tonight.

**Comment by frawhst** [comment]
Found the issue. Re-aiming works fine with a wrench, but not anything else (i.e. omnitool) because it specifically checks that you're holding a wrench in the aiming ability. Dumbcode, will fix soon

**Comment by frawhst** [comment]
Hm. Nevermind, that was a separate issue that I found by coincidence. Investigating the overall problem now.

**Comment by frawhst** [comment]
fbf1e32
