### ISSUE TITLE
Unable to interact with the game in any way

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#6963]
### Labels

[BUG]

### Description

Can't move, click on things, talk, use verbs. Restarting does not fix the issue, just results in the game looking weird. Happened just now on Morty, walked up to botany and was then unable to do anything. 

### Steps to reproduce

1. Be scientist traitor on Donut 3
2. Become completely unable to act
3. Don't know why
4. Game eventually crashes

### Expected Behavior

I expected to be able to interact with the game

### Additional Information & Screenshots

I just updated Byond to the latest version.
Sounds persist for several seconds after closing the game.
Another player called "Achtung_X" I think, said that they also had this issue the previous round. 
How game looks after restart: ![image](https://user-images.githubusercontent.com/20713227/147015599-6b03383c-d12b-4ab3-83ba-87bfae2d1147.png)

I logged in a while later, stepped out of cryo, game worked fine for about 10 seconds before breaking again.

**Comment by TobleroneSwordfish** [comment]
I can reproduce this on a local server, no errors in console

**Comment by LlamaZelvyre** [comment]
I am also having this issue. A few others are also mentioning this problem.
I'm fairly certain it has something to do with the most recent byond update. 

I've re-installed Byond, restarted my PC and tried different servers. After about 45 seconds to a minute the issue happens.
I get the message stating i'm experiencing lag or the connection has been interuppted (closed?) but I can still see people moving/talking as well as radio chat and announcements. It seems to effect the individual character.

**Comment by TobleroneSwordfish** [comment]
Ah, new Byond patch 
![image](https://user-images.githubusercontent.com/20713227/147035387-cb9f68c2-81a7-4bff-8105-9b79211c89f0.png)
yeah that was probably it, I'll delete this issue as soon as I'm sure it's fixed it

**Comment by TobleroneSwordfish** [comment]
Yep, it was a broken Byond update. Anyone having similar issues, the patch is out now, just update Byond
