### ISSUE TITLE
2 Actionbars on dismantling church pews

### ISSUE THREAD

**Issue by alexeric123** [goonstation/goonstation#6964]
### Labels

[BUG]

### Description

Trying to dismantle a pew has 2 actionbars.

### Steps to reproduce

1. dismantle a pew
2. see 2 actionbars

### Expected Behavior

Only one actionbar

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/39737078/147040330-1094ecf9-414a-4ebb-844a-8e109b89259b.png)

**Comment by Arthur-Holiday** [comment]
That is intended and on every chair.

**Comment by frawhst** [comment]
^

**Comment by alexeric123** [comment]
Man, both issues i made recently are intended.

**Comment by penny64** [comment]
Why is this intended? It's weird UX to me and it's generating bug reports so presumably a considerable amount of people think it's weird
