### ISSUE TITLE
rocket shoes never remove the ability button

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#6969]
### Labels

[BUG] [MINOR]

### Description

title, the button to use the exists even after removing them and can clutter the "ability bar" fast

### Steps to reproduce

1. put on rocket shoes
2. remove them

### Expected Behavior

the button should be gone

### Additional Information & Screenshots
im running an older version and probably need to check on a newer one too

i highly suspect it could also be related to some mess up on the client given that the round it happened on had other bugs related to UI and controls however the mess up on the client was caused by something ive done not on its own

the round involved a lot of stuff related to matsci and possesing items and npcs

**Comment by BatElite** [comment]
Seems to work fine on local for me

**Comment by Gerhazo** [comment]
Can't seem to be able to reproduce the issue.
Attempted putting rocket shoes on and off, doing the same via the V hotkey or the click-drag hotkey, putting rocket shoes on a different mob to no result.

**Comment by MetricDuck** [comment]
Occurs only if you completely use up the charge in the rshoes, the ability button is trying and failing to delete itself
