### ISSUE TITLE
flusher can softlock

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#6971]
### Labels

[BUG]

### Description

flip breaking a flusher makes you stuck in it

### Steps to reproduce

1. enter a flusher
2. flip break it
3. suffer

### Expected Behavior

it should let you out

**Comment by frawhst** [comment]
To be clear, are you talking about the yellow square flushers (usually in security), or the mechcomp flushers?

**Comment by frawhst** [comment]
nevermind, found the issue.
