### ISSUE TITLE
mop text is missing punctuation

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#6974]
### Labels

[BUG - TRIVIAL]

### Description

When you dip a mop in a bucket, you are given the message "You wet the mop", which lacks punctuation like most other messages.

### Steps to reproduce

1.  Get mop and filled bucket
2. Dunk mop in bucket
3. be sad at lack of punctuation

### Expected Behavior

punctuation

### Additional Information & Screenshots

relevant line is here

https://github.com/goonstation/goonstation/blob/27ff0506849dca779bcfc84db3dc9468a758d36d/code/modules/chemistry/Chemistry-Tools.dm#L444

**Comment by frawhst** [comment]
6bc25eb
