### ISSUE TITLE
ointment/bruise pack missing punctuation

### ISSUE THREAD

**Issue by Vaskritaya** [goonstation/goonstation#6975]
### Labels

[BUG - TRIVIAL]

### Description

When applying ointment/a bruise pack to yourself or others, some of the potential messages lack punctuation.

### Steps to reproduce

1. Somehow obtain one of the positively ancient ointment or bruise packs
2. apply it to yourself or another non-silicon mob
3. see sentences that lack punctuation

### Expected Behavior

punctuation

### Additional Information & Screenshots

lines 58 and 66 in this proc

https://github.com/goonstation/goonstation/blob/5ac94ceb90c8d16cfc42395281eda5e1bf34dfe4/code/obj/item/bruisepack_ointment.dm#L49

**Comment by frawhst** [comment]
6bc25eb
