### ISSUE TITLE
Guardbuddies do not path

### ISSUE THREAD

**Issue by Francisco-Franks** [goonstation/goonstation#6986]
### Labels

[BUG]

### Description

Guardbuddies do not path

### Steps to reproduce

Guardbuddies can't path, thus they can't patrol, and they can't really purge. If set to purge/guard/heckle they will do it as long as the target is in their vision but they won't chase. Also they don't path back to chargers?

### Expected Behavior

Path, buddy, path

**Comment by AmazingDragon353** [comment]
I've been doing some testing and this seems to happen once you've recalled the buddy. "prman recall all" will break all of the buddies' pathing, while "prman recall [id]" seems to only break that buddy. Not sure what's causing this, but it's definitely still an issue.

**Comment by zjdtmkhzt** [comment]
I believe the pathing bug is unrelated to the bug where recalling doesn't work properly - the recharge stations do not receive the buddies message due to an oversight in the new packet code. I will make a fix for this, but it won't fix the pathing for stuff like purge/guard/heckle, I think.

**Comment by zjdtmkhzt** [comment]
The general pathing issue was solved in f2d9347.
