### ISSUE TITLE
Floor Interaction Crayons

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#699]
[BUG]

**Describe the bug**
Unable to interact with the floor if its under something

**To Reproduce**

1. get crayon, go to floor with air injector on it
2. tray to draw bee on floor at center of tile
3. Bee sad air injector is in the way

**Expected behavior**
 being able to interact with the floor if its under something, i mean i can still interact with things in a pile with the right click but not the floor.

**Additional context**
this really makes doing crayon things a pain if theres an air injector in the way

![0980219a8c5820a46a6e42a17a84d606](https://user-images.githubusercontent.com/63602513/82058063-3cf06300-9692-11ea-81d0-3bc1138c2ad7.png)

**Comment by pali6** [comment]
You can now use the Pick Up / Left Click option to do this.
