### ISSUE TITLE
Suit slot items appear over beards.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#7015]
### Labels

[BUG - MINOR]

### Description

Putting on suit slot items makes them layer over beards, this looks pretty bad and usually doesn't even make sense.

### Steps to reproduce

1. Have a thick, luxurious,  long beard
2. Put on a wizard robe or a hoodie.
3. Have most of my beard appear under the suit slot item

### Expected Behavior

Have my beard appear over the suit slot items.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/147524147-9a4ec49e-9845-4ab8-838e-442ad6fb2fdf.png)

**Comment by Mister-Moriarty** [comment]
This was fixed a while ago, however I can't quite remember when, or in which commit. Regardless, suits currently overlay correctly with respect to hair.
