### ISSUE TITLE
the genes disappear from my monkey after i inject it with the gene injectors!!!!

### ISSUE THREAD

**Issue by chemtrailhaze** [goonstation/goonstation#7030]
### Labels

[BUG]

### Description

my fire and cold resistance genes disappear from a monkey after injection!

### Steps to reproduce

1. have two injectors, one of fire resistance, one of cold resistance
2. inject injectors into monkey
3. immediately put monkey back into genetics scanner
4. INJECTED GENES ARE NOT THERE!!!!

### Expected Behavior

for the genes to be there so i can mess with them!

**Comment by Zonespace27** [comment]
Do both disappear or just 1?

**Comment by chemtrailhaze** [comment]
Both disappeared, and it was just those two genes, all the other genes
injected/added prior were still present.

**Comment by Zonespace27** [comment]
Okay, so it's some bug to do with genes being mutually exclusive, may be related to #7032

**Comment by Zonespace27** [comment]
81b2d00
