### ISSUE TITLE
Mutations not staying

### ISSUE THREAD

**Issue by mrprogamer96** [goonstation/goonstation#7032]
### Labels

[BUG]

### Description

some mutations when taken will despawn right away

### Steps to reproduce

1. Use ether an injector or buy a mutation from the gene booth (some mutations still work as normal, other mutations like radiation resistance do this)
2. The mutation goes as if you had the mutation taken out.

### Expected Behavior

The mutations to stay

**Comment by mrprogamer96** [comment]
oh, one more thing to note that i almost forgot, the stability is still removed if the mutation was not stabilized.

**Comment by Zonespace27** [comment]
Which mutations did this happen with?

**Comment by mrprogamer96** [comment]
the two i noticed it happening on was Hemopoiesis Overdrive and Radiation Resistance, but i think there were others.

**Comment by mrprogamer96** [comment]
seems to be the same bug

**Comment by Vaskritaya** [comment]
may be related to commit 3883162ceaa40bbf9645a49b096f68dff90d6823 from earlier today.

**Comment by Zonespace27** [comment]
81b2d00
