### ISSUE TITLE
Possessed Flashlights are Useless

### ISSUE THREAD

**Issue by seppucrow** [goonstation/goonstation#7043]
### Labels

[BUG] 

### Description

Living soulsteel flashlights do not give off any light.

### Steps to reproduce

1. Possess soulsteel flashlight
2. Turn yourself on
3. Discover that, despite your sprite changing, nothing around you lights up.

### Expected Behavior

Was expecting the flashlight to project a beam of light.

### Additional Information & Screenshots

![dark](https://user-images.githubusercontent.com/84199857/147805088-9c9b27cd-5fe3-4940-9295-f9bac447cd3c.PNG)

**Comment by ZeWaka** [comment]
fixed by the rework
