### ISSUE TITLE
Active flashlights still give light to the user if stored

### ISSUE THREAD

**Issue by mc-oofert** [goonstation/goonstation#7053]
### Labels

[BUG]

### Description

If you put an active flashlight into a toolbox, or your belt or whatever, the light effect is still on you.

### Steps to reproduce

1. Get flashlight from EVA
2. Activate flashlight
3. Put flashlight into toolbox on the floor
4. Still have light

### Expected Behavior

I expected to not magically produce light

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/9f09cd55c8577d46f32262098c3baa1772c26869
