### ISSUE TITLE
Regent Groups Bug

### ISSUE THREAD

**Issue by Vlaad3** [goonstation/goonstation#7056]
### Labels

[BUG]

### Description

Regent Groups do not save groups properly

### Steps to reproduce

1. Create a regent group using hydrogen=2;carbon=2;chlorine=6;water=6;sulfur=9;hydrogen=9;oxygen=9;oxygen=18;sodium=18;carbon=18;
2. Compare saved group to orignal group

### Expected Behavior

I expected it to save properly

### Additional Information & Screenshots

The chem group should make salyalic acid when used with 2u of welding fuel.

**Comment by Arthur-Holiday** [comment]
The issue is you have oxygen, hydrogen and carbon twice in it. you should try this: `hydrogen=11;carbon=20;chlorine=6;water=6;sulfur=9;oxygen=27;sodium=18;`

**Comment by ZWRh3** [comment]
this is on purpose iirc you used hydrogen twice

**Comment by Arthur-Holiday** [comment]
Not intended in code, people inputting 2 of the same reagents isn't accounted for in any way. I am going 2 PR a fix soon
