### ISSUE TITLE
Atmos Alerter PDA app doesn't work

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#7058]
### Labels

[BUG]

### Description

The atmos alerter pda app will softlock its self when trying to use it

### Steps to reproduce

1. Get a pda with the atmos alerter app
2. Scan for alerts on the app
3. "Waiting for reply, please hold... "
4. Never get a reply

### Expected Behavior

For the app to do something, not take up space

### Additional Information & Screenshots

Not sure if the app is a relic of the past or not.

**Comment by nefarious6th** [comment]
map this occurred on too might be helpful if it's the case that a lack of atmos alert machinery around the map causes something like this; rather than returning no alerts, there just might not be anything to return the alert?
