### ISSUE TITLE
UI, presentation issues and crashes on Windows Server 2022

### ISSUE THREAD

**Issue by ShadowMarker789** [goonstation/goonstation#7061]
The UI frequently has terrible issues on Windows Server 2022, including: 

- Invisible Players 
- Memory Access Violations
- Broken Popup windows that cannot be dismissed 
- Broken UI components

Below is a screenshot of a broken popup and UI component. 

![image](https://user-images.githubusercontent.com/37165910/147886380-a510c316-f83a-4c74-8dc5-c0e00f3f55b1.png)

I managed to catch an exception thrown by a memory access violation, but since it's unmanaged code that I don't have debug symbols for I can't do much digging into it as-is. 

![image](https://user-images.githubusercontent.com/37165910/147886391-a1589811-eb91-4fff-b74e-a0451c761756.png)

The trait menu is completely unusable and unreadable. 

![image](https://user-images.githubusercontent.com/37165910/147886418-6277afc4-4b78-4787-90d5-368cc3a69654.png)

It is incredibly crash happy.

**Comment by ShadowMarker789** [comment]
Here's a screenshot in-game that took a while to take because the app kept crashing with all players invisible. 

![image](https://user-images.githubusercontent.com/37165910/147886596-c9afc807-80b3-4c15-91e6-0c54ae18f81d.png)

Interestingly the chat log has this message about window-resize-event not recognised. 

![image](https://user-images.githubusercontent.com/37165910/147886617-fb938fb6-94ea-4b97-8459-c61876434c27.png)

**Comment by ZeWaka** [comment]
use a real OS
