### ISSUE TITLE
Ice floor tiles (and possibly other matsci things with ice)

### ISSUE THREAD

**Issue by Zonespace27** [goonstation/goonstation#7075]
### Labels

[BUG]

### Description

Ice floor tiles can melt into 0 tiles, letting them be used infinitely

### Steps to reproduce

1. Obtain ice floor tiles
2. let them melt like regular ice
3. you now have 0 floor tiles

### Expected Behavior

Either to not melt, or to get deleted on melting

### Additional Information & Screenshots

Issue filled out on behalf of @Thatdude#3348

**Comment by Tarmunora** [comment]
Could not reproduce
