### ISSUE TITLE
Late joining into battle royale spawns you naked.

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#7079]
### Labels

[BUG]

### Description

When you late join into a battle royale game, you spawn in arrivals with no gear.

### Steps to reproduce

1. Have the game mode be BATTLE ROYALE
2. Late join into it for some laughs.
3. Be completely nude in arrivals on spawn.

### Expected Behavior

To at least be equipped with basic battler gear.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/148115385-ef30abb7-312d-40d7-8756-353d836dd16b.png)

**Comment by Zonespace27** [comment]
it's supposed to qdel you and force to observe, but seems that something broke

**Comment by flappybatpal** [comment]
Yeah you're supposed to be a ghost. Not sure if it's due to Osha.
