### ISSUE TITLE
Reanimation as Kuzo person while being an AI

### ISSUE THREAD

**Issue by Proximitron** [goonstation/goonstation#7081]
### Labels

[BUG]

### Description

Reanimation as Kuzo person while being an AI

### Steps to reproduce

1: You are an AI
2: Your body is found by kuzo people, you are transformed in a Kuzo person
3: This should not be possible as you are NOT DEAD

### Expected Behavior

Reanimation as KUZO should not work

**Comment by penny64** [comment]
Bad news AI, you are dead
