### ISSUE TITLE
AI omniscience by suicide

### ISSUE THREAD

**Issue by Warpmancer** [goonstation/goonstation#7103]
### Labels

[BUG]

### Description

AI can hear the entire station like it was a ghost, while alive.

### Steps to reproduce

1. Be AI.
2. Suicide.
3. Rejoin your Core.
4. You can now hear all talk like you're still a ghost.

### Expected Behavior

Suiciding as AI should set you to DNR and make you unable to rejoin your core, otherwise it's very easy to abuse even if the messages go away after you rejoin your core.

**Comment by TheTyrant25** [comment]
rejoin core... after suicide?
