### ISSUE TITLE
Portable computers lack a network card

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#7106]
### Labels

[BUG]

### Description

The only thing the laptop can detect are PR6 radios, and the network ping tool doesn't work on wireless

### Steps to reproduce

1. Login into the portable computer at tech storage
2. Insert a network tools disk
3. Try using ping
4. It will respond with an error, saying that there's no network card
5. Alternatively, using FROG's term_ping will just show up PR6 radios.
6. Doing this on top of a data terminal will bring the same results, but using the normal ping tool will now bring the same two PR6 radios instead of an error

### Expected Behavior

I expected it to properly connect, at least in the wired network

### Additional Information & Screenshots

![laptop glitch](https://user-images.githubusercontent.com/62149527/148538147-b332d569-8cac-4209-a078-d5023af51eb2.PNG)
![laptop2](https://user-images.githubusercontent.com/62149527/148538343-ef6a1c66-cb22-4fa6-90d1-2d7c84eade0a.PNG)

**Comment by Nexusuxen** [comment]
Portable computers are equipped with an omni-network card. By default this is configured to WNET mode; however, using the `periph` command you can change it to PNET mode. I forget the exact arguments you need but the command's help command is useful enough to get you there.

**Comment by Exester509** [comment]
Yep, I lack quite a lot of knowledge in these fields and it's hard to get answers. The wiki's information is also a bit confusing, so I might edit that as well. Thank you for your help
