### ISSUE TITLE
Radiation storm overlay disappears before radiation storm ends

### ISSUE THREAD

**Issue by evsey9** [goonstation/goonstation#7110]
### Labels

[BUG]

### Description

The radiation storm overlay disappears before the radiation storm itself ends

### Steps to reproduce

1. Have radiation storm happen
2. Wait in maint
3. Flashing radiation overlay disappears
4. Entire station collectively walks out of maint
5. Rapidly start taking damage
6. Extraplanetary HQ XVIII Mass Silent Death Incident

### Expected Behavior

I expected that the radiation storm overlay would disappear only after the radiation storm itself was over

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/7791364/148587384-4c55f316-4510-4c0a-a4fc-fec183f73536.png)
Funny

**Comment by MetricDuck** [comment]
Anecdotally I would add it doesn't seem to be consistent across all areas. The other day I observed the ranch lost its overlay prematurely but the adjacent-right kitchen retained the overlay right up to the all-clear.

**Comment by evsey9** [comment]
> Anecdotally I would add it doesn't seem to be consistent across all areas. The other day I observed the ranch lost its overlay prematurely but the adjacent-right kitchen retained the overlay right up to the all-clear.

Yeah, I recall that some time later, on a different round/map, the overlay worked more or less fine

**Comment by MetricDuck** [comment]
Linking this issue to #6615, #5669, #4946, #4125

**Comment by MetricDuck** [comment]
I was able to reproduce this on a local by triggering the event and then doing any of the following: 
- turning lights on/off
- causing a welder tank explosion
