### ISSUE TITLE
Pressure pads now activate too easily

### ISSUE THREAD

**Issue by Faulty** [goonstation/goonstation#7128]
### Labels

[BUG]

### Description

Any item that is sent via a teleporter and pressure pad to another teleporter and pressure pad gets sent back straight away

### Steps to reproduce

1. Make 2 pressure/teleporter setups that are linked together via mechanics
2. Place an item on one of them
3. It will get sent from tele 1 to tele 2 then back to tele 1 straight away

### Expected Behavior

The item should be sent to the 2nd pad but not activate the pressure pad straight away, thus allowing pressure/tele setups to work.

### Additional Information & Screenshots

![Untitled](https://user-images.githubusercontent.com/4073630/148668885-8d0bcbc0-853f-440c-b96d-6066c296c245.png)

Video: https://streamable.com/m0iy6b

**Comment by ZeWaka** [comment]
Not a bug
