### ISSUE TITLE
TGHud overlaps with storage hud

### ISSUE THREAD

**Issue by Zonespace27** [goonstation/goonstation#7138]
### Labels

[BUG]

### Description

The storage hud overlaps with the TGhud inventory.

### Steps to reproduce

1. turn on tghud
2. open a belt or backpack on you

### Expected Behavior

They not overlap

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/41448081/148725934-2e40465a-08dc-48c6-b8b3-45102154addd.png)

**Comment by MetricDuck** [comment]
Someone has fixed this already by moving the storage hud to the middle

![image](https://user-images.githubusercontent.com/86617057/197210381-900dcd09-9611-42e1-afc5-b203747cde39.png)
