### ISSUE TITLE
Corporeal wraiths can move through more than they should

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#7151]
### Labels

[BUG]

### Description

Whenever wraiths are revealed, either through haunting or being revealed by salt, they are capable of passing through a lot of things that they probably shouldnt be able to. The worst offender for this would be windows, given that you can't hit a wraith when they're inside one and quite a few windows lead to space/the ocean, making it almost impossible to actually chase revealed wraiths.

### Steps to reproduce

1. Be wraith
2. Be revealed through haunting/passing over salt
3. Walk through windows and various impassable objects that crew cannot go through

### Expected Behavior

Wraiths shouldn't be able to go through solid objects while corporeal.

### Additional Information & Screenshots

my guess is that this is caused by semi recent changes to how objects like windows handle blocking people, i recall some fixes were made as a result of kleptomaniac grabbing items through windows and blob membranes not working properly so maybe it has something to do with those?

**Comment by Exester509** [comment]
You are also slower than a person, being semi-corporeal would leave you extremely vulnerable without those ways of avoiding threats like an angry crewmate with a weapon. I'm pretty sure that's an intended feature

**Comment by kotomato** [comment]
wraiths only began working like this recently and there's no changelog to suggest theyve been intentionally changed, so i dont believe it's necessarily intended. regardless, the point of being revealed as wraith IS that you're vulnerable and can be killed, and having it so wraiths can walk into any window to become unclickable kind of breaks that

**Comment by evsey9** [comment]
feel like wraiths should be still able to go through some solid objects, like airlocks, so that they would have a chance to actually run, but still be reachable (unlike going through windows, where they become actually unreachable)

**Comment by frawhst** [comment]
fixed by yass a while ago
