### ISSUE TITLE
Gravity artifact bugs out cargo holds

### ISSUE THREAD

**Issue by TDHooligan** [goonstation/goonstation#7157]
### Labels

[BUG]

### Description

gravity warping artifacts supposedly eject cargo holds from pods when loaded, but without unloading them

### Steps to reproduce

1. activate gravity artifact
2. place into pod cargo hold
3. cargo hold (supposedly) ejects gracelessly, with the pod still referencing it
4. place in second pod for linked cargo holds

### Expected Behavior

either cargo hold is not ejected, or cargo hold ejects gracefully

**Comment by zjdtmkhzt** [comment]
Oh, yeah, just remembered this, definitely happens.^^
