### ISSUE TITLE
Airless stairs in owlery

### ISSUE THREAD

**Issue by MetricDuck** [goonstation/goonstation#7161]
### Labels

[BUG - MINOR]

### Description

Some of the stairs in the owlery don't have air

### Steps to reproduce

1. Go to owlery.
2. As you exit John Bill's shuttle take one step into the arrivals corridor onto the stairs. 
3. Suffocate. (location 1)
4. Progress through the owlery until you've powered the first security checkpoint and opened the first set of shutters. 
5. Head south to the room with animatronic owls on the tables. 
6. Hack the southern bolted doors and take one further step south onto the stairs.
7. Resume suffocating. (location 2)

### Expected Behavior

The stairs, like everywhere else around it, should have air. 

### Additional Information & Screenshots

location 2: https://imgur.com/a/nqVHln9

**Comment by TTerc** [comment]
huh yea, those stairs are indeed airless
fixed in 354f654dee446370871c4ca45a41b10c4592adb3
