### ISSUE TITLE
Yetis are very wonky

### ISSUE THREAD

**Issue by alexeric123** [goonstation/goonstation#7170]
### Labels

[BUG]

### Description

Yetis do not seem to run the same deathcode as everything else. Resulting in mindslave status not being removed, and ai shells being eaten kills the ai.

### Steps to reproduce

1. have a yeti eat the ai shell
2. ai core dies

1.. have a yeti eat a mindslaved person
2.. they are still mindslaved,   the "you are no longer a mindslave" pop-up appears if the person is then cloned and killed normally.

### Expected Behavior

Have it be the same death as everything else.

**Comment by MetricDuck** [comment]
Tested on a local and found that eyebot shells return the ai to it's core as normal, but custom cyborg shells turn the AI into a ghost.
