### ISSUE TITLE
Pickpocket gun + Item arms 

### ISSUE THREAD

**Issue by MRLinew** [goonstation/goonstation#7181]
### Labels

[BUG]

### Description

If someone uses a pickpocket gun on someone with an item arm, the item becomes bricked. both parties lose functionality of the item arm. Ex: a csaber arm, If it gets taken, the person with the csaber arm can no longer toggle it on/off, and they lose the icon in their hand.

### Steps to reproduce

1. Get a csaber arm
2. Get shot with a pickpocket gun
3. observe

### Expected Behavior

Id assume the pickpocket gun should just not work, maybe even an error message, "Unable to steal this item"

**Comment by zjdtmkhzt** [comment]
Should change this to jank the person with the item arm towards the person with the pickpocket gun. :D
