### ISSUE TITLE
Missing floor tile in VR Dungeon

### ISSUE THREAD

**Issue by MetricDuck** [goonstation/goonstation#7199]
### Labels

[BUG - MINOR]

### Description

One of the rooms in the VR Dungeon bedrooms appears to be missing a floortile, showing space instead.

### Steps to reproduce

1. Go to VR Dungeon.
2. Enter one of the first bedrooms underneath where you spawn in.
3. Observe a hole in the floor.

### Expected Behavior

For there to be a floor tile instead of a space tile.

### Additional Information & Screenshots

https://imgur.com/a/rw8ExiV

It is possible another player got there before me and caused this somehow. It wasn't just a graphical glitch - I took burn damage and suffocated on that tile.

**Comment by alexeric123** [comment]
Always thought that was intended, by the explosive damage on the surrounding tiles, but only Emily knows for sure.

**Comment by MetricDuck** [comment]
Went back and there was damage, my bad!
