### ISSUE TITLE
Right click features don't work things you hold/wear

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#7203]
### Labels

[BUG]

### Description

When you use right click to point/examine/pick up any item you are wearing or holding nothing happens.

### Steps to reproduce

1. Wear/hold anything
2. Right click on it to examine
3. Nothing happens.

### Expected Behavior

Be able to right click to point at my stuff

### Additional Information & Screenshots

Hotkey versions of this stuff still work but specifically the right clicking to pull up a mini menu of things to do doesn't.

**Comment by flrsh** [comment]
Seems fixed.
