### ISSUE TITLE
Antag critter robots spawning in VR

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#7204]
### Labels

[BUG]

### Description

Accepting antag robot respawn in VR respawns you in VR

### Steps to reproduce

1. Be dead and a ghost in VR
2. Accept an antag critter respawn
3. Respawn as robot

### Expected Behavior

Be placed in Z1

**Comment by frawhst** [comment]
c5ca610c558e5c8278dc211ee4f05fc21b85033b
