### ISSUE TITLE
Hemochromia blood splatters are black

### ISSUE THREAD

**Issue by keiyakins** [goonstation/goonstation#7207]
### Labels

[BUG]

### Description

Hemochromiatic blood pools are black instead of the appropriate color

### Steps to reproduce

1. Get Hemochromia-U
2. Wait for it to decay
3. Stab yourself

### Expected Behavior

I expect homestuck blood to come out, not tar. 

### Additional Information & Screenshots

Footprints work *occasionally*, other times they're red or black, and I really have no idea why. Noticed on the 'real' servers, tested further on local.

**Comment by TobleroneSwordfish** [comment]
I noticed this with Colorful Reagent too (which actually might just use the mutation behind the scenes, not sure)

**Comment by pgmzeta** [comment]
It looks like the blood splatter icons are red in the .dmi; so what is occurring is the red image is then having a colour applied to it.

The base colour is bright red, so adding on blues/greens just makes it look black. With red-heavy hemochromia mutations, it adds a very minor-to-unnoticeable effect.

This also applies to non-mutated blood splatters, as the image is still tinted with `DEFAULT_BLOOD_COLOR "#990000"`

Removing the saturation and having a grayscale base image might fix this (and potentially colorful reagent) for decals, at least.

**Comment by Nebulacrity** [comment]
Have there been any attempts at fixing this?
