### ISSUE TITLE
Ghost Drone flashlights broken

### ISSUE THREAD

**Issue by KamikazeMongoose** [goonstation/goonstation#7224]
### Labels

[BUG]

### Description

Flashlights in Ghost Drone inventories do not switch on

### Steps to reproduce

1. Become a Ghost Drone
2. Turn flashlight on/off a few times and it won't turn on
3. Ask if other ghost drones are having the same problem
4. They say yes and you get mad because it's dark ouch oof owie my eyeballs

### Expected Behavior

Flashlight ought to turn on when you activate it

**Comment by TobleroneSwordfish** [comment]
Also affects AI eyebots

**Comment by MetricDuck** [comment]
Timeframe suggests it's related to #7053 and 9f09cd5.
