### ISSUE TITLE
Lethal transmute artifacts turn borgs into both statues and parts

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#7260]
### Labels

[BUG]

### Description

Transmute artifacts turn borgs into statues and parts

### Steps to reproduce

1. Activate a lethal type transmutation artifact.
2. Have a cyborg in range that gets transmuted.
3. See them become both a statue and a robot frame and set of parts.

### Expected Behavior

Borg would just become a statue

**Comment by frawhst** [comment]
ha
