### ISSUE TITLE
chest item material sheets do not work

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#7266]
### Labels

[BUG]

### Description

title, the GUI opens but the button do nothing

### Steps to reproduce

1. grab steel sheets
2. implant them as a chest item
3. try to use them

### Expected Behavior

the steel sheets should be able to be used for building

**Comment by frawhst** [comment]
Fails because it checks if you're holding the sheets during the action, and you aren't (since they're inside you).
Not considering this a bug.
