### ISSUE TITLE
Fabric stacking creates fabric made of fabric

### ISSUE THREAD

**Issue by MetricDuck** [goonstation/goonstation#7284]
### Labels

[TRIVIAL]

### Description

Stacking material_piece/fabric/whatever creates a stack of "whatever whatever", which fabric made of itself. Applies the relevant icon effect to the pieces when separated out the stack as well.

### Steps to reproduce

1. Get multiple pieces of eg: /obj/item/material_piece/cloth/beewool.
2. Stack them in hand.
3. Note the name is now "bee wool bee wool",
4. Unstack a piece.
5. Note it now has the bee wool icon overlay effect.

### Expected Behavior

Things should just stack without becoming made of themselves

### Additional Information & Screenshots

Bug is marked as trivial as the material properties are preserved and material recipes are unaffected (ie: you can still make dyneema dyneema).

**Comment by UrsulaMejor** [comment]
Unable to replicate in sptember 2023; mayhaps it is fixed?
