### ISSUE TITLE
Lighters accept any chemical

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#7286]
### Labels

[BUG]

### Description

When attempting to refuel a zippo lighter, it will accept any chemical

### Steps to reproduce

1. Drain all the fuel from a zippo lighter
2. Click on a fuel tank with the empty lighter
3. A message shows up saying that you have refilled your lighter, now it's full of whatever chem you had in the tank. Combustible/exploding ones can be taken out by heating the lighter to ignition temp, while inert ones can't be taken out at all

### Expected Behavior

I expected it to only accept welding fuel, not all chems

**Comment by TobleroneSwordfish** [comment]
can't seem to reproduce this, was it a normal zippo lighter?

**Comment by Exester509** [comment]
> can't seem to reproduce this, was it a normal zippo lighter?

It was a golden one from a spacebux purchase

**Comment by Exester509** [comment]
Alright, by testing I discovered that it was some other chem that triggered it. The welder tank seemingly had some other chemical that wasn't welding fuel, and it took up the space in the zippo. I'll edit the bug report to notice this
