### ISSUE TITLE
AI Eyebot Shell Flashlights do not work

### ISSUE THREAD

**Issue by stonepillars** [goonstation/goonstation#7290]
### Labels

[BUG]

### Description

AI Eyebot Shell Flashlights do not work

### Steps to reproduce

1. Become AI
2. Enter your eyebot
3. Try to turn on flashlight

### Expected Behavior

Flashlight go brr

### Additional Information & Screenshots

The exact cause of this bug is that the flashlight is contained inside of a borg module inside of the eyebot instead of being contained directly inside of the eyebot.
I stumbled upon it while debugging an almost identical issue with ghostdrones but it smells like a pile of shit to fix and i'm no expert at borgcode

**Comment by penny64** [comment]
Fixed 10m ago
