### ISSUE TITLE
Donut's 3 library has 2 bookshelves stacked in a row on top of eachother.

### ISSUE THREAD

**Issue by SirSnek** [goonstation/goonstation#7302]
### Labels

[BUG]

### Description

The top row of bookshelves in the Donut 3 library has 2 instances of them.

### Steps to reproduce

1. Have the map be Donut 3
2. Go to the lovely library
3. Right click the top row of bookshelves
4. Anger >:(

### Expected Behavior

Only 1 bookshelf is in a bookshelf.

**Comment by TTerc** [comment]
Fixed in cae332ec039012802db88665e5d2d9928d319c18
