### ISSUE TITLE
genetic hotbar toggle disappears (probably invisible) after use

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#7305]
### Labels

[BUG]

### Description

Toggling the genetics hotbar makes the button disappear, which leads to you not being able to ever reach your genetic abilities again.

### Steps to reproduce

1. toggle the genetics hotbar
2. see the button disappear

### Expected Behavior

To be able to toggle back

### Additional Information & Screenshots

Right clicking suggests to me that the button is still there and that it's more of an icon state issue.

I'm using the TG style UI if that makes the difference.

**Comment by Sovexe** [comment]
sounds like an icon state issue
what theme?

**Comment by BatElite** [comment]
I use vectorized or whatever the neon one is called
