### ISSUE TITLE
Clean bots can't open doors

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#7317]
### Labels

[BUG]

### Description

Clean bots can't open a door if it's trying to path find past it.

### Steps to reproduce

1. Put a clean bot on one side of a door
2. Make a mess on the other side
3. Notice the cleanbot just point in aw at the mess you made

### Expected Behavior

For the cleanbot to open the door to clean a mess

**Comment by frawhst** [comment]
Cleanbots only have janitor-level access; does this occur for all doors, or just ones it doesn't have access to?
(if it's the latter, that's by design)

**Comment by Wisemonster** [comment]
Ah, didn't know that. Was a bot trying to open a kitchen door.
