### ISSUE TITLE
Computers can't connect to the print server

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#7326]
### Labels

[BUG]

### Description

Trying to connect to the print server using pcs is impossible, so you can't use the printers

### Steps to reproduce

1. Login to a pc
2. Open up wizwrite
3. Try to connect to the print servers using config
4. Can't

### Expected Behavior

To be able to connect to the print servers, to print things

### Additional Information & Screenshots

As far as I know, this bug has been around since at least the 27 of december.

**Comment by Conchuckter** [comment]
I was unable to reproduce this, might be because you were using a wireless network adapter?

If you are using a universal network adapter make sure the network adapter is set to mode_wire or else WizWrite won't be able to see it.

**Comment by Wisemonster** [comment]
Gonna double check, only really tested this on the donut 3 pcs

**Comment by Wisemonster** [comment]
Ok, so I'm not really sure what's going on. Most of the PCs on donut 3 can't connect, but the one in mechanics on atlas works fine. Also, the one in cog1's infomation office works, but the captain's and mechanics one doesn't connect.

**Comment by Conchuckter** [comment]
Yeah I was just playing on the actual servers and I was unable to connect, I also tried the cog 1's information offices pc and it also didn't work.

**Comment by soleilan** [comment]
Haven't been able to reproduce locally (duh) but so far I've live tested on Kondaru, Cog1, Atlas and Oshan and not seen issues. 🤷
