### ISSUE TITLE
Bush misidentified as Wooden floor

### ISSUE THREAD

**Issue by Aivaria** [goonstation/goonstation#7338]
### Labels

[BUG]

### Description

When shaking a bush you get a message about shaking wood floor

### Steps to reproduce

1. I dont know yet, if thats map dependand, so i stay with those infos too.
2. Join donut 3
3. Go south west of chapel
4. click the bush at the maintenance door
5. get the message about shaking wood floor

### Expected Behavior

Expected to see im shaking a bush, not a floor tile.

**Comment by TTerc** [comment]
Fixed in f90f99b448b942d2363019b66909e66628cfa6ea
