### ISSUE TITLE
Weird interaction between banana slip and treads

### ISSUE THREAD

**Issue by Johann-Strauss** [goonstation/goonstation#7350]
### Labels

[BUG]

### Description

If you slip on a banana peel with treads you cannot stand up again, but the game still treats as if you were. So you can interact, hold and use items.

### Steps to reproduce

1. Have a pair of Treads for legs
2. Slip on a banana peel.
3. Your sprite will look like you are laying down, but you are actually standing.

### Expected Behavior

I expect that you shouldn't be able to lie on the ground with treads, but since slipping forces you to, perhaps it has something to do with it?

**Comment by frawhst** [comment]
just fixed in 4b8d105

**Comment by Johann-Strauss** [comment]
Oh nice, thanks for the information!
