### ISSUE TITLE
The text log does not load in

### ISSUE THREAD

**Issue by Spell-Tech** [goonstation/goonstation#7351]
### Labels

[MAJOR]

### Description

The text log on the right side of the screen does not load in when I connect to the server.

### Steps to reproduce

1. Every time I join any server, the bug occurs.

### Expected Behavior

I expect that when I join the server I will be able to see IC, OOC, etc. as usual.

### Additional Information & Screenshots

![image_2022-01-29_205952](https://user-images.githubusercontent.com/83785819/151685014-128c7df4-3546-432d-9402-cf7c2fa339dc.png)

I closed the game during the middle of a round. When I rejoined, the text log did not load and has not loaded in since.

Before this, I was having a possibly related issue where the text log would not scroll down automatically whenever a new message was added, so I has to click the # new messages button every time.

Reconnecting, switching servers, restarting the game, restarting my PC, and joining on a different BYOND account have not fixed the issue.

**Comment by Aivaria** [comment]
Might be an caching issue, had that in the past too

- close the game

- Open Internet Explorer
- Click on the 'Settings' menu at the top right of the screen
- From the drop-down menu, move the cursor over 'Safety'
- From the submenu, select 'Delete browsing history'
- A dialogue box titled 'Delete Browsing History' would open before you. Select the check box beside 'Temporary Internet files and website files. If you wish to remove other data such as download history, cookie and website data and form data, you can select those as well. 
- Click on 'Delete' at the bottom of the dialogue box. Once done, Internet Explorer confirms with a message at the bottom of the screen

- after this, try again

(copied from https://www.republicworld.com/technology-news/apps/how-to-clear-cache-in-internet-explorer-here-are-5-easy-steps.html )

**Comment by Spell-Tech** [comment]
This fixed the issue! Thank you for the help!
