### ISSUE TITLE
Reclaimer doesn't give the correct items

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#7357]
### Labels

[BUG]

### Description

Reclaimer returns 1 block, 2 panels and 1 unnamed shard with plasmaglass properties when fed 10 plasmaglass panels

### Steps to reproduce

1. Collect or spawn 10 reinforced plasmaglass panes
2. Put them into the reclaimer
3. Get back more than you actually put in

### Expected Behavior

It should really only give you the one block. 

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/151725534-342ed62b-9c5e-4840-8a1a-a564e5894b55.png)
![image](https://user-images.githubusercontent.com/96703882/151725638-1322cf33-e8d1-45e3-931c-3a11bc1a0d27.png)

**Comment by soleilan** [comment]
cant reproduce locally, just spits out a block

**Comment by frawhst** [comment]
fixed at some point
