### ISSUE TITLE
Mutantrace Lisps and the DetGadget Hat

### ISSUE THREAD

**Issue by JackTrysGames** [goonstation/goonstation#7361]
### Labels

[BUG - TRIVIAL]

### Description

Half of the functions of the DetGadget hat do not work for mutantraces with lisps. Y'know, same issue the Lawbringer had.

### Steps to reproduce

1. Spawn in as a Saurian Detective.
2. Put your Det.net goggles into the DetGadget hat.
3. Say "go go gadget glassssssesss" a couple times.
4. Cry because you can't get the goggles out of the hat.

### Expected Behavior

I expected the hat to register "glassssssesss" as "glasses", so it would give me the glasses I put into the hat.

### Additional Information & Screenshots

Affected equipment:
Saurians - "Spray", "Flashlight", "Scanner", "Glasses"
Bovines - "Monitor"

**Comment by ThatFiveGuys** [comment]
Pretty sure this isnt a bug.

**Comment by UrsulaMejor** [comment]
Feature request, not a bug.
