### ISSUE TITLE
Antag Critter for Suicides

### ISSUE THREAD

**Issue by Connie-Dun** [goonstation/goonstation#7371]
### Labels

[BUG]

### Description

Can sign up for ghost critter even if died by suicide command.

### Steps to reproduce

1. Use the suicide command to die.
2. Get offered antag critter when the appropriate random event is rolled.

### Expected Behavior

Dying by Suicide command is supposed to render you ineligible

### Additional Information & Screenshots

I died by nano-crucible suicide in particular.

To be honest, this could just be the wiki being out of date, as that's what I am basing "Suicide prevents you from being offered ghost critter/antag" on.

**Comment by frawhst** [comment]
To my knowledge, there's nothing that checks if you've suicided in regards to antag critter offering- only DNR. Will update the wiki!
