### ISSUE TITLE
Ghostdrone consumes the telephone hook

### ISSUE THREAD

**Issue by CaioFrancisco** [goonstation/goonstation#7375]
### Labels

[BUG]

### Description

When a Ghost Drone interacts with a telephone, no one will be able to interact with it and the telephone hook simply disappears. The Ghost Drone is unable to put the telephone hook back to the telephone base.

### Steps to reproduce

1. Become a Ghost Drone
2. Attempt to use a telephone

### Expected Behavior

The Ghost Drone wouldn't be able to use the telephone at all.

**Comment by BatElite** [comment]
trying on local I can't get the hook to disappear, and turning back into human the phone seems to work fine after

use the phone and the hook spawns on the floor, magtractor on the phone doesn't do anything (though you can pick the hook up off the floor with it, which seems to act fine too?)

**Comment by CaioFrancisco** [comment]
Surprised to see my issue back here. Labelling this as needs reproducing.
