### ISSUE TITLE
Players with DNR set can still be enthralled by a vampire

### ISSUE THREAD

**Issue by Josephin23** [goonstation/goonstation#7379]
### Labels

[BUG]

### Description

Players with DNR set can still be enthralled by a vampire. DNR should prevent all resuscitation methods.

### Steps to reproduce

1. Die
2. Set DNR
3. Have a vampire use Enthrall on your body
4. Get revived

### Expected Behavior

The vampire cannot enthrall the player with DNR set

### Additional Information & Screenshots

Tested it on a fresh repo, should be relatively easy to fix by implementing a DNR check.
![obraz](https://user-images.githubusercontent.com/93096874/152327884-2bc9e535-744b-42e6-b7c7-6f6d5711688e.png)

**Comment by flappybatpal** [comment]
This doesn't sound like a bug to me, I would think this is expected behaviour.

**Comment by Josephin23** [comment]
Well alright then, couldn't find anything on this on the wiki, Still a bit mean though.
