### ISSUE TITLE
Botany: broken plant sprites

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#739]
[BUG]

**Describe the bug**
Clothing sprites are broken for synthbutts
Magic Fungus sprites are broken when planted
Venne and venne variants sprites are broken when planted

**To Reproduce**
1. Grow a synthbutt plant
2. Plant some magic fungus
3. Plant some venne/venne mutations
3. Put a butt on your head
4. Notice broken sprites
4. Scream

**Expected behavior**
Well this shouldn't be broken I guess

**Comment by BatElite** [comment]
Venne and magic fungus sprites look like they've been fixed at some point. Looks like the missing synthbutt sprites are all that's left.
