### ISSUE TITLE
Painting large pods using patterns (ie plaid paint) only paints a corner of the pod

### ISSUE THREAD

**Issue by MetricDuck** [goonstation/goonstation#7396]
### Labels

[MINOR]

### Description

Using plaid paint on large pods only paints a quarter of it, likely due to different icon sizes.

### Steps to reproduce

1. Acquire /obj/item/paint_can/rainbow/plaid.
2. Apply the plaid to a 2 by 2 pod.
3. Note you only managed to paint a quarter of it.

### Expected Behavior

Plaid should cover entire pod, either by tessellating pattern or by stretching.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/86617057/152619184-a3af9c1d-e2aa-4f3b-8925-227ae6d00fd0.png)

**Comment by amylizzle** [comment]
Fun update, this paints the pattern centrally now!
![image](https://user-images.githubusercontent.com/3855802/185745864-aedf5e00-70a6-419b-bfac-c0eb1f1bd8db.png)
