### ISSUE TITLE
Thrown Fiberwire Twangs When Clicked

### ISSUE THREAD

**Issue by Superlagg** [goonstation/goonstation#74]
**Describe the bug**
So I just got done choking a braindead HoP with the fiber wire, and went to toss him out into the hallway. The fiberwire got thrown instead, which is to be expected, but when I went to pick it back up, it just sat there on the ground and toggled through its deployedness states. I could still pick it up by clickdragging it to myself, but it was kinda silly that clicking on it just made it go twang.

**To Reproduce**
1. Strangle person with fiberwire.
2. Throw fiberwire while still strangling person.
3. Click on fiberwire.
4. Twang.

**Expected behavior**
The fiberwire just gets picked up.

**Screenshots**
.

**Additional context**
We were in the chapel at the time.

**Comment by ZeWaka** [comment]
note: `attack_hand` check if in mob?

**Comment by ZeWaka** [comment]
Apparently due to some fuckery with it being a two-handed item
