### ISSUE TITLE
Botany: crop names are incorrect

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#740]
[BUG]
**Describe the bug**
Crop names carry original plant names, example: eggs harvested from free range egg plant are called "egg plants", paper sheets harvested from paper trees are called "trees"

**To Reproduce**
1. Grow some paper trees and free range egg plants
2. Harvest the crops
3. Notice that crops are named incorrectly
4. Scream

**Expected behavior**
Paper sheets harvested from paper trees should be named "paper"
Eggs harvested from free range egg-plants should be named "egg"

**Screenshots**
(https://i.imgur.com/CtlPjgt.png)

**Comment by ZeWaka** [comment]
@AwkwardDryad you?

**Comment by AwkwardDryad** [comment]
I think this has something to do with the crop name on plant datums.
