### ISSUE TITLE
Biodome sliding wall puzzle autowalls

### ISSUE THREAD

**Issue by MetricDuck** [goonstation/goonstation#7402]
### Labels

[BUG]

### Description

The new autowalls in biodome caves make the sliding wall puzzle look strange (and the puzzle is much easier).

### Steps to reproduce

1. Go to biodome caves sliding wall puzzle
2. Observe walls

### Expected Behavior

Walls should look more seamless I guess? IDK if live autowall updates are practicable or would even look any better what with the flickering, etc,

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/86617057/152640313-55786670-416b-435d-9dbf-5f135993240a.png)

**Comment by TheTyrant25** [comment]
guessing this is still broken
