### ISSUE TITLE
The Plasma Toxin Damage Threshold Is Too Low

### ISSUE THREAD

**Issue by RikuTheKiller** [goonstation/goonstation#7440]
It's extremely annoying when even after completely air-scrubbing an area with no visible plasma particles whatsoever still causes toxin damage. This means clearing out plasma fires is even more annoying due to the issue.

Solution? Literally just raise the threshold for the toxin damage and the indicator.

**Comment by ThatFiveGuys** [comment]
Github issues are reserved for bugs, for suggestions for features/balance changes forums are a much better place to discuss these things.

**Comment by RikuTheKiller** [comment]
This is essentially a bug, as the atmospheric analyzer shows a 0% plasma concentration, but the tile still causes plasma toxin damage.

**Comment by TheTyrant25** [comment]
sounds like an issue with the rounding

**Comment by TheTyrant25** [comment]
im just gonna close this actually
A. the format of the bug report isn't correct. it's phrased like a request.
B. if fixing it is so simple why haven't you done it yourself? be less rude.
C. if this is really a huge problem then a new bug report will be filled out sooner or later.
