### ISSUE TITLE
Soulsteel Clown Car/Black Hole

### ISSUE THREAD

**Issue by Confusedxoz** [goonstation/goonstation#7448]
### Labels

[BUG]

### Description

A soulsteel object on a vehicle can send objects inside of them as long as they're pullable, or people...

### Steps to reproduce

1. Become soulsteel possessed object.
2. Switch to grab intent
3. Get on vehicle.
4. Grab people while on vehicle or object.
5. People/items are sent inside of you till you exit vehicle.

### Expected Behavior

Not becoming a clown car bug

**Comment by Confusedxoz** [comment]
You essentially become a Katamari/buffed clown car.

**Comment by rmeaper** [comment]
Please keep this in the game
