### ISSUE TITLE
Thindow doors don't have proper layering in the afterlife

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#7449]
### Labels

[BUG]

### Description

The windoors in the after life bar don't have proper layering, with people appearing on top of them

### Steps to reproduce

1. Go to after life bar
2. Get behind a door in the botany section
3. See error

### Expected Behavior

To not break quantom stuff

### Additional Information & Screenshots

![2022-02-08 (1)](https://user-images.githubusercontent.com/87689371/153121280-0edf4b44-bc95-4a36-ad60-363f8d1f2c49.png)

**Comment by TobleroneSwordfish** [comment]
![thindows](https://user-images.githubusercontent.com/20713227/153559042-6145791a-1428-4cd9-b206-15c0aa886eeb.png)

I'll have a look.
