### ISSUE TITLE
Mutant races cannot lose limbs from taking >30 brute damage

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#7474]
### Labels

[BUG]

### Description

So, within human_parts.dm (code/obj/item/mob_parts/human_parts), on line 18, there is a proc that leads to a percent chance of a mob losing a limb if they recieve >30 brute damage (further explained in additional info). This is entirely non-functional on mutant races

### Steps to reproduce

1. Spawn two tdummys
2. Polymorph one tdummy into any limbed mutant race (ie roach)
2. Spawn a weapon of any kind
3. Modify the weapon force var to be any number above 30 (ie 900)
4. Target any limb
5. Use harm intent to attack both tdummys with the weapon
6. Notice as the human tdummy's arm flies off, while the mutant race's arm stays connected
7. See bug

### Expected Behavior

For mutant races to have their limbs come off like humans

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/75814831/153700465-20e8b175-074a-4fca-ac1f-8d2f42165e1d.png)
relevant code in human_parts.dm

Further explanation of what the code does outside the description. It first checks if the damage is above 30 brute damage. If above 30 brute damage was taken, it then subtracts 30 from that number (30 - X), then the result becomes the percentage chance to lose that limb (30 - 74 brute damage = 44% chance to lose that limb). 

A thought I had, although makes 0 sense, is that this is defined above all the mutant race parts. If I am not wrong, this should make it part of the parent and applied to all mutant race parts too? 

Here is an example video of the issue

https://user-images.githubusercontent.com/75814831/153700573-1dac7bd1-f80d-4c86-897e-40ba15892cbc.mp4

**Comment by Tarmunora** [comment]
note: `var/organs` issue

**Comment by frawhst** [comment]
This got fixed a while ago
