### ISSUE TITLE
More chameleon projector jank (player teleportation)

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#7482]
### Labels

[BUG]

### Description

If you chest implant a chameleon projector and someone uses Brown Note, they will get teleported to you. (and also get disguised)

### Steps to reproduce

1. Install chameleon projector in chest
2. Have someone within brown note range use brown note
3. They are teleported to you

### Expected Behavior

They aren't teleported to you and disguised

### Additional Information & Screenshots

I really like the idea of having chest/arm chameleon projector get activated on other people, it is quite funny and makes for some great gimmicks. This however seems like something that should be fixed!

**Comment by frawhst** [comment]
you love to see it

**Comment by pali6** [comment]
@Sord213 you requested these bugs remain unfixed, does it apply here too?
