### ISSUE TITLE
Constructing and deconstructing Computer Terminal Frames gives back 2 extra plates

### ISSUE THREAD

**Issue by HBS-System** [goonstation/goonstation#7495]
### Labels

[BUG]

### Description

Constructing and deconstructing Computer Terminal Frames gives back 2 extra plates

### Steps to reproduce

1. Grab 3 plates that can be used to craft Computer Terminal Frames
2. Construct a Computer Terminal Frame
3. Weld the Computer Terminal Frame to deconstruct it.

### Expected Behavior

I expect the frames to give back 3 materials instead of 5, because... Well.. Yeah. You only need 3 to make one.

**Comment by Conchuckter** [comment]
Do we want to decrease the amount it gives to 3 or increase how much is need to make it to 5

**Comment by Conchuckter** [comment]
https://github.com/goonstation/goonstation/pull/7511
