### ISSUE TITLE
Botany: venne just outright breaks everything

### ISSUE THREAD

**Issue by TTerc** [goonstation/goonstation#751]
[BUG]

**Describe the bug**
This is a very major bug that I've been encountering for months now, I probably reported it twice already and to my surprise it's still there. It's really weird to describe but I'm gonna do my best to explain it. 
Basically once you plant any variant of venne, for some bizzare reason, multiple things about botany break at once:
-Seeds just disappear from the ground, after being vended, they also disappear from your hands
-Seeds turn into another seeds, example: I had white cannabis seed that turned into burning commol seed for zero reason, nobody in botany even planted it 
-Seeds when being put into plantmaster turn into seeds that are in close proximity to it. And they disappear from the machine while still being visible. So you end up with a list of seeds that you cannot vend, infuse, or splice

**To Reproduce**
1. Grab a portable seed extractor from hacked garden gear
2. Ideally plant venne and some venne mutation in two trays
3. Start vending seeds from the vendor, picking them up and putting them into plantmaster
4. Try splicing, ejecting the seeds
5. Plant at least two other seeds into other trays
6. Observe how harvested seeds behave
7. I'm pretty sure that at this point you'll notice the problem

**Expected behavior**
Um, botany not being weird and broken? I guess

**Additional context**
I noticed a weird behaviour about seeds being put into PlantMaster a few times while not messing with venne. But it seems that venne is just a very cursed plant that just somehow breaks everything

**Comment by Connie-Dun** [comment]
My status on replicating it:

1. Planted a Venne seed normally.
2. Dispensed 15 other seeds. Nothing unusual occurred.
3. Placed 3 seeds near the PlantMaster and put the rest into the machine. Nothing unusual occurred.
4. Spliced 2 seeds, twice. Planted them. Nothing unusual happened.
5. Planted 2 regular seeds. Nothing unusual happened.
6. Used the Portable Seed Fabricator to plant 6 Venne seeds.
7. Dispensed 3 seeds from the seed vendor. Only one of the three types came out; assumed it may have been a misclick. Clicking the two unobtained ones properly dispensed them.
8. Put apple seed, then chili seed into the PlantMaster. The apple seed turned into a chili seed instantaneously. 
9. Harvested the plants planted in step 4 and 5. Seeds were as expected.
10. Planted 2 new, non-venne, regular seeds.
11. Looked at PlantMaster. The two Chili seeds were replaced by two seeds of one of the plants I harvested.
12. Harvested the 2 new plants. One of them was a non-seed-producing plant and provided no seeds as expected. Unfortunately, the other was not potent enough to produce anything. Planted a 3rd new seed.
13. Harvested the 3rd new seed. Seeds were as expected.
14. Checked PlantMaster again. The two formerly-Chili seeds are still the harvested plant's type. Attempts to eject or splice them give no response. The fields from Type to E are completely missing.
15. Put two more seeds into the PlantMaster. Nothing unusual occurred.

This is a bit long-winded, but tl;dr: I was not able to replicate unusual harvests nor replicate disappearing seeds for sure. The PlantMaster, however, started acting unusual after I used the Portable Seed Fabricator to plant Venne but not after I planted Venne normally. The PlantMaster's behavior was not consistently dysfunctional.

**Comment by pali6** [comment]
At least the reproducible part is definitely caused by some wrong pooling while still holding a reference.

**Comment by pali6** [comment]
I'm not 100% sure about the exact cause but if anyone decides to fix this I recommend starting with turning all `new /obj/item/seed` and `new I.unique_seed` into `unpool`s and all `qdel`s of seeds into `pool`s. You might need to tweak how seeds' New works, specifically with the argument that chooses whether to create colour.

**Comment by TTerc** [comment]
Right. I tested it again and I'm 99% sure this bug is exclusive to portable seed fabricator. I was growing venne the whole round and messing with botany while only using the regular seed vendor. And I encountered no issues.

**Comment by flrsh** [comment]
Sounds like a fun thing to try and debug.

**Comment by Tiggersaurus** [comment]
I've had similar with the Borg seed fabricator, seeds vanishing when placing in the plantmaster, different names, sometimes even the plantmaster refusing to be clicked on. Some of it I just thought I was being forgetful but apparently not.

**Comment by ZeWaka** [comment]
think this was fixed multiple times, pooling stuff
