### ISSUE TITLE
Getting teleported to nullspace when stuck in a pipe loop

### ISSUE THREAD

**Issue by du5tball** [goonstation/goonstation#7513]
### Labels

[BUG]

### Description

When being sucked into a short loop, the screen goes black and the GPS gives out

### Steps to reproduce

1. Build a short loop
2. Get sucked in by it

### Expected Behavior

See something / have a working GPS, like when you're in Pipehell

### Additional Information & Screenshots

Mechanics apparently built a very short loop from what I could see (2x2), I got sucked into it, spun a few times and then the map went black and the GPS gave out, as if I'd been teleported to an inexistent z-level.

**Comment by stonepillars** [comment]
I'll try to replicate this, but this sounds like the disposalHolder getting qdel'd for whatever reason.

**Comment by MetricDuck** [comment]
![set_loc(null)](https://user-images.githubusercontent.com/86617057/154807735-da42b0d7-4e5e-4bfd-98dc-9eec1d4ef6dc.gif)
