### ISSUE TITLE
Chat Not Loading

### ISSUE THREAD

**Issue by Zathaniel** [goonstation/goonstation#7529]
### Labels

[BUG]

### Description

Self-explanatory, my chat won't load and it told me to report it here.

### Steps to reproduce

1. Launch a Goonstation server 

### Expected Behavior

2. Watch the chat not load

### Additional Information & Screenshots

I suspect this might be due to me running Windows 8 as my OS, I've had previous difficulties getting chat displays on other games and servers to load properly.

**Comment by Conchuckter** [comment]
If it is because of your OS that might be a byond issue

**Comment by frawhst** [comment]
Unlikely to be fixed without a lot more information/testing
