### ISSUE TITLE
Dream plaza mall table issues

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#7532]
### Labels

[BUG][trivial]

### Description

Table doesn't look how it should

### Steps to reproduce

1. Go to dream mall
2. Kill securitron and go into main area
3. See stinky table

### Expected Behavior

Table should merge with the ones near it

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/154589539-a09b9f45-dd7e-4832-aec1-816411b20eca.png)

**Comment by MetricDuck** [comment]
Linking to #4879
