### ISSUE TITLE
Suiciding Again After Failed Suicide Into Full Pickle Jar

### ISSUE THREAD

**Issue by Jak27** [goonstation/goonstation#7543]
### Labels

[BUG]

### Description

When I try to suicide into a jar that already has something in it, it says I cant climb in because its full, ok so I take it out and then I suicide again, but instead of the normal popup, I just die on the spot

### Steps to reproduce

1. Obtain a pickle jar that is full with something in it
2. Suicide into pickle jar
3. Be told you cannot suicide into a full jar
4. Remove object from jar
5. Type suicide again into console
6. Die on the spot

### Expected Behavior

I should have gotten the suicide option UI instead

**Comment by 112358sam** [comment]
I could not replicate this on local. There seems to have been edits to the suicide proc since your report. Maybe it has been fixed?

**Comment by pali6** [comment]
Using suicide while already suiciding does a succumb. The jar suicide failure states should unset the suiciding status from the mob as a fix.

**Comment by pali6** [comment]
Actually this seems to be the case already. Unable to reproduce the issue.
