### ISSUE TITLE
Chemicompiler fails to mix chemicals after transfer

### ISSUE THREAD

**Issue by triacontakai** [goonstation/goonstation#755]
[BUG]

**Describe the bug**
Note: ~I don't know if this is actually related to the chemicompiler~ looks like it is related, or maybe specifically ammonia production, but that's where I encountered this

The chemicompiler sometimes doesn't seem to mix chemicals that it transfers into the same beaker (e.g. in my case, nitrogen and hydrogen just stay static inside a beaker, and don't mix into ammonia)

**To Reproduce**
This is the chemicompiler code used:
`+}'++++++++)@{+}+'@`
Description of the code:
sx = 1:		+}
ax = 1:		'
tx = 9:		++++++++)
transfer:		@
sx = 2:		{+}
ax = 3:		+'
transfer:		@
Nitrogen is in r1, hydrogen is in r2, target is r9

1. Copy code above into chemicompiler
2. Put nitrogen beaker into r1, hydrogen into r2, and target into r9
3. Run code a few times
4. See that sometimes ammonia is formed, and other times it isn't

**Expected behavior**
The nitrogen and hydrogen always mix into ammonia

**Screenshots**
![Mixing Failure Image](https://i.imgur.com/CwU8ogJ.png)

**Additional context**
Ethanol in the screenshot is not relevant, it's just part of the bigger program I was making
TODO: TEST WITH HIGHER AMOUNTS

**Comment by triacontakai** [comment]
Tested this with adding 3u hydrogen first, and 1u nitrogen after. Same problem can occur.

**Comment by triacontakai** [comment]
Could not reproduce in a chem dispenser with the same amounts after many trials.
Looks like it is related to the chemicompiler

**Comment by triacontakai** [comment]
Possibly related: sometimes when the ammonia mixes properly, there's a tiny amount of hydrogen left over. Maybe some kind of floating point error thing?

**Comment by MarkNais** [comment]
I ran some tests myself on local.
Can confirm the issue exists in the ChemiCompiler regardless of adding hydrogen or nitrogen first.
I also experienced some 2.8e-7u leftovers, but that was very rare.
Notably, Yass was unable to reproduce this on local.

**Comment by triacontakai** [comment]
Tried testing with 6u hydrogen, 2u nitrogen, didn't get the effect to occur
Looks like it happens with low amounts only

**Comment by Tiggersaurus** [comment]
I've been told that being unable to eject mining materials from the fab might be caused by something related to this? Rounding errors?

**Comment by MarkNais** [comment]
@Tiggersaurus yeah I mentioned that in an mhelp.
It might be me assigning every problem involving math to rounding errors.

**Comment by TDHooligan** [comment]
potentially an issue to do with the relative closeness of generated spawns (and why an earlier machine tick patch was made) 
testing a patch for this now

**Comment by TDHooligan** [comment]
nope! agree it seems to be rounding related
![image](https://user-images.githubusercontent.com/6061314/84809150-946f4f00-b001-11ea-8cc6-c15c384a46cc.png)
