### ISSUE TITLE
Crashing as AI Eye Ghost causes the player to die.

### ISSUE THREAD

**Issue by avimour** [goonstation/goonstation#7561]
### Labels

[BUG]

### Description

Crashing while crusing around as the AI eye ghost causes the player to go full ghost//dead. However, the AI core looks completely fine. Leading to confusion from everyone in-game.

### Steps to reproduce

1. Be AI and cruise around as the AI eye ghost.
2. Crash for whatever reason.
3. Reopen game and find out that suddenly you're dead and have a respawn timer (if on RP).

### Expected Behavior

I expect to not die due to a crash, and at the very least for my core to go to the BSOD face when I do.

### Additional Information & Screenshots

Honestly I think this is might just be an issue with how the AI eye ghost works?

**Comment by amylizzle** [comment]
I haven't been able to replicate this.
I've tried:
1. Joining as AI, cruising around as AI eye for a bit, killing the client with taskmgr and rejoining
2. As above, but killing with taskkill /F

If you could post the round ID that would be helpful - it might be that you were killed while disconnected, or something else weird happened.

**Comment by avimour** [comment]
Not exactly sure if this is right, but here's the round that it happened! https://goonhub.com/rounds/126211
My AI name is TURTLE and it does show that I died from, nothing basically, at the time I crashed. 
It did happen while I was in mid zooming past the bar, and my game was chugging a bit due to internet being cruel.

**Comment by amylizzle** [comment]
Well, we tried killing and deleting the AI eye in a bunch of fun and interesting ways and still could not trigger this crash or state. 
Hopefully this was just a super rare bug that won't ever happen again. 
If this happens to anyone else, please let us know with as many details as you can regarding the state of the game at the time.

**Comment by frawhst** [comment]
My guess for what happened is that during the crash the game interpreted you as holding whatever keys you had pressed at the time (not uncommon when the game crashes to reconnect and be at the other end of the hall, or deep space in the case of an AI eye).
On oshan, hitting the edge of a Z level would instantly kill and ghost you. Fixed in 4bac70d0928bb50a545c250e4fa7fc35982d8bc2

**Comment by MetricDuck** [comment]
This person was ghosted properly (name set up and everything), but not gibbed.
