### ISSUE TITLE
Error at game startup

### ISSUE THREAD

**Issue by Vhare55** [goonstation/goonstation#7566]
### Labels

[BUG]

### Description

Can't play game

### Steps to reproduce

1. Click on {Join} Goonstation 1
2. Error appears right after

### Expected Behavior

I expected to be able to play

### Additional Information & Screenshots

![Captureerror](https://user-images.githubusercontent.com/100077183/154844718-e0840c8a-7cc3-41f6-ad55-a99a8caa55c6.PNG)

**Comment by amylizzle** [comment]
You need IE11 installed and working. BYOND relies on an essential IE11 component to do it's rendering, and from the looks of your setup it isn't there.
Note: IE11 does not work on wine, if you're trying to do spessgame on linux, you need to use a virtual machine.
