### ISSUE TITLE
AI laws can be updated too frequently

### ISSUE THREAD

**Issue by du5tball** [goonstation/goonstation#7586]
### Labels

[BUG]

### Description

AI laws can be updated too frequently

### Steps to reproduce

1. Update laws
2. Update laws
3. Update laws

### Expected Behavior

Give it at least some kind of a cooldown

### Additional Information & Screenshots

See https://goonhub.com/rounds/126359, "bolt open all doors", law reset, unbolt all doors, "bolt open all doors" again. rinse and repeat a few times.

There needs to at least be some cooldown after the laws reset. In the linked round, two people had remotes to upload laws so even the disassembled upload computer didn't help. One spammed the same upload several times in quick succession, which doesn't change laws, but still pings all silicon and clutters chat to the point of making AI unable to respond to requests / commands.

**Comment by BatElite** [comment]
There is a ten second cooldown already, do you have something else in mind?

**Comment by du5tball** [comment]
I'm rather certain the 10 second cooldown didn't work, since in one instance AI got three resets within that time. I'd wish for the timeout to be 2 to 5 minutes after a law reset happened, where no resets nor uploads can happen, no matter the way chosen. Although considering how rare it is that someone spams law updates, I'm not sure how feasible that actually is.

**Comment by ThatFiveGuys** [comment]
New system no longer a thing really
