### ISSUE TITLE
blueprint marker does not make steel reinforced glass windows glow

### ISSUE THREAD

**Issue by Araulius** [goonstation/goonstation#759]
**Describe the bug**
Blueprint marker either does not, or insufficiently displays marked windows. this also applies to airlocks.

**To Reproduce**
1. Attempt to mark an airlock, or a window
2. Try to identify if it's been marked or not.

**Expected behavior**
marked structures should glow green

[BUG]

**Comment by Tarmunora** [comment]
Only turfs get marked by the marker currently

**Comment by ZeWaka** [comment]
This is a feature request, which should be done on our forum: https://forum.ss13.co
