### ISSUE TITLE
Spaced diner patron

### ISSUE THREAD

**Issue by De-Luuk** [goonstation/goonstation#76]
**Describe the bug**
When i joined with the "space diner patron" spacebux reward i spawned outside of the diner, on the solar panel, just south of the actual dining area.

**Steps to reproduce the behavior:**
1. Join game as "space diner patron"
2. Run to nearest airlock to not die

**Expected behavior**
I would expect to spawn inside of the diner, tho arguably it could be a funny intended side effect.

**Comment by ZeWaka** [comment]
@De-Luuk Which map was this on?

**Comment by flrsh** [comment]
Mapping bug with misplaced area, will look into.

**Comment by flrsh** [comment]
Fixed in fc380a03ed0171512727e439b8235b6948e3a189.
