### ISSUE TITLE
Opening a working TTV, phase shifting and dropping it mid-shift causes the TTV to explode while Wizard is invulnerable

### ISSUE THREAD

**Issue by mikecsiy** [goonstation/goonstation#7617]
### Labels

[BUG]

### Description

TTVs opened then dropped mid phase-shift do not harm the wizard

### Steps to reproduce

1. Be a wizard
2. Acquire a functional TTV
3. Manually open the valve
4. Phase shift
5. Drop the TTV while shifted
6. It explodes, damaging the station and nearby crew while leaving the wizard unharmed

### Expected Behavior

TTV either fails to explode or wizard takes damage from the explosion

**Comment by AmazingDragon353** [comment]
I think this is intentional, not a bug, as afaik the wizard's supposed to be invulnerable while phase shifting, though it does raise balance concerns.

**Comment by Yawet330** [comment]
> I think this is intentional, not a bug, as afaik the wizard's supposed to be invulnerable while phase shifting, though it does raise balance concerns.

The main issue is that they're still able to interact with objects in their inventory/hands while invulnerable, this includes dropping.

Things this can be done with:
Automatic-ignite welding tanks
Black-powder welding tank bombs
TTVs

Technically intentional but major balance issues.

**Comment by TobleroneSwordfish** [comment]
![image](https://user-images.githubusercontent.com/20713227/180672480-a2a317ab-bae3-46ed-ab1d-180fb410023f.png)
Not a bug, wizards are allowed to dodge damage with phase shift, open a PR or a forum thread if you want to change it.
