### ISSUE TITLE
Vendors unable to 'vend by name' items with apostrophe in the name through mech comp

### ISSUE THREAD

**Issue by OmegaShoots** [goonstation/goonstation#7621]
### Labels

[BUG]

### Description

Passing a signal into a vendor with the name of an item that has an apostrophe in it will not vend the item

### Steps to reproduce

1. Get a mech component
2. Wire it to vendor, vend by name
3. Attempt to input the name of item with apostrophe, ie "Discount Dan's x"
4. Item will not vend

### Expected Behavior

Item should be vended

### Additional Information & Screenshots

There is also some vendors that do not vend items, even without apostrohes. I will have to test more of those.
One item I know for certain, although it could be more, is an Analysis Made Easy cartridge from the pda cartridge vendor.

**Comment by OmegaShoots** [comment]
It also seems the entire selection of cartridges from the cartridge vendor are unable to be vended with 'vend by name' inputs either, but the things that are not cartridges CAN be vended, the PDA and High-power flashlight module.
Unsure if this needs a separate issue report or not.

**Comment by frawhst** [comment]
fixed this a while ago but forgot to close the issue
d132b02cbcea7394582ce4d49e0c8e8526ff07db
