### ISSUE TITLE
surplus crates sometimes contain more stuff than they should

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#7628]
### Labels

[BUG]

### Description

If a surplus crate contains another surplus crate, the total TC value of all the stuff between the two crates is greater than would be expected from two crates

### Steps to reproduce

1. Buy surplus crates until you get one that contains a surplus crate
2. Count the total TC of the stuff in the first crate
3. Open the second crate
4. Count the total TC of the stuff in the second crate
5. jesus christ I'm at 67 TC ignoring the surplus crate only stuff the wiki doesn't list the price of

### Expected Behavior

The total value of the stuff contained in a surplus crate containing a surplus crate should be no more than 48 TC, counting the 12 TC for the second crate.

### Additional Information & Screenshots

My best guess is that it's putting the contents of the second crate into the first crate, and then still spawning a second crate that contains stuff.  It's worth noting that the stuff in the second crate is not listed as being contained in the surplus crate at round end.  Only problem there is that would give a maximum of 72 TC and the specific one that led to this report was even more than that, so either surplus crates are no longer containing 18-24 TC of stuff or it's not properly displaying how many surplus crates the surplus crate contained.

**Comment by pali6** [comment]
Feature
