### ISSUE TITLE
Weird visual bug on cogmap2

### ISSUE THREAD

**Issue by Laboredih123** [goonstation/goonstation#7649]
### Labels

[BUG]

### Description

A tile in the West Electrical Substation appears as a wall

### Steps to reproduce

1. Look at tile

### Expected Behavior

The tile to appear as a floor

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/62359847/155914529-7b4580fc-449f-45a3-9557-2fb0d027b528.png)

**Comment by stonepillars** [comment]
Appears to be a wall in StrongDMM.

**Comment by Laboredih123** [comment]
How fun
