### ISSUE TITLE
Syndicate record does not play

### ISSUE THREAD

**Issue by Conchuckter** [goonstation/goonstation#7651]
### Labels

[BUG]

### Description

When attempting to play the new syndicate record I was unable to hear anything.

### Steps to reproduce

1. Go to the syndicate battle cruiser.
2. Enter the radio room
3. Attempt to play the unique record
4. Be sad cause you can't hear the banger tunes that you were promised.

### Expected Behavior

To hear the records contents

**Comment by frawhst** [comment]
Good, I'm not going senile. Played fine on a local, haven't seen it work on live (in 3 attempts)

**Comment by Conchuckter** [comment]
Me want the funny syndicate music NOW!

**Comment by Conchuckter** [comment]
Where is the code for the record located?

**Comment by frawhst** [comment]
https://github.com/goonstation/goonstation/blob/75c6740754616d12da2a823a32d221b01a518b36/code/modules/telescience/radiostation.dm#L540

song is `sound/radio_station/music/second_reality.s3m`

**Comment by Conchuckter** [comment]
Wait could this be because of the file type?

**Comment by virvatuli-gh** [comment]
This was either fixed or just a brief blip because it works fine currently. s3m is a tracker format (similar to .mod as an example) and yes, our music system can play it.
