### ISSUE TITLE
Setting DNR, Then Clicking Spawn As New Character, Then Observing Instead, Unsets DNR And Allows Cloning

### ISSUE THREAD

**Issue by HarleyLorenzo** [goonstation/goonstation#7652]
### Labels

[BUG]

### Description

Setting DNR, Then Clicking Spawn As New Character, Then Observing Instead, Unsets DNR And Allows Cloning

### Steps to reproduce

1. Goon RP rules (not sure if it works on Goon 1/2)
2. Set DNR while dead and clone scanned
3. Wait 10 minutes, click spawn as new character, but don't spawn as one, instead click observe
4. DNR is unset, you are able to be cloned, while observing and having previously set DNR

### Expected Behavior

Shoudln't be able to be cloned and DNR should be respected

**Comment by frawhst** [comment]
DNR moved to player datums so this is very unlikely to be an issue still
