### ISSUE TITLE
Wizards revived with Soulguard don't receive their VISOR back

### ISSUE THREAD

**Issue by deepfreezedefender** [goonstation/goonstation#7653]
### Labels

[BUG]

### Description

Heard from a friend that their character with blindness trait properly spawns with a VISOR as a wizard but after a death with Soulguard they spawn naked w/o VISOR, forcing them to sneak into medbay blind to steal one.

### Steps to reproduce

1. Be wizard
2. Get maimed and killed
3. Soulguard kicks in
4. Respawn blind
5. Wiznerd stumbles into medbay saying oh no, my g-glasses! I d-dropped them!

### Expected Behavior

Get a VISOR after being revived unconditionally, such as after cloning or in the afterlife bar.

**Comment by Conchuckter** [comment]
Probably not after cloning but I agree withvm the other ways

**Comment by deepfreezedefender** [comment]
Cloning does give you your VISOR back, right from the get go

**Comment by MetricDuck** [comment]
Same as #4503
