### ISSUE TITLE
various icons missing in menus

### ISSUE THREAD

**Issue by storm37000** [goonstation/goonstation#7655]
### Labels

[BUG]

### Description

some icons are missing on chui custom window frame and in chat area.

### Steps to reproduce

1. Just load into the main screen.

### Expected Behavior

Icons to render

### Additional Information & Screenshots

[screenshot 1](https://onedrive.live.com/?authkey=%21ACqsKV91Zh5zA4w&cid=9F6EC0A9F96610B8&id=9F6EC0A9F96610B8%215741&parId=9F6EC0A9F96610B8%215478&o=OneUp)
[screenshot 2](https://onedrive.live.com/?authkey=%21ACqsKV91Zh5zA4w&cid=9F6EC0A9F96610B8&id=9F6EC0A9F96610B8%215740&parId=9F6EC0A9F96610B8%215478&o=OneUp)

**Comment by ZeWaka** [comment]
cdn/chui/network issue
