### ISSUE TITLE
The AI map doesn't work on live

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#7661]
### Labels

[BUG]

### Description

The AI map is blank and does not work

### Steps to reproduce

1. Join a live server as AI
2. Click "Open station map" verb
3. The map is blank and does not work

### Expected Behavior

I expected my code to not be shit

### Additional Information & Screenshots

#7577
It works fine on latest master running locally, so I can't really debug it.
Just posting this here in case anyone has had it work on live or has any idea what would be different between live and local so I can try to fix.
aaaaaaaaaaaaaaaaaaaaa

**Comment by pali6** [comment]
Hopefully fixed by https://github.com/goonstation/goonstation/commit/78c69a20859db8307ebe6e574291a42f1b2b8911
Bug me to reopen this if not
