### ISSUE TITLE
Conspirator Naming Error

### ISSUE THREAD

**Issue by JackTrysGames** [goonstation/goonstation#7664]
### Labels

[BUG - MINOR]

### Description

Name shows up as "Unknown" on roundstart Conspirator list.

### Steps to reproduce

1. Spawn in as a job that has no ID and a mask at roundstart. (Examples include Clown, due to the roundstart name change, or Scientist if you have Stowaway.)
2. Roll Conspirator.
3. Check job list- your name shows up as "Unknown" _despite your actual name being different._

### Expected Behavior

I expected the name to appear regardless, so I wouldn't accidentally call my teammate a self-antag.

**Comment by JackTrysGames** [comment]
Possible fix- Add a flag similar to a SecHUD flag that lets you know who your fellow conspirators are.

**Comment by TobleroneSwordfish** [comment]
I don't think conspirators should have an overlay, because it doesn't really fit in RP and not always being entirely certain of who your allies are is very conspiracy like.
