### ISSUE TITLE
You were about to be transferred into another body, but that body was pending deletion! This may fuck everything up so if it does dial 1-800-CODER.

### ISSUE THREAD

**Issue by amylizzle** [goonstation/goonstation#7667]
### Labels

[BUG]

### Description

I threw my AI shell into the void, got it eaten by a ghost, and then went back to it

### Steps to reproduce

1. Telesci until the VOID opens
2. Be AI
3. Deploy to eyebot shell
4. Fly my eyebot shell into the void portal
5. Encounter the Transposed Particle Field ghost
6. Get eaten
7. Deploy to *same* eyebot shell, which for some reason is still in the list
8. ERROR: You were about to be transferred into another body, but that body was pending deletion! This may fuck everything up so if it does dial 1-800-CODER.
9. I'm an eyebot in space somewhere and I don't have HUD

### Expected Behavior

Shell gets deleted, stops being in my deploy list

**Comment by frawhst** [comment]
Fucking science ghosts. They don’t kill you, they just delete you, which bypasses all the death handling for shells
