### ISSUE TITLE
Taking a shower removes Noir

### ISSUE THREAD

**Issue by JackTrysGames** [goonstation/goonstation#7676]
### Labels

[BUG - MINOR]

### Description

The Noir gene's visual effects are erased by taking a shower.

### Steps to reproduce

1. Get the Noir gene
2. (Most difficult part) Take a shower
3. Watch as your spessman's grayscale filter vanishes

### Expected Behavior

I expected the Noir effect to persist through the shower, so I could be clean AND noir at the same time.

### Additional Information & Screenshots

Unconfirmed effects with Reinforced Noir.

90% sure it doesn't actually remove the gene, and is just a visual bug.

**Comment by TobleroneSwordfish** [comment]
Feature: you're washing off the grime of the gritty cyberpunk streets.

**Comment by zjdtmkhzt** [comment]
Also happens from stuff like sponging someone down, or splashing them with space cleaner.
