### ISSUE TITLE
Manually Constructed APC in a room made by ABCU does not power it.

### ISSUE THREAD

**Issue by Araulius** [goonstation/goonstation#770]
After constructing a new room in space with the abcu,  I manually constructed an APC, but it did not provide power to the lights, or the door.

1. Construct New room with ABCU
2. Construct new APC manually
3. Lights do not turn on, and door does not open despite the apc having charge

**Expected behavior**
The lights turn on, and the door opens.

**Screenshots**

https://gyazo.com/88a97ea33af0f94f8d4d9bc9c07b34a6

Edit: charging the apc more with an experimental local generator didn't fix it either.

[BUG]

**Comment by trerri** [comment]
This is because ABC-U does not construct an area. Have you tried renaming the APC with a pen? I don't exactly remember but I'm pretty sure it creates a new area

**Comment by Araulius** [comment]
> This is because ABC-U does not construct an area. Have you tried renaming the APC with a pen? I don't exactly remember but I'm pretty sure it creates a new area

you can name the area by using the labeler on the apc. but literally yesterday, i didn't need to do that in order for power to come on.
