### ISSUE TITLE
Failed TTVs delete the gas container in a weird way

### ISSUE THREAD

**Issue by amylizzle** [goonstation/goonstation#7709]
### Labels

[BUG]

### Description

TTVs that fail to go off result in bugged tanks when disassembled

### Steps to reproduce

1. Make a TTV with a non-explosive mix (ie, plasma and oxygen straight from the cans)
2. "Detonate" it
3. dismantle the resulting tanks 
4. Congrats, you have weird bugged tanks - don't put them in a cannister or it'll get in a weird state you can't use.

### Expected Behavior

Dismantled TTVs that fail to detonate should result in tanks containing either a mixture of the input gasses or no gas. They shouldn't be jank.

**Comment by frawhst** [comment]
I think I fixed this?
