### ISSUE TITLE
Certain food items are missing reagents

### ISSUE THREAD

**Issue by mopcat** [goonstation/goonstation#778]
[BUG]

**Describe the bug**
Certain food items produced through cooking don't have the reagents they should have, making certain chems unobtainable.

**To Reproduce**
1. Create either a buttburger, roburger, or any other food item with reagents using kitchen equipment and raw ingredients, or a smoldering mass/????/the very concept of fried foods with an invalid recipe.
2. Scan food item with reagent scanner.
3. Place in reagent extractor.
4. Extract into storage tank or beaker.
**Expected behavior**
The food is supposed to be extracted by the reagent extractor and the reagents sent to the extraction target. The reagents are also supposed to show up when scanned by a reagent scanner.

**Comment by UrsulaMejor** [comment]
Unable to reproduce with ????, smoldering mess, or very concept of fried foods. These items all had their reagents on creation and extracted properly.

Brainburgers, buttburgers, and roburgers produce their reagents on consumption, and not being able to extract them is an intended feature. I confirmed that these two items did work properly.

**Comment by UrsulaMejor** [comment]
Actually, just double checked, and the brainburger DID have prions pre-consumption O:

It also extracted properly. Both of those things are news to me.

**Comment by UrsulaMejor** [comment]
Unable to reproduce; everything seems to work as you expect, except buttburgers don't have reagents (and I don't think they're supposed to)
