### ISSUE TITLE
Scorching some tiles leave a black void

### ISSUE THREAD

**Issue by Merlin1230** [goonstation/goonstation#7781]
### Labels

[BUG]

### Description

whenever some tiles (the rainbow tiles and the ranch dirt both did this) get scorched, like from seething tomatos,  they leave a void behind instead of some scorched sprite

### Steps to reproduce

1. Start a fire to scorch a tile
2. Sometimes, the tile will just be a black void

### Expected Behavior

To be replaced with a scorched sprite, like the default one for steel tiles.

### Additional Information & Screenshots

screenshots:
![image](https://user-images.githubusercontent.com/76177064/158039676-d113eb8e-0e92-484b-8fe3-1f005facbb7a.png)
![image](https://user-images.githubusercontent.com/76177064/158039679-37744937-4402-4bf3-a80b-311b9e1735ac.png)

**Comment by MetricDuck** [comment]
Fixed in #8699
