### ISSUE TITLE
MONO card generation flat out does not work properly

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#7793]
### Labels

[BUG][MINOR]

### Description

There's an issue with how MONO cards are generated which breaks the `icon_state` of every card, setting it to the default value of `plain-1-1`. Cards which are drawn from a deck do not have the same card type as the deck they came from and cannot be placed back in the deck. Though the issue is relatively minor, it severely impacts how the card game is played.

### Steps to reproduce

1. Buy a box of MONO cards.
2. Draw a few from the deck.
3. Realise that their icons are fucked and the card types don't match when you try to place them back in the deck.

### Expected Behavior

For icons to work as intended and for the cards that are drawn to be of the same type as the deck they came from.

### Additional Information & Screenshots
_Front and reverse side of a "blue 4" card. Images by Gibus#1625 on Discord._
![image](https://user-images.githubusercontent.com/66253095/158062306-1aaba712-9f46-49fb-bae5-ae97a26849f7.png)
![image](https://user-images.githubusercontent.com/66253095/158062310-acc43bb0-d380-4c04-8e3c-d169fc86f3da.png)

**Comment by soleilan** [comment]
fixed?

**Comment by DisturbHerb** [comment]
aw man it didn't auto-close
