### ISSUE TITLE
New Prefabs loot (Portable Foldable Identification Computer) bugged, turns into base color (brown) when refolded

### ISSUE THREAD

**Issue by Crackaduck** [goonstation/goonstation#7830]
### Labels

[BUG]

### Description

I don't know why, but for some reason, the briefcase sprite and flavor text somehow reverted to the base portable briefcase ones when it was folded up once.

### Steps to reproduce

1. Go to new prefab when it spawns with a mining pod (Do not unfold the loot yet!)
2. Place the briefcase into the dresser, close it then open it, retrieve the briefcase
3. Go into the pod with the briefcase, still unopened in hand, and teleport back to the station
4. Unfold it on station, then fold it back up, it should be brown 

### Expected Behavior

It should be multicolored, with its flavor text, instead, it is a generic looking briefcase when folded up.

### Additional Information & Screenshots

on the topic of the briefcase, there are two fold up options, this can be fixed by deleting lines 105-113 on 'obj/machincery/computer/card/portable' in my testing, but given my testing proved insufficient, solve at your own pace.

**Comment by MetricDuck** [comment]
Struggling to reproduce this on local - with two different bug reports I don't doubt it happened, but I also can't see what might have fixed it
