### ISSUE TITLE
Nuclear operative bard class crate includes 2 studio monitors instead of the intended 1

### ISSUE THREAD

**Issue by ThatsMamaLuigiToYouMario** [goonstation/goonstation#7832]
### Labels

[BUG]

### Description

Minor bug, bard classes should only have one studio monitor pack, but the crate gives out 2 instead.

### Steps to reproduce

1. Acquire a syndicoin requisition token (such as through VR, playing as a nuclear operative or otherwise.
2. Redeem the token at an automated vendor and select the bard class.
3. Open the crate and find that the crate has given you a bonus speaker, as a treat.

### Expected Behavior

Vendor should only give out the one studio monitor instead of 2.

**Comment by frawhst** [comment]
I think this is intended? One for your back, one for leaving somewhere else

**Comment by Azrun** [comment]
> I think this is intended? One for your back, one for leaving somewhere else

💯
