### ISSUE TITLE
Capulettium ticks don't take mult into account, knockout lasts much longer than it used to.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#787]
[MINOR]

**Describe the bug**
Capulettium stuns the victim between the 12th and 60th cycle. This used to amount to around two minutes in the past.
However, some time ago, certain modifications were made and things tick slower. "mult" was added as a sort of compensation for this, where it multiplies the chemicals' effects to achieve the same results while cutting down on the amount of ticks.
So, instead of a chemical for example ticking from 1 units to 0.8 and again to 0.6 in short intervals, it goes from 1 to 0.6 in a slightly longer interval, with the same (if properly implemented) for their effects.
It appears that capulettium doesn't take mult into account and still just counts the cycles, checking whether it's between the 12th and 60th, basically meaning that the effective knockout duration was drastically increased.

**To Reproduce**
1. Ingest capulettium.
2. Knockout lasts much longer than the two minute amount recorded both on the wiki and relevant code comments.

**Expected behavior**
Taking the tickrate changes into account, perhaps using the mult in calculating counter increments?

Though very likely a bug, it appears to have been around for a decent amount of time, so it's also unintentionally a balance topic of sort, though I don't think that's very significant as these values should be easy to adjust if needed.

**Comment by zjdtmkhzt** [comment]
Using the multiplier in the incrementation of the counter seems to already be the way things are done in a lot of other chems (rajaijah, stable mutagen, sarin, etc...), so I am guessing this was just overlooked and it would be good to do it in the same way for consistencies sake.

Also, I haven't used capulettium a lot recently, but the old cap on the time it lasted seemed pretty alright. (From before the multiplier change).
