### ISSUE TITLE
Borgs can only quote the original AI Uploads laws (probably?)

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#7871]
### Labels

[BUG] [[MAJOR]

### Description

After doing testing, even after having fully connected to a new AI Upload with a separate set of laws, the borg could still only Quote the laws from the original AI Upload, even though they were not the laws they had. Interestingly, even after connecting to the mechanics upload and confirming that the laws were for mechanics, the linker still stated they were connected to AI upload.

### Steps to reproduce

1. Create a second upload.
2. Attempt to link a borg to the new upload
3. Encounter above description.

Notably, the borg couldn't be connected to the new AI Upload until after we went to the original upload and connected the linker/borg to that, and then connected it to the mechanics upload and used the linker to connect the borg.

Don't have anymore info to put down atm, sorry it's vague.

### Expected Behavior

Borgs can be switched to uploads when linked without having to set the link to the ai upload to start, and borgs can state their respective terminals logs.

**Comment by amylizzle** [comment]
So the issue here is that the linker only connects borgs/AIs to the stored rack _if they have no connection already_.

Upon reflection, that's maybe not the most intuitive setup.
