### ISSUE TITLE
emaging the makecaptain module doesnt change the item name nor description

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#7877]
### Labels

[BUG][MINOR]

### Description

same as title, the description is only fixed once you set the name and the item name is never fixed

### Steps to reproduce

1. emag the makecaptain module
2. examine it

### Expected Behavior

name and description changing

**Comment by ThatFiveGuys** [comment]
For context emagging is supposed to stealthily change it into a make clown module

**Comment by pali6** [comment]
This is intended

**Comment by pali6** [comment]
To elaborate the intended prank is to emag the module and let someone else accidentally Clown themselves with it
