### ISSUE TITLE
Slipping while in a wheeled chair sometimes makes it impossible to move.

### ISSUE THREAD

**Issue by DigitalOddity** [goonstation/goonstation#788]
**Describe the bug**
Occasionally, after using the fire extinguisher to propel yourself around in a rolling chair, slipping on the floor will make it impossible to move again, buckled or unbuckled. I haven't tested it out a lot, and it seems to be inconsistent. Unbuckling and having another player pull you into slippery floor until you trip again was able to fix it once. Manually resting and unresting does not. Falling because of crit also did not help.

**To Reproduce**
1. Buckle into a chair with a fire extinguisher full of space lube.
2. Propel yourself in any direction, and then back, until you slip on the lubed floor.

**Expected behavior**
After the player slips, they're still capable of moving.

[BUG - MINOR]

**Comment by pali6** [comment]
Unable to reproduce, likely got fixed at some point.
