### ISSUE TITLE
Potentially all electromagnetic storm affected APCs become AI-disabled

### ISSUE THREAD

**Issue by Nexusuxen** [goonstation/goonstation#7884]
### Labels

[BUG]

### Description

NOTE: This is not fully tested/proven to be the case. However, it seems like all APCs that got fucked during an ion storm had disabled AI control - I had checked like 15 of them, though I didn't use the new reset-all-APCs command. Another person reported a similar issue they had as AI in another round.

### Steps to reproduce

1. Wait for an electromagnetic storm
2. Go look for an APC with tripped breakers
3. Try to interact with it, fail
4. Repeat until you run out of APCs to test or you find one that doesn't have disabled AI control

### Expected Behavior

Only a small portion of APCs should have disabled AI control according to the changelog, rather than *all* affected APCs.

### Additional Information & Screenshots

As stated above, this might not actually be the case, and might instead have been just a freak accident. But, probability says otherwise, and it warrants some further analysis.

**Comment by soleilan** [comment]
I've seen this happen in a round, but not all APCs were affected, only one. No idea how to reproduce.

**Comment by frawhst** [comment]
Probability or something idk. Doesn't seem to be an issue anyways
