### ISSUE TITLE
Wrestler's belt has no cooldown.

### ISSUE THREAD

**Issue by HBS-System** [goonstation/goonstation#7957]
### Labels

[BUG]

### Description

When you use the wrestler belt, it seems to have no cooldown. 

### Steps to reproduce

1. 1. Get the Wrestler's Belt and equip it
2. Click any ability rapidly, when you are in a space capable of using it.

### Expected Behavior

I expet the abilities to have a cooldown, instead of being able to be spammed infinitely for massive damage.

**Comment by Tarmunora** [comment]
Fixed
