### ISSUE TITLE
Wrestle belt and Wrestler.EXE murderbox cooldown issues

### ISSUE THREAD

**Issue by ThatsMamaLuigiToYouMario** [goonstation/goonstation#7958]
### Labels

[BUG]

### Description

Both the wrestlebelt and wrestler.exe thing within the murderbox have no cooldown on abilities, meaning you can spam it as much as you want.

### Steps to reproduce

1. Go into VR.
2. Enter the murderbox.
3. Either spawn a wrestle belt from the traitor radio or get a wrestler's abilities through the WRESTLER.EXE object.
4. Find that your abilities have no cooldown, and you can go hog-wild on your test dummies or fellow murderboxers.

### Expected Behavior

I think the wrestlebelt should line up with the new cooldown patch and not be a non-stop ability machine.

**Comment by frawhst** [comment]
fixed by yass I think
