### ISSUE TITLE
Strange issue with display code on Retkid ringtones, [given error code and line to fix]

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#7965]
### Labels

[BUG]

### Description

So I bought a ringtone pack, I dont remember which but I assume its named retkid in code, I got this strange error code. (see attached screenshot)

### Steps to reproduce

1. buy ringtone pack (retkid)
2. install
3. scroll down
4. see error code
5. make bug report

### Expected Behavior

do be able to use those last few ringtones

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/75814831/160218096-aff86122-32c8-41ae-bdbb-ea0d3b04ecdb.png)

**Comment by pali6** [comment]
not a bug
