### ISSUE TITLE
law uploads no longer recorded on goonhub

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#7972]
### Labels

[BUG]

### Description

The laws uploaded during a round do not appear on the post round summary on goonhub

### Steps to reproduce

1. Upload law
2. Wait for round to end
3. Check goonhub

### Expected Behavior

I would expect to see what laws were uploaded and who uploaded them.

### Additional Information & Screenshots

It's probably more of a bug on goonhub's end but there isn't really a bug report thing for that unless I missed it.

Many laws are fun to read and it's a lot harder to ahelp rule-breaking laws uploaded by nonantags when you don't have a public record of who uploaded what law at round end.

**Comment by Retrino** [comment]
new goonhub who dis
