### ISSUE TITLE
Uquil no longer counts as "High density crystaline matter" for the purposes of Industrial Space Armour

### ISSUE THREAD

**Issue by amylizzle** [goonstation/goonstation#7989]
### Labels

[BUG]

### Description

Uqil is bad now

### Steps to reproduce

1. Mine for uquil
2. Turn it a material bar
3. put it in the mining fabricator
4. oh no, I can't make amazing space armor

### Expected Behavior

The hard crystal should count as hard crystal

**Comment by TTerc** [comment]
Fixed in f95ecbf2d13b254c73d76d8230b8d56ecee52928
