### ISSUE TITLE
AI can see trough walls when exiting out of a shell

### ISSUE THREAD

**Issue by TheRealMrN** [goonstation/goonstation#7994]
### Labels

[BUG]

### Description

You can see trough walls as AI when you exit out of a shell if you dont press any movement keys

### Steps to reproduce

1. Get a shell somewhere where your cameras dont reach
2. Exit out of your shell
3. See that your camera stays focused on the shell and you can see trough walls without any camera static being present

### Expected Behavior

For camera static to appear in areas you aren't supposed to see as AI eye

### Additional Information & Screenshots

This can be used to scout areas without any risk and cheese some azones by pressing buttons trough walls

**Comment by amylizzle** [comment]
This is a feature, not a bug. Next time you're AI, have a cyborg go to an area you can't see into - you'll be able to see the area. Cyborg shells act as mobile cameras.

**Comment by TheRealMrN** [comment]
I know that the shells can act as cameras but i dont think they should be able to see trough solid objects, just like cameras

**Comment by AmazingDragon353** [comment]
I think that's a feature, not a bug, as it also applies to guardbuddies and the like. If you think it's OP, maybe consider posting on the forums abt it.
