### ISSUE TITLE
AI cannot state full lawset

### ISSUE THREAD

**Issue by ReneeTaylor1** [goonstation/goonstation#7995]
### Labels

[BUG]

### Description

As AI, using the "state all laws" command does not produce your current lawset consistently, though using the "fake lawset" will show all laws. Additionally, it will misnumber the law it does state. (For example, it will only state law 5 and label it as "law 1")

### Steps to reproduce

1. As AI, use the command to state all laws after having your laws changed.

### Expected Behavior

The command should state all laws in your lawset.

**Comment by amylizzle** [comment]
Could you provide some more context here? 
What had happened to your laws? Were you in a shell at the time?

**Comment by ReneeTaylor1** [comment]
>What had happened to your laws? Were you in a shell at the time?

A freeform and make captain law had been uploaded, and I was not in a shell. Attempting to state laws only stated one law, which had not been occurring before in the round. 

Let me know if any other info would help!

**Comment by amylizzle** [comment]
Maybe the round ID would be best - I'll see if someone can grab the logs for me.

**Comment by ReneeTaylor1** [comment]
It just occurred to the AI EMMA on Round #128786, looks like there were no laws updated there.

**Comment by amylizzle** [comment]
Great, I'll look into this. Thanks for the report.

> looks like there were no laws updated there.
Yeah, that's the bot for that not updated yet. It's in the plan.
