### ISSUE TITLE
Chopping chicken after killing it in a carrier causes it to provide infinite meat

### ISSUE THREAD

**Issue by GabrielMation** [goonstation/goonstation#7999]
### Labels

[BUG] [MINOR]

### Description

Killing and skinning a chicken in a carrier causes it to provide infinite meat

### Steps to reproduce

1. Get a chicken (tested with standard, but others probably work too)
2. Place it in a chicken carrier
3. Kill it (tested with a knife) while it's inside the carrier
4. Skin it with a knife while it is still inside the carrier
5. Take it out of the carrier and chop it up. The chicken does not disappear and instead keeps making more meat

### Expected Behavior

For the chicken to disappear and be replaced by meat and feathers after being chopped once

**Comment by frawhst** [comment]
fixed
