### ISSUE TITLE
AMDL underneath conveyor 

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#8017]
### Labels

[BUG]

### Description

There an AMDL underneath a conveyor in Atlas' incoming cargo line. Possibly on other maps too.

### Steps to reproduce

1. Open Atlas
2. Go to cargo
3. See AMDL rendering under conveyor

### Expected Behavior

Not sure if it should even be there, or if it should render on top of the conveyor, but I'm pretty sure it didn't used to be like this

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/20713227/160684465-a1833c72-8499-4d29-b4bf-7ff6161c3c22.png)

**Comment by soleilan** [comment]
seems like normal business to me

**Comment by pgmzeta** [comment]
intended
