### ISSUE TITLE
Trichochromatic shift does not change your hair color

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#8024]
### Labels

[BUG]

### Description

The Trichochromatic shift gene power does not work.

### Steps to reproduce

1. Roll the trichochromatic shift gene through the mildly mutated trait
2. Use ability

### Expected Behavior

For your hair to change color.

### Additional Information & Screenshots

Hair:
![image](https://user-images.githubusercontent.com/53062374/160775841-6b0a1be0-1d46-4445-a8b5-1654f224c1d5.png)

**Comment by TobleroneSwordfish** [comment]
Yep this is how trichochromatic shift works, it just swaps around the three hair colours you can set, so if all your hair is the same colour it will do nothing.

**Comment by FlameArrow57** [comment]
Ah I see, misinterpreted the hover description then
