### ISSUE TITLE
Gravity warper artifact can pull AI eyes

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#8037]
### Labels

[BUG]

### Description

Gravity warper artifact can pull AI eyes.

### Steps to reproduce

1. Move by gravity warper artifact that pulls objects towards it as AI eye

### Expected Behavior

For the AI eye to not be pulled.

**Comment by TobleroneSwordfish** [comment]
Hot air can also move AI eyes unless that's been fixed

**Comment by pgmzeta** [comment]
> The AI eyes just want to feel included, stop removing them from every loop. 
:( but how are they supposed to point and laugh if they keep getting moved around???

**Comment by TobleroneSwordfish** [comment]
> The AI eyes just want to feel included, stop removing them from every loop. 😔

no we are going to add 200 more isintangible checks each in its own PR

**Comment by pgmzeta** [comment]
> no we are going to add 200 more isintangible checks each in its own PR
there's a proc for `target_is_valid` for artifact turrets we should probably raise up to /obj/machinery/artifact and implement, would allow for artifacts to override/supplant the proc as they see fit.
