### ISSUE TITLE
Goonhub Doesn't Track Law Changes Anymore

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#8041]
### Labels

[BUG]

### Description

Since the law rack was added, Goonhub has been unable to track law changes of any kind.

### Steps to reproduce

1. Join a Game
2. Add a law
3. Make sure it's there when the round ends
4. Check the round on Goonhub
5. Notice no law changes

### Expected Behavior

For Goonhub to say what laws where changed

**Comment by stonepillars** [comment]
Duplicate of #7972

**Comment by amylizzle** [comment]
Closed as duplicate
