### ISSUE TITLE
Can't put afk players into cryo

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#8045]
### Labels

[BUG]

### Description

I am unable to put afk players into cryo, instead getting the message that I can't put active players or npcs into cryo

### Steps to reproduce

1. Join game
2. Find a player that is "Staring blankly into space"
3. Grab and try to put them into cryo
4. Can't

### Expected Behavior

To be able to put afk players into cryo

**Comment by frawhst** [comment]
fixed
