### ISSUE TITLE
Body bags can't be rolled up

### ISSUE THREAD

**Issue by DisturbHerb** [goonstation/goonstation#8066]
### Labels

[BUG]

### Description

When trying to click-drag an open body bag to one's player sprite, it does not revert back into an item like it should.

### Steps to reproduce

1. Have an open body bag on the floor.
2. Click-drag to your player icon.
3. See error.

### Expected Behavior

I expected the body bag to roll up like it used to.

**Comment by frawhst** [comment]
probably fixed next round

**Comment by frawhst** [comment]
fc2aff6bc1f46ab4b74d91818dfdc649e8fb9c45
