### ISSUE TITLE
Suplex broke

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#8069]
### Labels

[BUG]

### Description

suplexing is broke
Edit: thus bug is also affecting lings as in they cant choke

### Steps to reproduce

1. aggressive grab another person
2. flip
3. no suplex happens
4. sad

### Expected Behavior

suplex happens

**Comment by frawhst** [comment]
oops 79651f1f3c6a40ec65ad80630bc3674efbd4cc1c
