### ISSUE TITLE
Oshan's Crusher is Gone.

### ISSUE THREAD

**Issue by avimour** [goonstation/goonstation#8084]
### Labels

[BUG]

### Description

Crusher is gone round-start

### Steps to reproduce

1. Spawn on Oshan.
2. Check disposals.
3. Crusher gone, but some scraps left!

### Expected Behavior

I expect the crusher to be there.

### Additional Information & Screenshots

I haven't checked any other maps so they might also be missing a crusher? But Oshan's is 100% gone round-start.

**Comment by frawhst** [comment]
should be fixed by 4dd263162b38b92116a6cbb18830bd7c78edaa1b
