### ISSUE TITLE
Old mining gizmo no longer designates tile for magnet

### ISSUE THREAD

**Issue by atenie** [goonstation/goonstation#8099]
### Labels

[BUG]

### Description

Old mining gizmo no longer works

### Steps to reproduce

1. Get mining magnet parts
2. Install them on the chassis
3. 
4. Use old mining gizmo to designate lower left corner for the area
5. Doesn't work on space area, doesn't work on catwalk. Space tile says "Error: bordering tile has a gap, cannot magnetize area. Designation failed.", whilst catwalk tile forces me to attack it, basically.

### Expected Behavior

Old mining gizmo would designate a tile

### Additional Information & Screenshots

Talked with Waffleloffle about the matter and sent an adminhelp on Goon2. I was Sandor Tapeworm.

**Comment by pgmzeta** [comment]
likely related to #8091
