### ISSUE TITLE
Cleanables that spawn in random rooms can't be mopped.

### ISSUE THREAD

**Issue by RubberRats** [goonstation/goonstation#8103]
### Labels

[BUG]

### Description

Dirt, blood, and other cleanable decals that spawn as part of a random room can't be cleaned with a mop.

### Steps to reproduce

1. Locate a random maintenance room with cleanables in it.
2. Attempt to mop up said cleanables
3. They are not cleaned up by the mop.

### Expected Behavior

The dirt that spawns in random rooms should be moppable just like the dirt that spawns in maintainence normally.

**Comment by TheTyrant25** [comment]
doesn't seem to be the case, at least with space fungus

**Comment by TheTyrant25** [comment]
unable to reproduce.
