### ISSUE TITLE
Surgery page on Wiki needs an update

### ISSUE THREAD

**Issue by Rademenes16** [goonstation/goonstation#8106]
### Labels

[WIKI]

### Description

Surgical removal page is not updated

### Steps to reproduce

Surgical removal section on surgery page needs an update. For example using scissors and scalpel in order: scissors>scissors>scalpel no longer removes a liver, but kidney. It also happens with other organs.
I talked to 3 different people in game and they confirmed it.

### Expected Behavior

I expected content on wiki to work in game, but it didn't

### Additional Information & Screenshots

https://wiki.ss13.co/Doctoring#Surgery

**Comment by BatElite** [comment]
I've tried on local and goon1 and liver surgery is still snip-snip-cut. Are you sure you're not using tools in the reverse order you intended? Because the kidney and liver surgeries are the same order but with the tools reversed.

**Comment by Rademenes16** [comment]
> I've tried on local and goon1 and liver surgery is still snip-snip-cut. Are you sure you're not using tools in the reverse order you intended? Because the kidney and liver surgeries are the same order but with the tools reversed.

Definitely not. I also tried eyes augmentation and it always failed. With tools in hand corresponding to operated eye.

**Comment by Rademenes16** [comment]
I made a quick video about this: https://www.youtube.com/watch?v=vlOMoPzKkpo

In the video you can see for eye augmentation I used **spoon>scalpel>spoon>spoon** instead of spoon>scalpel>spoon you see on wiki.

**Comment by Mobilfan** [comment]
I will point out that heart reinserting is missing on the wiki page.

**Comment by Rademenes16** [comment]
I'm closing this issue as I changed my mind and I do not want to help the game that has massive problems with admins abusing their power.
