### ISSUE TITLE
ValuChimp monkeys grant no evo points

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#8120]
### Labels

[BUG]

### Description

Eating monkeys from the ValuChimp as blob grants no Evo Points

### Steps to reproduce

1. Be blob
2. Break ValuChimp
3. Eat monkey
4. dangnabbit

### Expected Behavior

As NPC monkeys, ValuChimp monkeys should grant one evo point

### Additional Information & Screenshots

If this is an intended balance thing it really shouldn't be.  Spawning near the ValuChimps is risky.

**Comment by Eagletanker** [comment]
I think this was changed cause of April fools big maps

**Comment by MetricDuck** [comment]
Per fb01aa6 NPC monkeys have a 50% chance to grant 2 EVO points. Code seems to be working fine when tested: author probably got on an unlucky streak. 

I see the wiki is wrong though
