### ISSUE TITLE
Cyborgs cannot strip people

### ISSUE THREAD

**Issue by AdrienBoussard** [goonstation/goonstation#8122]
### Labels

[BUG]

### Description

Cyborgs are unable to remove items from people.

### Steps to reproduce

1. Be a cyborg
2. Be next to a person
3. Drag their sprite onto yours
4. The person inventory appears correctly
5. Click on an item to try to remove it
6. Nothing happens

### Expected Behavior

An attempt to remove the item should activate.

### Additional Information & Screenshots

Probably related by aloe's update on 05/04/22.

**Comment by AdrienBoussard** [comment]
Issue resolved by c097a6049a4d375f6d0a7b8ba08c5ffd7ce328d6.

**Comment by Eagletanker** [comment]
Wait shouldn’t cyborgs be unable to strip items
