### ISSUE TITLE
Stealth sting on monkeys aggros them

### ISSUE THREAD

**Issue by DrCta** [goonstation/goonstation#8131]
### Labels

[BUG]

### Description

Stealthily stinging monkeys as a buttcrab fully aggros them into beating you up, unknown if the same goes for changeling stings

### Steps to reproduce

1. Be a buttcrab (or perhaps even a changeling).
2. Stealthily sting a monkey mob as you have nothing better to do. Note the message "We stealthily sting [mob]".

### Expected Behavior

The mob should not aggro from a stealth sting and instead go along its merry, stealth-stung way as if nothing happened.

### Additional Information & Screenshots

Found this bug after spawning as a buttcrab pest, after having joined the round as an observer.
I do not know if this also applies to any other neutral mob or to changeling stings.

**Comment by Yellow-Mushroom** [comment]
To add, it also aggro’s NPC humans and basically any neutral non-player controlled mob.

**Comment by MetricDuck** [comment]
Strangely this is a feature, looks like early anti-cheese for blood/dna.

`	was_harmed(var/mob/M as mob, var/obj/item/weapon = 0, var/special = 0, var/intent = null)
		. = ..()
		if (special) //vamp or ling
			src.target = M
			src.ai_state = AI_ATTACKING
			src.ai_threatened = world.timeofday
			src.ai_target = M`

**Comment by frawhst** [comment]
Not a bug at the moment since it's pretty consistent.
