### ISSUE TITLE
Spy Thief Trading in Space

### ISSUE THREAD

**Issue by NotDucc** [goonstation/goonstation#8153]
### Labels

[Minor]

### Description

Spy Thief trades that require you to go to space seem to not work

### Steps to reproduce

1. Get a trade that tells you to turn in a "Photograph of X" in space for an Omnitool
2. Go to space
3. Get told you are not in the right destination; GPS is unable to lead you anywhere and PDA tells you that you are indeed in space
4. Cry

### Expected Behavior

The trade to happen

### Additional Information & Screenshots

The map was Atlas, not sure if that had any effect on trading in space not working

**Comment by MeggalBozale** [comment]
No longer a bug as it's not a valid bounty space (heh)
only valid bounty area types (which include their subtypes) are:
- /area/diner
- /area/station
