### ISSUE TITLE
Cyborgs are unable to use supply request consoles

### ISSUE THREAD

**Issue by AdrienBoussard** [goonstation/goonstation#8179]
### Labels

[BUG]

### Description

Clicking on a supply request console as a cyborg displays the message: "AI Interfacing with this computer has been disabled."

### Steps to reproduce

1. Be a cyborg
2. Click on a supply request console
3. "AI Interfacing with this computer has been disabled."

### Expected Behavior

The console interface should displays.

### Additional Information & Screenshots

Cyborgs can also use Cargo Request in their PDA, but supply request console interfaces are more pleasant to interact.

**Comment by Laboredih123** [comment]
Likely a non-issue. Someone probably cut the AI wire so ya'll silicons can't use it.

**Comment by Laboredih123** [comment]
Disregard that, I don't see a way to hack computers.

**Comment by Laboredih123** [comment]
But still intended. Line 27 in QM_order.dm

**Comment by BatElite** [comment]
Yeah borgs are meant to just use the QM consoles
