### ISSUE TITLE
Unable to move when using bag

### ISSUE THREAD

**Issue by Onetoughcreampuff** [goonstation/goonstation#8180]
### Labels

[BUG]

### Description

After having done something (clueless on what), my bag lead to me becoming unable to interact with anything unless i got ahelped, or command bar usage

### Steps to reproduce

1.  have bag and do unknown thing to break bag stability
2.  open bag
3.  interaction with game is disabled

### Expected Behavior

I expect to move one leg in-front of the other

### Additional Information & Screenshots

https://cdn.discordapp.com/attachments/846705223165804576/963807765522964520/funnybagbugbad.mp4

**Comment by UrsulaMejor** [comment]
Unable to replicate, old bug, submit a new report if it happens again
