### ISSUE TITLE
hairgrownium doesn't work when bald

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#8181]
### Labels

[BUG]

### Description

Specifically, hairgrownium will not grow you a new set of hair if you cut it all off by accident.

### Steps to reproduce

1. Cut off all hair by accident
2. Take hairgrownium

### Expected Behavior

I expect you to be able to try to grow your hair back

### Additional Information & Screenshots

It may also not work in other contexts but I haven't tried it recently in other contexts.

**Comment by Gerhazo** [comment]
Can't reproduce, could have gotten very unlucky with the hairgrownium expiring before causing the effect, the pillbottle pills contain small amounts of it.
