### ISSUE TITLE
Nukie Knights helmet is Bald

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#8186]
### Labels

[BUG]

### Description

The Nuclear Operatives feather that is supposed to be one their helmet doesn't show up, making you look bald

### Steps to reproduce

1. Be nukie
2. Grab Knight loadout
3. Equip Helmet
4. MY EYES

### Expected Behavior

To not be bald and have my lovely feather

### Additional Information & Screenshots

I believe this happened after the semi-recent change to a lot of hair, that caused some of the hairs to be invisible.
![2022-04-12](https://user-images.githubusercontent.com/87689371/163283285-d9ed0ed0-c241-424f-82a2-10fea3bc0073.png)

**Comment by Gannets** [comment]
Oh the feather hasn't been there since the human resprite. I just didn't get around to making a new item icon.

**Comment by ThatFiveGuys** [comment]
Not a bug

**Comment by ThatFiveGuys** [comment]
Oh yeah item icons are a thing

**Comment by nefarious6th** [comment]
Fixed by #11427
