### ISSUE TITLE
spectating someone as a ghost doesn't move your current location/SFX hearing range with them anymore

### ISSUE THREAD

**Issue by wolfolotl** [goonstation/goonstation#8188]
### Labels

[BUG] [MINOR]

### Description

very minor QoL thing, but observing another player now puts you back at the ghost spawn point when you exit them. it also doesn't put your hearing range at their location, though you can still hear their radio sound effects as well as some others

### Steps to reproduce

1. die or select "observe"
2. become a ghost, choose a player to observe
3. notice that you can't hear their voice mumbles, but you CAN hear the clown constantly walking by the spawn point
4. stop observing the player and notice you get zooped back to said spawn point

### Expected Behavior

for observing a player to carry your location and sound effect hearing range with them as they move

**Comment by frawhst** [comment]
fixing rn

**Comment by frawhst** [comment]
9c959623beff191848772e6ec038dfd55147ca69
