### ISSUE TITLE
Aggressive bees remain in sleeping state

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#8192]
### Labels

[trivial]

### Description

Bees which are awoken while sleeping to attack someone keep the bee sleeping sprite

### Steps to reproduce

1. Wait for a bunch of bees to sleep
2. Run in and punch one
3. See bug

### Expected Behavior

Bees look angry

### Additional Information & Screenshots

:beesleep:
![image](https://user-images.githubusercontent.com/67879783/163296755-0b34df99-73ed-465a-a8e9-8490e72c1e93.png)

**Comment by colossusqw** [comment]
i've seen some issues with sleep in critters recently, the critters randomly start sleeping with folks around or don't deaggro even if you're very far away

**Comment by ZeWaka** [comment]
fixed by pali i think
