### ISSUE TITLE
RD has power gloves in the traitor buy list

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#8195]
### Labels

[BUG]

### Description

RD has the power glove traitor item in the buy list

### Steps to reproduce

1. Be traitor RD
2. See power glove traitor item in buy list

### Expected Behavior

For the power gloves to not be there.

**Comment by frawhst** [comment]
find a generator artifact you coward!!

**Comment by frawhst** [comment]
4599c7249d8c2afe90f04ff45ac3bbfad4fb5e33
