### ISSUE TITLE
CentCom arrival overrides master volume setting.

### ISSUE THREAD

**Issue by MitchTheUser** [goonstation/goonstation#8220]
### Labels

[BUG]

### Description

Muting the game by setting master volume to 0, then arriving at CentCom, makes all sounds play at default volume, even though master volume is still set to 0.

### Steps to reproduce

1. Set master volume to 0 to mute the game.
2. Arrive at CentCom via escape shuttle.
3. Watch as all sounds start playing normally despite master volume being at 0.

### Expected Behavior

Game to remain muted.

**Comment by virvatuli-gh** [comment]
Cannot reproduce this, tested on multiple servers and the volume stays at 0 throughout the round, including roundend.
