### ISSUE TITLE
Rev Flash Item Uses Default Flash's In-Hand Animation

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#8223]
### Labels

[BUG] [TRIVIAL]

### Description

Using a rev flash uses a normal flashes animation, causes it to appear to as a normal flash in hand

### Steps to reproduce

1. Grab a rev flash
2. Use it
3. Notice it uses the same animation as a normal flash, despite having different colors on the sprite

### Expected Behavior

For the rev flash to have an animation that matches the sprite

**Comment by frawhst** [comment]
Yeah, we don't actually have an icon_state for a revflash flashing. Needs to be kitbashed together.
