### ISSUE TITLE
being inside of a negative matter locker pocket dimension while it gets destroyed z0s you

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#8230]
### Labels

[BUG]

### Description

same as title

### Steps to reproduce

1. make a locker out a negative matter alloy
2. enter it
3. cause something to destroy it eg. a bomb or crusher
4. you are now softlocked at z0 

### Expected Behavior

it teleporting you to the turf it was destroyed on or something

**Comment by frawhst** [comment]
heh

**Comment by pali6** [comment]
Hmmm, the behavior to dump contents onto the locker's turf is there but I guess moving it to null happens sooner than removal of components?
