### ISSUE TITLE
Hunter gear doesn't blow up on death

### ISSUE THREAD

**Issue by PrimeNumb** [goonstation/goonstation#8237]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. Remove hunter gear (tested with cloaker)
2. Let hunter blow up (possibly via suicide)
3. Observe error

### Expected Behavior

The gear should detonate on death of the hunter

**Comment by flappybatpal** [comment]
Looks like they dropped the cloaking device as there is no log of it being removed from them.
Some non-antag found it 6~ tiles away from you looting the hunter.
The hunter then blew up, much later you removed the device from that player.

For some reason it didn't successfully self destruct. It's on COMSIG_MOB_DEATH so it should be reliable, none of the other gear was around from the logs or chat. The qdel might have silently failed for some reason...

**Comment by flappybatpal** [comment]
The microbomb is breaking COMSIG_MOB_DEATH.
Someone has messed up the existing behavior.

**Comment by UrsulaMejor** [comment]
Unable to replicate. Seems to have been fixed?
