### ISSUE TITLE
Mono card deck "Bad Icon" & card deletion

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#8239]
### Labels

[BUG]

### Description

"Bad Icon" shows on mono card decks. These decks can permanently(?) delete cards.

### Steps to reproduce

1. Purchase mono card deck
2. Draw a card, drop it on the ground.
3. Draw another card, stack it into the first card
4. Bad Icon
5. Draw a card from the Bad Icon deck while holding it
6. The Bad Icon deck will split back into 2 cards in your hand
7. Throw both cards, notice only one throws properly. The other will remain spinning in place
8. Pick up and drop both cards, the spinning card will now be gone forever.

### Expected Behavior

I expect stacking cards to make a functional deck

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25157685/163713782-fa3bdf17-f9b8-4644-be8a-cba61a9adb2c.png)

**Comment by flappybatpal** [comment]
No idea about the spinning/deleting element.
