### ISSUE TITLE
Floor planner textureing and hangers.

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#825]
[BUG]

**Describe the bug**
Changing the floor texture of a hanger to something else removes its ablity to do what its supposed to do.
**To Reproduce**
1. be construction man and change hanger floor to something else
2. get in pod and try to move.

**Expected behavior**
i expect the texture to change only, not how the floor itself functions.
**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/82743364-6b2c0d80-9d38-11ea-9886-a48f7ab79857.png)

**Comment by ZeWaka** [comment]
Changing type?

**Comment by RSG250** [comment]
literally the only thing that i used to change the floor in the hanger was the floor planner. and some how that stops the pods from moving on the floor.

**Comment by ZeWaka** [comment]
no, i get that, my notation for fixing the bug is that the thingy might be changing type and not icon... not that it really should be able to change to icons owned by a different type anyways
