### ISSUE TITLE
Dummies' Guide to Material Science has outdated material values

### ISSUE THREAD

**Issue by zjdtmkhzt** [goonstation/goonstation#8252]
### Labels

[BUG]

### Description

Dummies' Guide to Material Science has outdated material values

### Steps to reproduce

1. Read Guide
2. It's wrong

### Expected Behavior

the guide to be correct

### Additional Information & Screenshots

For instance, the density of viscerite is now 45 when it used to be 65.
Some other values that were changed in #7443 are presumably not updated either, and maybe things that were changed earlier as well.

In an ideal world this would probably be automatically generated with the actual material stats?

**Comment by zjdtmkhzt** [comment]
Adding "add to wiki" because logically the mirror of the book on the wiki is outdated too. 
(https://wiki.ss13.co/Dummies%27_Guide_to_Material_Science)

**Comment by pgmzeta** [comment]
In-game fixed in #10109 but it still needs a wiki update

**Comment by Chatauscours** [comment]
Fixed by #10109
