### ISSUE TITLE
non movable objects in negative matter pocket dimensions are left there on the lockers destruction

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#8260]
### Labels

[BUG]

### Description

same as title, including objects and people inside them

### Steps to reproduce

1. make a negative matter and metal alloy
2. make a locker out of it
3. build non movable inside for example a disposals chute
4. destroy the locker
5. the object is still in the location where the pocket dimension was including objects and worst of all people that were inside of it

### Expected Behavior

not that, non movable objects either being teleported or destroyed and people inside teleported

**Comment by ThatFiveGuys** [comment]
Unable to reproduce, non anchored objects and mobs become on same contents as destroyed locker
