### ISSUE TITLE
infusing all of the sorium prereqs does not cause explosion

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#8268]
### Labels

[BUG]

### Description

when i have infusions synthesizing unstable sorium inside of me constantly nothing happens even though there is a reaction

### Steps to reproduce

1. infuse the sorium prereqs (nitrogen, carbon, mercury, oxygen) into 4 different stacks of 10 mauxite
2. plate a staple in each chem infused mauxite
3. implant yourself with all of them
4. sorium reaction with no explosion over and over

### Expected Behavior

sorium detonating and it being really cool

**Comment by kotomato** [comment]
oh forgot to mention that pyrosium and high body temperatures do not set off sorium inside body (i tried)

**Comment by Cthucky** [comment]
I might be mistaken but I think sorium/ldm use the same open/closed container code that smoke powder, foam, and aerosol use and consequently won't go off inside a mob.

**Comment by UrsulaMejor** [comment]
intended:
`	if(created_volume < 3)
		return 0`
infusions aren't creating enough in your blood to explode
