### ISSUE TITLE
starstone infuses infinite materials

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#8269]
### Labels

[BUG]

### Description

when you infuse a chem into something with starstone it infuses the entire stack as opposed to just 10 of it

### Steps to reproduce

1. place large amount of material into nanofab (preferably processed)
2. infuse it with starstone and a chemical
3. take the material out of the nanofab to see it is infused
4. if you used ore, you have to process it for it to show that it is infused, but it is indeed infused

### Expected Behavior

only 10 material are infused

**Comment by RSG250** [comment]
i honestly thought that it was more of a minimum ammount needed, never thought it was an bug for some reason, probably thought that do to how rare starstone is, and how rare it gets used for infusion.

**Comment by frawhst** [comment]
i think this is a feature
