### ISSUE TITLE
pizza chem and midas touch can unstack food

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#8279]
### Labels

[BUG][major]

### Description

same as title, the individual bites get unstacked

### Steps to reproduce

1. get the pizza chem
2. get a food that needs multiple bites
3. pour pizza on food
4. tada the food is now split bite by bite somehow

### Expected Behavior

not unstacking foods

### Additional Information & Screenshots

the amount of bites uses the amount property which is also used for stacks of for example money and ores
this bug is much more severe than what it looks like and should be patched asap (the major tag is not a joke)

**Comment by frawhst** [comment]
fix'd
