### ISSUE TITLE
Removing mutations (via gene console at least) does not change stability

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#8297]
### Labels

[BUG]

### Description

If you remove a mutation with the gene console that changes genetic stability when gained, your stability does not change.

### Steps to reproduce

1. Put in mutation
2. Remove mutation
3. Look at stability
4. Oh my this is horribly abuseable isn't it

### Expected Behavior

If I lose 20 stability by taking a mutation I should gain 20 by removing it

### Additional Information & Screenshots

Haven't tested with mutadone.

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/7524f0cd99c638398ae6d57911e3644dfd946fd8
