### ISSUE TITLE
changelog says "wednesday, april 22, 2022"

### ISSUE THREAD

**Issue by wolfolotl** [goonstation/goonstation#8310]
### Labels

[BUG] [MINOR]

### Description

changelog reads Wednesday, April 22 instead of Friday, April 22

### Steps to reproduce

1. look at today's changelog
2. look at today's date
3. see it's actually friday

### Expected Behavior

for it to be friday today

**Comment by Tarmunora** [comment]
time can be whatever we want it to be 👁️ 
but also [fixed](https://github.com/goonstation/goonstation/commit/87e2c4738094da95ebcc97f51176168216cc3d8e)
