### ISSUE TITLE
Cyborgs show up weird to Ghost drones

### ISSUE THREAD

**Issue by MitchTheUser** [goonstation/goonstation#8313]
### Labels

[BUG]

### Description

Cyborgs only show up as a chest unit when you look at them as a ghost drone

### Steps to reproduce

1. Become a ghost drone
2. Find a cyborg
3. Observe its lack of limbs

### Expected Behavior

The cyborgs limbs and head to be visible in its fuzzy silhouette?

### Additional Information & Screenshots

![Goonstation 1 Classic Heisenbee CorpJupiterStar Waystation XVIII 2022-04-22 231555](https://user-images.githubusercontent.com/94775877/164873124-8f6e519a-c90c-47cd-9c29-99ea0bb3a75c.png)

**Comment by soleilan** [comment]
![image](https://user-images.githubusercontent.com/111906440/223881621-89115805-617c-4e74-a409-62ce54e04055.png)
wacky!!
