### ISSUE TITLE
Smoke clouds prevents puddle clean up

### ISSUE THREAD

**Issue by MitchTheUser** [goonstation/goonstation#8328]
### Labels

[BUG]

### Description

If there is a smoke cloud over top of a puddle of liquid, you cannot soak it up with the mop.

### Steps to reproduce

1. Find puddle of liquid with smoke cloud over it.
2. click on puddle.
3. see as the mop cleans the floor, instead of the puddle.

### Expected Behavior

Mopping up the puddle to not be blocked by smoke clouds.

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/429a8bb46cc8f894f3917e6490d460a2c5462b60
