### ISSUE TITLE
Handheld arts cannot activate

### ISSUE THREAD

**Issue by UltraNumeron** [goonstation/goonstation#8352]
### Labels

[BUG]

### Description

Handheld artifacts do not activate even when checked for every activator and fully tested with all activators.

### Steps to reproduce

1. get any handheld artifact 
2. try all activators on it on as many settings as possible.
3. It never activates no matter what you do.

### Expected Behavior

I expected the artifact to activate at one of the activators.

### Additional Information & Screenshots

I had done artlab for 2 rounds straight and this kept popping up, none of em would activate. None of them were liquid containers so they should be able to activate, i had attempted to heater them, says no temperature response, thinktape, no response, xray no radiation response other xray settings do not do anything aswell, tap it get someone else to press against it no response, tap it with a cyborg arm, no response, tap it with a multitool no response elecbox on various settings did nothing aswell. Shoot fire extinguishers at it via pitcher, no respone. So i tried everything on about six artifacts throughout the two rounds i did artlab with this bug and none of the handheld ones would activate. large artifacts would however.

**Comment by zjdtmkhzt** [comment]
Tried minimum electricity? Cold stimulus? Maximum pitcher power fire extinguisher?
I did a round of artlab yesterday and did not encounter anything I could not activate, and it is pretty common for people to miss something.

**Comment by UltraNumeron** [comment]
> Tried minimum electricity? Cold stimulus? Maximum pitcher power fire extinguisher? I did a round of artlab yesterday and did not encounter anything I could not activate. In my experience as mentor it is pretty common for people to miss something and so far I've always been able to help them activate the artifact in the end.

I didnt try minimum electricity or maximum pitcher, i did try cold but still no temperature response. I thought i could be missing something but got kinda frustrated when this happened to every handheld item of the about 6 i was trying to activate, so thought it was  a bug thanks for the tips though.

**Comment by UltraNumeron** [comment]
Checked and this is probably just my own stupidity not a bug
