### ISSUE TITLE
Shoving away a chaplain traitor will not cancel them forcing you to sign a contract

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#8357]
### Labels

[BUG]

### Description

Shoving a person who is attempting to force you to sign a contract will not cancel it, meaning if they walk back in range before it would have finished, the contract will get signed. I don't know if this is intentional or not.

### Steps to reproduce

1. Have a chaplain traitor start forcing you to sign a contract
2. Shove them away
3. They walk back into range before the action would have finished
4. The contract gets signed without them having to re-attempt to force you

### Expected Behavior

I have pushed them away from me and they are now out of range and unable to finish guiding my hand. If they come back in range they should have to re-attempt to force me to sign.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25157685/165803706-3b38833c-9c56-4a48-b46b-53918e553bd4.png)

I am fairly certain I have seen this happen to other things too, but I can't recall what they were. Possibly syringes or food?

**Comment by Tarmunora** [comment]
fixed for contracts
