### ISSUE TITLE
Radio equipment is magic

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#8376]
### Labels

[BUG]

### Description

All four pieces of radio station equipment work without any power coming from an APC.

### Steps to reproduce

1. Go to (Oshan) radio station
2. Disable APC's main breaker (done as borg)
3. Somehow the broadcasting tower still transmits over radio (In its signature rose pink text, no less)
4. The casette player and record player work too.

### Expected Behavior

I expected to not hear a damn thing since equipment power is disabled.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/100481985/166081784-99ef9922-fb76-446a-bdca-62c85a84e270.png)
![image](https://user-images.githubusercontent.com/100481985/166081798-69fb22b6-ecba-4474-a39a-7d33533b094a.png)
Goon3, Morty, 7:56 PM EST. Playing as Cupric. Aurora Sky and Ashley Collins as eyewitness.

**Comment by ZeWaka** [comment]
so true, feel free to pr a feature

**Comment by TheTyrant25** [comment]
I believe this is because the radio station in the debris field has no power source yeah? Same reason as #12691
