### ISSUE TITLE
Allow spaces in Highlight String

### ISSUE THREAD

**Issue by RenzDot** [goonstation/goonstation#8380]
### Labels

[BUG]

### Description

Allow spaces in Highlight String menu

### Steps to reproduce

Steps to Reproduce
1. In chat: select settings cog -> Highlight String
2. Type " ling " as a highlight, with spaces on each side
3. Save

Reopen Highlight string, and notice that it's changed to "ling" without spaces

### Expected Behavior

Spaces should be saved in Highlight String 

### Additional Information & Screenshots

"ling" will highlight unintended words like "weakling"
Placing spaces (like " ling ") ensures only that word is highlighted
However spaces are not saved for some reason

![image](https://user-images.githubusercontent.com/42572753/166115488-7dadbd86-d304-4b0d-b58b-79d191d083fa.png)

**Comment by MitchTheUser** [comment]
Not sure if this is a bug, because I've noticed this kind of thing happening all the time, but if it isn't, spaces in the highlight string should definitely be a feature.

**Comment by amylizzle** [comment]
try replacing the spaces with \b instead. Highlight strings support regex and \b is better for that anyway.

**Comment by RenzDot** [comment]
> try replacing the spaces with \b instead. Highlight strings support regex and \b is better for that anyway.

\b worked for me
Though the average user doesn't regex is, so might still consider this a bug
