### ISSUE TITLE
MK. 2 Scout Laser projectiles are rotated incorrectly

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#8381]
### Labels

[BUG]

### Description

The projectiles are rotated the wrong way.

### Steps to reproduce

1. Obtain MK. 2 scout lasers and put it in a pod
2. Fire your new shiny guns
3. Notice the projectiles are sideways
4. Be confused

### Expected Behavior

I expect the projectiles you be the correct orientation 

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/84296283/166120214-5cd93584-36b7-4af1-8e07-f54fff8cf59b.png)

**Comment by virvatuli-gh** [comment]
fixed [here](https://github.com/goonstation/goonstation/commit/39a25dc9fea2fe089dd0ddf688adfeb1622b8f5a)
