### ISSUE TITLE
continuous gas drain on cog1 style toxins

### ISSUE THREAD

**Issue by Kaan-NN** [goonstation/goonstation#8394]
### Labels

[BUG] [MAJOR]

### Description

Gas canisters continously "leak gas"

### Steps to reproduce

1. play a map with a toxins like cog1 (first happened on donut3)
2. prepare a gas mixture (I used 31plasma 62oxygen 6fart)
3. hook the burn mix up on the pipesystem leading through the burn chamber
4. hook up a burn mix on the chamber input and ignite it (exhaust is opened during the burn)
5. space the rooms to keep everything cool?
6. wait until the canister below got some pressure on it 
7. open the purge valve to release some pressure
8. close it after some time
9. realize that the canister continues to lose pressure until its almost empty even though the temperature increases and disconnected from any pipe systems

### Expected Behavior

the canister shouldnt loose pressure after the purge valve is closed especially not if the temperatur is still increasing

### Additional Information & Screenshots

-it occured on cog1 and donut3. It did not occure on cog2.
-it has been tested on the official goon1 server on 1st of march 22 as well as a private server with a build leading
-the initial farts didnt seem to be used up rather the concentrtion increases
-this bug did not occure with pure plasma (I tested it first and then purged the gas, afterwards I hooked up the burn canister and it still happened, the pure plasma was also not very hot/not very high pressure could have affected it)
-the entire gas seems to land outside the vent I only collected parts of it by building some floors and walls at the vent but it has the same exact make up then the gas from the canister
-I didnt test if it does effect engineering in any wa but it might be possible that even closing a valve will drain gas from the TEG or even bursted pipes that got fixed
-it also seems like all the connected gas pipes are affected by that
-refilling the gas canister doesnt fix anything it just drains whatever added as well
![image](https://user-images.githubusercontent.com/68946148/166138854-21edb5c1-e9d2-4293-9349-2609948462fb.png)
![image](https://user-images.githubusercontent.com/68946148/166138859-63ec8e41-0ae9-4993-89c3-3ef1b97545de.png)
![image](https://user-images.githubusercontent.com/68946148/166138862-054ff839-b687-41ea-a982-67edce4a6718.png)

**Comment by ThatFiveGuys** [comment]
For every mol of co2 converted to plasma, .05 mols of farts are removed. This means there is a net decrease in farts (thus mol amount) but its minimal. The main point in pressure loss is oxygen, for fire plasma gets converted into co2 1:1, however oxygen decreases more in fire. So over time the pressure of a fart burn will decrease due to less oxygen and a bit less farts being present. Not a bug, just atmos.
