### ISSUE TITLE
shambler can get trapped by devouring pinned person

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#8411]
### Labels

[BUG]

### Description

shambling abomination can pin someone in one hand, then eat them with a grab in the other to become locked in place and completely incapable of movement

### Steps to reproduce

1. become shambling abomination
2. grab person and pin them to the ground
3. with other hand, grab them again while maintaining the pin
4. devour with the grab and not the pin
5. you can no longer move

### Expected Behavior

being able to move

### Additional Information & Screenshots

i'm pretty sure devouring with the pin doesn't break but for some reason devouring with a separate grab does
i discovered and tested the bug on local server and have not seen/done it on main

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/c781d8756eebfe9f7f537b7dee06da1be90ea6b4
