### ISSUE TITLE
Floortiles always apply steel material

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#8416]
### Labels

[BUG]

### Description

Non-steel floortiles nonetheless apply the steel material to turfs.

### Steps to reproduce

1. Crowbar up a floor that spawns with a material other than steel (wood for wood, grass for synthrubber, carpet for cloth)
2. Note that the correct type of floortile is produced
3. Place that floortile back where you took it
4. The turf is now greyish from applying the steel material, and if you've not taken your cursor off the turf, it'll say something along the lines of steel floor but this corrects itself if you hover over it afterwards.
5. Crowbar the tile again, you now get a steel floortile

### Expected Behavior

The correct material is applied

### Additional Information & Screenshots

This might be a result of that recent change to fix zero amount tile stacks (1b7a8d9eef1e7e9d70fd9e4d8690c33f4c4da962 I think?), I'm not sure and I did not check how multi-tile stacks function.

**Comment by BatElite** [comment]
Okay it only applies to the last tile in a stack

**Comment by Kubius** [comment]
It is indeed a result of [1b7a8d9](https://github.com/goonstation/goonstation/commit/1b7a8d9eef1e7e9d70fd9e4d8690c33f4c4da962); the last tile in a stack is deleted before it's actually applied, meaning there's no material to pull from.
