### ISSUE TITLE
The hover examine message for law modules is not right

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#8425]
### Labels

[BUG]

### Description

Holding alt and hovering the cursor over a law module does not show the updated law for it.

### Steps to reproduce

1. Hold alt.
2. Move cursor over a law module with text set for it.
3. Wait for hover examine message to appear.

### Expected Behavior

For the hover examine message to show the text set for the law.

**Comment by amylizzle** [comment]
Not actually sure this can be fixed without overhauling the tooltips stuff.

**Comment by TealSeer** [comment]
Duplicate of #16287
