### ISSUE TITLE
Portable reclaimer creates an insane amount of empty bars when given individual sheets.

### ISSUE THREAD

**Issue by Josephin23** [goonstation/goonstation#8429]
### Labels

[BUG] [MINOR]

### Description

Inputting a large amount of material sheets individually into the portable reclaimer causes intense empty bar creation.

### Steps to reproduce

1. Put a big amount (99+) of material sheets into the portable reclaimer.
2. Activate the reclaimer.
3. Watch in horror as for each sheet a bar is produced.

### Expected Behavior

Create a bar only for multipliers of 10 and not 100+ empty bars.

### Additional Information & Screenshots

I've only tested this with steel sheets but i assume this works with every material. The bars also spin infinitely in place when thrown, pretty funny ngl.
![Zrzut ekranu 2022-05-02 123434](https://user-images.githubusercontent.com/93096874/166221549-3b45089e-eed1-4e82-8f3b-9312dc410630.png)
![Zrzut ekranu 2022-05-02 123521](https://user-images.githubusercontent.com/93096874/166221556-08c34d89-31c8-45a7-98fb-aa2bbe135192.png)
![Zrzut ekranu 2022-05-02 123545](https://user-images.githubusercontent.com/93096874/166221563-95e3d02e-2302-4150-a215-8978f4ce174e.png)

**Comment by gear-space** [comment]
Cleaning up some old bug reports.

Unable to duplicate as of testing today, so marking as complete. Can't pinpoint exactly when this was fixed as there have been a lot of touches to materials since this bug report was submitted. Please reopen if this is not the case!
