### ISSUE TITLE
New Gourd Drink From Tea Vendor Spawns Empty

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#8438]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Go to tea vendor
2. Order some of that gourd drink
3. Try to take a sip
4. Find out it's empty

### Expected Behavior

For my drink to come with drink

**Comment by nefarious6th** [comment]
the gourd is intended to come empty and then you buy the yerba as a separate item and make it in the gourd; i too wonder if it would be possible to just have the gourd spawn with contents in it, but @colossusqw might have a different idea about why it should be that way

**Comment by colossusqw** [comment]
> the gourd is intended to come empty and then you buy the yerba as a separate item and make it in the gourd; i too wonder if it would be possible to just have the gourd spawn with contents in it, but @colossusqw might have a different idea about why it should be that way

i tried to make it closer to what it is irl, as in the gourd is generally something you keep with you and buy more of the packers and then add water, but it should probably not be as confusing as it is. Maybe if i added the steps to the description in some way..
