### ISSUE TITLE
Meson Goggles not functioning.

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#844]
[BUG]

**Describe the bug**
as the title says meson goggles arent doing their job and miners cant see inside roids even if there on.

**To Reproduce**
1. equip goggles
2. look at asteriod
3. see pitch black in it

**Expected behavior**
being able to see inside the asteriod as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/63602513/82832572-76db1980-9e89-11ea-8e25-a12a26f86495.png)

**Comment by Tarmunora** [comment]
@pali6 Sounds like it may be a victim of recent lighting changes?

**Comment by Tiggersaurus** [comment]
I'll try and check later to see if this is the same for Borg meson upgrade.

**Comment by pali6** [comment]
Correct, Tarm. I'm slowly working on a non-crap way to make light modifiers work.
