### ISSUE TITLE
Broken D-Saber animations

### ISSUE THREAD

**Issue by Exester509** [goonstation/goonstation#8443]
### Labels

[BUG]

### Description

Upon activating/deactivating the d-saber, the inhand c-saber animations play

### Steps to reproduce

1. Obtain a d-saber from a gang locker or otherwise
2. Press C/Click it in hand to turn it on and off
3. It magically plays the normal csaber animations

### Expected Behavior

I expected it not to have any animation at all, since it wasn't included in the PR IIRC

**Comment by ThatFiveGuys** [comment]
Duplicate
