### ISSUE TITLE
Scuttle Bots Delete Items They Are Holding When Turned Back Into Hats

### ISSUE THREAD

**Issue by Wisemonster** [goonstation/goonstation#8462]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1. Get a scuttlebot.
2. Grab something as a scuttlebot
3. Return to body
4. Use the scuttlebot glasses on the scuttlebot
5. Notice they return to hat form, but leave no item behind
6. Use hat to summon scuttlebot
7. Notice it is no longer holding anything
8. Cry at the captain's spare you just deleted

### Expected Behavior

For the scuttlebot to drop the item it is holding when it returns to hat form

**Comment by Bartimeus973** [comment]
Yep, makes sense, i'll fix it real quick

**Comment by Bartimeus973** [comment]
[https://github.com/goonstation/goonstation/pull/8463](url)
