### ISSUE TITLE
Bank computer doesn't total funds properly

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#8497]
### Labels

[BUG]

### Description

As title, it only counts the research budget

### Steps to reproduce

1. Get to a bank computer
2. put some money in all the categories
3. See error

### Expected Behavior

for the computer to compute

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/31984217/167229269-3a855cd3-240f-4022-8819-4827483bb852.png)

**Comment by Gerhazo** [comment]
Fixed in bc5276b682c6c51fde50e1cacfb0489d327be63a
