### ISSUE TITLE
you can feed a dead chicken and it will respond with a face

### ISSUE THREAD

**Issue by cathychav** [goonstation/goonstation#8500]
### Labels

[MINOR]

### Description

when you feed a dead chicken, it responds with a face just like an alive one would

### Steps to reproduce

1. get a chicken
2. start feeding it
3. it responds with a face

### Expected Behavior

the chickens already dead, so you shouldn't be able to feed it nor should it react as if it's alive

**Comment by UrsulaMejor** [comment]
lol.

**Comment by UrsulaMejor** [comment]
Fixed.
