### ISSUE TITLE
Observers do not always have see_invisible set correctly

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#8511]
### Labels

[BUG]

### Description

Observers can have see_invisible 10 instead of 17

### Steps to reproduce

Unreliable reproduction

1. Join a round in progress
2. Click Observe round
3. Check your ghost's see_invisible var, the value is 10
4. Use admin tools to Respawn Self
5. Click Observe round
6. Check your ghost's see_invisible var, the value is 17

### Expected Behavior

see_invisible is always 17

**Comment by UrsulaMejor** [comment]
Seems to have been fixed at some point by other changes to see_invisible stuff; unable to reproduce and I can't find any logic in the game that sets see_invisible to 10 unless you're a flock
