### ISSUE TITLE
Hemostat doesn't work when you're not the one operating 

### ISSUE THREAD

**Issue by TheBlueHatUD** [goonstation/goonstation#8522]
### Labels

[BUG]

### Description

Whenever there's a person operating, and the second one using a hemostat, the hemostat does not work on the person that's under the knife

### Steps to reproduce

1. perform any surgery
2. get one of the surgery steps to make the person bleed
3. have another person use a hemostat while the person is undergoing surgery

### Expected Behavior

the hemostat should stop the bleeding wether you're doing the surgery or not

**Comment by TheTyrant25** [comment]
outdated due to new chest surgery. Presumably fixed.
