### ISSUE TITLE
If two players get in the port-a-brig only one can exit

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#8530]
### Labels

[BUG]

### Description

Brig only allows exit of one player

### Steps to reproduce

1. Get two players to action bar into the port-a-brig at the same time.
2. Both enter.
3. Both try to exit.
4. Only one can exit.

### Expected Behavior

Maximum of one occupant

### Additional Information & Screenshots

Presumably the brig only bothers to try and handle one occupant and needs some kind of check to prevent two entering.

**Comment by UrsulaMejor** [comment]
Appears to have been fixed.

**Comment by UrsulaMejor** [comment]
![image](https://github.com/goonstation/goonstation/assets/50289389/b0ac158b-9a4a-4ed1-b269-b3861690e7e1)
