### ISSUE TITLE
debris is kinda messed up

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#8531]
### Labels

[BUG]

### Description

Asteroids are intersecting setpieces in odd ways and stuff I can't really describe

### Steps to reproduce

1. Go to debris
2. Wander around

### Expected Behavior

Debris looks better.

### Additional Information & Screenshots

This somehow posted while I was still writing it so give me a few minutes to get the screenshots aaaaaaa
![brokedebris1](https://user-images.githubusercontent.com/63796800/167445027-b8d1a29c-8b21-4a55-b7c0-1f8bf117a054.png)
![brokedebris2](https://user-images.githubusercontent.com/63796800/167445053-ced21dd1-8463-495a-a878-bff8f458dc3f.png)
![brokedebris3](https://user-images.githubusercontent.com/63796800/167445068-cb0ace35-a16a-438b-8213-c6901bf44fb3.png)

**Comment by MetricDuck** [comment]
Fixed in #8535
