### ISSUE TITLE
Blob observers are pulled by bubsium

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#8532]
### Labels

[BUG]

### Description

Blob observers are pulled by bubsium

### Steps to reproduce

1. Be a blob observer
2. Be near a bubsium filled player
3. Get pulled towards them

### Expected Behavior

Blob observers not be moved

**Comment by swinglow20** [comment]
Same thing happens to the AI eye. Singularity, grav artifacts and other movements affect their "ghost" including, I think, pressure change. I feel like I've had issues closing certain airlocks before because the air is getting sucked out and it keeps moving me.
