### ISSUE TITLE
Laser sprite appears to be facing the wrong way.

### ISSUE THREAD

**Issue by ThatsMamaLuigiToYouMario** [goonstation/goonstation#8539]
### Labels

[BUG][MINOR]

### Description

Lasers fired from any device appear to be facing the wrong way.

### Steps to reproduce

1. Get a device that fires lasers, such as an Energy Gun or Pod Lasers.
2. Fire the weapon.
3. Observe that the lasers appear to be firing improperly, coming out vertically from the weapon.

### Expected Behavior

I expect the lasers to face the right way when fired from my weapon.

**Comment by virvatuli-gh** [comment]
fixed [here](https://github.com/goonstation/goonstation/commit/39a25dc9fea2fe089dd0ddf688adfeb1622b8f5a)

**Comment by blackrep** [comment]
This probably also fixes #8381. They use the same laser sprites.
