### ISSUE TITLE
Dying as Scuttlebug in VR makes you observer

### ISSUE THREAD

**Issue by Jak27** [goonstation/goonstation#8559]
### Labels

[BUG]

### Description

When I die as a scuttlebot in VR, it makes you an observer, and you cant rejoin the murderbox, it kicks you out of VR.

### Steps to reproduce

1. Go into the murderbox
2. Equip the scuttlebug
3. You die while you are a scuttlebug
4. You become an observer that looks like a scuttlebug ghost (lmao)
5. Try to rejoin murderbox
6. Get ejected

### Expected Behavior

To not become an observer and be permanently banned from playing VR when dying as a scuttlebug.

**Comment by MetricDuck** [comment]
Scuttlebug is no longer purchaseable in VR as of fea6fb1
