### ISSUE TITLE
Getting stunned while holding a phone allows you to hear the phone from any distance

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#8567]
### Labels

[BUG]

### Description

If you get stunned while holding a phone, causing you to drop it, you can then walk away and hear the phone still.

### Steps to reproduce

1. Call a departments phone
2. Get stunned, drop phone
3. Walk away 
4. You can hear the person talking on the phone without being anywhere near it

### Expected Behavior

I don't think I should be able to hear the phone inside of security after security threw me out.

**Comment by UrsulaMejor** [comment]
They can't hear you, but i have confirmed that you can hear them
