### ISSUE TITLE
Swap character mid round with vr azone

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#8571]
### Labels

[BUG]

### Description

If you load a different character before entering vr azone, you will become that character.

### Steps to reproduce

1. Join round
2. Load a different character
3. Enter vr azone
4. You are now the character you just loaded

### Expected Behavior

I should stay as my round-start character

### Additional Information & Screenshots

I had also cryo'd and closed out of the game for a bit before I entered vr, unsure if this is required for the issue to occur.

**Comment by UrsulaMejor** [comment]
I have zero clue how to fix this, nor do I think I want to. I guess your "avatar" is your other character.
