### ISSUE TITLE
Lootchests ignore BR blacklist.

### ISSUE THREAD

**Issue by Josephin23** [goonstation/goonstation#8600]
### Labels

[BUG]

### Description

Battle royale lootchests ignore the blacklist, allowing blacklisted items such as red chainsaw to spawn.

### Steps to reproduce

1. Start a battle royale round.
2. Spawn lootchests over and over until you get a blacklisted item.

### Expected Behavior

Lootchests should follow the blacklist and not allow intant win items such as cloakers to spawn.

### Additional Information & Screenshots

Happened on round 132305 just now, someone got red chainsaw in a lootchest and basically had a free win.
Fine if this isn't a bug, would be really weird though given the reasoning of blacklisting them in the first place.

**Comment by flappybatpal** [comment]
Fixed by [644f56e2dcebddaae7dfc4eff63f122c9b107712](https://github.com/goonstation/goonstation/commit/644f56e2dcebddaae7dfc4eff63f122c9b107712)
