### ISSUE TITLE
Freezing upon opening any dialog box, especially for the first time

### ISSUE THREAD

**Issue by CourageTheCat** [goonstation/goonstation#8611]
### Labels

[BUG]

### Description

opening any kind of dialog box freezes the whole game for 10-20 seconds

### Steps to reproduce

1. click on nearly anything that requires HTML
2. freeze
3. suffer

### Expected Behavior

I would have expected for the game to be playable

**Comment by amylizzle** [comment]
Try clearing your BYOND cache, and also your IE cache.

**Comment by CourageTheCat** [comment]
I try to open IE but it just freezes and dies :(

**Comment by CourageTheCat** [comment]
tried it, still freezes :(

**Comment by amylizzle** [comment]
It kinda sounds like something is super janked on your system. I recommend coming on to discord and seeing if we can help there, since this isn't really the appropriate forum. Closing this issue.
