### ISSUE TITLE
Penlights probably can still flash people through their eye protection

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#8617]
### Labels

[BUG]

### Description

title

### Steps to reproduce

1. Shine a penlight in someones eyes
2. Ow thats bright
3. Do it again on someone wearing sechuds / welding mask / gas mask
4. Chat says you cant see their eyes
5. Same on yourself with eyewear
6. Ow thats bright
7. See issue

### Expected Behavior

Eyewear that prevents flashes from stunning you prevents penlights from making your screen go white

### Additional Information & Screenshots

Whoever fixes this the penlight is also extremely effing bright and while that is intentional it might do stuff to people with epilepsy if circumstances make thing go funky? Idk. 
They should totally still be a tool for annoying people / legit use but this bug might be annoying

I think I forgot to report this bug a while back oops.

**Comment by pgmzeta** [comment]
Feature removed, closed with #9352
