### ISSUE TITLE
Attempting to lay down with treads causes slowdown

### ISSUE THREAD

**Issue by Sord213** [goonstation/goonstation#8619]
### Labels

[BUG] [TRIVIAL]

### Description

If you are moving around while having treads as legs and you hit the hotkey or hud button to lay down it will slow you down but not make you lay down.

### Steps to reproduce

1. Have treads 4 legs
2. Attempt to lay down
3. slow down for half a second

### Expected Behavior

I know you can't lay down with treads but I would expect the slowdown to not happen

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/a5237fadc0d325c968983a05404cd08f5ab7530f
