### ISSUE TITLE
Invisable Pizza Maker

### ISSUE THREAD

**Issue by Conchuckter** [goonstation/goonstation#8622]
### Labels

[BUG]

### Description

This pizza vending machine is invisable, it probably shouldn't do that.
It's also is not usable. (Because it was knocked over)

UPDATE: I pried it upright and it became visable and usable, this leads me to believe the pizza machine does not have a knocked over sprite.

### Steps to reproduce

I don't know, I just stumbled apon it, however I did see that it seemed like there had been a explosion shortly before.

### Expected Behavior

The pizza maker should of been visable

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/93377868/168745889-a9b9471c-4dfa-43fc-ac32-a8a9a93a88e7.png)

**Comment by nefarious6th** [comment]
this is fixed, tested on local and all is well now

**Comment by Conchuckter** [comment]
Fixed with resprite
