### ISSUE TITLE
Uploading two laws at the same time deletes one of them

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#8633]
### Labels

[BUG]

### Description

^

### Steps to reproduce

1. Have two people with law modules
2. Have them both start uploading
3. The law that gets uploaded first gets overwritten by the one that comes after

### Expected Behavior

They should check which slot is free at the end of the action bar not the start

**Comment by amylizzle** [comment]
race conditions :screm:
