### ISSUE TITLE
You can put grabs in a cabinet

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#8634]
### Labels

[BUG]

### Description

The glass cabinets in research/medbay accept grabs

### Steps to reproduce

1. Block and click on an empty cabinet slot
2. Observe your block resting neatly on the shelf

### Expected Behavior

Another "if is grab don't do this" check

**Comment by frawhst** [comment]
merge conflict

**Comment by TobleroneSwordfish** [comment]
merge conflict.

**Comment by UrsulaMejor** [comment]
verified issue, woorks with blocks too
