### ISSUE TITLE
Borg managed to drop an integrated beaker

### ISSUE THREAD

**Issue by MeggalBozale** [goonstation/goonstation#8637]
### Labels

[BUG]

### Description

Borg managed to drop an integrated beaker

### Steps to reproduce

1. I do not know how and I do not know why. Sorry

### Expected Behavior

I expected this not to happen

### Additional Information & Screenshots

I picked up these beakers and could not drop them by any means. They were using a reagent heater and chem dispenser.
![bruhhhh'](https://user-images.githubusercontent.com/27376947/169150830-aa5a0db7-61f3-4575-b764-9d262e072870.png)

**Comment by soleilan** [comment]
seems fixed 👍
