### ISSUE TITLE
Single poster triggers Wizard popup

### ISSUE THREAD

**Issue by mikecsiy** [goonstation/goonstation#8639]
### Labels

[BUG]

### Description

There is a single generic poster that triggers the Wizard popup when examined

### Steps to reproduce

1. Find instance of /obj/decal/poster
2. Examine said poster
3. Wizard popup is displayed

### Expected Behavior

Wizard popup should not be displayed when examining this poster

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/29447052/169185695-0e0d70cc-c8ec-4d42-b872-f9647a360f3b.png)
![image](https://user-images.githubusercontent.com/29447052/169185729-1848c3e3-d17d-4adb-898d-e89a9bda38b3.png)

**Comment by MetricDuck** [comment]
Even the code is wondering why this is a thing...

![image](https://user-images.githubusercontent.com/86617057/170150141-f8b9791f-7d67-41c7-b61d-9c88e0d7bdbe.png)
