### ISSUE TITLE
Status displays can be under girders

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#8654]
### Labels

[BUG]

### Description

Status displays will appear to be under girders on the same tile.

### Steps to reproduce

1. Move a movable girder, I would think from the wall that initially appeared under the status display, onto the same tile as the status display

### Expected Behavior

For the status display to appear over the girder?

**Comment by UrsulaMejor** [comment]
Unable to reproduce. seems fixed?
