### ISSUE TITLE
Contents of unopened soda can be poured out of the container.

### ISSUE THREAD

**Issue by HBS-System** [goonstation/goonstation#8658]
### Labels

[BUG] [MINOR] [QoL]

### Description

You can pour out the contents of an unopened soda can onto floors, walls and some other surfaces I have yet to test.

### Steps to reproduce

1. Get a fresh, unopened soda can.
2. Click on a wall or floor, attempt with other surfaces as there may be more. The contents will spill out.

### Expected Behavior

I expect the contents to be sealed inside the container preventing it from being emptied and poured out, unless the can is opened.

**Comment by Buyrcsp2** [comment]
I have written a code that made it pour 0 unit into the floor when sealed, i will be testing it for now.

**Comment by Buyrcsp2** [comment]
after trying to fix this, i found out goonstation code is inflexible, and will be coding, however expect a fix soon
