### ISSUE TITLE
clownspiders target Aeyes

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#8683]
### Labels

[BUG]

### Description

they target AEYES

### Steps to reproduce

1. be Aeye
2. watch funny clownspider in pathology
3. it attacks you
4. it also phases through a wall into space while biting you

### Expected Behavior

this not to happen :(

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/169709663-457e994b-2fdd-475e-8c39-aea3f017fb02.png)
![image](https://user-images.githubusercontent.com/96703882/169709720-d0bf0318-380c-431d-a4a6-c2be58729a5f.png)

**Comment by Tarmunora** [comment]
fixed
