### ISSUE TITLE
Bows act weirdly with stacked arrows

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#8719]
### Labels

[BUG]

### Description

Feeding a bow from a stack of arrows fails to update the bow's sprite, and it will also happily accept more arrows despite already being loaded

### Steps to reproduce

1. Make a bow and a stack arrows
2. Load an arrow from the stack, note the sprite doesn't update
3. Load another. It'll give you message that there's already an arrow but it'll consume it anyway
4. Weep softly

### Expected Behavior

The sprite updating properly and no missing arrows

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/edbd851b4f2889b4ea77eb495be6a25768b08ebb
