### ISSUE TITLE
You can hit your own pod with its own lasers by moving a certain way

### ISSUE THREAD

**Issue by Yellow-Mushroom** [goonstation/goonstation#8745]
### Labels

[BUG]

### Description

So if youre moving diagonally after firing (which happens often in pod battles), you can somehow hit your own pod with your own laser, damaging it. It is done best my strafing one drection, firing one way, then moving diagonally the other. The video displays it some

### Steps to reproduce

1. be moving a certain direction
2. fire your weapon diagonally quicky
3. move slightly into the direction you fired into
4. notice as your own weapon hits your own pod

### Expected Behavior

My own weapons to not hit my own pod during a podfight

### Additional Information & Screenshots

Happens with both mk2 and mk4's, haven't tested others though

https://user-images.githubusercontent.com/75814831/170389886-85f4001d-5b40-4177-a235-1bc87ba4cf19.mp4

**Comment by CheffieGithub** [comment]
Fixed by commit 0a7387d.
