### ISSUE TITLE
Getting into pod action bar is whacky

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#8787]
### Labels

[BUG]

### Description

It has a double bar

### Steps to reproduce

1. spawn into goon
2. enter pod through click drag
3. observe jank

### Expected Behavior

I expect there to only be one

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/170804572-5c3e3f36-7eea-48fb-b5ce-6b028e92ef3d.png)
![image](https://user-images.githubusercontent.com/96703882/170804586-dedf67fe-b2ff-498c-b0e9-6b1a2261df4a.png)

**Comment by frawhst** [comment]
this is probably me

**Comment by frawhst** [comment]
c8f326f949dbf593e27641a64af6c282487ee5b4
