### ISSUE TITLE
chameleon projector protects from radstorms

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#8813]
### Labels

[BUG]

### Description

radstorms do not hit you while you are using a chameleon projector

### Steps to reproduce

1. spawn chameleon projector
2. trigger radstorm
3. use chameleon projector to become an item
4. radstorm will not hit you

### Expected Behavior

getting hit by rad storm

**Comment by soleilan** [comment]
syndicate tech strong 💪

**Comment by UrsulaMejor** [comment]
Feature imo (also it's coded by putting you inside a dummy item which would make this a pain to fix)

Maybe we could rename the item to better fit how it actually functions in lore, since a lot of these interactions are funny
