### ISSUE TITLE
Gang health buff initial health update issue

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#882]
**Describe the bug**
If you're at full health, 100% healthy as presumed by health analyzer, after you put on gang clothes and receive a health buff despite having no injuries you'll count as just 76% healthy and also suffer yellow health damage slowdown.
Punching yourself or doing anything else to prompt a health update will resolve this, albeit the initial functionality is still bugged.

**To Reproduce**
1. Become a gang member.
2. Dispense gang clothes and put them on from the locker.
3. Your health will show up as yellow and you'll suffer slowdown despite not being injured.
4. Prompting a health update by punching yourself or otherwise resolves the former.

**Expected behavior**
Not being considered injured

**Additional context**
The status effect is named "ganger" in statusSystem.dm, adding and removing the buff seems to be handled in /datum/game_mode/gang/process() of gangwar.dm.

**Comment by Tarmunora** [comment]
Uhg, max health changes probably should be triggering a health update. Will look into solutions
