### ISSUE TITLE
constructed crushers undeconstructable

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#884]
[BUG]

**Describe the bug**
Crushers constructed via scanning with the syndicate device analyzer cannot be deconstructed, instead printing the message that you must have sufficient access to operate the crusher to deconstruct it.

**To Reproduce**
1. Wait for someone to make a crusher or three, probably in a main hallway.
2. Attempt to deconstruct it so the station isn't cut in half.
3. Fail miserably.

**Expected behavior**
Being able to deconstruct crushers instead of giving up and having everyone explode.

[BUG]

**Comment by Tarmunora** [comment]
@UrsulaMejor can this be closed now?

**Comment by Gerhazo** [comment]
Closed per #984
