### ISSUE TITLE
Cyberappendix (possibly) not functioning correctly

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#885]
[BUG]

**Describe the bug**
The cyberappendix used to periodically inject you with small amounts of delicious healing chems, but does not appear to do that anymore.

**To Reproduce**
1. Replace your appendix with a cyberappendix
2. Get injured
3. Watch yourself not heal
4. Be sad that the cyber version of the most useless organ is now mostly useless

**Expected behavior**
Periodic injections of a small amount of charcoal, saline-glucose, salbutamol, or salicylic acid.  

This may have been an intentional change, but I didn't see it in the changelog so I'm reporting it.

**Comment by moonlol** [comment]
unable to reproduce. works fine for me

**Comment by Cthucky** [comment]
For what it's worth I've been unable to reproduce it after reporting it.  Whatever was causing it must either have been fixed or be a really niche thing.
