### ISSUE TITLE
Cardboard clumps disappearing when added to fabricator

### ISSUE THREAD

**Issue by freshoob** [goonstation/goonstation#8855]
### Labels

[BUG]

### Description

Cardboard is a material that is required in fabricators for some items. Cardboard currently can't be added to fabricators because the processed form - a cardboard clump - disappears as soon as it is added to a fabricator.

### Steps to reproduce

1. Acquire cardboard sheets
2. Add cardboard sheets to portable reclaimer to get a cardboard clump
3. Add cardboard clump to fabricator
4. Check materials list inside fabricator to see there is no cardboard clump, and that it has disappeared from your inventory as if it had been entered

### Expected Behavior

The cardboard clump should add a quantity of cardboard material to a fabricator when added.

**Comment by UrsulaMejor** [comment]
unable to reproduce; this appears to have been fixed
![image](https://github.com/goonstation/goonstation/assets/50289389/aa4cef21-aa32-44a2-a3e7-c82bee01fb7b)
