### ISSUE TITLE
TGUI DOESN'T WORK

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#8865]
### Labels

[Critical]

### Description

TGUI IS BUSTED

### Steps to reproduce

1. Open up a TGUI menu.
2. Have a white square forever.

### Expected Behavior

To open up a menu

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/171316492-95fca31c-2263-49e7-8752-6a3ff3ac9251.png)

**Comment by frawhst** [comment]
fixed next round
