### ISSUE TITLE
character drops inhand item as soon as i exit cryo storage

### ISSUE THREAD

**Issue by queen-mab** [goonstation/goonstation#8880]
### Labels

[BUG]

### Description

character drops inhand item as soon as i exit cryo storage

### Steps to reproduce

1. i late join the round
2. i exit cryo storage
3. my character drops their item (for example first aid when i spawn as doctor)

### Expected Behavior

my character keeps their item in their hands

**Comment by nefarious6th** [comment]
i know u got plant arms, so i assume this is the same as #8802

**Comment by ThatFiveGuys** [comment]
Closing due to other one having more info
