### ISSUE TITLE
Can't mount stools

### ISSUE THREAD

**Issue by Remixful** [goonstation/goonstation#8918]
### Labels

[BUG]

### Description

Can't mount stools (to shoulder dive)

### Steps to reproduce

1. Try to mount any stool (press Z while on the stool)

There's a stool in some boxing rings but what's the point if you can't use them?

### Expected Behavior

Can mount and shoulder dive

**Comment by frawhst** [comment]
Not a bug at the moment since you can't really do anything with stools. Could be revisited as a feature.
