### ISSUE TITLE
Borgs can trigger portable flashers with no cooldown.

### ISSUE THREAD

**Issue by ThatFiveGuys** [goonstation/goonstation#8936]
### Labels

[BUG]

### Description

Title

### Steps to reproduce

1.  Be borg
2.  Press portable flasher
3. See you can do it with no cooldown.

### Expected Behavior

For there to be a cooldown when using it.

**Comment by TTerc** [comment]
e0b5a864e64d3d327dbe5ff3532ac0351d9dba6e
