### ISSUE TITLE
Chemicompiler Register Values Not Auto-Updating

### ISSUE THREAD

**Issue by GimmeUrCoin** [goonstation/goonstation#8941]
### Labels

[BUG]

### Description

When the chemicompiler is finished compiling, the register readouts don't update

### Steps to reproduce

1. Change the value of any register
2. The readouts do not auto-update unless you click the machine or a button.

### Expected Behavior

Readouts should refresh automatically

**Comment by soleilan** [comment]
tgui fix plz

**Comment by Garash2k** [comment]
TeeGooed by #19107
