### ISSUE TITLE
Medical Cyborgs can't call Port-A-NanoMed or Port-A-MedBay

### ISSUE THREAD

**Issue by GimmeUrCoin** [goonstation/goonstation#8994]
### Labels

[BUG]

### Description

Not sure if intentional but cyborgs can't call Port-A-NanoMed or Port-A-MedBay

### Steps to reproduce

1. Try to call Port-A-NanoMed orPort-A-MedBay as cyborg (especially medical cyborg) on PDA

### Expected Behavior

I think cyborgs (at least the medical cyborgs) should be able to call Port-A-NanoMed and Port-A-MedBay

**Comment by TealSeer** [comment]
Could not reproduce
