### ISSUE TITLE
Singularity is still able to be activated without a proper containment up.

### ISSUE THREAD

**Issue by Momoberry** [goonstation/goonstation#9003]
### Labels

[BUG] [CRITICAL]

### Description

As the title says, you are able to activate a singularity without a proper containment procedure still.

### Steps to reproduce

This is going to be a little less coherent and simple than other step by steps.

The way I think this functions currently is that it checks for if "four" field generators have been activated, and then checks if there's 4 field generators forming a proper cage containment. The issue with that is I don't think it's checking that those 4 field generators are the ones that are "ACTIVE", and rather just that four are active in the vicinity, and four are making a containment. I've attached a picture below of an example I pulled off on saturday on donut3 highpop (not intentionally, bugger engineer tried to add more field generators after I said no, lol.)

Attach 4 field generators at the standard points in a square, weld them down and attach them. Next, once all four of those are down, add 3 field generators in between each of the east, north, and west containments (ideally symmetrical, but don't think it REALLY matters). Weld and bolt. Activate The bottom row, then activate one of east or west sides. Just keep activating while leaving a "gap", by not activating the final top ones. It will "probably" make an unfinished containment activate.

### Expected Behavior

The singularity REQUIRES a proper caged containment to form before activating.

### Additional Information & Screenshots

https://i.gyazo.com/ffd6b775f0c1142a69e0118d17f489d4.png

I'd also like to note that currently if you have a field generator in between two other ones, but attach it after you attach the initial connection, it will interrupt it and make it so you cannot attach the two "main" generators, even if you remove it.

**Comment by pali6** [comment]
It's been a while so it might have changed since then but iirc the actual check for whether the singulo generator is contained is... very weak. I think it's on the level of "check if 4 active field gens are nearby xoxo".
