### ISSUE TITLE
is the AI!

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#9046]
### Labels

[BUG]

### Description

The start of round message saying who the AI is simply says "is the AI!" now

### Steps to reproduce

1. Start a round with an AI in it

### Expected Behavior

I expected it to display the AI's name

**Comment by TobleroneSwordfish** [comment]
![image](https://user-images.githubusercontent.com/20713227/172678627-bdd2392e-e20c-45f3-8df9-a8f1c97a2dd6.png)

**Comment by frawhst** [comment]
751629996a9d82f0cf501b89da63efff8bbb0015

me forgetting to check for `src` in the final confirmation prompt, meaning it was getting sent to `null` and you could never confirm
