### ISSUE TITLE
Borgs don't use their special hud for targeting bodyparts

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#9050]
### Labels

[minor]

### Description

Cyborg hud has a mismatch hud icon compared to the rest of their hud.

### Steps to reproduce

1. Use Vaporized hud style
2. be borg

### Expected Behavior

To have a matching UI throughout the borg hud.

### Additional Information & Screenshots
Screenshot of the issue:
![image](https://user-images.githubusercontent.com/40079883/172704178-a17cba5d-08c4-4141-ac91-8c020e1a2177.png)

There currently IS a special sprite for all of it. They just aren't used for some reason.

**Comment by pgmzeta** [comment]
Fixed with #10179
