### ISSUE TITLE
Ghostdrone cybernetic cleaner bottle appears empty until first use

### ISSUE THREAD

**Issue by FlameArrow57** [goonstation/goonstation#9078]
### Labels

[BUG]

### Description

The ghostdrone cybernetic cleaner bottle appears to be empty on examine until used.

### Steps to reproduce

1. Be ghostdrone
2. Equip cybernetic cleaning spray for first time
3. Examine it

### Expected Behavior

For it to say its full.

**Comment by Josephin23** [comment]
![obraz](https://user-images.githubusercontent.com/93096874/183850357-54f0fb8d-a8a0-4ee8-94cc-f97215ee04b7.png)
looks fixed

**Comment by TobleroneSwordfish** [comment]
I'd guess one of the ghostdrone QoL PRs fixed this then
