### ISSUE TITLE
clothing rewards on cyborgs

### ISSUE THREAD

**Issue by Kaan-NN** [goonstation/goonstation#9086]
### Labels

[BUG]

### Description

cyborgs cant use the rewards that alter lab coats

### Steps to reproduce

1. by cyborg
2. get a lab coat
3. try claim reward
4. see it fail because only humans can use this

### Expected Behavior

rewards should alter clothing on cyborgs as well

**Comment by soleilan** [comment]
intended that only humans can but like.. why not cyborgs whats the worst that can happen 😎 too much work for me though

**Comment by Retrino** [comment]
not really a bug as much as a feature request

**Comment by UrsulaMejor** [comment]
1) strictly speaking, the cyborg isn't "wearing" the lab coat, so the check would fail on that count
2) these all explicitly call for humans

Feature request, not a bug
