### ISSUE TITLE
Mk. 4 Assault Lasers can shoot their way through spacial tears

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#9091]
### Labels

[BUG]

### Description

Unsure if this is a bug or not, feel free to close. A Mk. 4 Assault Laser has the capacity to blow up a spatial anomaly.

### Steps to reproduce

1. Find a pod weapon of overwhelming firepower (Mk. 4 Assault Laser)
2. Find an impassible anomaly with your pod
3. Shoot it out of frustration & discover you punched a hole through this unusual phenomenae.
4. Surprised Pikachu face

### Expected Behavior

I expect not to shoot my way through an anomaly. Maybe?

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/84296283/173206679-256ecee3-87de-48ec-a07b-84fa0ee4b77e.png)

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/3cd2266c4da9b0be1463f3107a5c1d07bd965e21
