### ISSUE TITLE
Antag critter gunbot can catch fire and takes burn damage

### ISSUE THREAD

**Issue by flappybatpal** [goonstation/goonstation#9103]
### Labels

[BUG]

### Description

Critter gunbot can be on fire

### Steps to reproduce

1. Be a /mob/living/critter/robotic/gunbot
2. Be set on fire
3. Be on fire!!!

### Expected Behavior

Robots are fire immune

**Comment by frawhst** [comment]
75e99a1bd4a366b962db789ea3b8668ac9aa9a9b
