### ISSUE TITLE
Overwriting of mind.special_role renders you unable to use your spy PDA (and probably other issues)

### ISSUE THREAD

**Issue by frawhst** [goonstation/goonstation#9110]
### Labels

[BUG]

### Description

If you have your mind's special role changed to something other than `spy_thief`, such as by a random event antag, and you get cloned from your original body, you will not longer be able to claim spy bounties (as it doesn't think you're a spy)

### Steps to reproduce

1. Be spy thief
2. Die
3. Get random event antag critter spawn
4. `mind.special_role` now `fire elemental`
5. Die
6. Get cloned from your original human body
7. Try to use spy PDA
8. "Doesn't recognize you!"

### Expected Behavior

Either respawning as an event antag renders you uncloneable (which I expected frankly) or your previous `special_role` is maintained somehow.

**Comment by soleilan** [comment]
possibly fixed with datumizations?
