### ISSUE TITLE
Nano-fabricator storage does not update

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#9112]
### Labels

[BUG]

### Description

Inserting material blocks into the nano-fabricator does not update the storage. Meaning that the nano-fabricator is inoperable.

### Steps to reproduce

1. Grab some material (I used plasmaglass)
2. Insert it in the nano-fabricator
3. Check it's storage
4. Notice it's empty
5. Try to make something using the material
6. Notice it says no materials found
7. Cri that you can't have fancy plasmaglass sunglasses

### Expected Behavior

I expect the nano-fabricator storage to udpate.

### Additional Information & Screenshots

May also be related to the change that broke #9104.

**Comment by frawhst** [comment]
Might have incidentally fixed this, testing now

**Comment by frawhst** [comment]
Seems to work, should be fixed next round
