### ISSUE TITLE
scuttlebots have blood

### ISSUE THREAD

**Issue by mantwerp** [goonstation/goonstation#9147]
### Labels

[BUG]

### Description

scuttlebots have blood, which i don't think they're really supposed to have, scuttleboot blood lore??????

### Steps to reproduce

1. get a scuttlebot
2. draw blood with syringe
3. get blood from the felt hat

### Expected Behavior

for the hat to not have blood

**Comment by ThatFiveGuys** [comment]
Pathing my beloathed

**Comment by frawhst** [comment]
scuttlebots are alive. did they not tell you that? did the company not teach you that in detective school? they feel pain

**Comment by Nihisohel** [comment]
red blood is just ketchup flavored oil
