### ISSUE TITLE
items in hand sometimes stop existing when you slip

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#9151]
### Labels

[BUG]

### Description

Sometimes, when you slip and fall, an item you're carrying will just seemingly vanish into the ether.  Sometimes it's possible I'm just missing it but I've seen it happen with a hadar power sword which isn't that easy to miss and doesn't really fit in anything so it's definitely happening.

### Steps to reproduce

1. I have no fucking idea
2. In the most recent one (about 10-15 minutes before I reported this, Goon1 if that helps) I slipped as I was reloading the detective revolver by clicking on the ammo in my inventory.  The revolver vanished but the ammo appeared on the ground where I slipped.  Could easily be a red herring because I've seen it happen, as mentioned, with a hadar power sword and those don't get reloaded.

### Expected Behavior

I expect my spacemans to have object permanence.

**Comment by frawhst** [comment]
Standard for these sort of things is that it's probably being dropped inside you somehow. Will see if I can reproduce with slips

**Comment by flappybatpal** [comment]
I feel like we would have heard way more on this if it occured.

**Comment by UrsulaMejor** [comment]
Unable to reproduce despite a lot of testing; if it happens again someone can reopen
