### ISSUE TITLE
hunter has no antag hud icon

### ISSUE THREAD

**Issue by kotomato** [goonstation/goonstation#9153]
### Labels

[BUG] [MINOR}

### Description

hunter does not have an icon over them signifying that they are antag at round end

### Steps to reproduce

1. be hunter
2. exist at round end
3. no icon

### Expected Behavior

icon

### Additional Information & Screenshots

![unknown](https://user-images.githubusercontent.com/93528889/173713023-a84af993-fb25-4c3c-81fc-3dd1e293da61.png)

**Comment by ZeWaka** [comment]
you shouldn't be seeing any icons
