### ISSUE TITLE
All shoes seem to always go over the uniform and the outer layer of clothing

### ISSUE THREAD

**Issue by Blahowsky** [goonstation/goonstation#9159]
### Labels

[BUG]

### Description

It used to be that if you put on a uniform and then shoes on, the shoes would go over the uniform, but if you put on shoes then a uniform on, the uniform would go over the shoes. The outer layer never went under the shoes.

### Steps to reproduce

1. Wear shoes (mechboots, boots, heavy military boots, or galoshes it's best visible on)
2. wear a uniform (it most sticks out on dresses)
3. it goes over the uniform, and if you wear an outer layer and then the shoes they will go over that too. (space suit for example)
4. if you wear shoes first and then a uniform, the shoes still go over the uniform layer.

### Expected Behavior

The shoes should go over the uniform is the uniform was worn first, but if the shoes were worn first then the uniform should appear over the shoes. The outer clothing layer should never go under the shoes.

**Comment by Nihisohel** [comment]
okay maybe the spacesuit one looks a bit too cool to remove

**Comment by TobleroneSwordfish** [comment]
Same cause as #9085 and #9137 I believe

**Comment by frawhst** [comment]
fixed by 4365fd6
shoes should layer under armor like normal now
