### ISSUE TITLE
voltagen volume scaling is broken

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#9167]
### Labels

[BUG]

### Description

voltagen volume scaling doesnt work

### Steps to reproduce

1. fill an instance of obj/reagent_dispensers with 4000u of voltagen (note that tests confirmed that the power of this and .1u of voltagen were the same)
2. detonate it
3. it tickles

### Expected Behavior

extremely lethal arcflash, proper volume scaling

### Additional Information & Screenshots

make sure its powerful enough due to it not exactly being a cakewalk to produce.

**Comment by soleilan** [comment]
```dm
if(volume >= 5)
  var/count = 0
  for (var/mob/living/L in oview(round(min(volume/5, 5)), get_turf(holder.my_atom)))
  count++
  for (var/mob/living/L in oview(round(min(volume/5, 5)), get_turf(holder.my_atom)))
  arcFlash(holder.my_atom, L, min(75000 / count, volume * 1000 / count), stun_coeff = min(volume / 25, 1))
else
  elecflash(holder.my_atom)```

just does a elecflash with default power of 1 over 5u, but idk if intended or oversight

**Comment by UrsulaMejor** [comment]
Seems intended
