### ISSUE TITLE
You can "pry up" broken vending machines and it works somehow

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#9178]
### Labels

[BUG]

### Description

The code that lets you pry up toppled vending machines also restores broken ones.

### Steps to reproduce

1. Break a vending machine (I don't know how you reliably accomplish this I just find broken vendors on the live server occasionally)
2. Use crowbar
3. Vending machine goes from fucked up to fixed??

### Expected Behavior

Being able to repair broken vendors is nice but maybe through an intentional method instead?

**Comment by swinglow20** [comment]
Archfiends can suck the power out of consoles until they break, which is probably what happened to that machine

**Comment by Nihisohel** [comment]
> Break a vending machine
id assume you would mean toppling over but it doesnt show the broken sprite as you say it does
i also tried to reproduce a broken vendor sprite state but shooting it doesnt even seem to work
broken vendors found in azones or the ones found in space diner doesnt appear to fix when a crowbar is used
i think arcfiends might reliably be the reproducer but ill check that out when i got time

**Comment by Sir-Mora** [comment]
unable to break vending machines besides knocking them over
