### ISSUE TITLE
You can scan ability buttons with the chameleon projector

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#9184]
### Labels

[minor]

### Description

Scanning an ability button allows you to chameleon project as said ability button

### Steps to reproduce

1. Have something like PDA light or superfart
2. Click the button while holding a chameleon projector.
3. Be superfart.

### Expected Behavior

To use the ability instead of scanning it.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/174230039-8898ba69-0571-49b4-a5ec-c7041aa0dab0.png)

**Comment by frawhst** [comment]
should probably get fixed eventually but I'm fine with this existing currently

**Comment by DimWhat** [comment]
> should probably get fixed eventually but I'm fine with this existing currently

Yeah not a high priority bug but a bug nontheless

**Comment by CaioFrancisco** [comment]
If you labeled this as a feature, I think nobody would truly care. It can be tied with something like splashing contents of beakers on the Map Vote button. But hey, on a technical level, this might be a open door for visual glitches.
