### ISSUE TITLE
You can scan grabs with the chameleon projector

### ISSUE THREAD

**Issue by DimWhat** [goonstation/goonstation#9186]
### Labels

[minor]

### Description

You can scan a grab and become a grab

### Steps to reproduce

1. Grab somebody with an empty hand
2. Click on the grab with a chameleon projector
3. Become a grab

### Expected Behavior

To not be able to scan a grab.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/40079883/174230505-2469a922-7c5c-41fd-be1e-f729fde733a0.png)

**Comment by TobleroneSwordfish** [comment]
only 23 more `isgrab` checks and we'll have fixed all the grab jank!
