### ISSUE TITLE
Invisible Banana Peels

### ISSUE THREAD

**Issue by MobiusStr1ptease** [goonstation/goonstation#92]
Description:
I'm not sure if this is an april fools' joke that's gone on for too long or if it's actually a bug.
Banana peels are currently invisible.
You can imagine how infuriating this must be.

To reproduce:
Eat a banana.
Watch the peel become invisible.
Slip on it.

**Comment by ZeWaka** [comment]
Due to recent produce resprite? @binarysudoku
