### ISSUE TITLE
Invisible doors in the Janitor/Rental Office Prefab

### ISSUE THREAD

**Issue by Munien7** [goonstation/goonstation#9224]
### Labels

[BUG]

### Description

The doors in the Janitor prefab are invisible but still function correctly

### Steps to reproduce

1. Go to janitor prefab
2. Walk into invisble doors and hear opening noise
3. Not see doors

### Expected Behavior

To be able to see doors

### Additional Information & Screenshots

![dreamseeker_OaaQZdHBxY](https://user-images.githubusercontent.com/99692679/174476525-3d167322-ce53-495e-8df3-ce37d810dbdc.png)

**Comment by Munien7** [comment]
On further inspection this seems to be the case in several areas including as the listening post, and what I am assuming what was mentioned in #9234

**Comment by nefarious6th** [comment]
related to #9236

**Comment by ZeWaka** [comment]
https://github.com/goonstation/goonstation/commit/e1d3998c4ba3301878875288242ac44f61b5eb3d
