### ISSUE TITLE
Cargo revenue split can create sub-credit amounts

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#9241]
### Labels

[minor]

### Description

The two-way split between scanned ID and cargo budget 

### Steps to reproduce

1. Have someone scan their ID in the QM barcode computer
2. Sell something for an uneven amount
3. Have half a credit in the cargo budget

### Expected Behavior

for the amounts to get rounded one way or another

### Additional Information & Screenshots

I don't know if the bank account also end up with half a credit in it, it wasn't mine.

**Comment by soleilan** [comment]
yup both cargo and qm get a .5 in their money, very cool
probably fix it by splitting in favor of NT or something?
