### ISSUE TITLE
Artifacts show 2 artifact types when on the ocean floor

### ISSUE THREAD

**Issue by TheRealMrN** [goonstation/goonstation#9305]
### Labels

[MINOR]

### Description

Artifacts have a second sprite of a wizard artifact on them when on the ocean floor

### Steps to reproduce

1. Have an artifact 
2. Place it on the ocean floor

### Expected Behavior

For the second sprite to not show

### Additional Information & Screenshots

Maybe because the admin turned the ocean into bourbon

![Screenshot_34](https://user-images.githubusercontent.com/100310349/175227303-3f8e6edb-b9e4-40b9-86cd-b2116357ecfd.png)

later found it it works on those 2 artifacts specifically
![Screenshot_36](https://user-images.githubusercontent.com/100310349/175228569-a02ef47c-9539-4e49-9e6e-06e12f665eea.png)

**Comment by frawhst** [comment]
Probably an issue with disguised artifacts and fluid overlays. I'd assume the fluid overlay is generating for the Actual artifact sprite rather than the Visible artifact sprite

**Comment by UrsulaMejor** [comment]
unable to reproduce
