### ISSUE TITLE
Medical Director doesn't start with Medic's Backpack

### ISSUE THREAD

**Issue by RenzDot** [goonstation/goonstation#9328]
### Labels

[BUG]

### Description

Medical Director doesn't start with Medical Backpack

### Steps to reproduce

1. Start round as Medical Director
Notice you start with grey backpack instead of medic's backpack

### Expected Behavior

MD Should start with Medic's Backpack, just like every other docter

### Additional Information & Screenshots

Roboticists, Docters and even geneticists have medical backpacks for RP
Only MD has a plain backpack, so has to raid a locker to obtain one

**Comment by ThatFiveGuys** [comment]
Not a bug, was intentional in order to better match there jumpsuit

**Comment by RenzDot** [comment]
> Not a bug, was intentional in order to better match there jumpsuit

Could you consider putting it in MD's locker?
Not all maps have the locker for medical backpacks
