### ISSUE TITLE
"Medical Uniform Locker" missing on Donut3

### ISSUE THREAD

**Issue by RenzDot** [goonstation/goonstation#9331]
### Labels

[BUG]

### Description

"Medical Uniform Locker" missing on Donut3

### Steps to reproduce

1. Start on Donut3

### Expected Behavior

Medical Uniform Locker exists on cog1, cog2, horizon, oshan... etc.
Not to be confused with Medical Clothing Locker

### Additional Information & Screenshots
![image](https://user-images.githubusercontent.com/42572753/175551880-7360e022-d507-453f-8d37-c60d0f2025fe.png)

**Comment by RenzDot** [comment]
Fixed as of today

**Comment by nefarious6th** [comment]
fixed by #9347

**Comment by Luxizzle** [comment]
Fixed by #9374
