### ISSUE TITLE
Plates dont break when smashed on people

### ISSUE THREAD

**Issue by Bartimeus973** [goonstation/goonstation#9338]
### Labels

[BUG] [Minor]

### Description

Plates do damage but dont shatter on hit

### Steps to reproduce

1. Grab a plate
2. Smash it on someone's head
3. It does damage and stun, causes shattered glass, but isnt broken and can be picked up to repeat step 2, leading to potential permastun, infinite shards, and more.

### Expected Behavior

Plates should shatter

**Comment by ThatFiveGuys** [comment]
Fixed
