### ISSUE TITLE
nukeops gear is back to not blocking sarin

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#9346]
### Labels

[BUG]

### Description

Like the old days, nukeops gear once again doesn't provide protection from sarin

### Steps to reproduce

1. look at the gear

### Expected Behavior

I expect the syndicate field mask to function in the manner that it was designed to function in.

### Additional Information & Screenshots

It could be intentional but I'd rather hope it's not.

**Comment by BatElite** [comment]
They're ahead of you -  #9343

**Comment by ThatFiveGuys** [comment]
Fixed by that pr linked
