### ISSUE TITLE
Spectating antag as AI kills you when they die

### ISSUE THREAD

**Issue by Redflame1022** [goonstation/goonstation#9359]
### Labels

[BUG]

### Description

Spectating (at least some) antags as AI kills you when they die

### Steps to reproduce

1. Be spectating an antag as the AI (for me it was the weird glowy purple thing for the void event)
2. Have the antag get killed while still spectating them (for me it was by an NTSO with a taser weapon)

### Expected Behavior

You should die

### Additional Information & Screenshots

After I died, it still showed that the core was alive, contacted an admin (Grifflez) to get it resolved.

**Comment by nefarious6th** [comment]
Related: #8580
