### ISSUE TITLE
Can't shoot with gun arm that has been twirled or juggled

### ISSUE THREAD

**Issue by prismfingers** [goonstation/goonstation#9373]
### Labels

[BUG]

### Description

Twirling or juggling an item arm can cause you to lose access to some of its functionality. Notably with in the case of a gun-arm, you can't fire at distant targets anymore.

### Steps to reproduce

1. Get a gun item arm through surgery.
2. *twirl it until you accidentally drop it or juggle if you're a clown.
3. The item has disappeared visually from your item arm's slot.
4. Attempt to fire at a nonadjacent target

### Expected Behavior

I shouldn't be able to drop or accidentally call upon dark powers to juggle something sutured onto my elbow.

### Additional Information & Screenshots

Examining yourself shows the item is still attached as your arm and can be retrieved normally through surgery.
Basic melee interactions still work: bashing with the item, pressing a gun's barrel to someone, point blank shots, etc
Special attacks specific to the item no longer seem to work.
Using the item in hand is no longer possible.

**Comment by ZWRh3** [comment]
reproduced
