### ISSUE TITLE
Chameleon Projector can scan UI buttons

### ISSUE THREAD

**Issue by Munien7** [goonstation/goonstation#9381]
### Labels

[BUG]

### Description

The chameleon projector can scan UI buttons.

### Steps to reproduce

1. Be a traitor
2. buy a chameleon projector
3. click on your Internals button or PDA light with it in hand
4. turn on the projector
5. be UI

### Expected Behavior

To not make yourself become UI

### Additional Information & Screenshots

![dreamseeker_8jMVJMd57j](https://user-images.githubusercontent.com/99692679/176345371-e727d1ea-9252-4c62-9da7-6f463c0ca823.gif)

**Comment by Merlin1230** [comment]
I wonder if this means it can also scan the map vote button considering thats an object...
