### ISSUE TITLE
Borg death by part damage tries to register a signal on the qdeleted mob

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#9387]
### Labels

[runtime]

### Description

The death alert code on borgs will try to register a radio component on a qdeleted mob if they die of a missing chest/head.

### Steps to reproduce

1. Be a borg
2. Die of chest damage (either bashing yourself or for a fun option, put yourself into the crematorium)
3. Get a runtime (or two when using the crematorium, see below)

### Expected Behavior

no runtimes 

### Additional Information & Screenshots

The runtime message is `Exception has occurred: Attempted to add a new component of type [/datum/component/packet_connected/radio] to a qdeleting parent of type [/mob/living/silicon/robot]!`

The first death gets called in robot_statusupdate (from the mob/living Life proc) due to the lack of a chest, and afterwards in the borg Life proc because of <0 health. Both seem to occur in the same cycle of the life loop.

In the crematorium this runtime happens twice: once when the borg dies of chest damage, and then again when the crematorium calls remove() on the borg

Suiciding seems to be fine

**Comment by UrsulaMejor** [comment]
unable to reproduce
