### ISSUE TITLE
Trick Telecrystals survive exploding

### ISSUE THREAD

**Issue by Cthucky** [goonstation/goonstation#9427]
### Labels

[BUG]

### Description

When you insert the trick telecrystals into a PDA, they explode, but they remain, intact, in your hand.  Inserting them again causes another explosion.

### Steps to reproduce

1. Be a traitor
2. Buy the trick whatever-they're-called-this-round.
3. Insert into PDA.
4. Repeat.

### Expected Behavior

Things that explode generally do not continue existing in their original, explosive form.

**Comment by MetricDuck** [comment]
So I *think* this is because you can click the uplink with the TC again after the first explosion but before the crystal qdels

**Comment by MetricDuck** [comment]
Actually strangely it seems to be qdel cant snatch the crystal out of your hand

**Comment by UrsulaMejor** [comment]
unable to reproduce
