### ISSUE TITLE
Shocking Assembly

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#943]
[BUG]

**Describe the bug**
Signaller/Prox Sensor Assembles shock people who pass by them, as far as i know this is not intended.

**To Reproduce**
1. build Signaller/Prox Sensor Assembly
2. activate
3. walk past it

**Expected behavior**
it really shouldnt shock people in my opinion, but thats just me

**Additional context**
this  isnt listed as what this sort of thing is supposed to do on the wiki.

**Comment by pali6** [comment]
Could be caused by doors using `usr` incorrectly maybe.

**Comment by Tarmunora** [comment]
@RSG250 could not reproduce with listed steps. Likely an issue with whatever you were triggering from the prox sensor (e.g.: a door maybe)
