### ISSUE TITLE
Borg mining update

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#948]
[BUG]

**Describe the bug**
The update "Borgs can now also automatically use their mining tools without having to click." appears not to work.

**To Reproduce**
1. Be borg
2. Choose mining module
3. Move into mining node.
4. Get no ore or message about ore.
5. Be sad.

**Expected behavior**
To mine ore like humans do by moving into it.

**Additional context**
Maybe a "hand" numbering issue like organs had etc? I dunno, not a coder.

**Comment by pali6** [comment]
@zjdtmkhzt

**Comment by pali6** [comment]
Actually the PR is probably correct, someone just accidentally reverted a ton of changes from the past two days.

**Comment by Tiggersaurus** [comment]
*squints in Borg*

**Comment by Tiggersaurus** [comment]
Confirmed this is now working again as intended.
