### ISSUE TITLE
Sprint bug

### ISSUE THREAD

**Issue by qrqwerqwr** [goonstation/goonstation#949]
[BUG]

**Describe the bug**
If you sprint while pushing an object this causes your stamina to regenerate instead of draining. While pushing an object does slow you down, the fact that your able to sprint forever negates this.

**To Reproduce**
1. Get a large object that can be pushed
2. Sprint while pushing it
3. Profit???

**Expected behavior**
I expect my stamina to go down faster than normal sprinting

**Comment by Tiggersaurus** [comment]
Related to the mining push change maybe? Code is wizardry so who knows *Pulls face*
