### ISSUE TITLE
Packet Sender Programs not sending packets

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#9498]
### Labels

[BUG]

### Description

Packet Sender Programs not sending packets

### Steps to reproduce

1. Using the Packet Sender program, write a simple key = value packet
2. Turn on Program-Building Mode
3. Save the packet as a button
4. Save the program
5. Open the program
6. Push the button

No packet is actually sent out. Tried with a different frequency, and could confirm that the wifi machinery wasn't receiving the packet I made. "Send Packet" button inside the Packet Sender program worked #1 though.

### Expected Behavior

A sent packet

### Additional Information & Screenshots

Here's a recording: https://files.catbox.moe/4lzrip.mp4

**Comment by SenExus** [comment]
I work with packets on the regular and my program just yesterday was working. Is this an issue that has followed you? Perhaps it could be an issue with allowing the user to change the frequency, as I never enable this on my programs. Nonetheless, I'll test this a little

**Comment by soleilan** [comment]
Closed, as #9619 is the actual issue here
