### ISSUE TITLE
Ghostdrones can't use APCs

### ISSUE THREAD

**Issue by BatElite** [goonstation/goonstation#9574]
### Labels

[BUG]

### Description

As title.

### Steps to reproduce

1. Be a ghostdrone
2. Open APC UI
3. Be unable to do anything

### Expected Behavior

For the UI to work, drones have reasons to use em

**Comment by CaioFrancisco** [comment]
Intentional. Any kind of interface gets completely greyed out to a Ghostdrone, even stuff like door wires.

**Comment by amylizzle** [comment]
![image](https://user-images.githubusercontent.com/3855802/178273998-cb817a9a-ae11-4b94-ae07-0dcb39666d63.png)
intentional

**Comment by BatElite** [comment]
Ghostdrones and ghost critters are different things

As for Caio's comment, that seems like an overbearing implementation then. There might not be much they need to interact with, but fixing APCs and door wires definitely fall under repairing.
