### ISSUE TITLE
BIG SERVER KILLING LAG (it probably wasnt the cause but still it should really cook instead of make the paper char)

### ISSUE THREAD

**Issue by RSG250** [goonstation/goonstation#958]
[BUG]

**Describe the bug**
ok so nuggets from the loafer that have paper in them, if the paper inside turns to ash and then you eat the nugget, it make the big lag, eat a shit ton all at once.

**To Reproduce**
1. make nuggets using thermal printer at loafer
2.make a lot
3. throw welder under them expecting them to cook
4. THE PAPER CHARS X102
5. EAT A SHIT TON ALL AT ONCE
6. OH NO WHAT HAVE I DONE.

**Expected behavior**
i expect the server to not fucking die. also that the nuggets get cooked from the welder like donks

**Screenshots**

![image](https://user-images.githubusercontent.com/63602513/83905643-0ad19e80-a730-11ea-9ae3-5c5adb8ed819.png)

**Comment by pali6** [comment]
This wasn't the cause of the lag and I fixed a bug that was likely responsible for the absurd amount of nuggets.
