### ISSUE TITLE
Flock abilities don't go away when observing as ghost

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#9588]
### Labels

[BUG]

### Description

Flock ability buttons seem to be persistent if you respawn under some conditions

### Steps to reproduce

1. Observe flockdrone
2. respawn as mentor mouse while/after observing (I think I pressed the button, clicked on drone, then pressed yes but I wasn't paying particularly much attention)
3. ability bar remains constant as mentor mouse
4. ghostize and bar is still there

### Expected Behavior

I expect there to be only the ghost hud after pressing the funny button

### Additional Information & Screenshots

For what it's worth I respawned as mentor mouse immediately after leaving a flockdrone so that might have something to do with it. Apologies if it's unreplicable.
![image](https://user-images.githubusercontent.com/96703882/178395872-afa7aff9-9fae-43cc-b9d9-4a7fe2317391.png)

**Comment by TobleroneSwordfish** [comment]
I knew my abilityHolder crimes would have consequences aaa
