### ISSUE TITLE
AMDLs (Automatic Mass Driver Loaders) and Mass drivers activated by AI camera

### ISSUE THREAD

**Issue by qrqwerqwr** [goonstation/goonstation#959]
[BUG]

**Describe the bug**
It appears that the AI camera that flies around can activate AMDLs (Automatic Mass Driver Loaders) and mass drivers. I didn't spawn as an AI, I became one, so maybe that has something to do with it.

**To Reproduce**
1. Be an AI
2. Hover over an  AMDLs (Automatic Mass Driver Loaders) or mass driver with your camera
3. It should activate

**Expected behavior**
I don't believe a non-physical entity should activate it.

**Additional context**
May only trigger if you were made an AI and didn't spawn as one

**Comment by trerri** [comment]
Maybe you don't mean mass drivers but AMDLs (Automatic Mass Driver Loaders). Mass drivers don't fire when interacting with the Aeye I think
