### ISSUE TITLE
Flock relay resets shuttle timer

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#9593]
### Labels

[BUG]

### Description

Detonating a second flock relay while the shuttle is still coming from the first will reset the shuttle time to 3 minutes.

### Steps to reproduce

1. Construct two flock relays one after the other
2. Let one explode and call the shuttle
3. The second one explodes and sets the shuttle timer back to 3 minutes

### Expected Behavior

I expected it to not teleport the shuttle back to centcom

**Comment by FlameArrow57** [comment]
Can be closed I think?

**Comment by TobleroneSwordfish** [comment]
👍
