### ISSUE TITLE
Borg meson upgrade not working

### ISSUE THREAD

**Issue by Tiggersaurus** [goonstation/goonstation#961]
[BUG]

**Describe the bug**
When using the borg meson goggles upgrade, you see darkness instead of seeing through walls/into asteroids.

**To Reproduce**

    1. equip goggles upgrade
    2. look at asteriod
    3. see pitch black in it
    See error

**Expected behavior**
For them to function as intended.

**Comment by MarkNais** [comment]
Guess @pali6 's change in #844 wasn't sufficient :(

**Comment by Tiggersaurus** [comment]
Or duplicate code coz borg just *have* to be special and difficult :)
