### ISSUE TITLE
Ambient tracks break when moving directly between areas with different non-null sound_group values

### ISSUE THREAD

**Issue by Sovexe** [goonstation/goonstation#963]
**Describe the bug**
If passing from an area with a defined sound_group into an area with a different sound_group the ambient track will attempt to swap playing a very brief clip of the new ambiance before stopping entirely. Walking back and forth over between the area will cause the brief clip to repeat (it can be very hard to hear on some tracks, easily noticeable if using louder ones).

However if a transition area with a null sound_group is placed between them the ambient tracks will play as normally when moving between the areas.

Ambient noise is handled by `Entered(var/atom/movable/A, atom/oldloc)` of `/area`

**To Reproduce**
1. Place two areas with two different sound_group values and the desired sound_loop adjacently
2. Enter one of the areas, the ambient music plays normally
3. Move to the second area, music halts, you hear a very brief clip of the second area
4. Move back to the original area, hear another brief clip, ambiance remains broken

**Expected behavior**
Ambient noise plays correctly when moving between areas

**Comment by ZeWaka** [comment]
Should be fixed by 898e2e3b.
