### ISSUE TITLE
thralled spies cant use spy PDA

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#9649]
### Labels

[BUG][MAJOR]

### Description

thralling changes the victims special_role to ROLE_VAMPTHRALL this fucks up stuff tied to special_role such as spy PDA

### Steps to reproduce

1. be a spy
2. get thralled
3. try to claim any reward using your PDA

### Expected Behavior

being able to use your uplink as a thralled spy

### Additional Information & Screenshots

checks related to special_role tend to be quite bad often as you can only have one special role despite stuff like thralled spies being possible

**Comment by nefarious6th** [comment]
duplicate of #9110
