### ISSUE TITLE
soulsteel bypasses dnr

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#9657]
### Labels

[BUG][MINOR]

### Description

same as tittle, DNR ghosts can be forced to posses stuff

### Steps to reproduce

1. drop sousteel stuff on ground
2. die
3. set dnr
4. move over it a few times
5. possessing a soulsteel item with dnr set

### Expected Behavior

not that

**Comment by frawhst** [comment]
I don't think DNR really applies to being a floating toolbox
