### ISSUE TITLE
Inaccessible bar notice board on Donut3

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#9665]
### Labels

[BUG]

### Description

The persistent notice board in the bar cannot be interacted with without using a deconstructing device

### Steps to reproduce

1. Load into a game on Donut3
2. Go behind the bar
3. Click on the notice board, to either read a note or place a new one
4. Be unable to, because the chemical heater, reagent extractor, and ChemMaster are in the way, even though some other wall-mounted objects can be used despite being behind similar objects

### Expected Behavior

I expected to be able to read the bar’s persistent notice board.

### Additional Information & Screenshots

I was playing as a cyborg at the time, but that really shouldn’t prevent me from being able to read a bulletin board.

**Comment by t-toasted** [comment]
Tested. Cyborgs can't access notice boards in any way, it seems, even to read. Sorry
