### ISSUE TITLE
Soulguard removes wizard abilities upon respawn.

### ISSUE THREAD

**Issue by HBS-System** [goonstation/goonstation#9708]
### Labels

[BUG] [Major]

### Description

Soulguard respawns you with no abilities.

### Steps to reproduce

1. Get Soulguard, and any spell set of your choice.
2. Die, and watch as your skills magically cease to exist!

### Expected Behavior

I expect abilities to stay persistent after the activation of soulguard.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/34522718/179379320-87ee10e0-9f25-4a55-8856-474cdbae04b7.png)

**Comment by Ilysen** [comment]
I can state that this is hopefully __not__ caused by #9366 - the bug appears to be present on commit 746ca44, which is the commit *before* the merge commit for that PR.
