### ISSUE TITLE
living prison artifacts keep your hands full even after you've left

### ISSUE THREAD

**Issue by wolfolotl** [goonstation/goonstation#9713]
### Labels

[BUG] [MAJOR]

### Description

"living [artifact name]"-variant prison artifacts leave behind invisible, undroppable items of the same name as the artifact in your hands after they've returned you to your body. when this happens you basically have to ahelp or you lose the ability to use that hand

### Steps to reproduce

1. smack an artifact with your bare hands
2. it's a prison artifact that comes to life once you're inside
3. leave the prison artifact once the duration is up
4. try to interact with someone with what you think is an empty hand
5. hit it instead
6. mouse over that hand slot to see "pulpy bulk" and no item icon
7. scream

### Expected Behavior

for it to not put bugged items in my hands, or for any undroppable items put in my hands to be an obvious, intentional side effect

### Additional Information & Screenshots

I was playing a character with the kleptomaniac trait, I'm not sure if that affected anything

**Comment by soleilan** [comment]
unable to reproduce after lengthy testing, with and without klepto
