### ISSUE TITLE
White discount saber's activated inhand sprite is invisible.

### ISSUE THREAD

**Issue by Gerhazo** [goonstation/goonstation#973]
**Describe the bug**
White discount saber's inhand sprite is invisible.

**To Reproduce**
1. Acquire a white colored /obj/item/sword/discount
2. Turn it on.
3. The turning on sound plays, a light is generated but the sword inhand is not visible.

**Expected behavior**
The sword is visible.

**Additional context**
Very likely a mis-named icon_state in either code or the .dmi file. Probably just need to check both and correct the discrepancy.
The inhand image's icon_state currently on live servers for the bugged white d-saber is "d_sword1-W-R". An example one for a purple one is "d_sword1-P-R".

**Comment by Adharainspace** [comment]
looks like the white d saber and the pink d saber iconstates are completely mixing, will fix
