### ISSUE TITLE
Destiny has a roundstart spawn which is impossible to escape without help

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#9733]
### Labels

[BUG]

### Description

Roundstart spawned as a staffie on destiny. Found out I spawned in a spot I can't escape without tools / help.

### Steps to reproduce

1. Roundstart spawn as staffie
2. Spawn on the benches south of the pool
3. Realize you can't escape
4. cri.
5. Tableslam a stray monkey to shatter the table to escape

### Expected Behavior

I expect not to spawn in a spot I can't escape.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/84296283/179432973-af7eae06-e93c-47f3-b740-ee81ecee4683.png)

**Comment by blackrep** [comment]
Forgot you can technically escape it by spam putting stuff on / off a table. However still not really an ideal spawn location. Especially for new players who don't know that trick.

**Comment by nefarious6th** [comment]
Smh, it was meant for staffie containment

Will fix some time this week

**Comment by blackrep** [comment]
> Smh, it was meant for staffie containment

I will never be caged

**Comment by BatElite** [comment]
I think you've got access to the chute on the right for the time being

Really feels like the south end of pools should be impassable on the north edge only
