### ISSUE TITLE
Hair dye doesn't dye all layers

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#9756]
### Labels

[BUG][minor]

### Description

The hair dye doesn't affect all the hair layers

### Steps to reproduce

1. have hair color A
2. Dye hair different color
3. Witness fashion disaster

### Expected Behavior

I expect to not have 1 dark layer and 2 pink

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/179827368-d672519f-1ea7-4264-8dca-b2eb65afaa1f.png)

**Comment by nefarious6th** [comment]
Obscure mechanic time: was this after cycling through the layer options with the dye bottle in hand by pressing C until you got the one that said "you will now target the recipient's entire coiffure"?
