### ISSUE TITLE
Sleeper agents don't have traitor icon

### ISSUE THREAD

**Issue by flrsh** [goonstation/goonstation#9771]
### Labels

[BUG]

### Description

Sleeper agents (who spawn midround) don't get the red T icon 

### Steps to reproduce

1. Be an admin
2. Observe a sleeper agent
3. See that they don't have the red T icon

### Expected Behavior

I expect sleeper agents to have the red T icon.

### Additional Information & Screenshots

Related to recent backend refactor of our antag / gamemode system.

**Comment by Ilysen** [comment]
Shouldn't be too hard to fix up - I'll see what I can do.

**Comment by flappybatpal** [comment]
Made a really lazy fix that adds them back to ticker.mode.traitors
https://github.com/goonstation/goonstation/commit/b30ffad13d43ec0e065a8924b80a1a376687386d

**Comment by Ilysen** [comment]
It'll do for now, I suppose

**Comment by ThatFiveGuys** [comment]
Fixed
