### ISSUE TITLE
Security flashbangs (and all flashbangs) are useless

### ISSUE THREAD

**Issue by MylieDaniels** [goonstation/goonstation#9787]
### Labels

[BUG][BALANCE]

### Description

Security flashbangs (and all flashbangs) have been nerfed to uselessness, because the sonic and flash powder changes are so overwhelmingly large that you can hold a pair of active flashbangs in your hands and still dance away from security after they go off.

### Steps to reproduce

1. Activate a security flashbang.
2. Hold it in your hand.
3. Laugh as it consumes half your stamina and makes you disoriented for 8 seconds.
4. Question why flash and sonic powder were nerfed this badly.
5. (optional) activate an entire box of sec flashbangs, observe that the cooldowns on flash/sonic powder prevent all but the first from working.

### Expected Behavior

I expect holding a flashbang going off in my palm to do something substantial.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/25803648/180253969-0449e4ec-65fc-4ecd-8555-e6c86738802f.png)

**Comment by ThatFiveGuys** [comment]
Not a bug, please use the forums for balance suggestions

**Comment by Josephin23** [comment]
heavily cringe ngl
