### ISSUE TITLE
Mining map highlights nearly everything

### ISSUE THREAD

**Issue by blackrep** [goonstation/goonstation#9800]
### Labels

[BUG]

### Description

The mining map for some reason highlights almost everything in red. This is a regression from when it'd only highlight man-made structures.

### Steps to reproduce

1. Load into a round
2. Open the mining map
3. Open your PDA mining map
4. Visible confusion

### Expected Behavior

I expect the mining map to only highlight man-made structures (prefabs)

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/84296283/180369860-5d2b5186-d618-403c-af14-c922813e2e36.png)

**Comment by BatElite** [comment]
What's going on with this bug:

#9743 has the side-effect that the majority of asteroid turfs are now made of steel.

The map making algorithm (starting /code/datums/controllers/sea_hotspot_controls.dm line 53) largely operates on comparing turf names, and "steel asteroid" doesn't match.

The grey mottling is that not every asteroid tile is actually steel, I don't know why that's the case though.
