### ISSUE TITLE
AI can see action bars in areas that are not in camera view.

### ISSUE THREAD

**Issue by ThatFiveGuys** [goonstation/goonstation#9802]
**Description**
If someone is mopping in an area without camera coverage, the AI can see the action bar for mopping in that area anyways.

**Steps to reproduce**
1. Have someone doing something that causes an action bar in an area without camera coverage
2. Be an AI
3. See the action bar despite not being able to see the action that's happening.

**Expected behavior**
Action bar to not be visible

**Comment by TealSeer** [comment]
Fixed in https://github.com/goonstation/goonstation/commit/a1709a30395d1bdb51b024d9776a9d7754171136
