### ISSUE TITLE
Skeletons don’t bleed calcium sometimes

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#9804]
### Labels

[BUG]

### Description

Skeletons make normal blood instead of calcium when throwing their detached head

### Steps to reproduce

1. Enter round as skeleton
2. Detach head with wrench and crowbar and wrench again
3. Throw your head at the floor
4. Why did my head make a puddle of red human blood?

### Expected Behavior

I expected there to be either no blood at all or a puddle of calcium, since that’s what skellies bleed usually.

**Comment by ZeWaka** [comment]
probly fixed
