### ISSUE TITLE
Suiciding via firelock as a skeleton with no head can create infinite meat

### ISSUE THREAD

**Issue by muzcl** [goonstation/goonstation#9816]
### Labels

[BUG] [MINOR]

### Description

If you take your head off as a skeleton, use the suicide command and pick firelock, a chef can use the gibs created to get strange meat at no cost to the skeleton suiciding. Repeat this, and you have infinite meat.

### Steps to reproduce

1. Have Ossification mutation or Skeleton trait
2. Take your head off with a wrench and crowbar
3. Use the suicide command and pick firelock
4. Have a chef harvest the gibs spawned by suiciding
5. Repeat this, and you can have infinite meat

### Expected Behavior

Skeleton shouldn't be able to suicide with a firelock without a head, or gibs should not spawn from it

**Comment by muzcl** [comment]
its pretty funny, but a bugs a bug i guess

**Comment by TheTyrant25** [comment]
cannot reproduce
