### ISSUE TITLE
Trying to put a box into a toolbox no longer works

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#9818]
### Labels

[BUG][minor]

### Description

it no work :(

### Steps to reproduce

1. Find a box
2. Find a toolbox
3. Attempt to place one into the other
4. Fail

### Expected Behavior

Toolboxes should be able to hold normal sized items, no?

### Additional Information & Screenshots

It doesn't give a "you can't do this message", or display anything about attacking the toolbox with the box, it just does nothing. Unless toolboxes got nerfed I dont think this should be the case

**Comment by Wisemonster** [comment]
Gotta use non-help intent to put the box into the tool box

**Comment by UrsulaMejor** [comment]
unable to reproduce
