### ISSUE TITLE
You can make someone horizontal while standing up by couchbuckling them

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#9819]
### Labels

[BUG]

### Description

Dunno how but it's pretty funny

### Steps to reproduce

1. Aggressive grab a friend
2. Have them lay down 
3. Walk them over to a couch and buckle them into it
4. Drop them
5. Have them stand up, and then unbuckle
6. See that they don't right themselves

### Expected Behavior

They should look like they stand up when they press the = sign again

### Additional Information & Screenshots
Was able to recreate it twice with help of a monkey and the mime
![image](https://user-images.githubusercontent.com/96703882/180608279-7c33c6ff-3d28-4ded-aa15-b38966f4dc7b.png)
The sprite issue can be fixed by laying down and standing up again

**Comment by Tarmunora** [comment]
https://github.com/goonstation/goonstation/commit/9a0e9ea5dd77dbf24de7ca0c8da92fe67132046c
