### ISSUE TITLE
Sawflies and cluster sawflies cost 0.1 material

### ISSUE THREAD

**Issue by NightmareChamillian** [goonstation/goonstation#9846]
### Labels

[BUG]

### Description

Since I used the [is_syndicate] = true they can be syndie scanned but use default materials. This isn't good.

### Steps to reproduce

1. Syndicate scan a sawfly
2. Mass produce it
3. Invade half the station

### Expected Behavior

They should have balanced materials.

### Additional Information & Screenshots

![image](https://user-images.githubusercontent.com/96703882/180651806-26d4ec57-ca89-4b7a-b623-4d660c416d0f.png)
![image](https://user-images.githubusercontent.com/96703882/180651821-44d2267d-9cd3-43b2-9455-917727ee92df.png)
As much as I do love chaos this isn't balanced. Opening this bug for tracking's sake.

**Comment by flappybatpal** [comment]
Put in a higher cost for the moment.
