### ISSUE TITLE
Zoldorf dies due to code oversight

### ISSUE THREAD

**Issue by Roninnozlo** [goonstation/goonstation#9869]
### Labels

[BUG]

### Description

Zoldorf players can die due to a code oversight

### Steps to reproduce

1. Spawn into a round
2. Hack Zoldorf fortune machine
3. Buy burrito, unroll burrito into scroll, sign with a pen (your blood)
4. Insert signed burrito into Zoldorf machine to play as Zoldorf
5. Use a fortune to brand someone
6. Use Astral Projection to observe the branded person
7. Branded person dies and gets cloned
8. _You observe the corpse instead of the clone??_
9. Cloned person **puts corpse you’re observing into enzymatic reclaimer**
10. _**When the enzymatic reclaimer is turned on, you die.**_

### Expected Behavior

I expected to just be ejected back into the zoldorf machine, not die completely and leave Zoldorf inert for the rest of the round.

**Comment by Roninnozlo** [comment]
Goon3, Oshan lab

**Comment by nefarious6th** [comment]
ah. 

related: #8580 and #9359
