### ISSUE TITLE
Waiters spawn holding serving tray in one hand

### ISSUE THREAD

**Issue by Conchuckter** [goonstation/goonstation#9871]
### Labels

[BUG - TRIVIAL]

### Description

When someone spawns as a waiter they spawn holding their serving tray in a single hand instead of both.

### Steps to reproduce

1. Late join as waiter
2. Spawn

### Expected Behavior

Waiters should spawn holding the tray with both hands

**Comment by UrsulaMejor** [comment]
unable to reproduce
