### ISSUE TITLE
Flock structures don't get hit by melee special attacks

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#9895]
### Labels

[BUG]

### Description

^

### Steps to reproduce

1. Use a melee special attack on a flock structure or cage
2. See it not hit
3. Get consumed by the flock

### Expected Behavior

They probably should

**Comment by FlameArrow57** [comment]
Is this a bug? Don't think any other object can be attacked by special attacks, if that's intended
