### ISSUE TITLE
Quantum Plate Duplication

### ISSUE THREAD

**Issue by muzcl** [goonstation/goonstation#9914]
### Labels

[BUG]

### Description

Throwing a breakable object over a kitchen island or any other movable table causes a spinning clone of the thrown item to be recreated when the table is moved, allowing for infinite glass and possibly infinite food.

### Steps to reproduce

1. Get a kitchen island
2. Throw a plate over it
3. Move the kitchen island
4. Thrown plate reappears unbroken and able to be reused

### Expected Behavior

Plate should be broken forever and should not reappear on the moving table

### Additional Information & Screenshots

There are other ways to abuse this such as making fractals out of food items and quantum plates, and possibly food duplication, but I'm not completely sure on how those are achieved.
The reason I called it Quantum Plate Duplication is because you can use the glass shards created by smashing the plate to make more plates, and then create more quantum plates.

**Comment by HBS-System** [comment]
This is a new way to cause a thought to be fixed bug! Plate code is truly cursed.

**Comment by HBS-System** [comment]
New discovery, this bug is not isolated to the Kitchen Island, I have recreated this using a surgical tray, so I assume all tables you can move will experience this bug when a plate is thrown at it.

**Comment by frawhst** [comment]
fixed in a few ways
