### ISSUE TITLE
While skating, Oshan walls are sometimes lethal and sometimes not when bouncing off them

### ISSUE THREAD

**Issue by Garash2k** [goonstation/goonstation#9951]
### Labels

[BUG]

### Description

Oshan walls are inconsistent while skating

### Steps to reproduce

1. Acquire max skateboard speed
2. Inevitably skate off oshan
3. Skate into an outer wall

The first time around, skating off a northern wall, (don't remember the precise location/thickness of it,) it bounced me off back to the station.
The 2nd time, I sorta went through this wall and it killed me without leaving a corpse behind
![image](https://user-images.githubusercontent.com/6396368/181817090-e2bd47a8-6c38-446e-b279-4894495b5e89.png)

### Expected Behavior

Walls should act in a consistant manner

**Comment by ZeWaka** [comment]
not really fixable
