### ISSUE TITLE
Unable to get infusion-based gene strains.

### ISSUE THREAD

**Issue by avimour** [goonstation/goonstation#9953]
### Labels

[BUG]

### Description

Infusions don't give gene strains when they should.

### Steps to reproduce

1. Grab either ammonia, unstable mutagen, or space fungus. Get a lot.
2. Infuse it a lot.
3. Notice the seeds never gain the strain.

### Expected Behavior

Expect it to be possible to get the gene strain, not impossible.

### Additional Information & Screenshots

I tested over 20 seeds and infused over 1000 units of ammonia. I then performed two tests of 5 seeds and infusing with 600 units of unstable mutagen and space fungus. Neither tests were I able to get the gene strain associated with the infusing chem. 
I've also spent a lot of time in botany, and have done a lot of infusions of ammonia, unstable mutagen, and space fungus. 
I can't recall a time I've seen any of these genes get added to the plants via infusing.

**Comment by Gerhazo** [comment]
might be related/same to #9943, said issue has an associated runtime error described.

**Comment by avimour** [comment]
fixed with #10801!
