### ISSUE TITLE
donut 2 listening outpost walls are simulated

### ISSUE THREAD

**Issue by ZWRh3** [goonstation/goonstation#9961]
### Labels

[MAJOR]

### Description

same as title, can be broken

### Steps to reproduce

1. go to listening post
2. literally deconstruct your way in

### Expected Behavior

be unsimmulated

### Additional Information & Screenshots

havent tested in game but saw it be simmed in strongdmm unlike other maps

**Comment by Sord213** [comment]
Resolved
