### ISSUE TITLE
Enzymatic reclaimer on donut 2 doesn't work

### ISSUE THREAD

**Issue by Zamazenta** [goonstation/goonstation#9967]
### Labels

[BUG]

### Description

The reclaimer in donut 2 refuses to link with the rest of the cloner, so it just fills up with biomass that is unusable.

### Steps to reproduce

1. Run out of biomass on donut 2
2. Reclaim a body
3. See issue

### Expected Behavior

I expect that the biomatter from the reclaimer will actually be usable.

### Additional Information & Screenshots

Honestly I knew about this for over a year but for some reason I was certain there was already an issue posted about it. There was also a donut 2 change made right as I am posting this so it may have just gotten fixed right now.

**Comment by Sord213** [comment]
Resolved
