### ISSUE TITLE
Donut 2 shuttles are very broken

### ISSUE THREAD

**Issue by TobleroneSwordfish** [goonstation/goonstation#9968]
### Labels

[BUG]

### Description

The science outpost shuttle loses all walls and floors once used more than once and the escape shuttle seems to take the entire station z level with it.

### Steps to reproduce

1. Use the donut 2 science outpost shuttle
2. Use the donut 2 escape shuttle

### Expected Behavior

I expected floors to exist

**Comment by ThatFiveGuys** [comment]
Issue with all shuttles, science outpost shuttle just gets used a lot apparently

**Comment by Sord213** [comment]
Relevant runtime error

>  Summary
This runtime has occurred undefined times.


File null 
Line null 
Error Maximum recursion level reached (perhaps there is an infinite loop) To avoid this safety check, set world.loop_checks=0. 

 Description
proc name: get all mobs in (/proc/get_all_mobs_in)

**Comment by TealSeer** [comment]
Could not reproduce, most likely fixed at some point
