### ISSUE TITLE
Science department on donut2 has no spare equipment lockers

### ISSUE THREAD

**Issue by Luxizzle** [goonstation/goonstation#9971]
### Labels

[BUG]

### Description

Science department on donut2 has no spare equipment lockers

### Steps to reproduce

1. Die and body is unrecoverable
2. Try to get new gear after getting an ID
3. You're unable to get new gear as there are no spare equipment lockers.

### Expected Behavior

There are spare equipment lockers.

**Comment by Sord213** [comment]
Resolved
