### ISSUE TITLE
Overlay of syringe "inject" / "draw" was visible when item was dropped by a slipping clown.

### ISSUE THREAD

**Issue by Luxizzle** [goonstation/goonstation#9974]
### Labels

[BUG]

### Description

Overlay of syringe "inject" / "draw" was visible when item was dropped by a slipping clown.

### Steps to reproduce

1. Clown slips
2. Drops syringe
3. Overlay was visible

### Expected Behavior

Not seeing the overlay

### Additional Information & Screenshots

![dreamseeker_CdCeeOM7WR](https://user-images.githubusercontent.com/14966486/181936885-6fd71b21-6b0c-47bb-b0bd-333793987cf2.png)

**Comment by UrsulaMejor** [comment]
unable to replicate
