### ISSUE TITLE
Pug Fur color is randomized at all times, and/or doesn't display correctly on Setup.

### ISSUE THREAD

**Issue by Obengrad** [goonstation/goonstation#9978]
### Labels

[BUG]

### Description

The Pug's fur color is randomized both in the character setup and in-game when first joining a round.

### Steps to reproduce

1. Open character setup and select "Pug" species trait.
1.5 (Optional) Use smaller arrows on the skin tone option to see the how radically and randomly it changes.
2. Find a color that is desirable, save, then join round as character.
3. See that the color is, most likely, different than what was selected.

### Expected Behavior

I expected the fur to stay constant with each round according to what I select, and for the setup to display selected fur color properly.

**Comment by trazodont** [comment]
Pugs have a special option for fur color specifically in the appearance menu. Open the appearance menu with your pug character and look at the option "special style".

**Comment by Obengrad** [comment]
WELP.
I am the fool
